### ISSUE TITLE
Support for multiline YAML statements

### ISSUE THREAD

**Issue by zanona** [Shippable/support#1003]
One cool thing about YAML is the ability to add multiline strings as parameter values.
Unfortunately, it seems Shippable currently does not support it.
If you guys could implement this, it would great for improving config file management and readability as well.

For example:
```yaml
after_script: …
after_success: |
  if [ "$BRANCH" == "master" ]
      then rsync -azP --exclude=node_modules --del "$OUTPUT_DIR/" "$SSH:api"
      ssh "$SSH" "forever restartall"
  fi  
```

**Comment by manishas** [comment]
Thanks for the suggestion. We'll definitely keep this in mind as we implement new features.

**Comment by mbrodala** [comment]
@zanona It kind of works if you make sure to end all statements with a `;` (semicolon). We are using something like this which works fine:

```yaml
after_success:
  - >
    if [[ "$BRANCH" != "master" ]]; then
      command1;
      command2;
    fi;
```

**Comment by manishas** [comment]
This is not on our roadmap, and has a workaround. Closing.

**Comment by milesjordan** [comment]
Wondering if this has finally made it onto the roadmap? The workaround is actually fairly misleading, when you consider that to pass a build you want all commands to complete successfully. Using the stated workaround the build phase will pass if the final statement returns 0. If any previous statement fails, it would be ignored, so the whole build would be invalid but you might never know, and you could deploy something not properly tested. Implementing this the way YAML was intended would be a big improvement.

**Comment by ttrahan** [comment]
We use the [js-yaml parser](https://github.com/nodeca/js-yaml), which supports multiline yaml.  For the example above, try indenting the multiline commands further, as the multiline strings must be indented from the key.

For instance, this yaml block in a shippable.jobs.yml file doesn't pass the parser:
```yaml
jobs:
  - name: test
    steps:
    - IN: test1
    - TASK:
      - script: >
        export 
        IMAGE_REPO=$DOCKER_IMG_SOURCENAME
        IMAGE_TAG=$DOCKER_IMG_VERSIONNAME
```

While this one does:
```yaml
jobs:
  - name: test
    steps:
    - IN: test1
    - TASK:
      - script: >
          export 
          IMAGE_REPO=$DOCKER_IMG_SOURCENAME
          IMAGE_TAG=$DOCKER_IMG_VERSIONNAME
```
