### ISSUE TITLE
NPM dependencies not being cached

### ISSUE THREAD

**Issue by zanona** [Shippable/support#1005]
With `cache:true` defined on `shippable.yml` file I got the positive response at the end of the build after installing npm dependencies, etc.

```
caching_image ✓ 12 seconds
Docker cache 549295d7d46935d5fbc086e4
caching container...
successfully cached container
```

After changing `shippable.yml` to include the part below and pushing it:

```yml
before_install:
  - npm config get cache
  - ls "$(npm config get cache)"
```

the following errors comes in, meaning that the dependencies were not cached:

```
before_install ✗
npm config get cache
/home/shippable/.npm
ls "$(npm config get cache)"
ls: cannot access /home/shippable/.npm: No such file or directory
Stopping services
```
#### shippable.yml before change:
```yml
language: node_js
cache: true
before_install:
  - npm install -g npm@next
install: npm install --production
script:  npm run build
after_success: 
  - npm run deploy
  - npm config get cache
  - ls "$(npm config get cache)" #properly output with all dependencies
```

#### shippable.yml file after change:
```yml
language: node_js
cache: true
before_install:
  - npm config get cache
  - ls "$(npm config get cache)" #error no directory
  - npm install -g npm@next
install: npm install --production
script:  npm run build
after_success: npm run deploy
```

How can this be?
