### ISSUE TITLE
rvm failed to install ruby 2.0

### ISSUE THREAD

**Issue by godfat** [Shippable/support#1007]
Because `2.0` is treated as `2`, and rvm didn't understand `2`.

    rvm install 2 --verify-downloads 1
    Unrecognized command line argument: '2' ( see: 'rvm usage' )

With the following config:

``` yaml
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby

install: 'bundle install --retry=3'
script: 'ruby -r bundler/setup -S rake test'
```

I know that a workaround would be fixing my YAML,
but it would be great that if this could be fixed on CI,
because I have a number of repositories and I don't
really want to fix all of them one by one.

Those should always be treated as strings anyway.

Thanks!
