### ISSUE TITLE
Tests running twice...

### ISSUE THREAD

**Issue by luigi7up** [Shippable/support#1020]
Hi guys, 

I've just noticed that all my tests are running 2 times e.g. https://app.shippable.com/builds/54ce0db29c08c40d00304c31

output in __console ->script -> rake__ says:

```
rm -rf shippable/testresults
/home/shippable/.rvm/rubies/ruby-2.1.3/bin/ruby -I/home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-core-3.1.2/lib:/home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-support-3.1.0/lib /home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-core-3.1.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options:
  include {:focus=>true}
  exclude {:broken=>true}
....
Finished in 10 minutes 11 seconds (files took 22.23 seconds to load)
178 examples, 0 failures, 22 pending


/home/shippable/.rvm/rubies/ruby-2.1.3/bin/ruby -I/home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-core-3.1.2/lib:/home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-support-3.1.0/lib /home/shippable/.rvm/gems/ruby-2.1.3@[my-gemset]/gems/rspec-core-3.1.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options:
  include {:focus=>true}
  exclude {:broken=>true}
....
Finished in 7 minutes 5 seconds (files took 28.34 seconds to load)
178 examples, 0 failures, 22 pending
```

shippable.yml

```
language: ruby
rvm:
  - 2.1.3
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CAPYBARA_PAGE_PATH=shippable/capybara
archive: true

# if a commit has this: [reset_minion] - will reset the cached container and start over for that build  on a pristine environment
# http://blog.shippable.com/faster-builds-with-cached-containers
cache: true

services:
  - selenium
  # - memcached
  # - redis

addons:
  postgresql: '9.3'
  firefox: "31.0"
  selenium: "2.43"
before_install:
   - rvm rvmrc trust .
before_script:
   # ensure the test output and coverage dirs are created
   - "export DISPLAY=:99.0"
   - "/etc/init.d/xvfb start"
   - mkdir -p shippable/testresults
   - cp config/database.yml.shippable config/database.yml
   # - psql -c 'create database "ria_test";' -U postgres
   - rake db:create RAILS_ENV=test
   - rake db:schema:load RAILS_ENV=test
after_script:
  - "/etc/init.d/xvfb stop"
```

I have something setup wrong, but I have no clue what might be causing this.

Thank you
