### ISSUE TITLE
Build failed without errors, as well tests not verbose 

### ISSUE THREAD

**Issue by pilot** [Shippable/support#103]
How to see a verbose info in the console how tests is run? 
Like it act at the travis, or like you did it for the `before_script` section

![image](https://cloud.githubusercontent.com/assets/28564/2890828/89daa320-d52c-11e3-9025-171b7618519b.png)

``` yml
language: php

php:
  - 5.3
  #- 5.4

services:
 - mysql

install:
 - sudo apt-get install php5-mysql

before_script:
  #- mkdir -p shippable/testresults
  - cp app/config/parameters-shippable-ci.yml.dist app/config/parameters.yml
  - cp behat.yml.dist behat.yml
  - composer install --prefer-source #> /dev/null
  - app/console do:da:cr -e=test > /dev/null
  - app/console do:sc:cr -e=test --no-interaction > /dev/null
  - app/console do:fi:lo -n

script:
  - phpunit -c app/ #--log-junit shippable/testresults/junit.xml
  - bin/behat --no-snippets --verbose -fpretty
  #- bin/phpspec run -fpretty --verbose

notifications:
  email: false
```
