### ISSUE TITLE
Capybara default wait. tests failing randomly

### ISSUE THREAD

**Issue by luigi7up** [Shippable/support#1054]
Hi guys, 

we are running a lot of integration tests using Capybara. On the local machine tests pass in 99% of the cases with __Capybara.default_wait_time__ set to __3 sec__. We've noticed that 3 sec is not enough in Shippable so we put __8 sec__ and it went better, but still failing sometimes. We identified the tests that are the problematic ones and we set manually wait to __12s__:

```

expect(page).to have_content I18n.t('xxxxxxx'), :wait => 12
```
it's much better now, but even like this we've noticed that sometimes the next page doesn't load on time (artifacts screenshots and html prove it) and test, of course, fails :|

What's the best practice in these cases? It can't be that the page needs more than 12 sec to load :(

Best regards,
Luka

**Comment by luigi7up** [comment]
Hi! Any update on this one? Thanks

**Comment by manishas** [comment]
Can you send us your yml? Sorry it took some time to take a look at this. We couldn't repro this so looking at the yml would be helpful. Thanks!

**Comment by luigi7up** [comment]
Here you go:


```
language: ruby

rvm:
  - 2.1.3

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CAPYBARA_PAGE_PATH=shippable/capybara MANGO_CLIENT_PASSPHRASE=ZmD9h8mJAz721GscTv1UMjy6XjejPL5nK5LXvQDeRwWOHaJiAw
archive: true

cache: true

services:
  - selenium


addons:
  postgresql: '9.3'
  firefox: "33.0"  # be carful not to update selenium to a version incompatible with firefox
  selenium: "2.44"

# bundler_args: -j 3 --without development debug production profile console

before_install:
  - rvm rvmrc trust .


before_script:
  # ensure the test output and coverage dirs are created
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
  - mkdir -p shippable/testresults
  - cp config/database.yml.shippable config/database.yml
  # - psql -c 'create database "ria_test";' -U postgres
  - rake db:create RAILS_ENV=test
  - rake db:schema:load RAILS_ENV=test



script:


after_script:
  - "/etc/init.d/xvfb stop"

notifications:
    email:
      recipients:
        - luigi7up@gmail.com
        - abelardogilm@gmail.com
        - rpages07@gmail.com
```
