### ISSUE TITLE
Can't get parallelization to work.

### ISSUE THREAD

**Issue by vincentpaca** [Shippable/support#1083]
I'm trying to configure my rails app to build in parallel tests and my `shippable.yml` currently looks like this.

```
# Build Environment
build_environment: Ubuntu 12.04

# language setting
language: ruby

# version numbers, testing against two versions of node
rvm:
  - 2.1.5

addons:
  firefox: "28.0"

services:
  - selenium

parallelized_test: true

cache: true

# env tag
env:
  global:
    - DISPLAY=:99.0
    - SPEC_OPTS="spec/suite.rb --color --require ci/reporter/rake/rspec_loader --format CI::Reporter::RSpecFormatter"
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - DB=mysql2://shippable:@localhost/test
    - RAILS_ENV=test
  matrix:
    - RUN="rake" TEST_GROUP=1of9
    - RUN="rake" TEST_GROUP=2of9
    - RUN="rake" TEST_GROUP=3of9
    - RUN="rake" TEST_GROUP=4of9
    - RUN="rake" TEST_GROUP=5of9
    - RUN="rake" TEST_GROUP=6of9
    - RUN="rake" TEST_GROUP=7of9
    - RUN="rake" TEST_GROUP=8of9
    - RUN="rake" TEST_GROUP=9of9

# install dependencies
before_install:
  - "mysql -e 'create database if not exists test;'"

before_script:
  - "rm -rf $CI_REPORTS && mkdir -p $CI_REPORTS"
  - "rm -rf $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS"
  - "/etc/init.d/xvfb start"
  - rake -f CI.rake ci:copy_example_configs
  - rake -f CI.rake ci:update_db_yml
  - rake db:schema:load

script:
  - $RUN

after_script:
  - "/etc/init.d/xvfb stop"
```

Rakefile:
```
...
require 'ci/reporter/rake/rspec'
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec => ["ci:setup:rspec"]) do |t|false
  t.rspec_opts = ENV['SPEC_OPTS']
end
task :default => [:spec]
...
```

I can't make it play nice with parallel tests. I got the code coverage reports to work, but the test splitting doesn't.

Any insight would be really helpful.
