### ISSUE TITLE
apt-get install succeeds, but service not started

### ISSUE THREAD

**Issue by ceejbot** [Shippable/support#112]
Here's a yml file that describes the test environment I would like to see running:

``` yml
build_environment: Ubuntu 14.04
language: node_js
node_js:
  - 0.10.28
before_install:
    - sudo apt-get install -qq couchdb
    - sudo service couchdb start
```

Example output from a failed build is here: https://www.shippable.com/projects/536bb9b74531c1ae00863a40
Couchdb installs, but the OS refuses to start the new service automatically, and the explicit start fails because a sudo password is required.

Is this a scenario I should expect to work? A more general question would be: do you expect users to test with only the provided services, or like Travis, do you allow installing whatever dependencies are needed?
