### ISSUE TITLE
cannot get xdebug to work

### ISSUE THREAD

**Issue by diegotdai** [Shippable/support#1190]
![image](https://cloud.githubusercontent.com/assets/1164234/6739541/143bfe50-cede-11e4-83d9-318a8f679b7b.png)

**Comment by diegotdai** [comment]
shippable.yml
```yml
language: php

php:
  - 5.4
  - 5.5
  - 5.6
    #- hhvm

reset_minion: true

before_script:
  - composer self-update
  - composer config -g github-oauth.github.com blablablablablablablablablablablabalba
  - echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults

script:
  - vendor/bin/phpspec run -c phpspec.tests.ci.yml > shippable/testresults/junit.xml
  - vendor/bin/phpspec run -c phpspec.ci.yml
```
