### ISSUE TITLE
Firefox not installed after using "addons" as described

### ISSUE THREAD

**Issue by thrawn-a-D** [Shippable/support#1242]
I'm trying to execute some selenium based tests. I've configured my firefox version in the "addons" section and did everything else as described in the documentation. For whatever reason though, firefox is still not present while executing those tests. Trying to call "firefox --version" in the script section, produces a "/home/shippable/build/build.sh: line 90: firefox: command not found"

My yml file looks as following:
``` yml
# Language setting
language: clojure

lein:
  - lein2

build_image: shippableimages/ubuntu1204_clojure

before_install:
    - shippable_retry apt-get update
    - shippable_retry apt-get install -y xvfb libxrender-dev libxtst-dev

addons:
  firefox: "23.0"

services:
  - selenium

# Create directories for test and coverage reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - "Xvfb :99.0 &"
  - "export DISPLAY=:99.0"

# Running the test with Leiningen
script:
   - firefox --version
```

An example build is here: https://app.shippable.com/builds/5518e5ee86c05f0c00693555
