### ISSUE TITLE
Best way to run test for different environment configs

### ISSUE THREAD

**Issue by dmregister** [Shippable/support#1247]
```
language: php

php: 
  - 5.6
  
before_script:
  - mkdir -p $SHIPPABLE_REPO_DIR/shippable/testresults

script:
   - php codecept.phar build
   - php codecept.phar run api --config codeception.dist.yml --env $environment --xml $SHIPPABLE_REPO_DIR/shippable/testresults/$environment-reports.xml   

cache: true

notifications:
   email: false

after_failure:
  - python slack_notifier.py --token $slack_token

after_success:
  - python slack_notifier.py --token $slack_token -s

env:
#    - secure: shshs.... (dev settings)
    - secure: shshs.... (prod settings)
```

My secure variables have the $environment variable set.

The problem is that the same test are running for both dev and prod, but not all code is deployed to prod, so the test are failing. 

As of right now, I am having to change the secure tokens and commit the config file to check builds against the different environments.

Besides duplicating the repository, is there any way to specify to run the tests with either the dev settings or the prod setting, but not both?

These test work by going through our api and validating the response or each endpoint. So code needs to be deployed before it can be tested...which is kind of backwards.

**Comment by dmregister** [comment]
This might be overkill, but I have considered moving my tests to a submodule or subtree and making a dev repo and prod repo so I can run the test independently as needed.

**Comment by rageshkrishna** [comment]
Hi @dmregister! I'm not sure if I've understood your situation correctly. Are you saying you want to be able to select which envs to use to run the build without changing the YML file? This is currently not possible, but if you are using branches to separate dev and production code you can look for the branch name in your YML file and swap the settings. For example:

````
env:
  # Let's say this sets DEV_DB=localhost
  - secure: aaaaaaaaaa
  # Let's say this sets PROD_DB=192.168.1.1
  - secure: aaaaaaaaaa

script:
  # This will set DB to either PROD_DB or DEV_DB, depending on the branch name
  - if [ "$BRANCH" == "master" ]; then export DB=$PROD_DB; else export DB=$DEV_DB; fi
````

Now, builds on your dev branches will not cause tests to run against production. 

Does this help, or am I misunderstanding the scenario?
