### ISSUE TITLE
Build timeout due to code coverage

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1263]
I have enabled code coverage via PHPUnit in one of our repositories but now the build times out.

This is our `shippable.yml`:

```yaml
language: php

php:
  - 5.3
  - 5.4
  - 5.5

build_image: shippableimages/ubuntu1404_php

env:
  global:
    - <GITHUB_OAUTH_TOKEN>
  matrix:
    - TYPO3_BRANCH=TYPO3_6-2

before_install:
  - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
  - phpenv global $SHIPPABLE_PHP_VERSION
  - php --version
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - sudo apt-get install parallel
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv <extension> typo3conf/ext/
  - echo "memory_limit = 256M" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mkdir -p shippable/codecoverage

script:
  - ./bin/phpunit --coverage-xml shippable/codecoverage -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/<extension>/Tests/Unit
```
