### ISSUE TITLE
Does not deploy to correct environment on AWS EBS

### ISSUE THREAD

**Issue by manonthemat** [Shippable/support#1281]
Shippable registers changes to my **master** and **develop** (and *ebs* for testing) branch on a private GitHub repository. It then proceeds to build on a dedicated host via Dockerfile.

It'll run tests and *after_success* I'm deploying to AWS ElasticBeanstalk via `eb init && eb deploy`.

However, everything is getting pushed to my production environment, while the development branch should be deployed to my development environment on AWS.

Here is my shippable.yml (env and notification sections ommited)

```
build_image: node
language:
  - node_js
node_js:
  - "0.12"
branches:
  only:
    - master
    - develop
    - ebs
before_install:
  - apt-get install -y python-dev
  - pip install awsebcli
install:
  - npm install
before_script:
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config
script:
  - npm test
commit_container: manonthemat/iris
after_success:
  - eb init && eb deploy
```

This is my .elasticbeanstalk/config.yml

```
branch-defaults:
  default:
    environment: Iris-production
  develop:
    environment: Iris-dev
global:
  application_name: Iris
  default_platform: Docker 1.5.0
  default_region: us-west-2
  profile: eb-cli
```

My Iris-production environment is the one being updated regardless of which branch is being updated.
How do I fix this?
