### ISSUE TITLE
Build caching not working for my build

### ISSUE THREAD

**Issue by camullen** [Shippable/support#1316]
No matter how many times I push, I've been unable to get the build to cache. Each time, the console shows:

```
 docker pull ✓ 3 seconds
 Docker login
 Docker pull shippable/minv2:latest
```

My shippable.yml file:

```yaml
# language setting
language: ruby

# version numbers
rvm: jruby-1.7.19

env:
  global:
    - CI_REPORTS=shippable/testresults
    - COVERAGE_REPORTS=shippable/codecoverage
    - CODECLIMATE_REPO_TOKEN=XXXXX
before_install:
  - bundle update
  - bundle install

install:
  - bundle install

# NOT WORKING RIGHT NOW. WILL TRY RESETTING
cache: true

# ensure the test output and coverage dirs are created
before_script:
  - mkdir -p shippable/testresults

# write the rspec tests to the output dir
script:
  - jruby --dev -S rubocop
  - jruby --dev --debug -S rspec --format RspecJunitFormatter --out shippable/testresults/results.xml
```
