### ISSUE TITLE
Can't Initialize Dedicated Host on Rackspace

### ISSUE THREAD

**Issue by jchamberlain** [Shippable/support#1319]
I'm trying to setup an Ubuntu 14.04 build server on Rackspace. Running the initialization via the Shippable UI gives the following output:
```
Writing key to file
mode of '/tmp/19810a10-99e9-40d5-bc6a-26dcba311526.rsa' changed from 0644 (rw-r--r--) to 0600 (rw-------)
KEY file created: /tmp/19810a10-99e9-40d5-bc6a-26dcba311526.rsa
Writing script to file
Script file created: /tmp/19810a10-99e9-40d5-bc6a-26dcba311526.sh
Warning: Permanently added '[ip address]' (ECDSA) to the list of known hosts. sending incremental file list 19810a10-99e9-40d5-bc6a-26dcba311526.sh sent 1,459 bytes received 35 bytes 2,988.00 bytes/sec total size is 3,567 speedup is 2.39
executing script file
Command failed : ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=0 -p 22 -i /tmp/19810a10-99e9-40d5-bc6a-26dcba311526.rsa shippable@[ip address] /tmp/19810a10-99e9-40d5-bc6a-26dcba311526.sh Exception Script failure tag received
Checking kernel
sudo: no tty present and no askpass program specified
```

Update: I get the same error on Digital Ocean.

**Comment by jchamberlain** [comment]
Just tried again on Digital Ocean, and the initialization step now succeeds. However, I then run into #1297. Deploy just hangs.

**Comment by jchamberlain** [comment]
After a long wait, the deploy now finishes. However, tests don't run. I get an eternal "Waiting for build information...".

**Comment by manishas** [comment]
@jchamberlain can you share a link to the project on shippable? which builds were stuck?

**Comment by jchamberlain** [comment]
Here's one: https://app.shippable.com/projects/553005bdedd7f2c052c56d6e

**Comment by manishas** [comment]
I see some unread notifications for the project. Have you specified a build_image in your yml or in the project settings tab?

**Comment by jchamberlain** [comment]
Yup. The project works perfectly when I'm not using a dedicated server. When I a deploy a server, I can click build or push code all I want, but nothing happens--builds just disappear. When I remove the server, everything returns to normal and keeps working just fine.

**Comment by jchamberlain** [comment]
The unread notifications are about PRs from team members who have not rebased on the current master, and are thus still only configured for Travis instead of Shippable.

**Comment by manishas** [comment]
to build with dedicated hosts, you need a build_image tag in your yml or you need to specify a build image in the project settings tab. 
http://docs.shippable.com/en/latest/config.html#dedicated-hosts

**Comment by manishas** [comment]
can you share your shippable.yml?

**Comment by manishas** [comment]
also, can we trigger a manual build on your behalf?

**Comment by jchamberlain** [comment]
Please see my previous comment and disregard the notifications. Go ahead and trigger the manual build.

**Comment by jchamberlain** [comment]
shippable.yml:
```yml
language: php
php:
  - 5.5

env:
  global:
    - [a bunch of vars]

services:
  - mongodb

before_install:
 - sudo apt-get update && sudo apt-get install -y gnumeric gdal-bin
 - phpenv config-add .test.ini
 - composer config -g github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install
  - mysql -e 'create database epiphany;'
  - mongo epiphany --eval 'db.addUser("epiphany", "nothing");'
  - ./artisan migrate --force

script:
  - phpunit
```
