### ISSUE TITLE
No sufficient output 

### ISSUE THREAD

**Issue by fisera123** [Shippable/support#1325]
Hello, 
I'm trying to integrate shippable with my project, in the repository project is not the root folder, I couldn't find any explanation how to change directories on shippable docs webpage.
This is my shippable.yml 
```
language: ruby

rvm:
  - 1.9.3

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

before_script:
  - mkdir -p shippable/testresults

install:
  - cd ./taxiapp/
  - bundle install --gemfile="Gemfile"
script:
  - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml

notifications:
 email:
     recipients:
         - example@gmail.com
```
Result is failure but no information is provided, thus I don't know what I did wrong. I've also tried adding `- cd ./taxiapp/` to the `script` in that case output was directory not found
https://app.shippable.com/builds/5531c6143ef75c0c00a39a86
