### ISSUE TITLE
Shippable builds incredibly slow

### ISSUE THREAD

**Issue by nathanpeck** [Shippable/support#1352]
I'm having issues where builds take 15 or more minutes at the `test_ve` stage. Here is my `shippable.yml` file:

```yaml
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

services:
  - redis

env:
  - REDIS_HOST=localhost REDIS_PORT=6379

cache: true

# scripts
script:
  # Install dependencies
  - npm install

  # Start server
  - node cluster.js &
  - NODE_PID=$!

  # Run tests
  - npm test

  # Cleanup
  - kill $NODE_PID
```

It appears that Shippable is compiling Node.js from source, as I see thousands of lines of build output like this:

```
ln -f "/home/shippable/.nvm/src/node-v0.12.2/out/Release/obj.target/deps/uv/libuv.a" "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a" 2>/dev/null || (rm -rf "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a" && cp -af "/home/shippable/.nvm/src/node-v0.12.2/out/Release/obj.target/deps/uv/libuv.a" "/home/shippable/.nvm/src/node-v0.12.2/out/Release/libuv.a")
```

Expected behavior would be that Shippable uses something like a prebuilt binary at https://nodejs.org/dist/ which should be able to be installed in seconds.
