### ISSUE TITLE
Permission denied error when installing awsebcli python package

### ISSUE THREAD

**Issue by hopsor** [Shippable/support#1360]
Hi,

We have a project on shippable that deploys to Amazon Elastic Beanstalk when the build is successful which requires us to use the `awsebcli` python package within our shippable build. This has been working fine for like 2-3 months but today it suddenly crashed when trying to install such pip package. 

We are a bit lost here since we haven't made any changes to our `shippable.yml` in the last days.

Here I attach a snippet of our `shippable.yml` and the error we are getting:

**shippable.yml:**

```yaml
cache: true
language: ruby
rvm: 2.1.5
services:
  - redis
branches:
  only:
    - master
before_install:
  - pip install awsebcli
before_script:
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo "aws_access_key_id = $AWS_KEY" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWS_SECRET" >> ~/.aws/config

```

**Error trace:**

```
pip install awsebcli
Downloading/unpacking awsebcli
  Running setup.py egg_info for package awsebcli
    warning: no files found matching '*.json'
Requirement already satisfied (use --upgrade to upgrade): pyyaml>=3.11 in /usr/local/lib/python2.7/dist-packages (from awsebcli)
Downloading/unpacking cement==2.4 (from awsebcli)
  Running setup.py egg_info for package cement
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.1,<3.0.0 in /usr/local/lib/python2.7/dist-packages (from awsebcli)
Requirement already satisfied (use --upgrade to upgrade): jmespath>=0.6.1 in /usr/local/lib/python2.7/dist-packages (from awsebcli)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil>=2.1,<3.0.0->awsebcli)
Installing collected packages: awsebcli, cement
  Running setup.py install for awsebcli
    changing mode of build/scripts-2.7/eb_completion.bash from 644 to 755
    error: could not create '/usr/local/lib/python2.7/dist-packages/ebcli': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/shippable/workspace/src/bitbucket.com/XXXXX/XXXXX/build/awsebcli/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-Jy46Zp-record/install-record.txt:
    running install
```

Any idea what might be causing this problem? 

Thanks in advance.
