### ISSUE TITLE
eb deploy is causing build failures

### ISSUE THREAD

**Issue by smaiyaki** [Shippable/support#1392]
We have noticed that our builds suddenly starting to behave in a weird manner. In the after success segment of the build, we have the command "eb deploy --debug" that pushes our changes to elastic beanstalk. The failure is coming from there with the error:

```
Traceback (most recent call last):
  File "/home/shippable/build_ve/python/2.7/bin/eb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.6.1,<2.7
```
This works perfectly from the command line. I believe this has to do with the minion because at first, we used t get messages from the pull minion segment like:
```
image shippable/minv2:latest exists, skipping pull
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
grep: write error: Broken pipe
```
We managed to solve this by removing the caching and reset_minions but this has not yet solved the eb deploy.

In case this will help you, our project is on https://app.shippable.com/projects/54aae412d46935d5fbc182e4

**Comment by manishas** [comment]
i've escalated this to the team. we'll take a look and let you know as soon as we have a fix.

**Comment by manishas** [comment]
@smaiyaki can you share your shippable.yml?

**Comment by smaiyaki** [comment]
Thanks for looking in to this one.. Here is my yaml file:
```
language: python
#build_environment: Ubuntu 13.10

python:
  - 2.7

addons:
  firefox: "28.0"
  selenium: "2.44"

# Postgres binds to 127.0.0.1 by default and is started on boot. Default username is "postgres" with no password
# Create a DB as part of before script to use
# Mongo binds to 127.0.0.1 by default
services:
  - mongodb
  - selenium

before_script:
  - psql -c 'drop database if exists sh;' -U postgres
  - psql -c 'create database sh;' -U postgres
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config
  - git submodule init
  - git submodule update
  - ls -al
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
 


env:
  global:
    - RDS_HOSTNAME=xxxx
    - AWSAccessKeyId=xxxx
    - secure: xxxx
install:
  - pip install awsebcli
  - pip install -r requirements.txt --use-mirrors


script:
  - mkdir -p .elasticbeanstalk
  - cp config.yml .elasticbeanstalk/

after_success:
  - eb deploy --debug
```
