### ISSUE TITLE
Error response from daemon: Registration: \"email is already associated with an account\"" 

### ISSUE THREAD

**Issue by bubenshchykov** [Shippable/support#1421]
Started to happen today
https://app.shippable.com/builds/554b10dfff724e0c00e4d777

```yml
build_image: shipimg/ubuntu1204_nodejs

language: node_js

node_js:
  - 0.10.26

before_install:
  - npm install -g npm-install-cache

install:
  - true

services:
  - mongodb

script:
  - make build --recon
  - make build
  - node runAllTests

env:
  - APP_ENV='staging'
  - SHIPPABLE=true
```
