### ISSUE TITLE
How to set multiple env variables in matrix

### ISSUE THREAD

**Issue by nikhiljindal** [Shippable/support#1438]
From https://github.com/GoogleCloudPlatform/kubernetes/pull/8134, this is what I have right now:

```
matrix:
  include:
    - go: 1.4
      env:
        - KUBE_TEST_API_VERSIONS="v1beta1"
          KUBE_TEST_ETCD_PREFIXES="registry"
    - go: 1.3
      env:
        - KUBE_TEST_API_VERSIONS="v1beta3"
          KUBE_TEST_ETCD_PREFIXES="kubernetes.io/registry"
```
I expect this to result in 
```
export KUBE_TEST_API_VERSIONS="v1beta1";
export KUBE_TEST_ETCD_PREFIXES="registry"
 ```
But, from https://app.shippable.com/builds/555290013566980c00a3a820, it is resulting in:
```
export KUBE_TEST_API_VERSIONS="v1beta1",KUBE_TEST_ETCD_PREFIXES="registry";
```
and hence when I access KUBE_TEST_API_VERSIONS in my code, I get "v1beta1,KUBE_TEST_ETCD_PREFIXES=registry" value and KUBE_TEST_ETCD_PREFIXES is empty.

What is the right way to set multiple env variables? I tried to find an example at http://docs.shippable.com/en/latest but could not find one.
Thanks!
