### ISSUE TITLE
Build Dockerfile and push to Quay.io

### ISSUE THREAD

**Issue by howarddierking** [Shippable/support#1490]
Hey all - sorry if this question is a repeat, but in reading through the other threads, I'm having a hard time teasing apart the requests for custom _build_ containers vs. support for building container images from my project artifacts. It is the latter scenario that I'm interested in.

I need to support the following workflow:

* Build the project (e.g. current workflow)
* Build an image from the Dockerfile (need to also be able to tag it with the build number)
* Login to Quay.io (robot account)
* Push image to Quay.io

Maybe down the road I'll bake in automated deployment, but because we do deployments at the entire auto-scaling group level and need to support multi-container orchestration, I'll probably continue to do this out of band for some time.

So, is this workflow supported in Shippable today?

**Comment by manishas** [comment]
@howarddierking we currently support the following -

* Build the project (e.g. current workflow)
* Build an image from the Dockerfile and tag it with the build number
* Push to Docker Hub or Google Container Registry

Let me know if you need help with the above. We are adding support for other registries soon.

Also, I'd love to chat further about your requirements for multi-container deployments. Can I send you an email and schedule a meeting? We would love to show you a preview of what we have coming up.

**Comment by mbrevoort** [comment]
@howarddierking we have this same workflow working from a custom build node (coincidentally up until today).

```
  # language setting
language: go
  # version numbers
go:
  - 1.4

archive: true
cache: true
build_image: robotsandpencils/shippable-ubuntu1404_go

env:
  global:
    # robotsandpencils+push password as QUAYIO_PUSH_PASSWORD
    - secure: XXXXXXXXXXX

before_install:
  - export GOPATH=$SHIPPABLE_GOPATH
  - . $HOME/.gvm/scripts/gvm
  - gvm use go$SHIPPABLE_GO_VERSION
  - export PATH=$GOPATH/bin:$PATH
  - sudo redis-server /etc/redis/redis.conf

install:
  - make init
  - export GOPATH=`godep path`:$SHIPPABLE_GOPATH
  - export COMMIT_SHORT=`git rev-parse --short HEAD`

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmlsec1
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - make test-shippable
  - if [ "$BRANCH" = "master" ]; then sudo docker build -t quay.io/robotsandpencils/api-router:$COMMIT_SHORT .; fi

after_failure:
  - python /notify.py --slack-url https://hooks.slack.com/services/XXXXXXXXXXX --message failure

after_success:
  - python /notify.py --slack-url https://hooks.slack.com/servicesXXXXXXXXXXX --message success
  - if [ "$HEAD_BRANCH" = "master" ]; then sudo docker login -u robotsandpencils+push -p $QUAYIO_PUSH_PASSWORD -e "robotsandpencils+push" quay.io; fi
  - if [ "$HEAD_BRANCH" = "master" ]; then sudo docker push quay.io/robotsandpencils/api-router:$COMMIT_SHORT; fi
  - if [ "$HEAD_BRANCH" = "master" ]; then sudo docker logout quay.io; fi
```
