### ISSUE TITLE
Git sync clones into wrong directory when pulling from bitbucket repo

### ISSUE THREAD

**Issue by vially** [Shippable/support#1520]
The `git_sync` step clones the repo into: `~/workspace/src/bitbucket.com` instead of `~/workspace/src/bitbucket.org`

This is causing issues with the Go language because the import paths have to match the file locations on disk.

I know you can fix it by defining the `SHIPPABLE_REPO_DIR` global env var but I think that should be the default behaviour so I don't have to clutter the `shippable.yml` file for every Go project
```yaml
env:
  global:
    - SHIPPABLE_REPO_DIR="$HOME/workspace/src/bitbucket.org/$REPO_NAME"
```

Related issues: #1226
