### ISSUE TITLE
`/etc/init.d/xvfb start ` was failed. What selenium service will do?

### ISSUE THREAD

**Issue by mookjp** [Shippable/support#1556]
I tried to run [spinach](https://github.com/codegram/spinach) test with `shippable.yml` like this:

```
language: ruby
rvm:
  - 2.1
addons:
  firefox: "28.0"
services:
  - selenium
before_install:
  - apt-get update
  - apt-get install -y libpq-dev
before_script:
  - /etc/init.d/xvfb start
after_script:
  - /etc/init.d/xvfb stop
env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - secure: <secure-variable>
```
![screen shot 2015-06-16 at 19 56 55](https://cloud.githubusercontent.com/assets/1519309/8190452/dc62a7ca-1462-11e5-8520-10b5602d62b5.png)

But it fails on `before_script` section because of `/root/c7d27eeb-409a-4877-a9eb-c2d75e817d9d.sh: line 96: /etc/init.d/xvfb: No such file or directory`.
I thought I set selenium service so it handles this command but it won't. Could you tell me what service does on the container?

And my container settings is here:
![screen shot 2015-06-16 at 20 05 26](https://cloud.githubusercontent.com/assets/1519309/8190485/17e49876-1463-11e5-90e0-f49fbd6f66e0.png)
