### ISSUE TITLE
Shippable does not display phpunit test results...

### ISSUE THREAD

**Issue by pennyarcade** [Shippable/support#1557]
Hello Team,

I followed the documentation very closely to set up phpunit tests (among others) with shippable using the '--log-junit' option and the '--coverage.xml' option. 
I am using the standard image for now.
My coverage results are displayed correctly and the phpunit output looks ok, too. (Failing as expected)
Sadly I can't seem to get the phpunit results displayed in the testresults tab. I tried different filenames and triplechecked output directory and format. Please help.

Also my composer update fails when I turn caching on. It gets a permission denied on the cache directory. File permissions are OK, there might be an Issue of files already being open that I can't reproduce locally. I am trying to test a small Symfony application. The intendet result should be saving build time by caching but keeping dependencies up to date.
Update: This only happens for the buildin global composer. I have no errors when using my own composer.phar in the project directory.

Third and least important, I'd like to also display my code sniffer results of PHPMD and PHPCS in the testresults tab. The output is set to xml, too. 

Here is an example build with the above problems : https://app.shippable.com/builds/55812bf06cde2e0c0077a5b7
(Build 43)

Here is my shippable.yml for reference:

```yaml
cache: true

# language setting
language: php

# php tag
php:
    # only test one php version until problems are solved.
    #- 5.3
    #- 5.4
    #- 5.5
    - 5.6
    #- hhvm

before_install:
    - cd imgboard
    # make sure the directories are writable (this shouldn't be nessessary and doesn't solve the problem!)
    - sudo chmod 777 -R app/cache
    - sudo chmod 777 -R app/logs
    # update composer (works fine)
    - php ./composer.phar selfupdate

install:
    # update dependencies (fails with obscure permission denied error when using builtin composer)
    # composer update
    - php ./composer.phar update
    - cd ..

before_script:
    # make sure the result folders exist
    - mkdir -p shippable/codecoverage
    - mkdir -p shippable/testresults
    - cd imgboard

script:
    # don't fail for code smells (|| true)
    # PHP mess detector HTML output for offline use
    - bin/phpmd src/ html cleancode,codesize,controversial,design,naming,unusedcode --reportfile ../shippable/testresults/phpmd.html --strict || true
    # PHP mess detector xml output to be displayed in testresults tab
    - bin/phpmd src/ xml cleancode,codesize,controversial,design,naming,unusedcode --reportfile ../shippable/testresults/phpmd.xml --strict || true
    # PHP CS text output for offline use only until above works
    - bin/phpcs --report-file=../shippable/testresults/phpcs.txt src/ || true
    # PHPUNIT Tests anc code coverage in different formats for display in testresults tab and for offline use
    - phpunit -c app/ --log-junit ../shippable/testresults/phpunit.xml --coverage-xml ../shippable/codecoverage --coverage-html ../shippable/codecoverage --testdox-html ../shippable/testresults/junit.html

after_script:
    # Prove the files were written correctly
    - cd ..
    - ls -a shippable/testresults
    - cat shippable/testresults/junit.xml
    # check in test results for offline use 
    - git add shippable
    - git add imgboard/composer.*
    # suppress infinite loop on ci
    - git commit -m 'update test results [skip ci]'
    - git push

notifications:
    email: false

```

Thank you very much for your help.

Martin
