### ISSUE TITLE
Error installing ruby 2.1.3

### ISSUE THREAD

**Issue by cgutierrez** [Shippable/support#1599]
Hello,

I'm getting an error with my builds during the Ruby installation process. Here's the declaration in the shippable.yml file.

```yml
language: ruby
rvm:
  - 2.1.3

cache: true

addons:
 postgresql : "9.3"

services:
 - redis

before_install:
  - sudo apt-get install postgresql-9.3-postgis
```

Here's a screenshot of the error I'm getting. Please let me know if there is anything else I can provide.

![screen shot 2015-06-24 at 11 42 48 am](https://cloud.githubusercontent.com/assets/133389/8334483/2e4b82ec-1a66-11e5-857d-dd07f775a802.png)
