### ISSUE TITLE
Dynamically change/cancel docker image to build 

### ISSUE THREAD

**Issue by xherriot** [Shippable/support#1608]
Hello,

I would like to do:
• Commit with tag *-alpha, build my/app:alpha
• Commit with tag *-beta, build my/app:beta
• Commit with tag *, build my/app:latest
• Commit without tag, CI without build a docker image.

To this, I have a bash script executed "after script":
```yml
after_script:
  - 'bash shippable-deploy.sh'
```

Content of this file:
```bash
#!/bin/bash

hash=$(git log -n 1 --pretty=format:"%H")
tag=$(git tag --points-at $hash)

if [[ -n "$tag" ]]
then
    echo "Tag: $tag"
    dir=./shippable/buildoutput/"$tag"/
    echo "Dir: $dir"
    mkdir "$dir"
    cp -R ./dist/* "$dir"
    ln -s "$dir"/../.common/ "$dir"/.common/
    echo "$tag" > ./shippable/buildoutput/"$tag"/version.txt
else
    echo "No tag related, we don't add this to the Docker image."
    echo "Hack for CI without docker build." > ./shippable/buildoutput/shippable.txt
fi
```

Then, the build is processed with my Dockerfile:
```docker
FROM my/app
ADD ./buildoutput/ /var/www/app/
```

Each build tagged add its own directory (named with the tag) to the docker image.
For now, for a commit without tag, I have to do a trick to build the Docker image without send my real build (if no file is added, shippable fail).
And for now, all my builds tagged are send to my/app:latest image (then, its a big image).
(For some reasons, I have to keep each tagged build a certain time)

It would be nice if inside the shippable.yml file, we could do something like that:
```yml
tags:
    *-alpha*:
        docker:
            build: Dockerfile.alpha
            to: my/app:alpha
    *-beta*:
        docker:
            build: Dockerfile.beta
            to: my/app:beta
    *:
        docker:
            build: Dockerfile
            to: my/app:latest
    none:
        docker: 
            build: false
```
Then check if the commit we test is related to a tag.

(Launch a CI when a new tag is send to the repository (without any commit) would be nice too)
