### ISSUE TITLE
deploy and before_deploy hooks

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#1645]
Hi,

I'm am trying to upload my build artifact to s3. When I used travis I have the following tasks:
- before deploy
- deploy

```
before_deploy:
  - gulp images
  - cp public/styles/*.min.css public/dist/
  - BUILD_DATE=$(git log -n1 --pretty=format:'%ci' | cut -d' ' -f1)
deploy:
  - provider: s3
    skip_cleanup: true
   // upload minified js and css to s3
```

My question:
Does shippable has "deploy" and "before_deploy" hooks? I thought since shippable is compatible with travis, it should have one?

Also I noticed after my build was successful, the "after_success" hook was followed by 

```
  upload artifacts 0 seconds
 echo 'skipping archive upload...'
```

Why is it skipping that?
for reference:
https://app.shippable.com/projects/552c7ec75ab6cc1352c300d8

---

I googled around and found shippable doesn't allow upload to s3 unless I install awscli in the container and the manually invoke the command to upload to s3 after_success. Just wondering if it's that the best practice recommended by shippable? 

Thanks
-Oby
