### ISSUE TITLE
Error response from daemon: Wrong login/password, please try again

### ISSUE THREAD

**Issue by molinto** [Shippable/support#1671]
Keep getting fails, due to this error:
time="2015-07-13T12:58:43Z" level=fatal msg="Error response from daemon: Wrong login/password, please try again"

Wrong login/password for what?

**Comment by molinto** [comment]
Linked Docker integration to project & now getting this:
docker: "login" requires a maximum of 1 argument. See 'docker login --help'.

**Comment by manishas** [comment]
@molinto can you describe your scenario in a bit more detail? Are you using a custom docker image or just our default one?

Can you share your shippable.yml?

**Comment by molinto** [comment]
Yep, its:
```
language: node_js

build_image: shippableimages/ubuntu1404_nodejs

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

env:
  - NODE_ENV=test

before_install:
  - npm install -g mocha
  - npm install -g nodemon
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install

after_script:
  - ./node_modules/mocha/bin/mocha --timeout 5000 --reporter spec --recursive -t 5000 -G

notifications:
     email:
         recipients:
             - me@email.com
         on_success: change
         on_failure: always
```
