### ISSUE TITLE
I can't install gulp

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#1680]
I can't seem to install gulp. In the Shippable console I'm getting, "``npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/gulp'``". This is primarily a python project but I wanted to install gulp so that I could run a javascript linter. Here is my ``shippable.yml`` file. 

```yml
language:
  - python
  - node_js

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - "2.7"

services:
  - redis

before_install:
 - npm install -g gulp

install:
  - pip install -r config/requirements/testing.txt --use-mirrors
  - npm install

before_script:
  - mkdir -p docs/admin/_static
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - make lint
  - make lint_docs
  - which python
  - coverage run manage.py test -v 3 --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```

Here is the console output:
![kpics-django shippable-fix 737 - shippable 2015-07-15 09-09-32](https://cloud.githubusercontent.com/assets/191620/8700487/ad5d4ea0-2ad1-11e5-9c33-84cdfae14cae.jpg)

**Comment by epicserve** [comment]
If I install gulp without using ``-g`` it installs but when it tries to run gulp you get, ``gulp: Command not found``.

**Comment by epicserve** [comment]
I just tried ``sudo npm install -g gulp``, which installs gulp globally, however now when it tries to install the npm packages with ``npm install`` it fails with:

```bash
npm WARN package.json @ No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.6
npm ERR! Error: EACCES, mkdir '/home/shippable/.npm/chalk/0.5.1'
npm ERR! { [Error: EACCES, mkdir '/home/shippable/.npm/chalk/0.5.1']
npm ERR! errno: 3,
npm ERR! code: 'EACCES',
npm ERR! path: '/home/shippable/.npm/chalk/0.5.1',
npm ERR! parent: 'gulp-livereload' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/shippable/workspace/src/bitbucket.org/oeie/kpics-django
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/shippable/.npm/chalk/0.5.1
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/shippable/.npm/chalk/0.5.1'
npm ERR! not ok code 0
```

**Comment by epicserve** [comment]
@manishas Any ideas?

**Comment by manishas** [comment]
@epicserve we do not support 2 language tags in the yml. If I remove python and just use node.js it gets past the npm install step even with your original yml (i.e. without sudo). Can you give that a shot?

**Comment by epicserve** [comment]
@manishas, thank you for your help!

It seems to work ... not very intuitive though. You would think, since I'm running python tests, I would still need the Python language in the language setting. I wonder if you could add some notes in your docs to cover this, it might save someone needing to submit a support issue.

Here is the ``shippable.yml`` file that worked (just in case it helps someone else):

```yml
language: node_js

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - "2.7"

services:
  - redis

before_install:
  - npm install -g gulp

install:
  - pip install -r config/requirements/testing.txt --use-mirrors
  - npm install

before_script:
  - mkdir -p docs/admin/_static
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - make lint
  - make lint_docs
  - which python
  - coverage run manage.py test -v 3 --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```
