### ISSUE TITLE
Can't have node_js 0.12 alongside xvfb without waiting 10+ minutes per build?

### ISSUE THREAD

**Issue by posita** [Shippable/support#1712]
Originally, our `shippable.yml` file was this:

```yml
language: node_js

node_js:
  - "0.12"

addons:
  firefox: "29.0"

services:

before_script:
  - "git clone --depth 1 https://github.com/laurentj/slimerjs.git"
  - "export SLIMERJS_BIN=`pwd`/slimerjs/src/slimerjs"
  - "export SLIMERJSLAUNCHER=firefox-bin"
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
```

But that took 10+ minutes to set up before even getting to the tests. So we added:

```yml
cache: true
```

But that didn't seem to do anything, plus it's [going away](http://blog.shippable.com/shippable-3.0-breaking-changes#BuildImage). So we added:

```yml
build_image: shippableimages/ubuntu1204_nodejs
```
Which sped up the time it took to get to the `before_script` step quite a bit, but then we failed on `/etc/inid./xvfb start`:

```
/root/[...].sh: line 87: /etc/init.d/xvfb: No such file or directory
```

Waiting 10+ minutes for a build is unusable for us. How do we use node_js 0.12 alongside xvfb?
