### ISSUE TITLE
Permission denied when installing python packages with pip

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#1732]
My config was working and just stopped working like a week ago. I'm just now getting around to looking into it.

I'm getting the following during the install section:

```
pip install -r config/requirements/testing.txt --use-mirrors
...
creating /usr/local/lib/python2.7/dist-packages/bleach
error: could not create '/usr/local/lib/python2.7/dist-packages/bleach': Permission denied
----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/shippable/workspace/src/bitbucket.org/oeie/kpics-django/build/bleach/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-3V2WZr-record/install-record.txt failed with error code 1
Storing complete log in /home/shippable/.pip/pip.log
...
```

My shippable.yml file:

```yaml
language: node_js

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - "2.7"

services:
  - redis

before_install:
  - npm install -g gulp

install:
  - pip install -r config/requirements/testing.txt --use-mirrors
  - npm install

before_script:
  - mkdir -p docs/admin/_static
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - make lint
  - make lint_docs
  - which python
  - coverage run manage.py test -v 3 --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```
