### ISSUE TITLE
Build hangs after docker image build.  Never pushes to docker hub.

### ISSUE THREAD

**Issue by macgyver2028** [Shippable/support#1748]
I am having an issue where the docker container is built, but is never pushed to docker hub.  I am using a dedicated node and everything seems to be in order there.  After the image is built, the build hangs until it ultimately times out.  No other errors that I can find.

![screen shot 2015-08-01 at 7 25 07 pm](https://cloud.githubusercontent.com/assets/1762038/9024132/2b8b1ef6-3883-11e5-8835-46cf28d628a6.png)

Current Settings:
![screen shot 2015-08-01 at 7 21 46 pm](https://cloud.githubusercontent.com/assets/1762038/9024125/bd01ebf4-3882-11e5-92ee-d605fef840e0.png)

Last build:
https://app.shippable.com/builds/55bd5f5a00d6ce0b00fd8344

**Comment by macgyver2028** [comment]
Any chance this is something I've set wrong someplace?  Any pointers as to where I should look?  I've tried alternate settings but get the same results.

**Comment by macgyver2028** [comment]
Would posting our shippable.yml file help?

**Comment by lekhab** [comment]
@macgyver2028: apologies for the delay. following up on this.  Please go ahead and add the YML to the issue..

**Comment by macgyver2028** [comment]
YML file below.
```
language: node_js
node_js:
- '0.10'
before_install:
  - SUDO=$(which sudo) && $SUDO pip install --upgrade awscli 
  - shippable_retry npm update npm -g
  - shippable_retry npm install -g grunt-cli pm2 sails
env:
  global:
    - AWS_ACCESS_KEY_ID=REDACTED
    - AWS_DEFAULT_REGION=us-east-1
    - TASK_FAMILY=respondr-scheduler
    - ECS_CLUSTER_NAME=respondr-scheduler
    - secure: ogAAGj7zDhrB/fqhcEv+qFw8Ix8Q1ullAW3JmljhaD3LTCicL73i2jcUGcbPRKhrc/ceW+kX1hC8ekhWqbeDvgT0GKAmDy2pzuipss+4CIeuo4m1fq22JXKtIXBveWpASSt1h6dXyv7x/b/R1fR9h5HR46SxcF7jMlGEed/i24JpJzHDKQ1mVjYQTj8jgSSAPE2HI8PdhkvwGCc6GCKc+UxB1HOF2Hj3+zbdrCIP5D0lrFMt4uuxakfvFbIcA0cvwHCCOTM9ren5ChNWP9fdDbwfr6I1jJixrlgfip0zouYJayucfHlodTKwbxgF6lsuJYbDvQnO3CU1luDGbzzb/Q==
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - admin@respondr.io
    on_success: always
    on_failure: always
after_success:
  - if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ]; then sed -e "s;%BUILD_NUMBER%;$BUILD_NUMBER;g" -e "s;%NODE_ENV%;development;g" -e "s;%NAME%;dev;g" $TASK_FAMILY.json > $TASK_FAMILY-v_$BUILD_NUMBER.json; aws ecs register-task-definition --family $TASK_FAMILY --cli-input-json file://$TASK_FAMILY-v_$BUILD_NUMBER.json; export TASK_REVISION=`aws ecs describe-task-definition --task-definition $TASK_FAMILY | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`; export DESIRED_COUNT=`aws ecs describe-services --services $ECS_SERVICE_NAME --cluster $ECS_CLUSTER_NAME | egrep -m 1 "desiredCount" | tr "/" " " | awk '{print $2}' | sed 's/,$//'`; aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $TASK_FAMILY:$TASK_REVISION --desired-count $DESIRED_COUNT; fi
```
