### ISSUE TITLE
Build fails due to maven gpg signing

### ISSUE THREAD

**Issue by arnonmoscona** [Shippable/support#1801]
My build always fails with 

```
gpg: signing failed: secret key not available
[INFO] BUILD FAILURE
```

I could not find in the documentation how to skip this. My shippable.yml looks like:

```
language: java

jdk:
   - oraclejdk8

after_success:
   - mvn clean cobertura:cobertura
   - mvn test -Dgpg.skip=true

notifications:
   email:
       recipients:
          - arnon@moscona.com
```

If I run on my machine ```mvn install -Dgpg.skip=true``` it works just fine as long as all tests pass ("works on my machine")

Not clear how to fix the YAML file to get the desired outcome.
