### ISSUE TITLE
Including global environment variables in matrix

### ISSUE THREAD

**Issue by ixdy** [Shippable/support#1808]
I'm trying to include a number of environment variables across all variations of our matrix. In particular, the configuration I'm trying is [here](https://github.com/ixdy/kubernetes/blob/coveralls/shippable.yml).

However, based on the [Shippable build results](https://app.shippable.com/builds/55d5188f4e6e0d0c001d6dba), it seems like these variables aren't being exported. They don't appear in the script tab, and an echo debug command which prints `"Reporting coverage results to Coveralls for service ${CI_NAME:-}"` isn't showing the variable defined, either.

I've tried reading through the docs at http://docs.shippable.com/yml_reference/, but it isn't very clear what I'm doing wrong.

My issue seems similar to #1223, but there wasn't an applicable resolution there.

**Comment by lekhab** [comment]
@ixdy: you are right - for some reason when I have both "global" env and matrix "include" - the global vars are being ignored. I have opened an internal issue to figure out what's going on.

In the meantime, a quick workaround is to add the global variables under each include. That seemed to do the trick for me.. Let me know if the workaround works for you. will keep you posted on what we find.

```
matrix:
  include:
    - go: 1.4
      env:
        - KUBE_TEST_API_VERSIONS=v1 KUBE_TEST_ETCD_PREFIXES=registry
        - CI_NAME="shippable"
        - CI_BUILD_NUMBER="$BUILD_NUMBER"

    - go: 1.3
      env:
        - KUBE_TEST_API_VERSIONS=v1 KUBE_TEST_ETCD_PREFIXES=kubernetes.io/registry
        - CI_NAME="shippable"
        - CI_BUILD_NUMBER="$BUILD_NUMBER"

```
