### ISSUE TITLE
Script executing out of order

### ISSUE THREAD

**Issue by RealNobody** [Shippable/support#1838]
I am playing around trying to work around some issues I've been having to try to either fix things or at least diagnose what is going on.

That being said, I know our script as it is now (in this branch) is not the best.

However, I don't know how it ended up breaking this run:
https://app.shippable.com/builds/55e75db2e9afdc0b003957bc

A more normal run sorta looks like:
```
  pulling image from hub
  setup_jdk
  setup_ve
  Installing addons
  start_services
  git_sync
  install
  before_script
  script
  after_script
  zipping archive
  uploading artifacts
  save reports
```

This run looks like:
```
  pulling image from hub
  setup_jdk
  setup_ve
  Installing
  start_services
  git_sync
  install
  before_script
  script
  uploading artifacts
  after_script
```

You'll notice that the `after_script` runs out of order.

The `uploading artifacts` step just says:

```
echo 'skipping upload'
```

The `after_script` doesn't run all of the commands in the script.

Some points of interest:

```
install:
 - mkdir -p shippable/testresults
 - date > shippable/testresults/start_date.txt
 - cat shippable/testresults/start_date.txt

script:
 - set +e
 - date
 - rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml
 - cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd ..
 - set +e
 - DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults

after_script:
 - cp -r cornucopia_report shippable/testresults
 - date > shippable/testresults/end_date.txt
 - cat shippable/testresults/end_date.txt
```

You'll note that I have a `set +e`.  This is to try to work around an issue where artifacts aren't getting uploaded when Cucumber fails.

This creates the problem where we could get false green builds when Cucumber fails.  I'd worry about that if we could get more of our runs to work.

However, we've had so many other issues (like this) which break things that fixing that isn't actually an issue yet.  I will be fixing it though.

I will keep trying to figure out what I can from my end, but if commands just won't be executed, there is little I can do.

**Comment by manishas** [comment]
@RealNobody We'll follow up on all your issues today and get back to you.

**Comment by manishas** [comment]
@RealNobody can you send us your shippable.yml?

**Comment by RealNobody** [comment]
> can you send us your shippable.yml?

Yes.

I have a couple of versions that I'll send you here.

**Comment by RealNobody** [comment]
For this incident - This is the YML that I was running:

```
language: ruby
archive: true

rvm:
 - 1.9.3-p392

node_js:
  - "0.12.2"

install:
 - mkdir -p shippable/testresults
 - date > shippable/testresults/start_date.txt
 - cat shippable/testresults/start_date.txt
 - cd dashboard && npm install ember-cli@0.2.5 --save
 - npm install bower --save
 - npm install
 - bower install
 - node_modules/.bin/ember build
 - cp dist/assets/vendor.js ../app/assets/javascripts/vendor.js
 - cp dist/assets/dashboard.js ../app/assets/javascripts/dashboard.js
 - cd .. && shippable_retry bundle install --gemfile=Gemfile

addons:
  firefox: "28.0"
  hosts:
   - www.mortgagedev.local
   - testy.mortgagedev.local
   - www.agentdev.local
   - testy.agentdev.local
   - www.insurancedev.local
   - testy.insurancedev.local
   - www.cornerstone.local
   - testy.cornerstone.local
   - www.howardhannamortgage.local
   - testy.howardhannamortgage.local
   - testy.fntg.local
   - testy2.fntg.local
   - api.cardtapp.local
   - admin.mortgagedev.local
   - testy.cardtapp.local
   - www.cardtapp.local

services:
 - mongodb
 - selenium
 - redis

before_script:
 - mkdir -p shippable/testresults
 - rm -f shippable/testresults/*
 - spec/scripts/create_config_files.sh
 - rm -rf cornucopia_report

script:
 - set +e
 - date
 - rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml
 - cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd ..
 - set +e
 - DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults

after_script:
 - cp -r cornucopia_report shippable/testresults
 - date > shippable/testresults/end_date.txt
 - cat shippable/testresults/end_date.txt

# - bundle exec rake jasmine:ci RAILS_ENV=test

# see: http://docsv2.readthedocs.org/en/latest/config.html
env:
 - secure: qbXuuO7YiDrT2a5C91NtySbF7hyHufIW6xHjaXYh+wOgUySQ4gukXiMGgBked1k9G9PzQa4b7QzwdnqWc2EsPRPC74EWQOK754IfVAurMKsvilDTMvYIWhMJcDSru5twtuVo7EFvQwaq8sC3otfcOpbwNddeMNbSGY3KIyW0V4tpZ1F+3L7Yln0we9WnR4RAGCr2i3Br6EqwtFgE63VOmjD7SGYK/DdMGMIdzivbHfalrYbuOxW0EB2vs/7XAThhGrL31FBmV3NhEBDMqbTbnZu6IG3k2jtlWg4sSlhGwwUGxSKHOAdbQqqONTUgNwVwszx7mGUya5gMbTqr5sBQBqDGrS54hhgPGktsivTt3MKtxRCcM9FEvj2b1O/kVHvnPkQr/MZxK91S6NYuHxx2NUMf2auiuIDSWspFuzDRlJ05/4CezfjLhd0wvCDTIdRN5aqicWOzXEYDJ2rVJVJCrGb44L6wuq7COWXsp7e0mGHpt4r5x3LGSwuIhIuv7Gul+ZB0SkMZCV24ddP0nV+tOtWWIFi1Now5Hs49vH4igvLENoX2pF8KTaAmXKy/RJMZkOs3hJrzup96333kugAVt8rb199qinDAhx2f+Fo05ncLZg2xMFtrVoBN4BuQdBGEUk4nJp+LNpPM1yyjPbZUXwT+/knYQSdgNHOyv/qaPBZDgoBjAsBYmtg3l2CVjFO8GKnjXM9H1PQISLC7d1j2+wwZP3wFwNnP7RS+LltiZhYfzYqiw1trlgXeUDwR+PdSfdGp0vmZGEc+xdBKUEOC9JYHpfe0TTyDlIL3r8C4yrkOsYFIzAa9z1DwQMn+olwYth3AvwrvTZawSCF1ljG8HGUTmLhKKS2ALbwmDHxDRMlHNbrOUPdRIrZJBN881EVk0qQUgVRT9na0ZIZO/5L0s9nbAlvem2AKAYtKv//KEcSksYFNM/t2INiNqgD2eWCh128DYbJ6+E81f/pmz0AFal++b35wQNeJreoFedKo63EDcbKJePoScWke+XBCCAHWogz1lTRmqOEn3jCZZYDXdOwf+Ayv6j56xmbME1njQjVmLFgIfAqnpUwT4yI4NcmBgF4lYzY7aC+2k4wgrn7UV4/IODKHn8D3gAuBUF1ZcyUFGFwcgod6xF3S2SeVJYrdrMNekNbj9WhD55NF+iuaY4J/J244ZmtPnpnTtsuRodCGeXWxPRLKxsks9bYwBN2gsNK/al9B8ey3JYTqYpv6/g/97iIVBp5DIp7MiJX4Av45IneOEe3CgNZIxTNhYSMSxgTZsYVV/f4FiuC0EltX21Zz/FXgSkSqcTODndHlx9hbuMbmdYMWDYS/N/GgIUaz6UkaThTX3l5sm8h5tdDGliZ6kT2wTgQAcfT3iDPEs7qD9YwS5OGOsNdBQr8Dun39pYQVYuQ8RZ1vD00/54LXV/mijbdE30uGZ5SWiemr5MPASgQ6p4H+eDqJm6jmgBVRCcYZd3/TVBNjsb6eG5ZWGzeSNy9/ls9AGWubwFa7jISh25CBgq1sC+Aj586HZS7Y9+CoQy4rb4hLa25PaLHJGZNgtL0SBzs+C+0Ur297PqZehRsVRPfw01MuJEdW0ESs2RTigx1/r5SJnoch/uj+zzKzmMqZbIHiC49KfMPcWzT5HqOQ0QqwAxMKXukEhWaKe0nIk0xYGVayJkKvW5gPvX3M2afF4aAAWlKqKJrxpYuYBBBuJD9NG5kGGQGaVOnPJ+dAre4XWQpeQBJbRD0NhI6hiSwYaBlrFdBPgyfIW9DI346TrUz8VzBlSXNEFqJdEz0KyREzU8sfXhYQK2tlITEiuF+eu4nDDxpCKw1GHD2KZwTrtzFw34DnKp8U/DJ/guBVhOOKxd3R8CgpID4LwL+NSCk2bB8AHmXr3A2HAwc2TwkMUo3dBX8AkuewVM0wxihjY68uaI8naMRb/Q3lb33BDtcibI+jcGoSPMXa33k88u5TWN456CbSsXC/+JD7aHiCfJ9fxxpLUKmj78gUg9Fbzr0jsAXJKOctrScMk5Hq4apj3ox0Kta6fNS5pccoUrjc0XDxR/MdEvNJ3GSRzq+LT1yENMDFJeECW5XbahmX5o1GuVh0HGX3uhhDU+q5BFSvg9I51z8Ao6t3I7FqxCqFwFpotzjHAI1T6HkdD3wpIc96dR8GU/ilbxWUz6dlntWeUoyVygCZUfIoGjkp4QbxX152uxseWQqLER8DRMKBcGc7qwRmuoQCJ4GW0yYKdM91CISDQryF0h7vddgzG1f1o/2sXo0g16CsFS79c8rw/M9d8qp7Pt3l0qN7+Fr9GvhSGvZXUgvXS3wujlWc2RIdcCqMQe8cW+sTPVnJDavu4k55e8JbL/YxZ4sbg6WqBqzWEdKX+GBqD5ttnNLPAQ==
#  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

notifications:
   email: false
```

NOTE:  I don't like the `set +e`.  I think it is a bad idea.  The ONLY reason I did/do it is because it seemed to fix the problem I was having of not getting uploads when Cucumber failed.  I found a different solution later.

**Comment by RealNobody** [comment]
The different solution.

I am currently testing the following YML file:

```
language: ruby
archive: true

rvm:
 - 1.9.3-p392

node_js:
  - "0.12.2"

install:
 - mkdir -p shippable/testresults
 - rm -f shippable/testresults/*
 - date > shippable/testresults/start_date.txt
 - cat shippable/testresults/start_date.txt
 - cd dashboard && npm install ember-cli@0.2.5 --save
 - npm install bower --save
 - npm install
 - bower install
 - node_modules/.bin/ember build
 - cp dist/assets/vendor.js ../app/assets/javascripts/vendor.js
 - cp dist/assets/dashboard.js ../app/assets/javascripts/dashboard.js
 - cd .. && shippable_retry bundle install --gemfile=Gemfile

addons:
  firefox: "28.0"
  hosts:
   - www.mortgagedev.local
   - testy.mortgagedev.local
   - www.agentdev.local
   - testy.agentdev.local
   - www.insurancedev.local
   - testy.insurancedev.local
   - www.cornerstone.local
   - testy.cornerstone.local
   - www.howardhannamortgage.local
   - testy.howardhannamortgage.local
   - testy.fntg.local
   - testy2.fntg.local
   - api.cardtapp.local
   - admin.mortgagedev.local
   - testy.cardtapp.local
   - www.cardtapp.local

services:
 - mongodb
 - selenium
 - redis

before_script:
 - spec/scripts/create_config_files.sh
 - rm -rf cornucopia_report

script:
 - bash script/run_shippable_tests.sh

after_script:
 - cp -r cornucopia_report shippable/testresults
 - date > shippable/testresults/end_date.txt
 - cat shippable/testresults/end_date.txt

# - bundle exec rake jasmine:ci RAILS_ENV=test

# see: http://docsv2.readthedocs.org/en/latest/config.html
env:
 - secure: OrzbzAZCOYsfJVw28AU2t6QEnNm0gJRA7JtVO9ECb4tkatvq5i/wH1rm4mvVOHMWlsLVu9SvQfkE3K0hbddZnbjUtvsGhBxeoCkl0A7UZAAxfJtkx8700K+3I6EH7ZvPKgnB4e5NOuYieXRiAcc4DsLiXytFmjLlN8giIMWqLDCGLb4TA1JOdqHaez2eYtQdOHQ+0yemzAIGjMVH67ODAE+2Gj0ACX/haXYsPIztXCqXfgPeHTgZp7nbB2Gph+z5GunS8hDdM25XIRbDDuJvi0F/gtfam7IQKW+5XJA4jCDDE+L4EDf+q7MY0PmNxO+77z7/0vkvuLWfmed/hgvMfAPLyKwA4yO+5lEdgEwKYnWbtV6XmBsin4s17R+3/sYzJSpWzYUst0P9scWOsPjh+zwWBGgS53m/gx4xpulmRCL18tM+Vcfg9RR9q5xCFY5OTjchFYPR76x3e+Qc3PaFyT28I0bUtLCEBaJVN7cHIwfthN64Hr4zICLzFqNKp8p597llDOomlVeo4Q8yrVuVP+kb7omjvUhYYzedEaZ4/wjyc7h0I0rF0lc1zJhyWit1VppvdFoU/hhryx6sByly98ftpgqFj26ohgeVFwgYuVW9rZMiGkwZmtculCe887M4sKbqCkNJzBGDlOecBp4ihj475JdkXknAe1xu/+jgMlGZztAD5jGhcVmqQfZiFuX3ZZJ7Jrn9wkEXEXdrg4TUECEuPQt9l8I49BtX+nDdkwutjo054DM0vOL6YGNDzi+ybhX26sUz8Czk2sTRAegGLGnXvLviUbPrY2en3Yq1KwypKYmY6bYymJj2/eXjpLfhQIm1kth+KFhVGLk9WwQtL586XKIipD8k1TwnnIk1T9BdhXfL4iGB13hVeKwrYAwn8OGqDPy/dKwJkU2Vbtgs+xdHeV9bBvqdNP7bBKtiRZ2KiHGX3C18CCAvMV6gZ8Ki4U3bRKPfZ2Phu6y5zJwfAycmgLwgIZ3tLxvghe5SoV8/0oXDgUDyILMcqqeFo7h+QSTg+KjdHzLbEmzD1QWQCBhxLaevsF/iG1M3gvCkD/Rg7yXc4ppWpVeTuLzrjW+UWnoI1lpWfuezdtewNhc4hvTuqdaPBQNV2LUsFZidT+WFw24Dy6A635jpRXO6qKb1KrobFm/+ZoOvyLzI0uYHN1pIEDnzZ3H1+Sn+pKQTdCnFbXQAzHq0EJIR4TngxWDHXxBMSiN8tA+3+i4oEDp+pms2mBm3B9TMTzc4O86d5PNwu4li8jkLns5Za4s9WL+swg+g8EQ+YbqJobixDnIxv7VQ8lkPdvsdLqrdOulnlHFnVuIjjx3hkFESufQOS+f4Ewj8tPQU+bDqYzkjxcoHUGApD2uNYtgEhirqBYV4SCQhDhjhm8ZxWGErYS2FOMGMS++4DGTWr7ODLnSOrNsNNduxz1PtBJTA3VAixUXhm7cZQKfuR+kE7XG0CyDjMiDOMUGg0mAiNr6hnKAX9vbZ6phjRnHQBnVkqXhNS0gZ3WtPxaJv966+jp+DY0VGCFzvrb9U9haPn0KAoiSvI+d4dDGWKQqArx3aLT4OGT/iUyu80ff8OPbwUFBTNjveZWHjGYrUN1JKwKnTpjvJKw7v/Es4JQfcK0R6IiXG6Jd+16pR2dmQ2yQjAyasbMy7nuuX+7XnzV+oV8ei/CNpngXazqbSPtUZfvMhdmu9t9QWBqctjmd0Hditpo3Jxwf/+GRvJFkb2bubw3zCv+O9NGJkacQMhvLEwEo6VrtjImNvkzqD5xYTl2Qlt5Izkcbl/TIBS+x/koSyCsfLnHys9XUtwHz50y1sxRw3l3Ka8oSpAvEpqHYWW1yFbfoL5wiFj8PlVCzPeOec9DUbdghm5hGCBigmoODDbCpXwrqSZ0Z0t5Iz13TXSkOOMqqnRc3xZ8l0jS/eGdy1NO55XRFeqYUjC+s9osrnHxIqwqll6bl6BSj/j3BmsHAu8xVuxpV0+4WZ401Ub9NVXzPcfXUjN/lf5mYlw+ciXFhMBtT5a6OBgGua/nRN84S5ZppHzuzF99O+jnr98KVDgVR8Ly78plRN4brJMLZu3ETIy3ZkkVG5kv6kbIpBUrmGNxQi2QD5CkmXhxjBaBmVswAOVwQ8ZhFRD2PZ+IbBWCZDoY/MkK2EfRf8hmWBM5XXcF6kIjvREJP849/38hUmyhegcO8ob7MRhTH/lhtjrCIPnl/fz99u/R+vo/Z59m4E9ACsStBBJ1+VCauJjbbsGmLntc4BOMgHrrGVo/AJBgAKaqBI5XfFz7tbExSY0tpKLjE14/XSJxSbksMi/IjqpHbLsPwwAUrALH3uJW69nuT4/0keZY1BXysQoOe8wVVX1u5ZfcULIEV4BEwh+yak+z0gbUi+0HGZ2w==
#  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

notifications:
   email: false
```

Where the script file is:
```
#!/bin/bash +e

function set_param_value
{
  # This funciton sets the passed in value to a variable.
  #
  # PARAMETERS:
  #   ${1}  - set_var - The array variable to append to.
  #   ${2}  - set_val - The value to append to the array.

  set_var="${1}"
  set_val="${2}"

  # OK, I admit it, I don't know why this line works exactly, but it does
  # and I couldn't figure out something that would work the way I wanted it to
  # so, I'm just leaving it as is.
  # if you put "'s arond the line here, it breaks.
  # set_val=${set_val//\"/\\\"}
  set_val=${set_val//\'/\'\"\'\"\'}
  eval ${set_var}="'${set_val}'"
}

function execute_command
{
  # This executes a command and echos the output.
  #
  # NOTE: The value of success_return_var may not be accurate if the
  #       value of file_to_echo_to is set.
  #
  #       If file_to_echo_to is used, you should parse the output
  #       to validate success.
  #
  # PARAMETERS:
  #   ${1}  - command_to_execute      - The command to execute
  #   ${2}  - file_to_echo_to         - A file to output the text into.
  #   ${3}  - success_return_var      - The variable to return the success/failure in
  #   ${4}  - execute_text_return_var - The variable to return the text in

  command_to_execute="${1}"
  file_to_echo_to="${2}"
  success_return_var="${3}"
  execute_text_return_var="${4}"

  if [ ! -z "${file_to_echo_to}" ]; then
    echo "$(pwd) \$ ${command_to_execute}" 2>&1 | tee -a ${file_to_echo_to}
  else
    echo "$(pwd) \$ ${command_to_execute}"
  fi

  if [ ! -z "${file_to_echo_to}" ]; then
    command_to_execute="${command_to_execute} 2>&1 | tee -a ${file_to_echo_to}"
  fi
  if [ ! -z "${execute_text_return_var}" ]; then
    command_to_execute="execute_text=\$(${command_to_execute}"
    if [ -z "${file_to_echo_to}" ]; then
      command_to_execute="${command_to_execute} 2>&1"
    fi
    command_to_execute="${command_to_execute})"
  fi

  if [ ! -z "${success_return_var}" ]; then
    set +e
  fi
  eval "${command_to_execute}"
  execute_command_successful="${?}"

  echo "execute_command_successful = ${execute_command_successful}"

  if [ ! -z "${success_return_var}" ]; then
    set -e

    # for this script, I want the +e always set
    set +e
  fi
  if [ ! -z "${execute_text_return_var}" ]; then
    echo "${execute_text}"
  fi

  if [ ! -z "${success_return_var}" ]; then
    set_param_value "${success_return_var}" "${execute_command_successful}"
  fi
  if [ ! -z "${execute_text_return_var}" ]; then
    set_param_value "${execute_text_return_var}" "${execute_text}"
  fi
}

function do_stuff
{
  overall_success="0"

  current_directory=`pwd`

  echo "current_directory = ${current_directory}"

  cd ${current_directory}

  echo "Date:"
  echo `date`
  echo " "

  execute_command "bundle exec rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml" "" run_success ""
  cd ${current_directory}

  if [ "${run_success}" != "0" ]; then
    echo " "
    echo " "
    echo " "
    echo " "
    echo "RSpec tests failed!"
    overall_success="1"
    echo " "
    echo " "
    echo " "
    echo " "
  fi

  execute_command "cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd .." "" run_success ""
  cd ${current_directory}

  if [ "${run_success}" != "0" ]; then
    echo " "
    echo " "
    echo " "
    echo " "
    echo "Ember tests failed!"
    overall_success="1"
    echo " "
    echo " "
    echo " "
    echo " "
  fi

  execute_command "DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults" "" run_success ""
  cd ${current_directory}

  if [ "${run_success}" != "0" ]; then
    echo " "
    echo " "
    echo " "
    echo " "
    echo "Cucumber tests failed!"
    overall_success="1"
    echo " "
    echo " "
    echo " "
    echo " "
  fi

  cp -r cornucopia_report shippable/testresults

  if [ "${overall_success}" != "0" ]; then
    exit 1
  else
    exit 0
  fi
}

do_stuff
```

I am much happier with this solution.

Yesterday (unrelated to Shippable) we had 2 breaks in our code that broke all 3 test suites (RSpec, Ember, and Cucumber.)

With this YML and script solution combination, I was able to identify the causes of the breaks where I had been unable to do so on any other branch because of the `after_script` and the `upload` not working.

The script is ugly (I know), but it does work.  Basically, all I did was I moved the calling of the 3 tests out of being called in-line and into a script where the +e is isolated to to just this script (which makes me much happier at least.)

All the other garbage in the script is my attempt to echo what is happening to the console and to make sure that at the end of the day, if any one part fails, the script fails so that I get a valid red or green result in the Ember console.
