### ISSUE TITLE
Shippable always compiles node

### ISSUE THREAD

**Issue by czardoz** [Shippable/support#1881]
Looking at the logs,

```
mv: cannot move `/home/shippable/.nvm/bin/node-v0.12.7-linux-x64' to `/home/shippable/.nvm/versions/v0.12.7': No such file or directory
```
My Shippable config is here:

```
language: node_js

node_js:
  - 0.12.7

# build settings
notifications:
  email:
    recipients:
      - <removed>
    on_success: change
    on_failure: always
cache: true

services:
  - mysql

addons:
  postgresql: "9.3"

install:
  - npm install -d

before_script:
  - mysql -e 'create database if not exists mower_test;'
  - psql -c 'create database mower_test;' -U postgres
  - export source__uri="mysql://shippable@127.0.0.1/mower_test"
  - export destination__uri="postgres://postgres@127.0.0.1:5432/mower_test"

# test script to be run
script:
  - npm test
```

**Comment by czardoz** [comment]
Looks like this is the same issue as #1352

**Comment by lekhab** [comment]
@czardoz -- can you please try the suggestion from 1352 as a workaround? This worked for similar cases.  (You could also use our custom nodejs images, but it is barebones and you will have to install any other service you need on top of that)

Remove the `node_js:` version key from  `shippable.yml` and install node 0.12.7 manually in `before_install`

*shippable.yml*
```yml
language: node_js

# no node version specifier

before_install:
  - mkdir -p ~/.nvm/versions
  - source ~/.nvm/nvm.sh && nvm install 0.12.7
```
