### ISSUE TITLE
Caching npm modules

### ISSUE THREAD

**Issue by pastawoua** [Shippable/support#1892]
I've enabled caching on my project but the npm packages when running npm install aren't cached between builds. Do I need to do anything differently?

https://app.shippable.com/builds/55ffa83a58124d0d00ef8f1a

```
language: node_js

node_js:
  - 0.12.7

env:
  global:
    - NODE_ENV=develop
    - TZ="Australia/Sydney"

before_install:
  - apt-get update && apt-get install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version

install:
  - npm install
  - npm run postinstall

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" npm run shippable-test

notifications:
  email: false
```

Thanks,
Brice
