### ISSUE TITLE
Installing PostgreSQL 9.4 in shippable.yml

### ISSUE THREAD

**Issue by TimHolahan** [Shippable/support#1901]
Hi.

Like those of [many of your would-be clients](https://github.com/Shippable/support/issues/1092), our stack requires PostgreSQL 9.4. 

Per your instructions in response to [this issue](https://github.com/Shippable/support/issues/1446), I've installed it in shippable.yml. Here's the YML block:

```yml
before_install:
  - sudo service postgresql stop
  - sudo apt-get remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - shippable_retry sudo apt-get update -y -q
  - shippable_retry sudo apt-get install -y -q postgresql-9.4-postgis-2.1 postgresql-client-9.4 postgresql-contrib-9.4 postgresql-plperl-9.4 --fix-missing
  - echo 'host all all localhost trust' | sudo tee /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
  - echo 'local all all trust' | sudo tee --append /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
  - sudo service postgresql start
```
(I should mention that we're using the **shippable/minv2** image, not a barebones language-only image as you suggest, because we encountered difficulty finding the additional postgresql packages we need on **ubuntu1404_ruby**, despite apt-get update.)

The commands above all seem to work. The output from the last command is:
```
 * Starting PostgreSQL 9.4 database server
   ...done.
```
However, when the build gets to this crucial line in our before_script block:
```yml
  - psql -c 'create database "broadstripes_test";' -U postgres
```
... it fails with this output:
```
Error: Specified cluster does not exist locally and does not specify a remote cluster
```
**What do we do to fix this?**

By the way, the "create database" line works when we use your addon for PostgreSQL 9.3. Unfortunately, we can't proceed to set up our data model and run tests in that version for compatibility reasons.

**Comment by shaneog** [comment]
:+1:

**Comment by jamescgibson** [comment]
For what it's worth, copying this before_install into my .shippable.yml worked just fine. 

I ran into an issue in which Postgres PG::Error: ERROR: new encoding (UTF8) is incompatible was thrown. Adding "template: template0" to config/database.yml (in a Rails 4.2 project) solved that.

**Comment by goosetav** [comment]
this is working for me:
```yaml
build_image: shippable/minv2

before_install:
  - sudo service postgresql stop
  - sudo apt-get remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - shippable_retry sudo apt-get update -y -q
  - shippable_retry sudo apt-get install -y -q postgresql-9.4-postgis-2.1 postgresql-client-9.4 postgresql-contrib-9.4 postgresql-plperl-9.4 --fix-missing
  - echo 'host all all localhost trust' | sudo tee /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
  - echo 'local all all trust' | sudo tee --append /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
  - sudo service postgresql start 9.4
  - sudo env

addons:
  # this was the key line; it causes the initial service install to fail but seems to set whatever ENV var is needed to make it all work
  postgresql: "9.4" 
```
