### ISSUE TITLE
Run tests as non root user

### ISSUE THREAD

**Issue by antonbass** [Shippable/support#1908]
Hi,

Some of my unit tests spawn a temporary postgres instance. These don't work on your build system as postgres refuses to run as root.

Is there a way to run the 'script' section as a non-root user?

I know you have a postgres addon, but this is not an easy option for us to use.

**Comment by rageshkrishna** [comment]
This is now possible with the new build system. You can get your build container to run as any user with the `pre_ci_boot` section of the YML:

````
build:
  pre_ci_boot:
    image_name: your/image
    image_tag: latest
    options: "--user foo"  
````
