### ISSUE TITLE
PHP5.5 + Mongodb fails

### ISSUE THREAD

**Issue by leipert** [Shippable/support#192]
Hello there. Our php 5.5 Setup with mongodb fails with the following error:

```
phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
PHP Warning: PHP Startup: Unable to load dynamic library /home/minion/.phpenv/versions/5.5.9/lib/php/extensions/no-debug-non-zts-20121212/mongo.so - /home/minion/.phpenv/versions/5.5.9/lib/php/extensions/no-debug-non-zts-20121212/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

Our config file seemed to work with travis-ci. Here is our config file:

``` yaml
language: php

php: 
  - 5.5

services:
  - mongodb

before_script: 
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction --prefer-dist --dev

script:
   - phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage

notifications:
   email: false
```
