### ISSUE TITLE
SFTP errors with `gulp-sftp`

### ISSUE THREAD

**Issue by krispy1298** [Shippable/support#1948]
U: kamilkecki (bitbucket)
Project ID: 561f2ca34ae4dc0c003e014f

Trying to deploy to a server using `gulp-sftp`. Getting error:
```bash
[04:37:25] Authenticating with password.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

with this script:
```js
import gulp from 'gulp';
import gutil from 'gulp-util';
import sftp from 'gulp-sftp';

gulp.task('deploy', function () {

  gulp.src([
    './dist/**/*'
  ], { base: './dist', buffer: false })
    .pipe(
      sftp({
        host: 'XXXX',
        user: 'XXXX',
        pass: 'XXXX',
        remotePath: 'XXXX'
      })
    );

});
```

My yml: 
```yml
# language setting
language: node_js

# version numbers, testing against two versions of node
node_js:
  - 0.10
  - 0.11

before_install:
  - npm install -g gulp

install:
  - npm install

before_script:
  - mkdir build
  - mkdir dist

after_success:
  - gulp dist
  - if [ "$BRANCH" == "auto-deploy" ]; then gulp deploy ; fi
  - if [ "$BRANCH" == "auto-deploy" ]; then gulp deploy ; fi
  - if [ "$BRANCH" == "auto-stage" ]; then gulp stage ; fi
  - if [ "$BRANCH" == "auto-stage" ]; then gulp stage ; fi

branches:
  only:
    - master
    - develop
    - auto-deploy
    - auto-stage

```
