### ISSUE TITLE
Unable to add email-notification to project

### ISSUE THREAD

**Issue by janober** [Shippable/support#1988]
I did set up two "notification : Email" in my account but are unable to use it on a project. When I go under:
"Project Integrations" => "Notification"
it displays: "No notification integration added"
and there is nothing else to select.

Thanks!

**Comment by janober** [comment]
Not having gotten an answer for 2 days and seeing that other people have not received one for 6 days and more, I really wonder if you are the right choice for any business. Having a good product is not enough, especially if you make your potentially soon paying customers wait an unnecessary long time. That is just does not give someone confidence into your product & company.

**Comment by kanthchandra** [comment]
Hi @janober , I'm sorry that we couldn't reach out to you earlier. Currently we support only Slack notification in the project settings. To add email notification, you will need to add the following config to your `shippable.yml` file.
```
notifications:
     email:
         recipients:
             - exampleone@org.com
             - exampletwo@org.com
         on_success: change
         on_failure: always
```
the documentation on this can be found at http://docs.shippable.com/yml_reference/#email-notifications

Please let us know if you have any more questions. We will be happy to help you.
