### ISSUE TITLE
Cannot execute .phar signed with subscription key

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1993]
We are currently taking an approach to have a `foo.phar` built on Shippable using the PHP [Box project](http://box-project.github.io/box2/) and have it signed with the private subscription key available to all of our projects and builds via `~/.ssh/id_rsa`.

However, providing the matching public key available via `~/.ssh/id_rsa.pub` afterwards as `foo.phar.pubkey` fails which you can see in [this build](https://app.shippable.com/builds/5638cd5d7731c20c003f7a83). The mentioned `foo.phar` was built and signed with [this build](https://app.shippable.com/builds/5638caf595b39b0d00541b48).

It only works if we make the `foo.phar.pubkey` generated on build available for download which defeats the purpose of signing since we need a trustworthy origin for the public key.

Am I misunderstanding something with the [subscription key](http://blog.shippable.com/demystifying-shippables-deployment-keys) or is there some other error here?

**Comment by mbrodala** [comment]
I now found a solution. The following setup works:

```yaml
env:
  global:
    - ...
    - |
      FOO_PUBKEY="-----BEGIN PUBLIC KEY-----
      ... armored public key output ...
      -----END PUBLIC KEY-----"

script:
  - ...

after_success:
  - >
    ...
    echo "$FOO_PUBKEY" > foo.phar.pubkey;
    php foo.phar ...;
```
