### ISSUE TITLE
composer self-update doesn't take and sudo composer self-update breaks phpenv

### ISSUE THREAD

**Issue by schroedad** [Shippable/support#2033]
If I run "composer self-update" in the before_install section, then the composer install command tells me that composer is over 30 days out of date and throws the error: "[UnexpectedValueException]          Could not parse version constraint ^1.0: Invalid version string "^1.0"".

If I change to "sudo composer self-update", I no longer get this error but then I'm told phpenv doesn't exist, which I read somewhere else is a problem when you do a "sudo composer self-update".  How can I get around this? Below is my current shippable.yaml:

```yaml
language: node_js

php:
  - 5.5
  - 5.6

before_install:
  - npm install -g gulp
  - composer self-update

install:
  - npm install

before_script:
  - mkdir -p build
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - composer install --no-interaction --no-scripts
  - echo "xdebug.max_nesting_level = 250" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ./node_modules/.bin/gulp

script:
  - ./vendor/bin/phpunit -c phpunit-shippable-fast.xml
```
Here are links to the 2 different failed builds:
https://app.shippable.com/builds/564ab6e62299470d002452f4
https://app.shippable.com/builds/564ab1222299470d0023cd6c
