### ISSUE TITLE
Get "phpenv config-add" working

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2140]
To speed up our PHP builds I tried the following:

```yaml
before_install:
  - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
  - phpenv global $SHIPPABLE_PHP_VERSION
  - phpenv config-rm xdebug.ini

before_script:
  - composer ...

script:
  - phpenv config-add xdebug.ini
  - bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
```

The goal is to disable Xdebug for Composer invocation (see [Xdebug impact on Composer](https://getcomposer.org/xdebug)) and re-enable it for PHPUnit invocation. However, this fails with the following error:

> File xdebug.ini does not exist.

Is there a reliable way to determine the absolute path of the `xdebug.ini` to satisfy `phpenv config-add`?
