### ISSUE TITLE
Timeout for build while trying to implement Shippable support for our project

### ISSUE THREAD

**Issue by kaspernj** [Shippable/support#2155]
I continue to get timeouts for this build:
https://app.shippable.com/builds/56812666493a190d007a5e14

I am trying to make our project build on Shippable, but I don't know why it times out?

**Comment by manishas** [comment]
can you share your shippable.yml.... especially what changed between builds 46 and 47?

**Comment by kaspernj** [comment]
@manishas The change was that I added Redis to the services. Otherwise all tests failed. Here is the output from Github:

```
   firefox: "28.0"
  services:
    - selenium
 +  - redis
  env:
    global:
      - DISPLAY=:99.0
```

Here is the "shippable.yml" file:
```yaml
addons:
  firefox: "28.0"
services:
  - selenium
  - redis
env:
  global:
    - DISPLAY=:99.0
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS shippa;'
  - cp config/database.shippable.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load
  - /etc/init.d/xvfb start
after_script:
  - /etc/init.d/xvfb stop
language: ruby
cache: bundler
archive: true
rvm:
  - ruby-2.1.2
script:
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec haml-lint --exclude vendor/
  - bundle exec scss-lint app/assets/stylesheets
  - bundle exec rake coffeelint:lint_naoshi
  - bundle exec rails_best_practices
notifications:
   email: false
```
