### ISSUE TITLE
PHP xdebug.ini randomly missing

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2186]
A few of our latest builds fail because the `xdebug.ini` is missing while it shouldn't. ([Example](https://app.shippable.com/builds/568f690a340dc90c005d2abc)):

```
cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
cp: cannot stat ‘/root/.phpenv/versions/5.5/etc/conf.d/xdebug.ini’: No such file or directory
```

Our `shippable.yml` does something along these lines to boost Composer performance:

```yaml
before_install:
  - ...
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini
  - composer ...

script:
  - phpenv config-add /tmp/xdebug.ini
  - bin/phpunit ...
```

Rebuilding sometimes succeeds though, we haven't tried clearing the cache yet.
