### ISSUE TITLE
Shippable Node Language 0.12+ Support

### ISSUE THREAD

**Issue by 4ndywilliamson** [Shippable/support#2187]
When using this in the shippable.yml file:

language: node_js

node_js:
        - "0.12"

It has to compile a new version of node which takes forever to build before running the rest of the build script.

I understand that the documentation allows node_js: - "0.11" as a default but some packages that we run require "0.12" and above.

Please could you add this version or allow a quicker way of building this.

I have used this:

- mkdir -p ~/.nvm/versions
- source ~/.nvm/nvm.sh && nvm install 5.4.0
- node --version

It appears to download and use node version 5.4.0 but when installing node dependences, it still thinks that the node version is less than the one required.

Example:

(current: {"node":"0.10.33","npm":"1.4.28"})

Please could you rectify this or send us a workaround?

**Comment by manishas** [comment]
Our default image minv2 does not have node 0.12 installed. Can you try using the image at https://hub.docker.com/r/drydock/u14nodpls/ and let me know if that works better?

You'll need to set this image in your docker options in project settings. Let me know if you need help with that.

**Comment by 4ndywilliamson** [comment]
So, adding this into our project failed the build as any node commands would return as command not found?

Is there any ETA when node 0.12 could be added to minv2?

Would be really useful!

**Comment by chriskinsman** [comment]
Have to add a line like:
- . /root/.nvm/nvm.sh && nvm alias default 4.2.2

To your before_install.  Pick your node_version...

**Comment by manishas** [comment]
@4ndywilliamson did the suggestion above work for you?

**Comment by pukapukan** [comment]
personally - coming out from my own experience, I find using official node image is the easiest way to get around all the issues related to the the node versions

throw this into shippable.yml should work like charm

build_image: node:latest

**Comment by naxmefy** [comment]
hi - got same problem with ``` image shippable/minv2:latest (id: 63655319ed5c) ```

tried this:

```Yaml
# Language setting
language: node_js

# Version number
node_js:
  - 0.12
  - 4.2.2
  - 4.2.6
  - 5.5

services:
  - mongodb

before_install:
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version
  - npm install -g istanbul
  - npm install xunit-file

install:
  - npm install

script:
  - npm test
```

Results:

* 0.12 could install
* 4.2.2 ``` nvm: install v4.2.2 failed! ```
* 4.2 (-> 4.2.6) ``` nvm: install v4.2.6 failed! ```
* 5.5 (-> 5.5.0) ``` nvm: install v5.5.0 failed! ```
