### ISSUE TITLE
Heroku push error: src refspec develop does not match any

### ISSUE THREAD

**Issue by aliismayilov** [Shippable/support#220]
I followed instructions on [documentation](http://docs.shippable.com/en/latest/config.html#continuous-deployment) (e.g. added deployment key from [this url](https://www.shippable.com/settings/keys) to [this url](https://dashboard.heroku.com/account)).

Here is my `shippable.yml`:

``` yml
language: ruby
rvm:
 - 2.1.2
before_script:
  - psql -c 'create database edu_rails_test;' -U postgres
  - mkdir -p shippable/testresults
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
script:
  - rspec --format RspecJunitFormatter --out shippable/testresults/results.xml
after_success:
  - git push git@heroku.com:edu-rails-staging.git develop:master
```

Build is passing fine. But I get the following error on `after_success`:

```
git push git@heroku.com:edu-rails-staging.git develop:master
Warning: Permanently added the RSA host key for IP address 50.19.85.156 to the list of known hosts.
Fetching repository, done.
error: src refspec develop does not match any.
error: failed to push some refs to git@heroku.com:edu-rails-staging.git
```

It works fine if I try to push from local machine.
