### ISSUE TITLE
build artefacts in sub directories?

### ISSUE THREAD

**Issue by cloudkite** [Shippable/support#222]
I am trying to deploy the results of a gulp build which outputs to a dist folder in the working directory. I thought I could achieve this by copying `./dist/` to `./shippable/dist/` however if I run a bash on heroku I see all my other files but not the dist folder. Are only the files in ./shippable copied across and not subdirectories? I want to maintain the folder structure.

``` yml
language: node_js
node_js:
  - "0.11.13"
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/dist
  - rm -rf dist
script:
  - node_modules/.bin/gulp dist
  - cp -R ./dist/* ./shippable/dist/
after_success :
  - git push git@heroku.com:whatever.git master
```
