### ISSUE TITLE
Environment Variables not getting picked for using with code deploy

### ISSUE THREAD

**Issue by battuashwik** [Shippable/support#2225]
Uploaded a screenshot of the build and my yaml file. the ********************* are my access Id and keys

<img width="989" alt="screen shot 2016-01-25 at 2 47 10 am" src="https://cloud.githubusercontent.com/assets/944924/12548889/4ecd5832-c30e-11e5-8b9e-f130e53660a0.png">
<img width="949" alt="screen shot 2016-01-25 at 2 50 51 am" src="https://cloud.githubusercontent.com/assets/944924/12548931/9182c46e-c30e-11e5-8b63-55f3a89c9749.png">

**Comment by battuashwik** [comment]
Can u guys help me with this issue. Last integration for me to go ahead with the subscription

**Comment by rageshkrishna** [comment]
Hi @battuashwik! The problem is the way your env's are defined in the YML file. The way you have defined it results in a matrix build, with each build having just one line of the env's in your YML file. To get what you need, please change your YML file to use the `global` setting, like this:

````
env:
  global:
    - XUNIT_FILE=shippable/testresults/result.xml
    - AWS_ACCESS_KEY_ID=...
    - secure: *****
    - CD_APP_NAME=...
````
