### ISSUE TITLE
Python 3 and Node not working

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#2242]
I've been using the following shippable config on our project for awhile. Which works fine most of the time. It uses `language: node_js` instead of Python because we wanted to use `gulp-jshint` for linting our Javascript files as well as running our python test suite. So My question is how do we change your shippable config so it works with Python 3, because we've just now converted our project to Python 3.

```yaml
language: node_js

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - "2.7"

services:
  - redis

before_install:
  - npm install -g gulp

install:
  - /home/shippable/shippable_ve/bin/pip install -r config/requirements/testing.txt --use-mirrors
  - npm install

before_script:
  - mkdir -p docs/admin/_static
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - which pip
  - which python
  - which coverage
  - which flake8
  - flake8 --version
  - pip freeze
  - make lint
  - coverage run manage.py test -v 3 --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```

I've done some testing and the following config just prints outputs `Python 2.7.3` as the Python version.

```yaml
language: node_js

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - "3.4"

services:
  - redis

install:
   - echo "hello World"

script:
  - which pip
  - which python
  - which coverage
  - python --version
  - pip --version
```

**Comment by epicserve** [comment]
FTW, I switched back to just using the `language: python` so I could get my tests to work, but I would still like to get node working as well so I could run my linter. The following is my current config.

```yaml
language: python

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
  - 3.4

services:
  - redis
  - mysql

install:
  - pip install -r config/requirements/testing.txt --use-mirrors

before_script:
  - mkdir -p docs/admin/_static
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - which pip
  - which python
  - which coverage
  - which flake8
  - python --version
  - pip --version
  - pip freeze
  - flake8 . --ignore=E501,F403,E402,E731
  - coverage run manage.py test -v 3 --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```
