### ISSUE TITLE
Shippable Branch Coverage always 0.00%

### ISSUE THREAD

**Issue by sushantbajra** [Shippable/support#2247]
Here is my gemfile
```
group :test do
  gem "capybara-webkit"
  gem 'database_cleaner', '~> 1.5'
  gem 'factory_girl_rails', '~> 4.2.1'
  gem 'launchy'
  # gem 'rb-inotify', '~> 0.8.8'
  gem 'rspec-rails', '~> 3.0'
  gem 'spork', '~> 0.9.2'
end

group :development, :test do
  #gem 'pry-doc', '~> 0.4.4'
  gem 'pry-rails', '~> 0.2.2'
  gem 'pry-nav'
  gem 'better_errors', '~> 0.6.0'
  gem 'binding_of_caller', '~> 0.7.1'
  gem 'meta_request', '~> 0.2.1'
  gem 'capistrano', '~> 2.13.5'
  gem 'capistrano-ext', '~> 1.2.1'
  gem 'cucumber-rails', :require => false
  gem 'selenium-webdriver'
  # added :require => false, as updating rvm hoses rails s, sunspot, etc
  gem 'rvm-capistrano', '~> 1.3.0', :require => false
  gem 'simplecov' , :require => false
  gem 'simplecov-csv', :require => false
end
```

Here is my shippable.yml

```
# language setting
language: ruby
addons:
  firefox: "44.0"
services:
  - selenium
env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

before_script:
  - /etc/init.d/xvfb start
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

after_script:
  - /etc/init.d/xvfb stop

# version numbers
rvm: 2.3.0
cache: true


# activate rvm
before_install:
  - source ~/.rvm/scripts/rvm
  - rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY

#install the dependencies
install:
  - bundle install --gemfile="Gemfile"

script:
  - bundle exec cucumber

```
here is a link to my env.rb file [http://pastebin.com/jD67SdNi](url)
After successfully running the build, the code coverage shows 0.00% any idea how ?

**Comment by sushantbajra** [comment]
Fortunately I found the answer why..
to understand what is branch coverage or sequence coverage is follow this link [http://stackoverflow.com/questions/35362313/what-is-sequence-coverage](url)

here is how I got it working
my gemfile

```
group :development, :test do
  # Call 'debugger' anywhere in the code to stop execution and get a debugger console
  # gem 'debugger'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'sqlite3'

group :staging, :production do
  gem 'pg'
end

group :test do
  # gem "capybara-webkit"
  gem 'database_cleaner', '~> 1.5'
  gem 'factory_girl_rails', '~> 4.2.1'
  gem 'launchy'
  # gem 'rb-inotify', '~> 0.8.8'
  gem 'rspec-rails', '~> 3.0'
  gem 'spork', '~> 0.9.2'
end

group :development, :test do
  #gem 'pry-doc', '~> 0.4.4'
  gem 'pry-rails', '~> 0.2.2'
  gem 'pry-nav'
  gem 'better_errors', '~> 0.6.0'
  gem 'binding_of_caller', '~> 0.7.1'
  gem 'meta_request', '~> 0.2.1'
  gem 'capistrano', '~> 2.13.5'
  gem 'capistrano-ext', '~> 1.2.1'
  gem 'cucumber-rails', :require => false
  gem 'selenium-webdriver'
  # added :require => false, as updating rvm hoses rails s, sunspot, etc
  gem 'rvm-capistrano', '~> 1.3.0', :require => false
  gem 'simplecov' , :require => false
  gem 'simplecov-csv', :require => false
end
```
I have commented the capyabra-webkit gem as I am using selenium-webdriver

here is  my shippbale file

```
# language setting
language: ruby
addons:
  firefox: "44.0"
services:
  - selenium
env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

before_script:
  - /etc/init.d/xvfb start
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

after_script:
  - /etc/init.d/xvfb stop

# version numbers
rvm: 2.3.0
cache: true


# activate rvm
before_install:
  - source ~/.rvm/scripts/rvm
  - rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY

#install the dependencies
install:
  - bundle install --gemfile="Gemfile"
 
script:
  - bundle exec cucumber
```

the reason I removed capybara-webkit from my gem file was because I had selenium addon defined in shippable.yml file

this is my config/cucumber.yml file

```
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: --profile ci --profile dev
ci: --format junit --out <%= ENV['CI_REPORTS'] %>
dev: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip

```

Now when running the build I got what I needed.

PS. If your branch coverage test is 0.00% then please follow the link I have mentioned above.
