### ISSUE TITLE
Can't open shippable. Loads infinitely 

### ISSUE THREAD

**Issue by kepkin** [Shippable/support#2255]

**Comment by rageshkrishna** [comment]
Thanks for reporting. We're looking in to it right now. I'll keep this issue updated as I get more details.

**Comment by bryanvaz** [comment]
Same. On login we just get redirected to https://app.shippable.com/error and get the following error:

```
Error
An error occured, please choose an action.

Missing response
```

**Comment by rageshkrishna** [comment]
We had an issue with some of our API containers. Things should be back to normal now. Please let me know if everything looks good at your end. Thanks!

**Comment by kepkin** [comment]
UI is working now.. but my builds are hanged... and I can't cancel them
5645fd5d1895ca4474237436

**Comment by kepkin** [comment]
Oh... it's totally down again.

**Comment by bryanvaz** [comment]
Also we are no longer getting emails on builds (we have blanket success and failure emails). We assume that it is probably connected to the primary API container problems.

**Comment by manishas** [comment]
@bryanvaz emails should be working... are you still running into this?

**Comment by bryanvaz** [comment]
Yes. We just did a test build and no email was recieved, even though it was a successful build. Our shippable.yml hasn't changed.

excerpt from *shippable.yml*:

```
#email notifications to the IT admin on any activity
notifications:
     email:
         recipients:
             - ouradmin@gmail.com             
         on_success: always
         on_failure: always
```
