### ISSUE TITLE
Add multiple deployments for AWS EB (one for each branch)

### ISSUE THREAD

**Issue by jlsupport** [Shippable/support#2267]
What is the timeframe for getting more than one Deployment added?

We want both the development and master branch deployment to AWS EB.

it will also be nice if we can select on the master that it should upload and create the application version on EB, but not update

**Comment by bryanvaz** [comment]
Hey @jlsupport we've been using the AWS EB config to accomplish this. It's much more resilient since it is directly supported by AWS and is independent of your CI tool. 

(This of course assumes you have more than one EB environment, and they all roll up to the same AWS EB "Application", if not, your config file will need to be slightly more detailed)

## Step 1: Initialize your EB config locally
If you haven't already configured your project for AWS EB, on your dev box, run '`eb init`' at the root of your project and match it to your application. You should end up with a folder called '*.elasticbeanstalk*' in the root of your project with a '*config.yml*' in it. 

## Step 2: Configure your .elasticbeanstalk/config.yml to match your branches to environments
Normally you will have dev and prod environments in AWS EB that correspond to your development and master branches respectively. Adjust the '*.elasticbeanstalk/config.yml*' to match your desired configuration. This is what we have:

``` YAML
branch-defaults:
  develop:
    environment: agency-uat
  master:
    environment: agency-prod
global:
  application_name: agency-web-master
  default_ec2_keyname: aws-eb-key
  default_region: us-east-1
  profile: null
  sc: git
``` 

## Step 3: Copy this '.elasticbeanstalk/config.yml' configuration to 'beanstalk_config.yml' in your root
Normally, you will have your .elasticbeanstalk ignored by git to allow you dev team to manage their own individual preferences for AWS EB. Copy the configured '.elasticbeanstalk/config.yml' to the root of your project and rename it to 'beanstalk_config.yml' (you can move it somewhere else, or name it something else, just note it down as you will need to refer to it later on.)

## Step 4: Configure your shippable.yml to download and setup AWS EB
**a) setup your 'branches' option**
``` YAML
# build and process only release branches
branches:
  only:
    - develop
    - master
```
**b) setup your environment variables (append to your existing set of env variables)**
Using your preferred strategy (we have a dedicated IAM user for shippable to interact with AWS) encrypt and upload the access key and client secret as 'AWSAccessKeyId' and 'AWSSecretKey', respectively (you can either encrypt both or just the AWSSecretKey).
``` YAML
env:
  global:
    - AWSAccessKeyId=NODWIAnawdaiwda8dada9
    - secure: dwa,dlawldawlda;dlamd;anldnancuiabuyfvlaif;obabauBOzRHGj5fndpzfmuyuP5EZECV0Yk/vAHH6LBg==
```
Refer to [Shippable: Secure Variables](http://docs.shippable.com/ci_configure/#secure-variables) for how to encrypt secure variables. 

**c) instruct shippable to add the AWS CLI and configure it to match your local configuration**
You can copy the exact code below or drop it in to match your code. All this does is 

1. Installs AWS CLI
2. Copies AWS credentials into a credentials file
3. Copies your EB config which relates the specific branch to the specific AWS environment
4. Deploys the code using the EB config file
5. Cleans up the credentials (we cache our images, so we need to clean up our credentials)

``` YAML
before_install:
  - SUDO=$(which sudo) && $SUDO pip install awsebcli
install:
  - '... insert any install code'
before_script: 
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config
script:
  - mkdir -p .elasticbeanstalk
  - cp beanstalk_config.yml .elasticbeanstalk/config.yml
  - eb init && eb status
after_success:
  - eb deploy -v
  - rm ~/.aws/config
after_failure:
  - rm ~/.aws/config
```
This works because when shippable downloads your git branch, it stays on the branch being processed. The AWS CLI detects which branch Shippable is on and auto selects the correct AWS EB environment.

_This shippable.yml still works, but you should move this to the new CI format._ 


As to your note about deploying to AWS EB, but not updating, this behavior would break most of the EB command processor scripts and principles that drive EB (i.e. instances are ephemeral and can be replaced at any time). AWS EB will allow you to buffer your compiled source in an S3 tarball to make deploy faster, but if you are trying to time your deployments to prod, try using a release branch strategy to do your CI for prod, then schedule a master merge during your maintenance window.

**Comment by jlsupport** [comment]
Hi @bryanvaz , Thanks for the great explanation, but this does not work work with EB Docker as far as i can see...

**Comment by bryanvaz** [comment]
@jlsupport You should be able to adjust the "after_success" commands to match what you do locally to deploy to a EB Docker app. Specifically at which point is your setup failing? 

The above commands were also working for our Dockerized EB apps, however we ended up just moving them to ECS/Weave to get a higher density/DR capability.

**Comment by ttrahan** [comment]
hi @jlsupport:  Assuming I'm understanding your scenario correctly, you should be able to accomplish both of these items in shippable.yml.  To do so, you'll need to maintain two slightly different shippable.yml files in your two branches in order to handle the different deployment instructions.

Below is a sample yml I use to perform a Docker build, execute CI, push the image to Amazon ECR, update the EB Dockerrun deploy spec, update the EB application version, and ultimately, update the EB environment with the new image. (you can find this in the amazon-eb-cli-beta branch of [this repo]((https://github.com/ttrahan/micro-api/tree/amazon-eb-cli-beta)) along with the Dockerfile, Dockerrun.aws.json, etc.).

Note that this is a non-standard example, as I don't use a standard Shippable image in my Dockerfile.  As a result, I have to install the AWS CLI in my Dockerfile and perform `aws configure` commands in the yml.  If you're using a Shippable standard image and have assigned an AWS Account Integration to your project, you wouldn't have to do those steps.

```
# language setting
language: node_js

# version numbers, testing against two versions of node
node_js:
  - 0.10.33

env:
  global:
    - XUNIT_FILE=./shippable/testresults/result.xml
    - AWS_EB_APPLICATION=aye0aye # existing EB application name
    - AWS_EB_ENVIRONMENT=micro-api-beta # existing EB environment name
    - AWS_S3_BUCKET=shippable-demo-eb # existing S3 bucket that allows EB access
    - AWS_S3_FOLDER=$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT # S3 folder to use
    - AWS_REGION=us-east-1 # AWS region to deploy into
    - REGISTRY_ACCOUNT=288971733297.dkr.ecr.us-east-1.amazonaws.com # image registry account name, e.g. Docker Hub account
    - ACCOUNT_IDENTIFIER=shippable.$REGISTRY_ACCOUNT
    - AWS_DEPLOY_JSON=Dockerrun.aws.json.$ACCOUNT_IDENTIFIER.$AWS_EB_APPLICATION
    - AWS_DOCKER_CONFIG=dockerconfig.$ACCOUNT_IDENTIFIER.$AWS_EB_APPLICATION
    # encrypted variable for AWS_ACCESS_KEY_ID, unique to each Shippable project
    # you must generate your own hash within Shippable project settings
    - secure: KNPdy2sc6Y/jiy9/yd7m3mWYLWRK/lkDcM2hF7A699c8WuGcXZ0DoO3Qb59HuZRGoYA6GPURwprusLySSC5rKV7wTJBSDA4GQCoUboJ7ZtRrFm5gMF8p/uQVrLCyb4GmaX28BqJzONrH936j9fFeSsTJpJhWMGjeSJaOi881tGXJb7QZNDkpTtWsN7yg8eU2VJklxlNGVXEZsTxXrtdY6Jw/TiSsnv6DhmB3bqw+0VAWu+smbVEtcYdPyx2S2kpmqisTHcvJBck98d7lt0ay9MNhNCtV7AAJkRwc64dYs44G2Tcy+Lk+baCvm0uJSEmZ5nXk1f7bjb3xRbiPObgm9A==
    # encrypted variable for AWS_SECRET_ACCESS_KEY, unique to each Shippable project
    # you must generate your own hash within Shippable project settings
    - secure: Z64+B7KlurxU44tqlsrQhIxvbEw1sdVLmhBW6LV6nQK6bbxI3LxmlUsOlzhtoaTnvbam8TWA703JOSD9YC2hZ/7HI/P0IGsvOh7uF8ZcgXu0/LBKz8N47yPHLaRJHOVEPk6R2XDaRy0kCry67aZhonLMnjkZHe5HsJcKUxlK7g/bYm3evnzf/+ozPCR85e8IxzdjFLC8VY6QId6LmBGbrq3lLa97Mm+9p47oZX4ZvpXsG8FIKjXO7PHjyL/kokjDyh6lCso1uGsUtEwVJ7gO6K/Ccs51j81q5VdzoWoRoCWadlt/8xevkv48BjYg8J/B3bBPIj5F779LF0ytjz9D7A==

build:
  pre_ci:
    - docker build -t $REGISTRY_ACCOUNT/$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT:latest .
    - node --version
    - mkdir -p ./shippable/testresults
    - mkdir -p ./shippable/codecoverage
  pre_ci_boot:
    image_name: $REGISTRY_ACCOUNT/$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT
    image_tag: latest
    pull: false
    options: --privileged=true
  ci:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - npm install
    - grunt
  post_ci:
    - ./node_modules/.bin/istanbul cover grunt -- -u tdd
    - ./node_modules/.bin/istanbul report cobertura --dir  ./shippable/codecoverage/
    - echo $BUILD_NUMBER > ~/buildConfig.txt
    - docker tag -f $REGISTRY_ACCOUNT/$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT:latest $REGISTRY_ACCOUNT/$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT:$BRANCH.$BUILD_NUMBER
    - docker push $REGISTRY_ACCOUNT/$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT:$BRANCH.$BUILD_NUMBER
    # update the Elastic Beanstalk Dockerrun.aws.json deployment spec and copy files to S3
    - cat Dockerrun.aws.json | sed "s/<IMAGE_NAME>/$REGISTRY_ACCOUNT\/$AWS_EB_APPLICATION\/$AWS_EB_ENVIRONMENT/" | sed "s/<TAG>/$BRANCH.$BUILD_NUMBER/" | sed "s/<DOCKER_CONFIG>/$AWS_EB_APPLICATION\/$AWS_EB_ENVIRONMENT\/$AWS_DOCKER_CONFIG.$BRANCH.$BUILD_NUMBER/" > $AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER
    - aws s3 cp $AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER s3://$AWS_S3_BUCKET/$AWS_S3_FOLDER/$AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    - aws s3 cp /root/.docker/config.json s3://$AWS_S3_BUCKET/$AWS_S3_FOLDER/$AWS_DOCKER_CONFIG.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    # create new Elastic Beanstalk application version
    - aws elasticbeanstalk create-application-version --application-name $AWS_EB_APPLICATION --version-label $ACCOUNT_IDENTIFIER.$AWS_EB_ENVIRONMENT.$BRANCH.$BUILD_NUMBER --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$AWS_S3_FOLDER/$AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    - sleep 20s #This sleep is to make sure the image is available in the registry
    # deploy new application version to Elastic Beanstalk
    - aws elasticbeanstalk update-environment --environment-name $AWS_EB_ENVIRONMENT --version-label $ACCOUNT_IDENTIFIER.$AWS_EB_ENVIRONMENT.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION

integrations:
    hub:
      - integrationName: "Amazon ECR - ttrahan"
        type: ecr
        agent_only: false
        branches:
          only:
            - amazon-eb-cli-beta
```

* For your master branch, you'll skip the last command that starts `aws elasticbeanstalk update-environment'.  Doing so will perform all of the steps I listed above except for the last one that updates the environment.
* For your second branch, you'll include that last step.

If you're looking to trigger two deployments, one from each branch, for every commit to either branch, that's not currently supported, but something that's possible using our APIs.  Either way, please feel free to email me at tom@shippable.com to arrange a Hangout to get this working for you.

**Comment by abhijitkini** [comment]
The [documentation on deploying to Elastic Beanstalk](http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk) has been updated. It includes Docker deployment.

**Comment by ttrahan** [comment]
@jlsupport: we've completed the updates to our EB deployment integration and updated the documentation.  please re-open this issue if you continue to have issues deploying to EB.

**Comment by PaoloFalomo** [comment]
I know this is old but it would help me to know https://github.com/Shippable/support/issues/2267#issuecomment-190405114

if this is valid
```yaml
branch-defaults:
  master:
    environment: staging
  master:
    environment: production
```
