### ISSUE TITLE
Old default Shippable Image does not have GCR tools

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2276]
Hello,

Some of our configurations were using default Shippable CI images while pushing the built docker image to GCR. The problem is the default Shippable CI image does not have GCR tools and thus fails in "gcr_login" step. I think it should have them for compatibility reasons.

Related to https://github.com/Shippable/support/issues/2272

Our build script is:
```
language: python

python:
  - "3.4"
```
So according to your documentation it should pull one of the drydock images and everything, which includes GCR tools according to http://docs.shippable.com/ci_configure/#pushing-to-gcrecr-with-custom-images , and it should work.

**Comment by manishas** [comment]
@pmezard can you share a build link where this is failing?

**Comment by rvrignaud** [comment]
We are on the same team. 
Here is a link : https://app.shippable.com/runs/56d44ff0348ba60c00a4dfa3

**Comment by manishas** [comment]
We looked into this and here is what is happening -
since you are using Docker Options in project settings and old yml format, we're pulling shippable/minv2 image by default which does not have gcloud installed.

Here's the cleanest fix-
- Delete Docker Options from Project Settings
- Convert yml to new format. This means that we will start pulling a base image from drydock for the build. For your build, it should pull drydock/u14pyt
- Include following config in your yml (replace your-project-id and image_name):

```
language: python
python: 
    - "3.4"

build:
    post_ci:
      - docker build -t gcr.io/your-project-id/image_name:latest .
      - docker push gcr.io/your-project-id/image_name:latest

integrations:
    hub:
      - integrationName: GCE
        type: gcr
```

**Comment by manishas** [comment]
updated yml above.

**Comment by pmezard** [comment]
Thank you for the sample .yml, we worked around the issue by using one of our images including GCR tools as a CI image.

The point of this issue was more that:
- It should not have happened in the first place, for example by installing GCR tools in the "default Shippable CI image" before the update.
- If it was not possible, offer the ability to reference one of your drydock images as a custom CI image in the UI without us having to edit all our build files. I tried several URLs without success.

Now, it is also possible that:
- You emailed our team well in advance about incoming compatiblity breakage and for some reason the message got lost and here we are.
- Backward compatibility is secondary.

Either way, feel free to close the ticket if you consider the concern has been addressed.

**Comment by manishas** [comment]
@pmezard I agree this should not have happened in the first place. We will communicate better in the future and make sure everyone understands what will break.

It's probably too late since you've converted to using a custom image, but you can pull one of our drydock images by including the following in the yml (new format):

```
pre_ci_boot:
    image_name: drydock/image_name
    image_tag: prod
    pull: true
```
