### ISSUE TITLE
How is scoped the new integration name on yaml

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#2280]
Hello,

With the new yaml format, how is scoped (by user/org) the authorizationName ?
In my settings, for my user I have the following integration set-up:
```
Master Integration
GCR

Name
GCE
```

I have in my yaml the following:
```
integrations:
    - integrationName: GCE
      type: gcr

build:
  pre_ci_boot:
      image_name: gcr.io/xxx/shippable-ubuntu-1510
      image_tag: latest
  ci:
    - make test
  post_ci:
    - docker build -t gcr.io/clustree-cloud/${REPO_NAME}:${COMMIT} .
    - docker push gcr.io/clustree-cloud/${REPO_NAME}:${COMMIT}
```

I get the following error:
```
Post https://gcr.io/v2/xxx/my_repo_name/blobs/uploads/: token auth attempt for registry: https://gcr.io/v2/token?scope=repository%3Axxx%2Fmy_repo_name%3Apush%2Cpull&service=gcr.io request failed with status: 403 Forbidden
```

Am-I doing something wrong ?

**Comment by manishas** [comment]
@rvrignaud can you share a link to your build?

**Comment by manishas** [comment]
@ric03uec is taking a look into this.

**Comment by rvrignaud** [comment]
https://app.shippable.com/runs/56d47f75439a8a0b00bc3e0f

**Comment by manishas** [comment]
couple of quick questions -
- I see you're using a custom image. Does it have gcloud sdk installed on it?
- Does this Stack overflow answer help - http://stackoverflow.com/questions/34881697/cloud-docker-push-403-forbidden

**Comment by manishas** [comment]
@rvrignaud also for integrations, can you add the hub tag as shown below -

```
integrations:
    hub:
      - integrationName: GCE
        type: gcr
```
