### ISSUE TITLE
Docker daemon not running on standard image

### ISSUE THREAD

**Issue by bryanvaz** [Shippable/support#2287]
The standard minv2 image that shippable is now pulling from the Shippable ECR repo doesn't seem to be running docker (thus we cannot build new images, post ci). Can you confirm if this is a bug or if we should be using a different image?

Error Details:
![image](https://cloud.githubusercontent.com/assets/9157498/13418561/8127b02e-dfb1-11e5-9dab-a15109b08b43.png)

shippable.yml:
``` YAML
language: ruby
build:
  post_ci:
    - docker build -t advisory/webapp:min-latest -f Dockerfile.min . 
    - docker push advisory/webapp:min-latest
integrations:
  - integrationName: advisoryDockerHub
    type: docker
    branches:
        only:
          - master-docker
```

**Comment by manishas** [comment]
@bryanvaz if you are not using any preinstalled services, you should add the following to your yml:

```
build:
    pre_ci_boot:
      image_name: drydock/u14rub
      image_tag: prod
      pull: true
      options: --privileged=true
```

This is our standard Ruby image and has what you need preinstalled on it. Let me know if this works.

**Comment by bryanvaz** [comment]
Thanks @manishas! Because we run AWS commands during the process I had to adjust the build script to allow the awscli to update (see below). But we just noticed a more serious bug (see after yaml).
``` YAML
build:
  pre_ci_boot:
    image_name: drydock/u14rub
    image_tag: prod
    pull: true
    options: --privileged=true
  ci:
    - SUDO=$(which sudo) && $SUDO apt-get update -qq && $SUDO apt-get install -y python-dev
    - SUDO=$(which sudo) && $SUDO pip install --upgrade pip
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awscli
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awsebcli
``` 

### New issue: Docker does not login to DockerHub integration
The last step that we have "docker push advisory/webapp:min-latest" breaks. I assume that the container is not logging into our private repo even though the integration is present in the shippable.yml (see below). Can you do a quick check on this?
![image](https://cloud.githubusercontent.com/assets/9157498/13421805/94c92d8c-dfcb-11e5-845d-68f1e6d5ffbd.png)
``` YAML
  post_ci:
    - docker build -t advisory/webapp:min-latest -f Dockerfile.min . 
    - docker push advisory/webapp:min-latest
integrations:
  - integrationName: advisoryDockerHub
    type: docker
    branches:
        only:
          - master-docker
```
"advisoryDockerHub" is of course specified and configured in our Account Settings and project setting:
![image](https://cloud.githubusercontent.com/assets/9157498/13421961/ac0af2b8-dfcc-11e5-82ae-740bb20c4d30.png)

![image](https://cloud.githubusercontent.com/assets/9157498/13421982/d31bf92e-dfcc-11e5-8cbf-934a1d7c6256.png)

**Comment by rageshkrishna** [comment]
Hi @bryanvaz. Can you please link me to your latest run? Thanks.

**Comment by manishas** [comment]
@bryanvaz can you add a hub tag to your integration settings in yml and try again -

```
integrations:
    hub:
      - integrationName: advisoryDockerHub
        type: docker
        branches:
          only:
            - master-docker
```

**Comment by manishas** [comment]
@cratz which preinstalled services are you using? I can recommend the right image to pull based on that.

**Comment by cratz** [comment]
@manishas 
The solution for my problem is simple I just have to prefix all docker commands with `sudo`. I found this after checking old build logs. My be you should update [the documentation](http://docs.shippable.com/ci_configure/?utm_campaign=Shippable+4+Release#pushing-an-image-to-a-registry)

Unfortunately the used "shippable default image" changed magically during the night 
from `sudo docker pull shippable/minv2:latest` to  `sudo docker pull drydock/u14rub:prod`
This is even worst since it fails now much earlier now even I was so close to have my build running again ;(

[Last build](https://app.shippable.com/runs/56d6a39e4726420b003da6aa) with correct image 
[First build](https://app.shippable.com/runs/56d6a39e4726420b003da6aa) with wrong image

**Comment by manishas** [comment]
@rageshkrishna can we check why we're pulling u14rub by default? They are on the CD plan but their project was enabled in 11/2015.

**Comment by cratz** [comment]
@manishas @rageshkrishna 
Same magic change happened in 2 other (node.js) projects. 
From `shippable/minv2:latest` to `drydock/u14nod:prod` 
Looks like you try to determine correct image for project language.

Btw. our node projects are working fine with new the image.

**Comment by rageshkrishna** [comment]
@cratz You're correct -- if you're using the new YML format and you do not specify the image we try to pick the most appropriate drydock image for your project. You can always force the build to use any image you want with the following YML:

````
build:
  pre_ci_boot:
    image_name: shippable/minv2
    image_tag: latest
````
