### ISSUE TITLE
Composer permission issues with new YML format

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2290]
With the new `shippable.yml` format and the Continuous Delivery plan I am seeing permission errors [on build](https://app.shippable.com/runs/56d55940df0cf40c00ad36f6):

```
composer self-update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Updating to version cc14bb3ba99eaf2b1ee45bf292962551b4f1436d.
    Downloading: Connecting...    Downloading: 100%         
Cannot create cache directory /root/.composer/cache/repo/https---composer.pagemachine.de/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---composer.typo3.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache

                                                                                                     
  [ErrorException]                                                                                   
  file_put_contents(/root/.composer/keys.dev.pub): failed to open stream: No such file or directory
```

This is the relevant part of our `shippable.yml` currently:

```
...

build:
  pre_ci_boot:
    image_name: drydock/u14php
    image_tag: tip

  ci:
    - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
    - phpenv global $SHIPPABLE_PHP_VERSION
    - echo "date.timezone = Europe/Berlin" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - php --version
    - composer self-update
    - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"
    # Install PHP "intl" extension for \Collator class usage
    - sudo apt-get update
    - sudo apt-get install --yes php5-intl
    - echo "extension=$(dpkg -L php5-intl | grep intl\.so)" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
    - phpenv config-rm xdebug.ini
    - composer install --ansi --no-progress
    - bin/parallel-lint --exclude bin --exclude Packages/Libraries --exclude typo3_src --exclude web/typo3temp .
    - phpenv config-add /tmp/xdebug.ini
    - bin/phpunit --colors=always --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage;
```

Aside from the permission error: can this be trimmed down a bit with the new environment/image?
