### ISSUE TITLE
Postgresql in shippable default image

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2304]
Postgresql server is not running in the new shippable default image even I specified it as an addon.
Add the following line to your shippable.yml before you try to access (create) the database: 
(start only a specific version. I wanna have 9.3)

```
ci:
  - fancy things
  - "sudo /etc/init.d/postgresql start 9.3"
  - %create database%
  - %run migrations%
  - more fancy things
```

**Comment by manishas** [comment]
Can you please share a build link?

We will look into why the addons isn't working. In the meantime, if you want to continue using the old default image, you can do the following in your yml:

```
pre_ci_boot:
     image_name: shippable/minv2
    image_tag: latest
    pull: true
```
This will pull the old default image minv2 for your builds.

**Comment by cratz** [comment]
@manishas 
e.g. https://app.shippable.com/runs/56d59ea4797c670c00f6fe71
With my workaround (starting pg server by "hand") it works with the new default image. 
I just created this issue to help other users who have the same problem.

Thank you anyway!

**Comment by rageshkrishna** [comment]
I think I see the problem here... specifying postgres as an addon alone does not work, but if you configure and addon and _also_ list it under services, it will start the version you asked for. This should definitely work without having to add both tags to the YML.

We'll fix this soon.

**Comment by cratz** [comment]
@rageshkrishna 
Thanks, but I tried it after I read your comment in #2316 
And adding postgres to services will not start the pg  server ;(
Here is the build:
https://app.shippable.com/runs/56d6ce8487a3710b00471568

I did everything described in the [documentation](http://docs.shippable.com/ci_configure/?utm_campaign=Shippable+4+Release#postgresql)
But the only way to have a running pg-server was the one I described in the initial issue description.

**Comment by rageshkrishna** [comment]
OK, we'll take a deeper look at this and get back to you soon.

**Comment by rageshkrishna** [comment]
@cratz I think our documentation needs to be fixed. Here's a minimal YML that works for me:

````
language: node_js

node_js:
  - "0.10"
  
services:
  - postgres

build:
  pre_ci_boot:
    image_name: shippable/minv2
    image_tag: latest
    pull: false
  ci:
    - echo "Hello, World!"
````

If it still doesn't work, please share your complete YML file. You can email me at ragesh@shippable.com if you'd rather not paste it here. Thanks!

**Comment by cratz** [comment]
@rageshkrishna 
Thanks.
I tried it but still not working [here is the build](https://app.shippable.com/runs/56d85890f4bf7e0c0004416e) `could not connect to server: Connection refused`

The important parts of my shippable.yml
```yaml
language: ruby
addons:
  #postgresql: "9.3"
  firefox: "42.0"
service:
  - postgres
build:
  ci: 
    - command which creates database and where the error happens 
```
I can't see any database operation in you example may be you should add something like 
`- psql -c 'create database myapp_test;' -U postgres` to the `ci` section because if I would not run a database operation it would not fail.

Btw. will it be possible to specify a PG version?
