### ISSUE TITLE
Keep getting "Hub login failed" on builds

### ISSUE THREAD

**Issue by alvaroc1** [Shippable/support#2305]
Builds used to work before migration. Where do I need to configure the docker hub login? It's already setup correctly on the project settings (on shippable website > project settings).

**Comment by manishas** [comment]
@alvaroc1 From my understand, you're pulling a custom image from Docker Hub and using it for CI. You do not want to push this image after CI or run any docker commands in your `ci` or `post_ci` sections.

The problem you're seeing is because your custom image does not have docker installed, and if you have an integration configured in the yml, we try to login to the registry. However, if you are not using docker commands in your `ci` and `post_ci` sections, we do not need to do the login.

We are deploying a fix for this in a couple of hours. You will need to add a tag in your integration-

```
integrations:
    hub:
      - integrationName: <your_integration_name>
        type: docker
        agent_only: true
```
