### ISSUE TITLE
/bin/sh: 1: ssh-agent: not found | Using my own Dockerfile

### ISSUE THREAD

**Issue by JasonSwindle** [Shippable/support#2306]
Using this ( https://github.com/JasonSwindle/shippable-example/blob/master/Dockerfile ) I am unable to build as I keep getting the error:

```bash
/bin/sh: 1: ssh-agent: not found
```

How do I make Shippable not try to ssh into my container which will never have ssh installed into it.

**Comment by manishas** [comment]
@JasonSwindle we are pushing a fix for this soon.

However, please note that we do need certain tools in the custom image, like git and python for example. We install these in the custom image as part of the build process.

**Comment by rvrignaud** [comment]
@manishas could you please document an exhaustive list of all tools needed in a custom image ?

**Comment by rageshkrishna** [comment]
@JasonSwindle This should now be working. Please try a build and let me know how it goes.

**Comment by rageshkrishna** [comment]
@rvrignaud We now check for and install the following dependencies in the build container when it is started:

1. sudo
1. git
1. ssh-agent
1. python

**Comment by JasonSwindle** [comment]
So how does one use Shippable to build a Dockerfile that cannot have sudo, git, ssh-agent, or python installed? I simply want Shippable to do a docker build -t "..." . without trying to inject extra un-needed items.

**Comment by rageshkrishna** [comment]
The CI container itself requires these tools. However, you're free to push whatever image you want at the end of it. For example, here's a YML that lets you build your image, run tests inside it, and then push the original image (without any of the stuff we installed) to your registry:

````
build:
  pre_ci:
    - docker build -t=foo/bar .
  pre_ci_boot:
    image_name: foo/bar
    image_tag: latest
    pull: false
  ci:
    - ./runSomeTests.sh
  post_ci:
    - docker push foo/bar
````
