### ISSUE TITLE
When pulling image from gcr, we need to prepend gcr.io

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2311]
When using gcr.io, we need to prepend gcr.io to the image name. The [yml docs](http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry) say that image_name value is in the format (docker registry username)/(docker registry image repo), but that's not the case: if I remove gcr.io, the pull fails. Here's the relevant part of my yml file for reference:

```
build:
  pre_ci_boot:
    image_name: gcr.io/user/image
    image_tag: latest
    pull: true

integrations:
  hub:
    - integrationName: GCE
      type: gcr
```
