### ISSUE TITLE
Push image to GCR after ci

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2312]
I'm trying to use the new way to build yaml files to reproduce the setup that was working perfectly fine until now. I retrieve an image from GCR, add things to it, test the result, and want to send it back to GCR. The `pre_ci_boot` and `ci` steps work, but `post_ci` does not. As you can see in https://app.shippable.com/runs/56d6b68e6b86640c0040f716, I get:

> The push refers to a repository [gcr.io/project/$REPO_NAME] (len: 1)
> Repository does not exist: gcr.io/project/$REPO_NAME

What's going on? 

```
build:
  pre_ci_boot:
    image_name: gcr.io/project/shippable-ubuntu-1510
    image_tag: latest
    pull: true
  ci:
    # build and test
  post_ci:
    - docker build -t $REPO_NAME .
    - gcloud docker push gcr.io/project/$REPO_NAME:$COMMIT

integrations:
  hub:
    - integrationName: GCE
      type: gcr
```
