### ISSUE TITLE
Support per branch env

### ISSUE THREAD

**Issue by kilianc** [Shippable/support#232]
I need to have set in my code specific per branch env, is it possible?

Scenario: I have a static website, each branch has to be deployed to a specific bucket, with a specific region.

Example just assuming all buckets are in Oregon and the folder is always app for all branches:

``` yml
script:
  - export DEPLOY_S3_TARGET_develop=s3://dev.website.com
  - export DEPLOY_S3_TARGET_staging=s3://stag.website.com
  - export DEPLOY_S3_TARGET_master=s3://website.com
  - export DEPLOY_S3_TARGET=$(eval "echo \$DEPLOY_S3_TARGET_$BRANCH")
  - grunt build --no-colors
  - aws s3 sync app $DEPLOY_S3_TARGET --delete --acl public-read --region us-west-2
```

kinda dirty isn't it? and not sure if it works. something like this exists?

``` yml
env:
  develop:
    - NODE_ENV=dev DEPLOY_S3_BUCKET=s3://dev.website.com DEPLOY_S3_REGION=us-west-2
```

or even better:

``` yml
env:
  develop:
    - NODE_ENV=dev
    - DEPLOY_S3_BUCKET=s3://dev.website.com
    - DEPLOY_S3_REGION=us-west-2
```
