### ISSUE TITLE
Matrix include drops global env

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2322]
It seems like matrix includes in the `shippable.yml` drop the global `env`. Example:

```yaml
language: php

php:
  - 5.5
  - 5.6

env:
  global:
    - secure: ...
    - COMPOSER_NO_INTERACTION=1
  matrix:
    - ...
    - TYPO3_VERSION=~6.2
    - TYPO3_VERSION=^7.6

matrix:
  include:
    - php: 7.0
      env: TYPO3_VERSION=^7.6

...

build:
  ...

  ci:
    - ...
    - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"
    - composer require typo3/cms $TYPO3_VERSION
```

In this case the [build for the last environment fails](https://app.shippable.com/runs/56d84547636e050c001d2b20) because the global environment variables are not set.

---

Regular:

```
Matrix Values 
  Language version: 5.6
  Environment Variables:
  #SHIPPABLE_SECURE_VARIABLE
  COMPOSER_NO_INTERACTION=1
  TYPO3_VERSION=^7.6
```

---

Failing matrix include:

```
Matrix Values 
  Language version: 7
  Environment Variables:
  TYPO3_VERSION=^7.6
```

A Composer error message exposes the issue:

```
  [UnexpectedValueException]                                              
  Your github oauth token for github.com contains invalid characters: "" 
```

**Comment by manishas** [comment]
@mbrodala we will look into this, but in the meantime, there is a workaround. You can specify the global values in each include like this:

```
matrix:
  include:
    - php: 7.0
      env: 
        - TYPO3_VERSION=^7.6
        - secure: ...
        - COMPOSER_NO_INTERACTION=1
```

Let me know if this works for you.
