### ISSUE TITLE
valid yml is not parsing correctly

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2329]
Integrations in the new yml format fail if the integrationName contains spaces.  The following yml appears to be formatted correctly, but causes an error when parsed in Shippable:

This throws an error in Shippable:
```
integrations:
    hub:
      - integrationName: Amazon ECR - ttrahan
        type: ecr
        agent_only: false
        branches:
          only:
            - amazon-eb-ui-beta
```

Validated at http://yaml-online-parser.appspot.com/:
![image](https://cloud.githubusercontent.com/assets/4467650/13541415/e8722ef6-e210-11e5-9147-150a789da5e8.png)

Putting double quotes around the value fixes the issue:
```
integrations:
    hub:
      - integrationName: "Amazon ECR - ttrahan"
        type: ecr
        agent_only: false
        branches:
          only:
            - amazon-eb-ui-beta
```
