### ISSUE TITLE
Archive:true option does not give expected result

### ISSUE THREAD

**Issue by peterhav** [Shippable/support#2331]
Hello, I have setup a `shippable.yml` file for my Android project, unfortunately, the **archive: true** does not seem to work as expected; I'm not able to download any archives from the console of a sucesfully finished job (only a job logfile). How can I get this to work?

```
language: java
jdk:
    - oraclejdk8
before_install:
    - sudo dpkg --add-architecture i386
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1
    - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
    - tar -zxf android-sdk_r24.4.1-linux.tgz
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo "y" | android update sdk -a --filter tools,platform-tools,build-tools-23.0.2,android-23,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository --no-ui --force
install:
    - chmod +x gradlew
archive: true
before_script:
    - mkdir -p shippable/artifacts
script:
    - ./gradlew clean assembleRelease --no-daemon
after_script:
    - cp -r app/build/outputs/mapping/release/mapping.txt shippable/artifacts/mapping.txt
notifications:
    email:
        recipients:
            - xxxxxx@gmail.com
```
