### ISSUE TITLE
Provide an updated guide for deployment in beanstalk

### ISSUE THREAD

**Issue by Lughino** [Shippable/support#2333]
I read all the possible guides to configure a CD in my beanstalk with your service.

I can not in any way to configure properly as all guides are completely outdated and can not I deploy!

The guides that I have followed are these:
[http://blog.shippable.com/deploying-containers-to-elastic-beanstalk-the-shippable-way](deploying-containers-to-elastic-beanstalk-the-shippable-way)
[http://blog.shippable.com/shippable-continuous-delivery-to-amazon-ec2-container-services](shippable-continuous-delivery-to-amazon-ec2-container-services)
[http://blog.shippable.com/shippable-continuous-delivery-to-amazon-ec2-container-services-0](shippable-continuous-delivery-to-amazon-ec2-container-services-0)

What I'm trying to do is this:
* I run the CI to commit
* if the branch is master it pushes on docker registry Amazon ECR
* always if the branch is master run deploy on my beanstank.

I configured everything as it is explained in the guides .. but does not push to the docker registry and does not deploy on the beanstalk.

**Please provide an updated guide so that it can use your service!**

**Comment by manishas** [comment]
@Lughino we will update the guide in the next 1-2 days.

**Comment by Lughino** [comment]
@manishas thanks.

**Comment by ttrahan** [comment]
@Lughino we discovered an issue with how EB deployments are working and are working on the fix now.  As soon as that is complete, we will post the updated documentation and notify you here.  In the meantime, if urgent, you can configure EB deployments within the shippable.yml to accomplish your scenario. Let me know if you'd like to do this.

**Comment by Lughino** [comment]
@ttrahan thanks for the reply.
I'm taking care to configure the shipping.yml and I'm encountering two problems, one of which perhaps does not depend on your platform but from my inexperience:

- Shippable properly performs tasks and launches the deployment without giving errors
- The beanstalk will not start properly and reported a generic error "Update environment operation is complete, but with errors. For more information, see the troubleshooting documentation."

The first problem is that it provides me with a success feedback, but in fact the deployment has not been successful.

As the second problem, investigating a bit, I find inside the ec2 instance in `/var/app/current` two files, `Dockerfile` and `Dockerrun.aws.json`
which content is:

``` bash
#Dockerfile:
FROM 583343711111.dkr.ecr.us-east-1.amazonaws.com/api:latest
EXPOSE 3000


#Dockerrun.aws.json
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "583343711111.dkr.ecr.us-east-1.amazonaws.com/api:latest",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "3000"
    }
  ]
}
```

I do not understand why the `Dockerrun.aws.json` shows the branch `latest` and perhaps the fact that nothing works is due to this.

My shipping.yml is this:
```yml
language: node_js

services:
  - mongodb

env:
  global:
    - XUNIT_FILE=../shippable/testresults/result.xml
    - NODE_ENV=test
    - AWS_ECR_NAME=api
    - AWS_EB_APPLICATION=DockerTest
    - AWS_EB_ENVIRONMENT=dockertest-qa
    - AWS_S3_BUCKET=dockertest-y
    - AWS_S3_FOLDER=$AWS_EB_APPLICATION/$AWS_EB_ENVIRONMENT
    - AWS_REGION=eu-west-1
    - REGISTRY_ACCOUNT=583343711111.dkr.ecr.us-east-1.amazonaws.com
    - ACCOUNT_IDENTIFIER=shippable.$REGISTRY_ACCOUNT
    - AWS_DEPLOY_JSON=Dockerrun.aws.json.$ACCOUNT_IDENTIFIER.$AWS_EB_APPLICATION
    - AWS_DOCKER_CONFIG=dockerconfig.$ACCOUNT_IDENTIFIER.$AWS_EB_APPLICATION
    # AWS_ACCESS_KEY_ID
    - secure: vDp59a+0/MGcGVUkkUvhN9HizJ/RSeYLukk/223JmAJZ1mpWVSC+02Q08IBEPKBPd8lX0wNJpPy2B2471NrVHKls3ylDkaAUTx/5cXTH+OJNl5xIPIh2KnT7WRnOb/4Hkr/IpJ47fhNbVHWV7n6zcpdZZkeFB0O/C/rktyguigiugaNeojt4Pwv3P4Z5H41oLufj44RViOYlMdn355COwwnLmHU7jWMM6BziYOBWX4qpGZ3gpttr0izS515m8Vrql++BDSkC7VASbf5CDcjg8QA7qoLfPrY52LS8Gz9uq82qmHuU/V/MmBF9yM4uM1VKHwid0KERbHqjxgg==
    # AWS_SECRET_ACCESS_KEY
    - secure: Asmt6egPGErspoROAAmMlmgXtvBs97ZYDE5Cm/4/hWm5wj9o+ScdK6DRD7+mXOYMWb4a3/QeuQWJeP11rkRhDiugiugKJHFbFPi/hJv6tpDqGc9BATnOPsnwYFYS4go1o197mekZ4SPmMZ8C+kDpZhkdIx/vGHA9Vz7Xed+79DC9qhK/pNvqtEfiWfMTgqRf6su7KwK16g+AfQL4s9EaUszq+/tSWgtvWFE4yiKkzvpBYF9t7Ri9RcU8X1rDg9ZaMDQ74EJyWNcUHp5ctOxAS9avONmvC6VlV53Jh44JQODyVO4gZ1Sary/xypY58AS06UCv4iFjw1Penpl1cDvrfw==

build:
  pre_ci:
    - docker build -t $REGISTRY_ACCOUNT/$AWS_ECR_NAME:latest -f api/docker/production/Dockerfile .
    - mkdir -p ./shippable/testresults
    - mkdir -p ./shippable/codecoverage
  pre_ci_boot:
    image_name: $REGISTRY_ACCOUNT/$AWS_ECR_NAME
    image_tag: latest
    pull: false
    options: --privileged=true
  ci:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - cd api
    - shippable_retry npm i
    - grunt
  post_ci:
    - ./node_modules/.bin/istanbul cover grunt -- -u tdd
    - ./node_modules/.bin/istanbul report cobertura --dir  ../shippable/codecoverage/
    - echo $BUILD_NUMBER > ~/buildConfig.txt
    - docker tag -f $REGISTRY_ACCOUNT/$AWS_ECR_NAME:latest $REGISTRY_ACCOUNT/$AWS_ECR_NAME:$BRANCH.$BUILD_NUMBER
    - docker push $REGISTRY_ACCOUNT/$AWS_ECR_NAME:$BRANCH.$BUILD_NUMBER
    - cd ..
    - cat Dockerrun.aws.json | sed "s/<IMAGE_NAME>/$REGISTRY_ACCOUNT\/$AWS_ECR_NAME/" | sed "s/<TAG>/$BRANCH.$BUILD_NUMBER/" | sed "s/<BUCKET>/$AWS_S3_BUCKET/" | sed "s/<DOCKER_CONFIG>/$AWS_EB_APPLICATION\/$AWS_EB_ENVIRONMENT\/$AWS_DOCKER_CONFIG.$BRANCH.$BUILD_NUMBER/" > $AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER
    - aws s3 cp $AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER s3://$AWS_S3_BUCKET/$AWS_S3_FOLDER/$AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    - aws s3 cp /root/.docker/config.json s3://$AWS_S3_BUCKET/$AWS_S3_FOLDER/$AWS_DOCKER_CONFIG.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    - aws elasticbeanstalk create-application-version --application-name $AWS_EB_APPLICATION --version-label $ACCOUNT_IDENTIFIER.$AWS_EB_ENVIRONMENT.$BRANCH.$BUILD_NUMBER --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$AWS_S3_FOLDER/$AWS_DEPLOY_JSON.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION
    - sleep 20s
    - aws elasticbeanstalk update-environment --environment-name $AWS_EB_ENVIRONMENT --version-label $ACCOUNT_IDENTIFIER.$AWS_EB_ENVIRONMENT.$BRANCH.$BUILD_NUMBER --region=$AWS_REGION

integrations:
    hub:
      - integrationName: "api"
        type: ecr
        agent_only: false
        branches:
          only:
            - master
    notifications:
      - integrationName: slack-notification
        type: slack
        recipients:
          - "#ci"
        branches:
            only:
              - master
              - dev
        on_start: always
        on_success: always
        on_failure: always

branches:
  only:
    - dev
    - master
```


Could you help me?

Thank you
