### ISSUE TITLE
can't execute bower install

### ISSUE THREAD

**Issue by kilianc** [Shippable/support#235]
this is part of my conf

``` yml
before_install:
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo pip install awscli
  - sudo gem install sass

install:
  - bower install
```

![screen shot 2014-06-20 at 21 12 23](https://cloud.githubusercontent.com/assets/385716/3344744/d78fc44c-f8ae-11e3-8f39-6a5e5780a27f.png)

Output from `npm install -g bower` seems correct
