### ISSUE TITLE
`shippable_cache_container` causes failure in ci step

### ISSUE THREAD

**Issue by lloydcotten** [Shippable/support#2351]
My builds are failing if I try to use `shippable_cache_container` command in the `ci` stage.  But then apparently works in the `on_failure` stage.  It means I can't cache where I want to and advertised in the docs: http://docs.shippable.com/ci_configure/#caching-your-container

Is it a bug or is my yaml wrong?

```
build_ci
  ...
  shippable_cache_container
  echo 'Caching container c.exec.myproject.200.1'
      Caching container c.exec.myproject.200.1

build_on_failure
  shippable_cache_container
  echo 'Caching container c.exec.myproject.200.1'
  su -c "docker export c.exec.myproject.200.1 | docker import - 690089443214.dkr.ecr.us-east-1.amazonaws.com/56968fd21895ca4474682f80:56968fd41895ca4474682fbe"
  echo Build container cached successfully
```

Relevant shippable.yaml

```
language: node_js

node_js:
  - "4.2"

build:
  pre_ci_boot:
    image_name: repo/custom_image
    image_tag: my-image-tag
    pull: true
  cache: true
  ci:
    - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
    - node --version
    - npm install
    - npm install mocha-junit-reporter
    - npm update
    - shippable_cache_container
    - npm test
  on_success:
    - my_notify_command.sh

  on_failure:
    - my_notify_command.sh
```

**Comment by ric03uec** [comment]
@lloydcotten this is a bug at our end. we're re-implementing caching from ground up that will resolve this and give users a lot more flexibility in how they can use cache. 
For now, we've disabled cache and the builds should run normally. You should remove the `cache:true` statement if builds are still failing for you

**Comment by lloydcotten** [comment]
Thanks for the response.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.
