### ISSUE TITLE
Can't mount volume on docker run.

### ISSUE THREAD

**Issue by rhherrera** [Shippable/support#2353]
Hi, I really need help with this, I'm trying to run a postgres image, and mount a volume so I can run a lot of commands inside it (this works perfect for me local, but seems that doesn't work in shippable). 

here is my shippable.yml
```
#set your language below
language: python
#set language version. This is only required if you use the default Shippable image for your build
python:
    - 2.7
env:
  - LIVELY_REPO_DIR=/root/src/github.com/myrepo
build:
    post_ci:
      - docker rm -f postgres  &> /dev/null || true
      - docker run --name postgres --publish 5432:5432 --detach=true --volume $LIVELY_REPO_DIR/deploy/docker/containers/postgres/docker-entrypoint.sh:/docker-entrypoint.sh postgres
    on_failure:
      - docker logs --tail="all" gunicorn
```

The error is the following:
Error response from daemon: Cannot start container c1461a3eb5a6d6767bb57c2e1fb29d151edd1915b7867b527b655c8aa2e62824: [8] System error: not a directory

[https://app.shippable.com/runs/56e095aeb8adfb0c005aa32b](url)

Also had to remove a -v from another container that was like:
```
-v $LIVELY_REPO_DIR/data:/django
```
because was creating the folder but not mounting it, I mean /django inside container was always empty, I fixed that removing -v and using COPY inside Dockerfile, but in the postgres case I'm using a postgres image so I don't have a DockerFile.

any help?

**Comment by stephanielingwood** [comment]
Hi @rhherrera,

Thanks for your question. On Shippable, when you run a container (like your postgres container) from inside your build container, they end up running side-by-side in the host machine - not one-inside-the-other. In other words, the build container does not act as the host machine for the postgres container.

This means that you need to create a separate data volume container to share data between the two containers. That data volume can then be mounted inside either your build container or the postgres container. With just a small modification to your yml, this will work.

Here's how you want to configure your yml for this scenario:
```
#set your language below
language: python
#set language version. This is only required if you use the default Shippable image for your build
python:
    - 2.7

build:
    pre_ci_boot:
        options: -v /dataDir
    post_ci:
      - docker rm -f postgres  &> /dev/null || true
      - cp $SHIPPABLE_BUILD_DIR/deploy/docker/containers/postgres/docker-entrypoint.sh /dataDir/docker-entrypoint.sh
      - docker run -i --name postgres --publish 5432:5432 --detach=true --volumes-from $SHIPPABLE_CONTAINER_NAME postgres
    on_failure:
          - docker logs --tail="all" gunicorn
```

There are three changes here:
- The `-v /dataDir` in the pre_ci_boot options is what creates your separate data volume container
- To reference the separate data volume container when you're creating the mount inside the postgres container, you use `--volumes-from`, instead of `--volume` (more info on this here: https://docs.docker.com/v1.7/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container)
- The path you had assigned to LIVELY_REPO_DIR is already available as an environment variable, named SHIPPABLE_BUILD_DIR

Hope this helps! Let me know if you have any questions.

**Comment by rhherrera** [comment]
Hi @stephanielingwood , thanks for the answer.
If I'm getting right, that way the entrypoint.sh will be mounted on /dataDir inside the postgres container.
so as is not in  "/" to exec the entrypoint I need to add ``` --entrypoint /dataDir/docker-entrypoint.sh.sh ``` .
Doing that,  get the following error ( I assume that is because volume is not mounted yet when entrypoint run).

Error response from daemon: Cannot start container 448037c207371950c828a9291866850c94c4ef3472efb367d7f971e1fdd2550e: [8] System error: exec: "/dataDir/docker-entrypoint.sh.sh": stat /dataDir/docker-entrypoint.sh.sh: no such file or directory

[https://app.shippable.com/runs/56e1b81cdc87380c00705a26](url)

I leave you here my shippable.yml
```
#set your language below
language: python
#set language version. This is only required if you use the default Shippable image for your build
python:
    - 2.7

build:
    pre_ci_boot:
        options: -v /dataDir
    post_ci:
      - docker rm -f postgres  &> /dev/null || true
      - cp $SHIPPABLE_BUILD_DIR/deploy/docker/containers/postgres/docker-entrypoint.sh /dataDir/docker-entrypoint.sh
      - docker run -i --name postgres --publish 5432:5432 --detach=true --volumes-from $SHIPPABLE_CONTAINER_NAME --entrypoint /dataDir/docker-entrypoint.sh.sh postgres
      - docker ps
      - docker logs --tail="all" postgres
    on_failure:
          - docker logs --tail="all" postgres
```

any help?
