### ISSUE TITLE
cache: true results in long build times

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2356]
If I add this to my shippable.yml builds that typically complete in 3-4 minutes are taking 15-20+ minutes.  Not sure they ever finish.  I finally canceled them.

**Comment by manishas** [comment]
@chriskinsman we realized that our strategy of flattening the image and pushing is leading to very slow cache process which defeats the purpose. We have decided to redo caching and implement a folder based approach. 

At this point you should do one of the following -
- turn off cache for your builds until the new implementation is available in a few days
- ask to be reverted back to the old build system until the new caching mechanism is available.

**Comment by manishas** [comment]
@chriskinsman we have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
