### ISSUE TITLE
Pulling private docker container sometimes fails

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2359]
<img width="614" alt="screenshot 2016-03-10 10 49 26" src="https://cloud.githubusercontent.com/assets/2778689/13665716/19f84306-e6ae-11e5-9f5b-a5cc529526a5.png">

As an example: The first build succeeds, a number of hours later the exact same git sha fails since it seems unable to fetch the docker container (even though the registration to Docker etc is all correct). On the new architecture this has happened a number of times over the last week, whereas the old one never had any problems.

I should mention the specific container is private, so if a login is not performed the container cannot be pulled indeed

<img width="988" alt="screenshot 2016-03-10 10 52 18" src="https://cloud.githubusercontent.com/assets/2778689/13665771/519db138-e6ae-11e5-8172-3dfd4afe6574.png">

**Comment by manishas** [comment]
@rogierslag we suspect you're missing the integrations section in your yml. You need this in your yml in addition to having the integration in project settings (which you already do)

http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry

```
pre_ci_boot:
    image_name: manishas/myImage
    image_tag: latest
    pull: true
    options: "-e HOME=/root" 

integrations:
    hub:
      - integrationName: "manishasDockerHub"
        type: docker
```
