### ISSUE TITLE
Postgres and mysql not starting by default on minv2

### ISSUE THREAD

**Issue by flakron** [Shippable/support#2361]
Up until an hour ago everything was ok, now I'm getting the below message:

```
build_ci 
     /root/e006de8c-89cb-4ce5-bb9d-9da733b587bf.sh: line 58: psql: command not found
```

**Comment by avinci** [comment]
@flakron could you give me your projectId or a link to the build. We are upgrading the back end infra and it should be transparent for users, but might be affecting you. I want to see if thats the case

**Comment by flakron** [comment]
Sure
project id: 56d45cd19d043da07b0fcabb
latest build: https://app.shippable.com/runs/56e1862800d3410c00b61da6

**Comment by avinci** [comment]
@flakron There is an issue with image picker. The new build system should pulled the old image `minv2` instead of the latest image. I am opening a ticket to get this fixed ASAP. If we need to fire a test build on your project would that be ok, i.e. once we fix the issue

**Comment by avinci** [comment]
@ric03uec can we get this fixed ASAP. The image picker should have defaulted to minv2 if the project was enabled before 2/29 and this seems to be not working as expected. Lets fix this as a CQD so that this project get unblocked.

**Comment by flakron** [comment]
Thanks for the fast response.
Sure fire the build whenever you need.

:+1:

**Comment by manishas** [comment]
@flakron I looked into this and here is what is happening-

- your subscription was upgraded to the new plan a few hours ago. 
- Since our recent release was on 2/29, all projects on the new plan and enabled on or after 2/29 do not pull shippable/minv2 as build image by default. Your project now meets this criteria, hence it started pulling u14php by default.

Can you share your shippable.yml? We can help you change it to the new format and explicitly pull minv2 and your builds should work again.

**Comment by flakron** [comment]
Sorry could not reply earlier, here is the project shippable file
```
language: php

php:
  - 5.5

before_script: mkdir -p shippable/testresults
before_script: psql -c 'create database maredoo;' -U postgres

env:
  - DB_CONNECTION=pgsql DB_DATABASE=maredoo DB_USERNAME=postgres APP_KEY=gFAPXS4RNzznTAvwhZsyiLXGmU2WdReQ

script:
  - composer self-update
  - composer update --prefer-source
  - phpunit --log-junit shippable/testresults/junit.xml

notifications:
  email:
      recipients:
         - myemail@email.com
```

**Comment by rageshkrishna** [comment]
Hi @flakron. Here's what the new YML format would look like for your project:

````
language: php

php:
  - 5.5
  
env:
  - DB_CONNECTION=pgsql DB_DATABASE=maredoo DB_USERNAME=postgres APP_KEY=gFAPXS4RNzznTAvwhZsyiLXGmU2WdReQ
  
build:
  pre_ci_boot:
    image_name: shippable/minv2
    image_tag: latest

  ci:
    - mkdir -p shippable/testresults
    - psql -c 'create database maredoo;' -U postgres
    - composer self-update
    - composer update --prefer-source
    - phpunit --log-junit shippable/testresults/junit.xml

integrations:
  notifications:
    - integrationName: "email"
      type: "email"
      recipients:
         - myemail@email.com
````
