### ISSUE TITLE
Projects links

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2376]
How can I trigger other project in subscription, or create project build dependency?

**Comment by manishas** [comment]
@luckyraul you will need to do it via API calls in your shippable.yml.

We had written a [blog about this last year](http://blog.shippable.com/daisychaining-builds-with-our-new-public-api), however it needs to be updated to follow new yml syntax and latest APIs. 

I have tagged this issue as a content issue and we will publish a new blog on this in the upcoming week.

**Comment by DavidGDragon** [comment]
Here is a sample YML to trigger another project from inside your build:
```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12

env:
  global:
    - FOO=FUBU
    - FO1=BUBU
    - BOO=GUBU
    - NOTHING=NEW
    - PROJECT_ID=56c64e31c77dae78a8e6e7d1
    - secure SHIP_TOKEN

build:
  ci:
  - echo $PROJECT_ID
  - JSON='{"projectId":"$PROJECT_ID","branchName":"master","type":"push"}'
  - 'curl -H "Content-Type: application/json" -H "Authorization: $SHIP_TOKEN" -X POST -d $JSON https://apibeta.shippable.com/projects/$PROJECT_ID/newBuild'
  ```
Important note: `secure SHIP_TOKEN` is your Shippable api token encrypted to be a secure var from the project settings page. To encrypt your token, go to `https://beta.shippable.com/projects/:projectId/settings` and in the 'Encrypt' section input `SHIP_TOKEN='apiToken 12345'` (where 12345 is your shippable token). Then you paste the result into the yml at that point.
