### ISSUE TITLE
Cannot actually run a test on shippable

### ISSUE THREAD

**Issue by bryanvaz** [Shippable/support#2377]
I've been using shippable for 5 months now to as a CD pipeline for RoR to AWS EB, but I would actually like to use it to do CI as well. However I can't seem to find any documentation on how to actually run a test. The best I could find was http://carlosbecker.com/posts/integrating-minitest-with-shippable. However one problem, Shippable is saying that there is no 'bundler' on the image. @manishas ideas?

**shippable.yml**
```YAML
# language setting
language: ruby
#email notifications to the IT admin on any activity
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - <notifications email>
      on_start: always
      on_success: always
      on_failure: always 

# build and process only release branches
branches:
  only:
    - develop
    - master
rvm:
  - 2.2.4
services:
    - postgres
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - USER=postgres
    - AWSAccessKeyId=<## obviously not included ##>
    - secure: <## obviously not included ##>
build:
  pre_ci_boot:
    image_name: drydock/u14rubpls
    image_tag: prod
    pull: true
    options: --privileged=true
  ci:    
    - mkdir -p $CI_REPORTS
    - mkdir -p $COVERAGE_REPORTS
    - mkdir -p ~/.aws   
    - psql -c 'create database myapp_test;' -U $USER
    - bundle install
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:schema:load RAILS_ENV=test
    - bundle exec rake test
  post_ci:
    - SUDO=$(which sudo) && $SUDO apt-get update -qq && $SUDO apt-get install -y python-dev
    - SUDO=$(which sudo) && $SUDO pip install --upgrade pip
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awscli
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awsebcli
    - echo [profile eb-cli] > ~/.aws/config
    - echo "aws_access_key_id=$AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key=$AWSSecretKey" >> ~/.aws/config
    - mkdir -p .elasticbeanstalk
    - cp beanstalk_config.yml .elasticbeanstalk/config.yml
    - eb init 
    - eb status
    - eb deploy -v
```

**shippable ouput:**
![capture](https://cloud.githubusercontent.com/assets/9157498/13740604/af43278a-ea0c-11e5-8621-f6679cc22ba0.PNG)

Ouput: https://app.shippable.com/runs/56e685a92911630c0071d0c4

Obviously all I do to test locally is 'rake test'

Cheers,
Bryan

**Comment by chetantarale** [comment]
@bryanvaz We tried to reproduce this with our sample projects by using relevant sections from your yml but we are not running into this issue.

Link for the build that passed:
https://app.shippable.com/runs/56e69ae473719a0c00791d9f

Is there anything specific in your `gemfile`?

**Comment by bryanvaz** [comment]
Resolved: Included a couple of fixes (better if documented)

1) bundler is not installed in the new ruby CI images by default, so you need a '**gem install bundle**' line

2) The drydock images don't have any build dependencies installed so you they have to be installed before installing gems. For postgres notably the '**libpq-dev**' package, and the nokogiri '*libxml2-dev libxslt1-dev*'. Put these in an environment variable to make it easier to use.

However I noticed my aws config file didn't carry over from the 'ci' section to the 'post_ci'.  

**shippable.yml**
```YAML
# language setting
language: ruby

# build and process only release branches
branches:
  only:
    - develop
    - master
rvm:
  - 2.2.4
services:
    - postgres
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - BUILD_PACKAGES="build-essential libssl-dev libpq-dev libxml2-dev libxslt1-dev"
    - RUBY_PACKAGES="openssl nodejs postgresql-client"
    - USER=postgres
    - AWSAccessKeyId=<## obviously not included ##>
    - secure: <## obviously not included ##>
build:
  pre_ci_boot:
    image_name: drydock/u14rubpls
    image_tag: prod
    pull: true
    options: --privileged=true
  ci:    
    #setup reports directories
    - mkdir -p $CI_REPORTS
    - mkdir -p $COVERAGE_REPORTS
    #setup AWS
    - mkdir -p ~/.aws 
    - SUDO=$(which sudo) && $SUDO apt-get update -qq && $SUDO apt-get install -y python-dev
    - SUDO=$(which sudo) && $SUDO pip install --upgrade pip
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awscli
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awsebcli
    - echo [default] > ~/.aws/config
    - echo "aws_access_key_id=$AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key=$AWSSecretKey" >> ~/.aws/config
    - echo "region=ap-southeast-1" >> ~/.aws/config 
    - echo [profile eb-cli] >> ~/.aws/config
    - echo "aws_access_key_id=$AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key=$AWSSecretKey" >> ~/.aws/config
    #download env files
    - AWS_CONFIG_FILE=/home/shippable/.aws/config 
    - aws s3 cp "s3://secure-config.improvemy.it/webapp/dev.env" "./dev.env"
    #setup postgres  
    - createdb -U $USER --no-password -e "imit-prototype-test"
    #install build dependancies
    - sudo apt-get update && sudo apt-get -y install $BUILD_PACKAGES $RUBY_PACKAGES    
    - gem install bundle
    #setup test env
    - bundle install
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:schema:load RAILS_ENV=test
    #test app
    - bundle exec rake test
  post_ci: 
    - SUDO=$(which sudo) && $SUDO apt-get update -qq && $SUDO apt-get install -y python-dev
    - SUDO=$(which sudo) && $SUDO pip install --upgrade pip
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awscli
    - SUDO=$(which sudo) && $SUDO pip install --upgrade awsebcli
    - echo [profile eb-cli] > ~/.aws/config
    - echo "aws_access_key_id=$AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key=$AWSSecretKey" >> ~/.aws/config   
    - mkdir -p .elasticbeanstalk
    - cp beanstalk_config.yml .elasticbeanstalk/config.yml
    - eb init 
    - eb status
    - eb deploy -v
#email notifications to the IT admin on any activity
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - <## obviously not included ##>
      on_start: always
      on_success: always
      on_failure: always 
```

These nuances make more sense if you you come from a docker world.
