### ISSUE TITLE
Shippable skips some lines from the YML script

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2392]
Look at my script source:

```
build:
  pre_ci_boot:
    image_name: ubuntu
    image_tag: wily
    pull: true

  ci:
    - shippable_retry apt-get update
    - shippable_retry apt-get install -y git
    - git config user.name "RadioKit Build Farm"
    - git config user.email "admin+buildfarm@radiokit.org"
    - cp -vf shippable-buildfarm-windows-mingw64.yml shippable.yml
    - git commit -am "[buildfarm:$BUILD_NUMBER $COMMIT] `git log -1 --pretty=%B`"
    - git remote add windows-mingw64 git@bitbucket.org:radiokitbuildfarm/electron-backbone-windows-mingw64.git
    - git push --force windows-mingw64 $BRANCH
    - git reset --soft HEAD~1
    - cp -vf shippable-buildfarm-windows-mingw32.yml shippable.yml
    - git commit -am "[buildfarm:$BUILD_NUMBER $COMMIT] `git log -1 --pretty=%B`"
    - git remote add windows-mingw32 git@bitbucket.org:radiokitbuildfarm/electron-backbone-windows-mingw32.git
    - git push --force windows-mingw32 $BRANCH
    - git reset --soft HEAD~1
```

and the outcome

![zrzut ekranu 2016-03-16 o 15 32 37](https://cloud.githubusercontent.com/assets/389651/13815850/7c5edc3e-eb8c-11e5-9faf-fdb352f3c3a8.png)

Second 

```
- git commit -am "[buildfarm:$BUILD_NUMBER $COMMIT] `git log -1 --pretty=%B`"
```

is silently skipped.

See https://app.shippable.com/runs/56e96bf8ac6b5d0d0011490e
