### ISSUE TITLE
pre_ci_boot not finding image built in pre_ci

### ISSUE THREAD

**Issue by pbkhrv** [Shippable/support#2399]
I have the following in my shippable.yml:

```
build:
  pre_ci:
    - docker build -t builder:tip .

  pre_ci_boot:
    - image_name: builder
      image_tag: tip
      pull: false
      options: "-e HOME=/root"
```

when the build runs, the pre_ci_boot step doesn't seem to pick up the `image_name` and `image_tag` vars:
```
echo 'No running build container to stop'
No running build container to stop

echo 'Using : for the build'
Using : for the build

echo 'Booting job image :'
Booting job image :

sudo docker run -d                                 -v /home/shippable/cexec:/home/shippable/cexec -v /tmp/cexec:/tmp/cexec -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock           --name=           --entrypoint=/home/shippable/cexec/build.sh           -e RUN_MODE=production           -e SHIPPABLE_API_URL=https://api.shippable.com           -e SHIPPABLE_API_RETRY_INTERVAL=3           -e SHIPPABLE_CONTAINER_NAME=           -e SHIPPABLE_IS_OFFICIAL_IMAGE=           -e SHIPPABLE_IS_LEGACY_IMAGE=           :
Unable to find image ':latest' locally
repository name must have at least one component
```
