### ISSUE TITLE
bundle command missing for official ruby image

### ISSUE THREAD

**Issue by ric03uec** [Shippable/support#2404]
- for the official ruby image `drydock/u14rubpls:prod` the following error is thrown in `ci` step
![image](https://cloud.githubusercontent.com/assets/1110988/13855519/19c22110-ec2e-11e5-8683-aa81bbd62a1a.png)

- build id: https://app.shippable.com/runs/56eaec0785ed8e0b0086085e

**Comment by manishas** [comment]
i don't think bundle is missing.. tried it out with sample and it works fine -

https://app.shippable.com/runs/56eb31622894c90c00818f54

```
language: ruby
rvm:
  - 2.2.2

services:
  - postgres
  - redis
  - elasticsearch
  
build:
  pre_ci_boot:
    image_name: drydock/u14rubpls
    image_tag: prod
    pull: true
  ci:
    - bundle install
```
