### ISSUE TITLE
bzr not found in $PATH in golang docker image

### ISSUE THREAD

**Issue by vastbinderj** [Shippable/support#2406]
When I am attempting to load a golang package from Launchpad, I see the following error:

![image](https://cloud.githubusercontent.com/assets/713960/13861425/8ba1ef2e-ec4a-11e5-8348-7bcc13a28ff1.png)

I have even tried installing `bzr` in the `pre_ci:` step and I still see this error.  Am I missing something?  Is there a reason it is not already pre-installed in the docker image?

I install `bzr` with `sudo apt-get install bzr -y`

**Comment by manishas** [comment]
@vastbinderj the pre_ci section runs outside the build container. Please include the installation command in your ci: section and it should work as expected.

**Comment by vastbinderj** [comment]
ahh - TY @manishas - will report back.

**Comment by vastbinderj** [comment]
ok - so that gets me past my first issue.  The next one is that I'm not really building in the container at this time.  Here is my shippable.yml.  Notice in the after_success section that I run a deploy.sh bash script that does the real build and running of my tests on several staging servers in my server farm.  The status shows that section is running successfully, but I know these scripts are not being run on those servers.

What am I not doing correctly?

```
language: go
go:
    - 1.5.3
env:
    global:
        - SLACK_ORG=Ottemo PROJECT=Foundation
        - secure: T2ImzTpns/H12TPzWD+/XYWBJzvLdIdBj2rzO7EgCezxBRk3EcixCCcj6ImXKxk7kyCMHJR/fALjoE7u7elHG9Y+TmtR7useu95TMVekO66RD702jrEu4LA7tUGvDfBzTw8Dr4PVeCjr0NFQlJ/z1XHk9knrsHEXydHRtQ4ciN/DTw4M1yVImp3VXYMpOePCGIfjcYA20M8/ZvTZA9Nv5f/eBcGZbPLsNCdvMasUEekWwpZzJvXycX7tS7EYc5kUZdqzpHpToY1/HYLtcLm4qmILUahWiaMKAYloA0nT/FCUcPpZLCOf0hhm9nNaEuE1YfA/3anAhBu89rqqSPzM5Q==

build:
    pre_ci:

    ci:
        - sudo apt-get install bzr -y

cache: false

install:

script:
    - go version

# only build develop
branch:
    only:
        - develop

after_failure:
    - python bin/slack_notifier.py --org $SLACK_ORG --project $PROJECT --token $SLACK_TOKEN

after_success:
    - REMOTE_HOST=rk.staging.ottemo.io bash bin/deploy.sh
    - REMOTE_HOST=kg.staging.ottemo.io bash bin/deploy.sh
    - REMOTE_HOST=mp.staging.ottemo.io bash bin/deploy.sh
    - REMOTE_HOST=demo.staging.ottemo.io bash bin/deploy.sh
    - python bin/slack_notifier.py --org $SLACK_ORG --project $PROJECT --token $SLACK_TOKEN -s

notifications:
    email: false
```

**Comment by vastbinderj** [comment]
Hold up a bit, I see now that there is a ssh failure, give me a bit to fix that.

**Comment by manishas** [comment]
First of all, a mix of yml syntax is not supported. You either need to do old format or new format....[migration guide is in our blog.](http://blog.shippable.com/migrating-to-the-new-build-platform)

Here is how your yml will look:

```
language: go
go:
    - 1.5.3
env:
    global:
        - SLACK_ORG=Ottemo PROJECT=Foundation
        - secure: T2ImzTpns/H12TPzWD+/XYWBJzvLdIdBj2rzO7EgCezxBRk3EcixCCcj6ImXKxk7kyCMHJR/fALjoE7u7elHG9Y+TmtR7useu95TMVekO66RD702jrEu4LA7tUGvDfBzTw8Dr4PVeCjr0NFQlJ/z1XHk9knrsHEXydHRtQ4ciN/DTw4M1yVImp3VXYMpOePCGIfjcYA20M8/ZvTZA9Nv5f/eBcGZbPLsNCdvMasUEekWwpZzJvXycX7tS7EYc5kUZdqzpHpToY1/HYLtcLm4qmILUahWiaMKAYloA0nT/FCUcPpZLCOf0hhm9nNaEuE1YfA/3anAhBu89rqqSPzM5Q==

build:
    ci:
      - sudo apt-get install bzr -y
      - go version
   on_failure:
      - python bin/slack_notifier.py --org $SLACK_ORG --project $PROJECT --token $SLACK_TOKEN
   on_success:
     - REMOTE_HOST=rk.staging.ottemo.io bash bin/deploy.sh
     - REMOTE_HOST=kg.staging.ottemo.io bash bin/deploy.sh
     - REMOTE_HOST=mp.staging.ottemo.io bash bin/deploy.sh
     - REMOTE_HOST=demo.staging.ottemo.io bash bin/deploy.sh
     - python bin/slack_notifier.py --org $SLACK_ORG --project $PROJECT --token $SLACK_TOKEN -s


# only build develop
branches:
  only:
    - develop

integrations:
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_pull_request: never

```
