### ISSUE TITLE
Env parameters not available on PHP cli after update

### ISSUE THREAD

**Issue by yobottehg** [Shippable/support#2416]
i just updated the shippable yml to the new version and i recognized that the environment parameters are not available on the cli with the new setup:

```
language: php
php:
  - 5.6
env:
  global:
    - FORTRABBIT_HOST=deploy.eu2.frbit.com
    - DEV_REPO=dev-forms.git
    - PROD_REPO=prod-forms.git
    - APP_ENV=test
    - SYMFONY__DATABASE__HOST=127.0.0.1
    - SYMFONY__DATABASE__PORT=~
    - SYMFONY__DATABASE__NAME=dbname
    - SYMFONY__DATABASE__USER=shippable
    - SYMFONY__DATABASE__PASSWORD=
    - SYMFONY__CSS=dev
services:
  - mysql
build:
  ci:
    - echo "xdebug.max_nesting_level = 1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e 'CREATE DATABASE $SYMFONY__DATABASE__NAME;'
    - mkdir -p shippable/testresults
    - composer self-update 1.0.0-beta1 -n
    - composer install --prefer-source -n
    - ./app/console server:start -n
    - ./app/console doctrine:schema:update --force
    - ./app/console cache:clear --env=prod
    - phpunit -c app --log-junit shippable/testresults/junit.xml

  on_success:
    - git remote add dev git@$FORTRABBIT_HOST:$DEV_REPO
    - git remote add prod git@$FORTRABBIT_HOST:$PROD_REPO
    - ssh-keyscan $FORTRABBIT_HOST >> ~/.ssh/known_hosts
    - >
      [[ $BRANCH = 'master' ]] && REMOTE=prod || REMOTE=dev
    - git push $REMOTE $BRANCH:master -f
    - ./app/console server:stop -n
```

`./app/console doctrine:schema:update --force` fails with connecting to database. With the old setup this worked:

```
language: php
php:
  - 5.6
env:
  global:
    - FORTRABBIT_HOST=deploy.eu2.frbit.com
    - DEV_REPO=dev-forms.git
    - PROD_REPO=prod-forms.git
    - APP_ENV=test
    - SYMFONY__DATABASE__HOST=127.0.0.1
    - SYMFONY__DATABASE__PORT=~
    - SYMFONY__DATABASE__NAME=dbname
    - SYMFONY__DATABASE__USER=shippable
    - SYMFONY__DATABASE__PASSWORD=
    - SYMFONY__CSS=dev

before_install:
  - echo "xdebug.max_nesting_level = 1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - mysql -e "CREATE DATABASE $SYMFONY__DATABASE__NAME"
  - mkdir -p shippable/testresults
  - composer self-update -n
  - composer install --prefer-source -n
  - ./app/console doctrine:schema:update --force
  - ./app/console cache:clear --env=prod

script:
  - ./app/console server:start -n
  - phpunit -c app --log-junit shippable/testresults/junit.xml

after_script:
   - ./app/console server:stop -n

after_success:
  - git remote add dev git@$FORTRABBIT_HOST:$DEV_REPO
  - git remote add prod git@$FORTRABBIT_HOST:$PROD_REPO
  - ssh-keyscan $FORTRABBIT_HOST >> ~/.ssh/known_hosts
  - >
    [[ $BRANCH = 'master' ]] && REMOTE=prod || REMOTE=dev
  - git push $REMOTE $BRANCH:master -f

notifications:
  email: false

```

Any help would be good.
Thank you
