### ISSUE TITLE
git_sync step fails

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2417]
git_sync step fails in case of this build: https://app.shippable.com/runs/56efd567d7fd180d00e3df5f

The command was

`ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone ssh://.....'`

**Comment by rageshkrishna** [comment]
@mspanc There is a known issue with using shippableImages on the new build system. The problem is that those images were not built to set $HOME or $USER. The new build system does not initialize these variables any more. There are two ways to fix this:

1. Use the `drydock` images for your build instead of shippableImages. Please see http://docs.shippable.com/ci_languages/#nodejs for a list of supported images. Moving forward, we will only be maintaining the `drydock` images with the latest updates, so this is the recommended fix.

1. If you have already updated [to the new shippable.yml file format](http://docs.shippable.com/ci_configure/), you should be able to pass the HOME and USER settings via the `pre_ci_boot` section:

````
build: 
  pre_ci_boot:
    imageName: shippableImages/ubuntu1404_node
    imageTag: latest
    options: "--user root -e HOME=/root -e USER=root"
````

I hope this helps.

**Comment by mspanc** [comment]
I've changed the image to 

```
pre_ci_boot:
  image_name: drydock/u14nod
  image_tag: prod
  pull: true
```

but now I run into this: https://github.com/Shippable/support/issues/2418
