### ISSUE TITLE
nvm install step fails

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2418]
It is impossible to install nodejs 4.2.3.

The `nvm install 4.2.3` crashes on compilation.

Build URL: https://app.shippable.com/runs/56efd5d061cf9e100096eaeb

**Comment by manishas** [comment]
@mspanc the build you have linked to is still using shippable/minv2. Look at the boot container section and you will see it there.

Can you share your yml? I just tried with drydock/u14nod:prod and did not run into an error with 4.2.3. My yml was:

```
# Language setting
language: node_js

# Version number
node_js:
  - 4.2.3

build:
  pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: true

  ci:
    - npm install
```
