### ISSUE TITLE
Integration name match problem

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2427]
https://app.shippable.com/runs/56f24d388ded2a0e004182f3

```
integrations:
    hub:
      - integrationName: mygento
        type: docker
        agent_only: true
      - integrationName: Docker
        type: docker
        agent_only: true
```

both the same as in account

**Comment by rageshkrishna** [comment]
@luckyraul Thanks for reporting this. I'll see if there's a good way to surface this error message.

**Comment by avinci** [comment]
this is in production and should be throwing a console error.

**Comment by luckyraul** [comment]
ok, how to place my CA into ```/etc/docker/certs.d/```?

```
v2 ping attempt failed with error: Get https://hub.cloud.mygento.net:5000/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://hub.cloud.mygento.net:5000/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry hub.cloud.mygento.net:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/hub.cloud.mygento.net:5000/ca.crt'
```

**Comment by luckyraul** [comment]
any updates?

**Comment by avinci** [comment]
@luckyraul this is a feature request as we don't have a way to do this right now. I am going to get this prioritized internally and get back to you....

**Comment by avinci** [comment]
@manishas the problem is that we don't have a way to run a script while we do `pre_ci_build`. 

@luckyraul, can you share your YML to avi@shippable.com if you don't want to put it in here so that we can come up with a design

**Comment by luckyraul** [comment]
```
build:
    pre_ci_boot:
        image_name: mygento/php
        image_tag: 5.6
        pull: true
    ci:
     - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
     - php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '41e71d86b40f28e771d4bb662b997f79625196afcca95a5abf44391188c695c6c1456e16154c75a211d238cc3bc5cb47') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
     - php composer-setup.php
     - php -r "unlink('composer-setup.php');"
     - mv composer.phar /usr/local/bin/composer
     - composer install
    on_success:
        docker build -t mygento_sample:$BRANCH .
        docker push mygento_sample:$BRANCH

integrations:
    hub:
      - integrationName: mygento
        type: private docker registry
        agent_only: true
      - integrationName: Docker
        type: docker
        agent_only: true
```
