### ISSUE TITLE
secret environment usage is not clear

### ISSUE THREAD

**Issue by menny** [Shippable/support#2443]
I'm trying to use environment variable with a CI using a custom docker image in my [open source project](https://github.com/AnySoftKeyboard/AnySoftKeyboard/).
This is my `shippable.yml` file: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/shippable.yml

It seems that no matter what I do, the scripts inside the Docker image do not get the environment variable values.

For example, (this is from my shippable.yml file) :
```
build:
  pre_ci_boot:
    image_name: menny/android_ndk
    image_tag: latest
    pull: true
  env:
    global:
    - MY_TEST_ENV_VAL="TestWorked"
    - secure: AAM8atSJwUAt5lXGUoepcT6/+xoX8NzHs88goeBJrc3S9+Pow6pxDPx0ySQeZsat2ZBskXidEdlb37WoQn2cKU1BfYoU/aCPKxezBI827ivtsPunyQtrWS6UHQdLfj83aU2Sg3uS3aZa9hzenJbxipfUVPutW+sqd0OP5YE4YZlCGmYlrOwXNWze+We+1E4jO6DQPBuXWlHD6v6eAo8gBYtejc8gex62vYfy/O4JFCRMoaJWEw+l8/lXt/jv0p0pvbfax9oltZmtGNGUKyebw4RbFSUbytdYWvRcxPnZ1kTXuLNLiXiUs8pETXj+W2tdn3ptkThD8z4JKtS4BG6daVrpE0VeC5Pn8q2i6SKtoh3/73IGpo5N3PjgOW+u0Bk0EUVRZhQmJG20At6vqPO3a+ErsthJNU+OGgBmi1GpeV3pHcERzgTK6xrPRegWPl7wPZHSxak4u4POrFJml8S3MdB7tfmQBziwtM6Q5Kb1CXbI827miHO5MvYCm40rfI9SL8XA6eXZtHLcldRUVb1AxRFENdg7WZbDPqtRusE352lRQmdCwVGg+UI3/WYW69THdvDPTyK62s++XxbHQJLZ0Gg1JnbfBm7+kC8g+y1zt+AJZwR9F5EWfniY0PlxjY8eNlzC2+YRxdqa90EomUKcsMECtztRYa13vQBfYzlVpew=
  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - echo "ALIAS $ANYSOFTKEYBOARD_KEYSTORE_ALIAS"
    - echo "Test $MY_TEST_ENV_VAL"
    - ./download_signing_files.sh $ANYSOFTKEYBOARD_KEYSTORE_ALIAS $MY_TEST_ENV_VAL
    - ./gradlew clean testDebug checkDebug
```

the `echo` call will not output anything, and the `download_signing_files.sh` does not seem to get the variable values too (see an actual CI run [here](https://app.shippable.com/runs/56f6a7512501a30d00de6560))

What am I doing wrong?

Thanks!

**Comment by manishas** [comment]
@menny you need to tweak your yml a bit. The `env` tag should be at the same level as the `build` tag as shown below:

```
 env:
    global:
    - MY_TEST_ENV_VAL="TestWorked"
    - secure: AAM8atSJwUAt5lXGUoepcT6/+xoX8NzHs88goeBJrc3S9+Pow6pxDPx0ySQeZsat2ZBskXidEdlb37WoQn2cKU1BfYoU/aCPKxezBI827ivtsPunyQtrWS6UHQdLfj83aU2Sg3uS3aZa9hzenJbxipfUVPutW+sqd0OP5YE4YZlCGmYlrOwXNWze+We+1E4jO6DQPBuXWlHD6v6eAo8gBYtejc8gex62vYfy/O4JFCRMoaJWEw+l8/lXt/jv0p0pvbfax9oltZmtGNGUKyebw4RbFSUbytdYWvRcxPnZ1kTXuLNLiXiUs8pETXj+W2tdn3ptkThD8z4JKtS4BG6daVrpE0VeC5Pn8q2i6SKtoh3/73IGpo5N3PjgOW+u0Bk0EUVRZhQmJG20At6vqPO3a+ErsthJNU+OGgBmi1GpeV3pHcERzgTK6xrPRegWPl7wPZHSxak4u4POrFJml8S3MdB7tfmQBziwtM6Q5Kb1CXbI827miHO5MvYCm40rfI9SL8XA6eXZtHLcldRUVb1AxRFENdg7WZbDPqtRusE352lRQmdCwVGg+UI3/WYW69THdvDPTyK62s++XxbHQJLZ0Gg1JnbfBm7+kC8g+y1zt+AJZwR9F5EWfniY0PlxjY8eNlzC2+YRxdqa90EomUKcsMECtztRYa13vQBfYzlVpew=

build:
  pre_ci_boot:
    image_name: menny/android_ndk
    image_tag: latest
    pull: true
 
  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - echo "ALIAS $ANYSOFTKEYBOARD_KEYSTORE_ALIAS"
    - echo "Test $MY_TEST_ENV_VAL"
    - ./download_signing_files.sh $ANYSOFTKEYBOARD_KEYSTORE_ALIAS $MY_TEST_ENV_VAL
    - ./gradlew clean testDebug checkDebug

```
