### ISSUE TITLE
Archive is not created

### ISSUE THREAD

**Issue by menny** [Shippable/support#2444]
I'm trying to enable the `archive` option in my `shippable.yml` file on a CI using a custom docker image in my [open source project](https://github.com/AnySoftKeyboard/AnySoftKeyboard/).
But it seems to have no effect.

At the top of my shippable file I've added `archive: true`, and then added `cp` calls in the `ci:` section:
```
build:
  pre_ci_boot:
    image_name: menny/android_ndk
    image_tag: latest
    pull: true
  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - ./download_signing_files.sh
    - ./gradlew clean testDebug checkDebug
    - ./gradlew jacocoTestReport
    - cp -r build/test-results/* shippable/testresults/
    - cp -r build/jacoco/* shippable/codecoverage/
    - cp -r build/reports/jacoco/jacocoTestReport/* shippable/codecoverage/
    #- ./gradlew clean assembleCanary publishCanary -PenableApkPublish
    - ./gradlew clean assembleDebug assembleCanary assembleRelease
    - cp build/outputs/apk/* shippable
```

https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/shippable.yml

What am I doing wrong?

Thanks!

**Comment by manishas** [comment]
@menny in the new build platform, archiving is not available as a built in feature. 

You will need to upload the artifacts to your S3 bucket by following the instructions in the link below:
http://docs.shippable.com/ci_configure/#build-artifacts

**Comment by menny** [comment]
That's unfortunate, it's a big benefit to have archives per build, making it very clear where I can find the specific build output

**Comment by manishas** [comment]
@menny i am going to tag this as a feature request. We so plan to add support for archiving again, so leaving this open..

**Comment by menny** [comment]
Thank you

**Comment by incapture-build** [comment]
Came here looking for this. Your documentation still says that you should be able to download any artifacts you place in the ~/shippable dir. I've been pulling my hair out trying to get that to work, but apparently you decided to take it away? What good is a CI tool if i can't get information on why the build failed?

I looked at the S3 documentation you provided above. Your documentation here on secure environment variables is unclear: http://docs.shippable.com/ci_projects/#encrypting-your-environment-variables
"To encrypt a variable, enter the environment variable and its values in the text box as shown below and click on Encrypt-" -- What? click on encrypt? where?

**Comment by incapture-build** [comment]
I could possibly try the API, yet that's not available to non-paid accounts. Hard to convince me to pay up  & move over if I can't simply retrieve artifacts..

**Comment by manishas** [comment]
@incapture-build you need to go to the Settings of the Project -

![image](https://cloud.githubusercontent.com/assets/2983749/15000186/b39341be-1142-11e6-9c67-0cab62d6bd8a.png)

Scroll down until you get to the `Encrypt` section -

![image](https://cloud.githubusercontent.com/assets/2983749/15000199/cf63aaa0-1142-11e6-9f90-ee2ca2118a5a.png)

enter your variables in the textbox in the format `AWS_ACCESS_KEY_ID="4yfht" AWS_SECRET_ACCESS_KEY=75yghg78igfngby75hfj"` and click on Encrypt. Copy the contents of the textbox by clicking on Copy

![image](https://cloud.githubusercontent.com/assets/2983749/15000226/1bf22662-1143-11e6-8fbe-0386a8509842.png)
 
In your shippable.yml, you should paste the secure variable in the `env` section of your yml and push to S3 as shown in the docs -

```
env:
  global:
    #secure variable contains values for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: HKwYujx/qmsyQQdHvR2myu8HLUDtcLeDyYV149YJuxIV4J7Hk3SxeY8X3D6aTlR8mvMnd/ZFY+tGNUh4G0xtLLjjZcPsBgvFlB

build:
  on_success:
    - aws s3 sync $SHIPPABLE_BUILD_DIR "s3://bucket_name" --region "us-east-1"
``` 
 
Let me know if this works.
