### ISSUE TITLE
Hub login fails

### ISSUE THREAD

**Issue by knowredev** [Shippable/support#2445]
I'm trying to move the github repositories to new organizations so Shippable account is also moved. However, it cannot login to Docker hub when trying to build on Shippable. The error messages are below:

I checked the password many times and the error message is different when I type dockerhub password wrong on purpose. Any idea?

```
  echo 'Hub login failed'
  echo 'Docker login failed for username knowre and email dev@knowre.com'
  echo 'Error response from daemon: Registration: "Password is too short (1), needs to be at least 5 characters"'
```

**Comment by avinci** [comment]
A couple of things to check. Is your project integration on settings page accurate? Does the name of the project integration match your YML? If you could share your projectId, I can try and debug it...

**Comment by knowredev** [comment]
I'm not sure what you mean projectId, but these are the URLs of the project and build attempt.
https://app.shippable.com/projects/567bb5fe1895ca447466e46a
https://app.shippable.com/runs/56f7f3c09ae7e90c004537a3

And this is the content of shippable.yml below:
```
language: node_js
before_install:
  - npm install -g eslint
branches:
  only:
    - testing
env:
  global:
    - secure: blahblah==
integrations:
  deploy:
    - integrationName: "AWS Knowre Infra"
      type: AWS
      target: eb_paas
      platform: "docker"
      application_name: Glesea-testing
      env_name: glesea-testing
      branch: testing
      bucket_name: knowre-shippable
      region: ap-northeast-1
```

**Comment by avinci** [comment]
You are using project settings for Docker. We retired that functionality, can you delete all your docker settings and move to the new YML structure? You will need to add a docker hub integration and use the `pre_ci_build` & `pre_ci_boot` tags to accomplish what you are trying to do.

here is a blog that should talk more about this. 
http://blog.shippable.com/migrating-to-the-new-build-platform

**Comment by KnowRe** [comment]
I removed docker settings and tried several configuration but the hub login is still an issue. Here's my new `shippable.yml` file:

```
language: node_js
node_js:
  - "5.7.0"
env:
  global:
    - secure: blahblah==
branches:
  only:
    - testing
build:
  pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: true
    options: "-e HOME=/root"
  ci:
    - npm install -g eslint
  post_ci:
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="knowre/glesea:$BRANCH.$BUILD_NUMBER" .
    - docker push knowre/glesea:$BRANCH.$BUILD_NUMBER
integrations:
  hub:
    - integrationName: "Knowre Docker Hub"
      type: docker
  deploy:
    - integrationName: "AWS Knowre Infra"
      type: AWS
      target: eb_paas
      platform: "docker"
      application_name: Glesea-testing
      env_name: glesea-testing
      branch: testing
      bucket_name: knowre-shippable
      region: ap-northeast-1
```
