### ISSUE TITLE
Compatibility clarification with .travis.yml file format

### ISSUE THREAD

**Issue by thaiat** [Shippable/support#246]
Hi, 
Shippable documentation is saying that a `.travis.yml` file could be used as is.
I was wondering if this include their deploy section:

```
deploy:
  provider: heroku
  api_key: ...
  app: my-app-123
```

For my tries it does not seem to be the case...
