### ISSUE TITLE
docker image is not pulled from docker hub

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2463]
please investigate, here is the build id:

https://app.shippable.com/runs/56fc2d751368e80c00cd3b3f

**Comment by a-murphy** [comment]
It looks like you were migrated to our new build system today.  If you have not already migrated to the new YML, you will have to do so to use a custom Docker image.  We have a guide to migration available in our [blog](http://blog.shippable.com/migrating-to-the-new-build-platform).  If you already updated your shippable.yml, then you may want to check that you included the ```integrations``` section at the same level as ```build```.

**Comment by manishas** [comment]
@n0mer In addition to a [migration guide](http://blog.shippable.com/migrating-to-the-new-build-platform), we also have [some tips](http://blog.shippable.com/5-tips-for-a-successful-migration) to help solve common migration issues.

**Comment by manishas** [comment]
@n0mer please let us know if you need any more help with this. Happy to jump on a hangout and help with the migration to new yml if necessary.

**Comment by n0mer** [comment]
@manishas yes i'd definitely need your assistance with migration.

my shippable.yml is quite small and not tricky at all

**Comment by n0mer** [comment]
actually - here it is

```yml
# language setting
language: node_js

build_image: n0mer/pdna-backend:dashboard-app-build

archive: true

# version numbers
node_js:
  - "0.12.7"

branches:
  only:
    - master

#debug
before_install:
  - node --version
  - pwd
  - whoami
  - echo $HOME

# Running the tests with grunt
script:
  - npm install --allow-root
  - bower install --allow-root
  - gulp deploy_artefacts

after_success:
  - pwd
```
