### ISSUE TITLE
Trying to migrate, do not know if I completed changes to my YML right

### ISSUE THREAD

**Issue by copyhawk** [Shippable/support#2475]
https://app.shippable.com/runs/56fede7ecb505d0b00b8ae9f

**Comment by manishas** [comment]
Can you share your yml so we can take a look?

**Comment by copyhawk** [comment]
# Language setting - TODO: UPDATE YML
language: node_js

# Version number
node_js:
  - 4.2.1 # EB supported version

# Cache environment
cache: true

# Mongo binds to 127.0.0.1 by default
# memcached runs on port 11211
services:

env:
  global:
    - XUNIT_FILE=shippable/testresults/xunit.xml MongoConnectionStringTests=mongodb://127.0.0.1:27017/test MemcachedLocationTest=localhost:11211 LogLevel=error BraintreeEnvironment=Sandbox
    - secure: GVfbYWQ6H65vvkehkZLnfwKrFpmFBumlseB1/ZeiCbUjTk2oWrxrw81ZFF0c2G6D0WShLvyK+I9b5OyO32Ln8c34fOD93Vo/DXEtWa74mGezTCuO3hCO2MwDbRldji03qcK/5E4yqwcz5IGIFU6m0Pa5ydvy1vvvQHwfGGEL5A7xF7TQSCw2IcmMVWT+ddBtTUssTr+2RJgpDpiaKbEIFfA14wFI8wl2geIObeHoOZlNBo405v4n/Sw8JLMQWOtkzY9cIKgIIJkbp1upZDvZvf1mnpLpi/vpIIE4eNmdktp3yBgJY9/tKITXzp8sRxGRc3ZdoWwhj2mzhypbK8P7T3Ac7O9hpXwXYmhSxXOj1voK6flJ/YUby2nT+nqtBEgNPmsbVLe7Wsugw/eXxiPpBL4Bmdmp3DbdcL2RMzFkmnEv45UjRIWs+FWRC2rPrwewALln8z0IOVcuryAuEqS0Itek6g4gvDZ5hgyjPo5A6IinqTwJhWHStzkUGqN0DHyOwRSK1yHl7qpAsIKZtMCxw9LMHmeS+6XsDHPmJF8FfC6UyL+OR8R5EDcKM6aMFETz6C7FoRc6AUA5CZ3pyu+zYlshDBUofzj4BMIfIP35OjPM8dvKwKR75N39AwyaInc8I+J8YvL1Qqm0opE1p79qrsrfGo22V1o4//D15VpsjSE=

build_image: drydock/u14nod:prod

build:
  ci:
    - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
    - shippable_retry npm install
    - node --version
    - sudo npm install -g istanbul
    - . installMongoAndMemcachedCI.sh
    - sudo mongod --smallfiles &
    - sleep 15
    - mongo --eval 'db.collection.find()'
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm run-script ci

  on_success:
    - mongo test --eval "db.dropDatabase()"
    - istanbul report cobertura --dir  shippable/codecoverage/
    - cat shippable/codecoverage/cobertura-coverage.xml

  on_failure:
    - mongo test --eval "db.dropDatabase()"
    - istanbul report cobertura --dir  shippable/codecoverage/
    - cat shippable/codecoverage/cobertura-coverage.xml

integrations:
    notifications:
      - integrationName: email
        type: email
        recipients:
          - admin@copyhawk.co
        on_start: false
        on_success: change
        on_failure: false
        on_pull_request: true
        branches:
          only:
            - master

**Comment by copyhawk** [comment]
YML is attached, markdown made it look formatted, I'll simply attach it here.

[shippable.yml.txt](https://github.com/Shippable/support/files/200557/shippable.yml.txt)

**Comment by manishas** [comment]
@copyhawk is there a reason you're not using the pre-installed mongodb and memcached?

**Comment by copyhawk** [comment]
Yes, they were not working for me before and on a previous case I was
recommended to use this.

**Comment by manishas** [comment]
The yml looks right. 

@kanthchandra can you look into why this build is failing?

**Comment by kanthchandra** [comment]
@copyhawk I dont know how you are installing memcached and mongodb, since you are running it from a script. If you can post that here I'll try to help you.

But as an alternative I would suggest you to use drydock/u14nodall:prod image which has memecached and mongodb installed. You can invoke memcached and mongodb by using the services tag. 

Here is a sample_node project https://github.com/kanthchandra/sample_node/blob/master/shippable.yml 
Link to successful build: https://app.shippable.com/runs/570206ddb50f850c0042a9eb

**Comment by copyhawk** [comment]
Tried that image and it still fails.

**Comment by kanthchandra** [comment]
@copyhawk you have used that image, but you havent started, mongodb and memcached. You need to add the services tag in order to start them. More information on configuring your build can be found here http://ship-docsv2.s3-website-us-west-2.amazonaws.com/ci_configure/

Can you please replace your yml file with this and see if it works and let us know?

```
# Language setting
language: node_js

# Version number
node_js:
  - 4.2.1

env:
  global:
    - XUNIT_FILE=shippable/testresults/xunit.xml MongoConnectionStringTests=mongodb://127.0.0.1:27017/test MemcachedLocationTest=localhost:11211 LogLevel=error BraintreeEnvironment=Sandbox
    - secure: GVfbYWQ6H65vvkehkZLnfwKrFpmFBumlseB1/ZeiCbUjTk2oWrxrw81ZFF0c2G6D0WShLvyK+I9b5OyO32Ln8c34fOD93Vo/DXEtWa74mGezTCuO3hCO2MwDbRldji03qcK/5E4yqwcz5IGIFU6m0Pa5ydvy1vvvQHwfGGEL5A7xF7TQSCw2IcmMVWT+ddBtTUssTr+2RJgpDpiaKbEIFfA14wFI8wl2geIObeHoOZlNBo405v4n/Sw8JLMQWOtkzY9cIKgIIJkbp1upZDvZvf1mnpLpi/vpIIE4eNmdktp3yBgJY9/tKITXzp8sRxGRc3ZdoWwhj2mzhypbK8P7T3Ac7O9hpXwXYmhSxXOj1voK6flJ/YUby2nT+nqtBEgNPmsbVLe7Wsugw/eXxiPpBL4Bmdmp3DbdcL2RMzFkmnEv45UjRIWs+FWRC2rPrwewALln8z0IOVcuryAuEqS0Itek6g4gvDZ5hgyjPo5A6IinqTwJhWHStzkUGqN0DHyOwRSK1yHl7qpAsIKZtMCxw9LMHmeS+6XsDHPmJF8FfC6UyL+OR8R5EDcKM6aMFETz6C7FoRc6AUA5CZ3pyu+zYlshDBUofzj4BMIfIP35OjPM8dvKwKR75N39AwyaInc8I+J8YvL1Qqm0opE1p79qrsrfGo22V1o4//D15VpsjSE=

services:
  - mongodb
  - memcached

build:
  pre_ci_boot:
    image_name: drydock/u14nodall
    image_tag: prod
    pull: true
    options: '--privileged=true --net=bridge'

  ci:
    - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
    - shippable_retry npm install
    - node --version
    - sudo npm install -g istanbul
    - sudo mongo --eval 'db.collection.find()'
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm run-script ci

  on_success:
    - mongo test --eval "db.dropDatabase()"
    - istanbul report cobertura --dir shippable/codecoverage/
    - cat shippable/codecoverage/cobertura-coverage.xml

  on_failure:
    - mongo test --eval "db.dropDatabase()"
    - istanbul report cobertura --dir shippable/codecoverage/
    - cat shippable/codecoverage/cobertura-coverage.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - admin@copyhawk.co
      on_start: never
      on_success: change
      on_failure: never
      on_pull_request: always
      branches:
        only:
          - master
```
