### ISSUE TITLE
Failed to setup deployment to Google Container Engine

### ISSUE THREAD

**Issue by gg-dh** [Shippable/support#2479]
I've just created deployment pipeline to GKE. Then I went to **Routing**, specified **Host Port**, checked **External?** and filled in the load balancer parameters:
- **External Port**: TCP 80
- **Health Check**: HTTP /_health

Then went to **Configuration**, clicked **Deploy**, and got this error:

```
Failed to put health check for undefined. Provider response: { error: { errors: [ [Object] ], code: 400, 
message: 'Invalid value for field \'resource.name\': \'svc-ext-b50f850c00471914-health-check\'. The name 
of the resource in request body must be the same as the resource name in the URL' } }
```

My Kubernetes dashboard of the cluster that I used as a target shows that no service (load balancer) was created, only replication controller.

Note: I'm running Kubernetes v1.2.0

**Comment by abhijitkini** [comment]
@gg-dh when you configured the host port, you need to specify a range. Could you confirm if you have used a range of ip address?
Here's more info: http://docs.shippable.com/pipelines_faq/#why-is-my-application-not-accessible-externally-even-though-my-pipeline-is-working-perfectly

**Comment by trriplejay** [comment]
@gg-dh do you get this error consistently or was in under a particular condition?

one potential workaround you can try is:
1. uncheck the 'external?' box and deploy from the configuration tab. wait for 'success' message.
2. check the 'external?' box again, choose your settings, deploy from config tab again.

**Comment by gg-dh** [comment]
@abhijitkini 

> Could you confirm if you have used a range of ip address?

If by range you mean something like `30500 - 31500`, then no, this doesn't work.
I use 31000 for my current setup.

@trriplejay I was getting this error all the time.
Your workaround actually helped.
- First I unchecked "external?" box, specified 31000 host port and deployed the app. This created some internal and external endpoints in my cluster (as I've seen in the Kubernetes dashboard), but the "external" endpoint turned to be unreachable.
- Then I checked "external?" box, specified 80 port of the load balancer and "/" health check, deployed, and finally it worked.

**Comment by gg-dh** [comment]
Btw, is the ip of the load balancer immutable? I mean, what I have to do next is create a "static ip" in the google cloud console and create a DNS record. Can I be confident that the external ip won't change in the future? Or, maybe a better question is: when does the ip change, under what conditions?

**Comment by trriplejay** [comment]
Google seems to be pretty good about making that IP stick.  If you uncheck that 'external?' box again and deploy, I'd say that gives you the highest chance of losing the IP, but even in some of those cases it will reassign the same IP if you request a load balancer again.  

Deployments that don't change the routing section won't affect the IP for sure.

**Comment by gg-dh** [comment]
It would be great if we could specify that load balancer ip manually (or Shippable would remember it and reuse when load balancer is recreated).

That's how I can do it via the Kubernetes resources configs.

First, I create the service without specifying the ip:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: balkan
  labels:
    name: balkan
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    name: balkan
```

This actually allocates some external ip. Then I go to the cloud console -> Networking -> External IP addresses, search for this ip and make it static.

Then I modify the config.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: balkan
  labels:
    name: balkan
spec:
  type: LoadBalancer
  loadBalancerIP: XXX.XXX.XXX.XXX # static IP allocated in the Google Cloud
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    name: balkan
```

And now I'm confident that I won't lose that ip unless I make it ephemeral in the cloud console!
I can delete and recreate the load balancer, but the ip will be the same all the time.

Is it possible? Maybe I should create a separate issue for that?

Nevertheless, thank you for your support regarding the original problem.
