### ISSUE TITLE
Unable to start PostgreSQL with custom configuration.

### ISSUE THREAD

**Issue by lucasmpb** [Shippable/support#2481]
Hello guys, I'm having the same problem reported here (#1013), trying to setup the `SHIPPABLE_POSTGRES_CMD` env variable.

```
env:
  global:
    - SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf\" -c \"fsync=off\" -c \"synchronous_commit=off\""
```
I'm using the postgresql 9.3 addon
```
addons:
  postgresql: '9.3'
```
But it's still using the default cmd
```
postgres_start 5s
  sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config_file=/etc/postgresql/9.3/main/postgresql.conf > /dev/null 2>&1 &"
```
Same thing if I echo the env var
```
echo $SHIPPABLE_POSTGRES_CMD 0s  
sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config_file=/etc/postgresql/9.3/main/postgresql.conf
```
I'm using my own host to build (BYOH feature)

**Comment by manishas** [comment]
@lucasmpb Our latest official images do not have multiple versions of Postgres installed, they only have 9.4. If you want to use an older version, you should specify the build image to be shippable/minv2 or your custom image with the specific version you need. 

The following snippet in your yml will pull shippable/minv2 for your build:

```
build:
  pre_ci_boot: 
    image_name: shippable/minv2
    image_tag: latest
    pull: true

```

**Comment by lucasmpb** [comment]
Hi @manisha. According to the build log, it looks like we are already using `shippable/minv2:latest`

```
echo 'Booting job image shippable/minv2:latest' 0s  
Booting job image shippable/minv2:latest
```

This is the build ID if you want to take a look at the logs `5701448915baad0c002c0b2b`

**Comment by rageshkrishna** [comment]
@lucasmpb I took a deeper look at this today and it appears that we have regressed on the ability to pass options to services when they start up in the new build system. We're working on enabling this again and should have an update for you a little later today.

**Comment by lucasmpb** [comment]
Thanks Ragesh, i appreciate it.

**Comment by manishas** [comment]
@lucasmpb this is now fixed. Please let us know if it works. Thanks!

**Comment by harsh157** [comment]
You will need to define the env. variables that you use in postgres start command in yml.

Sample yml:
```


# Language setting
language: node_js

services:
  - postgres

env:
  global:
    - SHIPPABLE_POSTGRES_VERSION="9.4"
    - SHIPPABLE_POSTGRES_BINARY="/usr/lib/postgresql/$SHIPPABLE_POSTGRES_VERSION/bin/postgres"
    - SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf\" -c \"fsync=off\" -c \"synchronous_commit=off\""

  matrix:
    - M1=ONE

build:

  ci:
    - ps -eax

```
