### ISSUE TITLE
Some failed builds do not trigger a Slack notification

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2516]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Some failed builds do not trigger a Slack notification (but others do). Somes examples (I'll add more when I see more):

https://app.shippable.com/runs/570b722da6dbbe0c00f47263
https://app.shippable.com/runs/570bd53ae9b5240d0064b10c
https://app.shippable.com/runs/570cc071ab73e00c0029fa32
https://app.shippable.com/runs/570cbb4a7f71080c006c2e38

The Slack integration looks like this in the `.shippable.yml` file:

```
integrations:
  notifications:
    - integrationName: slack
      type: slack
      recipients:
        - #dev
      on_success: never
      on_failure: always
```

I'm not sure what's the problem. How can we diagnose this further?

**Comment by pranaypareek** [comment]
@pquentin would you please try using double quotes around the name of the slack channel?

```
      recipients:
        - "#dev"
```

We expect the channel names to be wrapped in quotes (http://docs.shippable.com/ci_configure/#slack-notifications)

The reason why this might be working in your case is if you have some channel names configured from the UI in the account integration. Our system takes those values as strings.

I reproduced this issue using my sample (https://github.com/pranaypareek/samplePyt/blob/support_2516/shippable.yml)

```
integrations:
  notifications:
    - integrationName: slack
      type: slack
      recipients:
        - "#guilty_spark"
        - #test_interns
      on_success: never
      on_failure: always
```

I was able to receive the messages for the channel `"#guilty_spark"`  but not for `#test_interns` since this format isn't recognized.

Please let us know if the problem persists after making the change!
