### ISSUE TITLE
Reusing load balancer IP (GKE)

### ISSUE THREAD

**Issue by gg-dh** [Shippable/support#2518]
It would be great if we could specify load balancer ip manually (or Shippable would remember it and reuse when load balancer is recreated).

That's how I can do it via the Kubernetes resources configs.

First, I create an LB without specifying the ip:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: balkan
  labels:
    name: balkan
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    name: balkan
```

This actually allocates some external ip. I go to the cloud console -> Networking -> External IP addresses, search for this ip and make it static.

Then I modify the config.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: balkan
  labels:
    name: balkan
spec:
  type: LoadBalancer
  loadBalancerIP: XXX.XXX.XXX.XXX # static IP allocated in the Google Cloud
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    name: balkan
```

Now I'm confident that I won't lose that ip unless I make it ephemeral in the cloud console.
I can delete and recreate the LB, but the ip will be the same all the time.
