### ISSUE TITLE
Build failure, PostgreSQL not found

### ISSUE THREAD

**Issue by neilberkman** [Shippable/support#2519]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Trying to set up a simple rails app with PostgreSQL.  In the build_ci step I'm getting:

```
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"fuelsherpa_test", "pool"=>5, "username"=>"postgres", "password"=>nil, "min_messages"=>"warning"}
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
```

Did this to get past an issue installing the pg gem:
https://github.com/Shippable/support/issues/1241#issuecomment-107207262

But now I'm getting stuck on the "could not connect to server" issue.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure

https://app.shippable.com/runs/570d157c9c1cba0c004af9ae

- `shippable.yml` (optional, would really help expedite troubleshooting)

``` yaml
language: ruby
rvm:
  - 2.3.0
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
before_script:
  - cp config/database.shippable.yml config/database.yml
  - bundle exec rake db:setup
script:
  - bundle exec rake test
```

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Are you starting Postgres in your script, or expecting it to already be running?  If you want Shippable to start Postgres for you, you will have to specify it in the [services](http://docs.shippable.com/ci_configure/#services) section of ```shippable.yml``` as follows:

```YML
services:
  - postgres
```

**Comment by manishas** [comment]
@neilberkman we do not start postgres by default, so you will need to specify it in your yml with the following:

```
services:
  - postgres
```

Also, is there a reason you're not using our new yml format documented at http://docs.shippable.com/ci_configure/

With the new format, your yml will be:

```
language: ruby
rvm:
  - 2.3.0
services:
  - postgres

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - cp config/database.shippable.yml config/database.yml
    - bundle exec rake db:setup
    - bundle exec rake test

```

**Comment by neilberkman** [comment]
Thanks.  Now my shippable.yml is:

``` yaml
language: ruby
rvm:
  - 2.3.0
services:
  - postgres

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - cp config/database.shippable.yml config/database.yml
    - bundle exec rake db:setup
    - bundle exec rake test
```

Latest build failure is:
https://app.shippable.com/runs/570d4eb85f74910c00f7f774

It's failing on this step:

```
  bundle exec rake db:setup 0s  
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-11.1.2 in any of the sources (Bundler::GemNotFound)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
