### ISSUE TITLE
"Could not find rake-11.1.2" error on bundle exec rake

### ISSUE THREAD

**Issue by neilberkman** [Shippable/support#2520]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Using ruby 2.3.0, build is failing on this step:

```
  bundle exec rake db:setup 0s  
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-11.1.2 in any of the sources (Bundler::GemNotFound)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure

https://app.shippable.com/runs/570d4eb85f74910c00f7f774
- `shippable.yml` (optional, would really help expedite troubleshooting)

``` yaml
language: ruby
rvm:
  - 2.3.0
services:
  - postgres

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - cp config/database.shippable.yml config/database.yml
    - bundle exec rake db:setup
    - bundle exec rake test
```
- Scripts called from the yml (optional)
