### ISSUE TITLE
Need docker engine > 1.10.0 available on Minion

### ISSUE THREAD

**Issue by filipegiusti** [Shippable/support#2532]
# technical issue

### Description of your issue:

Trying to run my tests using docker-compose and got the following error:

```
The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.10.0 or greater.
```

https://app.shippable.com/runs/571173d14019220b0069ff52

shippable.yml:

```yml
language: none

build:
  post_ci:
    - sudo pip install -U docker-compose
    - docker-compose up -d
    - docker-compose exec app bundle exec rails db:setup
    - docker-compose exec app bundle exec rails test
```

docker-compose.yml:

```yml
version: '2'
services:
  app:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/project_name
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - bundle_cache

  db:
    image: postgres:9.5.2

  bundle_cache:
    image: busybox
    volumes:
      - /bundle
```
