### ISSUE TITLE
ECR available in eu-west-1

### ISSUE THREAD

**Issue by sriv1211** [Shippable/support#2541]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

In your ECR integrations, only the us-east-1 region is available, but I have a repository in eu-west-1.

**Comment by trriplejay** [comment]
@sriv1211 If you're planning to push/pull an image during your CI, then we do support multiple regions.  The integration page is a bit misleading in that it only shows us-east-1.  If you're planning to use our pipeline product, then currently only us-east-1 is supported, but that will be expanded within the next couple of days.

**Comment by manishas** [comment]
This is now available. You can set the region tag in the integrations section of your yml and everything should work as expected:

```
integrations:
    hub:
      - integrationName: your_integration_name
        type: ecr
        region: eu-west-1
```
