### ISSUE TITLE
Can't start postgresql with custom image

### ISSUE THREAD

**Issue by filipegiusti** [Shippable/support#2542]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

I'm can't start postgresql with my custom image. I've tried using `services` but it doesn't start postgresql, then I tried to start the postgres container, what am I doing wrong?

https://app.shippable.com/runs/5715b2347aa8790c004b2899

shippable.yml
```
language: none

build:
  pre_ci:
    - docker build -t $REPO_NAME:$COMMIT .

  pre_ci_boot:
    image_name: $REPO_NAME
    image_tag: $COMMIT
    pull: false

  ci:
    - docker run -p 5432:5432 -d postgres:9.5.2
    - while ! nc -z localhost 5432; do sleep 1; done
    - cp config/database.shippable.yml config/database.yml
    - bundle exec rails db:setup
    - bundle exec rails test

  push:
    - docker build -t gcr.io/project/$REPO_NAME:$COMMIT .
    - docker push gcr.io/project/$REPO_NAME:$COMMIT

integrations:
  hub:
    - integratioName: hub
      type: gcr
      branches:
        only:
          - master
```
