### ISSUE TITLE
Getting '(gcloud.docker) internal_failure' on builds that worked previously

### ISSUE THREAD

**Issue by devillex** [Shippable/support#2548]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Since today, 19 April 2016, we started seeing GCE login issues on our builds. The Shippable configuration has remained the same, so has the Google Cloud Console config.

Requested Information:
- Link to the build failure: https://app.shippable.com/runs/5716399619ad990c00f7754a

- `shippable.yml`:
```
# Language setting
language: node_js

# Version number
node_js:
  - "4.4.1"

# Limit automatic builds of only specific branches (and pull requests into these branches)
branches:
  only:
    - master
    - development

build:
  pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: true
    options: '--privileged=true --net=bridge'

  ci:
    # installs dependencies (npm and bower)
    - npm install
    # run tests and save output
    - mkdir -p shippable/testresults
    - mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./shippable/testresults/mocha.xml
    # determine code coverage and store output
    - mkdir -p shippable/codecoverage
    - ./node_modules/.bin/istanbul cover --report cobertura --dir shippable/codecoverage _mocha
    # lint code and store output
    - ./node_modules/.bin/eslint -f junit -o ./shippable/testresults/lint.xml ./app/**/*.js ./test/**/*.js gulpfile.babel.js ./gulp/**/*.js
    # check code style and store output
    - ./node_modules/.bin/jscs -r junit ./app/*.js ./test/*.js gulpfile.babel.js ./gulp/*.js > ./shippable/testresults/style.xml

  on_success:

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules

integrations:
    hub:
      - integrationName: addynamo-gcr
        type: gcr
        branches:
          only:
            - master
            - development

    notifications:
        - integrationName: shippable-hipchat
          type: hipchat
          recipients:
            - "#BlueRobot - Notifications"
          branches:
              only:
                - master
                - development
          # receive notifications only when the build status changes to from failure to success, and not for subsequent successful runs
          on_success: change
          # always receive notifications for failures
          on_failure: always
```

- Scripts called from the yml: N/A

- Build output:
```
InfoProvisioning a node for subscriptionId: 56fccc619d043da07b0966a5Infols -ltra /tmp/ssh
total 8
drwxr-xr-x 2 root root 4096 Apr 19 13:47 .
drwxrwxrwt 7 root root 4096 Apr 19 13:51 ..

echo 'writing rsa key'
writing rsa key

chmod -cR 600 /tmp/ssh/01_deploy
mode of '/tmp/ssh/01_deploy' changed from 0644 (rw-r--r--) to 0600 (rw-------)


ls -ltra /tmp/ssh
total 12
drwxrwxrwt 7 root root 4096 Apr 19 13:51 ..
-rw------- 1 root root 1676 Apr 19 13:51 01_deploy
drwxr-xr-x 2 root root 4096 Apr 19 13:51 .

echo 'writing rsa key'
writing rsa key

chmod -cR 600 /tmp/ssh/00_sub
mode of '/tmp/ssh/00_sub' changed from 0644 (rw-r--r--) to 0600 (rw-------)


cd /tmp && gcloud -q auth activate-service-account --key-file key.json
Loading legacy configuration file: [/root/.config/gcloud/properties]
This configuration file is deprecated and will not be read in a future
gcloud release.  gcloud will automatically migrate your current settings to the
new configuration format the next time you set a property by running:
  $ gcloud config set PROPERTY VALUE
You may also run:
  $ gcloud init
to create a new configuration and walk you through initializing some basic
settings.  You can find more information on named configurations by running:
  $ gcloud topic configurations

Activated service account credentials for: [shippable@ad-blue-robot.iam.gserviceaccount.com]

gcloud docker -a
Loading legacy configuration file: [/root/.config/gcloud/properties]
This configuration file is deprecated and will not be read in a future
gcloud release.  gcloud will automatically migrate your current settings to the
new configuration format the next time you set a property by running:
  $ gcloud config set PROPERTY VALUE
You may also run:
  $ gcloud init
to create a new configuration and walk you through initializing some basic
settings.  You can find more information on named configurations by running:
  $ gcloud topic configurations

ERROR: (gcloud.docker) internal_failure 
```
