### ISSUE TITLE
Cache PHP extension directory

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2553]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

We are currently installing the PHP extension `intl` via Pickle as described in #2086. This process takes a bit more than one minute and we'd like to speed this up by skipping the installation if the extension is already present.

This could be achieved with the new `cache_dir_list` option but that one needs literal paths, thus the currently used `$HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-non-zts-20131226/` cannot be added to that list.

Any idea how to achieve this or if there are other options?

**Comment by manishas** [comment]
@mbrodala we have a bug at our end for this scenario. The $(phpenv version-name) is not being parsed correctly and hence there is an issue with caching this directory.

@chetantarale is going to work on fixing this.

**Comment by chetantarale** [comment]
@mbrodala This has been fixed now. Can you please try and confirm that it works .
Also [here](https://github.com/chetantarale/php-intl/blob/master/shippable.yml) is sample project for your reference.

**Comment by mbrodala** [comment]
@chetantarale Somehow it doesn't work [as it seems](https://app.shippable.com/runs/571e274c4374eb0c002c23a6). I'm using the following ATM:

```yaml
build:
  cache: true
  cache_dir_list:
    - ...
    - $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/

  ci:
    # Debug before
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l
    - >
      if [ $(find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l) -eq 0 ]; then
        # Install PHP "intl" extension for \Collator class usage
        pickle install --ansi intl
        echo "extension=intl.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      fi;
    # Debug after
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
    - find $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/ -name intl.so | wc -l
    - ...
```

The 2nd debug shows the installed `intl.so` but it's not present on rebuild/next build. Any idea why?

(I'm using this setup since I see no way to figure out the `no-debug-non-zts-20131226` part at build time, e.g. via `phpenv`.)
