### ISSUE TITLE
Not able to run build with different version of firefox

### ISSUE THREAD

**Issue by rturak** [Shippable/support#2576]
### Is your request:
- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

NOTE: If you are experiencing a build failure, please include:
- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
The ``addons`` section doesn't support multiple versions right now.  I'll mark this as a feature request.

For now, if you need multiple versions in your matrix, you will have to put the versions that you want in the ```env``` section and start them yourself in your build script.  The commands that we run to start Firefox can be found in the install_firefox_addon section of your build logs.

**Comment by rturak** [comment]
Thanks Murphy for quick reply.

My goal is to run test different versions browser in one build.

Here is the yml file:

`language: java

jdk:
   - oraclejdk8
   
addons:
  selenium: "2.53"


services:
  - selenium
  
env:
  - firefox="45.0"
  - firefox="44.0"


before_install:
 - "curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip"
 - "unzip /tmp/chromedriver.zip -d /home/shippable/bin"
 - "chmod +x /home/shippable/bin/chromedriver"
 - "echo '#!/bin/bash' | sudo tee /usr/local/bin/google-chrome"
 - "echo 'exec /usr/local/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/local/bin/google-chrome"
 - "sudo chmod +x /usr/local/bin/google-chrome"

script:
   - sudo ln -sf /tmp/firefox/firefox /usr/bin/firefox
   - export DISPLAY=:99.0
   - /etc/init.d/xvfb start
   - mvn clean cobertura:cobertura
   - mvn test`

Error:

Running TestSuite
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.533 sec <<< FAILURE! - in TestSuite
setUp(net.lacework.SignIn)  Time elapsed: 0.419 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: '31acb1b8c2aa', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-51-generic', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.Executable.<init>(Executable.java:75)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at net.lacework.SignIn.setUp(SignIn.java:38)

This error is because ff is not installed as it is not in addon section. But if i add ff version in addon section then every build will have the same version of ff installed. 
That is not what i want.

**Comment by a-murphy** [comment]
I don't think Selenium can run without a browser.  You'll have to take it out of services, and move the commands from selenium_start into your script (after installing Firefox).  I also don't see where in your script you are installing the version of Firefox that you plan to use.

**Comment by rturak** [comment]
If i add firefox version to addon section, then for very build i will get the same version of ff installed.
But i want to test different versions of ff.

**Comment by rturak** [comment]
If i provide the version of firefox in the script , its same issue. Both the builds will run with same firefox version.
Not sure by what you mean "take it out of services".
Could you please help with yml if i am missing your instructions.

**Comment by a-murphy** [comment]
I was thinking something more like this:
```YML
language: java

jdk:
  - oraclejdk8

addons:
  selenium: "2.53"

env:
  - firefox="45.0"
  - firefox="44.0"

before_install:
 # Firefox
  - "sudo wget \"https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/$firefox/linux-x86_64/en-US/firefox-$firefox.tar.bz2\""
  - sudo tar -xjvf firefox-$firefox.tar.bz2
  - sudo ln -sf /tmp/firefox/firefox /usr/bin/firefox
  - ff_version=`firefox --version 2>&1`;
  - echo "Using firefox version $ff_version"
 
  # Selenium
  - export SHIPPABLE_SELENIUM_PORT=4444
  - export DISPLAY=":99.0"
  - start_generic_service "selenium" "$SHIPPABLE_SELENIUM_BINARY" "$SHIPPABLE_SELENIUM_CMD" "$SHIPPABLE_SELENIUM_PORT" "$SHIPPABLE_SELENIUM_LOG";

  - "curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip"
  - "unzip /tmp/chromedriver.zip -d /home/shippable/bin"
  - "chmod +x /home/shippable/bin/chromedriver"
  - "echo '#!/bin/bash' | sudo tee /usr/local/bin/google-chrome"
  - "echo 'exec /usr/local/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/local/bin/google-chrome"
  - "sudo chmod +x /usr/local/bin/google-chrome"

script:
  - export DISPLAY=:99.0
  - /etc/init.d/xvfb start
  - mvn clean cobertura:cobertura
  - mvn test

  # Stop Selenium
  - sudo su -c "killall -15 java";
```
