### ISSUE TITLE
Invalid RUN language: fsharp

### ISSUE THREAD

**Issue by haf** [Shippable/support#2581]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: https://app.shippable.com/runs/57234be0a2db4f0e00635ebf
- Scripts called from the yml (optional)

```
---
language: fsharp

fsharp: 4.0.0.4

build:
  pre_ci_boot: fsharp/fsharp
  image_tag: staging
  pull: true
  options: '-e PRODUCTION=true'

  pre_ci:
    - echo "This is the master branch"

  ci:
    - bundle
    - bundle exec rake

  post_ci:
    - ls -lah
    - pwd

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/packages
```

How do I build with F# with albacore? https://github.com/Albacore/albacore/wiki

Basically: how to get started?
