### ISSUE TITLE
MySQL database in Docker container doesn't appear to be initialized on Shippable

### ISSUE THREAD

**Issue by billmccord** [Shippable/support#2590]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
I'm having a very strange issue attempting to use a MySQL database in a docker container from my application docker container. If I run these commands on my local machine it works fine, so not sure what's going on. Here is a link to my failing build:
https://app.shippable.com/runs/572880d4ef18f90c001a1baf

The relevant parts of my script are below. Note that in the ci_tests.sh script that I'm running I am attempting to create tables from the database that was defined in the $PWD/mysql/dumps file (which should have been loaded by the MySQL container into the database named 'oxr_api') using:
```
CREATE TABLE usd_rates AS SELECT * FROM oxr_api.usd_rates LIMIT 0
```

Unfortunately, it tells me:
```
Failed to CREATE TABLE usd_rates Error 1146: Table 'oxr_api.usd_rates' doesn't exist
```

However, if I run the commands on my local machine, everything works fine:
```
docker build -t openexchangerates/go-api ./go
docker build -t openexchangerates/nginx-api ./nginx
docker run -d --name mysql_api -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=oxr_api -v $PWD/mysql/dumps:/docker-entrypoint-initdb.d mysql:5.7.10
docker run -d --name api --link mysql_api -e API_MYSQL_PASSWORD=root -e API_MYSQL_HOSTNAME=mysql_api -e API_MYSQL_DB_NAME=oxr_api openexchangerates/go-api
docker run -d --name nginx_api --link api openexchangerates/nginx-api
docker exec api /go/src/github.com/openexchangerates/api/ci_tests.sh
```
All tests pass, no complaints about missing table.

Script:
```
language: python

env:
  global:
    - PROJECT_ID=openexchangerates
    - API_SERVICE=go-api
    - NGINX_API_SERVICE=nginx-api

build:
    pre_ci:
      # Build the containers.
      - docker build -t $PROJECT_ID/$API_SERVICE ./go
      - docker build -t $PROJECT_ID/$NGINX_API_SERVICE ./nginx
      
      # Make sure the containers aren't running.
      - docker stop -t 1 mysql_api || true
      - docker stop -t 1 api || true
      - docker stop -t 1 nginx_api || true
      - docker rm -f mysql_api || true
      - docker rm -f api || true
      - docker rm -f nginx_api || true
      - docker rm $(docker ps -qa --no-trunc --filter "status=exited") || true

      # Run the containers and ensure there are no issues.
      - docker run -d --name mysql_api -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=oxr_api -v $PWD/mysql/dumps:/docker-entrypoint-initdb.d mysql:5.7.10
      - docker run -d --name api --link mysql_api -e API_MYSQL_PASSWORD=root -e API_MYSQL_HOSTNAME=mysql_api -e API_MYSQL_DB_NAME=oxr_api $PROJECT_ID/$API_SERVICE
      - docker run -d --name nginx_api --link api $PROJECT_ID/$NGINX_API_SERVICE

    ci:
      # Execute the tests.
      - docker exec api /go/src/github.com/openexchangerates/api/ci_tests.sh
```
