### ISSUE TITLE
Run multiple different builds per commit

### ISSUE THREAD

**Issue by filipegiusti** [Shippable/support#2608]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

I would like Shippable to run two different builds for the same pull request/commit, the reasoning for this is because I wanna check that my tests pass and also I wanna run a code style check. Those use different commands to run and pre/post build commands, also those build should report their statuses separately to the pull request as I would like to know which failed.

**Comment by avinci** [comment]
You can do this with a Matrix setup using Custom Variable
http://docs.shippable.com/ci_configure/#custom-variables

* Setup 2 ENV vars, 1 for Tests and 1 for Code Style. This will automatically fire 2 builds now. 
* Write a simple shell script, for this eg lets call it `ci.sh`. In this script check for ENV vars and fire different commands 
* in the YML file exec `ci.sh`

this should do what you exactly need it to do. let me know if you need more help

**Comment by avinci** [comment]
@abhijitkini please add this to How To Series that we are doing..

**Comment by abhijitkini** [comment]
@filipegiusti Stay tuned for a How-To series on doing this. In the mean time, if you need help, please let us know. 
Closing the issue.

**Comment by filipegiusti** [comment]
This would partially work, the PR wouldn't have statuses reported separately. Also would I be able to have different pre/post build commands?

For now I decided to have a different service so I can have separated reports on the PR and separated notifications.

Besides what's possible now, this feature still has value to me.

**Comment by abhijitkini** [comment]
_This would partially work, the PR wouldn't have statuses reported separately._ 
- Though there are 2 jobs kicked off for a run, each job has a separate status in a matrix build. For example, if 1 job succeeds & another fails, you will be able to see the status of for each of them and the overall job status will show failed.

_Also would I be able to have different pre/post build commands?_
- Yes, you can have different pre/post build commands. You can write scripts to execute actions in the pre-ci & post-ci sections. Here is a sample shippable.yml configuration:

```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12

env:
  - TESTS=1
  - CODESTYLE=1

build:
  pre_ci:
    - ./pre_ci.sh
  ci:
   - node --version
  post_ci:
    - ./post_ci.sh

# In pre_ci.sh and post_ci.sh you can run whatever commands you need by checking for the env variables    
#    - if [ "$TESTS" == 1 ]; then <do something>; fi
#    - if [ "$CODESTYLE" == 1 ]; then <do something>; fi
```

Do let us know if you have further questions.
