### ISSUE TITLE
/root/.rvm/scripts/rvm: No such file or directory

### ISSUE THREAD

**Issue by sushantbajra** [Shippable/support#2609]
```
# language setting
language: ruby
rvm: 2.3.0

addons:
  firefox: "44.0"

services:
  - selenium

env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - ms-dev@bajratechnologies.com
      on_failure: true
      on_success: true

build:
  ci:
    - source ~/.rvm/scripts/rvm
    - rvm install $SHIPPABLE_RUBY --verify-downloads 1
    - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY
    - bundle install --gemfile="Gemfile"
    - /etc/init.d/xvfb start
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - bundle exec cucumber

  on_success:
    - /etc/init.d/xvfb stop

cache: true

```

Somehow my builds are failing because I am getting this err

`/root/b75fc1ae-ccaa-442f-9745-a94ad2b3799b.sh: line 58: /root/.rvm/scripts/rvm: No such file or directory`

I had no problems before but now I am having that issue. How can i fix it?
