### ISSUE TITLE
Bitbucket tag builds support

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2615]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

The recently announced environment variables `IS_GIT_TAG` and `GIT_TAG_NAME` are apparently not set on [tagged builds](https://app.shippable.com/runs/5735909986e5040c0061d4b9).

Here's my minimal `shippable.yml`:

``` yaml
language: php

php:
  - 5.6

build:
  ci:
    - echo "Built"
    - env

  on_success:
    - >
      if [ "$IS_GIT_TAG" = "true" ]; then
        echo "Release as ${GIT_TAG_NAME}."
      fi;
```

On the `env` step I can see that `IS_GIT_TAG` is always `false` and `GIT_TAG_NAME` is always empty.
