### ISSUE TITLE
pg gem is not installing

### ISSUE THREAD

**Issue by sushantbajra** [Shippable/support#2616]
When running the `bundle install` the pg gem installation seems to be failing.

```
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.3.0/gems/pg-0.18.4/ext
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160513-11588-ujfd5b.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out
```

Here is my `shippable.yml` file

```
# language setting
language: ruby
rvm: 2.3.0

addons:
  firefox: "44.0"

services:
  - selenium

env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - ms-dev@bajratechnologies.com
      on_failure: true
      on_success: true

build:
  ci:
    - bundle install --gemfile="Gemfile"
    - /etc/init.d/xvfb start
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - bundle exec cucumber
  on_success:
    - /etc/init.d/xvfb stop

cache: true

```

In my shippable.yml file I have also tried adding

```
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install libpq-dev
gem install pg
```

inside build > ci but I am still getting the same err. Anyway to solve this?
