### ISSUE TITLE
/etc/init.d/xvfb: No such file or directory

### ISSUE THREAD

**Issue by sushantbajra** [Shippable/support#2617]
why am i getting this error ?

`/root/b663d0d8-48f2-47b9-a08c-9eeaac0ef2d1.sh: line 58: /etc/init.d/xvfb: No such file or directory`

Here is  my yml file

```
# language setting
language: ruby
rvm: 2.3.0

addons:
  firefox: "44.0"

services:
  - selenium

env:
  global:
    - DISPLAY=:99.0
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - ms-dev@bajratechnologies.com
      on_failure: true
      on_success: true

build:
  ci:
    - sudo apt-get update --fix-missing
    - sudo apt-get -y install libpq-dev
    - bundle install --gemfile="Gemfile"
    - "export DISPLAY=:99.0"
    - "/etc/init.d/xvfb start"
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - bundle exec cucumber
  on_success:
    - /etc/init.d/xvfb stop

cache: true
```
