### ISSUE TITLE
How to just build a Docker image?

### ISSUE THREAD

**Issue by NiclasHedam** [Shippable/support#2624]
Hello,

I would like to just build a Docker image based on the Dockerfile. When I try, the build fails due to some ruby gem stuff.
`bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS`

My YML file:
```
build:
  post_ci:
    - docker commit web eu.gcr.io/........
    - docker push eu.gcr.io/........

integrations:
  hub:
    - integrationName: gcr
      type: gcr
      branches:
        only:
          - production
```

**Comment by manishas** [comment]
@NiclasHedam this is because when your ci  section is empty we run default commands for ruby language. 

To skip the default command you can include something in your ci section as shown below-

```
build:
  ci:
    - pwd 
  post_ci:
    - docker commit web eu.gcr.io/........
    - docker push eu.gcr.io/........

integrations:
  hub:
    - integrationName: gcr
      type: gcr
      branches:
        only:
          - production
```
