### ISSUE TITLE
Slack Integration not Recognized

### ISSUE THREAD

**Issue by clounie** [Shippable/support#2626]
### Description of your issue:
I created two integrations for my project: a GCR integration, and a Slack integration. 

The GCR integration is recognized just fine (and when I purposefully screw up the name in the yaml, it catches that and won't build)

However, the Slack integration - though it exists in my integrations and I put the name in the yaml - will not behave. It pretends like I didn't add Slack to my integrations at all.

- Link to the build failure: https://app.shippable.com/runs/573b55a812be900d00694e93

**Comment by manishas** [comment]
@clounie can you double check that you have enabled the Slack integration in your project settings as well?

**Comment by clounie** [comment]
Nevermind, I failed to add the integration to the project as WELL as my account.

**Comment by clounie** [comment]
Yep, that was it, thanks @manishas.

**Comment by manishas** [comment]
glad it worked :)

closing this issue.

**Comment by BrilliantBasicsSync** [comment]
Having this issue also, but it's on our project **and** account

https://app.shippable.com/runs/5742cfe5dd010b0c008f1964

**Comment by a-murphy** [comment]
Could you check that the Slack notification integration has type "slack" in your shippable.yml file?

**Comment by BrilliantBasicsSync** [comment]
Indeed, that was the issue thanks a-murphy. Dare suppose you could provide a link to the docs where this is mentioned? Can't find it anywhere. The only docs I can find relate to the old-style before the revamp of Shippable.

Cheers

**Comment by BrilliantBasicsSync** [comment]
Also, it wasn't documented that 'recipients' was required, even though the channel is set in the integration configuration page?

For anyone else having this issue this is my config, that works, except the payload (raising new issue for that).

```
notifications:
    - integrationName: "SlackIntegration"
      type: slack
      recipients:
        - "#channel_name"
      payload:
        - isPRBuild=$IS_PULL_REQUEST
        - branchName=$BRANCH
        - message=API Built $BUILD_NUMBER ($BUILD_URL) succeeded for $COMPARE_URL
      on_success: always
      on_failure: always
      on_pull_request: never
      on_start: never
```
