### ISSUE TITLE
aws_eb_deploy not replacing "<IMAGE_NAME>:<TAG>" values in Dockerrun.aws.json

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2632]
### aws_eb_deploy not replacing "<IMAGE_NAME>:<TAG>" values in Dockerrun.aws.json

Please see this successful build:
https://app.shippable.com/runs/573dca2712ebb90c00a9e031

It pushed the code to AWS, but really I wanted to push the Docker Image. I don't really want AWS to ru-run the Dockerful, as that build has already happened on Shippable.

The docs here:
http://docs.shippable.com/ci_configure/

Say:

```
Docker deployment to AWS Elastic Beanstalk
Shippable performs the following steps for you to deploy Docker on EB, after all the steps in shippable.yml that run inside the container are complete:

* Logs into EB
* Updates your Dockerrun.aws.json file with the IMAGE_NAME & TAG
* Uploads the artifacts to S3
* Updates the application version
* Issues the command to update the EB environment

Upon completion of the above, EB updates your environment based on the uploaded application version, independent of Shippable.
```

**BUT** - the zip file published to S3, has just the original Dockerrun.aws.json file, and AWS deployed using the Dockerfile.

**Comment by bobbydeveaux** [comment]
My shippable.yml

```
# specifying build image
build_image: drydock/u14php7all:tip

# language setting
language: php

# specifying runtime
php:
   '7.0'

build:

  ci:
    - echo "No tests yet. Build successful."

  post_ci:
    - docker build  --rm=true -t bobbydvo/quint-api-release:$BRANCH.$BUILD_NUMBER .
    - docker build  --rm=true -t bobbydvo/quint-api-release:latest .
    - docker push xxxxxxx/xxxxxxxxxx:$BRANCH.$BUILD_NUMBER
    - docker push xxxxxxx/xxxxxxxxxx:latest

integrations:
  hub:
    - integrationName: "integrationName"
      type: docker
      branches:
      only:
        - master
  deploy:
    - integrationName: "integrationName"
      type: aws
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxxxxxxxxxxx
      env_name: xxxxxxxxxx
      bucket_name: xxxxxxxxxxxxxxxx/xxxxxxx
      region: eu-central-1
      image_name: "xxxxxx/xxxxxx"
      image_tag: "$BRANCH.$BUILD_NUMBER"

```
