### ISSUE TITLE
Shippable build fails due to Don't run Bundler as root error

### ISSUE THREAD

**Issue by vivekbhupatiraju** [Shippable/support#2633]
This is my repo with shippable.yml file below:
https://github.com/vivekbhupatiraju/docker-compose-example/blob/master/shippable.yml

My code follows this example here:
https://docs.docker.com/compose/gettingstarted/

My shippable run:
https://app.shippable.com/runs/573e3c48c795b70c00b7e2ab

I'm trying to do a build in shippable and it fails in the build_ci section with the below error:

**bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
/root/src/github.com/vivekbhupatiraju/docker-compose-example/Gemfile not found**

**Comment by stephanielingwood** [comment]
Hi @vivekbhupatiraju ,

Thanks for your question. Here's why you're getting this error:
- Your shippable.yml doesn't specify a language
- When no language is specified, our build system uses Ruby as the default
- When it's a Ruby build, we look for a gemfile. It's not there, which creates the "gemfile not found" error.

You can fix this by adding a language to your yml. It looks like your project is using Python, so your yml will look something like this:

```
# language setting
language: python

# version numbers
python:
  - "2.7"

build:
    pre_ci:
      - docker build -t web .

    post_ci:
      - pip install -U docker-compose
      - docker-compose up -d
      - docker ps
``` 

More documentation on Python language settings is here: http://docs.shippable.com/ci_languages/#python

Hope this helps! Let us know if you have any other questions.
