### ISSUE TITLE
Deploy Integration Multiple Branches

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2636]
### How can I specify multiple environments like in .elasticbeanstalk/config.yml ?

config.yml allows specifying different environments for different branches. How can we do this with deploy integrations? I need to change the 'env_name' parameter depending on the branch.

Also the hub integration for Docker doesn't seem to adhere to the 'master' branch restriction. 

```
integrations:
  hub:
    - integrationName: "xxxxxx"
      type: docker
      branches:
      only:
        - master
  deploy:
    - integrationName: "xxxxxxxx"
      type: aws
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: appName
      env_name: envName
      bucket_name: bucketName
      region: eu-central-1
      image_name: "image/name"
      image_tag: "$BRANCH.$BUILD_NUMBER"
```

**Comment by trriplejay** [comment]
Hello,

regarding your hub integration: your indentation appears to be off.  the `only` section should be indented from the `branches` section like this:
```
 hub:
    - integrationName: "xxxxxx"
      type: docker
      branches:
        only:
          - master
```

There are a couple different ways to accomplish the branch logic you suggest.  First of all, if your logic is branch dependent, then you could simply modify the Shippable.yml for that particular branch, making env_name whatever it needs to be for that branch.

On the other hand, if you wanted to keep your Shippable.yml uniform across branches, you can instead use an environment variable to set an env_name value based on whatever logic you want.

for example:
```
build:
  ci:
    - if [[ "$BRANCH" == "master" ]]; then MYENV="master_env"; fi
    - if [[ "$BRANCH" == "develop" ]]; then MYENV="develop_env"; fi
```

something like that.  Then in your integration, you'd say:
```
deploy:
    - integrationName: "xxxxxxxx"
      type: aws
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: appName
      env_name: "$MYENV"
      bucket_name: bucketName
      region: eu-central-1
      image_name: "image/name"
      image_tag: "$BRANCH.$BUILD_NUMBER"
```
