### ISSUE TITLE
Trigger builds - at a directory level commit / change

### ISSUE THREAD

**Issue by gsvijayraajaa** [Shippable/support#2640]
Hi,

I am aware of the build trigger process in shippable, its one build for each commit/pull request to the git repository. My specific use case is that, we have the repository hosting the project, catering to multiple microservices. Each microservices is a separate build of its own. When we have individual repositories per microservices, the number of repo becomes huge, henceforth I would like to know if we can trigger builds when there is a commit or change to a specific folder within the project structure. The project will be organized such that the microservices is placed at individual directories within the parent project structure. Can the webhook be altered to cater the same? Any other way to achieve the same without creating multiple branches?

Regards,
Vijay Raajaa GS

**Comment by avinci** [comment]
@gsvijayraajaa you can do this, but not exactly the way you are expecting. There is no way to know what folder changed at a web hook level. We do this internally at Shippable by using a script that will allow us to do what you are trying to achieve. But a build will fire no matter what and its up to you do what you want with it. 

to achieve this, first we create a script file called `builds.sh` which a docker image based on the new code and then pushes it to the hub.

```
#!/bin/bash -e
export IMAGE_NAME=shipimg/micro41
if [ "$IS_PULL_REQUEST" != true ]; then
  sudo docker build -t $IMAGE_NAME:$BRANCH.$SHIPPABLE_BUILD_NUMBER .
  sudo docker push $IMAGE_NAME:$BRANCH.$SHIPPABLE_BUILD_NUMBER
else
  echo "skipping because it's a PR"
fi
```

Now we need to tag it based on the folder that got changed so that different tests can be fired. We create `tag_image.sh`. We also have a global folder which consists of all the common code across all micro services. Hence if global changes, we want to push every single micro service even if nothing changes (you might not needs this, but its a pattern thats worth having) . 

```
#!/bin/bash -e
export IMAGE_NAME=shipimg/micro41
detect_changed_languages() {
  echo "detecting changes for this build"
  languages=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`

  for language in $languages
  do
    detect_changed_folders $language
  done
}

detect_changed_folders() {
  folders=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | grep $1 | awk 'BEGIN {FS="/"} {print $2}' | uniq`

  push_all_images=false
  for folder in $folders
  do
    if [ "$folder" == '_global' ]; then
      echo "pushing all images"
      push_all_images=true
      break
    fi
  done

  if [ "$push_all_images" == true ]; then
    cd $1
    export changed_components=`ls -d */ | sed 's/.$//'`
    cd ..
  else
    export changed_components=$folders
  fi
}

tag_and_push_changed_components() {
  for component in $changed_components
  do
    if [ "$component" != '_global' ] && [ "$component" != 'node_modules' ]; then
      tag_and_push_image $component
    fi
  done
}

tag_and_push_image() {
  if [[ -z "$1" ]]; then
    return 0
  else
    echo "tagging image $1"
    sudo docker tag -f $IMAGE_NAME:$BRANCH.$SHIPPABLE_BUILD_NUMBER $IMAGE_NAME:$1.$BRANCH.$SHIPPABLE_BUILD_NUMBER
    echo "pushing image $1"
    sudo docker push $IMAGE_NAME:$1.$BRANCH.$SHIPPABLE_BUILD_NUMBER
  fi
}

if [ "$IS_PULL_REQUEST" != true ]; then
  detect_changed_languages
  tag_and_push_changed_components
else
  echo "skipping because it's a PR"
fi
```

Now we just call these scripts in our YML. In the above script wherever we are doing tag and push, you could run different `ci scripts` based on what changed in your folder structure.

our shippable YML looks like this. 
```
  ci:
    - ./build.sh
    - ./tag_image.sh
```
 
Let me know if this helps, else I can write a blog..

**Comment by kanthchandra** [comment]
Another thing to note before using the above script is our folder structure.

- At the root of the repository we have  node, python, go which are basically languages and each of the languages has different micro services associated with them and an _global folder. 
- So in order to detect the micro services that changed we first figure out which languages changed (detect_changed_languages())
- then for each language we figure out if _global folder changed (detect_changed_folders()). If _global changed we push all the images else we push only that particular micro service that changed.

**Comment by abhijitkini** [comment]
Closing issue as resolved. If you have additional questions on this issue, let us know.

**Comment by gsvijayraajaa** [comment]
Thanks for the direction, I shall checkout the solution and get back. Thanks.

Cheers!!

**Comment by christophervalles** [comment]
Hi guys,

I've been trying to setup something similar to this. I have a bash script that detects the folders that have changed and runs the tests and pushes the images. 

```
#!/usr/bin/env bash

test_microservice() {
  if [ -d $1 ]; then
    curdir=`pwd`
    pushd $curdir/"$1"/

    echo -e "\n## Testing $1"
    echo "### Installing specific dependencies"
    godep go install

    echo "### Linting code"
    golint ./...

    echo "### Analysing code"
    go tool vet -v .

    echo "### Running the tests"
    go test -v ./... >> $curdir/shippable/testresults/results.txt

    if [ $? -ne 0 ]
    then
        popd
        go-junit-report < $curdir/shippable/testresults/results.txt > $curdir/shippable/testresults/results.xml
        echo "### Test suite failed"
        return 1
    else
        popd
        go-junit-report < $curdir/shippable/testresults/results.txt > $curdir/shippable/testresults/results.xml
        echo "### All test OK"
        return 0
    fi
  fi
}

build_microservice() {
    if [ -d $1 ]; then
        echo "## Building $1"

        curdir=`pwd`
        pushd $curdir/"$1"/
        name=`echo "${1,,}"`
        image=REDACTED.dkr.ecr.eu-west-1.amazonaws.com/$name:$BRANCH.$COMMIT

        echo "### Compiling the static binary with no dependencies"
        CGO_ENABLED=0 go build -a -ldflags '-s' -installsuffix cgo -o main .

        if [ $? -ne 0 ]
        then
            echo "### Error compiling the binary"

            popd
            return 1
        else
            echo "### Building the docker image"
            docker build -t $image .

            echo "### Pushing the docker image"
            docker push $image

            echo "### Docker image built"

            export ${1^^}_TRIGGER=always

            popd
            return 0
        fi
    fi
}

microservices=()

changes=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`

for change in $changes; do
    if [ -d "$change" ]; then
        microservices+=($change)
    fi
done

if [ ${#microservices[@]} -ne 0 ]; then
    echo "# Changes detected for ${microservices[@]}"

    echo "## Installing common dependencies"

    echo "### Installing godep tool"
    for i in {1..3}; do go get -u github.com/tools/godep && break || echo "Installation failed, retrying in 5s" && sleep 5; done

    echo "### Installing junit report tool"
    for i in {1..3}; do go get -u github.com/jstemmer/go-junit-report && break || echo "Installation failed, retrying in 5s" && sleep 5; done

    echo "### Installing golint"
    for i in {1..3}; do go get -u github.com/golang/lint/golint && break || echo "Installation failed, retrying in 5s" && sleep 5; done

    echo "### Installing gocov"
    for i in {1..3}; do go get -u github.com/axw/gocov/gocov && break || echo "Installation failed, retrying in 5s" && sleep 5; done

    echo "### Installing gocov-xml"
    for i in {1..3}; do go get -u github.com/AlekSi/gocov-xml && break || echo "Installation failed, retrying in 5s" && sleep 5; done


    for microservice in "${microservices[@]}"; do
        test_microservice $microservice

        if [ $? == 0 ]; then
            build_microservice $microservice
        fi
    done

    echo "## Computing code coverage for ${microservices[@]}"
    paths=()
    for p in "${microservices[@]}"; do paths+="./$p "; done
    gocov test ${paths[@]} | gocov-xml > $curdir/shippable/codecoverage/coverage.xml
    exit 0
else
    echo "# No μservices have changed"
    exit 1
fi
```

My problem comes when I want to hook this up to the CD pipeline and deploy it to ECS or whatever. I thought I could do it using global env vars and use them on the on_change like this so I will have a separate pipeline per microservice.

```
language: none

env:
  global:
    - APP1_TRIGGER=never
    - APP2_TRIGGER=never
    - APP3_TRIGGER=never

build:
  ci:
    - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
    - sudo apt-get update
    - sudo apt-get -q -y install golang
    - export GOPATH=/root
    - ./test.sh

integrations:
  hub:
    - integrationName: aws-ecr
      type: ecr
      region: eu-west-1

  notifications:
    - integrationName: app1-trigger
      type: webhook
      payload:
        - versionName=$BRANCH.$COMMIT
        - sourceName=REDACTED.dkr.ecr.eu-west-1.amazonaws.com/app1
      on_success: $APP1_TRIGGER

    - integrationName: app2-trigger
      type: webhook
      payload:
        - versionName=$BRANCH.$COMMIT
        - sourceName=REDACTED.dkr.ecr.eu-west-1.amazonaws.com/app2
      on_success: $APP2_TRIGGER

    - integrationName: app3-trigger
      type: webhook
      payload:
        - versionName=$BRANCH.$COMMIT
        - sourceName=REDACTED.dkr.ecr.eu-west-1.amazonaws.com/app3
      on_success: $APP3_TRIGGER

```

But it's not working.

Any ideas on how to do this? 
I'm I using the wrong approach?
How do you connect your script to the CD?

Cheers
