### ISSUE TITLE
Slack improvements: payload support, desktop notifications

### ISSUE THREAD

**Issue by BrilliantBasicsSync** [Shippable/support#2650]
### Slack Payload Parameter being ignored

Please forgive me if this is explained in some documentation that I cannot find, but the payload parameter of the slack integration is not working (i.e. it's as though I've not passed the payload at all).

```
notifications:
    - integrationName: "SlackIntegration"
      type: slack
      recipients:
        - "#channel_name"
      payload:
        - isPRBuild=$IS_PULL_REQUEST
        - branchName=$BRANCH
        - message=API Built $BUILD_NUMBER ($BUILD_URL) succeeded for $COMPARE_URL
      on_success: always
      on_failure: always
      on_pull_request: never
      on_start: never
```

The values being passed into Payload are actually values from another example that I came across, so was checking that it worked. 

Do you have any suggestions how to get the payload through? Or a link to the documentation surrounding this? The only docs I can find relate to the old-style integration.

Many thanks! :)
