### ISSUE TITLE
Slack Integration Filters

### ISSUE THREAD

**Issue by RobertLippens** [Shippable/support#2654]
This is a feature request - not an actual issue we are having with Shippable.
Yesterday I tried implementing Slack Integration for our Shippable builds and noticed that there were no options for selecting exactly what sends a notification.  It would be great to only send notifications on failed builds, for example (otherwise our Slack channels are going to get really spammy with build notifications).

Oh - and we're really enjoying the fast build times!

**Comment by a-murphy** [comment]
Have you tried the `on_success` and `on_failure` settings for the Slack integration in your shippable.yml?  You should be able to set `on_success: never` to only get notifications for failures.  The documentation is available [here](http://docs.shippable.com/ci_configure/#slack-notifications).

**Comment by manishas** [comment]
@RobertLippens glad you're enjoying the fast build times :)

Regarding choosing what events send a notifications, we do have that configuration in place. Your yml section for slack notification looks like this:

```
integrations:
  notifications:
    - integrationName: my_slack_integration
      type: slack
      recipients:
        - "#channelOne"
        - "#channelTwo"
      on_success: never
      on_failure: always
```

In the above config, if you set `on_failure` to always and `on_success` to false, you'll only get notified on failures.
