### ISSUE TITLE
Email integration to --lastcommitter is not working

### ISSUE THREAD

**Issue by cabeB** [Shippable/support#2655]
After I have added the integration with email I have stopped receiving build status mails.

This is my configuration:

```
language: java

jdk:
  - oraclejdk8

build:
    ci:
        - mvn test

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - --lastcommitter
      on_success: always
      on_failure: always
```
