### ISSUE TITLE
Docker-Compose Project Volume Mounts

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2656]
I am having an issue with getting the project repos code mounted from the shippable host to my docker volume container. I am using docker-compose so here are some of the configuration and log files. 

### docker-compose.yml 
```
  code:
    image: alpine:latest
    volumes:
      - .:/hotel-platform
  php: 
    image: php:latest
    volumes_from: 
      - code
```

During the build I check to ensure the volume got mounted. 
```
docker exec -i hotelplatform_php_1 sh -c 'ls -al /hotel-platform'
```

which returns an empty directory
```
total 8
drwxr-xr-x  2 root root 4096 May 27 16:59 .
drwxr-xr-x 51 root root 4096 May 27 17:16 ..
```

Also, I've inspected the container and it looks identical to my local configuration. The only differencing being projects directory path. This looks right but still can't reach any data
```
...
"Mounts": [
        {
            "Source": "/root/src/<the git repo>/hotel-platform",
            "Destination": "/hotel-platform",
            "Mode": "rw",
            "RW": true
        }
    ],
...
"Volumes": {
     "/hotel-platform": {}
},
```

Note, I left out specifics so you can see the build here: https://app.shippable.com/runs/574880eca339030d00ad88b1
Checkout the build_ci > ci-run.sh section.
