### ISSUE TITLE
eb deploy nohang parameter

### ISSUE THREAD

**Issue by BrilliantBasicsSync** [Shippable/support#2665]
### Support nohang parameter in eb deploy

the aws_eb_deploy task takes a while sometimes, and it's often because it's waiting for the "eb deploy" command to finish. Even if this fails, Shippable marks the build as success anyway.

Given the above fact, it makes sense to support the "nohang" parameter:

```
-nh, --nohang         return immediately, do not wait for deploy to be
                        completed
```

e.g.

```
deploy:
    - integrationName: "AwsIntegration"
      type: aws
      nohang: true <-----------------------------
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxxxx-api
      env_name: "$MYENV"
      bucket_name: xxxxxxxx-eu-central-1-34345435345/asdasdasdasdasd-api
      region: eu-central-1
      image_name: "asdfasdf/asdf-asdf-asdf"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
```
