### ISSUE TITLE
Unable to view files within a mounted volume

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2666]
While building a Docker container, trying to mount a volume inside the Docker container. Have a folder called 'test' within the SHIPPABLE_BUILD_DIR, as part of the pre-ci stage.

Unable to view files/directories within this test folder using the command `ls -lart`.

**Comment by deanmraz** [comment]
@abhijitkini not sure this helps but I had to mount $SHIPPABLE_BUILD_DIR to the host and boot container so docker-compose containers could have access. 

shippable.yml
```
pre_ci_boot:
    image_name: drydock/u14pyt
    image_tag: prod
    pull: true
    options: "-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"
```

docker-compose.yml
```
  data:
    volumes:
      - .:/hotel-platform
```

See here: https://github.com/Shippable/support/issues/2656
