### ISSUE TITLE
end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by Banbury** [Shippable/support#267]
I'm using the following shippable.yml. I copied it almost verbatim from your docu.

```
language: java

 jdk:
    - openjdk7
    - oraclejdk7

after_success:
   - mvn clean cobertura:cobertura
   - mvn test

notifications:
   email:
       recipients:
          - mymail@gmail.com

```

The webhook get's this message:
    JS-YAML: end of the stream or a document separator is expected at line 7, column 1:\n    after_success:\n    ^

But I can't see any problem on line 7.
