### ISSUE TITLE
Private Git Repo - Git Sync Failing

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2670]
### Private Git Repo - Git Sync Failing

Having an issue with Git Sync failing, despite integrating and checking all these issues:
https://github.com/Shippable/support/search?q=git+sync&type=Issues

I've added SSH Key Integration in account settings, used 'Generated Keys'. I've taken the public key, and added it as the deploy key in GitHub for the repo. That didn't work, I've also generated my own private/public key pair and still no luck. Each time I re-pressed the 'Sync' button in account settings.

Further to this, my shippable.yml file has:

```
integrations:
  key:
    - integrationName: SSHKeyIntName
      type: ssh-key
```

Example failing build:
https://app.shippable.com/runs/574f5092fa40840c002d76aa

Any ideas?
