### ISSUE TITLE
Multiple Deploy Hooks

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2687]
### Multiple Deploy Hooks

I'd like to raise this as a bug (you guys fix bugs really quickly!), however I'm afraid it may be a feature request!

We have a use-case, where I'm trying to deploy to 2 Elastic Beanstalk environments, but this could easily be because the app needs to be deployed to AWS & DigitalOcean for Redundancy

I've tried:

``` yml
  deploy:
    - integrationName: "integrationName"
      type: aws
      target: targetname2
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxx-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-eu-central-1-1234213421341234/asdfasdfasdf-api
      region: eu-central-1
      image_name: "asdfasdf/asdfasdf-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
deploy:
    - integrationName: "integrationName2"
      type: aws
      target: targetname
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxx2-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-eu-central-1-1234213421341234/asdfasdfasdf-api
      region: eu-central-1
      image_name: "asdfasdf/asdfasdf-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
```

I've also tried:

``` yml
 deploy:
    - integrationName: "integrationName"
      type: aws
      target: targetname2
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxx-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-eu-central-1-1234213421341234/asdfasdfasdf-api
      region: eu-central-1
      image_name: "asdfasdf/asdfasdf-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
    - integrationName: "integrationName2"
      type: aws
      target: targetname
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: xxxxxx2-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-eu-central-1-1234213421341234/asdfasdfasdf-api
      region: eu-central-1
      image_name: "asdfasdf/asdfasdf-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
```

In both cases, only the 2nd deployment happens (better than an error!). However, I'd of course prefer both deployments to be successful.

In my use case, I'm looking at having to type the 'eb deploy' commands myself, unless you guys tell me this functionality can exist pretty easily.

Thanks guys!

**Comment by manishas** [comment]
@bobbydeveaux what you're asking for isn't currently supported with our platform. If you specify 2 integrations of the same type, the second one is chosen and the first one will be ignored. That said, we're making some enhancements over the next 3-4 weeks that will address this scenario. I will keep this open as a feature request and let you know when that's available.

Thanks!

**Comment by bobbydeveaux** [comment]
FWIW @manishas  - I've worked around this here:

https://app.shippable.com/runs/5764382e77a4b10c00d967cd

part of shippable

```yml
post_ci:

    - if [[ "$BRANCH" == "master" ]] || [[ "$BRANCH" == "develop" ]]; then docker build  --rm=true -t xxxxxxx/yyyyyyyy-release:$BRANCH.$BUILD_NUMBER . ; fi
    - if [[ "$BRANCH" == "master" ]] || [[ "$BRANCH" == "develop" ]]; then docker build  --rm=true -t xxxxxxx/yyyyyyyy-release:latest . ; fi
    - if [[ "$BRANCH" == "master" ]] || [[ "$BRANCH" == "develop" ]]; then docker push xxxxxxx/yyyyyyyy-release:$BRANCH.$BUILD_NUMBER ; fi
    - if [[ "$BRANCH" == "master" ]] || [[ "$BRANCH" == "develop" ]]; then docker push xxxxxxx/yyyyyyyy-release:latest ; fi
    - cat Dockerrun.aws.json

    #
    # Shippable doesn't support multiple deploy hooks (3-4 weeks away)
    # https://github.com/Shippable/support/issues/2687
    #
    # Below is a manual workaround until it's resolved.
    # Modify Dockerrun.aws.json!

    - sed -i -e 's/<IMAGE_NAME>/xxxxxxxx\/yyyyyyyy-release/g' Dockerrun.aws.json
    - sed -i -e "s/<TAG>/$BRANCH.$BUILD_NUMBER/g" Dockerrun.aws.json

    - cat Dockerrun.aws.json

    - pip install awsebcli
    - echo '[profile eb-cli]' > ~/.aws/config
    - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key = $AWSSecretAccessKey" >> ~/.aws/config
    - cat ~/.aws/config
    - mkdir -p .elasticbeanstalk

    # QL Deployment
    - cp ebconfig-client-a.yml .elasticbeanstalk/config.yml
    - cat .elasticbeanstalk/config.yml
    - eb init
    - eb use $CLIENT1ENV
    - eb status
    - eb deploy

    # MC Deployment
    - cp ebconfig-client-b.yml .elasticbeanstalk/config.yml
    - cat .elasticbeanstalk/config.yml
    - eb init
    - eb use $CLIENT2ENV
    - eb status
    - eb deploy
```

annoying that eb init doesn't respect the branch, as git is detached from the head so it doesn't know what branch it's on hence the above workaround!

Anyway, hope this helps someone until this feature is added natively.

**Comment by sheldon-sminq** [comment]
I am looking for a similar scenario to differentiate between a staging and release/prod build.

for a regular github commit the build should happen to staging, but when a github TAG or RELEASE webhook is triggered would like the build to be pushed to production Elastic beanstalk env.

```
deploy:
    - integrationName: "integrationName"
      type: aws
      target: targetname2
      platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1"
      application_name: staging-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-ap-southeast-1-288789354248
      region: ap-southeast-1
      image_name: "asdfasdf/staging-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        except:
          - master

    - integrationName: "integrationName2"
      type: aws
      target: targetname
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: prod-api
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-ap-southeast-1-288789354248
      region: ap-southeast-1
      image_name: "asdfasdf/asdfasdf-api-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
```
