### ISSUE TITLE
Better Hub/Deploy Integrations for Custom Images

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2695]
I find using the Hub Integrations and Deploy integrations are so easy to use, when using one of the drydock images. 

However, when building against a custom image, most the integrations are null and void. I.e. I have to use Secure Env vars to login to Docker & for my AWS credentials, and I have to copy the .elasticbeanstalk config.yml file so that I can eb init - it's all very 'hacky'

See below for a working Shippable integration for Building Custom Docker and Deploying to Elastic Beanstalk:

```
# language setting
language: php

# specifying runtime
php:
   '7.0'

env:
  global:
    - secure: KWzBVQZwAOm5Iu0tyMrHT5Oghqa/pAn6LbOrNeGqrPbICzZqHgHhhKIg/cEjT2ikXlTDsMcLZU/anWvFeSdZTMv1uJX73pd7Ddd25v04j90ISIb0gO08bV5aa5s+PUPPQSIeRaWc0pJHyFRtBBksW/YKmGBL4T6N84Eg6Kfmkia8/TGJcbcqXBH8d9ycSMPZN1Y5Ze6Ott8qp0wwQE3RbBHTbNHJOag8wXQJOzgVTrPGA4h+/FlE0Ibf+0E010AuRbSPr0CtlBE035cNEu5+zJ+kMxrlrHSbCRHR64J16SO0lo45NJBlDVK3RT+CZPMJS6xc5qzz3B/BSrHKrpw3UA==
    - secure: C+379fb+JF5kAElT+RSZhPK6SukpcNraSIaiYi0YKGljqS8cJ5bYJ+R4rNYXR7kEyqZpjs3mSnNd2OpvO5zITQAggtNIA67n6fEbqEopXTPL7r7KYUYm9LnZ2G6b+HTJmOvS6Ck6/sJrYe/vQHUFMlP+zxKBz6j5kTsJDi8MtlBju2vdinw8sxdQPC/46NNtLKQfFWnuXF7Y+FTmgtYd5zTpBgG5mhO5NC7TJzLkhXI84UM4X6hncTIsSwMedBZJ+N9PfhM5Qyu1aRcOXwFrXB34ymMKbe30fBiTQLvclbgPBw4ctZQTDAmGEFocvETNPU+pVPpW7dQioBvIDrCvEg==
    - secure: Yd1ws9Zhdk+eGlnTrDp/f/59VIuoRyl1wGyieI9uNUpuoaGsNmWYW89fFILXYQ9zPPLXVyMrBpZk2Gig1WtGZ1TTP+ZpgYehRFQUc1rhyTMiDAiUsR3q0UDv9XGssNhiyRcg3/4IQAEHN6uaedkQ8nizjZuzOa7qr6hTItbXMYDVX92+zWQ8udvrEyY588d0dzqs3hlbiNpiuI+Pu6+xZVQE0JK34S0DjzQemOrE155ftP+rQwpQnXiKRs0dOCT/GLTauMKnInTTYXTkHvxqfYMZBAMhZA/3dFK7XrjIJmXC848irrx/jhMHd3HhmhZyEnXbhintEvi++uKZnyzebQ==
    - secure: lEX6yWay3bZYooVQ0yJptZ3kvCZuhpLtBq1Bdk2kQKTDVjzhKKkgQ4aCaWPhAzDRQ1ELxmD7SbrAD7yL//qrZOMVni6SrcWey6OhKLkhi+uwLjE5wVJY3f4aXeysq+9Hxh2tuB0s5C/YlqVTb4kPMr2Gs+edSjPhZCBuQbhCfmVxkeWd6BMyfRi5bMxuJ1T6pMtxd5e4vdKemMllz+BbGTLnKykDF3Cx3BSmuSXMk62cUn2k3prGxJlwuiPD2yIGcq4uUxdYZ9DlFW7H/vY0Iaj7wa/w+X/WKKqV7w4T8p5oGEGMrdtU2f01kyKrF6PNslqqu/gjukqNfKQrYqgRAg==
    - secure: qylSUuvmUXVNXrXQ9nUq/cuW/gCOXALlFgF51QBRYzjinKWwsg9mBGUEN1pS/131RsN9Ro+EehWgCAwmakpDQnb+6frAt7K9H0ag/v0vrguXNFg9zr3LR5tBtg4oe2QeOxkhLUjODtFbr3MwV9ND3SLULoCCwvRq3xOntYEfnvG2uVktyK3XtbbVUMT6I09hPB+UzWNpSxHX73Uom4/kzqAYvmkWE5DrVH1NobPQPxGwapuhoEbQZxvF5oOsS1bHtsLZI7G73lHwSwd0hkNG7/t9YfnCLYHraL6dtKpzlWpTSAMeFModkWBVj9Ol0wbynF6Pbiq/NhE/x8OoUWSD1A==

build:
  # commands in this section run on your build machine and not inside your CI container.
  pre_ci:
    - docker build  --rm=true -t bobbydvo/webapp-release:tip .
    - docker build  --rm=true -t bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER .
    - docker images

  pre_ci_boot:
    image_name: bobbydvo/webapp-release
    image_tag: tip
    pull: false
    options: "-e HOME=/root"

  # commands in this section run inside your CI container. In addition, any commands such as ls, in this section can be used to skip default processing for CI.
  ci:
    # Here you'd place anything you want to test. For PHP apps, maybe Phpunit?
    - yum -y install python-pip
    - mkdir -p ~/.aws
    - echo '[profile eb-cli]' > ~/.aws/config
    - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key = $AWSSecretAccessKey" >> ~/.aws/config
    - cat ~/.aws/config
    - cd /srv
    - mkdir -p .elasticbeanstalk
    - cp beanstalk.yml .elasticbeanstalk/config.yml
    - pip install awsebcli
    - eb init && eb status
    - echo 'No tests.'

  # Everything all good? Let's push this to docker.
  post_ci:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e $DOCKER_EMAIL
    - docker push bobbydvo/webapp-release:tip
    - docker push bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER

integrations:
  ## Our Docker Hub Integration in Shippable
  hub:
    - integrationName: "DockerHub"
      type: docker
      agent_only: true
      branches:
        only:
          - master
  deploy:
    - integrationName: "BobbyAWS"
      type: aws
      target: adapt-webapp
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: "Test Application"
      env_name: testenv
      region: eu-west-1
      image_name: "bobbydvo/webapp-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
```

Is this a misunderstanding with using custom images? Or is this the only current way? Is there something that I can put on my custom build image (whatever is in the drydock images?) that would allow integrations to work just like the drydock images do?

Thanks again for your great support.

**Comment by manishas** [comment]
@bobbydeveaux I see you have the agent_only flag set to true in your hub integration. This is only necessary for situations where the customer wants to push to GCR or ECR and does not have the necessary CLI on their custom image. Since you are pushing to Docker Hub, you should remove `agent_only: true` from your yml so that we log in to your hub account from inside your build container. 

```

# language setting
language: php

# specifying runtime
php:
   '7.0'

env:
  global:
#remove any secure variables defined for docker login
    - secure: KWzBVQZwAOm5Iu0tyMrHT5Oghqa/pAn6LbOrNeGqrPbICzZqHgHhhKIg/cEjT2ikXlTDsMcLZU/anWvFeSdZTMv1uJX73pd7Ddd25v04j90ISIb0gO08bV5aa5s+PUPPQSIeRaWc0pJHyFRtBBksW/YKmGBL4T6N84Eg6Kfmkia8/TGJcbcqXBH8d9ycSMPZN1Y5Ze6Ott8qp0wwQE3RbBHTbNHJOag8wXQJOzgVTrPGA4h+/FlE0Ibf+0E010AuRbSPr0CtlBE035cNEu5+zJ+kMxrlrHSbCRHR64J16SO0lo45NJBlDVK3RT+CZPMJS6xc5qzz3B/BSrHKrpw3UA==
    - secure: C+379fb+JF5kAElT+RSZhPK6SukpcNraSIaiYi0YKGljqS8cJ5bYJ+R4rNYXR7kEyqZpjs3mSnNd2OpvO5zITQAggtNIA67n6fEbqEopXTPL7r7KYUYm9LnZ2G6b+HTJmOvS6Ck6/sJrYe/vQHUFMlP+zxKBz6j5kTsJDi8MtlBju2vdinw8sxdQPC/46NNtLKQfFWnuXF7Y+FTmgtYd5zTpBgG5mhO5NC7TJzLkhXI84UM4X6hncTIsSwMedBZJ+N9PfhM5Qyu1aRcOXwFrXB34ymMKbe30fBiTQLvclbgPBw4ctZQTDAmGEFocvETNPU+pVPpW7dQioBvIDrCvEg==
    - secure: Yd1ws9Zhdk+eGlnTrDp/f/59VIuoRyl1wGyieI9uNUpuoaGsNmWYW89fFILXYQ9zPPLXVyMrBpZk2Gig1WtGZ1TTP+ZpgYehRFQUc1rhyTMiDAiUsR3q0UDv9XGssNhiyRcg3/4IQAEHN6uaedkQ8nizjZuzOa7qr6hTItbXMYDVX92+zWQ8udvrEyY588d0dzqs3hlbiNpiuI+Pu6+xZVQE0JK34S0DjzQemOrE155ftP+rQwpQnXiKRs0dOCT/GLTauMKnInTTYXTkHvxqfYMZBAMhZA/3dFK7XrjIJmXC848irrx/jhMHd3HhmhZyEnXbhintEvi++uKZnyzebQ==
    - secure: lEX6yWay3bZYooVQ0yJptZ3kvCZuhpLtBq1Bdk2kQKTDVjzhKKkgQ4aCaWPhAzDRQ1ELxmD7SbrAD7yL//qrZOMVni6SrcWey6OhKLkhi+uwLjE5wVJY3f4aXeysq+9Hxh2tuB0s5C/YlqVTb4kPMr2Gs+edSjPhZCBuQbhCfmVxkeWd6BMyfRi5bMxuJ1T6pMtxd5e4vdKemMllz+BbGTLnKykDF3Cx3BSmuSXMk62cUn2k3prGxJlwuiPD2yIGcq4uUxdYZ9DlFW7H/vY0Iaj7wa/w+X/WKKqV7w4T8p5oGEGMrdtU2f01kyKrF6PNslqqu/gjukqNfKQrYqgRAg==
    - secure: qylSUuvmUXVNXrXQ9nUq/cuW/gCOXALlFgF51QBRYzjinKWwsg9mBGUEN1pS/131RsN9Ro+EehWgCAwmakpDQnb+6frAt7K9H0ag/v0vrguXNFg9zr3LR5tBtg4oe2QeOxkhLUjODtFbr3MwV9ND3SLULoCCwvRq3xOntYEfnvG2uVktyK3XtbbVUMT6I09hPB+UzWNpSxHX73Uom4/kzqAYvmkWE5DrVH1NobPQPxGwapuhoEbQZxvF5oOsS1bHtsLZI7G73lHwSwd0hkNG7/t9YfnCLYHraL6dtKpzlWpTSAMeFModkWBVj9Ol0wbynF6Pbiq/NhE/x8OoUWSD1A==

build:
  # commands in this section run on your build machine and not inside your CI container.
  pre_ci:
    - docker build  --rm=true -t bobbydvo/webapp-release:tip .
    - docker build  --rm=true -t bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER .
    - docker images

  pre_ci_boot:
    image_name: bobbydvo/webapp-release
    image_tag: tip
    pull: false
    options: "-e HOME=/root"

  # commands in this section run inside your CI container. In addition, any commands such as ls, in this section can be used to skip default processing for CI.
  ci:
    # Here you'd place anything you want to test. For PHP apps, maybe Phpunit?
    - yum -y install python-pip
    - mkdir -p ~/.aws
    - echo '[profile eb-cli]' > ~/.aws/config
    - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key = $AWSSecretAccessKey" >> ~/.aws/config
    - cat ~/.aws/config
    - cd /srv
    - mkdir -p .elasticbeanstalk
    - cp beanstalk.yml .elasticbeanstalk/config.yml
    - pip install awsebcli
    - eb init && eb status
    - echo 'No tests.'

  # Everything all good? Let's push this to docker.
  post_ci:
    #- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e $DOCKER_EMAIL
    - docker push bobbydvo/webapp-release:tip
    - docker push bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER

integrations:
  ## Our Docker Hub Integration in Shippable
  hub:
    - integrationName: "DockerHub"
      type: docker
      #agent_only: true
      branches:
        only:
          - master
  deploy:
    - integrationName: "BobbyAWS"
      type: aws
      target: adapt-webapp
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: "Test Application"
      env_name: testenv
      region: eu-west-1
      image_name: "bobbydvo/webapp-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master

```
