### ISSUE TITLE
Shippable eb deploy ERROR IOError [Errno 2] No such file or directory(zip file)

### ISSUE THREAD

**Issue by ramasamymohan** [Shippable/support#2698]
I'm trying to deploy docker application to elastic beanstalk. eb deploy says creating application archive, but its not able to locate the archive or may be archive not created. I'm not sure whether missing something. Any ideas?

Here is my shippable.yml,

```
language: node_js
node_js:
  - "6.1"
env:
  global:
    - SHIPPABLE_ARCHIVE=false
    #secure variable contains values for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: xxxxxx/xxxxxxxx
build:
    ci:
      - echo 'CI is running'
    post_ci:
      - docker build -t xxx/xxxxx:0.0.1 --rm ./
      - docker tag -f xxxx/xxxxx:0.0.1 xxxxxx/xxxxxxx:latest
      - docker push xxxxx/xxxxxx:latest
    on_success:
      - aws s3 sync $SHIPPABLE_BUILD_DIR "s3://xxxxxx" --region "us-west-2"

integrations:
  hub:
    - integrationName: "xxxxxxxxxxx"
      type: docker

  deploy:
    - integrationName: "xxxxxxx"
      type: aws
      target: eb_docker
      platform: "Docker"
      application_name: "xxxxxxxx"
      env_name: "xxxxxxxx"
      bucket_name: "xxxxxx"
      region: "us-west-2"
      image_name: "xxxxxxx"
      image_tag: "latest"
```

![screen shot 2016-06-11 at 11 31 33 am](https://cloud.githubusercontent.com/assets/7361904/15986354/d0c50aae-2fcb-11e6-9a0d-36c4200b029c.png)

Thank you!
