### ISSUE TITLE
Customization for different branches in the yml

### ISSUE THREAD

**Issue by steelorbis** [Shippable/support#2705]
Hi, 

I would like to use different tags while pushing docker images for master and feature branches. Also I would lke to customize my yml file according to the branch name. Would it be possible? 

Thanks.

**Comment by stephanielingwood** [comment]
Hi @steelorbis,

Thanks for your question. Within the build, you have access to the BRANCH environment variable, which gives you the current branch being built. This would let you use your branch names in your docker tags, as well as take different actions and/or trigger different scripts based on the branch.

You can read more about our standard environment variables here: http://docs.shippable.com/ci_configure/#standard-variables

Hope this helps! Let us know if you have any other questions.

**Comment by abhijitkini** [comment]
To add to the above, there are multiple ways you can achieve this. Here are a few:

1) If your logic is branch dependent, then modify the `shippable.yml` file to use use env_var for that branch.

2) To keep the `shippable.yml` consistent across all branches, you can use an environment variable to set an env_name value based on the logic you want. For example:
```
build:
  ci:
    - if [[ "$BRANCH" == "master" ]]; then MYENV="master_env"; fi
    - if [[ "$BRANCH" == "develop" ]]; then MYENV="develop_env"; fi
```
Then in your integration, you'd say:
```
deploy:
    - integrationName: "xxxxxxxx"
      type: aws
      target: xxxxxx
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: appName
      env_name: "$MYENV"
      bucket_name: bucketName
      region: eu-central-1
      image_name: "image/name"
      image_tag: "$BRANCH.$BUILD_NUMBER"
```
3) If you need to execute several commands based on the branch, then include the logic in a script and use it in the ci section. For example:
```
build:
  ci:
    if [ "$BRANCH" == "master" ]; then ./your-deployment-script.sh; fi
```
