### ISSUE TITLE
'eb_docker' use image pushed to ECR hub NOT image from shippable

### ISSUE THREAD

**Issue by designreact** [Shippable/support#2712]
Apologies if I am approaching things incorrectly. I am new to CI/CD setups but am keen to get my team to use shippable.

Here is my process so far.

- Create node container on shippable
- Run CI (tests etc)
- install other dependancies (SASS etc)
- Run build tasks (minify code move other important files to buildoutput)
- Build new docker image using contents of buildoutput
- Tag docker image and push to ECR

Then I'd like to deploy the image I pushed to ECR onto elastic beanstalk. It seems that the image that is uploaded is the image running my CI and build tasks. 

How do you specify which image to use when updating EB? Do I need to script this manually? if so how do I go about using the aws deploy integration with the aws cli. 

Many thanks for you help. I've added configs below which will hopefully help.

My latest run is here https://app.shippable.com/runs/5763dd5f090d7b0b00477954.

**Shippable YML**
```
post_ci
    - docker build -t buildname:$BRANCH.$BUILD_NUMBER .
    - docker tag buildname:$BRANCH.$BUILD_NUMBER userid.dkr.ecr.eu-west-1.amazonaws.com/buildname:$BRANCH.$BUILD_NUMBER
    - docker push userid.dkr.ecr.eu-west-1.amazonaws.com/buildname:$BRANCH.$BUILD_NUMBER

integrations:
  deploy:
    - integrationName: "integration-name"
      type: aws
      target: eb_docker
      application_name: "appname"
      env_name: "envname"
      bucket_name: "elasticbeanstalk-eu-west-1-userid"
      region: "eu-west-1"
      image_name: "userid.dkr.ecr.eu-west-1.amazonaws.com/buildname"
      image_tag: "$BRANCH.$BUILD_NUMBER"
  hub:
    - integrationName: "wbc amazon ecr"
      type: ecr
      region: "eu-west-1"
```

**Dockerfile**
```
FROM risingstack/alpine:3.4-v4.4.4-3.6.1

# Add compiled source files
COPY ./shippable/buildoutput ./

#Install node dependencies
RUN npm install --production

#Expose node app to world
EXPOSE 8000

#Start application
CMD ["npm","start"]
```
