### ISSUE TITLE
cache: true doesn't cache npm global modules

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2713]
installing global packages can take 1-3 minutes

*shippable.yml*
```
language: node_js

cache: true

env:
  CI=true
  COVERAGE=true

node_js:
  - "4.0"

before_install:
  - apt-get update --yes && apt-get install --yes phantomjs libfreetype6 libfontconfig
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version
  - npm config set spin false
  - npm install -g broccoli-clext
  - npm install -g bower
  - npm install -g ember-cli

install:
  - npm install
  - bower --allow-root install
```

**Comment by kanthchandra** [comment]
@BryanCrotaz can you point me to the build where caching dint work?

**Comment by kanthchandra** [comment]
Hi @BryanCrotaz , We have migrated to the new build platform after our latest release and the yml that you have posted is in the old format. So here is a guide which helps you to migrate to the new build platform http://blog.shippable.com/migrating-to-the-new-build-platform 

More documentation on caching can be found here http://docs.shippable.com/ci_configure/#caching .
I just gave a shot at creating a new yml based on the yml that you have provided. Please try this out and let us know if it doesn't work for you.
```
language: node_js

env:
  CI=true
  COVERAGE=true

node_js:
  - "4.0"

build:
  ci:
    - apt-get update --yes && apt-get install --yes phantomjs libfreetype6 libfontconfig
    - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
    - node --version
    - npm config set spin false
    - npm install -g broccoli-clext
    - npm install -g bower
    - npm install -g ember-cli
    - npm install
    - bower --allow-root install

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
```
