### ISSUE TITLE
Feature Request: Dynamic build matrix

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2714]
It would be useful if the build matrix could be dynamic, so that the number of jobs dispatched could be dependent on the files changed in a PR or since the last build on a branch.

The use case for this is when there are significantly different numbers of jobs that need to be run depending on the files changed in a given commit or PR. A common scenario would be a documentation only change requiring  1 job while a code change may require 30 jobs.

It seems like there are probably two different ways to accomplish this:
### Pattern Matching

Provide pattern matching on files changed as part of the matrix configuration. For example, the `shippable.yml` might accept configuration like the following to dispatch 1 job for changes to documentation, but 2 jobs for changes to code:

``` yaml
matrix:
  include:
    - env: ACTION=docs
      python: 2.7
      on_change: ^/docs/
    - env: ACTION=code
      python: 2.7
      on_change: ^/code/
    - env: ACTION=code
      python: 3.5
      on_change: ^/code/
```
### Dynamically Adding Jobs

Allow currently running jobs to add additional jobs to the currently running matrix. This would allow for more complex scenarios than the above, and may be much easier for you to implement. For example, a running job could execute commands such as the following to add additional jobs to the matrix that is already running:

```
shippable-matrix-add --python=2.7 --env='ACTION=code'
shippable-matrix-add --python=3.5 --env='ACTION=code'
```

To make use of this, the static matrix would most likely only contain a single job which would be responsible for deciding which additional jobs should be started.
