### ISSUE TITLE
Angular-Fullstack test results

### ISSUE THREAD

**Issue by molerat619** [Shippable/support#2716]
Hey there!

Currently I am using following .travis.yml file with Shippable in my angular-fullstack project.

```
language: node_js
node_js:
  - 5.6.0
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
services:
  - mysql

before_install:
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - curl -sSL https://get.rvm.io | bash -s stable
  - echo '[[ -s /etc/profile.d/rvm.sh ]] && source /etc/profile.d/rvm.sh' >> $HOME/.bashrc
  - source /etc/profile.d/rvm.sh && rvm install ruby-2.0.0-p598

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - npm install -g bower grunt-cli
  - ruby --version
  - gem install sass
  - bower install --allow-root
  - mysql -e 'create database sec24_testable;'

script:
  - grunt test

after_script:
  - ./node_modules/.bin/istanbul cover grunt test -- -u tdd
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/

build:
  cache: true
```

I get no test results nor coverage reports though. What am I missing? Thank you.

Edit: I am getting coverage reports now.
