### ISSUE TITLE
'Clear Cache' under Settings does not clear project cache

### ISSUE THREAD

**Issue by devillex** [Shippable/support#2720]
I tried clearing the cache from the project settings tab, but it failed to clear my cached node modules. What broke my build was when Angular renamed their NPM packages recently. What fixed it for me was to include the suggested [reset minion] or [reset_minion] in the commit message.

- Excerpt from documentation:

> Clearing cache

> You can clear cache in one of two ways:
> - Including [reset minion] or [reset_minion] in your commit message.
> - Clicking on the Clear cache in your Project settings UI.

- Excerpt from yml:
```yml
  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
```

- Link to the build failure
https://app.shippable.com/runs/57692909cb11530c00fc2c13
