### ISSUE TITLE
support yaml dict notation in env

### ISSUE THREAD

**Issue by halberom** [Shippable/support#2722]
### Description of your issue:

valid yaml dict notation is not supported in the env section of the shippable.yml config file.

See https://app.shippable.com/runs/57693eace89f5e0c00531efc for a job failing due to this

Works

```
env:
  - distribution=centos tag=6.8
  - distribution=centos tag=7.2.1511
  - distribution=ubuntu tag=14.04
  - distribution=debian tag=jessie
```

Fails

```
env:
  - distribution: centos
    tag: 6.8
  - distribution: centos
    tag: 7.2.1511
  - distribution: ubuntu 
    tag: 14.04
  - distribution: debian 
    tag: jessie
```

Expected
It would be nice if the valid yaml dict notation above worked.
