### ISSUE TITLE
"gcloud: command not found" when running a build which includes pushing images to GCR

### ISSUE THREAD

**Issue by randomsync** [Shippable/support#2725]
I'm trying out the micro-sample project for building docker images and and pushing them to registry, as documented here: http://docs.shippable.com/gs_deploy_sample/. The only change I'm making is instead of pushing to docker hub, I'm pushing the images to GCR. Here's my shippable.yml: https://github.com/randomsync/micro-sample/blob/986dd777b563b63af8fa5e348552948bf1174fa5/shippable.yml

I'm getting an error which seems related to authenticating with GCR and pushing:
```
  cd /tmp && gcloud -q auth activate-service-account --key-file key.json 0s  
/root/f6cb670e-e4a9-40fa-bdec-38b4da8c2eb2.sh: line 58: gcloud: command not found
```

- Link to the build failure
https://app.shippable.com/runs/5769c395ca639d0c00d3f6c7

Similar to #2272 #2276 #2288

**Comment by abhijitkini** [comment]
@randomsync the micro-sample project does not have gcloud sdk installed. Hence you are seeing this error.

Could you modify your `shippable.yml` file to include both actions below?
- add the `agent_only: true` in the GCR hub integration 
- move the docker tag and push commands to the `push` section

Here's [our documentation](http://docs.shippable.com/ci_configure/#gcrecr-and-custom-images) for your reference.

**Comment by manishas** [comment]
Can you try the yml below:

```
# language setting
language: node_js

# version numbers, testing against one version of node
node_js:
    - 0.12

env:
    - XUNIT_FILE=../shippable/testresults/result.xml API_PORT=3001

build:
   pre_ci:
       - cd micro-api && docker build -t micro-sample/micro-api .
   pre_ci_boot:
        image_name: micro-sample/micro-api
        image_tag: latest
        pull: false
   ci:
       - mkdir -p ../shippable/testresults
       - mkdir -p ../shippable/codecoverage
       - cd micro-api
       - npm install
       - grunt
   push:
       - cd ..
       - cd micro-www && docker build -t micro-sample/micro-www .
       - docker tag micro-sample/micro-www:latest us.gcr.io/handy-coast-134920/micro-www:$BRANCH.$BUILD_NUMBER
       - docker tag micro-sample/micro-api:latest us.gcr.io/handy-coast-134920/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push us.gcr.io/handy-coast-134920/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push us.gcr.io/handy-coast-134920/micro-www:$BRANCH.$BUILD_NUMBER

integrations:
    hub:
        - integrationName: gcr
          type: gcr
          agent_only: true

```

**Comment by manishas** [comment]
@randomsync please let us know if the suggestion above doesn't work for you. Closing this issue.

**Comment by randomsync** [comment]
@manishas I tried the yml and am getting a different error this time:

```
  cd micro-www && docker build -t micro-sample/micro-www . 0s  
/root/a5271af7-d272-46dc-87ba-28204260e372.sh: line 58: cd: micro-www: No such file or directory
```
output here: https://app.shippable.com/runs/57702c3cd7b8e20c0089ce95

It could be that I have missed something minor, so let me know if I should create a separate ticket. Thanks.

**Comment by manishas** [comment]
@randomsync sorry for the delay on this.... made a small tweak in the push section:

```
# language setting
language: node_js

# version numbers, testing against one version of node
node_js:
    - 0.12

env:
    - XUNIT_FILE=../shippable/testresults/result.xml API_PORT=3001

build:
   pre_ci:
       - cd micro-api && docker build -t micro-sample/micro-api .
   pre_ci_boot:
        image_name: micro-sample/micro-api
        image_tag: latest
        pull: false
   ci:
       - mkdir -p ../shippable/testresults
       - mkdir -p ../shippable/codecoverage
       - cd micro-api
       - npm install
       - grunt
   push:
       - cd /root/src/github.com/randomsync/micro-sample
       - cd micro-www && docker build -t micro-sample/micro-www .
       - docker tag micro-sample/micro-www:latest us.gcr.io/handy-coast-134920/micro-www:$BRANCH.$BUILD_NUMBER
       - docker tag micro-sample/micro-api:latest us.gcr.io/handy-coast-134920/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push us.gcr.io/handy-coast-134920/micro-api:$BRANCH.$BUILD_NUMBER
       - docker push us.gcr.io/handy-coast-134920/micro-www:$BRANCH.$BUILD_NUMBER

integrations:
    hub:
       - integrationName: gcr
         type: gcr
         agent_only: true
```
