### ISSUE TITLE
Can't see how to deploy using a script

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2726]
We deploy to AWS using CloudFormation, from a node.js script. We want to use this script with parameters from env vars in various environments.

Can't see how to set up a deployment for a repo

**Comment by stephanielingwood** [comment]
Hi @BryanCrotaz,

Let me see if I have this right. Fundamentally, you want to execute a node.js script in a build, and be able to use specific env vars within that script. It just so happens that that script handles your deploy to CloudFormation.

If that's the case, then you would first export those env vars in your yml; we support four different kinds of [environment variables](http://docs.shippable.com/ci_configure/#using-environment-variables). Then, you can reference them in your node script the way you normally would (e.g. process.env). Finally, you would execute that script, most likely in the on_success section. The resulting yml might look like this:

```
language: node_js

node_js:
  - "0.12"

env:
  global: 
    - FOO=foo
    - BAR=bar

build:
  ci:
    - npm install
    - grunt test
  on_success:
    # myDeploymentScript references process.env.FOO and process.env.BAR
    - node myDeploymentScript.js 
```
