### ISSUE TITLE
Postgres not start with official image

### ISSUE THREAD

**Issue by bronislav** [Shippable/support#2745]
### Description of your issue:
I'm experiencing an issue with starting postgres during ci

This is my `shippable.yml`:
```yaml
language: ruby

services:
  - postgres

build:
  ci:
    - psql -c 'create role shippable with superuser;' -U postgres
    - psql -c 'create database deals_test;' -U postgres
  on_success:
    - echo "Cool !!"
```

Failed build: https://app.shippable.com/runs/576d34f723e2800e0025bb52

My issue is that postgres never starts. It's rebooting several times and then reported that server couldn't boot. If I try to run postgres manually (ssh to node and docker run) it reports certificate access problem. 
It's related to the https://github.com/docker/docker/issues/783 I believe.
