### ISSUE TITLE
AWS region change

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2761]
We are currently in a process of migrating our aws resources to a different region, was unable to figure out where i can set the new region for the Shippable build process for Elastic beanstalk/Docker.

**Comment by stephanielingwood** [comment]
To set the new region, you'll need to change it in your yml. Specifically, look for the AWS integration in the integrations block of your yml, and update the "region" setting to your new region. Here's an example: 

```
integrations:
  deploy:
    - integrationName: "aws-test"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: sample-node-eb-paas-app
      env_name: sample-node-eb-paas-env
      region: us-east-1
```
 
For more information, check out our [docs on using Elastic Beanstalk](http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk).

**Comment by sheldon-sminq** [comment]
I currently use the following in my yml

post_ci:
       - cp -r ./target/* ./shippable/buildoutput
       - cp ./src/main/resources/build/test.sh ./shippable/buildoutput
       - cp ./test-api.yml ./shippable/buildoutput
       - sudo docker build -t test/baseimage:$BRANCH.$BUILD_NUMBER .
       - sudo docker push test/baseimage:$BRANCH.$BUILD_NUMBER
       - export EBS_IMAGE_TAG=$BRANCH.$BUILD_NUMBER
       - export EBS_IMAGE_NAME=test/baseimage
       - export EBS_VERSION=shippable.test.baseimage.$BRANCH.$BUILD_NUMBER
    on_success:
    on_failure:
    push:
    cache: false

integrations:
    hub:
        - integrationName: "Docker hub"
          type: docker

**Comment by stephanielingwood** [comment]
Based on that snippet of yml, it looks like you aren't specifying a deploy integration for AWS. Is that the case, or is it in a different section of the yml?

**Comment by sheldon-sminq** [comment]
In my shippable setup i deploy a docker application to AWS elastic
beanstalk, so i have a deploy integration along with a hub integration.

Shippable creates and image pushes it to docker hub, and then uses ebcli
commands to deploy the docker hub registry to the elasticbeanstalk
application.

But i have never set a region, so not sure where is shippable picking up
the default region.

I have attached a build log for reference, this is of a build for an
application in AWS Asia region.

**Comment by stephanielingwood** [comment]
Would you mind sharing the section of your yml where you declare your deploy integration for AWS?

Also, FWIW, the attached build log didn't come through. If you add a link to your build, though, we can take a look at the logs (and the project) directly.

**Comment by sheldon-sminq** [comment]
I do not declare any AWS section in my yml, currently it just works with
the hub integration.

Attached a build log which is a successful build for ap-southeast-1 region.

https://app.shippable.com/runs/576fec54561e0a0c00d9be1f

**Comment by bobbydeveaux** [comment]
@sheldon-sminq please can you share your full shippable.yml file?

The only integration we can see so far, is that you have is a DockerHub integration, so Shippable will not be deploying to AWS. To deploy to AWS with Shippable, you must have  an AWS Integration, of which you must specify a region, unless you have also put 'eb init', & 'eb deploy' somewhere in your shippable file? 

On your local machine, when typing 'eb init', an '.elasticbeanstalk' folder will be created with a config.yml file. You need to make sure you have this folder in your .gitignore (eb init normally does this for you).

**Comment by sheldon-sminq** [comment]
language: java
 # jdk tag
 jdk:
   - oraclejdk8
 services:
  - redis
  - mysql

 env:
  global:
     - secure:
YmnmUtDvTipSbmaHCjhdSRHX1dJgNfpfpMjN+FPEeCXFrHI/YVSlPVAH/daomspKiIR1GUszvdom6AZej/fl+Wz0nCzLxIc4Bv5GQgzHP7dfRNYQHfT7tY17wmEF1SsV43Ukoo+U6CZmPBhsbDv0/LByK7bA1+7ueINfSjlkwNVbbNnECeDq2q1ONK7jZcEcDfkt4RwwMRNWLGUQQVPvFbBmLHgX9RWu3mnC3dldG9CrYKQlxMb9+4575Gep3fSzDTufo7sTysUbj3DQ5h7lXDctZLEzo4ROWp2ZLvqBUsVyaG20q6K3kYnwrvfFO+/dlN2A+6pBUdYvYfwPFWmXLQ==
 branches:
   except:
     - master
     - api2.0.0
 build:
     pre_ci:
     pre_ci_boot:
         image_name: shippable/minv2
         image_tag: latest
     ci:
        - mysql -e 'DROP DATABASE IF EXISTS xxxx'
        - mysql -e 'CREATE DATABASE xxxx charset=utf8'
        - mysql -u root xxxx < database.sql
        - mysql -u root xxxx < data.sql
        - mvn install
     post_ci:
        - cp -r ./target/* ./shippable/buildoutput
        - cp ./src/main/resources/build/xxxxapi.sh ./shippable/buildoutput
        - cp ./xxxx-api.yml ./shippable/buildoutput
        - sudo docker build -t xxxx/baseimage:$BRANCH.$BUILD_NUMBER .
        - sudo docker push xxxx/baseimage:$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_TAG=$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_NAME=xxxx/baseimage
        - export EBS_VERSION=shippable.sminq.baseimage.$BRANCH.$BUILD_NUMBER
     on_success:
     on_failure:
     push:
     cache: false

 integrations:
     hub:
         - integrationName: "Docker hub"
           type: docker

This is my current yml file, and somehow it works with my current region.

**Comment by bobbydeveaux** [comment]
Your yaml file is not making any AWS deployment at all. What leads you to believe that your AWS environment is being updated?

**Comment by sheldon-sminq** [comment]
Well I have been running my staging apps with the same config since a while
now.

I also attached the log for a successful build.
On 30 Jun 2016 4:18 p.m., "Bobby DeVeaux" <notifications@github.com> wrote:

Your yaml file is not making any AWS deployment at all. What leads you to
believe that your AWS environment is being updated?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2761#issuecomment-229625179>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALMWfCKaS0TmRqu_DGeiwcUiFT6wMzAVks5qQ570gaJpZM4JA0vo>
.

**Comment by bobbydeveaux** [comment]
I do not have access to your build as I do not work for Shippable.

Do you have any logs that suggest it is deploying to AWS? Can you copy/paste?

Cheers

**Comment by stephanielingwood** [comment]
@bobbydeveaux thanks for chiming in. :)

@sheldon-sminq Looks like you set up your AWS integration at a time when it was configured through the UI. We've since moved to configuring deploy integrations via the yml, as it allows for version control of your deployment settings. 

We did, however, maintain backwards compatibility for those users - like yourself - who had set up their EBS deployments through our UI. That's why your EBS deploys have been working, even though you don't have the deploy integration in your yml. 

To update your region, you'll need to add the deploy integration to the yml. Your integrations section will now look something like this:

```
 integrations: 
  hub: 
    - integrationName: "Docker hub" 
      type: docker
  deploy:
    - integrationName: "name_of_your_aws_account_integration"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: your-application-name
      env_name: your-env-name
      region: us-east-1 # change this to your desired region
```

Then, go to your project on Shippable, and click on the "settings" tab. Double-check that your AWS integration is listed in the "Deploy Integration" section. 

Trigger your build, and you should see it use the new region. If it doesn't, let us know and we can change it in the db.

**Comment by sheldon-sminq** [comment]
@stephanielingwood thanks for the detailed explanation, will update my yml files accordingly

**Comment by sheldon-sminq** [comment]
I tried shifting to the new yml format, but facing some issues. Not sure if i am missing something here.

`integrations:
     hub:
         - integrationName: "Docker hub"
           type: docker
     deploy:
         - integrationName: "sminq-aws"
           type: aws
           target: eb_paas
           platform: "Docker"
           application_name: "sminq-api-staging"
           env_name: "sminq-api-staging"
           region: "ap-southeast-1"`

This is my updated yml for integrations, i have attached a build log to debug the issue.  https://app.shippable.com/runs/577a2254ae1dd40c00ec080b

**Comment by bobbydeveaux** [comment]
The platform should be: 

platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1"

Not sure if that's your only issue though! :)

**Comment by sheldon-sminq** [comment]
In the debug logs it shows

deployment_details

  Application Name: "sminq-api-staging"
  Environment Name: "sminq-api-staging"
  Version Label: "shippable.sminq-api-staging.api1.7.3-patch.1643"
  Region: "ap-southeast-1"
  *Platform: "*64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1*" *
*  Image Name: ""*
*  Image Tag: ""*
*  S3 Bucket Name: ""*

Do i need to setup all these values?

**Comment by sheldon-sminq** [comment]
Trying this config now, will get back with output results from build

integrations:
    hub:
        - integrationName: "Docker hub"
          type: docker
    deploy:
        - integrationName: "sminq-aws"
          type: aws
          target: eb_docker
          platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker
1.11.1"
          application_name: "sminq-api-staging"
          env_name: "sminq-api-staging"
          region: "ap-southeast-1"
          S3 Bucket Name: "elasticbeanstalk-ap-southeast-1-288789354248"
          Image Name: "abcd/baseimage"
          Image Tag: "$BRANCH.$BUILD_NUMBER"

**Comment by bobbydeveaux** [comment]
bucket_name not S3 Bucket Name :)

**Comment by bobbydeveaux** [comment]
ie. 

```
deploy:
    - integrationName: "MyIntName"
      type: aws
      target: paas
      platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1"
      application_name: app-name
      env_name: "$MYENV"
      bucket_name: elasticbeanstalk-eu-central-1-123123123123/myapi
      region: eu-central-1
      image_name: "bobby/dummy-dummy"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master
          - develop
```

**Comment by sheldon-sminq** [comment]
Thanks @bobbydeveaux will check the same.

**Comment by sheldon-sminq** [comment]
There seems to be some issue with the ebcli installation 

changing mode of build/scripts-2.7/eb_completion.bash from 644 to 755

running install_lib

creating /usr/local/lib/python2.7/dist-packages/ebcli

error: could not create '/usr/local/lib/python2.7/dist-packages/ebcli': Permission denied

Build https://app.shippable.com/runs/577a72b62575b70c00654f3c

**Comment by bobbydeveaux** [comment]
Are you using one of the new drydock images? I think not? 

 image_name: shippable/minv2 <- looks like an old one which the no longer maintain.

All their new images are "drydock" images.

e.g.build_image: drydock/u14php7all:tip

Not sure what you need to be honest! :)

**Comment by bobbydeveaux** [comment]
fyi: https://github.com/dry-dock

**Comment by sheldon-sminq** [comment]
I missed that completely, will check it out.

**Comment by sheldon-sminq** [comment]
Getting the following error in my build

```sudo docker run -d --privileged=true --net=bridge -v /home/shippable/cexec:/home/shippable/cexec -v /usr/bin/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.api.1650.1 --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.api.1650.1 -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false dry-dock/u14jav:tip 0s  
Unable to find image 'dry-dock/u14jav:tip' locally
Pulling repository docker.io/dry-dock/u14jav
Error: image dry-dock/u14jav:tip not found```

**Comment by sheldon-sminq** [comment]
Build is working now, thanks for the support @bobbydeveaux

**Comment by bobbydeveaux** [comment]
Awesome, good work!

**Comment by sheldon-sminq** [comment]
@bobbydeveaux  there seems to be an issue during the deployment process.

```creating build/temp.linux-x86_64-2.7/ext

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o

ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory

 #include "pyconfig.h"

                      ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pCebGI-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pyyaml
Storing debug log for failure in /root/.pip/pip.log

eb --version
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: blessed==1.9.5
```

**Comment by sheldon-sminq** [comment]
Do i need to include this in my .yml post_ci section? i think that is causing the conflict

```
- sudo docker build -t xxxx/baseimage:$BRANCH.$BUILD_NUMBER .
        - sudo docker push xxxx/baseimage:$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_TAG=$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_NAME=xxxx/baseimage
        - export EBS_VERSION=shippable.sminq.baseimage.$BRANCH.$BUILD_NUMBER
```

**Comment by bobbydeveaux** [comment]
No, I don't have that in my post_ci section :)

just:

```
 - docker build -t xxxx/baseimage:$BRANCH.$BUILD_NUMBER .
 - docker push xxxx/baseimage:$BRANCH.$BUILD_NUMBER
```

No need for sudo! :)

**Comment by stephanielingwood** [comment]
@sheldon-sminq How's it going? Looks like you and @bobbydeveaux (thanks again!) have gotten much of it sorted out.

**Comment by sheldon-sminq** [comment]
I am actually still stuck with 1 issue, could be a configuration error but need some help on the same.

https://app.shippable.com/runs/577b91f36a64790c0080d438 
sample build attached, my image gets deployed successfully but build still throws and error.

final config
```
pre_ci:
     pre_ci_boot:
         image_name: drydock/u14javpls
         image_tag: tip
         pull: true
     ci:
        - mysqldump -d --routines -h db.host -usminq -pdbpass sminq | sed -e 's/ AUTO_INCREMENT=[0-9]*//g' -e  's/DEFINER=`sminq`@`%`//g'  > ./database.sql
        - mysqldump --no-create-info -h db.host -usminq -pdbpass sminq  > ./data.sql
        - mysql -e "GRANT ALL ON *.* TO shippable@localhost IDENTIFIED BY ''; FLUSH PRIVILEGES;"
        - mysql -e 'DROP DATABASE IF EXISTS sminq'
        - mysql -e 'CREATE DATABASE sminq charset=utf8'
        - mysql -u shippable sminq < database.sql
        - mysql -u shippable sminq < data.sql
        - mvn install
     post_ci:
        - cp -r ./target/* ./shippable/buildoutput
        - cp ./src/main/resources/build/sminqapi.sh ./shippable/buildoutput
        - cp ./sminq-api.yml ./shippable/buildoutput
        - sudo docker build -t sminq/baseimage:$BRANCH.$BUILD_NUMBER .
        - sudo docker push sminq/baseimage:$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_TAG=$BRANCH.$BUILD_NUMBER
        - export EBS_IMAGE_NAME=sminq/baseimage
        - export EBS_VERSION=shippable.sminq.baseimage.$BRANCH.$BUILD_NUMBER
     on_success:
     on_failure:
     push:
     cache: true

 integrations:
     hub:
         - integrationName: "Docker hub"
           type: docker
     deploy:
         - integrationName: "sminq-aws"
           type: aws
           target: paas
           platform: "64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1"
           application_name: "sminq-api-staging"
           env_name: "sminq-api-staging"
           region: "ap-southeast-1"
           bucket_name: "elasticbeanstalk-ap-southeast-1-288789354248"
           image_name: "prod/baseimage"
           image_tag: "$BRANCH.$BUILD_NUMBER"

```
