### ISSUE TITLE
Building protobufs with shippable

### ISSUE THREAD

**Issue by distorce** [Shippable/support#2773]
I have a proto file(foo.proto) that I need to build(https://github.com/google/protobuf) whenever the protofile is changed in my bitbucket.  I'm not sure how I would go about doing this with shippable as in each container I would need to compile the C++ implementation of protobufs this would take a long long time. 

At the moment I am just building the proto myself when I know I've changed it and storing it in my bit bucket repo. 

I would like to not have to store the built proto and just have it generated each time the foo.proto is changed. 

Is there a possibility of the ubuntu containers on shippable to come with support for protobufs ? Then I could just run under CI: - protoc --go_out=. *.proto

Thanks

**Comment by manishas** [comment]
@distorce can you point us to a current build?

**Comment by abhijitkini** [comment]
@distorce here’s a suggestion: Create a new image by adding protobuf to the default Shippable image. Then use that image for your CI. The steps to do so are:

- Pick the most appropriate default image (https://github.com/dry-dock) from our platform based on the language you use.
- Build a new Docker image by adding protobuf support to the default image from above. (Ensure the Dockerfile for the new image has a FROM pointing to one of our standard images)
- Push the new image to a Docker registry.
- Override the default Shippable image in your YML file to use the newly created Docker image. 
- Your `shippable.yml` file should look like the sample below: (Replace manishas/myImage with the Image you created & manishasDockerHub with the integration name for your Docker Registry)
```
pre_ci_boot:
    image_name: manishas/myImage
    image_tag: latest
    pull: true
    options: "-e HOME=/root"

integrations:
    hub:
      - integrationName: manishasDockerHub
        type: docker
        branches:
          only:
            - master
```
- For more details, [refer our docs](http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry).
