### ISSUE TITLE
SSH key integration fails after maintenance

### ISSUE THREAD

**Issue by sethii** [Shippable/support#2775]
After maintenance SSH key integration stoped working:

In our shippable yml we have:

```
integrations:
  key:
    - integrationName: cojemy
      type: ssh-key
```

after successful ci build we add that key with `ssh-add /tmp/ssh/cojemy`, however it seems like file does not exists - this can be seen on [https://app.shippable.com/runs/577a4509ae1dd40c00f3a822](url)
