### ISSUE TITLE
New Slack Notification Update does not make use of default channel from the integration

### ISSUE THREAD

**Issue by asans** [Shippable/support#2789]
### Description of your issue:
Now that I'm setting up the slack notification in the shippable.yml, I was able to get the notifications to slack to work again.  However, when I remove the "recipients" config, the notifications does not make use of the default slack channel specified for that slack integration as indicated in the docs and therefore, nothing shows up on slack.

The default channel for the slack integration is "#builds" (including the # sign).  If I were to add `recipients: "#builds"` in the shippable.yml, then it will work.  If I take that out, it won't post to the default channel.

Thanks,
Alex

**Comment by abhijitkini** [comment]
@asans the `recipients:` field is required even for a single recipient/channel. Here's how a sample `shippable.yml` file for a single channel would look:
```
integrations:
  notifications:
    - integrationName: my_slack_integration
      type: slack
      recipients:
        - "#builds"
      branches:
        only:
          - master
          - dev
      on_start: always
      on_success: always
```
For more details, you can read [our docs](http://docs.shippable.com/ci_configure/#slack-notifications) on this topic.
