### ISSUE TITLE
no longer receive email updates

### ISSUE THREAD

**Issue by 9len** [Shippable/support#2791]
The last time I got a notification for a failed or successful build was 3/24. I have verified that the address specified in my account settings is correct. Our shippable.yaml does nothing fancy with notifications, we use the stock behavior. We are receiving slack notifications, and other members of my team receive emails. I have looked through my spam folder and archive, can find nothing after 3/24.

Here's a build I expected to get a failure notification for:

https://app.shippable.com/runs/577ec2985acb3d0d00f7b0e4/1/console

Thanks!

**Comment by abhijitkini** [comment]
@9len By default, the last committer and project owners are notified by email when a build fails, or the status changes from failed to passed. To override this default, you can specify the recipients in the `shippable.yml` file. A sample is given below:
```
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - exampleone@org.com
        - exampletwo@org.com
      branches:
        only:
          - master
          - dev
      on_success: always
      on_failure: always
```
Could you add your email address under the recipients for the email section, in your `shippable.yml` file and see if you receive notifications?
Let us know if it worked. 

[Our docs](http://docs.shippable.com/ci_configure/#email-notifications) go into more details of the options available.
