### ISSUE TITLE
Integration name specified in yml does not match integrations present in Subscription settings: Slack

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2803]
I get the following error when I try to build:
Integration name specified in yml does not match integrations present in Subscription settings: Slack

```yaml
integrations: 
  notifications: 
    - integrationName: Slack
      type: slack
      recipients: "#devops"
```

The integration name seems correct to me. https://app.shippable.com/accounts/562f309941bf7f0d00f5387a/settings/integrations/562f3bed41bf7f0d00f70e16/edit
