### ISSUE TITLE
Extra job created when only `matrix: include:` defined

### ISSUE THREAD

**Issue by jayvdb** [Shippable/support#2808]
When `.travis.yml` contains only a `matrix: include:` , shippable is creating an extra job for the defined environment outside of the `matrix: include:`
- https://app.shippable.com/runs/578714c1b9cd8b0c00034092/summary

There are other related problems like the top level `language: x` being mandatory, and langugages `generic` and `bash` causing an error, but they are not critical.   Creating an extra job is a waste of resources.

**Comment by manishas** [comment]
@jayvdb can you share your yml?

**Comment by jayvdb** [comment]
The following creates three jobs, when Travis only creates two jobs.

```yaml
matrix:
  include:
    - language: python
      env: DO=python
    - language: python
      env: DO=pascal

install:
  - if [ "$DO" == "python" ]; then pip install flake8; fi
  - if [ "$DO" == "pascal" ]; then sudo apt-get install fp-compiler; fi

script:
  - if [ "$DO" == "python" ]; then flake8 .; fi
  - if [ "$DO" == "pascal" ]; then find . -name '*.pas' | xargs -n1 fpc ; fi
```
