### ISSUE TITLE
Email and Slack notifications not working

### ISSUE THREAD

**Issue by robblovell** [Shippable/support#2815]
### Slack and Email Notification Failure:
The build goes or doesn't go, but no slack nor email notifications occur. At one point I did receive emails. But after adding slack web-hook integration, things stopped working. I went through the setup on slack and shippable twice and double checked everything many times.

Tried integration type of notification instead of slack, tried to put a separate notifications section, tried to remove the on_success/failure/start flags, tried not having branches, tried the minimum of notification configuration. 

app name and emails removed for privacy: #####-###, and ###@#########.com below.

```
env:
  global:
    - APP_NAME=#####-###

language: node_js

node_js:
   - "6.2.2"

build:
  pre_ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

  ci:
    - npm install
    - npm test
    - npm run-script test-shippable

  post_ci:
    - npm run-script test-coverage
    - npm run-script shippable-cobertura

  on_success:
    - git push -f git@heroku.com:$APP_NAME-$BRANCH.git master

integrations:
  notifications:

    - integrationName: CI-Notification
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
          - develop
      on_success: always
      on_failure: always
      on_start: never

    - integrationName: email
      type: email
      recipients:
        - ###@#########.com
      branches:
        only:
          - master
          - develop
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: never     # options: [always|never|change] default: always
```
