### ISSUE TITLE
CI Ruby is possible do gems dir cache and save it ?

### ISSUE THREAD

**Issue by maceto** [Shippable/support#2820]
When the process starts it takes longer to install all the gems than run all tests

Could be possible create and save a cache of the required gems?

**Comment by chetantarale** [comment]
@maceto This can be achieved by adding the following in build section of your yml.
```
build:
cache: true
cache_dir_list:
  - dir1
  - dir2
```
All the installed gems are stored under  `/usr/local/rvm/gems/$(ruby-version)/gems` directory.
You can find more info on caching [here]( http://docs.shippable.com/ci_configure/#caching).

**Comment by manishas** [comment]
@maceto I am closing this issue, but please let us know if the suggestion above doesn't work and we can reopen it.

**Comment by maceto** [comment]
Hi @chetantarale 

here my new config 

```
language: ruby
rvm:
  - 2.2.2
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage rvm_autoupdate_flag=0
services:
  - mongodb

build:
  ci:
    - cp env.development.sh.sample env.test.sh
    - cp config/mongoid.yml.sample config/mongoid.yml
    - bundle install --gemfile="Gemfile"
    - bundle exec rake
  cache: true
  cache_dir_list:
     - /usr/local/rvm/gems/2.2.2/gems
```

before new cofing this was my cache:

<img width="1013" alt="screen shot 2016-07-20 at 4 00 18 pm" src="https://cloud.githubusercontent.com/assets/52358/16999300/a97e59be-4e93-11e6-825a-c3c4c9044465.png">

after implement the new config with cache_dir_list:

<img width="1002" alt="screen shot 2016-07-20 at 3 59 16 pm" src="https://cloud.githubusercontent.com/assets/52358/16999295/a3f8ad50-4e93-11e6-91cd-7a4233685f74.png">

is not working. What I'm doing wrong ?

Thanks
Martin

**Comment by a-murphy** [comment]
Based on your shippable.yml and screenshots above, there are two reasons this isn't working as you expected.  First, `/usr/local/rvm/gems/2.2.2/gems` isn't a directory in the container.  There is however, `/usr/local/rvm/gems/ruby-2.2.2/gems`.  And it looks like you were using the default caching of the build directory before, which won't apply now that you have listed a directory to cache.

Could you try this in your shippable.yml?
```YML
  cache_dir_list:
     - /usr/local/rvm/gems/$(rvm strings 2.2.2)/gems
     - $SHIPPABLE_BUILD_DIR
```
It changes the path for the Ruby gems directory to cache and adds the build directory that you were caching before.

**Comment by maceto** [comment]
Hi @a-murphy, after change the config to this:

```
language: ruby
rvm:
  - 2.2.2
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage rvm_autoupdate_flag=0
services:
  - mongodb

build:
  ci:
    - cp env.development.sh.sample env.test.sh
    - cp config/mongoid.yml.sample config/mongoid.yml
    - bundle install --gemfile="Gemfile"
    - bundle exec rake
  cache: true
  cache_dir_list:
     - /usr/local/rvm/gems/$(rvm strings 2.2.2)/gems
     - $SHIPPABLE_BUILD_DIR
```
and run test the cache was created with the gems how you can see here:

<img width="980" alt="screen shot 2016-07-20 at 9 14 07 pm" src="https://cloud.githubusercontent.com/assets/52358/17007463/5ce226a4-4ebf-11e6-9864-ca9cb9dddb25.png">

RUN (630) https://app.shippable.com/runs/579011e8ba678a0c008d99b6/1/console


But on the second run wasn't restored the gems directory:

<img width="988" alt="screen shot 2016-07-20 at 9 14 37 pm" src="https://cloud.githubusercontent.com/assets/52358/17007457/524b1138-4ebf-11e6-80df-ce4cf1ac7904.png">

RUN (631) https://app.shippable.com/runs/57901373ba678a0c008db005/1/console
