### ISSUE TITLE
We no longer get slack notifications of builds as of July 13th. 

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2822]
Our last slack notification was July 12th. 

We tested the credentials that are in shippable and we can post to the channel.

**Comment by abhijitkini** [comment]
@chriskinsman can you provide a link to the build where the Slack notification is not working?

**Comment by chriskinsman** [comment]
All of the builds under this account: https://app.shippable.com/subscriptions/5490c3add46935d5fbc061a8/ci/dashboard

**Comment by abhijitkini** [comment]
@chriskinsman Slack notifications stopped working for this account based on a [recent service update](http://blog.shippable.com/slack-elastic-beanstalk-and-ui-changes-in-july1-update) we made, where we changed the way legacy Slack notifications were being handled.  

To get back Slack notifications like before, please ensure the following code is included in the `shippable.yml` file for all projects that you want Slack notification:

```
integrations:
  notifications:
    - integrationName: foobar-slack
      type: slack
      recipients:
        - "#shippable"
      on_start: always
      on_success: always
```
where `integrationName` is the exact name you have specified for the Slack integration in your `Subscription` Settings and `recipients` is(are) the channel(s) on Slack you want to be notified.

You can read more about it in [our docs](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance).
