### ISSUE TITLE
PHP: Cannot install "fileinfo" via Pickle

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2830]
I'm trying to install a few PHP extensions via Pickle on build but [fail right away](https://app.shippable.com/runs/5792395bde87980c00f67e4b/1/console) with `fileinfo`:

```
pickle install --ansi fileinfo
  - Installing fileinfo (latest-stable)
    Downloading: ...
                                                                   
  [RuntimeException]                                               
  Unsupported package.xml version, 2.0 or later only is supported
```

Any idea what's wrong here?

The full `shippable.yml`:

```yaml
language: php

php:
  - 5.6

build:
  ci:
    - echo "date.timezone=Europe/Berlin" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - pickle install --ansi fileinfo
```
