### ISSUE TITLE
PHP: Cannot install "bz2" via Pickle

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2846]
I am unable to install the PHP extension "bz2" via Pickle during [build](https://app.shippable.com/runs/579f28b0f8e06c0c001d2133/1/console):

```
pickle install --ansi bz2
  - Installing bz2 (latest-stable)
    Downloading: ...

  [RuntimeException]                                               
  Unsupported package.xml version, 2.0 or later only is supported  
```

This is my `shippable.yml`:

``` yaml
language: php

php:
  - 5.6

build:
  ci:
    - echo "date.timezone=Europe/Berlin" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - php -m
    - pickle install --ansi bz2
```

Quoting from [the PHP docs](http://php.net/manual/en/bzip2.installation.php):

> Bzip2 support in PHP is not enabled by default. ...

Please also see #2830 for more details.
