### ISSUE TITLE
build images only for master branch

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2849]
I want my CI to test PRs. But build only images of master. And only after they are actually merged in.
How do i set it up?
My current yaml:
```yaml
language: node_js

node_js:
    - 5.11

build:
    ci:
    - echo "is a PR? $IS_PULL_REQUEST"
    - cd client; npm install
    - npm test
    - npm run build
    - cd ../server; npm install
    - echo "module.exports =  $BUILD_NUMBER;" > dist/version.js
    - npm test
    - cd ..
    post_ci:
    -  if [ "$IS_PULL_REQUEST" == false ]; then docker build -t trilogiq/web-template .; fi
    -  if [ "$IS_PULL_REQUEST" == false ]; then docker tag -f trilogiq/web-template:latest 975150373617.dkr.ecr.eu-west-1.amazonaws.com/trilogiq/web-template:$BUILD_NUMBER; fi
    -  if [ "$IS_PULL_REQUEST" == false ]; then docker push 975150373617.dkr.ecr.eu-west-1.amazonaws.com/trilogiq/web-template:$BUILD_NUMBER; fi
integrations:
  hub:
    - integrationName: ecr_repository
      type: ecr
      region: eu-west-1
      branches:
        only:
          - master
```

Problem is that after i merge PR into master another build is not kicked off. So the end result is no image.
