### ISSUE TITLE
Specify JDK version - Node

### ISSUE THREAD

**Issue by timtribers** [Shippable/support#2863]
Hi,

Is there any way to tell shippable to use j2se 8 in a **node** language run (as I have a 3rd party jar, that I need to shell out and run)?

It seems to default to 7.
> java version "1.7.0_80"
> Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

I have tried adding 
```
language: node_js

jdk:
   - oraclejdk8
```
to the .yml , but to no effect.

Thanks

**Comment by stephanielingwood** [comment]
Hi @timtribers,

Right now, trying to use oraclejdk8 in the node build won't work, because it's not installed in the node image. 7 is, however, which is why you're seeing it default to 7.

To make this work, you'll need to end up with certain languages and whatever other sevices/addons you need, by the time you start executing test commands and such in your build. There are a couple ways to approach this, which are also discussed in our docs: http://docs.shippable.com/ci_faq/#can-i-use-multiple-langauges-in-a-build. At a glance, they are:

1.) Create your own custom build image with exactly what you need. This is a bit more work, as you'll need to build, tag, and push your image to a registry, but gives you the most control over what's installed. Check out [our docs](http://docs.shippable.com/ci_configure/#overriding-the-default-build-image) on how to override the pre-set build image and use your own. Feel free to use our [build images](https://github.com/dry-dock) as a starting point.

2.) Use one of our existing images for one language, and install what you need for the other language. For example, you could specify the language as node, but use one of the java images, since our base image already has node installed:
```
language: node_js

node_js:
  - 0.12

jdk:
   - oraclejdk8

build:
  pre_ci_boot:
    image_name: drydock/u14javpls
    image_tag: prod
    pull: true
  ci:
    - echo $JAVA_HOME
    - java -version
    - npm install
    - npm test
```
If you want to learn more about what's in each image, you can start [in our docs](http://docs.shippable.com/ci_languages/), or look at our install scripts in the [dry-dock](https://github.com/dry-dock) repo.
