### ISSUE TITLE
Slack notification doesn't work

### ISSUE THREAD

**Issue by chebum** [Shippable/support#2867]
Our Slack integration stopped working completely. The Slack's webhook itself is working - I can confirm this by sending a POST request to it. I tried re-adding a webhook with no luck. Looks like Shippable doesn't send POST request to the webhook. Is there something we can do to solve the problem?

Build in question: https://app.shippable.com/runs/57a9afe54e773c1800a877a4/1/console
For this particular build we didn't receive a notification.

Notifications stopped working in July. July 11 was the last day we received notifications from Shippable.

**Comment by kanthchandra** [comment]
@chebum  Slack notifications stopped working for this account based on a [recent service update](http://blog.shippable.com/slack-elastic-beanstalk-and-ui-changes-in-july1-update) we made, where we changed the way legacy Slack notifications were being handled.  You will now have to have slack notifications configured in your subscription settings as well as in shippable.yml

To get back Slack notifications like before, please ensure the following code is included in the `shippable.yml` file for all projects that you want Slack notification:

```
integrations:
  notifications:
    - integrationName: foobar-slack
      type: slack
      recipients:
        - "#shippable"
      on_start: always
      on_success: always
```
where `integrationName` is the exact name you have specified for the Slack integration in your `Subscription` Settings and `recipients` is(are) the channel(s) on Slack you want to be notified.

You can read more about it in [our docs](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance). 

You can read more about configuring notifications in shippable.yml [here] (http://docs.shippable.com/ci_configure/#notifications)

**Comment by manishas** [comment]
@chebum let us know if you have any other questions or need help with configuring slack.

**Comment by chebum** [comment]
Hi Manishas,

Thank you for the suggestion. I added configuration file on Aug 10 and still no notifications from Shippable since then. Here is a build log with the commit:
https://app.shippable.com/runs/57ab0b4b2363531000284dce/1/console

And here is shippable.yml
```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

# The path for Xunit to output test reports
env:
  - XUNIT_FILE=shippable/testresults/result.xml

# Create directories for test and coverage reports
before_install:
  - cd ./Xenarius.2015
  - npm install -g grunt-cli

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

# Running the tests with grunt
script:
  - npm test
  
integrations:
  notifications:
    - integrationName: Slack
      type: slack
      recipients:
        - "#repo"
      on_start: always
      on_success: always
```

Did I miss anything?

**Comment by chebum** [comment]
@kanthchandra @manishas sorry for disturbing you again. Not sure you saw my follow-up on this topic.

**Comment by kanthchandra** [comment]
Hi @chebum, since the issue was closed I lost track of this. Initially I assumed that your yml had been migrated to the new format but it looks like it hasn't been migrated. Can you try this yml and also make sure that the url you have mentioned in the account integration is working?
```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

# The path for Xunit to output test reports
env:
  - XUNIT_FILE=shippable/testresults/result.xml

build:
  ci:
    - cd ./Xenarius.2015
    - npm install -g grunt-cli
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm test

integrations:
  notifications:
    - integrationName: Slack
      type: slack
      recipients:
        - "#repo"
      on_start: always
      on_success: always
```

**Comment by chebum** [comment]
@kanthchandra Didn't help, unfortunately. No notification on the Slack channel.

**Comment by kanthchandra** [comment]
Can you point me to the build that dint receive the notification now?

**Comment by chebum** [comment]
@kanthchandra Sure. https://app.shippable.com/runs/57b59f272a033c0f00bacaa4/1/console

**Comment by manishas** [comment]
@chebum sorry for the late follow up on this. I think I know what the issue is.... did you replace the values in yml with what you need? The format for Slack notifications is documented here along with the list of values needed:
http://docs.shippable.com/integrations/notifications/slack/#ci-notifications

**Comment by chebum** [comment]
Hi @manishas Already did this (see my code above). Unfortunately, it didn't help. 
It also tried to rename my integration and added the `branch` node as well. Still no luck.
Build link: https://app.shippable.com/runs/57c41f0ec96a570f00b9c2ac/1/console
Shippable.yml:
```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

# The path for Xunit to output test reports
env:
  - XUNIT_FILE=shippable/testresults/result.xml

build:
  ci:
    - cd ./Xenarius.2015
    - npm install -g grunt-cli
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm test

integrations:
  notifications:
    - integrationName: slack-shippable
      type: slack
      recipients:
        - "#repo"
        - "#channelTwo"
      branches:
        only:
          - master
      on_success: always
      on_failure: always
```

**Comment by a-murphy** [comment]
Could you check that the name in "integrationName" matches the name of the integration on the subscription settings tab exactly?  There doesn't appear to be a "slack-shippable" integration in that subscription.  And, since they weren't working with a different integration name either, by any chance are these private Slack channels?  If they're private channels, they don't need the `#` in front of the name.

**Comment by chebum** [comment]
Hi @a-murphy Yes, I have slack-shippable integration. See the screenshot.
![integration](https://cloud.githubusercontent.com/assets/1398682/18161998/8eab85cc-7034-11e6-8a6d-87840468f99b.PNG)

**Comment by kanthchandra** [comment]
Hi @chebum, you also need to add that account integrations to your subscription settings. So here are the steps that you need to do.

```
# Language setting
language: node_js

# Version number
node_js:
  - 0.12.2

# The path for Xunit to output test reports
env:
  - XUNIT_FILE=shippable/testresults/result.xml

build:
  ci:
    - cd ./Xenarius.2015
    - npm install -g grunt-cli
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - npm test

integrations:
  notifications:
    - integrationName: slack-shippable
      type: slack
      recipients:
        - "#repo"
        - "#channelTwo"
      branches:
        only:
          - master
      on_success: always
      on_failure: always
```

Note: I'm assuming you are using this yml for your build and giving the steps based on this yml.
1. Go to the [subscriptions integrations](https://app.shippable.com/subscriptions/55d47dd61895ca44740e28a1/settings/integrations/) page.
2. Click on Add Integration on the top right corner of the integrations panel.
3. Give the name of the new subscription integration as `slack-shippable` (it's the same integrationName that you have given in the yml `integrationName: slack-shippable`)
4. Next select `slack-shippable` (it's the same name that  you have given while creating the account integration) in the account Integrations drop down.
5. Next select the projects for which you want to use this integration or just select all projects if you want all the projects in this subscription to have access to this integration.
6. Click on save and you are good to go.

Even after following the instructions if it doesn't work, Let us know the runId, I will check the logs and let you know.

Sorry about the back and forth on this one, we are unable to repro this at our end.
