### ISSUE TITLE
.NET Core custom build image and Docker hub image push

### ISSUE THREAD

**Issue by johnmckinzie** [Shippable/support#2870]
I don't really know if this is a bug, b/c I know there are some restrictions on the custom build images. I'm trying to build my project using the following custom image:

https://hub.docker.com/r/microsoft/dotnet/

I can successfully build the project using the file below:

```
language: none

build:
  pre_ci_boot:
    image_name: microsoft/dotnet
    image_tag: 1.0.0-preview2-sdk
    pull: true
    options: "-e HOME=/root"

  ci:
    - dotnet restore
    - cd src/DibblerApi
    - dotnet build
    - dotnet publish

  push:
    - docker push dibbler/dibbler-api:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: dockerhub
      type: docker
      branches:
        only:
          - master
```

However, when I get tot the `push` step, I get the following error:

```
docker push dibbler/dibbler-api:$BRANCH.$BUILD_NUMBER
The push refers to a repository [docker.io/dibbler/dibbler-api] (len: 1)
Repository does not exist: dibbler/dibbler-api
```

I can successfully push to that repo form my local machine using the same credentials.

I would be nice to now that it is or is not tied to the custom image.

**Comment by rageshkrishna** [comment]
@johnmckinzie The error message `Repository does not exist` typically shows up when the image you're trying to push doesn't exist locally. Is your build doing a `docker build` to create the image?

**Comment by johnmckinzie** [comment]
So since I'm building in a custom container, I should use the "push" commanded to build the Docker image on the host machine not in the Docker container, correct? If that's true, the following is the only example I found in the documentation:

```
build:
  push:
    - docker push manishas/sample-node:$BRANCH.$BUILD_NUMBER
```

I went ahead and added a `docker build` command to the the `push:` step and now I get the following error:

```
docker build -t dibbler/dibbler-api:$BRANCH.$BUILD_NUMBER . 0s  
     unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/Dockerfile: no such file or directory
```

Here is my latest shippable.yml:

```
language: none

build:
  pre_ci_boot:
    image_name: microsoft/dotnet
    image_tag: 1.0.0-preview2-sdk
    pull: true
    options: "-e HOME=/root"

  ci:
    - dotnet restore
    - cd src/DibblerApi
    - dotnet build
    - dotnet publish

  push:
    - docker build -t dibbler/dibbler-api:$BRANCH.$BUILD_NUMBER .
    - docker push dibbler/dibbler-api:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: dockerhub
      type: docker
      branches:
        only:
          - master
````
