### ISSUE TITLE
Slack Integration Stopped Working

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2872]
Our Slack notifications integration stopped working a couple of days ago without and configuration changes on our part.

https://app.shippable.com/projects/562f31c81895ca4474213d1f/status/

```yaml
integrations: 
  notifications: 
    - integrationName: Slack
      type: slack
      recipients: "#devops"
```
