### ISSUE TITLE
`npm install` silently fails

### ISSUE THREAD

**Issue by OddEssay** [Shippable/support#2878]
`npm install` has been silently failing for some time, but we haven't noticed because the node modules we were using were in the cache. 

Now we've added a new requirement, we noticed it wasn't finding the new file and after deleting the cache, have realised what the problem actually was.

The most recent failed build is: https://app.shippable.com/runs/57b1b7e500cee6110080c685/summary

Our shippable.yml is:
```
language: node_js                                                                                                                                                                                           
node_js:
  - 6.2.0
  - 4.2.3
env:
  - NODE_ENV=production
build:
  pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: true
  ci:
    - npm install
    - npm test
```

The build looks like this:

![failed-build](https://cloud.githubusercontent.com/assets/837227/17664913/4d9f7b94-62ef-11e6-8ceb-c672e1fa6df1.png)
