### ISSUE TITLE
Getting a tar write error on install_firefox_addon

### ISSUE THREAD

**Issue by acburdine** [Shippable/support#2889]
### Description of your issue:

When running a build that requires the firefox addon, I'm getting a tar write error on the firefox install step.

Another project that has the same exact shippable.yml doesn't have this issue.

[Build failure link](https://app.shippable.com/runs/57ba3fb94d7c050e00836018/1/console)
[Link to the different project that works](https://app.shippable.com/runs/57ba3a791419e20f001a60a1/1/console)

I've tried clearing the cache as well, several times with no effect 😞

**Comment by acburdine** [comment]
It seems to happen randomly too - here's a link to the build of [another project](https://app.shippable.com/runs/57ba45671419e20f001a60d9/2/console) where the second build succeeded for firefox install but the other ones failed.

**Comment by acburdine** [comment]
Here's the shippable files:

First project mentioned:
```yml
language: node_js

node_js:
  - "4.4.3"

addons:
  firefox: "48.0.1"

services:
  - selenium

build:
  ci:
    - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
    - "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - "export DISPLAY=:99.0"
    - xvfb-run npm test
  cache: true

branches:
  only:
    - master
```

Second project mentioned (the one that was working) is the same as the first

The one that was failing randomly for different sub-builds:
```yml
language: node_js

node_js:
  - "4.4.3"

addons:
  firefox: "48.0.1"

services:
  - selenium

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - TEST_SUITE=lint

build:
  ci:
    - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
    - "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - "export DISPLAY=:99.0"
    - "if [ '$TEST_SUITE' == 'lint' ]; then npm run lint; else xvfb-run npm run test:single; fi"
  cache: true

branches:
  only:
    - master
```
