### ISSUE TITLE
Docker Compose failure. Any examples to learn from?

### ISSUE THREAD

**Issue by tspicer** [Shippable/support#2913]
Im trying to leverage docker-compose in my builds. However, I keep getting errors related to it not being able to find the image. I attempted to find documentation on this topic, but having trouble as the documentation page seems to be  having problems (not rendering properly): 
http://docs.shippable.com/ci_docker/#docker-compose

here is my test shippable.yml

```
# language setting
language: none

build:

    ci:
      - docker build -t $SHIPPABLE_CONTAINER_NAME .
      - docker commit $SHIPPABLE_CONTAINER_NAME 1111111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name
      - docker push 1111111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name
    post_ci:
      - sudo pip install -U docker-compose awscli pip
      - docker images
      - docker tag -f $SHIPPABLE_CONTAINER_NAME 1111111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
      - docker pull 1111111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
      - docker-compose up -d
      - docker ps

integrations:
  hub:
    - integrationName: shippable-aws-ecr
      type: ear
```

Here is the compose file
```
name:
  image: 1111111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
  volumes:
    - /ebs:/ebs/
  environment:
    - ob_mode=aws
    - ob_tag=name
    - REDIS_INSTANCE=172.17.0.1
  container_name: name
  restart: always
  tty: true
redis:
    image: redis
    container_name: redis
    restart: always
    ports:
     - 6379:6379
    volumes:
     - /ebs/data:/data
    command: redis-server --appendonly yes
```
Link to the build
https://app.shippable.com/runs/57c07a72fa8c170f0091bd27/1/console

Having difficulty finding any full samples of a docker-compose shippable.yml to learn from.

**Comment by a-murphy** [comment]
So, it looks like you're committing the build container (the Shippable container that runs builds) and then trying to run that image.  It's not working because the entrypoint for the build container is a file in a mounted volume that runs the build script. However, that also doesn't appear to be the image you were trying to push.  Removing the `docker commit` command and replacing `$SHIPPABLE_CONTAINER_NAME` with the image name you have in `docker push` should push the correct image.  The `docker tag` also probably won't do what you intended.

**Comment by tspicer** [comment]
@a-murphy , thanks for the pointer. I made the following changes and was able to get it to run as expected.  

```
# language setting
language: none

build:

    ci:
      - docker build -t foo/name .
      - docker tag -f foo/name:latest 11111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
      - docker push 11111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
    post_ci:
      - sudo pip install --upgrade pip docker-compose awscli
      - docker pull 11111111111.dkr.ecr.us-east-1.amazonaws.com/foo/name:latest
      - docker-compose up -d
      - docker ps

integrations:
  hub:
    - integrationName: shippable-aws-ecr
      type: ecr
```
