### ISSUE TITLE
Question - how to run tests using docker-compose?

### ISSUE THREAD

**Issue by Zhomart** [Shippable/support#2938]
I have multiple services that need to be pulled from private docker repo. And my app uses these services and mongodb. Services are RPC servers using TCP.

Where should I run docker-compose, in `pre_ci` or in `ci`? And how `pre_ci_boot` should look like?

Example of my docker-compose.yml
```yaml
version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rake test
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - myservice
  myservice:
    image: gcr.io/mycompany/myservice:latest
    ports:
      - "41003:41003"
  mongodb:
    image: mongo:3.3
    volumes:
      - engine-mongo-data:/data/db
volumes:
  engine-mongo-data:
```

And here is the example of my shippable.yml
```yaml
language: python # I dont use any language, python is choosen randomly

build:
  ci:
    - pip install -U docker-compose
    - docker-compose -f docker-compose.test.yml up -d myservice mongodb && sleep 10
    - docker-compose -f docker-compose.test.yml build app
    - docker-compose -f docker-compose.test.yml run app ls -lah /    # it shows directories, including /app
    - docker-compose -f docker-compose.test.yml run app ls -lah /app # it's empty
    - docker-compose -f docker-compose.test.yml run app rake test    # fails, because it cannot find the file Gemfile

integrations:
  hub:
    - integrationName: my-gcr
      type: gcr
```

I see that when running my container you provide docker binary and sock file `-v /opt/docker/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock`.

**Comment by manishas** [comment]
@rageshkrishna can we please look into this?

**Comment by jatindogra** [comment]
@Zhomart Can you please share your Dockerfile as well?

**Comment by Zhomart** [comment]
@jatindogra Sure.

app/Dockerfile
```Dockerfile
FROM ruby:2.3.1

RUN mkdir -p /app
WORKDIR /app

RUN gem install bundler

COPY Gemfile /app/
COPY Gemfile.lock /app/

RUN bundle install

COPY . /app

CMD bin/run-app
```

myservice/Dockerfile
```Dockerfile
FROM python:2.7-wheezy

RUN pip install --upgrade pip
COPY requirements/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY . /app
WORKDIR /app

EXPOSE 31005

CMD ["python", "main.py"]
```

**Comment by jatindogra** [comment]
@Zhomart, what happens is all the docker commands are running on the host i.e docker daemon and the project files are cloned in some other container. So when we use `. :/app` in volumes, it doesn't know where the files actually are and fails to copy the files.
 
If we will add the docker volumes in `pre_ci_boot` in `shippable.yml`, then it knows where the host container is and then in the `ci` section of the shippable yml you can copy the files using `cp -R . /app`

Now when we are adding volumes in `pre_ci_boot` we also, need to update volumes in the docker-compose yml with `/app:/app`

**Update volumes in docker-compose.yml**
```
  volumes:
    - /app:/app
```

**Add pre_ci_boot in Shippable.yml with volumes**
```
build:
  pre_ci_boot:
    options: "-v /app:/app"
```

**Add a copy command in ci steps in shippable.yml before docker-compose commands**
```
ci:
    - pip install -U docker-compose
    - cp -R . /app
    - docker-compose -f docker-compose.test.yml up -d myservice mongodb && sleep 10
```

I am also adding a sample project where I tested out above changes.
https://github.com/jatindogra/samplePyt

**Comment by manishas** [comment]
closing this issue.

**Comment by eddwardo** [comment]
As a developer I don't treat this a solution. Changing docker-compose.yml volumes makes it unusable locally where I don't have the `/app`. Is there any other way to use docker-compose untouched on shippable?

**Comment by Zhomart** [comment]
@eddwardo, I didn't like that solution too, so I moved to  Gitlab CI, where I can run CI Runner on my own server and configured it as [a shell executor](https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-shell-executor).

As I understood, currently Shippable does the same thing as [docker-socket-binding](https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-socket-binding), which has it's own limitations, like mounting directories in containers.

**Comment by jmills-bespoke** [comment]
I don't understand why this has no been re-opened, I don't agree with this solution either.. has something come up since? is there a better way to handle this?

**Comment by manishas** [comment]
I'll ask the team to respond to this asap. I agree that you shouldn't need to change anything in your docker compose yml.

**Comment by jmills-bespoke** [comment]
thanks @manishas

**Comment by ttrahan** [comment]
There's an alternative solution that does not require any changes to your docker-compose.yml.

You can reference this sample file to see an example of how to use Compose to bring up multiple containers on the build machine without changing your docker-compose.yml:
https://github.com/ric03uec/sample_jacoco/blob/master/shippable.yml

The key concept to understand for this is how Shippable CI jobs run. In CI jobs, two containers (at a minimum) will run on the VM host. The first, genExec, orchestrates what occurs on the VM. All commands in the 'pre_ci', 'pre_ci_boot' and 'push' sections of the shippable.yml run in this genExec container. The second, cexec, is the build container, i.e. your build machine. The issue you're likely seeing is that the Docker Compose instruction within the 'ci' section is pointing to a compose file in the file system of the cexec container, which the Host docker engine isn't finding. Instead, you can leverage a shared directory on the Host file system to copy your Compose files into before issuing the 'docker compose ... up' command.

Currently, the shared directory on the Host that both genExec and cexec have access to is the '/build' directory. You'll see in the sample, a directory path is created in this directory, then the compose files are copied there before issuing the compose up command.

Please note that this /build directory also contains Shippable files required for build execution. Take care not to overwrite or delete these files. We have a backlog item that will create a dedicated, shared data directory on the VM host for all containers to share to avoid this possibility in the future.

If you use this method, your docker-compose.yml files do not need to be changed. Let us know if this will work for you.

**Comment by jmills-bespoke** [comment]
Thanks @ttrahan but this solution is just another work around as the link https://github.com/ric03uec/sample_jacoco/blob/master/compose-config.yml#L8 is referencing in the volume a path that does not exist locally and will not build.

So we are right back to the fact that I will need two different `docker-compose` files in order to run my stack locally and within the CI. I have used the examples above to get my environment working and running all my tests with a separate `docker-compose` but this still leaves me with a file specifically for shippable.

My solution involves copying the entire Monorepo into the `/build` directory and having each individual micro services within my docker-compose referencing their own directory in the volumes:
```
volumes:
    - /build/{service}:/app
```
----
Can you provide the link to the backlog item on this fix just so I can stay updated on its progress?


Cheers,

**Comment by ttrahan** [comment]
@jmills-bespoke : ah, sorry about that. Missed that this sample is also mounting a volume. Let me investigate if there's another alternative.

**Comment by eddwardo** [comment]
I added this https://github.com/docker/compose/pull/4566/commits/83388ec31ae0e81fec0c6904f74e04345f1fb069 to docker-compose which got to upstream.

Quite soon we will be able to do: `docker run -v local:remote container`

That enabled to run tests without changes to compose file like this:

```
language: python
build:
  pre_ci_boot:
    options: "-v /app:/app"
  ci:
    - cp -R . /app
    - docker-compose build
    - docker-compose run -v /app:/app --rm service_from_compose py.test tests/
cache: true
```

**Comment by ttrahan** [comment]
@eddwardo : That's a great way to solve this. Thanks for making that commit and letting us know about it.

@jmills-bespoke : Until @eddwardo's commit is live, another option is to use the [Compose override](https://docs.docker.com/compose/extends/) feature. It still requires a second file, but is cleaner than maintaining two separate docker-compose.yml files. Using the override feature via a second file such as `docker-compose.ci.yml`, would allow the incremental info required for CI to be merged during the CI run, but ignored locally. Your devs could still make any required updates to their docker-compose.yml without having to redundantly remember to make them in a second copy of the compose yml.

Using the earlier example:

docker-compose.yml
```
redis:
  image: shipimg/rdsbase:master.698
  privileged: true
  net: "host"
  ports:
    - "6379:6379"
```
docker-compose.ci.yml
```
redis:
  volumes:
    - ./build/fo0:/tmp/data  
```

running compose locally:
```
docker-compose up
```
running compose on Shippable:
```
docker-compose up -f docker-compose.yml -f docker-compose.ci.yml up
```

**Comment by jmills-bespoke** [comment]
Thanks @eddwardo and @ttrahan, I will continue to follow the progress of this and in the interim use the fix as stated by @ttrahan

**Comment by manishas** [comment]
@chetantarale we need to write a tutorial on using docker compose with Shippable. Please include Tom's approach above and also mention the upcoming change contributed by @eddwardo .

**Comment by zoro1666** [comment]
Hi, 
Is @eddwardo commit live yet? . And can you make a full example to demonstrate solving this issue, please.

**Comment by eddwardo** [comment]
@zoro1666 yes.

**Comment by zoro1666** [comment]
@eddwardo  thanks. Any documentations or clear example to follow ?

**Comment by ambarish2012** [comment]
@zoro1666 we are in the process of creating a doc on using docker-compose, will share the link latest by EOD tomorrow.

**Comment by ambarish2012** [comment]
@zoro1666 we are investigating a bug with docker-compose run -v. The mounts are not working as expected. I will keep you posted about our progress.

**Comment by eddwardo** [comment]
@zoro1666 what's the issue. I use the `run -v` option with the recent docker-compose and it works fine.

```
language: python
env:
  - secure: {my secure venv}
build:
  cache: true
  pre_ci_boot:
    options: "-v /code:/code"
  cache_dir_list:
    - /root/venv/2.7
    - $SHIPPABLE_BUILD_DIR/app/.tox
  ci:
    - cp -R . /code
    - pip install -U docker-compose
    - docker-compose build
    - docker-compose run -v /code/app:/code --rm test
  on_success:
    - docker tag ...
    - docker push ...

integrations:
  hub:
    - integrationName: ecr
      type: ecr
      region: region
```
