### ISSUE TITLE
Canceling build causes Provisioning job node

### ISSUE THREAD

**Issue by EvgeneOskin** [Shippable/support#2944]
### Description:
Hello, 

I've experienced the issue with canceling build at `pre_ci` stage. I use `docker-compose` to run tests, so I use this stage to run the tests and put stub to `ci` stage. 

Once the job canceled, a new build gets stuck in the _Provisioning job node_ stage.

The part of my `shippable.yml`:
```yml
  pre_ci:
    - pip install -r dev_requirements.txt
    - docker-compose build
    - docker-compose run web sh -c "$WEB_CI_COMMAND"
  ci:
    - echo "Stub"
```
