### ISSUE TITLE
Pipelines: Build Notification Doesn't Trigger Deploy

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2948]
### Problem
The webhook build notification I've configured in the `shippable.yml` does not trigger the deployment pipeline.

### Configuration
I have a repo called `platypus` which contains a `shippable.yml` with the following notification:

````
integrations:
  notifications:
  - integrationName: trigger-crm-image
    type: webhook
    payload:
    - "versionName=$BRANCH.$BUILD_NUMBER"
    on_success: always
    on_failure: never
```

This is basically a copy of the sample webhook notification. I've also tried setting the payload to `versionName=$BRANCH`.

The integration `trigger-crm-image` is configured to trigger the `crm-image` resource in the pipeline. This is, of course, a resource of type `image` which is wired into two manifests and their subsequent deploy jobs. None of those jobs are triggered on build.

### What I Want
I would like builds on the `master` and `develop` branches to triger the `crm-latest` and `crm-develop` manifests respectively. I don't see a way to do this explicitly - it only lets me wire up the webhook integration to the `crm-image` resource.

**Comment by manishas** [comment]
@trriplejay we need to look into this asap.

**Comment by manishas** [comment]
@BlueDragonX I dont know if it'll make a difference, but can you try fixing the indentation? 

```
integrations:
  notifications:
    - integrationName: trigger-crm-image
      type: webhook
      payload:
        - "versionName=$BRANCH.$BUILD_NUMBER"
      on_success: always
      on_failure: never
```
