### ISSUE TITLE
Pipelines: Manifest Fails During Validation

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2953]
## Problem
I'm manually (because #2948) kicking off my `location-http-develop` manifest job. It fails like this:

```
- Initializing Job
  + Getting system codes
  + Validating incoming message
  - Validating job dependencies
    stepExec|microWorker|_validateDependencies, location-image dependency has been deleted from the yml or has no versions
```

I am currently unable to deploy the `location-image`.

## Configuration
My `location-image` image resource looks like this:

```
- name: location-image
  type: image
  integration: ***
  pointer:
    sourceName: ***
  seed:
    versionName: latest
```

And my `location-http-develop` manifest job looks like this:

```
- name: location-http-develop
  type: manifest
  steps:
  - IN: location-image
    versionName: develop
  - IN: location-http-opts
```

## What I Want
I'm ultimatley trying to get a build of the `master` branch to trigger a deployment of the `latest` tag of `location-image` and a build of the `develop` branch to trigger a deployment of the `develop` tag of `location-image`. But barring that I expect a manual triggering of `location-http-latest` or `location-http-develop` to deploy their respective `location-image` tags.

Maybe I don't understand how versioning is supposed to work in this system. The documentation is maddeningly opaque on this topic. I'm hoping my call with @manishas will help enlighten me, but I politely request that you improve your documentation.

**Comment by manishas** [comment]
@BlueDragonX can you try indenting the job yml:

```
- name: location-http-develop
  type: manifest
  steps:
    - IN: location-image
    - IN: location-http-opts
```
