### ISSUE TITLE
ELB on AWS in new pipelines

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2955]
I am unable to see ELB attached to ECS service in amazon console. No errors in deploy script as well.

https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines/builds/57d683be7ce635100052b138/consoles

job definition:
```
jobs:
  - name: web-template-manifest
    type: manifest
    steps:
     - IN: web-template-image
     - TASK: managed

  - name: delivery-pipeline
    type: deploy
    steps:
      - IN: web-template-manifest
      - IN: docker-options
      - IN: devELB
        applyTo:
          - manifest: web-template-manifest
            image: web-template-image
            port: 80
      - IN: ecs-cluster
      - TASK: managed

```

and elb resource:
```

  - name: devELB
    type: loadBalancer
    pointer:
      sourceName: "dev-Trilogiq-ELB"
      method: classic
```
