### ISSUE TITLE
unable to add syncRepo

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2957]
Following piece of config in main repository:
```
  - name: connector-catalogue-repo
    type: syncRepo
    integration: GIT
    pointer:
      sourceName: "Trilogiq/connector-catalogue"
```

causes the pipeline to fail.

in the job i see:

`SyncRepo resource with name: connector-catalogue-repo could not be added from the YML due to non-allowable type`

link:
https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines/builds/57d6b63634e98910001bd77b/consoles

So how do i tie together more than one repository with resources and jobs??

My idea was to have a MAIN repo that defines the pipeline and common resources like load balancers etc. and then link specific repositories that do define only manifests and images. That manifest/images would be the used in the main pipeline. But apparently i miss something?
