### ISSUE TITLE
Pull an image from ECR

### ISSUE THREAD

**Issue by OdedArieli** [Shippable/support#2966]
Hi,

I'm trying to pull an image from ECR, but getting this error on docker run:
Unable to find image '317263640737.dkr.ecr.ap-southeast-1.amazonaws.com/web-ace:latest' locally
Pulling repository 317263640737.dkr.ecr.ap-southeast-1.amazonaws.com/web-ace
Authentication is required.

- Link to the build failure: https://app.shippable.com/runs/57d8cede4b15480e00c16260/1/console

I did my best to follow this doc:
http://docs.shippable.com/integrations/imageRegistries/ecr/

I created an integration of type "Amazon ECR" with my account's access key and secret access key, and linked it to my project (the same account that created the ECR repository).

My shippable.yml looks like:
build:
  pre_ci_boot:
    image_name: 317263640737.dkr.ecr.ap-southeast-1.amazonaws.com/web-ace
    image_tag: latest
    pull: true
    options: "-e HOME=/root"

  integrations:
    hub:
      - integrationName: ace-ecr
        type: ecr
        region: ap-southeast-1
        branches:
          only:
            - master

So I guess my integration doesn't work cause I'm not logged in to docker.
(My subscription integration and integrationName are equal)

Would appreciate any help!

**Comment by a-murphy** [comment]
Could you check the indentation in your shippable.yml file?  Your build isn't recognizing that there is a hub integration and this is often because of a mis-indented section.  The `integrations:` line should have the same indentation as `build:` and `hub:` should be indented one level from `integrations:`.  There have been cases where a mixture of spaces and tabs used to indent the file, resulting from copying and pasting sections, has caused the parsed YML to not match what it appears to be as well.

**Comment by manishas** [comment]
```
build:
  pre_ci_boot:
    image_name: 317263640737.dkr.ecr.ap-southeast-1.amazonaws.com/web-ace
    image_tag: latest
    pull: true
    options: "-e HOME=/root"

integrations:
  hub:
    - integrationName: ace-ecr
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master
```
