### ISSUE TITLE
Pipelines: Deploy Fails with ENOENT

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2967]
### Problem
I get this error:
![2016-09-14-181950_1428x593_scrot](https://cloud.githubusercontent.com/assets/465340/18535308/fccc42f8-7aa7-11e6-8b41-54399075d336.png)

### Configuration
The deploy job:
```
- name: zd
  type: deploy
  steps:
  - TASK: managed
    deployMethod: upgrade

  - IN: zd-uw2-ecs-services
  - IN: zd-params

  - IN: crm-develop
  - IN: crm-zd-elb
    applyTo:
    - manifest: crm-develop
      image: crm-image
      port: 80

  - IN: location-http-develop
  - IN: location-http-zd-elb
    applyTo:
    - manifest: location-http-develop
      image: location-image
      port: 80
```

The ECS cluster:
```
- name: zd-uw2-ecs-services
  type: cluster
  integration: ZD-ECS
  pointer:
    sourceName: ZD-UW2-ECS-Services
    region: us-west-2
```

The ZD-ECS integration does exist and has access.
