### ISSUE TITLE
Linux Alpine base image - Cannot start container

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#2971]
### Description of your issue:

Hi, I don't understand the origin of this problem https://app.shippable.com/runs/57dc0298cbc353100077f6f6/1/console, where the log says
```
echo 'Using jacopochevallard/beaglebaseimage:1.0 for the build'
Using jacopochevallard/beaglebaseimage:1.0 for the build

echo 'Booting job image jacopochevallard/beaglebaseimage:1.0'
Booting job image jacopochevallard/beaglebaseimage:1.0

sudo docker run -d                      --privileged=true --net=bridge           -v /home/shippable/cexec:/home/shippable/cexec -v /usr/bin/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock           --name=c.exec.test-shippable.16.1           --entrypoint=/home/shippable/cexec/build.sh           -e RUN_MODE=production           -e SHIPPABLE_API_URL=https://api.shippable.com           -e SHIPPABLE_API_RETRY_INTERVAL=3           -e SHIPPABLE_CONTAINER_NAME=c.exec.test-shippable.16.1           -e SHIPPABLE_IS_OFFICIAL_IMAGE=false           -e SHIPPABLE_IS_LEGACY_IMAGE=false           jacopochevallard/beaglebaseimage:1.0
1243eb636e506c232c5e8d2afe540b20917257847711ef788455dc935c0a2f0b
Error response from daemon: Cannot start container 1243eb636e506c232c5e8d2afe540b20917257847711ef788455dc935c0a2f0b: [8] System error: no such file or directory
```

Below the yml I'm using
```
language: none


integrations:                              
    hub:
      - integrationName: Docker-jc
        type: docker                        

branches:
  only:
    - master

compiler:
  - gcc

build:

  pre_ci_boot:
    image_name: jacopochevallard/beaglebaseimage
    image_tag: "1.0"
    pull: true                              #required, false if image already built or pulled in pre_ci
    #options:
    #env:

  ci:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_Fortran_COMPILER=gfortran ..
    - make
    - ./hello_world

  post_ci:
    - echo "true"
```
