### ISSUE TITLE
Pipelines: Force Deploy

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2977]
### Description of your issue:
When using the same container tag for a second deploy the deploy step does nothing. I would like to force the deploy to run every time.

I see there is a line in the deploy output that says "Force deployment is: false". That would imply that there is a way to force the deployment. Is there?

**Comment by manishas** [comment]
This is not implemented yet but is in our backlog. 
How critical is this for you?

Let me get back to you with an ETA.

**Comment by BlueDragonX** [comment]
Not critical at the moment. I'm getting around it by taking containers with a build number and running CI.

**Comment by trriplejay** [comment]
This feature is now available. Any manifest specified as an IN to a deploy job can be marked with `force: true` such that it will deploy every time the job is triggered, whether or not it has changed. Any manifest not marked with `force: true` will maintain the default behavior of deploying only when a change is detected (essentially `force: false`).

example yml:
```yml
  - name: box-tripub
    type: deploy
    steps:
      - IN: box-tripub-manifest
        force: true
      - IN: env-tripub
```
