### ISSUE TITLE
DryDock u14javall issue with apt-get update

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2983]
### Description of your issue:
We started facing issues with this image, our build do not move forward beyond this point. 

- https://app.shippable.com/runs/57e2a006930ea51000d8b120/1/console

``` build:
     pre_ci:
     pre_ci_boot:
         image_name: drydock/u14javall
         image_tag: prod
         pull: true
     ci:
         - apt-get update
         - apt-get install python-dev
         - pip install --upgrade botocore
```

**Comment by kqdtran** [comment]
Same. We're also having trouble with `apt-get update`. Here's what the beginning of our script looks like.
```
language: python

python:
  - 2.7

services:
  - postgres

build:
  cache: true
  ci:
    - shippable_retry sudo apt-get update
```
