### ISSUE TITLE
How do I use flags in the SPOG?

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#2989]
I see there is a filter that uses flags in the SPOG to be able to filter the view however the documentation does not really indicate how to do this other than indicating flags need to be included in jobs/resources options.

I did not see any example or format on how I can specific flags in a resource/job.

So, I do I do this?

thanks

**Comment by manishas** [comment]
@Kirtap it's undocumented because we're still tweaking it to be completely effective in filtering the right info... i.e. not showing too much or too little.

You can include the following in any job or resource definition:

```
jobs:
  - name: job_name
    type: job_type
    #other stuff for the job
    flags:
      - dv
```

```
resources:
  - name: resource_name
    type: resource_type
    #other stuff for the resource
    flags:
      - dv
```

You should be able to see the flag in the UI and filter based on that. Let us know how it goes.
