### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MaheshPesani** [Shippable/support#2991]
I am trying to build and deploy the first sample first pipeline code and getting the below error:

http://docs.shippable.com/tutorials/pipelines/samplePipeline/

Error: https://app.shippable.com/runs/57e4709abd5c050f0094c6b9/1/console
  echo 'CI Running' 0s  
  export IMAGE_NAME=maheshpesani/samplepipelinesdemo 0s  
  ./build.sh 0s  
/root/cad6e2d9-989f-4be6-90b0-be5fb5efadbd.sh: line 58: ./build.sh: Permission denied

**Comment by rageshkrishna** [comment]
This is probably caused by the `build.sh` file not having execute permission. Can you please add the permission with `chmod +x build.sh`? You can either commit this change to the repo, or add a step in your YML file to do this at run time.

**Comment by MaheshPesani** [comment]
the permission denied error is gone after changing to chmod +x build.sh in YML file, but the build.sh file scripts are not executing.

**Comment by trriplejay** [comment]
after the `chmod` command, you'll still need to have the `./build.sh` line to run the script. `chmod` is just changing the permission level of the file to allow it to be executed, then `./build.sh` will actually perform the execution.

**Comment by MaheshPesani** [comment]
well, it's not executing the build.sh file, i am hoping to see the "docker build" message from build.sh in the shippable build. But it's empy, not sure what's going on here.
build.sh:
#!/bin/bash -e
echo "docker build"

if [ "$IS_PULL_REQUEST" != true ]; then
  sudo docker build -t $IMAGE_NAME:$BRANCH.$BUILD_NUMBER .
else
  echo "skipping because it's a PR"
fi


Shippable.yml:
build:
  ci:
    - echo 'CI Running'
    - export IMAGE_NAME=maheshpesani/samplepipelinesdemo
    - chmod +x ./build.sh

  post_ci:
    - chmod +x ./push.sh

Build Output:
  build_ci 0s
  echo 'CI Running' 0s  
  export IMAGE_NAME=maheshpesani/samplepipelinesdemo 0s  
  chmod +x ./build.sh 0s

**Comment by MaheshPesani** [comment]
https://app.shippable.com/runs/57e5936696003f0f005363fe/1/console

**Comment by trriplejay** [comment]
actually it needs to be two separate commands. sorry for the confusion. It should look like this:
```yml
build:
  ci: 
    - echo 'CI Running'
    - export IMAGE_NAME=maheshpesani/samplepipelinesdemo
    - chmod +x build.sh  #make the file executable
    - ./build.sh  #execute the script
  post_ci:
    - chmod +x push.sh
    - ./push.sh
```
