### ISSUE TITLE
Builds report as failed while every build step seems to succeed

### ISSUE THREAD

**Issue by realAkhmed** [Shippable/support#3018]
### Description of your issue:

Hello, my builds seem to report as failed while every build step seems to succeed (green checkmark)
The link to the failing build is below. Tried it twice - both times the same result.

These are regular Docker-based builds.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/runs/57f44db96da7b40e005cdea3/1/console

- Scripts called from the yml (optional)

**Comment by kanthchandra** [comment]
Hi @realAkhmed I see that there are a couple of errors in setup ruby section of the console

```
  gem install bundler --no-ri --no-rdoc  
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - bad response Domain Not Found 500 (https://api.rubygems.org/specs.4.8.gz)
          Unable to download data from http://rubygems.org - bad response Domain Not Found 500 (http://api.rubygems.org/specs.4.8.gz)
```

**Comment by realAkhmed** [comment]
Thanks @kanthchandra .  This is very strange, I am not using `ruby`.

The file hasn't changed for months. It was working fine until a few days ago.
Below is my `shippable.yml` with all the information removed. From the logs it is clear that both `docker build` and `true` succeed.

```yaml
env:
  global:
    - secure: <SECURE_VALUE>

build:
    pre_ci:
        docker build --build-arg SOME_ARG=SOME_VALUE -t SOME_TAG .
    ci:
        true
```
