### ISSUE TITLE
Migration to Application Load Balancer

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#3027]
i had a perfectly fine working pipeline, after replacing ELB to ALB on AWS the deployment
https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines/builds/57f6752fa4b44e0f004ddf89/consoles
 fails with:
```
creating task definition
Executing deploy type: blueGreen
Finding IAM role for loadbalancer
creating service
  message: 'Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions.',
error creating serviceInvalidParameterException: Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions.
  code: 'InvalidParameterException',
{ [InvalidParameterException: Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions.]
  time: Thu Oct 06 2016 16:01:00 GMT+0000 (UTC),
  retryable: false,
  requestId: '130f7731-8bde-11e6-a396-9f14b3d1cee2',
  retryDelay: 44.04742543119937 }
  statusCode: 400,
Failed to deploy manifest for type: blueGreen
```
Load balancer resource definition
```
  - name: devELB
    type: loadBalancer
    pointer:
      sourceName: "arn:aws:elasticloadbalancing:eu-west-1:975150373617:loadbalancer/app/dev-Trilogiq-ALB/339640bb9aaf0027"
      method: application
```
So the question i have is are the roles, policies etc different for ALB?
If not that means my automated Terraform scripts did not connect sth correctly after infra teardown and rebuild.
Or might i declared the resource wrong ?
 Any advice ?
