### ISSUE TITLE
post_ci not executed on_failure

### ISSUE THREAD

**Issue by coco1979ka** [Shippable/support#3037]
If you define a yml file like:

```
build:
  pre_ci:
    - mkdir -p shippable/buildoutput
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
  ci:
    - gradle cobertura
    - grade assemble
  post_ci:
    - cp -r ./build/test-results/*.xml ./shippable/testresults
    - cp -r ./build/reports/cobertura/*.xml ./shippable/codecoverage
```

The reports are not copied because post_ci does not get executed. This is really weird because you would have to specify the same in on_success and on_failure
