### ISSUE TITLE
Shippable runSh job cannot pull image from AWS_ecs

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3038]
Hi guys,
I am new to Shippable CD pipeline setup, if you need more information based on my description below, please let me know. 

## Purpose:
I want a shippable runSh job to pull an image from aws and deploy it on Shippable node as an end-to-end test of my another web server which already deployed via Shippable CD. 

## Here is what I am doing:
An **e2etest-image** is defined in shippable resources yml file, 

resources:
  - name: e2etest-image  
    type: image  
    flags:  
      - staging  
    integration: <ec2 integration registry>  
    pointer:  
      sourceName: "location of the image in ec2"  
    seed:  
      versionName: latest  

and it is one of the IN in a runSh job. Like below:
jobs:
-   name: e2e-test  
    type: runSh  
    flags:  
      - staging  
    steps:  
      - IN: web-deploy-staging-ecs  
      - IN: **e2etest-image**  
      - TASK:  
            - script: docker images  
            - script: docker run <the image>  

After running this job, log saying there is no such images found locally and tried to pull from aws but failed. Does it mean the step "- IN: **e2etest-image**" don't really pull the image from AWS to the node?

Then, I wanted to try another way: adding "- script: ./IN/e2etest-img/integration.env" in the task to see if I can pull the image by using "docker pull " in the node, but couldn't get success neither. Because command "./IN/e2etest-img/integration.env" permission denied. 

Please let me know if I am even on the right path to debug this issue. Then, I can post detailed log to see what really happen to my environment. Thanks, appreciate.

**Comment by Neal910** [comment]
It might be a little similar to this one #2966, but his happened during CI, mine is in CD. And I have double check any indentation in my shippable.jobs.yml and shippable.resources.yml.

**Comment by a-murphy** [comment]
The images aren't pulled by default because in most cases the images aren't needed and just the names are used.  To pull the image, you'll have to log in to Docker first.  A `TASK` section like this should work (replacing "ecr-image" with your image resource name):
```YML
- TASK:
        - script: "apt-get install unzip jq"
        - script: 'curl -s "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
        - script: "unzip awscli-bundle.zip"
        - script: "./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
        - script: "chmod +x /build/IN/ecr-image/integration.env"
        - script: ". /build/IN/ecr-image/integration.env"
        - script: "dockerLogin=$(AWS_ACCESS_KEY_ID=$aws_access_key_id AWS_SECRET_ACCESS_KEY=$aws_secret_access_key aws ecr get-login --region us-west-2)"
        - script: "$dockerLogin"
        - script: "docker pull $(cat /build/IN/ecr-image/version.json | jq -r '.sourceName'):$(cat /build/IN/ecr-image/version.json | jq -r '.version.versionName')"
  ```
It'll install the AWS CLI, get the login command, log into Docker, and pull the image.
