### ISSUE TITLE
Run selenium tests in shippable

### ISSUE THREAD

**Issue by toshovski** [Shippable/support#3054]
I'm trying to run tests in shippable, but the [demo project](https://github.com/shippableSamples/sample_node_selenium) that i found is pretty old. I tried the u14nodall:tipp, but I receive the following error:

> echo "selenium will not be started because the binary was not found at /usr/local/selenium/selenium-server-standalone-2.52.0.jar."

What am I doing wrong? Is there a smaller image, because only the preparing of the image takes about 25 minutes, which is takes too long!

```
build_image: drydock/u14nodall:tip
language: node_js
node_js:
  - "6.7.0"
services:
  - selenium
addons:
  - firefox: "29.0"
build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
  pre_ci:
    - cd
    - mkdir -p shippable/buildoutput
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
  ci:
    - sudo npm install
    - export DISPLAY=:99.0
    - bower --allow-root install
    - xvfb-run --server-args="-ac" npm test
  post_ci:
  on_failure:
  on_success:
```
