### ISSUE TITLE
Can't copy file from mounted volume

### ISSUE THREAD

**Issue by billmccord** [Shippable/support#3057]
I'm attempting to use volume-from in order to mount a volume where I will store CI results. I got the idea from issue #2353. However, it doesn't seem to be working and it is probably because I'm doing something wrong. This is what the relevant portion of my shippable.yml file looks like:
```
build:
    pre_ci_boot:
        # Create a volume to store our test results
        options: -v /usr/src/fx-feed/shippable

    pre_ci:
      # Build the fx-feed container.
      - docker build -t $PROJECT_ID/$PROJECT_NAME .

    ci:
      # Run the tests / converage with the mounted volume.
      - docker run --rm --volumes-from $SHIPPABLE_CONTAINER_NAME $PROJECT_ID/$PROJECT_NAME mvn cobertura:cobertura
      # Copy results from volume to this directory so that it is visible to shippable.
      - cp -r /usr/src/fx-feed/shippable $SHIPPABLE_BUILD_DIR/shippable
```

So, essentially, I'm creating a volume that I expect to be at the following path inside of my container:
/usr/src/fx-feed/shippable

Then I attempt to copy the files from the volume directory to my build directory so that the shippable/testresults and shippable/codecoverage data will get seen by Shippable. The result is that there are no coverage or test results reported, see here:
https://app.shippable.com/runs/5805f847e8fe021000f9dd5b/1/coverage

I can confirm that when I run this locally on my machine with a regular volume like so, it works fine:
```
docker run --rm -v $(pwd)/shippable:/usr/src/fx-feed/shippable $PROJECT_ID/$PROJECT_NAME mvn cobertura:cobertura
```

Any idea what I might be doing wrong here?

Thank you!
