### ISSUE TITLE
Push to AWS ECR  - no basic auth credentials

### ISSUE THREAD

**Issue by nedyang** [Shippable/support#3082]
In my shippable, I configure the integration to AWS ECR with the Aws_access_key_id and Aws_secret_access_key copied from the IAM user created in AWS with the policy AmazonEC2ContainerRegistryFullAccess. But when I run the build, the error is,

`Post https://623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/v2/creditcard_server_dockerimg_rep/blobs/uploads/: no basic auth credentials`

My yml,

```
language: node_js

node_js:
  - 0.12

build:
  ci:
    - npm install server_app/new_app
  post_ci:
    #Commit the container only if you want all the artifacts from the CI step
    - docker commit $SHIPPABLE_CONTAINER_NAME 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      agent_only: true
      branches:
        only:
          - master      

```

Any idea?

Tks

**Comment by manishas** [comment]
Can you remove the agent_only: true from your
yml and try again?

**Comment by nedyang** [comment]
I move the docker push to the 'push' section, and my job is sucessful. However, when I am deploying the docker image, there is an error below. Any idea why "Container command '/home/shippable/cexec/build.sh' not found or does not exist"?

```
-------------------------------------
/var/log/docker
-------------------------------------
time="2016-10-27T08:21:48.700687890Z" level=info msg="Layer sha256:12bdabbe43302f26c564a1804a93dcb6335dcdcc2f48b6be14b80b94110d64e5 cleaned up" 
time="2016-10-27T08:21:55Z" level=error msg="containerd: start container" error="oci runtime error: exec: \"/home/shippable/cexec/build.sh\": stat /home/shippable/cexec/build.sh: no such file or directory" id=1a51236416122573e68964dbf3639c0a2015d70af2659f6d3388aacf2df36609 
time="2016-10-27T08:21:55.558293835Z" level=error msg="Handler for POST /v1.23/containers/1a51236416122573e68964dbf3639c0a2015d70af2659f6d3388aacf2df36609/start returned error: Container command '/home/shippable/cexec/build.sh' not found or does not exist." 
time="2016-10-27T08:33:42.983748640Z" level=info msg="Layer sha256:36f1bd8a2a48a87fe4e1a509a19eeed616c80cf7f2b465a5830870c6d426d841 cleaned up" 
time="2016-10-27T08:33:47Z" level=error msg="containerd: start container" error="oci runtime error: exec: \"/home/shippable/cexec/build.sh\": stat /home/shippable/cexec/build.sh: no such file or directory" id=ec28d6485fa827700216d920e3459e3e7664768fbd74631f474e1c59addabe49 
time="2016-10-27T08:33:47.610398162Z" level=error msg="Handler for POST /v1.23/containers/ec28d6485fa827700216d920e3459e3e7664768fbd74631f474e1c59addabe49/start returned error: Container command '/home/shippable/cexec/build.sh' not found or does not exist." 
```


My yml:

```
language: node_js

node_js:
  - 0.12

build:
  ci:
    - npm install server_app/new_app
  post_ci:
    #Commit the container only if you want all the artifacts from the CI step
    - docker commit $SHIPPABLE_CONTAINER_NAME 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

  push:
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master     
```
