### ISSUE TITLE
Push to Amazon ECR - Container command '/home/shippable/cexec/build.sh' not found or does not exist

### ISSUE THREAD

**Issue by nedyang** [Shippable/support#3085]
I set up shippable to grab the nodejs source code from bitbucket, dockerize it and push to Amazon ECR . 

Then AWS beanstalk is to pull the image and deploy.

Any idea why "Container command '/home/shippable/cexec/build.sh' not found or does not exist"?

```
-------------------------------------
/var/log/docker
-------------------------------------
time="2016-10-27T08:21:48.700687890Z" level=info msg="Layer sha256:12bdabbe43302f26c564a1804a93dcb6335dcdcc2f48b6be14b80b94110d64e5 cleaned up" 
time="2016-10-27T08:21:55Z" level=error msg="containerd: start container" error="oci runtime error: exec: \"/home/shippable/cexec/build.sh\": stat /home/shippable/cexec/build.sh: no such file or directory" id=1a51236416122573e68964dbf3639c0a2015d70af2659f6d3388aacf2df36609 
time="2016-10-27T08:21:55.558293835Z" level=error msg="Handler for POST /v1.23/containers/1a51236416122573e68964dbf3639c0a2015d70af2659f6d3388aacf2df36609/start returned error: Container command '/home/shippable/cexec/build.sh' not found or does not exist." 
time="2016-10-27T08:33:42.983748640Z" level=info msg="Layer sha256:36f1bd8a2a48a87fe4e1a509a19eeed616c80cf7f2b465a5830870c6d426d841 cleaned up" 
time="2016-10-27T08:33:47Z" level=error msg="containerd: start container" error="oci runtime error: exec: \"/home/shippable/cexec/build.sh\": stat /home/shippable/cexec/build.sh: no such file or directory" id=ec28d6485fa827700216d920e3459e3e7664768fbd74631f474e1c59addabe49 
time="2016-10-27T08:33:47.610398162Z" level=error msg="Handler for POST /v1.23/containers/ec28d6485fa827700216d920e3459e3e7664768fbd74631f474e1c59addabe49/start returned error: Container command '/home/shippable/cexec/build.sh' not found or does not exist." 
```

My yml:

```
language: node_js

node_js:
  - 0.12

build:
  pre_ci:
    - docker build -t creditcardserverimg .
  post_ci:
    #Commit the container only if you want all the artifacts from the CI step
    - docker commit $SHIPPABLE_CONTAINER_NAME 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

  push:
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master     
```

```
Dockerfile

FROM node:argon

ENTRYPOINT ["/bin/sh","-c"]

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

EXPOSE 8080
CMD [ "npm", "start" ]
```

I have also tried running local docker with the image created by shippable and running into the same issue. 

Pls help . this is a roadblock.

**Comment by nedyang** [comment]
I change the yml and same error. How can I use the standard docker build command instead of shippable's, which is not in the image?

```
language: node_js

node_js:
  - 0.12

build:
  pre_ci:
    - docker build -t creditcardserverimg .
  post_ci:
    #Commit the container only if you want all the artifacts from the CI step
    - docker commit $SHIPPABLE_CONTAINER_NAME 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

  push:
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master   
```

**Comment by a-murphy** [comment]
It looks like you're pushing an image of the Shippable build container instead of the image you built.  (And you'll see that error with the Shippable image unless you override the entrypoint when you run it.)  The simplest way to push your image is to tag it with the name that you intend to push when you build it.  So your shippable.yml would be something like this:
```YML
language: node_js

node_js:
  - 0.12

build:
  pre_ci:
    - docker build -t 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest .

  push:
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master     
```

**Comment by Nedvedyy** [comment]
Thanks for the reply. I updated the Yammer to ,

```
language: node_js

node_js:
  - 0.12

build:
  pre_ci:
    - docker build -t 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest .
  post_ci:
    #Commit the container only if you want all the artifacts from the CI step
    - docker commit $SHIPPABLE_CONTAINER_NAME 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

  push:
    - docker push 623575552266.dkr.ecr.ap-southeast-1.amazonaws.com/creditcard_server_dockerimg_rep:latest

integrations:
  hub:
    - integrationName: amazonECR
      type: ecr
      region: ap-southeast-1
      branches:
        only:
          - master   
```

Same error

```
-------------------------------------
/var/log/docker
-------------------------------------
time="2016-10-29T15:26:45.217123930Z" level=info msg="Layer sha256:dd767c28caadc38a800427336537eee86b01148dba9b72dcd5699ab586881e16 cleaned up" 
time="2016-10-29T15:26:51Z" level=error msg="containerd: start container" error="oci runtime error: exec: \"/home/shippable/cexec/build.sh\": stat /home/shippable/cexec/build.sh: no such file or directory" id=7a2d7d71ce051909906998b335384146adc1899dac1d817d11d992c2063b5412 
time="2016-10-29T15:26:51.894357530Z" level=error msg="Handler for POST /v1.23/containers/7a2d7d71ce051909906998b335384146adc1899dac1d817d11d992c2063b5412/start returned error: Container command '/home/shippable/cexec/build.sh' not found or does not exist." 
```

Any idea?
