### ISSUE TITLE
Connect AWS ECS Data Volume when deploying the container

### ISSUE THREAD

**Issue by Zingoer** [Shippable/support#3087]
Thank's for making this great CI/CD platform first!

I'm new to the AWS and Shippable and have multiple questions relating to this topic.

### Background
I want to deploy my postgres server into a container on my AWS ECS and link other microservices with that. Because the container is ephemeral, according to the [docker tutorial](https://docs.docker.com/engine/tutorials/dockervolumes/#/creating-and-mounting-a-data-volume-container), if I want to persistent and share data between containers, the best practice is using the Data Volume Container. To achieve that, in docker it usually need these two lines code:
``` bash
docker create -v /dbdata --name -dbstore postgres /bin/true
docker run -d --volumes-from dbstore --name db1 postgres
```
Then according to the [AWS ECS Document](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html), usually if I want to manually create a task which can mount a volumes for a containers, the volumes section and mountPoints section will have some settings.

### YML Files
``` yml
resources:

# Resources for deploying database to staging and then production on demand

# Postgres db docker image
  - name: db-image
    type: image
    flags:
      - staging
      - db
    integration: ec2_container_registry
    pointer:
      sourceName: "...some amazon private repo..."
    seed:
      versionName: latest

# Postgres dbstore docker image
  - name: dbstore-image
    type: image
    flags:
      - staging
      - db
    integration: ec2_container_registry
    pointer:
      sourceName: "...some amazon private repo..."
    seed:
      versionName: latest

# Postgres dbstore docker options
  - name: dbstore-dockeropt-staging
    type: dockerOptions
    flags:
      - staging
      - db
    version:
        portMappings:
          - 5432:5432
        volumes:
          - "dev/sdb/dbdata"
        entrypoint:
          - /bin/true

# Postgres database docker options
  - name: postgresdb-dockeropt-staging
    type: dockerOptions
    flags:
      - staging
      - db
    version:
        portMappings:
          - 5432:5432
        volumesFrom:
          - "dbstore-image"
```
``` yml
jobs:

# jobs for deploying database to staging and then production on demand

# manifest for database data volume container staging
  - name: dbstore-man-staging
    type: manifest
    flags:
      - staging
      - db
    steps:
      - IN: dbstore-image
      - IN: dbstore-dockeropt-staging
      - TASK: managed

# manifest for postgres database staging
  - name: db-man-staging
    type: manifest
    flags:
      - staging
      - db
    steps:
      - IN: db-image
      - IN: postgresdb-dockeropt-staging
      - TASK: managed

# Deploy database data volume container to the staging area (in ECS)
  - name: dbstore-deploy-staging-ecs
    type: deploy
    flags:
      - staging
      - db
    on_success:
      - NOTIFY: shippable-slack-staging
    on_failure:
      - NOTIFY: shippable-slack-staging
    steps:
      - IN: dbstore-man-staging
      - IN: env-staging-ecs
      - TASK: managed
        deployMethod: replace

# Deploy postgres database to the staging area (in ECS)
  - name: db-deploy-staging-ecs
    type: deploy
    flags:
      - staging
      - db
    on_success:
      - NOTIFY: shippable-slack-staging
    on_failure:
      - NOTIFY: shippable-slack-staging
    steps:
      - IN: db-man-staging
      - IN: env-staging-ecs
      - TASK: managed
        deployMethod: replace
```

### My Problems

1. I check most of the similar questions in support issues like #2353, #2840, #3057, they all mentioned that how to mount a volume in CI build. But I want to achieve that in the deployment. I don't think I have any CI involved for the database because I directly use the postgres image and upload it to a private repo for creating container. **So I just write deployment resource and job yml, Do I get wrong from the beginning? Do I have to write a CI shippable.yml?**

2. **how should I use the "volumes" in the dockerOptions?** I tried `"/dbdata"`, `"dbdata"`, `"/dev/sdb/dbdata"` (BTW, /dev/sdb is the path showing in AWS that the extra storage/Block device I'm using) , none of them works. Even the dbstore-man-staging ---- dbstore-deploy-staging-ecs in pipeline runs correctly which also create a task definition and task in the AWS ECS. But when I check the task JSON, the "volumes" section is empty (```"volumes": []```). So I assume that I make the run implementation somewhere?

3.  **How to use the "volumesFrom" in the dockerOptions? especially the <container name>** I saw in one issue saying that the container name is same as the image name. In my case is it "db-image" and "dbstore-image"? How can I figure it out the container name if I want to mount the dbstore into db? If you can improve your document and explain that, that would be helpful for future developers.

4.  **Do I actually use the wrong jobs? Should I use runSh to customze all of these?**

Thanks for looking at this long issue!
