### ISSUE TITLE
Unable to copy config/database.shippable.yml file

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3088]
### Description of your issue:
Unable to copy the config/database.shippable.yml file.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/runs/5814d4a9133af40e000040d6/1/console
- Scripts called from the yml (optional)
```yml
language: ruby
rvm:
  - 2.3.0

services:
  - postgres

build:
  pre_ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - pwd
    - cp config/database.shippable.yml config/database.yml
    - bundle install
    - bundle exec rake db:setup
    - bundle exec rake
```
