### ISSUE TITLE
PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3089]
### Description of your issue:

PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)

NOTE: If you are experiencing a build failure, please include:
- Link to the build failure
  https://app.shippable.com/runs/5814dfb7a7de2f100059c1dd/1/console
- Scripts called from the yml (optional)

``` yml
language: ruby
rvm:
  - 2.3.0

services:
  - postgres

build:
  pre_ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - pwd
    - cp config/database.shippable.yml config/database.yml
    - bundle install
    - bundle exec rake db:setup
    - bundle exec rake
```

**Comment by vittorius** [comment]
@magicalbanana creating the DB manually has helped me to solve similar problem:

```yaml
build:
  ci:
    - psql -c "CREATE DATABASE shippable ENCODING 'UTF-8' TEMPLATE template0" -U postgres;
```
