### ISSUE TITLE
Include logs of failed build inside email notification?

### ISSUE THREAD

**Issue by toogley** [Shippable/support#3091]
Hello.

Ideally, I'd like to receive an email with the complete log file (= the one which is showed inside the build status of every  build). I've read already the [documentation page](http://docs.shippable.com/integrations/notifications/email/) for mail notifications, but I didn't found sth suitable.
- Did i overlook sth?
- If not, I want to make a feature request for that.

regards.

**Comment by deepikasl** [comment]
@toogley this is now in production. If you want console logs attached to your build report email. Please add `sendConsoleLogs: true` in email integration under notification section, like this: 

```yaml
integrations:
  notifications:  
    - integrationName: email
      type: email
      recipients: 
        - deepika@shippable.com
      sendConsoleLogs: true
```
You can also refer here: [notifications-email](http://docs.shippable.com/integrations/notifications/email/).

Closing, as it is done.
