### ISSUE TITLE
AWS Creds in CI

### ISSUE THREAD

**Issue by jessica-pixvana** [Shippable/support#3099]
I'd like to push artifacts to S3 in on_success section. AWS credentials are configured in Account Settings -> Integrations section.

I tried adding this to my shippable.yml but looks like it is trying to deploy to ebs:
```
 on_success:
    - aws s3 cp $SHIPPABLE_BUILD_DIR/myjar.jar "s3://mybucket/myjar.jar" --region "us-west-2

integrations:
  deploy:
    - integrationName: aws-builder-creds
      type: aws
```
