### ISSUE TITLE
Slack notification doesn't work

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#3142]
The slack notification for my new repo does not work. The other notifications for other repos are working well.

Log: https://app.shippable.com/runs/58241b7beb90dd1000da1d99/1/console

```
  notifications:
    - integrationName: "Shippable-Slack-Yamizaka"
      type: slack
      recipients:
          - "#deploy-yamizaka"
      on_success: always
      on_failure: always
      on_start: always
```
