### ISSUE TITLE
Pipelines: What's a Trigger and How Does It Work?

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3156]
### Description of your issue:
The documentation is not very clear about what a trigger is for and how it works. My assumption is that it's used to trigger other jobs, but I don't understand how to trigger the trigger.

I've attempted to create a trigger which itself triggers all of the production release jobs I have defined in my pipeline. That way I can trigger a full prod release. But in the SPOG there's no "Run" button on the trigger as there is with the release jobs.

So how do I use it?

**Comment by trriplejay** [comment]
Currently the only way to set off a trigger is to update its version section in your shippable.triggers.yml file.  It doesn't actually matter what you update it with, as long as it has changed.

for example:
```yml
  - name: prodDeployTrigger
    type: trigger
    version:
      message: 'deploying version 101'
```

then later you want to trigger again, you might update your yml with:
```yml
  - name: prodDeployTrigger
    type: trigger
    version:
      message: 'deploying version 105'
```
(note: it doesn't have to say `message`, you can put any yml object you want in there)

Shippable will detect that a change was made to your trigger's version section, and as a result it will trigger anything that it's connected to.

We're hoping to implement other methods of setting these off in the future, but for now, that's how it is done.
