### ISSUE TITLE
EB deploy triggered from within container, before image is pushed.

### ISSUE THREAD

**Issue by antoligy** [Shippable/support#3160]
### Description of your issue:
Hey, my Elastic Beanstalk deploy is triggered before my push step, and by the looks of it this seems to happen from within my container - so the EB deployment fails as the integration isn't available there.
Is there any way around this, or have I simply misconfigured something here?

Link to build: https://app.shippable.com/runs/5829dfbb7432da0f007348aa/1/console

```
language: php

php:
  - 7

env:
  global:
    - SERVICE=foobar
    - REGISTRY_ACCOUNT=foobar.amazonaws.com

build:

  pre_ci:
      - docker build -t "$REGISTRY_ACCOUNT/$SERVICE:$BRANCH.$BUILD_NUMBER" .

  pre_ci_boot:
    image_name: "$REGISTRY_ACCOUNT/$SERVICE"
    image_tag: "$BRANCH.$BUILD_NUMBER"
    pull: false

  ci:
    - echo 'CI is running'

  post_ci:
    - apt-get -y install python-pip

  push:
    - docker push "$REGISTRY_ACCOUNT/$SERVICE:$BRANCH.$BUILD_NUMBER"

integrations:
  deploy:
    - integrationName: "aws"
      type: aws
      target: eb_docker
      application_name: "$SERVICE"
      env_name: "$SERVICE-dev"
      region: "eu-west-1"
      image_name: "$SERVICE"
      image_tag: "$BRANCH.$BUILD_NUMBER"

  hub:
    - integrationName: "aws-ecr"
      type: "ecr"
      region: "eu-west-1"
      agent_only: true

branches:
  except:
    - "*/*"
```
