### ISSUE TITLE
Content-type is text/html; charset=utf-8 while trying to get yml at shippable.yml

### ISSUE THREAD

**Issue by tapina** [Shippable/support#3163]
### Description of your issue:
Can't get our project to build because of the above error. This has previously built OK (last successful build 3 Nov, two failed builds today).

- Link to the build failure
https://app.shippable.com/runs/582a60cfdeeed00f00f6b74f

- Scripts called from the yml (optional)

**Comment by tapina** [comment]
This is the shippable.yml

```
language: java
jdk:
  - oraclejdk8
services:
  - mongodb
env:
  global:
    # AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY
    - secure: (REDACTED)
build:
  ci:
    - mkdir -p shippable/testresults
    - mvn clean
    - mvn -Pshippable deploy

integrations:
  notifications:
    - integrationName: hipchat
      type: hipchat
      recipients:
        - '#Everyone'
      branches:
        only:
          - master
```
