### ISSUE TITLE
Firefox Build for Selenium tests

### ISSUE THREAD

**Issue by popelnuh** [Shippable/support#3174]
Hi, 

I am getting an error when trying to run Selenium tests on Firefox. It seems that the Firefox build fails. 

The tests run locally (FF 46 & Selenium 2.53.6). The errors start about 2 days ago.  The tests have always been running on Firefox 46. 

What I have tried to do:
•	changing Firefox versions to 47, 48, 49, 45 but no success
•	increasing implicit wait time for before_scenario (Selenium) up to 30 seconds

Error message:

`Exception WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpnxso6xlh If you specified a log_file in the FirefoxBinary constructor, check it for details. Traceback (most recent call last): File "/root/venv/3.5/bin/behave", line 11, in <module> sys.exit(main()) File "/root/venv/3.5/lib/python3.5/site-packages/behave/__main__.py", line 109, in main failed = runner.run() File "/root/venv/3.5/lib/python3.5/site-packages/behave/runner.py", line 672, in run return self.run_with_paths() File "/root/venv/3.5/lib/python3.5/site-packages/behave/runner.py", line 693, in run_with_paths return self.run_model() File "/root/venv/3.5/lib/python3.5/site-packages/behave/runner.py", line 483, in run_model failed = feature.run(self) File "/root/venv/3.5/lib/python3.5/site-packages/behave/model.py", line 523, in run failed = scenario.run(runner) File "/root/venv/3.5/lib/python3.5/site-packages/behave/model.py", line 867, in run runner.run_hook('before_scenario', runner.context, self) File "/root/venv/3.5/lib/python3.5/site-packages/behave/runner.py", line 405, in run_hook self.hooks[name](context, *args) File "tests/behave/environment.py", line 18, in before_scenario context.browser = webdriver.Firefox() File "/root/venv/3.5/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__ self.binary, timeout) File "/root/venv/3.5/lib/python3.5/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__ self.binary.launch_browser(self.profile, timeout=timeout) File "/root/venv/3.5/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser self._wait_until_connectable(timeout=timeout) File "/root/venv/3.5/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable % (self.profile.path)) selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpnxso6xlh If you specified a log_file in the FirefoxBinary constructor, check it for details.`

Shippable.yml:

`
```
# language setting
language: python

# version numbers
python:
    - "3.5"

env:
  - ENV=Staging

build:
    before_script:
        # Set env variable for display
        - "export DISPLAY=:99.0"
    ci:
        # Build Client Install
        - apt-get update
        - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -  # Ensure we pull node 4
        - apt-get install nodejs
        - node --version
        - cd client
        - npm install
        - ./node_modules/.bin/gulp build-staging
        - mkdir -p shippable/testresults

        # Build Python Install
        - cd ..
        - python --version
        - pip install -r requirements.txt

        # Python Unit tests
        - nosetests ./tests/server/unit --with-xunit --xunit-file ./shippable/testresults/unitresults.xml --with-coverage --cover-erase --cover-package=./server
        - coverage xml -o shippable/codecoverage/coverage.xml

        # JS Unit Tests
        - cd tests/client
        - ../../client/node_modules/.bin/karma start --single-run --browsers PhantomJS --reporters junit
        - cd ../..

    on_success:
        # Run deploy script to manage deploy to appropriate environment
        - . ./bin/linux/deploy.sh
        # Run integration tests post deploy to check nothing has broken
        - . ./bin/linux/integration-test.sh


addons:
  firefox: "46.0"

services:
  - selenium
```
`
- Link to the build failure: https://app.shippable.com/runs/582dbcf14dac720f008c491e/1/console

**Comment by popelnuh** [comment]
The build is now successful. I have changed shippable.yml (see below) - I don't think that's what fixed it, though, as the build and tests run successfully in another project with the old .yml.

The case can be closed :)

```
# language setting
language: python

# version numbers
python:
    - "3.5"

addons:
  firefox: "46.0"

services:
  - selenium

env:
  - BRITISH_LIBRARY_ENV=Staging

build:
    ci:
        # Build Client Install
        - apt-get update
        - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -  # Ensure we pull node 4
        - apt-get install nodejs
        - node --version
        - cd client
        - npm install
        - ./node_modules/.bin/gulp build-staging
        - mkdir -p shippable/testresults

        # Set env variable for display
        - "export DISPLAY=:99.0"
        # Build Python Install
        - cd ..
        - python --version
        - pip install -r requirements.txt

        # Python Unit tests
        - nosetests ./tests/server/unit --with-xunit --xunit-file ./shippable/testresults/unitresults.xml --with-coverage --cover-erase --cover-package=./server
        - coverage xml -o shippable/codecoverage/coverage.xml

        # JS Unit Tests
        - cd tests/client
        - ../../client/node_modules/.bin/karma start --single-run --browsers PhantomJS --reporters junit
        - cd ../..

    on_success:
        # Run deploy script to manage deploy to appropriate environment
        - . ./bin/linux/deploy.sh
        # Run integration tests post deploy to check nothing has broken
        - . ./bin/linux/integration-test.sh
```
