### ISSUE TITLE
Pipeline AWS elastic beanstalk 

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#3218]
WE are looking at using pipelines to support our CI/CD process flow. We already use shippable CI for our builds on AWS elastic beanstalk.

Just wanted to know if pipelines provides support for Elastic beanstalk deployments

**Comment by sheldon-sminq** [comment]
```
 - name: env-test-ecs
    type: cluster
    integration: demo-manishas-ecs
    pointer:
      sourceName : "demo-shippable-ecs-test"
      region: "us-east-1"
```

Is it possible to connect to Elastic beanstalk integration here, we do not use ECS.

**Comment by manishas** [comment]
@sheldon-sminq Elastic beanstalk isn't supported as a managed job today but this is on our radar since its come up a few times. 

You could hook it up using the generic runSh job and provide the scripts to deploy to beanstalk, though we do not have a sample for this at the moment. @trriplejay can provide some ideas around how to do it. 

I'm marking this as a feature request to add a managed job.

**Comment by sheldon-sminq** [comment]
@manishas @trriplejay i assumed runSh job will help with this, but could not figure it out from the documentation. Any ideas would be of great help.

**Comment by trriplejay** [comment]
so I'll assume you're building your image and pushing it in CI. If that's the case, then i recommend mostly following this tutorial: http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/

The difference is that your image resource will be the input to a runSh job (instead of a manifest job).

You should also add a resource of type 'integration' ( http://docs.shippable.com/pipelines/resources/integration/ ), which is just a simple way of including some credentials in the job. You can reference the same subscriptionIntegration that you're using to push to beanstalk via CI.

You should also add your repo as a gitRepo resource, so that you have access to your Dockerrun.aws.json file and can run a deploy via the amazon cli.

So, your runSh job will have both of these resources as input. Then you just need to write a few script steps to perform the actual update of your beanstalk environment

```yml
jobs:
  - name: deploy-to-beanstalk
    type: runSh
    steps:
      - IN: myImage
      - IN: myEcsIntegration
      - IN: myRepo
        switch: off
      - TASK:
        - script: source IN/myEcsIntegration/integration.env # add the credentials to the environment
        - script: # install aws cli and/or ebcli and run config, using the credentials
        - script: # look for the version.json in the IN/myImage for info on which image tag to use
        - script: # update the Dockerrun.aws.json with the latest image tag that was pushed
        - script: # run eb deploy
```

We're working on improving this process to involve fewer manual steps like this, but for now I think this is the best way to accomplish a beanstalk deploy via runSh.

Some information on how to use integrations and other resources with runSh jobs can be found here as well: http://docs.shippable.com/pipelines/jobs/runSh/

Let me know if you have more specific questions along the way!

**Comment by sheldon-sminq** [comment]
@trriplejay thanks for the details will get started with this on my end, if i come across any issue will get back.

**Comment by sheldon-sminq** [comment]
I have attached the sample sync repo yml files, also added the trigger integration within by CI repo

```
integrations:
     hub:
         - integrationName: "Docker hub"
           type: docker

 integrations:
   notifications:
     - integrationName: sminq-pipeline-trigger #Replace with name of the integration from subscription settings
     type: webhook
     payload:
       - versionName=$BRANCH.$BUILD_NUMBER  #Replace with the tag of the image you pushed during CI
     on_success: always
     on_failure: never
```

resources.yml

```
resources:

# resources for the dv demo pipelines from CI thru TEST environment

#######1: Create DV pipeline

# Docker Image for VISUALIZER
  - name: sminq-api
    type: image
    integration: "Docker hub"
    pointer:
      sourceName: "sminq/baseimage"
      isPull: false
    #make sure this seed version exists in your registry account
    seed:
      versionName: master.1

# Docker Image Options for VISUALIZER
  - name: sminq-image-opts
    type: dockerOptions
    version:
      portMappings:
        - 80:80
      publishAllPorts : true
```

jobs.yml

```
jobs:
# TEST deployment for VISUALIZER to Amazon ECS
  - name: deploy-to-beanstalk
    type: runSh
    steps:
      - IN: sminq-api
      - IN: sminq-aws
      - IN: sminq-pipeline
        switch: off
      - TASK:
        - script: source IN/sminq-aws/integration.env # add the credentials to the environment
        - script: pip install awscli # install aws cli and/or ebcli and run config, using the credentials
        - script: # look for the version.json in the IN/myImage for info on which image tag to use
        - script: mv Dockerrun.aws.json /tmp/Dockerrun.tmp # update the Dockerrun.aws.json with the latest image tag that was pushed
        - script: cat /tmp/Dockerrun.tmp | sed 's/<IMAGE_NAME>/sminq\/baseimage/' | sed 's/<TAG>/api2.0.6.2146/' | sed 's/<DOCKER_CONFIG>//' | sed 's/<BUCKET_NAME>/elasticbeanstalk-ap-south-1-288789354248/' > Dockerrun.aws.json
        - script: echo | eb init "sminq-api-staging" -r "ap-south-1" -p "64bit Amazon Linux 2016.09 v2.2.0 running Docker 1.11.2" # run eb deploy
        - script: eb use "sminq-api-staging"
        - script: eb deploy --staged -l shippable.sminq-https.api2.0.6.2146
```

trigger.yml

```
triggers:
  - name: sminq-trigger
    type: trigger
    version:
      counter: 1
```

Question: in the jobs section, what is the format of the version.json file? how do i read the values from that file?

**Comment by trriplejay** [comment]
I got this working today. here's the yml I used:

shippable.resources.yml
```yml
resources:

  - name: simple-image-eb
    type: image
    flags:
      - eb
    pointer:
      sourceName: "trriplejay/simpleserver"
    seed:
      versionName: master.58

  - name: myAwsCredentials
    type: integration
    integration: "trriplejay-aws"

  - name: simple-repo-eb
    type: gitRepo
    integration: "trriplejay github"
    flags:
      - eb
    pointer:
      sourceName: trriplejay/simpleserver
      branch: master

```

shippable.jobs.yml

```yml
jobs:
  - name: deploy-simpleEbApp-eb
    type: runSh
    flags:
      - eb
    steps:
      - IN: myAwsCredentials
      - IN: simple-repo-eb
        switch: off
      - IN: simple-image-eb
      - TASK:
        - script: ./IN/simple-repo-eb/gitRepo/deployToEb.sh
```

then, in my gitRepo that I wanted to deploy, I wrote a script to handle the rest of the logic.  This could also be done in the runSh `- script: ` sections themselves, but I found it easier this way:

deployToEb.sh:
```sh
#!/bin/bash

install_requirements() {
  sudo apt-get install -y jq
  pip install awscli
  aws --version
  pip install awsebcli==3.7.8
  eb --version
}

setup_env() {
  source IN/myAwsCredentials/integration.env

  export AWS_EB_APPLICATION_NAME="simple-eb-app" #application should already be created on aws
  export AWS_EB_ENVIRONMENT_NAME="simpleEbApp-env" #environment should already exist on aws
  export AWS_EB_REGION="us-west-2" #region that the app/env are in
  export AWS_EB_IMAGE_NAME="$(jq -r '.sourceName' IN/simple-image-eb/version.json)"
  export AWS_EB_IMAGE_NAME_ESCAPED=$(echo "$AWS_EB_IMAGE_NAME" | sed -e 's/\//\\\//g')
  export AWS_EB_IMAGE_TAG="$(jq -r '.version.versionName' IN/simple-image-eb/version.json)"
  export AWS_EB_VERSION_LABEL="shippable.$AWS_EB_ENVIRONMENT_NAME.$AWS_EB_IMAGE_TAG" #unique label

}

configure_aws() {
  # these values were added to the env in setup_env
  aws configure set aws_access_key_id $aws_access_key_id
  aws configure set aws_secret_access_key $aws_secret_access_key
  aws configure set region us-west-2
}

deploy_to_eb() {
  export DOCKERRUN_PATH=IN/simple-repo-eb/gitRepo/
  pushd $DOCKERRUN_PATH
  echo "deploying $AWS_EB_IMAGE_NAME:$AWS_EB_IMAGE_TAG to beanstalk"
  mv Dockerrun.aws.json /tmp/Dockerrun.tmp
  cat /tmp/Dockerrun.tmp | sed 's/<IMAGE_NAME>/'$AWS_EB_IMAGE_NAME_ESCAPED'/' | sed 's/<TAG>/'$AWS_EB_IMAGE_TAG'/' > Dockerrun.aws.json

  echo | eb init "$AWS_EB_APPLICATION_NAME" -r "$AWS_EB_REGION"
  eb use "$AWS_EB_ENVIRONMENT_NAME"

  git add -A
  eb deploy --staged -l $AWS_EB_VERSION_LABEL
  popd
}


install_requirements
setup_env
configure_aws
deploy_to_eb

```

make sure the application and the environment already exist.

I connected the CI job to the runSh job via evenTrigger as described in the example.

**Comment by sheldon-sminq** [comment]
@trriplejay thanks for the detailed example, will try it out today.

**Comment by sheldon-sminq** [comment]
@trriplejay do you have a separate sync repo? or these pipeline config files are in the same code repo as you app?

**Comment by sheldon-sminq** [comment]
I have followed your scripts, now when the sync repo parses the resources file it gives an error

```
Invalid integration Sminq Api for resource sminq-platform-repo
```
Resources config
```
resources:

  - name: sminq-platform-image
    type: image
    flags:
      - eb
    pointer:
      sourceName: "sminq/baseimage"
    seed:
      versionName: master.1

  - name: AwsCredentials
    type: integration
    integration: "sminq-aws"

  - name: sminq-platform-repo
    type: gitRepo
    integration: "Sminq Api"
    flags:
      - eb
    pointer:
      sourceName: sminq/api
      branch: api2.0.8
```
