### ISSUE TITLE
How to apply Shippable.yml conditional statement to pre_ci_boot & ci sections

### ISSUE THREAD

**Issue by desoukya** [Shippable/support#3224]
Please see image:
 
<img width="1284" alt="screen shot 2016-12-09 at 10 11 03 am" src="https://cloud.githubusercontent.com/assets/10380913/21053536/db20ffc0-bdf7-11e6-9329-b0a0b745fa64.png">

I want my conditional to determine which ECR Docker Image to pull depending on the branch. Additionally, I would like a similar conditional to determine which type of build task I should perform when building the app. 

The issue is the `before_script` does not seem to trigger prior to the `build` section, which always results in shippable using the initial values I've assigned to my environment variables for the build.

Any thoughts?

**Comment by cratz** [comment]
@desoukya 
looks like you just missed `export` 
`.... ; then export IMAGE_TAG="1.0.0" ; else export IMAGE_TAG="dev" ; fi`

**Comment by desoukya** [comment]
thanks @cratz, I've updated my file to reflect your comments. Although it seems the `pull_job_image` task is still running prior to my conditional statements, which seem to execute inside the `build_ci` task - see image below:

<img width="1426" alt="screen shot 2016-12-09 at 10 32 42 am" src="https://cloud.githubusercontent.com/assets/10380913/21054320/331c71f2-bdfb-11e6-8f37-2e70e49f3895.png">

**Comment by manishas** [comment]
@desoukya you need to adjust the structure of your yml... you're mixing up legacy tags (before_script) and current tags (ci, pre_ci_boot, etc)

```

build:
  pre_ci:
    #conditional statements
  pre_ci_boot:
  ci:

```

Please check the structure described at http://docs.shippable.com/ci/shippableyml/

**Comment by desoukya** [comment]
@manishas thank you for clarifying the issue with my yml file; I have since rectified the issue to correctly reflect the structure outlined in your post. Although unfortunately, I have noticed the issue still exists - see image below:

<img width="1426" alt="screen shot 2016-12-09 at 1 03 20 pm" src="https://cloud.githubusercontent.com/assets/10380913/21061238/73f12a7e-be19-11e6-8f99-afa3ab839ef2.png">


Moreover, notice the `git_sync` task now runs twice, adding roughly an additional 2 minutes to the build time.

**Comment by manishas** [comment]
@desoukya can you share your yml file and also a link to your build? We need to take a deeper look at this.

**Comment by desoukya** [comment]
@manishas as per your request:
[shippable build](https://app.shippable.com/runs/584aef2c307b1f0f00504fe7/1/console)
yml file:
```
language: none

branches:
  only:
    - develop
    - master
    - staging

cache: true

env:
  global:
    - IMAGE_TAG=dev
    - BUILD_TASK=test

build:
  pre_ci:
    - if [ "$BRANCH" == "master" ] || [ "$BRANCH" == "staging" ] || [ "$BRANCH" == "develop" ] ; then export IMAGE_TAG="1.0.0" ; else export IMAGE_TAG="dev" ; fi
    - if [ "$BRANCH" == "master" ] || [ "$BRANCH" == "staging" ] || [ "$BRANCH" == "develop" ] ; then export BUILD_TASK="build" ; else export BUILD_TASK="test" ; fi
    - echo $IMAGE_TAG
    - echo $BUILD_TASK

  pre_ci_boot:
    image_name: 0000000000000000.dkr.ecr.us-east-1.amazonaws.com/kl
    image_tag: $IMAGE_TAG
    pull: true
    options: "-e HOME=/root"

  ci:
    - npm install
    - npm run $BUILD_TASK

integrations:
  hub:
    - integrationName: ecr-integration
      type: ecr
      region: us-east-1

  notifications:
    - integrationName: slack-integration
      type: slack
      recipients:
        - "#ci-builds"
        - "#engineering"
      branches:
        only:
          - develop
          - master
          - staging
      on_success: always
      on_failure: always
      on_start: always    
```

**Comment by manishas** [comment]
@a-murphy can you look into this? I could repro this quite easily.

**Comment by manishas** [comment]
@desoukya there seems to be an issue at our end where we're not persisting the env variables across `pre_ci` and `pre_ci_boot`. We're investigating how to fix this.

In the meantime, I can suggest a workaround where you pull the docker image and retag it and then use that tag to pull during `pre_ci_boot` :

```

build:
  pre_ci:
    - if [ "$BRANCH" == "master" ] || [ "$BRANCH" == "staging" ] || [ "$BRANCH" == "develop" ] ; then export IMAGE_TAG="1.0.0" ; else export IMAGE_TAG="dev" ; fi
    - if [ "$BRANCH" == "master" ] || [ "$BRANCH" == "staging" ] || [ "$BRANCH" == "develop" ] ; then export BUILD_TASK="build" ; else export BUILD_TASK="test" ; fi
    - echo $IMAGE_TAG
    - echo $BUILD_TASK
    - docker pull 0000000000000000.dkr.ecr.us-east-1.amazonaws.com/kl:$IMAGE_TAG
    - docker tag 0000000000000000.dkr.ecr.us-east-1.amazonaws.com/kl:$IMAGE_TAG 0000000000000000.dkr.ecr.us-east-1.amazonaws.com/kl:ci

  pre_ci_boot:
    image_name: 0000000000000000.dkr.ecr.us-east-1.amazonaws.com/kl
    image_tag: ci
    pull: false
    options: "-e HOME=/root"

```
