### ISSUE TITLE
[Pipeline] how to  trigger functional tests after deploy

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3237]
### Description of your issue:
I been looking all around your documentation for an example of how to run my functional test after I deploy to a test environment but I can not find this.

Currently I have some functional/integration test with in my github repo so I can run them after deployment.

currently I am trying to update the jobs.yml files like below

```yml
# manifest gen for VISUALIZER
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-img
      - IN: dv-img-opts
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: dv-test-ecs
    type: deploy
    steps:
      - IN: dv-man
      - IN: env-test-ecs
      - IN: staging-microservice-alb
        applyTo:
          - manifest: dv-man         
            image: dv-img
            port: 80
      - TASK: managed
        deployMethod: upgrade
      - TASK:
        - script: cd automation
        - script: npm i
        - script: npm run test
# / TEST deployment for VISUALIZER to Amazon ECS
```

**Comment by manishas** [comment]
@asanchezgiraldo we will post more details in the morning but in a nutshell, you need to include a [runSh](http://docs.shippable.com/pipelines/jobs/runSh/) job after your deploy job. This runSh job should also take a [gitRepo](http://docs.shippable.com/pipelines/resources/gitRepo/) resource as an input pointing to the repo containing your functional tests.

@trriplejay will post a more detailed explanation in a few hours but wanted to get you started on the concept of how this will work.

**Comment by trriplejay** [comment]
currently, jobs only support one `TASK` section, so the correct way to do this is to split your existing deploy job into 2 jobs.

The first job is just the deploy action.  When the deploy action finishes successfully it will automatically trigger subsequent jobs.

The second job should be of type `runSh` as manishas linked to above.  The purpose of this job will be to run the functional test against the deployment that occurred.

Your pipeline might look something like this:
![image](https://cloud.githubusercontent.com/assets/6869398/21275484/e799755e-c381-11e6-9c8c-89054771593b.png)

in the runSh job, you can use the repo with your functional tests as an `- IN`. It might look something like this:
```yml
- name: simple-function-test-ft
    type: runSh
    steps:
      - IN: deploy-test-env-ft # the deploy job that should trigger this test
      - IN: simple-repo-ft # the repo containing the test scripts
        switch: off #changing repo shouldnt trigger test, only deploy should
      - TASK:
        - script: ./IN/simple-repo-ft/gitRepo/automation
        - script: npm i
        - script: npm run test
```

For the above example, whenever the job named `deploy-test-env-ft` completes successfully, this runSh job will be triggered.  `IN/<repo resource name>/gitRepo` is the base directory where your repo of that name will be cloned to, so you can `cd` there and run your test commands.

If you need additional information about your deploy (for example, the load balancer endpoint to test against) you can also get that info into your job through additional `IN` steps. If you need an example of that, let me know.

**Comment by rlennox-bauer** [comment]
This makes sense. Can you give us an example of providing additional info - in this case the load balancer URL from the previous deployment step. For our tests, this needs to be set as an environment variable APP_URL prior to 'npm run test'.

**Comment by rlennox-bauer** [comment]
Further to comment above. We need to install java on the node running the deploy task so we can fire up selenium. As part of the task scripts we have apt-update & apt-get install openjdk-7-jdk openjdk-7-jre-headless. This fails with the following error. 

> Ign http://archive.ubuntu.com trusty InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit https://deb.nodesource.com trusty InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty Release
Hit https://deb.nodesource.com trusty/main Sources
Hit https://deb.nodesource.com trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
distribution that some required packages have not yet been created
Some packages could not be installed. This may mean that you have
or been moved out of Incoming.
requested an impossible situation or if you are using the unstable
 openjdk-7-jre-headless : Depends: tzdata-java but it is not going to be installed
The following information may help to resolve the situation:
The following packages have unmet dependencies:
E: Unable to correct problems, you have held broken packages.
runSh failed with error:  100

The machine is running the standard pipeline node 
>uname -a
Linux 29340830b1a6 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Ideas?

**Comment by trriplejay** [comment]
the load balancer url actually wouldn't come directly from the deploy job, since Shippable only knows the name and the targetGroupArn as provided in the yml.

Instead, I'd recommend adding a "params" resource like this:
```
resources:
  name: testParams
  type: params
  source:
    params:
      albUrl: "my_load_balancer_url.amazonaws.com"
```

then, you can use this as another `IN` to your runSh job.

you can access this variable by adding a step to your runSh script like this:
```yml
- script: source ./IN/testParams/params
```

the "params" file is just a list of key/value pairs in shell form `key=value`, so when you source it, the variables are added to the bash ENV, and then you can access them as normal.

another option to simplify this is to just add the value directly to the runSh script, as one of the `- script: ` steps.  Then you don't have to deal with an extra params resource.
```yml
- script: "albUrl=my_load_balancer_url.amazonaws.com"
```

in the future we plan to add more support for LB resources that should simplify this, but for now these are the options I'd recommend.

**Comment by asanchezgiraldo** [comment]
HI @trriplejay thanks for your response, but currenlty I am not able to run any of my test as I am getting an error when running my chimpjs test.

```
at Object.start (/build/IN/now-site-repo/gitRepo/automation/node_modules/selenium-standalone/lib/start.js:59:27)
Error: not found: java
```

Then, when I try to install jdk i am getting the below error

```
Errors were encountered while processing:
 /var/cache/apt/archives/oracle-java8-installer_8u121-1~webupd8~0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

my job configuration is 
```yml
  - name: now-site-dev-automation-test
    type: runSh
    steps:
     - IN: env-dev-ecs
     - IN: now-site-repo
     - IN: now-site-alb-dev
     - IN: now-site-dev-deploy
     - TASK:
        - script: add-apt-repository ppa:webupd8team/java
        - script: apt-get -f -y update
        - script: apt-get -f -y install oracle-java8-installer
        - script: java -version
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://registryURL
        - script: npm install
        - script: xvfb-run --server-args="-screen 0, 1920x1080x24" npm run automation:test
```
