### ISSUE TITLE
Get acceptance testing results from pipeline shippable nodes

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3249]
Description of my implementation:
I have implemented selenium tests as acceptance testing after deployment in Pipeline, which is similar to the work described in issue #3237.
Here is the pipeline: [my pipeline](https://app.shippable.com/subscriptions/57b7db1f3d3c340e00026d35/pipelines/spog) 
you can find my acceptance testing in the end of the pipeline, called "e2e-testing-stage".

My issue:
This acceptance testing runs very well. But my problem is how to make a good testing reporting to show the test result in Shippable. Note that: I can generate testing results in Json, xml or HTML, but no feature to parse them and show on the page. It seems there is my demanded feature in CI shippable node, like testing results and coverage been parsed and shown in the sub-page of CI build results.

Could you please provide me with some solution to better show the testing result from pipeline instead of seeing results from console only?

Thanks a lot.

**Comment by manishas** [comment]
@Neal910 this is definitely on our radar. I'll update you when we address this scenario.

**Comment by asanchezgiraldo** [comment]
@Neal910 would you mind sharing with me what you have done to do this. As we are still not able to run our cucumber scripts locally.

```
# Test Dev site
  - name: now-site-dev-automation-test
    type: runSh
    steps:
     - IN: env-dev-ecs
     - IN: now-site-repo
     - IN: now-site-alb-dev
     - IN: now-site-dev-deploy
     - TASK:
        - script: sudo add-apt-repository ppa:webupd8team/java
        - script: sudo apt-get update
        - script: sudo apt-get install oracle-java8-installer
        - script: java -version
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: xvfb-run --server-args="-screen 0, 1920x1080x24" npm run now:automation
```

Are you using a Selenium grid of your own? or have you been able to run the test locally.
