### ISSUE TITLE
Issue with encrypted environment variable

### ISSUE THREAD

**Issue by hernandesbsousa** [Shippable/support#325]
Hi, I have encrypted two variables using the `secure variables` tab and placed them on my yaml file like this:

```
env:
  global:
    - secure: secure_output
    - MYVAR=value
```

I added these variables for testing: `FOO=bar BAR=foo` (in this format, with a whitespace between each var), but a simple `echo $FOO` doesn't produce any output, can someone give me a hand with this?

PS: the MYVAR unencrypted variable works fine.
