### ISSUE TITLE
Default foreground/background ANSI escape codes ignored

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3267]
While Shippable supports ANSI escape codes for colored output, it seems like the escape codes for default foreground (39) and default background (49) are not supported. Instead, the previously set foreground/background color continues to be active until the next escape code:

![image](https://cloud.githubusercontent.com/assets/5037116/21712207/9b16b6ba-d3f3-11e6-9ea1-c589f4217646.png)

This [build output](https://app.shippable.com/runs/586f56c63b531310004622cc/1/console) was produced with the following `shippable.yml`:

```yaml
language: none

build:
  ci:
    - echo -e "\033[31mred foreground\033[0m default foreground (full reset)"
    - echo -e "\033[41mred background\033[0m default background (full reset)"
    # Symfony
    - echo -e "\033[31mred foreground\033[39m default foreground (foreground reset)"
    - echo -e "\033[41mred background\033[49m default background (background reset)"
```

As indicated by the comment this reset behavior is the [default for all Symfony console applications](https://github.com/symfony/console/blob/40b3aca/Formatter/OutputFormatterStyle.php) and can lead to highly misleading output, e.g. within [Deployer](https://deployer.org/):

![image](https://cloud.githubusercontent.com/assets/5037116/21712250/e134abc0-d3f3-11e6-82dd-20699bdd2cd3.png)

From the user POV it looks like all of the commands failed with errors (red) whereas originally only the `>` was meant to be colored.
