### ISSUE TITLE
Endless docker container creation in AWS

### ISSUE THREAD

**Issue by Zingoer** [Shippable/support#3269]
Based on #3087, I successfully created the data volume container and postgres db container in Oct-Nov. I make sure I can redeploy db containers if needed. ([success build 1-5](https://app.shippable.com/subscriptions/57b7db1f3d3c340e00026d35/pipelines/spog)) But when I try to redeploy today, I'm not be able to run postgres db container successfully. The task will always try to create a postgres container but never run it. The snippet of ECS `docker ps -a` log is as following:
```
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS                       PORTS                                           NAMES
1a7111561683        xxxx.amazonaws.com/lrp/postgres:latest                  "/docker-entrypoint.s"   11 minutes ago      Created                                                                      xxxx-db-image-8ef286a7bbdcf8be3500
e6a7a2caed9a        xxxx.amazonaws.com/lrp/postgres:latest                  "/bin/true"              11 minutes ago      Exited (0) 11 minutes ago                                                    xxxx-dbstore-image-dea090a58399e1879e01
9d44d807c963        xxxx.amazonaws.com/lrp/postgres:latest                  "/docker-entrypoint.s"   11 minutes ago      Created                                                                      xxxx-db-image-8a919abbe7c8c9b6b501
f07ef67e1df5        xxxx.amazonaws.com/lrp/postgres:latest                  "/bin/true"              11 minutes ago      Exited (0) 11 minutes ago                                                    xxxx-dbstore-image-8ac7e58186e9f8d3f701
```
As you can see, there are two images try to deploy, dbstore-image and db-image, when dbstore is a data volume container and db-image is the postgrees db container. db-image status should be `up x seconds` instead of only created. Therefore, AWS task goes into endless deployment. 
In [failure build 10 and 14](https://app.shippable.com/subscriptions/57b7db1f3d3c340e00026d35/pipelines/spog), you can see the aws get into deploy loop as well.

I spent several hours but no idea why this would happen. And I almost didn't change the shippable ymls or postgres image. The only change I made is change from `entrypoint` to `entryPoint`. 

My ymls are as following:
```
resources:
# Postgres db docker image
  - name: db-image
    type: image
    flags:
      - staging
      - LRP
    integration: ec2_container_registry
    pointer:
      sourceName: "xxxx.amazonaws.com/lrp/postgres"
    seed:
      versionName: latest

# Postgres dbstore docker image
  - name: dbstore-image
    type: image
    flags:
      - staging
      - LRP
    integration: ec2_container_registry
    pointer:
      sourceName: "xxxx.amazonaws.com/lrp/postgres"
    seed:
      versionName: latest

# Postgres dbstore docker options
  - name: dbstore-dockeropt-staging
    type: dockerOptions
    flags:  
      - staging
      - LRP
    version:
        volumes:
          - "/somepath/postgres_data:/var/lib/postgresql/data"
        entryPoint:
          - /bin/true

# Postgres database docker options
  - name: postgresdb-dockeropt-staging
    type: dockerOptions
    flags:
      - staging
      - LRP
    version:
        portMappings:
          - 5432:5432
        volumesFrom:
          - "dbstore-image"

# Postgres database params
  - name: postgres-params
    type: params
    flags:
      - staging
      - LRP
    version:
      params:
        secure: ...
```
```
jobs:

# manifest for database data volume container staging
  - name: db-man-staging
    type: manifest
    flags:
      - staging
      - LRP
    steps:
      - IN: dbstore-image
      - IN: dbstore-dockeropt-staging
        applyTo: 
          - dbstore-image
      - IN: postgres-params
        applyTo:
          - dbstore-image
      - IN: db-image
      - IN: postgresdb-dockeropt-staging
        applyTo:
          - db-image
      - TASK: managed

# Deploy lrp postgres database to the staging area (in ECS)
  - name: db-deploy-staging-ecs
    type: deploy
    flags:
      - staging
      - LRP
    on_success:
      - NOTIFY: shippable-slack-staging
    on_failure:
      - NOTIFY: shippable-slack-staging
    steps:
      - IN: db-man-staging
      - IN: env-staging-ecs
      - TASK: managed
        deployMethod: replace
```

Do I miss some new configuration requirements for docker options? Or is there some change I should made? The most confusing thing is that the postgres container doesn't up but only create. However, it will up a postgres container when I manually try `docker run` with all same shippable options in the AWS instance.
