### ISSUE TITLE
"shippable_retry: command not found" in scripts

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3272]
[It looks like](https://app.shippable.com/runs/5873ac343b53131000472637/1/console) the `shippable_retry` function is somehow only available within the `shippable.yml` but not within scripts launched from there:

![image](https://cloud.githubusercontent.com/assets/5037116/21771791/164f41d4-d689-11e6-8983-2ef0c510c4ed.png)

The `shippable.yml` from the build:

```yaml
language: none

build:
  ci:
    - shippable_retry ls
    - bash test.sh
```

The `test.sh`:

```bash
#!/bin/bash

shippable_retry ls
```
