### ISSUE TITLE
Invalid integration for integration type: deploy

### ISSUE THREAD

**Issue by darilldrems** [Shippable/support#3280]
I am trying to set up AWS elastic beanstalk integration and I get the error below when I run the build
"  Errors  
Invalid integration aws-eb specified for integration type : deployInvalid integration undefined specified for integration type : deployInvalid integration undefined specified for integration type : deployInvalid integration undefined specified for integration type : deployInvalid integration undefined specified for integration type : deployInvalid integration undefined specified for integration type : deploy"

Here is the shippable.yml used
language: node_js
node_js:
  - 6.8.0
script:
  - npm test
integrations:
  deploy:
    - integrationName: "aws-eb"
    - type: aws
    - target: eb_paas
    - platform: "Node.js"
    - application_name: pwc-docs
    - env_name: pwc-docs-dev
    - region: eu-west-1

**Comment by trriplejay** [comment]
It looks like your yml has some errors. it should look like this:
```yml
language: node_js
node_js:
  - 6.8.0
script:
  - npm test
integrations:
  deploy:
    - integrationName: "aws-eb"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: pwc-docs
      env_name: pwc-docs-dev
      region: eu-west-1
```

note that only the top item after deploy has a `-`

**Comment by darilldrems** [comment]
Thank you. Works fine now but now facing this error:
 Application Name: "pwc-docs"
  Environment Name: "pwc-docs-dev"
  Version Label: "shippable.pwc-docs-dev.shippable.yml.4"
  Region: "eu-west-1"
  Platform: "Node.js"
  Image Name: ""
  Image Tag: ""
  S3 Bucket Name: ""

  echo | eb init "pwc-docs" -r "eu-west-1" -p "Node.js" 0s  
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 9, in <module>
    load_entry_point('awsebcli==3.7.8', 'console_scripts', 'eb')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/ebcore.py", line 43, in <module>
    from . import ebglobals, base, io, hooks
  File "/usr/local/lib/python2.7/dist-packages/ebcli/core/hooks.py", line 21, in <module>
    from ..lib import aws
  File "/usr/local/lib/python2.7/dist-packages/ebcli/lib/aws.py", line 22, in <module>
    from botocore.config import Config
ImportError: cannot import name Config

**Comment by trriplejay** [comment]
I think this is an issue with the version of botocore. 
can you add `pip install --upgrade botocore` to the end of your CI?

speaking of which, I notice that you have a `script` section in your yml.  This is an older format that we've since retired, though it still technically works. I'd recommend taking a look at the docs here: http://docs.shippable.com/ci/shippableyml/#anatomy-of-shippableyml

you'll probably want to change that script section to something like:
```yml
build:
  ci:
    - npm test
    - pip install --upgrade botocore
```
