### ISSUE TITLE
Cannot use SHIPPABLE_PHP_VERSION in image_tag

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3292]
I just tried to use the `php` image for a build and have used `${SHIPPABLE_PHP_VERSION}-cli` as value for `image_tag` in `pre_ci_boot`:

```yaml
  pre_ci_boot:
    image_name: php
    image_tag: ${SHIPPABLE_PHP_VERSION}-cli
    pull: true
```

However, this value does not seem to be filled at this point:

```
boot_container
...
  sudo docker run -d ... php:-cli
Unable to find image 'php:-cli' locally
Pulling repository docker.io/library/php
Tag -cli not found in repository docker.io/library/php
```

If this is not supported, how else would I go about running multiple jobs with different PHP versions?
