### ISSUE TITLE
Trigger Notifications issues

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3303]
I'm trying to configure trigger notifications to trigger pipeline from CI builds for this project:
https://app.shippable.com/projects/57bcb6573d3c340e000348ed
Its added successfully, except of this issue: https://github.com/Shippable/support/issues/3302, but doesn't actually works. Triggers for other project works fine, but sometimes, not often, its stops working and starts working only after deleting account, subscription integration and token and adding all this again.

**Comment by a-murphy** [comment]
The recent builds in that project don't appear to have the event trigger integration in the `shippable.yml` file.  Could you check that the integration is listed in the `notifications` section of `integrations` in the following format?

```YML
integrations:
  notifications:
    - integrationName: triggerDemoPipeline #Replace with name of the integration from subscription settings
      type: webhook
      payload:
        - versionName=$BRANCH.$BUILD_NUMBER  #Replace with the tag of the image you pushed during CI  
      on_success: always
      on_failure: never
```
Quite often, integrations that aren't working turn out to be indentation that isn't quite right or a `shippable.yml` that has two `integrations` sections (there should only be one with all integrations listed).

Triggers shouldn't stop working suddenly, unless the account that the integration belongs to no longer has access to the project containing the pipeline resource.  In what way do they stop working?  Is there an error message?
