### ISSUE TITLE
Incorrect branch used during build

### ISSUE THREAD

**Issue by dwickwire** [Shippable/support#331]
Hello, 

I pushed a branch clearly labeled `upgrade/rails-3.2`:

``` shell
[dwickwire]:myapp(upgrade/rails-3.2)$ git push origin upgrade/rails-3.2
Counting objects: 24, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.17 KiB | 0 bytes/s, done.
Total 7 (delta 3), reused 0 (delta 0)
To <my-apps-github-url>
   eb9aad4..0ac2298  upgrade/rails-3.2 -> upgrade/rails-3.2
```

Yet, it tries to build `rails-3.2` and fails:
![screen shot 2014-07-29 at 12 25 58 pm](https://cloud.githubusercontent.com/assets/181901/3738966/9541f77a-1746-11e4-8270-d87e7e6f75f4.png)

Is this a bug, or am I missing something?

My shippable.yml

``` yaml
# Build Environment
build_environment: Ubuntu 10.04.4

# Language Setting
language: ruby

# Ruby Version Numbers
rvm:
  - 2.1.0

# Set secure env variables
env:
  - RAILS_ENV=test

services:
  - mysql

before_script:
  - wget http://sphinxsearch.com/files/sphinx-2.1.9-release.tar.gz
  - ./sphinx-2.0.7-release/configure --with-mysql
  - make
  - sudo make install

  - mysql -e 'create database myapp_test;'
  - cp config/database.shippable.yml config/database.yml
  - RAILS_ENV=test rake db:migrate
```
