### ISSUE TITLE
Incorrect env.BRANCH property

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3311]
Hey,

There is git repo with branch `release/v0.1.6`.
But in `env.BRANCH` there is only`v0.1.6` (without `release/` prefix).

Link to the git repo: https://github.com/ykrevnyi/retryer.js/tree/release/v0.1.6
Link to the build: https://app.shippable.com/runs/5884c1f9aebc4e0f00801304/1/console

UI bug: http://take.ms/z8Eab
UI bug 2: http://take.ms/pa3lY

### shippable.yml

```
language: none

build:

  ci:
    - export DOCKER_IMAGE_NAME=ykrevnyi/retryer.js
    - if [ "$IS_RELEASE" == false ]; then export DOCKER_TAG=trunk-${COMMIT:0:7}; fi
    - if [ "$IS_RELEASE" == true ]; then export DOCKER_TAG=${GIT_TAG_NAME#v}; fi
    - ./ci/build.sh
    - ./ci/test.sh

integrations:
  hub:
    - integrationName: personal_dockerhub
      type: docker

  notifications:
    - integrationName: trigger.retryerjs.pipelines
      type: webhook
      payload:
        - versionName=${GIT_TAG_NAME#v}
        - isRelease=$IS_RELEASE
      on_success: always
      on_failure: never

branches:
  only:
    - master
    - v*
```
