### ISSUE TITLE
Release feature problems

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3319]
Hey guys,

I have the `shippable.resources.yml` file with:
```
- name: resource.gitRepo.retryerjs..release
    type: gitRepo
    integration: github
    pointer:
      sourceName: ykrevnyi/retryer.js-test
      branches:
        only:
          - v*
    buildOnRelease: true
    buildOnCommit: false
    buildOnPullRequest: false
    buildOnTagPush: false
```

Then I create `release` on Github and nothing happens.

I'm using these branches/tags:
- branch `master`
- branch `release/vX.X.X` together with tag `vX.X.X`

If we change `branches` property to:
```
branches:
  only:
    - release/v*
    - v*
```

Then build gets triggered by `branch`.

From Github Webhook Deliveries I can clearly see two deliveries:
- `X-GitHub-Event: push` (triggered at shippable)
- `X-GitHub-Event: release` (not triggered at shippable)

Thanks
