### ISSUE TITLE
Job always fails at "Saving Job Files" stage

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3320]
Hi

I'm always getting this strange error.
`runSh|_common|saveState|_getFilePaths, :postFilesByResourceId failed for resourceId: 10573 with error 404`

How is it possible to debug it?

- Link to the build failure
   https://app.shippable.com/download/buildJobConsoles?buildJobId=5887714caebc4e0f00812fcc

- Scripts called from the yml (optional)
```
jobs:
  - name: job.test
    type: runSh
    steps:
      - IN: resource.integration.personal-dockerhub
      - IN: resource.params.npm-token
      - IN: resource.gitRepo.retryerjs
      - IN: resource.gitRepo.pipelines
        switch: off
      - TASK:
        - script: apt-get install -y jq
        - script: export DOCKER_IMAGE_NAME=ykrevnyi/retryer.js
        - script: export COMMIT_SHA=$(cat ./IN/resource.gitRepo.retryerjs/version.json | jq -r '.version.versionName')
        - script: export DOCKER_TAG=alpha-${COMMIT_SHA:0:7}
        - script: cd ./IN/resource.gitRepo.retryerjs/gitRepo
        - script: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
        - script: docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_TAG npm test
        - script: echo "versionName=$DOCKER_IMAGE_NAME:$DOCKER_TAG" > /build/state/resource.image.retryerjs.env
        - script: cat /build/state/resource.image.retryerjs.env
        - script: ls -la /build/state
      - OUT: resource.image.retryerjs
```

Thanks a lot
