### ISSUE TITLE
Jacoco code coverage with sub-modules

### ISSUE THREAD

**Issue by jtaylor10** [Shippable/support#3322]
### Description of your issue:
I noticed recently the documentation was updated to mention support for Jacoco code coverage reporting. This is GREAT, thanks!!  In my project we're using gradle and have sub-modules/projects so each project gets a jacoco.xml result file. I've used the gradle jacocoFullReport plugin to aggregate these xmls into one large one and can see the results in shippable coverage tab which is also ideal!

My problem though is I'm trying to get the advanced reporting to work but it's not working with the combined file.  As detailed on http://docs.shippable.com/tutorials/ci/integrations/codeCoverage/usingJacoco/ I noticed that enabling advanced reporting you must copy your whole target directory over.  That works for maven but not gradle so can you tell me which file(s) the advanced reporting is looking for so I can aggregate/copy them over. 

Also do I need to aggregate or can I drop multiple files over the the code coverage directory and it will pick them up? I'm assuming not which is a real annoyance that it must look for a specific file.

- Link to the build failure
Build which captured coverage but no advanced reporting: https://app.shippable.com/runs/58878656b98c6c0f00f262d2/1/coverage

- Scripts called from the yml (optional)
My .yml build section

```yaml
services:
  - mysql

build:
  advancedReporting: true
  ci:
    #Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage/site/jacoco
    #Create mysql database
    - mysql -e 'create database <dbName>;'
    - ./gradlew clean check jacocoFullReport
  on_success:
    #Convert code coverage reports to supported format
    - cp build/reports/jacoco/jacocoFullReport/jacocoFullReport.xml shippable/codecoverage/site/jacoco/jacoco.xml
    - cp -r build/reports/jacoco/jacocoFullReport/html shippable/codecoverage/site/jacoco/html
```
