### ISSUE TITLE
Running a Task Definition in ECS

### ISSUE THREAD

**Issue by sample-sample** [Shippable/support#3339]
Is there a way to run a task definition from another after a build has been deployed? Task definition A has a container needs to run a script in a container under Task definition B after it has been deployed; both of these definitions in the same cluster. Container in B runs a script and is stopped once complete. I would want to run it again in the next build of A.

The way I've setup based on your tutorial right now, I always end up with a service in the cluster and a task definition. Is it possible to only create a task definition without a service in ECS?

**Comment by stephanielingwood** [comment]
Hi @sample-sample,

Currently, our deploy jobs are designed to get services up and running; they both create the task definition and create a service. 

If you wanted to do something more specialized with ECS - e.g. create a task definition without creating a service - you can use a runSh job. A runSh job gives you full control over what happens in the job, and you can script whatever you like. The AWS CLI comes pre-installed for runSh jobs, so you could use that to create a task definition on ECS. 

Here's what you'd need in your yml: 

In the shippable.resources.yml, add an [integration](http://docs.shippable.com/pipelines/resources/integration/) resource, like this:
```
  - name: awsIntegration # name this resource whatever you like
    type: integration
    integration: my-AWS-subscription-integration  #this is the name of your subscription integration with your AWS credentials
```

In the shippable.jobs.yml, add a runSh job. This will take three inputs: your deploy job, a [gitRepo](http://docs.shippable.com/pipelines/resources/gitRepo/) resource containing a .json file of your task definition, and your awsIntegration resource.
```
  - name: create-task-definition
    type: runSh
    steps:
      - IN: deployAwsService  # name of the deploy job that is deploying your first container
      - IN: myGitRepo  #name of a gitRepo resource that has your .json task definition file
      - IN: awsIntegration
      - TASK:
        - script: mkdir -p ~/.aws
        - script: AWS_PATH=~/.aws        
        - script: rm -f $AWS_PATH/config
        - script: rm -f $AWS_PATH/credentials
        - script: echo "[default]" >> $AWS_PATH/config
        - script: echo "region=us-east-1" >> $AWS_PATH/config     # replace us-east-1 with your region
        - script: echo "output=json" >> $AWS_PATH/config 
        - script: echo "[default]" >> $AWS_PATH/credentials
        - script: echo "aws_access_key_id=$AWSINTEGRATION_INTEGRATION_AWS_ACCESS_KEY_ID" >> $AWS_PATH/credentials
        - script: echo "aws_secret_access_key=$AWSINTEGRATION_INTEGRATION_AWS_SECRET_ACCESS_KEY" >> $AWS_PATH/credentials
        - script: aws ecs register-task-definition --cli-input-json file://$MY-GIT-REPO_PATH/gitRepo/taskDefinition.json
```

Above, you're setting up the `~/.aws/config` and `~/.aws/credentials` files with the credentials you saved in the awsIntegration. (Integrations are [made available as environment variables](http://docs.shippable.com/pipelines/jobs/runSh/) in runSh jobs.) The AWS CLI will read from those files, and use those credentials when making the call to [register the task definition](http://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html), using the taskDefinition.json file from your gitRepo. From here, you can take whatever action you want on ECS via the AWS CLI.

By adding the deploy job as an input to the runSh job, it will trigger the runSh job after your deployment has completed, so you know it'll happen once your first container is up and running.

Cheers.
