### ISSUE TITLE
Deploy to EB only from specific branches

### ISSUE THREAD

**Issue by aleksihakli** [Shippable/support#3340]
### Description of your issue: Deploy only from specific branches, for example master

Hi,

Is it possible to define a branch I want to deploy to from the shippable.yml or do I have to run the deployment manually with `eb deploy`?

I have the following set up, does this work?

```
integrations:
  deploy:
    - integrationName: "AWS Elastic Beanstalk Deployment"
      type: aws
      target: eb_paas
      platform: "Python"
      application_name: myproject
      env_name: myproject-api-staging
      region: eu-central-1
      branches:
        only:
          - master
```
