### ISSUE TITLE
Build failed by timeout

### ISSUE THREAD

**Issue by mariale425** [Shippable/support#3341]
Hi, I have a problem. I have an error in the second build. This error is by: "Error: failed to remove one or more containers".  I was reviewing and adding the cache to true. But I still have the same problem.

My yml: 

```
language: ruby
rvm:
  - 2.2.2

services:
  - elasticsearch
  - postgres
  - selenium

parallized_test: true

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: ...
  firefox: "23.0"

env:
  matrix:
    - TEST_SUITE=rspec
    - TEST_SUITE="rake spec:javascript"
    - TEST_SUITE=cucumber

  global:
    - APP_NAME= ..
    - COVERALLS_REPO_TOKEN= ...
    - CODECLIMATE_REPO_TOKEN= ...
    - CI=true
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - CI_NAME=shippable CI_BUILD_NUMBER=$BUILD_NUMBER CI_BRANCH=$BRANCH CI_BUILD_NUMBER=$BUILD_NUMBER
    - BLUEPAY_ACCOUNT_ID= ...
    - BLUEPAY_SECRET_KEY= ...
    - BLUEPAY_MODE_PAYMENT="TEST"
    - QBO_CONSUMER_KEY= ...
    - QBO_CONSUMER_SECRET= ...
    - QBO_SPEC_TOKEN= ..
    - QBO_SPEC_SECRET= ...
    - QBO_SPEC_REALM_ID= ..

script:
  - "bundle exec $TEST_SUITE"

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create --trace
  - bundle exec rake db:schema:load
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:schema:load RAILS_ENV=test

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
  - sudo apt-get -y install phantomjs

build:
  cache: true
  cache_dir_list: 
    - $SHIPPABLE_BUILD_DIR
```
