### ISSUE TITLE
Build 

### ISSUE THREAD

**Issue by mariale425** [Shippable/support#3346]
### Description of your issue:

Hi, I have a problem. All my tests are green but the build fails much times. This problem is intermitent:

https://app.shippable.com/runs/58948c648d80360f008b8aa0/1/console
https://app.shippable.com/runs/58948c648d80360f008b8aa0/3/console

- Screenshot:
https://www.evernote.com/l/AiQVG0yJTp9IN59ufYm-GqkYpAgKZUA22NQ
https://www.evernote.com/l/AiRnhs5SS8BHxYuWwJkI62csZeR_sCzO4sE
https://www.evernote.com/l/AiQYx__sZcVNurErcxyVD8BUJG6gfgKvmXw 

We doing rebuild at least 5 times. But my development process is slow now.

My yml: 

```
language: ruby
rvm:
  - 2.2.2

services:
  - elasticsearch
  - postgres
  - selenium

parallized_test: true

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: ...
  firefox: "23.0"

env:
  matrix:
    - TEST_SUITE=rspec
    - TEST_SUITE="rake spec:javascript"
    - TEST_SUITE=cucumber

  global:
    - APP_NAME= ..
    - COVERALLS_REPO_TOKEN= ...
    - CODECLIMATE_REPO_TOKEN= ...
    - CI=true
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - CI_NAME=shippable CI_BUILD_NUMBER=$BUILD_NUMBER CI_BRANCH=$BRANCH CI_BUILD_NUMBER=$BUILD_NUMBER
    - BLUEPAY_ACCOUNT_ID= ...
    - BLUEPAY_SECRET_KEY= ...
    - BLUEPAY_MODE_PAYMENT="TEST"
    - QBO_CONSUMER_KEY= ...
    - QBO_CONSUMER_SECRET= ...
    - QBO_SPEC_TOKEN= ..
    - QBO_SPEC_SECRET= ...
    - QBO_SPEC_REALM_ID= ..

script:
  - "bundle exec $TEST_SUITE"

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create --trace
  - bundle exec rake db:schema:load
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:schema:load RAILS_ENV=test

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
  - sudo apt-get -y install phantomjs

build:
  cache: true
  cache_dir_list: 
    - $SHIPPABLE_BUILD_DIR
```
