### ISSUE TITLE
`docker push` fails with `no basic auth credentials` using AWS ECR integration

### ISSUE THREAD

**Issue by milesjordan** [Shippable/support#3349]
### Description of your issue:
I have been unable to get the ECR integration working so instead have fallen back to encrypting AWS credentials and running $(aws ecr get-login) as a part of the build, which works fine. The only thing I can think that might be affecting it is that the image is hosted in the ap-southeast-2 region - not sure if it's supported by shippable. What I have is working fine for me so this is just for your info.

- Link to the build failure: 
https://app.shippable.com/runs/589716e28f655f1300c374cb/1/console

**Comment by a-murphy** [comment]
If you still want to use the ECR integration, you just need to specify the region.  In the linked build, AWS was configured with the default `us-east-1`, which would be why you couldn't push to `ap-southeast-2`.  You should be able to just add `region: ap-southeast-2` to the ECR integration in your `shippable.yml`.  It would look something like this:
```YML
integrations:
  hub:
    - integrationName: myECRIntegration
      type: ecr
      region: ap-southeast-2
      branches:
        only:
          - branch1
          - branch2
```
