### ISSUE TITLE
DJango LiveServerTestCase can't find selenium web browser

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#336]
I have a project with a django LiveServerTestCase based on selenium. It runs fine locally and launches firefox when it should. 

I setup my shippable.yml according to the documentation here:

```
http://docs.shippable.com/en/latest/config.html#selenium
```

My shippable.yml looks like:

```
python:
  - "2.7"

language: python

before_script:
  - mkdir -p shippable/codecoverage shippable/testresults
  - mysql -e 'create database hae;'
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"

install: "pip install -r dependencies.conf"

env:
  - DJANGO_VERSION=1.6

script:
  - ./website/manage.py test --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - ./website/manage.py test --with-coverage --cover-xml --cover-xml-file=shippable/codecoverage/coverage.xml --cover-package=website --cover-branches
  - pep8 --ignore=E501 website --exclude=migrations
  #- pylint website
  #- pyflakes website

addons:
   firefox: "29.0"

services:
  - selenium

after_script:
 - "/etc/init.d/xvfb stop"
```

However, when django's manage.py runs nose and picks up my selenium tests, I get:

```
WebDriverException: Message: The browser appears to have exited before we could connect. The output was: Error: no display specified\n
```

How can I get selenium tests to run successfully on shippable? Thanks!

**Comment by kaflesudip** [comment]
I am having similar issue. My config looks likes this:
```
language: python

python:
  - 2.7

services:
  - mongodb
  - selenium

addons:
  firefox: "36.0"

install:
  - pip install -r requirements.txt

# Make folders for the reports, and create the SQL db
before_script:
  - "export DISPLAY=:99.0"
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - sleep 15
  - mongo test_meroanswer --eval ''
script:
  - "export DISPLAY=:99.0"
  - cd meroanswer && python manage.py test --settings=config.production --configuration=Production --noinput

notifications:
  email:
   - myemail@email.com
```
