### ISSUE TITLE
Invalid integration [name] specified for integration type : hub

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3363]
I have been trying to evaluate shippable for our CI/CD process.  I got everything working, except this one bit, and according to every bit of documentation, I have it right.  

Every attempted build gives me the same error when I put in the integrations section in the shippable.yml file.

Invalid integration goodway-docker-hub specified for integration type : hub

I have added the integration in my account settings, and also added it to the subscription settings.  I've tried using the same name and different names.  I've tried removing and adding it back.  

example build: https://app.shippable.com/runs/589e881840ae0510002d1ca3/1/console

The shippable.yml file:
```
language: node_js

node_js:
  - 4.4.0

env: [redacted]

install:
  - npm install
  - npm run gulp

script:
  - npm run test:server
  - npm run test:client
  - mv coverage shippable/codecoverage

build:
  ci:
    - docker build -t [redacted] .
  post_ci:
    - docker push [redacted]

integrations:
  hub:
    - integrationName: goodway-docker-hub
	  type: docker
	  branches:
	    only:
		  - shippable

```
