### ISSUE TITLE
Support for triggering job in pipeline on CI build success without using docker image resource

### ISSUE THREAD

**Issue by saeed-eskano** [Shippable/support#3368]
Is it possible to trigger a shippable pipeline job from shippable CI without using docker image? we don't use docker for our deployment process. As far as I can see when adding a trigger integration in shippable we can use image resource only.

We have a simple shippable pipeline job like this:

```
jobs:
  - name: deploy
    type: runSh
    on_start:
      - script: echo 'Deploy job started...'
      - NOTIFY: slackNotification
    steps:
      - TASK:
        - script: echo 'Hello World!'
        - script: echo "Running deploy for build $BUILD_NUMBER"
    on_success:
      - script: echo 'Deploy job succeeded...'
    on_failure:
      - script: echo 'Deploy job failed...'
    always:
      - script: echo 'Deploy job finished...'
      - NOTIFY: slackNotification
```
