### ISSUE TITLE
Deploy Job is not picking the correct config from feature/branch

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3388]
### Description of your issue:
currenlty when I try to run a feature/branch through the pipeline, the Deploy dev job keeps using the Master configuration from yml

![image](https://cloud.githubusercontent.com/assets/15203863/23259937/a8eee608-fa23-11e6-9b3e-8e0b0fa4e0d1.png)

Job in yml file is 
```
# DEV deployment for VISUALIZER to Amazon ECS
  - name: now-site-dev-deploy
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man
        force: true
      - IN: env-dev-ecs
      - IN: now-site-params-dev
      - IN: now-site-alb-dev
        applyTo:
          - manifest: now-site-man
            image: now-site-img
            port: 3001
      - TASK: managed
        deployMethod: replace
```

- Job link
https://app.shippable.com/subscriptions/583638aafd9c101000d73b34/pipelines/builds/58aed9cab4650b0f00a9d201/consoles

Error on the Job is
![image](https://cloud.githubusercontent.com/assets/15203863/23260003/05cc0e1e-fa24-11e6-8ed1-47fee90ef274.png)
