### ISSUE TITLE
ECS load balancer: Unable to assume role and validate the specified targetGroupArn

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3390]
I have defined the load balancer as follows in my ``shippable.resources.yml``:

```
  - name: myro-loadbalancer                                                     
    type: loadBalancer                          #required                       
    pointer:                                                                    
      sourceName: "arn:aws:elasticloadbalancing:ap-southeast-2:843155918926:loadbalancer/app/brianmay-lb/1c764d11fdbd7b04"
      method: application                                                       
      role: shippable-role-to-allow-ecs-access                                  
      clusterName: brianmay-shippable                                           
      region: ap-southeast-2                                                    
    version:                                                                    
      ports:                                                                    
          protocol: TCP                                                         
          port: 80                               
```

The ``shippable-role-to-allow-ecs-access`` has been configured with ``AmazonEC2ContainerServiceRole`` as per documention. WIth the trust relation to ``ecs.amazonaws.com``.

Shippable is displaying the following error:

```
error creating service InvalidParameterException: Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions.
```

Have I misunderstood something?

I believe sourceName is the ARN of the load balancer that I have already defined in EC2. Is this correct?
