### ISSUE TITLE
[Pipeline] How can I test a different workflow without updating my default branch

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3394]
### Description of your issue:
Currenlty we are doing a POC to use shippable and one of our constrains is that every time we want to change the workflow or a parameter in the pipeline we need to update the default branch (in our case master)

Is there a way to test changes on the pipeline, and how can we test this across multiple applications with the same pipeline workflows

example
Master branch
```
resources:
# Docker Image Options
  - name: now-site-opts-dev
    type: dockerOptions
    version:
      memory: 256
      cpuShares: 64
      portMappings:
        - 0:3001
      publishAllPorts : true
      logConfig:
        type: awslogs
        options:
          awslogs-group: "dev_app_ecs"
          awslogs-region: "ap-southeast-2"
          awslogs-stream-prefix: "app-now-site"
```
feature branch
```
resources:
# Docker Image Options
  - name: now-site-opts-dev
    type: dockerOptions
    version:
      memory: 512
      cpuShares: 64
      portMappings:
        - 0:3001
        - 0:3002
      publishAllPorts : true
      logConfig:
        type: awslogs
        options:
          awslogs-group: "dev_app_ecs"
          awslogs-region: "ap-southeast-2"
          awslogs-stream-prefix: "app-now-site"
```

**Comment by avinci** [comment]
This is an interesting problem. Resource definitions were not meant to be forked or branched. We have been dabbling with gitflow based pipelines and it starts to get pretty ugly.

the easiest thing that I would suggest if you can do it is to isolate the pipeline definitions into a separate repo. Create 2 resources for each branch and then switch it out in the deploy workflows. 

There are cons with this above approach 
- the pipeline definition is no longer in the repo
- every time you add a new branch, then pipeline definition needs to change, i.e. gitflow based SDLC is a challenge to implement

Do you mind jumping on a hangout so that we can understand your scenario and see if our prototype helps your flow? My email is avi@shippable.com

**Comment by avinci** [comment]
linking this https://github.com/Shippable/support/issues/3064

**Comment by avinci** [comment]
If its purely for testing, we can do it, more like a dry run. I am closing this in lieu of the issue above and we will spec out a solution for this

**Comment by asanchezgiraldo** [comment]
@avinci i am very interested in the concept of a Dry run, but for the time being we are testing a concept of a dual pipeline https://app.shippable.com/subscriptions/583638aafd9c101000d73b34/pipelines


```
jobs:

# sync pipeline to CI
  - name: now-site_runCI
    type: runCI
    steps:
      - OUT: now-site-img-master
      - OUT: now-site-img-branch

# manifest for a branch image
  - name: now-site-man-branch
    type: manifest
    steps:
      - IN: now-site-img-branch
      - IN: now-site-opts-dev
      - TASK: managed
    flags:
      - now-site

# manifest for master image
  - name: now-site-man-master
    type: manifest
    steps:
      - IN: now-site-img-master
      - IN: now-site-opts-dev

```
