### ISSUE TITLE
Add mounts from Docker host

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3402]
I am currently investigating [VirtualBox support in Docker containers](https://stackoverflow.com/questions/25741904/is-it-possible-to-run-virtualbox-inside-a-docker-container) to make our custom Vagrant box testable. Installing the VirtualBox kernel module on the Shippable Docker host is easy via `pre_ci`.

However, I'd also need to expose `/dev/vboxdrv` to the build container. As far as I see (#1207) it is not possible to customize the Docker launch command line.

Do you see a way to achieve this?

**Comment by avinci** [comment]
this is an old support issue. Here is the way to do it. In `pre_ci_boot` section you can pass options `-v src:dest` paths. As long as the source path is on the host it should work. 

This is way easier to do on Custom Hosts than dynamic hosts. More help on `pre_ci_boot` is here

http://docs.shippable.com/ci/shippableyml/#pre_ci_boot

**Comment by kanthchandra** [comment]
Hi @mbrodala you can do something like this
```
  pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: false
    options: '--privileged=true --net=bridge -v /dev:/dev'
```
which will mount the /dev directory onto your build container. Instead of /dev you can give any path that exists on the host.
