### ISSUE TITLE
Kubernetes deployments rather than Replication Controller

### ISSUE THREAD

**Issue by christophervalles** [Shippable/support#3404]
Hi guys,

I've been trying to make shippable work with GKE. So far it works but the deployment uses replication controllers rather than the new kubernetes deployment approach.

I've seen on another ticket that this is not supported yet so I thought about running my own commands on a runCLI and do the deployment myself. 

Ideally I would have the yml files describing the ingress/deployment/service/secrets on the repo alongside the shippable.yml file but I don't seem to find the way to read those files from the runCLI job.

The job would like this:

```
  - name: svc-template-staging
    type: runCLI
    steps:
      - IN: svc-template-manifest
      - IN: env-staging
      - TASK:
        - script: shippable_replace svc_template_deployment.yml svc_template_ingress.yml svc_template_service.yml svc_template_secret.yml
        - script: kubectl apply -f svc_template_deployment.yml --record
        - script: kubectl apply -f svc_template_ingress.yml --record
        - script: kubectl apply -f svc_template_service.yml --record
        - script: kubectl apply -f svc_template_secrets.yml --record
```

Any ideas? Am I missing something here?

Cheers

**Comment by stephanielingwood** [comment]
Hi @christophervalles,

Your best bet in this case is to add the repo containing your yml files as a [gitRepo](http://docs.shippable.com/pipelines/resources/gitRepo/) resource. (Yes, you can add any repo as a `gitRepo`, even if it's the "syncRepo" - a.k.a. the repo you added to create your pipeline.)  Your `gitRepo` might look something like this: 

```yml
  - name: sample_pipelines #this can be whatever you want
    type: gitRepo
    integration: myGithubSubscriptionIntegration     # the subscription integration for your source control provider - GitHub, Bitbucket, etc.
    pointer:
      sourceName: "yourOrgName/sample_pipelines"     # here, sample_pipelines is the repo name
      branch: master
```

Now, you can add this gitRepo as an `IN` to your `runCLI` job:
```yml
  - name: myRunCLIJob 
    type: runCLI
    steps:
      - IN: gkeConfig     # the name of your cliConfig resource for GKE      
      - IN: sample_pipelines     # name of your gitRepo resource
      - TASK:
        - script: ls -la $SAMPLE_PIPELINES_PATH/gitRepo
```

This gives you access to all files in that repo, at the path `RESOURCENAME_PATH/gitRepo`. So, in the above example, that `ls` just showed me all the files in the root of my `sample_pipelines` repo. You also get access to a number of other environment variables associated with that `gitRepo` resource - they're documented [here](http://docs.shippable.com/pipelines/jobs/runSh/#gitrepo-resource-variables).

Hope this helps! Let us know if you have more questions.
