### ISSUE TITLE
version information in deploy

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3408]
Hello,

I am trying to work out if it is possible to get the version information in the deploy somehow. So that it is possible to confirm by looking at the deployed software what version it is.

I can see how to get version information in [runSh](http://docs.shippable.com/tutorials/pipelines/extractVersionInformation/) scripts.

However I think would I need is to be able to set ``params`` resources using the version information. However I can't see any documentation on how to do this, or how to set ``params`` from a ``runSh`` job even.

Is this sensible? Or have I misunderstood something? Is the above possible?

Thanks

**Comment by avinci** [comment]
Are you trying to get the version information into deploy or out of deploy? When you say version infromation, are you storing some state values etc.?

Most of the scenarios are possible and not very difficult to implement once you get comfortable with it. 

You cannot override param resources dynamically, but you can of course create new params and store them in the version of  the job you want to store them in. Now if you do an `IN` of that job into any other job, you will have access to the version information as well as the state.

This is how you can save state files
http://docs.shippable.com/tutorials/pipelines/persistStateBetweenRuns/

This talks about save state info into an output resource, but the job you run is also technically a resource and hence you can do the same for the job you are running and it should work
http://docs.shippable.com/tutorials/pipelines/updateResourceVersion/

Let me know if this helps.

**Comment by brianmay** [comment]
To try and clarify, when the application is deployed for testing, it has a version such as ``master.11``. Or when it is deployed for release it has a version such as ``1.2.3``.

I want to be able to see this version when I look at the website of my application. Maybe in the footer, for example. Meaning users of my website, when when complaining about problems, can easily cite the deploy version.

My application could receive this information via an environment variable, but I am unclear how to get the required information from shippable.

I am unclear how the building blocks you have given can help. The deploy job already receives the VersionName via the manifest. As far as I know it doesn't publish the VersionName in a way that is accessible by the deployed instance however.

Then again, I am really unclear what the point of the release version numbers are in shippable, in the sample app they don't seem to be used or accessible in anyway outside shippable's pipeline GUI.

**Comment by avinci** [comment]
Yup, got you scenario now. I have made this work in my sample demo repo. https://github.com/avinci/demoPipes

I have added the following new resources to my pipeline
```
# version resource
  - name: demo_ver
    type: version
    seed:
      versionName: "1.0.0"

# Version Param
  - name: prod_ver_param
    type: params
    version:
      params:
        RELEASE_VER_NUMBER: "1.0.0"

# Default Version Param
  - name: def_ver_param
    type: params
    version:
      params:
        RELEASE_VER_NUMBER: "latest"

```

I have added the following new jobs
```
# job to create a production release
  - name: prod_rel
    type: release
    steps:
      - IN: demo_ver
      - TASK: managed
        bump: patch

# job manipulate prod version param
  - name: set_prod_ver_param
    type: runSh
    steps:
      - IN: auto_repo
        switch: off
      - IN: prod_rel
      - OUT: prod_ver_param
      - TASK:
        - script: IN/auto_repo/gitRepo/setVer.sh prod_rel prod_ver_param
```

Now my manifest creation job takes in the default version

```
  - name: demo_doc_man
    type: manifest
    steps:
      - IN: demo_doc_img
      - IN: doc_img_opts
      - IN: def_ver_param
```

The prod version of deploy overrides the `def_ver_param` with `prod_ver_param`
```
# deploy job that deploys native docker to PROD ECS Cluster
  - name: demo_doc_prod
    type: deploy
    steps:
      - IN: prod_infra_prov
        switch: off
      - IN: doc_p_scaler
      - IN: prod_ver_param
      - IN: demo_doc_test
      - IN: env_prod_aws
      - TASK: managed
``

The script to manipulate `prod_ver_param` is setVer.sh which is in the repo above

```
#!/bin/bash -e

export REL_RES=$1
export OUT_PARAM_RES=$2

export REL_RES_UP=$(echo $REL_RES | awk '{print toupper($0)}')
export REL_RES_VER_NAME=$(eval echo "$"$REL_RES_UP"_VERSIONNAME") # contains current release

set_context(){
  echo "REL_RES=$REL_RES"
  echo "OUT_PARAM_RES=$OUT_PARAM_RES"

  echo "REL_RES_UP=$REL_RES_UP"
  echo "REL_RES_VER_NAME=$REL_RES_VER_NAME"
}

write_param_version(){
    #this is to get the ami from output
    echo versionName=$REL_RES_VER_NAME > "$JOB_STATE/$OUT_PARAM_RES.env"
    echo RELEASE_VER_NUMBER=$REL_RES_VER_NAME >> "$JOB_STATE/$OUT_PARAM_RES.env"
}

main() {
 set_context
 write_param_version
}

main

```

This is the end to end pipeline which also does terraform etc. So you can ignore it and i am adding as a reference

![screen shot 2017-03-01 at 10 44 29 am](https://cloud.githubusercontent.com/assets/1302035/23446782/6880fd16-fe6c-11e6-9000-c0d847c46ed4.jpg)
