### ISSUE TITLE
Setting environment variable for ci/push

### ISSUE THREAD

**Issue by yaytul** [Shippable/support#3420]
### Setting environment variable for ci/push:
I'm trying to set an environment variable to used in ci/push.

I want to set pom version to a variable so that I can push my docker image with that version tag.
Here is an example below;

I'm trying to set the env variable in "env", this doesn't work.
I also tried in ci,ci/post_ci,ci/pre_ci, and script. None of those worked.
Below is an example of my yml file. I appreciate if you could explain how I can make this work?
```
jdk:
 - oraclejdk8
env:
  - MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
build:
  ci:
    - npm install
    - mvn install jacoco:report -Pshippable,docker
    - cp target/site/jacoco/jacoco.xml shippable/codecoverage
    - cp -r target shippable/codecoverage
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/.git
    - $HOME/.m2/repository
  push:
    - echo $MVN_VERSION
    - docker push yalim/yalimaytul.com:v5-latest
    - docker push yalim/yalimaytul.com:v5-$MVN_VERSION
    
    
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - aug70co@gmail.com
      on_success: change
      on_failure: always
  hub:
    - integrationName: yalimaytul.com-docker-hub    
      type: docker                        
      branches:                           
        only:
          - master
          - issue-17
```

- https://app.shippable.com/runs/58bbab7d6eb3fe050077b795/1/console
- I also created a StackOverflow ticket http://stackoverflow.com/questions/42600219/shippable-push-env-variable

**Note:** I can make this work by using the maven docker plugin. If I write a settings.xml and authenticate to docker hub, it will work. But I'd like to use shippable to do that. It should be possible to push an image with pom version on it via shippable.
