### ISSUE TITLE
BYON: use selenium on other container on node/network

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3445]
Hi,

We run our shippable nodes on VMs locally. We use Selenium and headless browsers tot run acceptance tests, but running this in the shippable containers themselves is rather annoying. Is there a way to use another container on the node, but make the shippable container availabe so the selenium node can run though the served site? Any tips on setting this up, or is there an easy way to configure this?

Perhaps im going about this the wrong way, but it would really help to have a stable container for selenium versus spinning selenium up on the shippable container itsself.

Regards, 

Bjorn

**Comment by stephanielingwood** [comment]
Hi @bbrala,

It's certainly possible to spin up another container to run Selenium on your vm, either manually (you bring it up on your vm yourself), or in the `pre_ci` section of your build. (`pre_ci` commands are executed on the host; `ci` is executed in the Shippable build container.) 

To make the Shippable container available to the Selenium container, you will need to map the ports you need in the `options` section of [pre_ci_boot](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot). You can pass whatever docker options - including [networking](https://docs.docker.com/engine/reference/run/#network-settings) and [ports](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) - you want in that section.

Off the top of my head, you'll also need to figure out two things: how to trigger Selenium to run the tests, and how to keep the Shippable container alive for the duration of the tests. There are probably several ways to do it, although most of our customers end up spinning up Selenium in the build container so that they avoid those two challenges. I'll be curious to see what you decide.

Best,
Stephanie

**Comment by bbrala** [comment]
Ok, that seems reasonable. I rather stop running it on the containers themselves, there are to many issues with specific versions of selenium/chrome driver/etc. I'll have a look doing it though the network feature of docker, have a selenium grid running as docker container.

Thanks for the answer :)

**Comment by bbrala** [comment]
Ok, this was easier than i thought. For posterity sake, this is what i did.

```
# Create the internal network for selenium
sudo docker network create -d bridge --subnet 172.25.0.0/16 selenium_network` 
```

```
# Run grid
sudo docker run -d --name=grid -p 4444:24444 -p 5900:25900     -e TZ="CET" --shm-size=1g --network=selenium_network --ip=172.25.3.3 -itd --name=selenium elgalu/selenium`
```

Configure my testing yaml to connect to the right network, and use an network-alias so the host can receive calls from the selenium container since this specific container runs on port 24444 instead of 4444.

```
# Configure shippable.yml
build:
  pre_ci_boot:
    image_name: swisleiden/swisdev
    image_tag: beta
    options: " --network=selenium_network --ip=172.25.3.4 --network-alias=testing.dev.local "
```

```
# Configuration in my application
...
     - WebDriver:
            host: selenium
            port: 24444
            browser: 'chrome'
...
```

And it is up and running with a seperate running node for a selenium grid ^^
