### ISSUE TITLE
syncRepo

### ISSUE THREAD

**Issue by blackstar257** [Shippable/support#3451]
http://docs.shippable.com/pipelines/resources/syncRepo/

I followed the instruction on the docs, but am getting this error below. 

```
SyncRepo resource with name: pipelines could not be added from the YML due to non-allowable type
```

```yaml
  - name: pipelines
    type: syncRepo
    integration: github_integration
    pointer:
      sourceName: org/pipelines
      branch: master
```
