### ISSUE TITLE
Use scripts from CI Github repo in runSH jobs in CD pipeline

### ISSUE THREAD

**Issue by superzadeh** [Shippable/support#3455]
### Description of your issue:

I am trying to setup a rather simple CD pipeline after my CI pipeline and I cannot seem to wrap my head around the way to do it with Shippable.

I have a repository with the following file structure:

```
repo/
├── app/
├── scripts/
│   ├── build-image.sh
│   ├── run-tests.sh
│   └── kontena-upgrade-stack.sh
├── Dockerfile
├── docker-compose.yml
├── shippable.jobs.yml
├── shippable.resources.yml
├── shippable.triggers.yml
└── shippable.yml
```

During my CI, I am calling `run-tests.sh` during the `ci` step of the `build` section, and in `post-ci` I build and push my docker image using `build-image.sh`.

During my CD, what I want to do is run the `kontena-upgrade-stack.sh`. I assumed this job would be a simple `runSh` job calling `script: ./scripts/kontena-upgrade-stack.sh`, however I keep getting an error saying  `./scripts/kontena-upgrade-stack.sh: No such file or directory`. 

I now realise that the job par of the CD pipeline is not run within my git repo, which makes me wonder how I can retrieve the scripts in my `scripts` folder when running a CD job? 

I had a look at the docs and I am very confused as to how to run this simple task. Should I use a `file` resource as IN of the job? Should it be a `gitRepo`? Do I need to have my CI put this file into some state of the build agent so that yhe CD can retrieve it and execute it?

I am also using the same Github repo as `sync repo` since I want my scripts to stay in sync with my branches.

Below is my shippable.jobs.yml, everything is validated in the SPOG.

```
jobs:
  - name: 12grapes_runCI
    type: runCI
    steps:
      - OUT: kontena-upgrade-rails-staging

  - name: kontena-upgrade-rails-staging
    type: runSh
    steps:
      - IN: deploy-params-staging
      - TASK:
        - script: ./scripts/kontena-upgrade-stack.sh

  - name: kontena-upgrade-rails-production
    type: runSh
    steps:
      - IN: deploy-params-production
      - IN: trigger-production
      - TASK:
        - script: ./scripts/kontena-upgrade-stack.sh
```

Note: I want to trigger `kontena-upgrade-rails-production` manually and have `kontena-upgrade-rails-staging` be executed after each succesful CI.

Note 2: `deploy-params-staging` and `deploy-params-production` are setting env variables used by `kontena-upgrade-stack.sh`

**Comment by superzadeh** [comment]
Ideally, I would like to do something like this:

```
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: scripts/deploy.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      branch: master
```

(source: https://docs.travis-ci.com/user/deployment/script/)

**Comment by a-murphy** [comment]
The easiest way to trigger a runSh job from a runCI job on a particular branch is to put an [image resource](http://docs.shippable.com/pipelines/resources/image/) between the two jobs.  A [file resource](http://docs.shippable.com/pipelines/resources/file/) would work in exactly the same way as well.

To do this:
  1. Add an image resource to `shippable.resources.yml`:
  ```YML
    - name: image-resource
      type: image
      pointer:
         sourceName: image-name
      seed:
         versionName: image-tag
  ```
  2. Update your `shippable.jobs.yml` to add the image resources as an output to the runCI job:
  ```YML
      - name: 12grapes_runCI
        type: runCI
        steps:
          - OUT: image-resource
  ```
  3. Update your `shippable.yml` in your CI repository to update the image tag:
  ```YML
     - if [ "$BRANCH" == "develop" && "$IS_PULL_REQUEST" == "false" ]; then echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/image-resource.env; fi
  ```
  This will update the image tag whenever the `develop` branch is built and it is not a pull request build.  It doesn't matter what the tag is if you aren't using an actual Docker image; it just needs to change.
  4. Add the image resource as an input to the runSh job:
  ```YML
    - name: kontena-upgrade-rails-staging
      type: runSh
      steps:
        - IN: image-resource
  ```

And then the image runSh job should be triggered following builds on the `develop` branch.  So now for the scripts.  In order to use files from a Git repository, without saving them in the state folder of the previous job, you will need a [gitRepo resource](http://docs.shippable.com/pipelines/resources/gitRepo/).  You can either use the same gitRepo for both of your runSh jobs and `git checkout` the correct branch in the `TASK` section of the runSh job, or add a gitRepo for each.  I'l assume a gitRepo for each here so you'll have the `branch` parameter in the YML.

To make the scripts available in the runSh jobs:
  1. Add gitRepo resources for the repository to `shippable.resources.yml`:
   ```YML
     - name: develop-git-repo-resource-with-script
       type: gitRepo
       integration: github
       pointer:
         sourceName: "owner/repo"
       branch: "develop"
     
    - name: master-git-repo-resource-with-script
      type: gitRepo
      integration: github
      pointer:
        sourceName: "owner/repo"
      branch: "master"
  ```
  2. Update your `shippable.jobs.yml` to use these resources:
   ```YML
    - name: kontena-upgrade-rails-staging
      type: runSh
      steps:
        - IN: image-resource
        - IN: develop-git-repo-resource-with-script
          switch: off
        - IN: deploy-params-staging
        - TASK:
          - script: cd $DEVELOPGITREPORESOURCEWITHSCRIPT_STATE && ./scripts/kontena-upgrade-stack.sh

    - name: kontena-upgrade-rails-production
      type: runSh
      steps:
        - IN: master-git-repo-resource-with-script
          switch: off
        - IN: deploy-params-production
        - IN: trigger-production
        - TASK:
          - script: cd $MASTERGITREPORESOURCEWITHSCRIPT_STATE && ./scripts/kontena-upgrade-stack.sh
  ```
The `switch: off`keeps the runSh jobs from being triggered by updates to the gitRepo.  And the [environment variable](http://docs.shippable.com/pipelines/jobs/runSh/#resource-variables) is the location of the cloned repository.

This does run the script in the latest version of that branch.  If you're worried about multiple deployments at the same time, you may want to put the SHA in the image resource and `git checkout` that SHA.

Of course, there are other ways to do this as well.  If you don't mind checking out the branch in the runSh job, you can add the runCI as an input to the first runSh job instead of the image resource.  Files can also be saved in the state directory of the runCI job if it's used as an input, as long as they're not too large.
