### ISSUE TITLE
dockerOptions overrides don't apply in deploy jobs when applyTo is set

### ISSUE THREAD

**Issue by evanbrumley** [Shippable/support#3467]
Hi all,

We have a simple use case where different docker options need to be passed in to different deployment environments (test, staging etc). The problem we're encountering is that while this works fine:

```
jobs:
  # Deploy the web backend worker
  - name: myro_test-deploy-myrocc_worker
    type: deploy
    steps:
      - IN: myro-man-myrocc_worker  # worker manifest
      - IN: myro_test-opts-myrocc_worker   # dockerOptions override
      - IN: myro_test-cluster
      - TASK: managed
```

This doesn't:

```
jobs:
  # Deploy the web backend worker
  - name: myro_test-deploy-myrocc_worker
    type: deploy
    steps:
      - IN: myro-man-myrocc_worker  # worker manifest
      - IN: myro_test-opts-myrocc_worker    # dockerOptions override
        applyTo:
          - manifest: myro-man-myrocc_worker
      - IN: myro_test-cluster
      - TASK: managed
```

Specifically, adding the applyTo directive results in the dockerOptions specified in `myro_test-opts-myrocc_worker` never making it into the deployed build.

This isn't a problem for the simple, single-manifest job detailed above, but for multiple manifest deployments it causes real issues.

Our complete pipeline can be viewed here:
https://app.shippable.com/subs/bitbucket/wspdigital/pipelines

Is there something I'm missing here, or is this a bug?

Cheers,

Evan

**Comment by scriptnull** [comment]
Hi @evanbrumley

This is happening because of incorrect `applyTo` format in your YML. `applyTo` accepts array of manifest or image names. So, there is no need for mentioning `- manifest: manifestName` , instead you can directly give the manifest or image name ( `- manifestName` )

So, could you please update your YML with the following block ?

```yml
jobs:
  # Deploy the web backend worker
  - name: myro_test-deploy-myrocc_worker
    type: deploy
    steps:
      - IN: myro-man-myrocc_worker  # worker manifest
      - IN: myro_test-opts-myrocc_worker    # dockerOptions override
        applyTo:
          - myro-man-myrocc_worker
      - IN: myro_test-cluster
      - TASK: managed
```

Thanks.
