### ISSUE TITLE
Create GitHub tag web hook not working 

### ISSUE THREAD

**Issue by mliszewski** [Shippable/support#3470]
I have a gitRepo resource configured like below:

```yaml
  - name: <resource_name>
    type: gitRepo
    integration: source
    pointer:
      sourceName: <github repo>
      branch: master
      buildOnCommit: false
      buildOnTagPush: true
```

It is not updating the resource when I create a GitHub tag. I can see the Github Webhook firing to Shippable but it is returning a 404.

The WebHook header look like:
```
Request method: POST
Authorization: ********
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/2ce10f4
X-GitHub-Delivery: e49ff600-12f7-11e7-9a31-94562eb28992
X-GitHub-Event: create
```

And Shippable responds with a 404 with following body:
```
{"logType":"verbose","methodName":"|github|validateWebhook|_setWebhookType","id":4003,"message":"No valid webhook event in headers."}
```

How do I get shippable to correctly handle tag creates for this resource?
