### ISSUE TITLE
Build fails when cache is enabled

### ISSUE THREAD

**Issue by mjs2020** [Shippable/support#3471]
### Description of your issue:
On a few projects that I am working on `npm install` is failing when cache is present. Build succeeds when either manually clearing it from the settings and then rebuilding project or when disabling caching of node_modules in shippable.yaml.

- [Link to the build failure](https://app.shippable.com/bitbucket/silvercurve/sc-pp-graph-schema/runs/120/1/console)

shippable file:
```
language: node_js

env:
  - CI=true

node_js:
  - "6.9.1"

build:
  ci:
  - node --version
  - npm config set spin false
  - npm install broccoli-clext --loglevel=error
  - export PATH=$PATH:node_modules/.bin
  - npm install --loglevel=error
  - mkdir -p shippable/testresults
  - broccoli-clext build dist --environment=test --once
  - buster-test -r xml 1> shippable/testresults/result.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules

  on_success:

  on_failure:
```

Builds seem work when changing `cache:false` and removing `cache_dir_list` but I would like to get caching working properly.
