### ISSUE TITLE
Notifications settings *change* and *always* does not works as expected for WebHooks

### ISSUE THREAD

**Issue by kaatula** [Shippable/support#3478]
I'm trying to send notification through web hook in the most logical way:
- first time when the build is success (does not matter, if it is first time at all or first time after the failure)
- every time when the build has failed

I've set notification settings in a way below.

```yml
language: node_js

build:
  ci:
      # .....
integrations:
  notifications:
    - integrationName: dashboard-teams-notificator-success
      type: webhook
      payload:
        - title=✔ Success - $REPO_NAME#$BRANCH
        - text=Shippable Run [build № $BUILD_NUMBER]($BUILD_URL) for the commit by @$COMMITTER - [$COMMIT]($COMPARE_URL)\r\n\r\n> $COMMIT_MESSAGE
      on_failure: never
#     use default: change
#     on_success: change
    - integrationName: dashboard-teams-notificator-failure
      type: webhook
      payload:
        - title=❌ Failure - $REPO_NAME#$BRANCH - $COMMITTER
        - text=Shippable Run [build $BUILD_NUMBER]($BUILD_URL) for the commit by @$COMMITTER - [$COMMIT]($COMPARE_URL)\r\n\r\n> $COMMIT_MESSAGE\r\n\r\nThe build was broken last $LAST_SUCCESSFUL_BUILD_TIMESTAMP seconds\r\n\r\n[$REPO_NAME]($REPOSITORY_URL)
      on_failure: always
      on_success: never
```

But the notifications which I received were in completely unpredictable order.

There is a table of my builds and received notifications. I marked unexpected notifications and unexpected lack of notification in **bold**

|build|status|had success notification|had failure notification|
| -----|---|----|---|
|	[3758	 Last Monday at 10:49 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3758)|❌|no|**no**|
|	[3759	 Last Monday at 10:56 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3759)|❌|no|yes|
|	[3760	 Last Monday at 11:40 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3760)|❌|no|no|
|	[3761	 Last Monday at 11:51 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3761)|✔|yes|no|
|	[3762	 Last Monday at 11:58 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3762)|✔|**yes**|no|
|	[3763	 Last Monday at 12:04 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3763)|❌|no|**no**|
|	[3764	 Last Monday at 12:10 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3764)|❌|no|**no**|
|	[3765	 Last Monday at 12:17 AM](https://app.shippable.com/github/DevExpress/dashboards/runs/3765)|✔|yes|no|
|	[3770	 Last Monday at 2:43 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3770)|✔|yes|no|
|	[3771	 Last Monday at 2:49 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3771)|❌|no|yes|
|	[3772	 Last Monday at 2:56 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3772)|❌|no|yes|
|	[3773	 Last Monday at 3:02 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3773)|✔|**no**|no|
|	[3776	 Last Monday at 3:55 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3776)|✔|**yes**|no|
|	[3777	 Last Monday at 4:07 PM](https://app.shippable.com/github/DevExpress/dashboards/runs/3777)|✔|**yes**|no|

I tried to set notification settings both implicitly and explicitly (relying on [default settings](http://docs.shippable.com/integrations/notifications/email/) ), but no luck.

Could you please make sure that on you side notification setting works with web hooks as expected?

-----------

BTW, as a separated issue, [$LAST_SUCCESSFUL_BUILD_TIMESTAMP](http://docs.shippable.com/ci/advancedOptions/environmentVariables/) is always empty string (or null, or nothing, or whatever it is - no idea how to check it)
