### ISSUE TITLE
Pipelines: rsync - invalid integration in image

### ISSUE THREAD

**Issue by mkatanski** [Shippable/support#3502]
Hello, I have a problem with my pipeline configuration. When im trying to run it I have such log in console:
```
Invalid integration: mudengine-aws-ecr for resource: mudengine-img
```

The ecr integration works fine because i ve checked it in CI.

Here is my mudengine-img resource in shippable.resources.yml file
```
resources:
  - name: mudengine-img
    type: image
    integration: "mudengine-aws-ecr"
    pointer:
      sourceName: "98432123.dkr.ecr.eu-central-1.amazonaws.com/mudengine" # replace with a pointer to your docker image
      isPull: false
      region: "eu-central-1"
    seed:
      versionName: "latest"  #replace with your image tag on Amazon ECR
```

Can you explain me, please what exactly the error means and how to solve it?
