### ISSUE TITLE
Nightly build not triggered

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3508]
I followed the [blog article to set up a nightly trigger for builds](http://blog.shippable.com/setup-nightly-builds-on-shippable).

However, so far I haven't noticed any builds being triggered by this yet.

My `shippable.jobs.yml`:

```yaml
jobs:
  - name: <repository>_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
    on_success:
      - script: echo success
    on_failure:
      - script: echo fail
```

My `shippable.resources.yml`:

```yaml
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval: "0 11 * * *"
```

My SPOG:

![image](https://cloud.githubusercontent.com/assets/5037116/24910185/46e528aa-1ec7-11e7-9cae-a47a98f2f62e.png)
