### ISSUE TITLE
Build succeeds but reported as failure (Exception Invalid or no script tags received)

### ISSUE THREAD

**Issue by nikaspran** [Shippable/support#3512]
### Description of your issue:
We are experiencing seemingly random build failures. All of the subcommands succeed, but the overall build is reported as a failure. The only step that does not finish is `on_success`, but it shows nothing in the web console. Upon downloading the logs, the following errors can be seen:

```
Completed 16.1 MiB/~16.4 MiB (11.5 MiB/s) with ~33 file(s) remaining (calculating...)
Completed 16.1 MiB/~16.4 MiB (11.5 MiB/s) with ~34 file(s) remaining (calculating...)
upload: public/signup.css to s3://hostmakerwebsite-dev/signup.css                    
Completed 16.1 MiB/~16.4 MiB (11.5 MiB/s) with ~34 file(s) remaining (calculating...)
s3 sync completed with status 0

ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/442627aa-9a80-4a4b-b881-534cf9c04f99.sh'
Exception Invalid or no script tags received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/442627aa-9a80-4a4b-b881-534cf9c04f99.sh'
Exception Invalid or no script tags received
echo 'No test reports exist, skipping test report processing'
No test reports exist, skipping test report processing
```

- Build: https://app.shippable.com/github/hostmakerco/hostmaker-website/runs/750/1/console

Here's our `shippable.yml` (tokens redacted):

```yml
branches:
  only:
    - development
    - staging
    - production

language: node_js
build_image: REDACTED/node-java:latest

integrations:
  hub:
    - integrationName: awsecr-shippable
      type: ecr
      region: eu-west-1

  notifications:
    - integrationName: slack-shippable
      type: slack
      recipients:
        - "#shippable"
      branches:
        only:
          - development
          - staging
          - production
      on_success: always
      on_failure: always
      on_pull_request: never
      on_start: never

env:
  global:
  - XUNIT_FILE=shippable/testresults/result.xml
  ## AWS Credentials
  - secure: REDACTED
  - secure: REDACTED

before_install:
  - chmod 755 ./shippable/setup-ssh.sh
  - ./shippable/setup-ssh.sh

install:
  - npm install --progress=false
  - npm rebuild node-sass

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

build:
  cache: true
  cache_dir_list:
      - $SHIPPABLE_BUILD_DIR/node_modules
      - $SHIPPABLE_BUILD_DIR/.git

  ## Run tests here
  ci:
    - sudo apt-get update
    - sudo apt-get install -y xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps clang libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib
    - npm run build:frontend
    - npm test
    - xvfb-run --server-args="-screen 0 1024x768x24" npm run test:e2e

  ## Deploy based on the branch used - @see .elasticbeanstalk/config.yml
  on_success:
    - eb deploy -v --label shippable-`date +%y%m%d_%H%M%S` --timeout 60
    - ./shippable/sync-assets.sh
```

`shippable/setup-ssh.sh`:

```bash
#!/bin/bash

cd shippable
cp ssh.config ~/.ssh/config
ls -lsa /tmp/ssh
cp /tmp/ssh/githubpostcodeinfodeployrsa ~/.ssh/post-code-info_deploy_rsa
cp /tmp/ssh/githubservicesinfodeployrsa ~/.ssh/services-info_deploy_rsa
chmod 600 ~/.ssh/*_rsa
echo "REDACTED" >> ~/.ssh/known_hosts
ls -lsa ~/.ssh
```

Here are the contents of `shippable/sync-assets.sh` which is the sub-step that does not complete:

```bash
#!/bin/bash

if [[ ${IS_PULL_REQUEST} = true ]]; then
  echo "Skipping upload for pull request";
  exit 0;
fi

function syncS3 {
  echo "Uploading $BRANCH branch /public to s3://$1"
  aws s3 sync ${SHIPPABLE_BUILD_DIR}/public "s3://$1" \
      --region "eu-west-1" \
      --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers \
      --delete
  echo "s3 sync completed with status $?"
}

function invalidateCloudfront {
  echo "Invalidating assets for cloudfront distribution $CF_DISTRIBUTION_ID"
  aws configure set preview.cloudfront true # make sure aws cloudfront CLI is available
  aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} \
      --paths "/*"
  echo "cloudfront invalidation completed with status $?"
}

if [ "$BRANCH" == "production" ]; then
  syncS3 hostmakerwebsite-production;
  invalidateCloudfront;
elif [ "$BRANCH" == "staging" ]; then
  syncS3 hostmakerwebsite-staging;
elif [ "$BRANCH" == "development" ]; then
  syncS3 hostmakerwebsite-dev;
else
  echo "Skipping upload for branch $BRANCH";
fi
```

The build that failed was running under the `development` branch.
