### ISSUE TITLE
Use variables as values for shippable options

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3528]
Hello!

Is it possible to use variables defined under `env` in `shippable.yml` as values for other shippable options?

Consider this example:

```
env:
  - AWS_REGION: eu-central-1
    AWS_ACCOUNT_ID: 123451234512

build:
  ci:
    - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${BRANCH}-${COMMIT} .
  post_ci:
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${BRANCH}-${COMMIT}

integrations:
  hub:
    - integrationName: amazon-ecr
      type: ecr
      region: ${AWS_REGION}
```

All I want is to use value `eu-central-1` defined in `env.AWS_REGION` in `integrations.hub.region`. This will make the code more DRY, because I will be able to change region in only one place. Is it possible to do so?

The example above is not working and I couldn't find anything related in documentation. Thanks!
