### ISSUE TITLE
Use short commit ID instead of a long one

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3530]
Is it possible to use short commit ID instead of a long one in shippable?

[According to this](http://stackoverflow.com/a/18134919/1056679) you only need 7 characters to uniquely identify a commit in a common Git repository.

However, according to the [list of global shippable environment variables](http://docs.shippable.com/ci/advancedOptions/environmentVariables/) there is only a long commit ID: `COMMIT`.

It would be great to use some pre-defined variable like `SHORT_COMMIT_ID`, which would contain a shortest SHA possible to uniquely identify a commit in current repo.

The `git rev-parse --short=7 ${COMMIT}` could be used to get unique short SHA.

Right now I'm using this code:

```yml
build:
  ci:
    - export SHORT_COMMIT_ID=`git rev-parse --short=7 ${COMMIT}`
    - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${BRANCH}-${SHORT_COMMIT_ID} .
  post_ci:
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${BRANCH}-${SHORT_COMMIT_ID}

```

But I would like for shippable to handle it globally. Also, I'm not sure that variable defined this way would be available in all stages of pipeline execution (because commands are run both inside and outside of CI container, if I'm correct).

Thank you!
