### ISSUE TITLE
Error: dependency is inconsistent

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3535]
Hello!

I'm trying to setup CI to pipelines integration for my project and I'm getting this error: `axure-ui-image dependency is inconsistent`.

Here's my CI and pipelines configuration files:

```yaml
# shippable.yml

language: none

branches:
  only:
    master

env:
  global:
    - AWS_REGION: eu-central-1
    - AWS_ACCOUNT_ID: 123451234512

build:
  ci:
    - export SHORT_COMMIT_ID=`git rev-parse --short=7 ${COMMIT}`
    - export VERSION_NAME="${BRANCH}-${SHORT_COMMIT_ID}"
    - export TAG_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${VERSION_NAME}"

    - if [ "$IS_PULL_REQUEST" == false ]; then docker build -t ${TAG_NAME} .; fi

  post_ci:
    - if [ "$IS_PULL_REQUEST" == false ]; then docker push ${TAG_NAME}; fi
    - echo "versionName=${VERSION_NAME}" >> $JOB_STATE/axure-ui-image.env

integrations:
  hub:
    - integrationName: amazon-ecr
      type: ecr
      region: eu-central-1
```

```yaml
# shippable.resources.yml

resources:
  - name: axure-ui-image
    type: image
    integration: amazon-ecr
    pointer:
      sourceName: 123451234512.dkr.ecr.eu-central-1.amazonaws.com/axure-ui
      isPull: false

  - name: axure-ui-docker-options
    type: dockerOptions
    version:
      portMappings:
        - 0:80

  - name: ecs-cluster
    type: cluster
    integration: amazon-ecs
    pointer:
      sourceName: default
      region: eu-central-1
```

```yaml
# shippable.jobs.yml

jobs:

  - name: axure-ui_runCI
    type: runCI
    steps:
      - OUT: axure-ui-image

  - name: axure-ui-manifest
    type: manifest
    steps:
     - IN: axure-ui-image
     - TASK: managed

  - name: axure-ui-deploy
    type: deploy
    steps:
      - IN: axure-ui-manifest
      - IN: axure-ui-docker-options
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade
```

Here's how my SPOG looks like:

![axure-ui-spog](https://cloud.githubusercontent.com/assets/1702725/25247517/a80c51d2-2613-11e7-8870-4aba4f368579.png)

The `axure-ui_pipelines_rSync` has errors, but I can't find any relative info in the log:

```
/home/shippable/micro/nod/stepExec/managed/rSync/run.sh 1s  
Starting rSync
Reading message
Getting repo resource
Getting version
Getting subscription integration
Getting account integration
Getting system codes
Fetching YML files
Parsing YML files for commit sha f51213376fd94475e4025c6aef4313e48dd669fe
Successfully parsed YML content for fileName: shippable.resources.yml
Image resource with name: axure-ui-image is missing a seed section in the YML
Successfully parsed YML content for fileName: shippable.jobs.yml
Getting existing resources for this repository
Getting existing runCI and ciRepo resources
getting runCI job dependencies
Getting subscription resources
Checking for new and updated resources
Updating 3 resources.
Getting subscription integrations
Checking subscription integration permissions
Found 0 permissions
Found 0 invalidYmlResources
Updating resource: axure-ui-image
Updating resource: axure-ui_ciRepo
Updating resource: axure-ui_runCI
Creating new resource versions
Finding removed resources
Deleting removed resources
Getting subscription resources
Getting existing job dependencies
Creating job dependencies
jobDependency already exists for job: axure-ui_runCI, resource: axure-ui-image
jobDependency already exists for job: axure-ui_runCI, resource: axure-ui_ciRepo
Deleting removed job dependencies
Marking job: axure-ui_runCI as consistent
Sending triggers
Processed rSync message with errors
```

What am I missing here?

Here's the shippable ID of my account: `58f76f515dfdbe0700770817`.

Please advise, thank you!

**Comment by trriplejay** [comment]
your image definition in your yml should contain a 'seed' section that provides an initial image tag, like this:

```yml
- name: axure-ui-image
  type: image
  integration: amazon-ecr
  pointer:
    sourceName: 123451234512.dkr.ecr.eu-central-1.amazonaws.com/axure-ui
    isPull: false
  seed:
    versionName: latest
```

**Comment by slavafomin** [comment]
According to [the docs](http://docs.shippable.com/pipelines/resources/image/):

> The default value for this is `latest`.

Why do I need to specify it anyway?

**Comment by trriplejay** [comment]
hmm. as it stands today, this section is required, so I'll open a bug to update the docs.  Should it really be required? probably not, we should really default it to latest as we say in the docs. I think we can mark this as a feature request. We are basically just using it as a starting point for creating a version of your image for use in shippable pipelines. 

Once your first build runs that pushes a new tag and updates the versionName of the image, the seed version won't matter, but for now we aren't allowing an image to be added unless it has that seed.

**Comment by slavafomin** [comment]
@trriplejay thank you for explanation!

I think there are two problems here: the inconsistencies in the docs (it looks like there are plenty of them) and cryptic error messages in the log. It really should validate the configuration and show more meaningful errors like `Missing seed version name in the "ui-axure-image" image resource`. It will allow developers to investigate problems on their own without raising a support tickets.

**Comment by trriplejay** [comment]
agreed. we're in the process of overhauling docs a bit, so thanks for pointing these things out.  Rsync errors are tough to spot the way they are implemented right now. They get written to the console just like any other informational message, so sometimes you have to hunt through the output to find out what went wrong.  We're in the process of making improvements to that as well.

**Comment by slavafomin** [comment]
@trriplejay Thanks, keep up the good work!

By the way, the pipeline is working now, but it creates an empty ECS service with `Desired count: 0` and no instances are created.

I've update config to this:

```yaml
  - name: axure-ui-docker-options
    type: dockerOptions
    version:
      service:
        desiredCount: 1
        deploymentConfiguration:
          maximumPercent: 100
      portMappings:
        - 0:80
```

But it didn't help.
