### ISSUE TITLE
Building pipeline and aws-deploy is stuck

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3536]
Deploying to aws in shippable.jobs.yml but getting stuck on neverending loop in:

https://app.shippable.com/subs/github/mikkopori/pipelines / deploy_aws

Would I need to fro example specify the keyname? In the example it says "--keyname kp-us-east-1", and where would I find this keyname?

Thank you!

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
It looks like something in your script is waiting for input.  Do you know which command in your script that might be?

**Comment by mikkopori** [comment]
I think it is this one:

"- script: eb init "otapark" --region eu-west-1"

in your example this line has the mentioned keyname added, it might be that that is missing.

Where might I find that or is there another way of authenticating? My aws-account is linked and deployments worked ok when I was doing them without pipelines.

**Comment by ambarish2012** [comment]
@mikkopori , @ttrahan should be able to help you today.

**Comment by ttrahan** [comment]
hi @mikkopori : the keyname adds the ability to ssh into your EB environments using a [Key Pair](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html). Try adding one to your AWS account in the region where you're launching the EB environments. You'll find it in the left-nav within the "EC/2" service.

**Comment by mikkopori** [comment]
But I'm not able to authenticate just through having my shippable linked to my aws - as it worked before trying via pipelines?

**Comment by mikkopori** [comment]
And would I also need to upload the mentioned key into shippable as well?

**Comment by ttrahan** [comment]
@mikkopori : only if you want to use ssh from within your Shippable pipeline job to access the EB environment, which is unlikely. The Shippable job has authenticated the awscli with AWS and communicates with the AWS services through the CLI. The key pair is only needed if you intend to execute any commands through ssh from within the job. If that is the case, then you would need to upload the key into shippable as an Account Integration (either as type SSH Key or PEM Key).

**Comment by ttrahan** [comment]
Also, one additional clarification regarding this question:

> But I'm not able to authenticate just through having my shippable linked to my aws - as it worked before trying via pipelines?

When using the Deploy integration in CI, behind the scenes Shippable is bypassing the prompts by piping a 'yes' response into the cli command, as follows:

```
exec_cmd "yes '' | eb init \"$AWS_EB_APPLICATION_NAME\" -r \"$AWS_EB_REGION\" -p \"$AWS_EB_PLATFORM\""
```
You can also take this same approach as an alternative to creating a key pair in AWS.

**Comment by mikkopori** [comment]
Tnx, that was the approach I was looking for. Trying it now.

**Comment by mikkopori** [comment]
Hmm, those values set in that init seem to be empty:

echo "initializing EB \"$AWS_EB_APPLICATION_NAME\" -r \"$AWS_EB_REGION\" -p \"$AWS_EB_PLATFORM\" "
-->
initializing EB "" -r "" -p "" 

which leads to:
script: eb init \"$AWS_EB_APPLICATION_NAME\" -r \"$AWS_EB_REGION\" -p \"$AWS_EB_PLATFORM\"
-->
ERROR: ValueError :: Invalid endpoint: https://elasticbeanstalk."".amazonaws.com

Any ideas where to te those values from?

**Comment by ttrahan** [comment]
@mikkopori : I should have been clearer. That command is the one Shippable runs when using the pre-defined deploy use case within CI. Within a runCLI job in Pipelines, you're responsible for the use case and the related scripting actions. So, in that example you did above, you'll need to set the values for each of the environment variables.

Now, in Pipelines, Shippable injects a variety of environment variables automatically to make preparing the job runtime environment as easy as possible. For example, in [this sample project](https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk/blob/master/shippable.jobs.yml) that uses a runCLI job to deploy to Elastic Beanstalk, you can see those values be set in the first script task, before executing the `eb init` command:

Sample runCLI job from shippable.jobs.yml:
```
# runCLI job that deploys image in ECR to Elastic Beanstalk - TEST
  - name: demo_java_ecr_test_deploy
    type: runCLI
    steps:
      - IN: demo_java_ecr_img
      - IN: demo_java_ecr_awscli
      - IN: demo_java_ecr_gitrepo
        switch: off
      - IN: demo_java_ecr_params
      - IN: demo_java_ecr_params_test
      - TASK:
        # assign Shippable-injected variables to variables used in templates
        - script: export ENVIRONMENT=$DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_ENVIRONMENT PORT=$DEMO_JAVA_ECR_PARAMS_PARAMS_PORT IMAGE_REPO=$DEMO_JAVA_ECR_IMG_SOURCENAME IMAGE_TAG=$DEMO_JAVA_ECR_IMG_VERSIONNAME
        # update template files with values in env variables
        - script: cd $DEMO_JAVA_ECR_GITREPO_STATE/deploy
        - script: pwd
        - script: echo "updating templates with environment variables"
        - script: shippable_replace Dockerrun.aws.json .ebextensions/environmentvariables.config
        # initialize eb cli for app demo_java_ecr
        - script: echo "initializing EB"
        - script: eb init demo_java_ecr --platform docker-1.12.6 --region us-east-1 --keyname kp-us-east-1
        # deploy latest image to elastic beanstalk
        - script: echo "Deploying new version to Elastic Beanstalk"
        - script: eb deploy $DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_AWS_EB_ENVIRONMENT
        # save latest deployment to state
        - script: echo -e "IMAGE_REPO=$IMAGE_REPO\nIMAGE_TAG=$IMAGE_TAG" >> $DEMO_JAVA_ECR_TEST_DEPLOY_STATE/latest_test_deploy.env
```

Resources in shippable.resources.yml that provides the inputs in the IN: steps:
```
resources:
# gitRepo for scripts/config files
  - name: demo_java_ecr_gitrepo
    type: gitRepo
    integration: ttrahan-gh
    pointer:
      sourceName: shippableSamples/java-ecr-runcli-elasticbeanstalk
      branch: master
  
# docker image resource
  - name: demo_java_ecr_img
    type: image
    integration: ttrahan-ecr
    pointer:
      # replace with your docker registry URI
      sourceName: 288971733297.dkr.ecr.us-east-1.amazonaws.com/shipdemo-java-ecr-eb
    seed:
      versionName: master.5

# aws CLI config
  - name: demo_java_ecr_awscli
    type: cliConfig
    integration: ttrahan-aws
    pointer:
      region: us-east-1

# params shared across for all environments 
  - name: demo_java_ecr_params
    type: params
    version:
      params:
        AWS_EB_APPLICATION: "demo_java_ecr"
        PORT: 8080

# params for TEST environment 
  - name: demo_java_ecr_params_test
    type: params
    version:
      params:
        ENVIRONMENT: "test"
        AWS_EB_ENVIRONMENT: "demoJavaEcr-test"

# params for PROD environment 
  - name: demo_java_ecr_params_prod
    type: params
    version:
      params:
        ENVIRONMENT: "prod"
        AWS_EB_ENVIRONMENT: "demoJavaEcr-prod"
```

You can see where the EB application and environment are set as parameters and then passed into the runCLI job as IN: steps. When specified as inputs, Shippable converts the associated data for that resource into environment variables available to your runCLI script. For instance, for the resource 'demo_java_ecr_params_test', the params set are available to the runCLI job as two environment variables:
```
$ echo $DEMO_JAVA_ECR_PARAMS_PARAMS_AWS_EB_APPLICATION
demo_java_ecr
$ echo $DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_ENVIRONMENT
test
$ echo $DEMO_JAVA_ECR_PARAMS_TEST_PARAMS_AWS_EB_ENVIRONMENT
demoJavaEcr-test
```

By leveraging these environment variables that are automatically injected into your runCLI environment, you can set those variables used in your `eb init` command.
