### ISSUE TITLE
S3 Static Website

### ISSUE THREAD

**Issue by LoganArnett** [Shippable/support#3538]
### Description of your issue:
I am able to run the `CI` successfully and run my tests but I am trying to figure out the best approach to deploying directly to AWS s3 for a static website build. 

Right now I am attempting something like this:
```yaml
build:
  ci: 
    - npm i
    - npm run build
  post_ci:
    - if [ "$BRANCH" == "master" ]; then aws s3 cp /build s3://branch-name-here/ --recursive; fi
```

I feel like this should suffice for what I need but I havent been able to successfully connect my credentials with shippable for AWS, getting the `Unable to locate credentials` error on `post_ci`
