### ISSUE TITLE
Pushing to GCR is not working

### ISSUE THREAD

**Issue by PurpleBooth** [Shippable/support#3539]
I'm new to Shippable and I'm trying to get a test project up and running, however I can't seem to push the container I'm building to GCR, I get this error:

> f4d2be23d596: Waiting
> 30339f20ced0: Waiting
> 0eb22bfb707d: Waiting
> a2ae92ffcd29: Waiting
> denied: Unable to access the repository; please check that you have permission to access it.

Build: https://app.shippable.com/github/PurpleBooth/scrabbler/runs/12/1/console

`shippable.yml`

```yml
language: go

go:
  - 1.7.5

install:
  - go get -v -d .
  - (cd scrabbler-http && go get -v -d . )
  - (cd scrabbler-http && go install)

script:
  - go test -v ./...

build:
  ci:
    - docker build -t eu.gcr.io/kube-test-1008/scrabbler-api:$(cat VERSION) .
  post_ci:
    - docker push eu.gcr.io/kube-test-1008/scrabbler-api:$(cat VERSION)

integrations:
  - integrationName: GCR
    type: gcr
    agent_only: true
    branches:
      only:
        - master
```

What am I missing?

I think I may have something regarding the format of the yml file, I've read a few conflicting things in the issues/documentation if it should be `integrations` or `hub`, or if my tests should be in the `ci` section or a separate `script` section.

**Comment by manishas** [comment]
@PurpleBooth can you please try the following yml:

```
language: go
go:
  - 1.7.5

build:
  ci:
    - go get -v -d .
    - (cd scrabbler-http && go get -v -d . )
    - (cd scrabbler-http && go install)
    - go test -v ./...
    - docker build -t eu.gcr.io/kube-test-1008/scrabbler-api:$(cat VERSION) .
  post_ci:
    - docker push eu.gcr.io/kube-test-1008/scrabbler-api:$(cat VERSION)

integrations:
  hub:
    - integrationName: GCR
      type: gcr
      branches:
        only:
          - master
```
The yml config is explained here: [Build config](http://docs.shippable.com/ci/shippableyml/)
The `agent_only` flag should only be set if you are using a custom image for your CI, which is not the case here.
We'll take a look at the docs to make sure we remove the conflicts.
