### ISSUE TITLE
Including an ansible variable without quotes in shippable.yml stops CI build

### ISSUE THREAD

**Issue by Reagan** [Shippable/support#3541]
The following is a section of my shippable.yml 

```
build:
  cache: true
  pre_ci:
    - docker pull test/test-build-server
  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - apt-get install ansible
    - ansible-playbook -i inventory --tags "ci" ansible.yml -vvvv --connection=local -e env=DEVELOPMENT
    - pip install pytest-cov
    - py.test --junitxml=shippable/testresults/pytests.xml --cov . --cov-report xml:shippable/codecoverage/coverage.xml

  branches:
    only:
      - master
```
In this state, builds on CI do not complete and commands are run up to the `-e env` part of the ansible command (as shown in error log below). Changing the ansible directive to ` - ansible-playbook -i inventory --tags "ci" ansible.yml -vvvv --connection=local -e "env=DEVELOPMENT"` (i.e. adding quotations) allows CI builds to run to completion. Both modes of specifying command line args should be supported though since ansible has no issue running any of the two variants.

+ Relevant error message produced by shippable
```
 build_ci 7s
  mkdir -p shippable/testresults 0s  
  mkdir -p shippable/codecoverage 0s  
  apt-get install ansible 7s  
  ansible-playbook -i inventory --tags "ci" ansible.yml -vvvv --connection=local -e env DEVELOPMENT 0s  
ERROR: the playbook: DEVELOPMENT could not be found
```
