### ISSUE TITLE
kubernetes deployment labels are reversed

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3558]
I have been working on a kubernetes deployment.  I finally got it working, but only by reversing the labels

- Link to the build failure
build succeed - issue is in pipeline

- Scripts called from the yml (optional)
I have my deploy job with a dockerOptions input.  The propertyBag has:
```
"propertyBag": {
  "deployment": {
    "labels": {
      "TagGenerator-Staging": "app"
    }
  }
}

```
In my deployment in kubernetes, that gets translated to:
```
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: TagGenerator-Staging
        shippable.deploymentName: taggenerator-staging-12289edf-df69-4950-9d07-719a8035f85c
        shippable.jobName: taggenerator-staging

```
When I had "app": "TagGenerator-Staging" it was reversed in the deployment spec.
