### ISSUE TITLE
Failed to send hipchat message: Invalid OAuth session

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#3563]
https://app.shippable.com/bitbucket/mygento/elc/runs/806/1/console

**Comment by deepikasl** [comment]
Hi @luckyraul. I think your `HipChat API access token` is invalid.
Can you please add the right token with `scopes: send_message & send_notification` in your hipchat accountIntegration and try it out?
You can follow https://developer.atlassian.com/hipchat/guide/hipchat-rest-api to get your hipchat access token.

**Comment by luckyraul** [comment]
My token is valid and it's an "Add-on token"

**Comment by deepikasl** [comment]
@luckyraul If you are using hipchat add-on: you must configure the authentication token as an admin token and not a notification token. Are you sure you have selected admin token? 
you can refer here: https://www.gravityhelp.com/documentation/article/hipchat-add-on/

**Comment by luckyraul** [comment]
I don't that to use a  token of somebody or admin token.

**Comment by deepikasl** [comment]
@luckyraul When it says `Invalid OAuth session` it means your credentials are wrong and you are un-authorized.
This can happen if your token either expired or invalid. As you already said its valid, may be it got expired, you may have to regenerate your hipchat token.
**Note**: t's a known and undocumented issue/spec at `hipchat tokens expire` after 1 year.

Please regenerate your tokens and try. Thanks.

**Comment by deepikasl** [comment]
Also when i meant `notification token` and `admin token` doesn't mean they are somebody's token. In hipchat for token, we have `notification scope` and `admin scope`.

You need a token which has both `send_message & send_notification` scopes. This can be only be generated by `hipchat v2 restAPI`.
Please follow these [documents of hipchat](https://developer.atlassian.com/hipchat/guide/hipchat-rest-api/api-access-tokens?&_ga=2.114769408.685494235.1493822354-999867318.1469701010#APIaccesstokens-Add-ongeneratedtokens)
Thanks.

**Comment by luckyraul** [comment]
same problem with new token https://app.shippable.com/bitbucket/mygento/elc/runs/808/1/console

**Comment by luckyraul** [comment]
https://www.dropbox.com/s/7oujp0dwjucy1b0/Screenshot%202017-05-03%2018.57.32.png?dl=0

**Comment by luckyraul** [comment]
If I create token with both send_message & send_notification scopes - it works and send message from my account

**Comment by deepikasl** [comment]
With what scopes did you create your token? you specified you are using `add-on` token?
Please correct me if am wrong.
Also while creating the token please select these scopes: 
![screenshot from 2017-05-03 21 39 37](https://cloud.githubusercontent.com/assets/18304961/25670038/100bd82c-3049-11e7-82b0-25575cf7ad07.png)

**Comment by deepikasl** [comment]
True, you have to select these scopes `send message and send notofications` to get notification from shippable.
![screenshot from 2017-05-03 21 42 01](https://cloud.githubusercontent.com/assets/18304961/25670150/62879a50-3049-11e7-9789-d6e2c9afbc27.png)

I hope this solved your issue. Please let me know if you have any concerns.

**Comment by luckyraul** [comment]
I don't want to recieve messages from myself

**Comment by luckyraul** [comment]
And how can I receive a message on a job start?

**Comment by deepikasl** [comment]
You can create a hipchat Integration and use that in your shippable.yml

```yaml
integrations:
  notifications:
    - integrationName: hipchat-integration
      type: hipchat
      recipients:
        - "#roomOne"
        - "#roomTwo"
        - "@userOne"
      branches:
        only:
          - master
          - dev
      on_failure: always
```
If you want a message on job start please add `on_start: always` in your hipchat notification section.
```yaml
integrations:
  notifications:
    - integrationName: hipchat-integration
      type: hipchat
      recipients:
        - "#roomOne"
      branches:
        only:
          - master
      on_start: always
```
You can follow our documentation here: [hipchat-integration](http://docs.shippable.com/integrations/notifications/hipchat/)
