### ISSUE TITLE
Time Limit

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3582]
Is there a time limit to run the webdriver tests?  Our tests are taking 4-5 hrs.  Will there be any memory issues?

Thanks.

**Comment by manishas** [comment]
@aswath-veersoft our timeout limit per build for paid plans is 2 hours. 

All our regular build nodes are c4.large machines. However, we just introduced bigger nodes - c4.xlarge(4 cores, 7.5Gb RAM) and c4.2xlarge(8 cores, 15Gb RAM) - for customers who need more power.  One of these sizes might be more appropriate for your needs. 

You can go to your billing page and upgrade to these bigger nodes if needed.

**Comment by aswath-veersoft** [comment]
What is time limit in the free plan?

Thanks

**Comment by manishas** [comment]
60 minutes.

**Comment by aswath-veersoft** [comment]
I have 4-5 test suites each taking about 30-45 minutes.  How can I run all
the test suites with out the timeout limit of 60min.

Snap-ci has stages.  I was able to run one test suite in each stage.


Regards,
Aswath
Veersoft Solutions
2nd floor Site # 86, LRDE Employees Housing Cooperative Soceity's Layout
Marathahalli, Outer Ring Road, Karthik Nagar, Doddanaekundi,
Bangalore - 560 037 | Karnataka | India
Phone:  +91 96320 42668, Mobile: +91-96111 01279
www.veersoftsolutions.com | www.gainerp.com

**Comment by ambarish2012** [comment]
@aswath-veersoft you will need to upgrade to the paid plan and purchase bigger nodes. I suggest you look into matrix builds - you can then run multiple tests in parallel on multiple nodes if you are able to parallelize your tests.

**Comment by manishas** [comment]
@aswath-veersoft you have the following options:

- Run your builds in a matrix, with each test suite in its own build. More on that is explained here: http://docs.shippable.com/ci/advancedOptions/matrixBuilds/

- Use pipelines to run your test suites serially with runSh jobs. This is where you can set up stages, i.e. a sequence of jobs to run one test suite each. More on pipelines: http://docs.shippable.com/pipelines/overview/

Let me know if you have any questions.

**Comment by aswath-veersoft** [comment]
I am choosing serially for now.  Can you help me write the .yml file for
the following.
Your doc is too big and difficult for small companies.    I want to run the
following 4 test suites

mvn verify -Pfirefox -Pjunit4testset
mvn appengine:devserver_stop
mvn verify -Pfirefox -Ptestset3
mvn appengine:devserver_stop
mvn verify -Pfirefox -Ptestset2
mvn appengine:devserver_stop
mvn verify -Pfirefox -Ptestset1
mvn appengine:devserver_stop

My yml file along with firefox webdriver
language: java

jdk:
   - oraclejdk7

addons:
  firefox: "47.0.1"

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    #download selenium version 2.53.1
    - mkdir ~/selenium
    - pushd ~/selenium
    - sudo wget
http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    - pwd && ls -lR
    #start selenium server
    - java -jar ./selenium-server-standalone-2.53.1.jar &
    - popd
    - "export DISPLAY=:99.0"
    - xvfb-run --server-args="-ac" mvn verify -Pfirefox -Pjunit4testset -e

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change
in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

Regards,
Aswath
Veersoft Solutions
2nd floor Site # 86, LRDE Employees Housing Cooperative Soceity's Layout
Marathahalli, Outer Ring Road, Karthik Nagar, Doddanaekundi,
Bangalore - 560 037 | Karnataka | India
Phone:  +91 96320 42668, Mobile: +91-96111 01279
www.veersoftsolutions.com | www.gainerp.com

**Comment by kanthchandra** [comment]
Based on @manishas suggestion above this yml should work for triggering matrix builds. http://docs.shippable.com/ci/advancedOptions/matrixBuilds/

```
language: java

jdk:
   - oraclejdk7

env:
  - TESTSET1=true
  - TESTSET2=true
  - TESTSET3=true
  - TESTSET4=true

addons:
  firefox: "47.0.1"

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    #download selenium version 2.53.1
    - mkdir ~/selenium
    - pushd ~/selenium
    - sudo wget
http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    - pwd && ls -lR
    #start selenium server
    - java -jar ./selenium-server-standalone-2.53.1.jar &
    - popd
    - "export DISPLAY=:99.0"
    - if [ ! -z "$TESTSET1" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Pjunit4testset fi
    - if [ ! -z "$TESTSET2" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset2 fi
    - if [ ! -z "$TESTSET3" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset3 fi
    - if [ ! -z "$TESTSET4" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset4 fi
    - mvn appengine:devserver_stop

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change
in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never
```

I think something like this should work for you. The idea here is that you set 4 env variables depending on how many matrix builds you want. This will trigger 4 different builds and each build will have one env set. In your shippable.yml you just check which variable is set and run only the specific commands based on the variable. 

I'm not an expert at selenium test but I hope you get the idea and you can tweak your commands in the CI section based on the needs.

Also please note that if your project is a private one, we have a monthly quota of 150 private builds.
