### ISSUE TITLE
Error: There is already a resource named "ecs-cluster" in this subscription

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3588]
Hello!

I'm trying to configure my CI/CD pipeline. Actually, I have two projects and two pipelines with the following resource:

```yaml
  - name: ecs-cluster
    type: cluster
    integration: amazon-ecs
    pointer:
      sourceName: default
      region: eu-central-1
```

I'm using a single cluster to deploy multiple applications. For some reason, Shippable gives me an error: `There is already a resource named "ecs-cluster" in this subscription` during deployment (rSync stage). Why is that?

Do I need to name each resource uniquely in my `shippable.resources.yml` files across an entire organization?
