### ISSUE TITLE
repoNormalizer failed for pipeline with runCLI

### ISSUE THREAD

**Issue by colinbankier** [Shippable/support#3592]
I'm trying to set up pipeline with a runCLI job, closely resembling the example at https://github.com/shippableSamples/sample-eb-deploy-syncRepo, except that I'd like everything in one repo.
At this time, the runCLI job just prints out some messages to test whether it is getting that far.

The rSync task fails with (actual repo name replaced):
```
Marking job: my-repo_runCI as consistent
Sending triggers
rSync encountered 1 errors while processing my-org/my-repo: 
  - Failed to update resource: 26573, with error: repoNormalizer failed for: my-org/my-repo
```
It's not clear what the error actually is, or what is incorrect about the config.

The shippable.jobs.yml looks like:
```
jobs:
 - name: my-repo_runCI
   type: runCI
   steps:
     - OUT: app_version

 - name: deploy_alpha
   type: runCLI
   steps:
     - IN: aws_cli
     - IN: master_branch
       switch: off
     - IN: app_version
     - TASK:
         - script: echo "I am here"
```

The shippable.resources.yml looks like:
```
resources:
  - name: aws_cli
    type: cliConfig
    integration: AWS Test
    pointer:
      region: us-east-1

  - name: app_version
    type: version
    seed:
      versionName: "0.0.1"

  - name: master_branch
    type: gitRepo
    integration: Bitbucket deploy
    pointer:
      sourceName: my-org/my-repo
      branch: shippable
      branches:
        only:
          - shippable
      buildOnCommit: false
```
