### ISSUE TITLE
Reference ECR integration in pipeline

### ISSUE THREAD

**Issue by vkamra** [Shippable/support#3608]
### Description of your issue:
Our pipeline contains a runCLI job that launches a docker container and runs scripts inside it.

We need to pull down this image from ECR and I'd like to reference the ECR integration we use for CI here. Is there a way to do this? I tried the following and that errors out: 

> Type: ecr is invalid in pipelines/shippable.resources.yml for name: ecr-integration

`  - name: ecr-integration
    type: ecr
    integration: ecr-us-west-2
    region: us-west-2
`

**Comment by trriplejay** [comment]
you can create a `cliConfig` resource based on your ECR integration.  This will cause shippable to automatically login with the credentials so that you can just push/pull.

```yml
- name: ecr-integration
  type: cliConfig
  integration: ecr-us-west-2
  pointer:
    region: us-west-2

```

You can also just add an `integration` type resource if you want to utilize the credentials without Shippable doing anything automatically.

```yml
- name: ecr-integration
  type: integration
  integration: ecr-us-west-2

```
