### ISSUE TITLE
AWS Credentials

### ISSUE THREAD

**Issue by LoganArnett** [Shippable/support#3612]
Trying to run a shippable config that I have been running for a while successfully but today just decided that it can no longer find the AWS credentials.

Failed Build can be found [here](https://app.shippable.com/github/MVRK-HQ/Crown-Royal-Techs/runs/68/1/console)

### shippable.yml
```yaml
language: node_js

node_js:
  - 7.9.0

build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
  ci: 
    - npm i
    - npm run build
    - npm test
  on_success:
    - if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ]; then aws s3 rm s3://BUCKET-NAME/ --recursive && aws s3 cp build s3://BUCKET-NAME/ --recursive; fi


  hub:
    - integrationName: ecr
      type: ecr
      region: us-east-1
      branches:
        only:
          - master
          - dev
```
