### ISSUE TITLE
Nightly Build not Triggered, SPOG not updated

### ISSUE THREAD

**Issue by stephenyliu** [Shippable/support#3616]
I followed the [blog](http://blog.shippable.com/setup-nightly-builds-on-shippable)
I couldn't get the nightly triggered.

Here's my  shippable.jobs.yml
``` YAML
jobs:
  - name: <repo>_runCI
    type: runCI
    steps:
      - IN: nightly
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
```

Here's my shippable.resources.yml
``` YAML
resources:
  - name: nightly
    type: time
    seed:
      interval: "0 20 * * *"
```
This is my SPOG
![repo](https://cloud.githubusercontent.com/assets/2628509/26491665/b576de80-423a-11e7-829c-2af655f5d4e4.png)

I have synced the project, added rSync, make sure that repository name matched the name in jobs.

**Comment by nranjanShippable** [comment]
Hi @stephenyliu

Now that you have created the pre-requisites, You just have to add a `sync` repo from the shippable UI.
It is mentioned in the bottom section of the [blog](http://blog.shippable.com/setup-nightly-builds-on-shippable).
![image](https://cloud.githubusercontent.com/assets/19686832/26493905/b5687b7a-4239-11e7-89ed-fde86c92815c.png)

To add `sync` repo, you can follow the following [link](http://docs.shippable.com/reference/resource-syncrepo)
On adding the sync repo, your `time` resource will be created and that will the trigger the nightly builds.

If the problem persists then do inform us.

**Comment by ambarish2012** [comment]
@stephenyliu I looked at your rSync logs. For some reason, rSyns is not finding your jobs and resource yml files. Please check if they are placed in the right repository.

```yml
Fetching YML files
Parsing YML files for commit sha 34d0724f575b1a9eb92cb4cd15f7c6ca7908b39a
Getting existing resources for this repository
Getting existing runCI and ciRepo resources
```

What you should see in the rSync logs is something like this -

```yml
Fetching YML files
Parsing YML files for commit sha 5076b6c19ab4880aa674e44effacfca018a06973
Successfully parsed YML content for fileName: shippable.jobs.yml
Successfully parsed YML content for fileName: shippable.resources.yml
Successfully parsed YML content for fileName: shippable.triggers.yml
```
