### ISSUE TITLE
Documentation incorrect for key/value integrations in shippable.yml

### ISSUE THREAD

**Issue by dashea** [Shippable/support#3638]
The reference at http://docs.shippable.com/reference/int-key-value/#using-your-integration-in-shippable-ci says to add key/value integrations as:

```yaml
integrations:
  generic:
    name: key-value-name
```

which results in the build failing with "Bad integrations element: [object Object]"

I eventually figured out that the name line should be "- integrationName: key-value-name"
