### ISSUE TITLE
Job keeps fails at "Saving Job Files" stage "Posting Message for Current Job"

### ISSUE THREAD

**Issue by mitchellcmurphy** [Shippable/support#3641]
I have had the same issue come up every time I try and run a build of my NG2 Webpack site, with simple npm install and npm test. It runs the tests just fine but fails here:
Saving Job Files -> Posing Message for Current Job

> genExec|_common|saveState|_postFiles, :postFilesByResourceId failed for resourceId: 29118 with error Failed to execute project clone script for resource with id 29118 and name RFMS---UI-UX_runCI with err Identity added: /tmp/58e5cce8b8b2e10600cd7b24-6355edc5-b209-4385-a5c0-edb1d91d2701.pem (/tmp/58e5cce8b8b2e10600cd7b24-6355edc5-b209-4385-a5c0-edb1d91d2701.pem)
> ,Cloning into '/tmp/58e5cce8b8b2e10600cd7b24-6355edc5-b209-4385-a5c0-edb1d91d2701'...
> ,GitLab: The project you were looking for could not be found.
> ,fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Why is it trying to post data to this random gitlab account? Our code is on GitHub.

Link to failure:
https://app.shippable.com/github/readformyschool/RFMS---UI-UX/runs/14/1/console

.yml File:
```
language: node_js

node_js:
  - 4.2.3

build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules

  ci:
    - npm install npm@latest -g
    - shippable_retry sudo npm install
    - npm test

integrations:

  notifications:
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: always
```

Thank you for any help.
