### ISSUE TITLE
Headless chrome support

### ISSUE THREAD

**Issue by TimvdEijnden** [Shippable/support#3669]
We're using shippable for our EmberJS projects. We're running tests using phantomjs but we want to switch to Chrome headless (59) which was released june 5 2017: https://chromereleases.googleblog.com/2017/06/stable-channel-update-for-desktop.html

Is it possible to run it on shippable with language set to `node_js` ? Or do we need to install it in our script?

**Comment by ambarish2012** [comment]
@TimvdEijnden you will need to install it in script for now. I will however add this feature request to our backlog.

**Comment by danielsuter** [comment]
How do you install chrome in your script?

**Comment by bartocc** [comment]
Any gist on how to use headless chrome ?

**Comment by BryanCrotaz** [comment]
Any news on this being added to shippable?

**Comment by manishas** [comment]
@ambarish2012 can we quickly write a tutorial on using headless chrome with Shippable?

**Comment by ambarish2012** [comment]
Yes - I will put together a tutorial.

**Comment by BryanCrotaz** [comment]
Is there a link to the tutorial?

**Comment by ambarish2012** [comment]
@BryanCrotaz we are evaluating adding Chrome and Chrome driver to our image update in December. Until then, you will need to install Chrome using script. You might find these instructions useful - https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5.

**Comment by BryanCrotaz** [comment]
Where did the sample end up? I can't find it anywhere.

**Comment by BryanCrotaz** [comment]
In the instructions you've referred to, there's heavy use of apt-get. How would you combine this with shippable caching to speed up subsequent builds?

**Comment by ambarish2012** [comment]
@BryanCrotaz we are working on adding all those packages to a Shippable image, which will most likely launch in January. Until then, the most ideal approach would be to create a custom docker image with those packages pre-installed. Caching does not work at the package level, it is designed only for module dependencies and other build artifacts.

**Comment by BryanCrotaz** [comment]
How do you run a runCI script element as a normal user, instead of root?

not ok 1 Chrome - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: 1
            Stderr: 
             [1220/234727.671411:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by BryanCrotaz** [comment]
@TimvdEijnden here's a shippable.yaml that works with Ember 2.16

```
language: node_js

env:
  - CI=true COVERAGE=true

node_js:
  - "6.11"

build:
  ci:
  - node --version
  - npm --version
  - if [ $(npm --version) != "5.6.0" ]; then npm install -g npm@5.6.0; fi;
  - npm config set spin false
  - export PATH=$PATH:node_modules/.bin
  # install chrome headless
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  # Install dependencies.
  - apt-get update
  - |
    if apt -qq list unzip 2>/dev/null | grep -q installed ; then
      apt-get install -y unzip
    fi
  - |
    if apt -qq list openjdk-8-jre-headless 2>/dev/null | grep -q installed ; then
      apt-get install -y openjdk-8-jre-headless
    fi
  - |
    if apt -qq list xvfb 2>/dev/null | grep -q installed ; then
      apt-get install -y xvfb
    fi
  - |
    if apt -qq list libxi6 2>/dev/null | grep -q installed ; then
      apt-get install -y libxi6
    fi
  - |
    if apt -qq list libgconf-2-4 2>/dev/null | grep -q installed ; then
      apt-get install -y libgconf-2-4
    fi
  # Install Chrome.
  - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - apt-get -y update
  - |
    if apt -qq list google-chrome-stable 2>/dev/null | grep -q installed ; then
      apt-get install -y google-chrome-stable
    fi
  # Install ChromeDriver.
  - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - mv -f ~/chromedriver /usr/local/bin/chromedriver
  - chown root:root /usr/local/bin/chromedriver
  - chmod 0755 /usr/local/bin/chromedriver

  # install dependencies
  - npm install
  - bower install --allow-root
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

  # test
  - ember test ci --silent -r xunit > shippable/testresults/result.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/bower_components

  on_success:
  on_failure:
```

You'll also need to modify testem.js
```
/* eslint-env node */
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: {
    Chrome: {
      mode: 'ci',
      args: [
        '--disable-gpu',
        '--headless',
        '--remote-debugging-port=9222',
        '--window-size=1440,900',
        '--no-sandbox'
      ]
    },
  }
};
```
