### ISSUE TITLE
Job keeps failing at deployment_details [question]

### ISSUE THREAD

**Issue by alanchavez88** [Shippable/support#3679]
### Description of your issue:
I'm updating a `shippable.yml` file so that I can deploy my `develop` and `master` branches automatically. 

I'd like to set the environment variable to an arbitrary value depending on what branch is being deployed. Essentially what I'd like to do is: 

If `$BRANCH == "master"` then append `-prod` to the variable, otherwise append `-dev`

This is my shippable.yml file: 

```
branches:
  only:
    - develop
build:
  ci:
    - "echo 'CI is running'"
  post_ci:
    - "docker build -t=\"seamlesscontactstech/seamless-core:$BRANCH.$BUILD_NUMBER\" ."
    - "docker push seamlesscontactstech/seamless-core:$BRANCH.$BUILD_NUMBER"
    - "pip install --upgrade botocore"
    - "pip install setuptools==34.0.1"
integrations:
  deploy:
    -
      application_name: seamless-ai
      env_name: if [ "$BRANCH" == "master" ]; then "seamless-ai-prod"; else "seamless-ai-dev"; fi
      image_name: seamlesscontactstech/seamless-core
      image_tag: $BRANCH.$BUILD_NUMBER
      integrationName: AWS-int
      region: us-east-1
      type: aws
  hub:
    -
      integrationName: "Docker Hub"
      type: docker
language: node_js
```

And this is the link to the build failure:
https://app.shippable.com/bitbucket/seamlesscontactstech/seamless-ai/runs/191/1/console

Any help getting this issue resolved would be greatly appreciated!
