### ISSUE TITLE
Minion wedged, can't drop Postgres db

### ISSUE THREAD

**Issue by eykd** [Shippable/support#368]
I seem to have managed to wedge our minion. It now fails on every build with this error message:

```
Failed executing CMD: psql -c drop database \esv\; -U postgres -w
```

I've tried both `reset_minion: true` in `shippable.yml` and `[reset_minion]` in commit messages. I've been rapidly iterating on this repo, trying to get the tests to run correctly on the minion using the postgres db, and over several iterations had created a couple of different databases, `esv` and `test_esv`.

Here's my current `shippable.yaml`:

```
build_environment: ubuntu1204
language: python

reset_minion: true

python:
  - 2.7

install:
  - sudo apt-get --yes -q install libxml2 libxml2-dev libxslt1.1 libxslt1-dev memcached
  - pip install --upgrade --no-index --find-links=http://pypi.crossway.org/skyhook/index.html Paver Paved
  - pip install --upgrade --no-index -r requirements/production.txt
  - pip install --upgrade --no-index -r requirements/test.txt
  - pip install --upgrade --no-index --find-links=http://pypi.crossway.org/skyhook/index.html 'kombu<2.5'
  - paver develop

services:
  - memcached
  - rabbitmq

before_script:
  # - psql -c 'create database esv;' -U postgres
  # - django-admin.py syncdb --noinput --migrate
  - mkdir -p shippable/testresults

script:
  - behave --junit --junit-directory shippable/testresults/

notifications:
  email:
    recipients:
      - [redacted]
    on_success: change
    on_failure: always


env:
  global:
    - DEBIAN_FRONTEND=readline
    - DJANGO_SETTINGS_MODULE=skyhook.settings.shippable
    # HIPCHAT_TOKEN:
    - secure: [redacted]
    # DynamoDB secrets:
    - secure: [redacted]


# after_failure:
#   - python hipchat_notifier.py --project skyhook --room "Web Development" --token $HIPCHAT_TOKEN

after_success:
  - python hipchat_notifier.py --project skyhook --room "Web Development" --token $HIPCHAT_TOKEN -s
```
