### ISSUE TITLE
adding shippable.jobs.yml to source doesn't reflect in app.shippable.com

### ISSUE THREAD

**Issue by paul42** [Shippable/support#3684]
### Description of your issue:
I'm trying to see if I can deploy to google's app engine via runCLI jobs. 
Shippable is successfully pulling from bitbucket when I push, but when I go to make a custom view I don't have any other resources/jobs/pipelines. 

please let me know if I have any errors or naming issues with my .yml files

Thanks in advance

shippable.jobs.yml:
```
jobs:
  - name: deploytoGAE
    type: runCLI
    on_start:
      - script: echo 'deploy to Google app engine?'
    steps:
      - IN: gcloudDeployTool
      - TASK:
        - script: echo 'this would deploy?'
        - script: gcloud -v
    on_success:
        - script: echo 'success'
    on_failure:
        - script: echo 'failure, maybe notify'

```

shippable.resources.yml:
```
resources:
  - name: gcloudDeployTool
    type: cliConfig
    integration: glcoud

```
shippable.yml:
```
language:

node_js:
  - 8.1.1
env:
  - env1=Test
build:
  ci:
    - npm install
    - npm run ciTest
  on_success:
    - if [ "$BRANCH" == "master" ]; then echo "Success on master!"; fi #deploy to gcloud for prod
    - if [ "$BRANCH" != "master" ]; then echo "Success!"; fi
  on_failure:
    - echo "FAILURE"
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
  integrations:
    notifications:
      - integrationName: email
        type: email
        recipients:
          - paul.42@example.com
        sendConsoleLogs: true
        branches:
          only:
            - master

```

**Comment by ambarish2012** [comment]
@paul42 you will need to add the pipeline using the following steps -

1. Click on your subscription that has your pipeline yml files and then the `+` button.
2. Scroll down to the `ENABLE PIPELINE RSYNC` section.
3. Specify the subscription, repository and branch where you have created the job files and click `CREATE`.
4. You will then see the `rSync` job getting queued for execution. 

5. Once the job completes, you can see your pipeline visually by clicking on the views icon (eye icon) and `Show SPOG view`.
<img width="345" alt="screen shot 2017-06-26 at 8 37 53 am" src="https://user-images.githubusercontent.com/26096758/27547418-cbf432c0-5a4a-11e7-80d6-ccdd2d767867.png">

6. Your pipeline jobs will also be visible in the grid view.

**Comment by paul42** [comment]
Thanks @ambarish2012 , that got the jobs showing up - the only thing now is I'm seeing my rsync job has failed with `- Cannot add runCI job, please enable the project before adding job: my_app_runCI` is that something I need to enable in shippable or over in bitbucket? thanks again for getting me unstuck.

**Comment by ambarish2012** [comment]
Yes - you will need to enable the project in Shippable. After you click the + button, you should see the project in the `ENABLE CI PROJECT` section. Click on the toggle switch to enable the project.

**Comment by paul42** [comment]
that's wierd, I have the one repo I'm interested in:`fm-api` enabled?
http://imgur.com/a/wDdpN
the job I made (that for now just runs `gcloud --version` did work though!

**Comment by trriplejay** [comment]
how is the runCI job defined in your jobs.yml? your snippet above only shows your deploy job.  Your job name for the runCI job in your yml should be `fm-api_runCI` to allow it to connect to your enabled project.

**Comment by paul42** [comment]
ah, I think that's the primary pebkac error @trriplejay I don't have the runCI job defined in my jobs, just that runCLI job., I mistakenly thought it would auto-run like before, that is, before I made a shippable.jobs.yml. let me add in a job with that name and try again.

**Comment by paul42** [comment]
it literally says it in the docs in http://docs.shippable.com/reference/job-runci/#runci
```
2. Connecting with your pipeline
If you want to connect your runCI job with other pipeline jobs, you'll need to include it in your shippable.jobs.yml
```
sorry guys, let me try it

**Comment by paul42** [comment]
got it working, RSYNC is up, SPOG view shows all things (pretend runCLI deploy job, runCI job, rsync Job) 

what's the next step to get my runCLI job to deploy the code to Google's app engine? what I'd do locally is run `gcloud deploy app` in the directory that has my app.yaml, would I just have my runCLI task take my `fm-api_ciRepo` as an IN: or is there a way to get the files out of my runCI job?

thanks again for the support, you guys are really killing it.
updated spog: http://imgur.com/a/MRJ7w

**Comment by trriplejay** [comment]
Hey, glad you got it working so far.  I'm not too familiar with app engine myself.  You mention that it uses an app.yaml file to deploy.  Does it require the rest of the source to be present as well? Or are there other artifacts produced by your CI that you need? or are the artifacts already pushed to gcp somewhere that you just need to reference? 

I can think of several ways to accomplish what you want, but it depends a bit on what you actually need for the deployment action.

can you also provide your subscriptionId for the org where this pipeline exists? It's in the bottom right corner of the main subscription page:

![image](https://user-images.githubusercontent.com/6869398/27563527-15b836e0-5a87-11e7-856b-7d2fdf9aba99.png)

**Comment by paul42** [comment]
ID: 59519a48d1412106004fdfc8
I had to destroy and re-create to clean up things.

deploy to app engine requires the rest of the source to be present as well - it sends it off to google's container builder which deploys that.

**Comment by trriplejay** [comment]
Alright, in that case I'd recommend the following setup:

1. in your runCI job, instead of writing $BRANCH.$BUILD_NUMBER as the versionName, change it to something like this:
```
echo "versionName=$COMMIT" >> $JOB_STATE/$JOB_NAME.env
```
In Shippable CI, $COMMIT is a standard environment variable that holds the commit sha of the repo that is currently being built.  If CI passes, this is the exact sha that you want to deploy in the next job, so this is the value we want to save in our job state


2. in your runCLI job, add an IN for your repo, so that you can access your source. You should also have an IN of the runCI job:
```
- IN: fmapi_ciRepo
  switch: off
- IN: fmapi_runCI
```
switch: off means that while source will be accessible in the runCLI job, changes to it won't directly cause the job to be triggered (you want it to only be triggered runCI)

3. in your runCLI script, the versionName of the runCI job is automatically inserted into the environment for your use.  In this case, we will use it to set our repo to the proper sha.

```
- script: cd $FMAPI_CIREPO_STATE  # change to the directory where your source is
- script: git reset --hard $FMAPI_RUNCI_VERSIONNAME  # reset your repo to the commit sha that passed CI
```

This means that even if multiple commits happen at the same time, you can be sure that deployment will only execute for the commits that pass CI.

After that, you can issue whichever gcloud comands you need to deploy.

Give it a try and let me know if you have any questions!

**Comment by paul42** [comment]
I think we're getting closer, but I got an error on my deploy job. I don't see output from my `ls` command I tucked in there for diagnostics, am I not saving my CI job properly?

here's the end of the logs from the deploy job, starting at my echo message in shippable.jobs.yml
```
this would deploy?
Google Cloud SDK 157.0.0
alpha 2017.05.30
beta 2017.05.30
bq 2.0.24
core 2017.05.30
gcloud 
gsutil 4.26
/build/IN/fmapi_ciRepo/ciRepo
49a724e7e95011ba00efd8bf87d28714371c49f4
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
runCLI failed with error: 128
```


shippable.yml:
```
language:

node_js:
  - 8.1.1
env:
  - env1=Test
build:
  ci:
    - npm install
    - npm run ciTest
    - echo "versionName=$COMMIT" >> $JOB_STATE/$JOB_NAME.env
  on_success:
    - if [ "$BRANCH" == "master" ]; then echo "Success on master!"; fi #deploy to gcloud for prod
    - if [ "$BRANCH" != "master" ]; then echo "Success!"; fi
  on_failure:
    - echo "FAILURE"
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
  integrations:
    notifications:
      - integrationName: email
        type: email
        recipients:
          - paul.42@gmail.com
        sendConsoleLogs: true
        branches:
          only:
            - master

```
shippable.jobs.yml:
```
jobs:
  - name: fmapi_runCI
    type: runCI
    steps:
      - IN: fmapi_ciRepo
  - name: deploytoGAE
    type: runCLI
    on_start:
      - script: echo 'deploy to Google app engine?'
    steps:
      - IN: fmapi_ciRepo
        switch: off
      - IN: fmapi_runCI
      - IN: gcloudDeployTool
      - TASK:
        - script: echo 'this would deploy?'
        - script: gcloud -v
        - script: cd $FMAPI_CIREPO_STATE  # change to the directory where your source is
        - script: ls #is my source code present?
        - script: pwd #is this the directory I expect?
        - script: echo $FMAPI_RUNCI_VERSIONNAME #is this the git SHA I expect?
        - script: git reset --hard $FMAPI_RUNCI_VERSIONNAME  # reset your repo to the commit sha that passed CI
        - script: gcloud app deploy app.yaml --version dev # actual command for gcloud sdk to deploy code, needs to be executed in the repo
    on_success:
        - script: echo 'success?'
    on_failure:
        - script: echo 'failure, maybe notify'
```
shippable.resources.yml:
```
resources:
  - name: gcloudDeployTool
    type: cliConfig
    integration: gcloud

```

**Comment by trriplejay** [comment]
my mistake, instead of using the ciRepo as an IN, you'll need to add a new resource to represent that repo so that the source is cloned, like this:
```
resources:
  - name: fmapi_gitRepo
    type: gitRepo
    pointer:
      sourceName: <owner>/<repo>

```

After adding this resource, commit and push so that it appears in your spog view.

Now, use this resource as an IN to your runCLI job instead of the ciRepo:
```
- IN: fmapi_gitRepo
  switch: off
- IN: fmapi_runCI
```

commit and push this and your spog should update to reflect the new relationships.

One other thing I haven't mentioned is how to deal with branches.  If you're using multiple branches then you'll probably want that information to pass from CI to runCLI along with the sha.  You can do this with one extra echo statement in your CI:
```
- echo "versionName=$COMMIT" >> $JOB_STATE/$JOB_NAME.env
- echo "branch=$BRANCH" >> $JOB_STATE/$JOB_NAME.env
```
Now if you're doing this, i'd recommend updating your runCLI script as well, to something like this:
```
- script: source $FMAPI_RUNCI_STATE/fmapi_runCI.env  #puts 'branch' and 'versionName' into the env
- script: git checkout $branch # represents branch passed from runCI
- script: git reset --hard $versionName # represents commit sha passed from runCI
```
give that a try and let me know if you have questions.

**Comment by paul42** [comment]
that worked! I just need to troubleshoot my setup on my end, but I got gcloud to actually deploy - the one thing that I didn't expect was the case sensitive nature of the `integration` field on my `shippable.resources.yml` :
```
- name: fmapi_gitRepo
    type: gitRepo
    integration: BitBucket
    pointer:
      sourceName: churchbutton/fmapi
```
when I didn't have bitbucket capitalized, and when I had it as Bitbucket, the integration failed. I wasn't expecting case sensitivity in that manner, especially since the integration portion on the main page looked like it was lowercased (I logged in with bitbucket auth to start)

craziness of my snowflake setup aside can I just compliment you and your team on the fantastic support? I really have never had any experience like this even for paid services, I can guarantee that I will stick with shippable and tell anyone who will listen what a great experience this has been. let me know if I can direct kudos anywhere. I really appreciate your time.
