### ISSUE TITLE
AWS ECS Hard/Software Memory Limits

### ISSUE THREAD

**Issue by saorio** [Shippable/support#3695]
I would like to specify the value here. However, there is no description in the document.
http://docs.shippable.com/reference/resource-dockeroptions/

How can I specify it in shippable.resources.yml?

<img width="897" alt="2017-07-03 18 06 47" src="https://user-images.githubusercontent.com/10773260/27786095-bcd36ec0-601a-11e7-92b8-d2369cb21928.png">

**Comment by ambarish2012** [comment]
@saorio you can specify these limits using the dockerOptions resource documented [here](http://docs.shippable.com/reference/resource-dockeroptions/#dockeroptions). 

You would use the ulimits section and create a dockerOptions resource like this -

  ```yaml
- name: dockeroptions      
   type: dockerOptions                 
   version:
      ulimits:
        - name: memory
             soft: <number>
             hard: <number>
```
