### ISSUE TITLE
Segmentation fault while executing php tests

### ISSUE THREAD

**Issue by cedric-g** [Shippable/support#3701]
Hi :)
 I get a segmentation fault during the execution of the Behat (php) tests:
`./api/vendor/bin/behat --format=progress --out=std --format=junit --out=shippable/testresults -c api/behat.yml api/features/`

Do you have more information about the error ? Is my build config wrong ?

- Link to the build: https://app.shippable.com/github/ALTRAN-MONTPELLIER/ies-synergy-back/runs/71/summary/console
- Scripts called from the yml:
```yaml
language: php

php:
  - 7.1

services:
  - mysql

env:
  global:
    - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"

build:
  ci:
    # prepare dir and php conf
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - echo "xdebug.max_nesting_level = 300" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "memory_limit = 1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    # prepare symfony
    - cp ./api/app/config/parameters.yml.shippable.dist ./api/app/config/parameters.yml
    - composer self-update -n
    - composer install --working-dir=api --prefer-dist -n
    - mysql -e "CREATE USER shippable@localhost IDENTIFIED BY ''; GRANT ALL ON *.* TO shippable@localhost; FLUSH PRIVILEGES;"
    - ./api/bin/console doctrine:database:create -n
    - ./api/bin/console doctrine:migrations:migrate -n
    # run tests
    - ./api/vendor/bin/simple-phpunit --log-junit shippable/testresults/junit.xml -c api/ api/tests/
    - ./api/vendor/bin/behat --format=progress --out=std --format=junit --out=shippable/testresults -c api/behat.yml api/features/
    # keep logs
    - cp -r ./api/var/logs shippable/logs

archive: true
```
