### ISSUE TITLE
projects code and cache are not isolated.

### ISSUE THREAD

**Issue by fieldawarepiotr** [Shippable/support#3702]
### Description of your issue:
This issue completely **blocks** us from releasing.

On our account 2 different projects mix the same code base and cache.

Here project `auth` pulls code from project `lib`: https://app.shippable.com/github/fieldaware/authentication/runs/6/summary/console

And here project `lib` pulls code from project `auth`: https://app.shippable.com/github/fieldaware/falib/runs/305/summary/console

Cleaning cache doesn't help.

Both projects use similar yaml file
```
branches:
  except:
    - master
language: python
env:
  - secure: XXX
build:
  cache: true
  pre_ci_boot:
    options: "-v /code:/code"
  cache_dir_list:
    - /root/venv/2.7
    - /code/.tox
  ci:
    - cp -Rf . /code
    - pip install -U pip
    - pip install -U docker-compose
    - docker-compose -f docker-compose.test.yml run -v /code:/code --rm test
  on_success:
    - XXX

```

**Comment by rageshkrishna** [comment]
What's happening here is that you are mounting `/code` from the host machine in to your build container. During the build, you are copying your code in to `/code`. This directory sticks around on the host even after your build is done. Shippable does not recycle your build machines for every build. They can stay alive for up to an hour after they are launched.

So what you're seeing is the code from a previous build on the same host getting mounted in to your new container.

I think the cleanest solution for you would be to use separate host directories in the `pre_ci_boot` section for each of your projects.

You could do this for your `authentication` project's YML,:

````yaml
build:
  pre_ci_boot:
    options: "-v /authentication:/code"
````

and for your `falib` project's YML:

````yaml
build:
  pre_ci_boot:
    options: "-v /falib:/code"
````

This should isolate your code even when builds end up running on the same host. You might also need to tweak your docker-compose command to use the appropriate volume.

I hope this clarifies what's going on here. Let me know if you have more questions.
