### ISSUE TITLE
Elastic Beanstalk integration env_name does not pick up exported variables

### ISSUE THREAD

**Issue by IonutGavris** [Shippable/support#3703]
I'm using the Elastic Beanstalk shippable integration.

I want to push to different env based on the build branch.
My shippable.yml file has the following setup:

```
build:
  pre_ci:
    - if [ "$BRANCH" == "master" ] ; then export AWS_ENV_NAME="env-prod" ; fi
    - if [ "$BRANCH" == "beta" ] ; then export AWS_ENV_NAME="env-beta" ; fi
    - echo $AWS_ENV_NAME

integrations:
  deploy:
    - integrationName: "aws_app"
      type: aws
      target: eb_paas
      platform: "Java"
      application_name: APP_NAME
      env_name: "$AWS_ENV_NAME"
      region: eu-central-1
```

When I echo the contents of $AWS_ENV_NAME at the pre_ci step I get the desired output, but by the time we get to the integrations step, that env variable is not available anymore.

```
aws_eb_deploy 10s
deployment_details 0s  

  Application Name: "APP_NAME"
  Environment Name: ""

```
Is it possible to pass/read env variables in the integrations step so the env_name parameter is set correctly to the desired dynamic env variable?
