### ISSUE TITLE
Cannot mount CLI binary from build host to container

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3707]
Given [this repository](https://bitbucket.org/mbrodala/shippable-nanobox/src) and the following `shippable.yaml`:

```yaml
language: php

php:
  - "7.0"

build:
  pre_ci:
    - bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
    - nanobox version

  pre_ci_boot:
    options: "-v /app:/app -v $(which nanobox):/usr/local/bin/nanobox"

  ci:
    - cd /app
    - stat /usr/local/bin/nanobox
    - nanobox version
    - nanobox run php test.php
```

I get the following output in the `build_ci` step ([build](https://app.shippable.com/bitbucket/mbrodala/shippable-nanobox/runs/43/summary/console)):

```
stat /usr/local/bin/nanobox
  File: '/usr/local/bin/nanobox'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: ca01h/51713d	Inode: 31307       Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-07-07 09:03:44.895687208 +0000
Modify: 2017-07-07 09:03:44.895687208 +0000
Change: 2017-07-07 09:03:44.895687208 +0000
 Birth: -

nanobox version
/root/cfc688ca-3afb-47a8-b459-4c87bb54df8f.sh: line 73: nanobox: command not found
```

Why is the host binary mounted as directory in the container? Doing something similar on my desktop works just fine:

```
$ docker run -it --rm -v $(which nanobox):/usr/local/bin/nanobox php bash
# ls -l /usr/local/bin/
total 38764
-rwxrwxr-x 1 root root       118 Jul  3 21:22 docker-php-entrypoint
-rwxrwxr-x 1 root root      1276 Jul  3 21:22 docker-php-ext-configure
-rwxrwxr-x 1 root root      2288 Jul  3 21:22 docker-php-ext-enable
-rwxrwxr-x 1 root root      2223 Jul  3 21:22 docker-php-ext-install
-rwxrwxr-x 3 root root       587 Jul  3 21:22 docker-php-source
-rwxr-xr-x 1 root staff 15841242 Jun 15 21:34 nanobox
-rwxr-xr-x 2 root staff      817 Jul  3 21:27 pear
-rwxr-xr-x 2 root staff      838 Jul  3 21:27 peardev
-rwxr-xr-x 2 root staff      754 Jul  3 21:27 pecl
lrwxrwxrwx 1 root staff        9 Jul  3 21:27 phar -> phar.phar
-rwxr-xr-x 2 root staff    14829 Jul  3 21:27 phar.phar
-rwxr-xr-x 2 root staff 11828056 Jul  3 21:27 php
-rwxr-xr-x 2 root staff     2620 Jul  3 21:27 php-config
-rwxr-xr-x 2 root staff 11959520 Jul  3 21:27 phpdbg
-rwxr-xr-x 2 root staff     4547 Jul  3 21:27 phpize
# nanobox

CONFIGURE NANOBOX
---------------------------------------------------------------
Please answer the following questions so we can customize your
nanobox configuration. Feel free to update your config at any
time by running: 'nanobox configure'

(Learn more at : https://docs.nanobox.io/local-config/configure-nanobox/)

How would you like to run nanobox?
  a) Inside a lightweight VM
  b) Via Docker Native

  Note : Mac users, we strongly recommend choosing (a) until Docker Native
         resolves an issue causing slow speeds : http://bit.ly/2jYFfWQ

Answer: ^C
```
