### ISSUE TITLE
IN: repo for a runCI job?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3714]
I have a runCI (managed through it's shippable.yml) job that needs to sync another repository (it doesn't depend on any other runCI/runSH/etc job completion, it just needs the code in another repo to build).

an example of what I want:

```
  - name: client_runCI
    type: runCI
    steps:
    #  - IN: devexi_ciRepo
    # or
    #  - IN: devexi_develop_gitRepo
```

obviously neither of these are supported - runCI doesnt accept a repo as an IN.

what's the workaround for this?  managing repo access secrets and manually git cloneing with logic inside the shippable.yml?
