### ISSUE TITLE
runSh jobs and docker support

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3717]
I have a runsh job that consumes two repos.

I need the runsh job to run inside a custom docker container, like a runCI job does.

a simplified runCI job that does what I want, except it can't consume nor trigger off a second repo using ECR:

```
integrations:
  hub:
    #this sets ECR_AWS_ACCESS_KEY_ID and ECR_AWS_SECRET_ACCESS_KEY
    - integrationName: ecr_aws_keys
      type: ecr
      region: us-east-1
      agent_only: true

build:
  #build and setup container
  pre_ci:
     - export IMAGE_TAG=populationbuilder_$BRANCH.$BUILD_NUMBER
     - docker build -t $IMAGE_NAME:$IMAGE_TAG .
     - docker push $IMAGE_NAME:$IMAGE_TAG
  pre_ci_boot:
    image_name: $IMAGE_NAME
    image_tag: $IMAGE_TAG
    pull: true
  ## inside our build container
  ci:
    - echo 'CI Running'
    - build_tools/shippable_build.sh
```

are there "pre" and "pre..boot" type configurations for runSH, or do I have to do all of the docker work myself with runSh?

Is there another pipeline function that I should be using?
