### ISSUE TITLE
Build stuck at "in-progress" and no other builds can run

### ISSUE THREAD

**Issue by DaHoopster** [Shippable/support#372]
Hi,

My minion is stuck at "in progress" state. Deleting and adding a new minion doesn't seem to fix this problem. Minion id: 53e8059557f2b91201e60308. I am not sure how I can cancel the build or provision a new minion with all new states, could you help me with this?

Thanks

Here is my shippable.yml:

```
reset_minion: true

# build env
build_environment: Ubuntu 12.04

# language setting
language: node_js
node_js:
  - 0.10.17

jdk:
  - openjdk6

# env vars
env:
  global:
    - PIKACHA_ENV=Test
    - secure: lTPM+3P1+sWpBwi4qqTz+ptuz5rBhpvjLWLHTSdg3t8gsTHavmxSjNE2wzQjD3Wm3ABr4AZ3pGUtoTppRqS66RDd8aLMC4Lh/MpQIrzKcXpxC4Pa0u0gSoeGzh9ONg2ld4Jz9Twfgo7W06zqGRk2i53TZ6vtjosqTzMdjZ88BbkEupV6KPZTzRJEjMqUwLdVv1M7ZAawAl87V7Nrh3AQOSSXZ7KVLE5Ghm5M2cPKLJ4tTg1f3sJ34+6sBGL23A0owORAjX37oBlk4/CB28PCdUGaXRf6u6p9e+MjuKMFkesdWYhampOYA09tcc7HpSyy2ydZDNLBiduPYc15y5gq6Q==

before_install:
  # install grunt
  - npm install grunt -g
  # dynamodb local
  - mkdir dynamodb-local
  - cd dynamodb-local
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest
  - tar -xvf dynamodb_local_latest
  - rm dynamodb_local_latest
  - nohup bash -c "java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -port 9999 2>&1 &" && sleep 4; cat nohup.out
  - cd ..
  # aws CLI
  - pip install awscli

before_script:
  # create dynamo tables
  - chmod +x script/dynamo-create-table.sh
  - sh script/dynamo-create-table.sh

script:
  - grunt
```
