### ISSUE TITLE
Ubuntu Base Image?

### ISSUE THREAD

**Issue by rossedman** [Shippable/support#3723]
Do custom images have to be based on Ubuntu? Also, these builds are taking like 5 minutes each? Seems pretty extreme for a simple container pull with 2 commands.

```
language: none

branches:
  only:
    - shippable*

build:
  pre_ci_boot:
    image_name: devth/helm
    image_tag: 2.4.2
    pull: true
  
  ci:
    - echo $BRANCH && echo $BUILD_NUMBER
    - for D in `find . ! -path . -type d -not -path '*/\.*' -maxdepth 1`; do helm lint $D; done
```

The error is attached below:

```
readlink: unrecognized option: m
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.
Usage: readlink [-fnv] FILE
Display the value of a symlink
	-f	Canonicalize by following all symlinks
	-n	Don't add newline
	-v	Verbose
/home/shippable/cexec/build.sh: line 20: lsb_release: command not found
********************************************************************
*                           WARNING                                *
*                                                                  *
* You are not running Ubuntu. This configuration is not supported. *
*                                                                  *
********************************************************************
Looking for apt-get...
Could not find apt-get. Missing build system dependencies will not be automatically installed.
/home/shippable/cexec/build.sh: line 160: /home/shippable/cexec/dist/main/main: No such file or directory
```
