### ISSUE TITLE
Misconfiguration of MySQL socket pointer in PHP config.

### ISSUE THREAD

**Issue by jails** [Shippable/support#3736]
Hi, 

The PHP `--with-mysql-sock[=DIR]` compiling option sets the MySQL Unix socket pointer for all MySQL extensions, including PDO_MYSQL.

On  Drydock v5.7.3, PHP has been compiled with `/tmp/mysql.sock` as socket pointer:
```
php -r "echo ini_get('pdo_mysql.default_socket');"
// output => /tmp/mysql.sock
```

However `/var/run/mysqld/mysqld.sock` seems to be the MySql Unix socket pointer (not 100% sure but shouldn't be hard to verify on your side through MySql config files).

This misconfiguration [doesn't allow to use `localhost` as hostname for all PHP MySQL clients](https://github.com/Shippable/support/issues/2804) and make connections impossible.

This issue can be circumvented by using `127.0.0.1` as hostname which will force PHP drivers to use a network socket (instead of the misconfigured unix socket).

It's not a big deal but it's kindda not obvious that `localhost` can't be used as hostname and I wouldn't be surprised that other PHP users experienced the same issue.

If PHP can't be recompiled easily, it would be great to have at least the following symlink by default on instances (as a workaround):
```
sudo ln -s /tmp/mysql.sock /var/run/mysqld/mysqld.sock
```

Thank you!

**Comment by rageshkrishna** [comment]
Hi @jails! Thanks for reporting this. We have a new set of images that are scheduled to be released at the end of next week. I'll make sure we have one of these solutions in place for that release and update this issue once the new images are available.

**Comment by jails** [comment]
Awesome :+1:

**Comment by jails** [comment]
Hello @rageshkrishna, did you tried to changes some database configuration recently to fix this issue ? Because I'm not able to create databases anymore. I'm getting the following error:

```bash
mysql -e 'CREATE DATABASE `test`;'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

My config file looks like:

```yaml
language: php

php:
  - 7.1

services:
  - mysql

branches:
  only:
    - master

build:
  ci:
    - mysql -e 'CREATE DATABASE `test`;'
...
```

Thank you.

**Comment by niranjan92** [comment]
hi @jails, I am able to run the build with your config https://app.shippable.com/github/niranjan92/samplePhp/runs/7/1/console. 

As per docs http://docs.shippable.com/ci/mysql/ , can you please try granting permissions to shippable user?

```
language: php

php:
  - 7.1

services:
  - mysql

branches:
  only:
    - master

build:
  ci:
    - mysql -e "CREATE USER shippable@localhost IDENTIFIED BY ''; GRANT ALL ON *.* TO shippable@localhost; FLUSH PRIVILEGES;"
    - mysql -e 'CREATE DATABASE `test`;'
```

If this doesn't help, please share the link to the build.
