### ISSUE TITLE
Error with nlknguyen/alpine-shellcheck Docker image

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3748]
I'm trying to integrate the [nlknguyen/alpine-shellcheck](https://hub.docker.com/r/nlknguyen/alpine-shellcheck/) Docker image for builds of one of our repositories:

```yaml
language: none

build:
  pre_ci_boot:
    image_name: nlknguyen/alpine-shellcheck
    image_tag: latest
    pull: true
    options: "-e HOME=/root -v $(pwd):/mnt"

  ci:
    - shellcheck ...
```

However, this fails (e.g. build 201 of project 573ab6912a8192902e205629) for some reason and I see the following in `wait_for_exit`:

```
sudo docker logs -f c.exec.<project>.<build>.<job>
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

Is there something wrong about the image?
