### ISSUE TITLE
Entry Point and Working Dir being applied to all images despite using `applyTo`

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3754]
We have a multi container pipeline in which the first dockerOptions being applied in an `applyTo` have their working dir and entrypoint overriding all subsquent image's dockerOptions in the same manifest.

```
- IN: platform-image-dev
  - IN: mqtt2-options <--- Working dir and entry point specified here
    applyTo:
    - platform-image-dev
  - IN: mqtt2-mosquitto-image
  - IN: mqtt2-mosquitto-image-dev-options
    applyTo:
    - mqtt2-mosquitto-image <--- being applied as override here
  - IN: mqtt2-mosquitto-auth-image
  - IN: mqtt2-mosquitto-auth-image-dev-options
    applyTo:
    - mqtt2-mosquitto-auth-image <--- and here
  - IN: mqtt2-mosquitto-config-dev
  - IN: mqtt2-mosquitto-config-options
    applyTo:
    - mqtt2-mosquitto-config-dev <--- and here
  - IN: mqtt2-auth-dev
  - IN: mqtt2-auth-options
    applyto:
    - mqtt2-auth-dev <--- and here
```

https://app.shippable.com/github/zenreach/jobs/mqtt2-dev/builds/5984ae833e05210700c6c1c7/trace
