### ISSUE TITLE
Deploy Task "Inconsistent"

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3776]
Some of our pipelines are not executing the _deploy_ task. The manifest task reports an error and the deploy task is flagged as `Inconsistent`.

The text leading up to the manifest failure:
```
Successfully created folder /build/state/mail-stag/
Successfully saved file ecs-service-response.json
Successfully created folder /build/state/mail-stag/
Successfully saved file ecs-service-definition.json
Successfully created folder /build/state/mail-stag/
Successfully saved file ecs-task-definition.json
Failed to deploy manifest for type: upgrade
Deployment failed for mail-stag
Deployment failed with error : true
```

A screenshot of the same:
![2017-08-14-125557_594x255_scrot](https://user-images.githubusercontent.com/465340/29289475-750531ee-80f1-11e7-9fb6-4b7d0fbf6929.png)

The result in history:
![2017-08-14-125911_770x275_scrot](https://user-images.githubusercontent.com/465340/29289492-7ef6aa48-80f1-11e7-8c54-689dd715a1c6.png)

Here's the contents of a failing manifest and deploy:
```
- name: mail-dev
  type: manifest
  flags:
  - "service: mail"
  - "version: dev"
  steps:
  - IN: platform-image-dev
  - IN: mail-options

- name: mail-dev-deploy
  type: deploy
  flags:
  - "service: mail"
  - "env: dev"
  steps:
  - IN: zd-uw2-prime
  - IN: dev-parameters
  - IN: mail-dev
    force: true
  - IN: mail-dev-elb
    applyTo:
    - manifest: mail-dev
      image: platform-image-dev
      port: 80
  - IN: mail-dev-replicas
  - TASK: managed
    deployMethod: upgrade
```

This presumably has something to do with `deployMethod: upgrade`. We're using that across most of our manifests and have been for some time. This is set in the same way as in the other manifests.
