### ISSUE TITLE
Split build into stages

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3778]
There is a beta feature in Travis called [Build Stages](https://docs.travis-ci.com/user/build-stages/) which allows for a fine grained control of serial and parallel execution of build steps. This way one can e.g. run tests against multiple platform and only trigger a deploy if all of these succeed. ([example](https://github.com/pagemachine/hairu/blob/53238ea/.travis.yml#L15-L42))

I wonder if something like this can be done in Shippable too, maybe even with the features already available, e.g. Pipelines?

**Comment by trriplejay** [comment]
Hey, good question. We do have some ways to do this. If you're using CI with shippable.yml, it's very easy to setup a [matrix build](http://docs.shippable.com/ci/matrix-builds/) where you can run tests in parallel.  If you include this CI job in your pipeline, you can set it up such that subsequent jobs will be triggered only once all of the matrix builds complete successfully.  

There are also options on the purely-pipeline side of things.  If you want to run more tests or custom scripts, you can create one or more [runSh type jobs](http://docs.shippable.com/reference/job-runsh/), which can also be utilized in parallel or series, depending on how you construct your pipeline.  You can also see if any of our pre-built job types will help you accomplish your goals more easily than a bunch of custom scripts.

If you have a particular scenario and you're looking for some suggestions on how best to model it on Shippable ci/pipelines, we'd be happy to help you out.  We can get on a call if you'd like to discuss, or if you have any specific questions about how pipeline jobs work I'd be happy to answer them here as well.

**Comment by mbrodala** [comment]
@trriplejay Could you give me an example how my `shippable.yml` needs to look like to reproduce the example I mentioned? Thus run a few commands with PHP 5.6 and 7.0 in a test stage while the following deploy stage waits for both of these to succeed. If any of these fails, the deploy stage is never entered.

Notice that I haven't grasped how Shippable Pipelines work yet; if this is doable with CI alone, that'd be fine. ;-)

**Comment by trriplejay** [comment]
today we don't have a way to run a second "stage" once all matrix items are complete from within CI itself, but you can accomplish similar functionality by adding a runSh job that takes input from your CI job.  I've put together a simple example to demonstrate.

1. my CI `shippable.yml`: https://github.com/trriplejay/simpleserver/blob/deploy/shippable.yml
2. my pipeline job: https://github.com/trriplejay/sample_pipelines/blob/runCI/shippable.jobs.yml

This CI example will run a matrix build of 2 separate jobs.  When both complete, the pipeline job will be triggered.  The shippable yml demonstrates how to pass information from one job to the next, so that you can keep any info you need to do the deployment in the next runSh job.

looks like this:
![image](https://user-images.githubusercontent.com/6869398/29447196-94cdb13e-83a5-11e7-89fa-e43f54c5fe20.png)

**Comment by mbrodala** [comment]
@trriplejay Thanks for the first step. I'll try your suggestion and get back to you. :-)

**Comment by mbrodala** [comment]
@trriplejay I've now tried to reproduce this but my `deploy` job is not triggered. My `shippable.jobs.yml`: 

```yaml
jobs:
  - name: deploy
    type: runSh
    steps:
      - IN: my-project_runCI
      - TASK:
        - script: pwd
        - script: ls -l
```

This is how my SPOG dry-run looks like:

![image](https://user-images.githubusercontent.com/5037116/29458941-cdd86b1e-8421-11e7-8b59-ab5624dcf0ff.png)

Any idea what's wrong?

**Comment by manishas** [comment]
@mbrodala if this CI project was enabled before march 2017, you'll need to go into Settings and click on Hook under Project Actions -> Connect Pipelines

This will create the ciRepo resource.

**Comment by mbrodala** [comment]
@manishas As you can see in the SPOG view (probably not due to the ellipse) I already did that. ;-)

**Comment by trriplejay** [comment]
dryrun just shows how your pipeline would look once you actually add it.  it looks like you haven't actually added it as a syncRepo yet from the enable page.  And for that project ID you provided, it does look like the "hook pipeline" button hasn't been clicked yet, so there is no runCI associated with it.   Can you click that first? it's in the "project actions" section at the bottom of the project settings.

**Comment by mbrodala** [comment]
@trriplejay As said, I already have clicked that button, thus it's now shown anymore:

![image](https://user-images.githubusercontent.com/5037116/29507602-23705f9c-8651-11e7-9777-fe23fb75c0e5.png)

Notice that I've stumbled upon the issue with an inconsistent runCI, similar to the issue #3758; this disappeared after a few minutes however. Maybe this is related?

**Comment by a-murphy** [comment]
Have you added the repository with your `shippable.jobs.yml` as a syncRepo?  You can do this by clicking on the plus button in the top right of your subscription dashboard, scrolling to the bottom of that page, and selecting the project and branch with your `shippable.jobs.yml`.  Adding the syncRepo will create the rSync job that synchronizes the pipelines YML files in the syncRepo.

**Comment by mbrodala** [comment]
@a-murphy That's what I was missing, now the SPOG view looks more like I'd expect:

![image](https://user-images.githubusercontent.com/5037116/29553042-03668158-871a-11e7-95c5-702dba42423c.png)

Questions which wheren't answered by the docs:

1. What exactly does `syncRepo` do?
2. Do I have to add a `syncRepo` for every project?
3. What happens if I merge and delete the branch a `syncRepo` has been created for?
4. Can I re-use the same job for multiple projects? E.g. define a deployment workflow including encrypted credentials once in a separate project and then somehow connect various projects to that?

**Comment by a-murphy** [comment]
1. A `syncRepo` is a reference to a repository and branch on a source provider.  When a pipelines YML file in that branch is updated, the webhook will create a new version of the `syncRepo` for that commit SHA and trigger the rSync job.  The `rSync` job needs the `syncRepo` to know where to look for `shippable.jobs.yml` and/or `shippable.resources.yml`.

2. You will have to add a `syncRepo` for each branch with a `shippable.jobs.yml` or `shippable.resources.yml` that you want to include in your pipeline.  It's up to you if you want all your pipelines YML files to be in one `syncRepo` for the subscription or if you want to split them up into multiple repositories.

3. If you delete the branch to which the `syncRepo` refers, it will no longer update.

4. You can add multiple inputs to the same job, and they can be from different `syncRepo`s as long as they're in the same subscription, but the inputs won't change depending on how it's triggered.  There is a `JOB_TRIGGERED_BY_NAME` environment variable that you can use to figure out which input triggered a `runSh` job if you need a `runSh` job to behave differently depending on which input triggered it.

**Comment by a-murphy** [comment]
I'm closing this.  Let us know if there are any further questions.

**Comment by mbrodala** [comment]
Given the [latest consolidation of all assembly configuration](https://github.com/Shippable/support/wiki/5.11.1#deprecations) into `shippable.yml` can you write up an example for my initially described workflow?

**Comment by a-murphy** [comment]
The example above in the new one-file format is:

```YML
# Language setting
language: node_js

# Version number
node_js:
  - 6.8.0
  - 7.1.0


build:

  ci:
    - echo "run my tests for nodejs version $SHIPPABLE_NODE_VERSION"
  post_ci:
    - echo "if tests passed, maye create some artifacts and upload somewhere (docker image, jar/war files, etc)"  

  on_success:
    # saving some info in the state of this job to use later in the pipeline
    - echo "save some state information for future pipeline use"
    - shipctl put_resource_state $JOB_NAME versionName $BUILD_NUMBER
    - shipctl put_resource_state $JOB_NAME ciCommit $COMMIT
    - shipctl put_resource_state $JOB_NAME ciBranch $BRANCH


jobs:
  - name: deployChanges
    type: runSh
    steps:
      - IN: simpleserver_runCI
      - IN: myRepo
        switch: off
      - TASK:
        - script: echo "hello world"
        - script: echo "-------- state variables from CI --------------"
        - script: cat $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: echo "---------------------------------------------"
        - script: source $SIMPLESERVER_RUNCI_STATE/simpleserver_runCI.env
        - script: ciBuildNumber=$(shipctl get_resource_version_name simpleserver_runCI)
        - script: echo "ci build number was $ciBuildNumber"
        - script: echo "myRepo versionName is- $MYREPO_VERSIONNAME"

  - name: simpleserver_runCI
    type: runCI
    steps:
      - OUT: myRepo
        replicate: simpleserver_ciRepo

resources:
  - name: myRepo
    type: gitRepo
    integration: "trriplejay github"
    pointer:
      sourceName: trriplejay/simpleserver
      branch: master
      buildOnCommit: false
```

Basically, the `resources` section in `shippable.resources.yml` and the `jobs` section in `shippable.jobs.yml` are both copied into `shippable.yml` and `shippable.jobs.yml` and `shippable.resources.yml` can be deleted.

Jobs and resources created in one repository can still be referenced in `shippable.yml` files in other `syncRepo`s in the subscription, and the repository and branch with the `jobs` and `resources` still needs to be added as a `syncRepo`.
