### ISSUE TITLE
Shippable tries to install/find ruby even though my shippable.yml file specifices Nodejs

### ISSUE THREAD

**Issue by lucienbaumann** [Shippable/support#3781]
### Description of your issue:
I am trying to build from Github to AWS elastic beanstalk. The build seems to fail because Shippable can't find/install ruby on the instance. However, my project is in Node.js, and doesn't include Ruby anywhere. In my shippable.yml, I specify NodeJS as the language. How do I stop Shippable from trying to install Ruby?

- Link to the build failure: https://app.shippable.com/github/lucienbaumann/WillyCloud-GroupMe/runs/8/1/console

- Scripts called from the yml (optional): Here's the contents of my `shippable.yml` file:
```
integrations:
  deploy:
    - integrationName: "luke_aws"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: willycloud
      env_name: willycloud-groupme-env2
      region: us-east-1
```

**Comment by lucienbaumann** [comment]
Update: in [this thread](https://github.com/Shippable/support/issues/3780), the poster is using many more parameters in their shippable.yml file, including:

```
language: node_js
node_js:

7.4.0
```
Do I need to include these? If so, I might suggest adding a note explaining that to [this tutorial](http://docs.shippable.com/ci/deploy-to-aws-beanstalk/), which is where I copied and pasted my `shippable.yml` code from (and just filled in my own integration and environment names). I understand this might be a rookie mistake but it would be helpful for users like me!

Should I try including this in the `shippable.yml` file?

**Comment by a-murphy** [comment]
Yes, looks like you're missing the `language` tag in your `shippable.yml`.  Thank you for letting us know where you got your YML; we'll see if we can make that tutorial clearer.  Could you try adding `language: node_js` as documented [here](http://docs.shippable.com/ci/yml-structure/)?  You should also specify which version of NodeJS you want to use.  Supported versions are listed [here](http://docs.shippable.com/ci/nodejs-continuous-integration/#setting-language-and-runtime).

It should look something like this:
```YML
language: node_js
node_js:
  - yourVersion

integrations:
  deploy:
    - integrationName: "luke_aws"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: willycloud
      env_name: willycloud-groupme-env2
      region: us-east-1
```
with one of the supported
