### ISSUE TITLE
Inconsistent dependency 

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3791]
### Description of your issue:
We are trying to create a pipeline where we can deploy kubernetes cronjob objects.  In order to do this, we need a runCLI job with an input parameter of a github repo so we can access the yaml file for the cron job.  I've created other runCLI jobs with a gitRepo in parameter, but for some reason this job won't take it.

```
  Validating job dependencies 0s  
shippable-cron-test-repo dependency is missing :type
shippable-cron-test-repo dependency is missing :version.propertyBag
shippable-cron-test-repo dependency is inconsistent
```

- Link to the build failure
https://app.shippable.com/github/GoodwayGroup/jobs/shippable-cron-test-deploy-staging/builds/599dec11bc415d0700f52f60/console

**Comment by a-murphy** [comment]
Since the `shippable-cron-test-repo` doesn't have a branch specified in `shippable.resources.yml`, no version will be created when it is first added (all versions will be created by webhooks from GitHub).   The resource won't work as an input without any versions because we have no way of knowing which SHA you intend to use.

If you push a tag matching the pattern in the resource YML to that repository, a version will be created for `shippable-cron-test-repo` and then it will be possible to use the resource as an input to your job.

**Comment by rhenretta** [comment]
So is there a way to use the gitrepo resource which the current build is based on?  I don’t want to hard code a branch, because the spec may chance in a future version.

**Comment by trriplejay** [comment]
it looks like your gitRepo is set up only to operate on tag pushes.  Since no tags have been pushed since you added the resource, we don't have any record of what version of the repo the runCLI job should use.  You can correct this by pushing a tag to the repo. This will create a version of the gitRepo and trigger any jobs connected to it.

when you say "the gitrepo resource which the current build is based on" are you referring to the ciRepo at the beginning of your pipeline? If you need access to the source code, then your current setup is probably the best.  In your pipeline, should the version of the gitRepo always match the version of the ciRepo? or is this runCLI only supposed to execute when a tag has been pushed, while ci executes for commits?

**Comment by rhenretta** [comment]
the tag part is left over from the engineer copying and pasting from another pipeline.  We aren't actually pushing tags in this repo so I didn't think it would come into play.  I'd like the gitRepo to be the same hash as the version that triggered the CI build.

**Comment by trriplejay** [comment]
ok, in that case yes, there is a way to accomplish what you want. 

1. update your gitRepo resource to just have `branch: master` or any existing branch.  This is just to get a base version, it won't necessarily be used to run the job.  Also set `buildOnCommit: false`.  This means the repo will never update via webhook from github. It should look something like this:
```yml
- name: myRepo
  type: gitRepo
  integration: "trriplejay github"
  pointer:
    sourceName: trriplejay/simpleserver
    branch: master
    buildOnCommit: false
```
2. in your runCI job, add this gitRepo resource as an OUT, and use the `replicate` flag to copy the ciRepo information into the gitRepo, like this:
```yml
- name: simpleserver_runCI
  type: runCI
  steps:
    - OUT: myRepo
      replicate: simpleserver_ciRepo
```

3. Then in your runCLI job, use the gitRepo as an IN, and if you have other items that trigger the runCLI, i'd recommend setting `switch: off` on the gitRepo, like this:
```yml
- name: deployChanges
  type: runSh
  steps:
    - IN: simpleserver_runCI
    - IN: myRepo
      switch: off
    - TASK:
      - script: echo "hello world"
```

The final pipeline in this example looks like this:
![image](https://user-images.githubusercontent.com/6869398/29642824-da96a1fc-881f-11e7-8f49-0729a82a141e.png)
