### ISSUE TITLE
Deploy multiple branches on multiple AWS EC2 instances (1 instance = new branch)

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3801]
Hi, I'm trying make my deployment that way so I'll be able to deploy my production branch to the instance_1\cluster_1 whenever I made some changes on this branch and staging branch only when some changes was made by someone on the stage branch so shippable going to upload the image on the instance_2\cluster_2
In simple words changes on prod affects only on instance_1. Changes on stage affects only instance_2

http://docs.shippable.com/deploy/amazon-ecs-multiple-containers/
I found this guide, but that isn't what I want.

I have tried to make 2 different rSyncs but I can't have multiple runCI jobs.   When I ran it with rSync for prod and stage it return me this:
**- There is already a resource named my-app_runCI in this subscription.**

I tried this setup but don't how to specify the branch for each deploy.

**shippable.yml**

> language: node_js
> node_js:
>   - 7.4.0
> branches:
>   only:
>     - master
>     - dev
> 
> env:
>   global:
>     - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
>     - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
>     - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
>     - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
> 
> build:
> 
> 
>   ci:
>     - shippable_retry npm install
>     - shippable_retry npm run build
>     - docker build -t crep-master . 
>     - docker tag crep-master:latest rep/crep-master:latest
>   post_ci:
>     - docker push rep/crep-master:latest
>     - echo "versionName=latest" >> $JOB_STATE/shipdemo-img.env
>     - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img.env

**Resources**

> resources:
>   - name: shipdemo-img-master
>     type: image
>     integration: crep-dev-ecr
>     pointer:
>       sourceName: "rep/crep-master"
>       isPull: false
>     seed:
>       versionName: "latest"  
> 
>   - name: shipdemo-img-options-both
>     type: dockerOptions
>     version:
>       portMappings:
>         - 443:443
>         - 3000:3000
>         - 8000:8000
>         
>   - name: ecs-master-cluster
>     type: cluster
>     integration: crep-dev-aws #Name of your AWS integration
>     pointer:
>       sourceName : "cluster" 
>       region: "us-west-1"
>       
>       
>   - name: shipdemo-img-dev
>     type: image
>     integration: crep-dev-ecr
>     pointer:
>       sourceName: "rep/testshiprep" 
>       isPull: false
>     seed:
>       versionName: "latest"  
>       
>       
>   - name: ecs-dev-cluster
>     type: cluster
>     integration: crep-dev-aws
>     pointer:
>       sourceName : "cluster" 
>       region: "us-west-1" 

**jobs**

> jobs:
>   - name: shipdemo-manifest-master
>     type: manifest
>     steps:
>      - IN: shipdemo-img-master
>      - TASK: managed
> 
>   - name: app-name_runCI
>     type: runCI
>     steps:
>       - OUT: shipdemo-img-master
>       - OUT: shipdemo-img-dev
> 
>   - name: shipdemo-master-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest-master
>         force: true
>       - IN: shipdemo-img-options-both
>       - IN: ecs-master-cluster
>       - TASK: managed
>         deployMethod: replace
>         
>         
>         
>   - name: shipdemo-manifest-dev
>     type: manifest
>     steps:
>      - IN: shipdemo-img-dev
>      - TASK: managed       
>      
>      
>      
>   - name: shipdemo-dev-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest-dev
>         force: true
>       - IN: shipdemo-img-options-both
>       - IN: ecs-dev-cluster
>       - TASK: managed
>         deployMethod: replace   

Any suggestion how to specify image\cluster\instance per branch?
That's kind of blocker for me and **I would like if you answer me asap**.

**Comment by a-murphy** [comment]
In your case, I would suggest that you push a different image and update the matching image resource in your `shippable.yml` file depending on the branch.  You can only have one runCI job for a repository, but it's quite common to have some sections of the script that change depending on the branch.

A `build` section like this would push the correct image name and update the image resource for the current branch.
```YML
build:
  ci:
    - shippable_retry npm install
    - shippable_retry npm run build
    - if [ "$BRANCH" == "master" ]; then PUSH_IMAGE_NAME="rep/crep-master:latest"; else PUSH_IMAGE_NAME="rep/testshiprep:latest"; fi
    - docker build -t $PUSH_IMAGE_NAME .
    - docker push $PUSH_IMAGE_NAME
    - echo "versionName=latest" >> $JOB_STATE/shipdemo-img-$BRANCH.env
    - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img-$BRANCH.env
```

**Comment by glozhkovoy** [comment]
@a-murphy 
This won't solve the problem because in your example you said that choose one repository that will store the image then going to deploy the image for both instances.

In general I want something like this
![image](https://user-images.githubusercontent.com/20016615/29884927-9afed638-8dbd-11e7-8c5b-fb21cc587bdb.png)
Depends on branch I can choose the scenario. If I choose **Master branch** I going to deploy on the **Instance_1**
If I choose **Dev branch** I going to deploy on the **Instance_2**

**Comment by a-murphy** [comment]
You can only have one runCI job for a git repository (GitHub, Bitbucket, or GitLab), but you can have as many image repositories and image resources as you want.  Multiple image resources can be outputs of the same runCI job with just the relevant one updated/triggered each time the CI project runs.

**Comment by glozhkovoy** [comment]
@a-murphy 
I got your point.
multiple runCI is another way to achieve what I want. (But I've read having multiple runCI is not possible)

Can you help me setting up scenario that I described in my previous post?

**Comment by a-murphy** [comment]
The `shippable.resources.yml` and `shippable.jobs.yml` files you have above, completely unchanged, and an updated `shippable.yml` results in a pipeline like this:
![screenshot from 2017-08-30 11 46 44](https://user-images.githubusercontent.com/5492015/29889482-2a1b21ea-8d79-11e7-8c07-0238cf96b1d7.png)

The `dev` image is updated on the `dev` branch and and `master` image on the `master` branch.

The full `shippable.yml` file is:
```YML
language: node_js
node_js:
  - 7.4.0
branches:
  only:
    - master
    - dev

env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/

build:
  ci:
    - shippable_retry npm install
    - shippable_retry npm run build
    - if [ "$BRANCH" == "master" ]; then PUSH_IMAGE_NAME="rep/crep-master:latest"; else PUSH_IMAGE_NAME="rep/testshiprep:latest"; fi
    - docker build -t $PUSH_IMAGE_NAME .
    - docker push $PUSH_IMAGE_NAME
    - echo "versionName=latest" >> $JOB_STATE/shipdemo-img-$BRANCH.env
    - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img-$BRANCH.env

integrations:
  hub:
    - integrationName: docker-hub   
      type: docker
```

I'm assuming that you left out the integration you are using to push the Docker image when you copied your `shippable.yml`.  If you are missing that section, documentation is available [here](http://docs.shippable.com/ci/push-docker-hub/).

The `PUSH_IMAGE_NAME` environment variable is set depending on the branch and then used for the `docker build` and `docker push` to push the correct image for that branch.  And then the `versionName` and `buildNumber` are updated in the `.env` file for the image resource for that branch.  The other image resource is left unchanged and so will not update and will not trigger that part of the pipeline.

**Comment by glozhkovoy** [comment]
> I'm assuming that you left out the integration you are using to push the Docker image

Ye, I forgot to copy it.

> integrations:
>   hub:
>     - integrationName: crep-dev-ecr
>       region: us-west-1
>       type: ecr

That's what I'm using

**Comment by glozhkovoy** [comment]
@a-murphy 

shippable

```
language: node_js
node_js:
  - 7.4.0

branches:
  only:
    - master
    - dev

env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - shippable_retry npm install
    - shippable_retry npm run build
    - if [ "$BRANCH" == "master" ]; then PUSH_IMAGE_NAME="rep1:latest"; else PUSH_IMAGE_NAME="rep2"; fi
    - docker build -t $PUSH_IMAGE_NAME . 
    #- docker tag testshippable:latest $PUSH_IMAGE_NAME
  #post_ci:
    - docker push $PUSH_IMAGE_NAME
    - echo "versionName=latest" >> $JOB_STATE/shipdemo-img-$BRANCH.env
    - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img-$BRANCH.env



integrations:
  hub:
    - integrationName: name1
      region: us-east-1
      type: ecr
    - integrationName: name2
      region: us-west-1
      type: ecr
```

Resources

```
resources:
  - name: shipdemo-img-master
    type: image
    integration: name1
    pointer:
      sourceName: "rep1" 
      isPull: false
    seed:
      versionName: "latest"  

      
  - name: shipdemo-img-options-both
    type: dockerOptions
    version:
      portMappings:
        - 80:80
        - 443:443
        - 3000:3000
        - 8000:8000
        - 9001:9001
     
     
  - name: ecs-master-cluster
    type: cluster
    integration: name1-2 #Name of your AWS integration
    pointer:
      sourceName : "cluster1" #replace with name of the cluster to which you are deploying
      region: "us-east-1" #replace with region of the cluster to which you are deploying
      
      
  - name: shipdemo-img-dev
    type: image
    integration: name2
    pointer:
        sourceName: "rep2"
        isPull: false
    seed:
        versionName: "latest"
        
        
  - name: ecs-dev-cluster
    type: cluster
    integration: name2-2
    pointer:
      sourceName : "cluster2" #replace with name of the cluster to which you are deploying
      region: "us-west-1" #replace with region of the cluster to which you are deploying
```


jobs

```
jobs:
  - name: shipdemo-manifest-master
    type: manifest
    steps:
     - IN: shipdemo-img-master
     - TASK: managed

  - name: app-name_runCI
    type: runCI
    steps:
      - OUT: shipdemo-img
      - OUT: shipdemo-img-dev

  - name: shipdemo-master-deploy
    type: deploy
    steps:
      - IN: shipdemo-manifest-master
        force: true
      - IN: shipdemo-img-options
      - IN: ecs-master-cluster
      - TASK: managed
        deployMethod: replace
        
        
  - name: shipdemo-manifest-dev
    type: manifest
    steps:
      - IN: shipdemo-img-dev
      - TASK: managed
      
      
  - name: shipdemo-dev-deploy
    type: deploy
    steps:
      - IN: shipdemo-manifest-dev
        force: true
      - IN: shipdemo-img-options
      - IN: ecs-dev-cluster
      - TASK: managed
        deployMethod: replace  
```  


runCI works perfectly but rSync failed with

>   - Missing dependency for job: shipdemo-dev-deploy
>   - Missing dependency for job: shipdemo-master-deploy
>   - Missing dependency for job: app-name_runCI

Pipelines looks like this ...
![image](https://user-images.githubusercontent.com/20016615/29893965-86c3152a-8ddc-11e7-9f10-911aff2aca77.png)
