### ISSUE TITLE
Environment not updating to reflect shippable.resources.yml

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3814]
Ref: https://app.shippable.com/subs/github/ExecThread/resources/develop-gateway-env/versions

Changing the the env vars in the `secure` section does not use the new version: 
We had added a new env var and it was not showing up in ECS TaskDef...when I looked in the SPOG at the develop-gateway-env, I could see that the env had not been updated since last Wednesday despite many CI and deploy cycles since then. I clicked the Update link for the develop-gateway-env element, and put in the text that is in the secure section of the develop-gateway-env params section and then the env var was added to the ECS task as expected. Why is this not happening automatically based on the data in the shippable.resources.yml?

Here is the relevant section of the shippable.resources.yml: 

```
 - name: develop-gateway-env
    type: params
    version:
      params:
        PORT: 3000
        REDIS_URL: redis//dev...............:6379
        secure: nvZo.......................==
 ```
