### ISSUE TITLE
Can't connect to locally installed Selenium server

### ISSUE THREAD

**Issue by dverlik** [Shippable/support#3831]
I am using nightwatch.js with selenium chrome driver. My shippable.yml file:

```
language: node_js
node_js:
  - "7.6.0"
services:
  - mongodb
  - selenium
branches:
  only:
    - dev
    - prod
before_install:
  - "curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip"
  - "unzip /tmp/chromedriver.zip -d /home/shippable/bin"
  - "chmod +x /home/shippable/bin/chromedriver"
  - "echo '#!/bin/bash' | sudo tee /usr/bin/google-chrome"
  - "echo 'exec /usr/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/bin/google-chrome"
  - "sudo chmod +x /usr/bin/google-chrome"    
build:
  ci:
    - sudo npm install
    - npm run eslint-shippable
    - export DISPLAY=:99.0
    - xvfb-run --server-args="-ac" npm run nightwatch-app
```

The "nightwatch-app" command in the package.json:

```
...snip...
"nightwatch-app": "node ./app.js & ./node_modules/.bin/nightwatch",
...snip...
```

My nightwatch.json file:

```
{
    "src_folders": ["./tests"],
    "output_folder": "./shippable/testresults",
    "custom_commands_path": "",
    "custom_assertions_path": "",
    "globals_path": "",

    "selenium": {
        "start_process": true,
        "server_path": "",
        "log_path": "",
        "host": "127.0.0.1",
        "port": 4444,
        "cli_args": {
            "webdriver.chrome.driver": "bin/chromedriver"
        }
    },

    "test_settings": {
        "default": {
            "launch_url": "http://localhost",
            "selenium_port": 4444,
            "selenium_host": "localhost",
            "silent": true,
            "chrome_driver": "",
            "ie_driver": "",
            "screenshots": {
                "enabled": false,
                "path": ""
            },
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true
            }
        }
    }
}
```
Looking at the build logs, looks like selenium is starting normally:
```
================= Starting Selenium ===================

Waiting for selenium to start...
Waiting for selenium to start...
Waiting for selenium to start...
selenium started successfully
```
However, my build is failing when trying to execute the latest build_ci command:

```
...snip...
Error retrieving a new session from the selenium server
Selenium server is not running.

Connection refused! Is selenium server started?
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) code: 'ECONNRESET' }
...snip...
```
What should I do?

**Comment by manishas** [comment]
@dverlik one issue I see with the shippable.yml config is that before_install and build->ci config cannot be used together in the same yml. before_install tag is left over from our earlier yml format. 

Can you put the instructions you currently have in 'before_install' at the start of the 'ci' section and try running the build again

**Comment by manishas** [comment]
As a reference, this is the CI config: http://docs.shippable.com/ci/yml-structure/

**Comment by dverlik** [comment]
I've edited my shippable.yml file:
```
language: node_js
node_js:
  - "7.6.0"
services:
  - mongodb
  - selenium
branches:
  only:
    - dev
    - prod
build:
  ci:
    - "curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip"
    - "unzip /tmp/chromedriver.zip -d /home/shippable/bin"
    - "chmod +x /home/shippable/bin/chromedriver"
    - "echo '#!/bin/bash' | sudo tee /usr/bin/google-chrome"
    - "echo 'exec /usr/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/bin/google-chrome"
    - "sudo chmod +x /usr/bin/google-chrome"    
    - sudo npm install
    - npm run eslint-shippable
    - export DISPLAY=:99.0
    - xvfb-run --server-args="-ac" npm run nightwatch-app
```
But I am still getting the same error while trying to build my app:
```
...snip...
> node ./app.js & ./node_modules/.bin/nightwatch


[Index Page Test] Test Suite
================================

Running:  "/" page test
...snip...
Error retrieving a new session from the selenium server
Selenium server is not running.

Connection refused! Is selenium server started?
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) code: 'ECONNRESET' }


npm ERR! Linux 3.13.0-126-generic
npm ERR! argv "/root/.nvm/versions/node/v7.6.0/bin/node" "/root/.nvm/versions/node/v7.6.0/bin/npm" "run" "nightwatch-app"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
...snip...
```
