### ISSUE TITLE
runCI OUT env var not usable in post_ci step?

### ISSUE THREAD

**Issue by pstreef** [Shippable/support#3858]
I'm trying to use the following env var for my resource `img` as described in the docs:

`<NAME>_SOURCENAME | SourceName defined in the pointer.`

Expecting the output to show `imagetag will be example.com:5000/service:1.0` however the output shows an empty env var.

This is working fine with the keypath env vars used as INputs (cert/key files). Can OUT resources not be used in runCI for some reason? Because the docs state:

> Whenever image is used as an IN or OUT for a job that can execute user defined scripts, a set of environment variables are configured by the platform that may be useful to set the context before user defined scripts execute as part of the job. These variables are available when this resource is used.

```
jobs:
  - name: my_runCI
    type: runCI
    steps:
      - IN: ca_cert
      - IN: client_cert
      - IN: client_key
      - OUT: img
  - name: my_deploy
    type: runSh
    steps:
      - IN: img
      - IN: ca_cert
      - IN: client_cert
      - IN: client_key
      - TASK:
        - script: echo "hello"
```
```
resources:
  - name:           ca_cert
    type:           integration
    integration:    ca_pem
  - name:           client_cert
    type:           integration
    integration:    cert_pem
  - name:           client_key
    type:           integration
    integration:    key_pem
  - name: img
    type: image
    integration: dockerregistry
    pointer:
      sourceName: example.com:5000/service:1.0
    seed:
      versionName: master.1
```
      
shippable.yml: 
```
build_environment: Ubuntu 16.04
language: java
jdk:
    - oraclejdk8
branches:
  only:
    - master
build:
  ci:
    - mkdir -p ./certs/
    - cp $CA_CERT_KEYPATH certs/ca.pem
    - cp $CLIENT_CERT_KEYPATH certs/cert.pem
    - cp $CLIENT_KEY_KEYPATH certs/key.pem
    - mvn clean verify install -Pci
  post_ci:
    - echo "imagetag will be $IMG_SOURCENAME"
...
```

Project Id: 59b675beb54e3d0700f4fe9a
