### ISSUE TITLE
Resource env var not updated after name change

### ISSUE THREAD

**Issue by pstreef** [Shippable/support#3859]
I'm having trouble with an image resouce env var I'm using in my CI step.

When I change the name for the resource (and of the corresponding env vars in my yml files) the next build fails because the env var is not set.

`echo "image tag will be $IMG_SOURCENAME"`
will output `image tag will be`

When i rebuild the project the output is correct.

simplified config:

```
build:
  ci:
    - echo "imagetag will be $IMG_SOURCENAME"
```
```
  - name: img
    type: image
    integration: dockerregistry
    pointer:
      sourceName: example.com:5000/service:1.0
    seed:
      versionName: master.1
```
```
jobs:
  - name: service_runCI
    type: runCI
    steps:
      - OUT: img
```

Project Id: 59b675beb54e3d0700f4fe9a
