### ISSUE TITLE
runSh jobs failing to get env: / custom ENV vars set intermittently

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3869]
re using the http api to trigger a runSh job - https://github.com/Shippable/support/issues/3857

so I've been using this (for testing, getting to the point of being able to use it for real) for a few hundred+ triggers now I guess.

Intermittently, the runSh jobs don't get the  ENV variables (from shipppable.resources.yml or sometimes from the http request) properly defined in the environment.  Another trigger and they will be set.    No changes to either the rSync repo nor the repo that the runSh job consumes nor the http request occurs between triggers.

To be clear, I have a param defined:

```
  - name: ansible_deploy_params
    type: params
    version:
      params:
        SSH_USER: "ansible"
```

and a job that consumes it:

```
  - name: deploy-via-ansible
    type: runSh
    steps:
      - IN: ansible_master_gitRepo
        switch: off
      ## ssh key integrations for runSh jobs DO NOT add the keys to the agent
      ## you need to ssh-add from /build/IN/name/name_key yourself
      - IN: _ssh_key_integration
        switch: off
      - IN: ansible_deploy_params
        switch: off
      - TASK:
        - script: set -u
        - script: echo "ENV..."
        - script: env |grep -e SSH_USER -e ENVIRONMENT
        - script: echo "Echo..."
        - script: ### this should die out since we set -u if these are missing
        - script: echo ENVIRONMENT $ENVIRONMENT SSH_USER $SSH_USER


(adjusted to reduce complexity of the script for the scope of this ticket)
```

and an http request to trigger the job:

```
curl -v -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: apiToken TOKEN' https://api.shippable.com/resources/RESOURCE/triggerNewBuildRequest -d '{"globalEnv":{"PLAYBOOK":"ansible-test.yml", "ENVIRONMENT":"testing", "RDS_SNAPSHOT":"false", "ALLOW_DOWNGRADE":"false", "POPULATIONBUILDER_VERSION":"", "POPULATIONBUILDER_ASSETS_VERSION":"", "BACKOFFICE_ASSETS_VERSION":"" }}'
```

I've noticed that the `PARAM_NAME_PARAMS_VAR` variables ARE set for the param defined variables in this case.  http request env vars don't have such a variable that I can find.

successful job:

https://app.shippable.com/bitbucket/devexi/jobs/deploy-via-ansible/builds/59d401ba24ca780600332cfe/console

```
ENV...
SSH_USER=ansible
ENVIRONMENT=testing
ANSIBLE_DEPLOY_PARAMS_PARAMS_SSH_USER=ansible
Echo...
ENVIRONMENT testing SSH_USER ansible
```

http request vars missing inside job, but seen in UI, param env vars not set

https://app.shippable.com/bitbucket/devexi/jobs/deploy-via-ansible/builds/59d4022b24cffe070025b561/console

```
ENV...
ANSIBLE_DEPLOY_PARAMS_PARAMS_SSH_USER=ansible
Echo...
./bin/shippable-runner.sh: line 58: ENVIRONMENT: unbound variable
runSh failed with error: 1
```

http request env vars missing, and param env vars not set:

https://app.shippable.com/bitbucket/devexi/jobs/deploy-via-ansible/builds/59d4016aec6f3b07001641b5/console

```
ENV...
ANSIBLE_DEPLOY_PARAMS_PARAMS_SSH_USER=ansible
Echo...
./bin/shippable-runner.sh: line 58: ENVIRONMENT: unbound variable
runSh failed with error: 1
```
