### ISSUE TITLE
Pull docker image from ECR in runSh job

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3892]
Hello!

I'm trying to pull docker image from our private ECR repository in Shippable runSh job.

My job is looking like this:

```yml
  - name: application-sh
    type: runSh
    steps:
      - IN: application-image
      - IN: application-params
        switch: off
      - IN: application-ecr-config
        switch: off
        scopes:
          - ecr
      - TASK:
        - script: |
                  echo "docker pull ${APPLICATIONIMAGE_SOURCENAME}:${APPLICATIONIMAGE_VERSIONNAME}"
                  docker pull ${APPLICATIONIMAGE_SOURCENAME}:${APPLICATIONIMAGE_VERSIONNAME}
```

I'm passing image resource to the job in order to access source name and version name variables:

```yml
  - name: application-image
    type: image
    integration: amazon-ecr
    pointer:
      sourceName: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/application
      isPull: false
    seed:
      versionName: latest
```

I'm also passing `application-ecr-config`, which is a `cliConfig` resource:

```yml
  - name: application-ecr-config
    type: cliConfig
    integration: amazon-ecr
    pointer:
       region: eu-central-1
```

ECR integration is defined in my `shippable.yml`:

```yml
integrations:
  hub:
    - integrationName: amazon-ecr
      type: ecr
      region: eu-central-1
```

Here's the script output from the running job:

```
Identity added: /tmp/00_sub (/tmp/00_sub)
Configuring Amazon ECR credentials for application-ecr-config in region eu-central-1
Configured Amazon ECR credentials
docker pull 123456789012.dkr.ecr.eu-central-1.amazonaws.com/application:master-abc123400000
Error response from daemon: Get https://123456789012.dkr.ecr.eu-central-1.amazonaws.com/v2/application/manifests/master-abc123400000: no basic auth credentials
runSh failed with error: 1
```

For some reason, I'm getting authentication error when trying to pull the docker image. Shouldn't passed `cliConfig` establish authentication with ECR, so I could just do `docker pull …`?

---

Maybe this thread has related information for ECR login:
https://forums.docker.com/t/docker-push-to-ecr-failing-with-no-basic-auth-credentials/17358

---

Also, why do I need to specify Amazon region in two places (in integration and in cli-config)?

Thank you!
