### ISSUE TITLE
Documentation for isPull option of image resource?

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3893]
Hello!

According to various resources, there is a `isPull` option of image resource, e.g. I have this in my `shippable.resources.yml`:

```yml
  - name: application-image
    type: image
    integration: amazon-ecr
    pointer:
      sourceName: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/application
      isPull: false
    seed:
      versionName: latest
```

However, I can't find any mentions in the documentation:
- http://docs.shippable.com/platform/workflow/resource/image/
- http://docs.shippable.com/platform/integration/aws-keys/

Could you elaborate on it's purpose please? Or is it deprecated?

Thank you!
