### ISSUE TITLE
Pillow package installation error

### ISSUE THREAD

**Issue by 9dev** [Shippable/support#3915]
When I try to install Pillow package I receive the following error:

_The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source._

Used image: drydock/u14pytall

```
language: python

python:
  - 3.4

build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: prod
    pull: true
  ci:
    - pip install -r requirements.txt  # pillow==4.3.0
```

Could you help me? I don't want to post my build URL publicly.
