### ISSUE TITLE
/usr/local/bin/phpenv-install 7.1 0s   [Error]: Definition 7.1 not found.

### ISSUE THREAD

**Issue by jamesrward** [Shippable/support#3919]
Looks like my issue is similar to #3792 and #3640 however the solutions there aren't helping.

Here is the error I get on my current builds:
```txt
/usr/local/bin/phpenv-install 7.1 0s  
[Error]: Definition 7.1 not found.
```

shippable.yml currently contains:

```yml
language: php

php:
  - "7.1"

before_script:
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer
  - ./ci/pr_phpcs.sh
```

Also tried 7.1 without quotes:
```yml
language: php

php:
  - 7.1
```
But received the same error.
