### ISSUE TITLE
Docker: backstabbing_yalow on network bridge: Bind for 127.0.0.1:8080 failed: port is already allocated

### ISSUE THREAD

**Issue by zopyx** [Shippable/support#3929]
I am trying to get this project migrated from Travis to Shippable.
It uses Docker

https://github.com/xml-director/xmldirector.plonecore

However I receive the error

```
Docker: backstabbing_yalow on network bridge: Bind for 127.0.0.1:8080 failed: port is already allocated
```

- Link to the build failure

https://app.shippable.com/github/xml-director/xmldirector.plonecore/runs/1/1/console

- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
I see that your script is trying to execute a `docker run` twice in a row with the same options.  The first time it runs, the container is successfully started and therefore takes the 8080:80 port binding.  Then the second container fails because the port is in use by the first container.  I'd recommend removing the second docker run to avoid that particular error.

Later on your build fails because it can't access the container.  This is because on Shippable, the build itself runs inside a container where docker.sock is mounted.  So if you execute docker run, it starts the container on the host, but then if you try to access 'localhost', it will be inside the build container's local network, and it won't be able to talk to the container you just ran on the host.

The best way around this is to add a `pre_ci_boot` section to your yml where you can specify the `--net=host` option for your build container.

To do this, you'll have to convert your travis yml to a shippable yml.  This will allow you to access more shippable-specific features.

Check out our yml docs [here](http://docs.shippable.com/ci/yml-structure/), they should help you with the conversion.

Your pre_ci_boot section should look something like this:
```yml
pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: prod
    options: "--net=host"
```

once your boot container is running in net=host mode, you'll be able to access it directly on that port.

Let me know if you have any questions on the shippable.yml format or anything else that you run into.

**Comment by zopyx** [comment]
You are right with the double `docker run` command but the result remains the same:

https://app.shippable.com/github/xml-director/xmldirector.plonecore/runs/3/1/console

I can not use a static configuration for the Docker image since every build of my matrix uses a dedicated docker image for compatibility testing with various WebDAV enabled services.

**Comment by trriplejay** [comment]
the container specified in the pre_ci_boot section is the build container, which is separate from the container that you are running via docker run.  The build container remains static for each build that is run within your matrix. Currently, it is just using Shippable's default image for the python language. You can see the details of this in the "boot_container" section of the build logs.  Adding the pre_ci_boot section and providing this image directly won't affect any other aspect of the build, but it will allow you to provide the `--net=host` option, which should resolve this "connection refused" error.

The individual builds in your matrix can still use dynamic options for the docker run command in your script, but the build container itself, the container inside which your "build" section is executed, remains the same for each item in the matrix.

Your shippable yml would just become something like this:
```yml
build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: prod
    options: "--net=host"

  ci:
    - docker version
    - pwd
    - ls -la
    - mkdir -p /tmp/testing
    - rm -fr /tmp/testing/*
    - bash build_test.sh 
  on_success:
   - test -v QA && pip install python-coveralls==2.4.0 || true
   - test -v QA && coveralls || true
```
