### ISSUE TITLE
PhpUnit with code coverage = timeout

### ISSUE THREAD

**Issue by apfelbox** [Shippable/support#3937]
Hi,

I am trying to get shippable to run with code coverage.
I am building a PHP project (a symfony extension) and have the following `shippable.yml`:

```yaml
language: php

php:
    - 7.1

build:
    ci:
        - wget https://getcomposer.org/composer.phar
        - php composer.phar install --prefer-dist --no-interaction
        - mkdir -p shippable/testresults
        - mkdir -p shippable/codecoverage
        - phpunit -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
        # alternatively: - ./vendor/bin/simple-phpunit -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
```

`simple-phpunit` is a [wrapper by symfony](https://github.com/symfony/phpunit-bridge) around `phpunit`.

No matter what executable I choose, as soon as I activate `--coverage-xml shippable/codecoverage` the build just times out:

for `phpunit`:
```
phpunit -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage  
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.
```

for `simple-phpunit`:

```
./vendor/bin/simple-phpunit -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage  
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Package operations: 19 installs, 0 updates, 0 removals
  - Installing sebastian/recursion-context (2.0.0): Downloading (100%)
  - Installing sebastian/exporter (2.0.0): Downloading (100%)
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/environment (2.0.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (1.4.11): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
  - Installing phpunit/php-code-coverage (4.0.8): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (100%)
  - Installing sebastian/global-state (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (2.0.1): Downloading (100%)
  - Installing symfony/phpunit-bridge (v4.0.0-BETA2): Loading from cache
Writing lock file
Generating optimized autoload files
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.
```

Is there something missing? What can I do to fix this issue?

Bonus questions:
- Is it correct that there is no preinstalled `composer`?
- Should "uploading test reports" be this slow (in comparison to the rest)?
    
    ![2017-11-04 at 10 21](https://user-images.githubusercontent.com/1032411/32404106-0ac25c78-c14a-11e7-9585-990012b1c5f4.png)

Thanks!
