### ISSUE TITLE
Cannot execute a command line containing : in shippable

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#3940]
### Description of your issue:
This is the command that I want to execute and it works fine when I run in my local. 
`curl -H "Content-Type: application/json" -X POST -d '[{"fromEnv":"live", "fromSite":"AAA", "number":"2", "toSite":"BBB"}]' http://ThisIsAUrl`

However, when I add this command in a runSH job in shippable.
![image](https://user-images.githubusercontent.com/14726381/32426407-45cf4dec-c30e-11e7-9d5b-ec5958a45900.png)

The dry run will show an error as below.
![image](https://user-images.githubusercontent.com/14726381/32426305-aac426ce-c30d-11e7-85d7-cf47f7299270.png)

After investigating, it seems to be a problem of having `:`.
I have tried to use `{{:}}`  This can make the dry run successfully passed. However, my command won't work. It seems to me that the command needs to be the one that I mentioned in the beginning.

Could you please advise if there is any solution regarding this?

**Comment by Bharath92** [comment]
There seems to be a problem with the `:` character in the yml file.
Instead of using
```
- name: simple-curl
    type: runSh
    steps:
      - TASK:
        - script:  curl -H "Content-Type: application/json" https://api.shippable.com
```
could you try this?
```
- name: simple-curl
    type: runSh
    steps:
      - TASK:
        - script: >
             curl -H "Content-Type: application/json" https://api.shippable.com
```
