### ISSUE TITLE
support script for runCI sections always and on_start

### ISSUE THREAD

**Issue by brentfamily1** [Shippable/support#3977]
### Description of your issue:
The `on_start` script statements do not appear to run on a runCI job prior to the steps.  The documentation indicates a script should run in this context, http://docs.shippable.com/platform/tutorial/workflow/shippable-yml/#anatomy-of-shippable.yml

- Link to the build failure: https://app.shippable.com/github/PassageTech/VF-Remote-Object-Demo/runs/308/1/console

- Scripts called from the yml 
shippable.yml, https://github.com/PassageTech/VF-Remote-Object-Demo/blob/88806738eb96d9606e9a335ba1fcbe0550855a9f/shippable.yml

Job Definition:
```
jobs:

  - name: VF-Remote-Object-Demo_runCI 
    type: runCI
    steps:
      - IN: SFDX_DEVHUB
      - IN: SHIPPABLE_ASSETS
    on_start:
     - script: bash "$SHIPPABLE_ASSETS_STATE/build/scripts/sfdx-ci-setup.sh"
    always:
     - script: bash "$SHIPPABLE_ASSETS_STATE/build/scripts/shippable-cleanup.sh"
```
