### ISSUE TITLE
Cancel pending jobs

### ISSUE THREAD

**Issue by JaZo** [Shippable/support#3982]
I have a job which triggers only on PR's. I'd like to know if there's a way to cancel pending or running jobs for a PR when it is updated, just like a regular CI-job with 'latest commit on pull request' setting. This supports the following flow:

- PR 1 created
- Run 1 queued
- PR 2 created
- Run 2 queued
- PR 1 updated
- Run 1 cancelled
- Run 3 queued
- Run 2 finished
- Run 3 finished

shippable.yml
```
resources:
  - name: xxxRepositoryPullRequest
    type: gitRepo
    integration: bitbucket
    pointer:
      sourceName: swisnl/xxx
      branch: develop
      buildOnCommit: false
      buildOnPullRequest: true

jobs:
  - name: xxxDoStuff
    type: runCLI
    flags:
      - shippable-automated
    steps:
      - IN: xxxRepositoryPullRequest
        showBuildStatus: false

      - TASK:
        - script: echo "Do stuff"
```

Thanks!
