### ISSUE TITLE
runSH job hangs after line `Successfully cleaned directory at path: /tmp/ssh`

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4001]
After more than 2 hours the console still showed 
```
Initializing Job
...
Cleaning directories.
Successfully cleaned directory at path: /shippableci/onstartjobenvs
Successfully cleaned directory at path: /tmp/ssh
```

Reset, multiple restarts have not helped.

Latest job: 5a2e9363cf141c0700be15da

**Comment by vidiecan** [comment]
Update: seems all jobs are affected!

**Comment by deepikasl** [comment]
@vidiecan Sorry for inconvenience. We are looking into it.

**Comment by rageshkrishna** [comment]
@vidiecan Would you mind triggering one more build? We're monitoring your node to see what's going on here. Thanks.

**Comment by vidiecan** [comment]
@rageshkrishna it is fixed now, thanks. 

What was the problem, anything we could/should avoid in the future?

**Comment by rageshkrishna** [comment]
Thanks for the update, @vidiecan.

The build agent on your node had ended up in an unusual state that we have not seen before. Usually, when something like this happens, our system detects the unhealthy node and replaces it but for some strange reason even that process did not kick in for this node.

No action is necessary at your end.

I'm closing this issue as the problem appears to be resolved now. Please re-open this if you run in to it again.

**Comment by vidiecan** [comment]
seems to be happening again, 5a310db77cc9a807008b43dd

**Comment by rageshkrishna** [comment]
@vidiecan It looks like the build runner is unable to clean up some of the directories that are left behind by previous builds. I think this is why the build runs alright for you on a fresh node, but it gets stuck when the next build is picked up by the same node.

Can you tell me if there is anything in your build that might be acquiring any file locks or something similar which might prevent a delete from succeeding?

**Comment by vidiecan** [comment]
```
    type: runSh
    steps:
      - IN: c-image-to-text_runCI
        switch: off
      - IN: tei2tGitRepo
      - IN: tebinariesGitRepo
      - IN: tedatasetGitRepo
      - IN: tedatasetimagesGitRepo
      - IN: tedatasetPass
      - TASK:
        - script: pushd IN/tei2tGitRepo/gitRepo/ && mkdir bin && git status && git submodule update --init && popd
        - script: pushd IN/tebinariesGitRepo/gitRepo/ && cp -av lib* image* ../../tei2tGitRepo/gitRepo/bin && popd
        - script: pushd IN/tei2tGitRepo/gitRepo/_tests/stability && python run.py --dataset=../../../../tedatasetimagesGitRepo/gitRepo/ && popd
        - script: pushd IN/tei2tGitRepo/gitRepo/_tests/stability/scripts && ./init_dataset.sh ../../../../../tedatasetGitRepo/gitRepo/input.7z && popd
```
where `init_dataset.sh` is something like

```
#!/bin/bash
echo "Dataset in $1"
sudo apt-get install p7zip-full &> /dev/null

7z x -o../dataset -r $1 &> /dev/null
pushd ../
python run.py --dataset=./dataset
popd 
```

the only left out part is `run.py` that I cannot share but I do not see anything special there (similar things have been running on your infrastructure in a normal CI build for ages)
