### ISSUE TITLE
Tests are timing out.

### ISSUE THREAD

**Issue by vincentpaca** [Shippable/support#401]
I tried running quite a long test using parallelization but it seems that tests are timing out at 20 minutes.

I've split the test suite to 20 parts and, theoretically, each part should just run under ~5 minutes.

Is there a way for you to help me to debug this and see what's making the tests time out?

The error messages are not really that helpful either.

```
 $RUN
...
CMD sudo su - minion -c cd /home/minion/projects/53ed675bdef88e21028aa3c3/code && /home/minion/projects/53ed675bdef88e21028aa3c3/code/run_script 2>&1 non responsive for > 1200 seconds, terminating

Command timed out
Failed BUILD: 85
Uploading code coverage report
Uploading test reports
Archiving build artifacts
Finished archiving
Uploading Archive
Completed: PROJECT: 53ed675bdef88e21028aa3c3 | BUILD: 85 | BRANCH: shippable | TIME: Sat, 16 Aug 2014 08:27:35 +0000
```

Edit: shippable.yml file looks like this:

```
build_environment: Ubuntu 12.04
language: ruby
rvm:
  - 2.1.2

env:
  global:
    - DISPLAY=:99.0
    - SPEC_OPTS="--color --require ci/reporter/rake/rspec_loader --format CI::Reporter::RSpecFormatter"
    - CUCUMBER_OPTS="--format CI::Reporter::Cucumber --out shippable/testresults/cucumber.bla"
    - CUCUMBER_FORMAT=progress
    - CI=1
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - DB=mysql2://shippable:@localhost/test
    - RAILS_ENV=test
  matrix:
    - RUN="rspec spec/suite.rb" GROUP=1of20
    ....
    - RUN="rspec spec/suite.rb" GROUP=20of20

# install dependencies
install:
  - 'sudo apt-get install wkhtmltopdf'
  - 'sudo apt-get install pdftk'
  - "mysql -e 'create database test;'"

addons:
  firefox: "28.0"

services:
  - selenium

script:
  - $RUN

before_script:
  - "rm -rf $CI_REPORTS && mkdir -p $CI_REPORTS"
  - "/etc/init.d/xvfb start"
  - rake -f CI.rake ci:init
  - rake db:schema:load

after_script:
  - "/etc/init.d/xvfb stop"
```
