### ISSUE TITLE
Kubernetes integration in CI step not setting the env var

### ISSUE THREAD

**Issue by maxx-bachurin** [Shippable/support#4017]
### Description of your issue:
I am trying to setup K8S integration in my CI step using the following configurations:

shippable.yaml

build:
  ci:
  - ./cmd/env

  post_ci:
  - ./cmd/deploy_k8s

integrations:
  - integrationName: integrationName

or

shippable.yaml

build:
  ci:
  - ./cmd/env

  post_ci:
  - ./cmd/deploy_to_k8s

resources:
  - name: kubeconfig
     type: integration
     integration: integrationName

jobs:
  - name: name
    type: runCI
     steps:
       - IN: kubeconfig

and neither of them work setting the env var containing the kubernetes config

What might be wrong?

**Comment by deepikasl** [comment]
Hi @maxx-bachurin you have configured it wrong.
This is the way you set up integration in `shippable.yaml`
```yml

build:

  pre_ci:

  pre_ci_boot:
    image_name:
    image_tag:
    pull:
    options:
  ci:
    - #command1
    - #command2
  post_ci:
    - #command1
    - #command2

integrations:
  generic:
    - integrationName: integrationName
      type: type
 ```
Refere [Docs](http://docs.shippable.com/ci/yml-structure/) for more information

You can use  Kubernetes integration Assembly lines. For that you need to add `shippable.resources.yml` and `shippable.jobs.yml`. 

You can follow these docs for adding: 
**shippable.resources.yml**: http://docs.shippable.com/platform/tutorial/workflow/shippable-resources-yml/,
**shippable.jobs.yml**: http://docs.shippable.com/platform/tutorial/workflow/shippable-jobs-yml/
 in your repo

Follow these docs to configure kubernetes integration: http://docs.shippable.com/platform/integration/kubernetes/#kubernetes-integration

**Comment by maxx-bachurin** [comment]
what is the type should be for Kubernetes integration in:

`integrations:
  generic:
    - integrationName: integrationName
      type: type`

**Comment by deepikasl** [comment]
`type` here refers to the `integration type`. But you cannot use `kubernetes` integration in CI, it does nothing.
You need to use `Assembly lines` if you want to deploy to kubernetes.
You can refer this sample project: https://github.com/devops-recipes/deploy-kubernetes-basic on how to deploy.

**Comment by manishas** [comment]
@maxx-bachurin can we set up a call and walk you through how to do Kubernetes deployments? Let me know what times work for you and I'll connect you with our customer success team.

Some docs you should check out:

* [Workflow overview](http://docs.shippable.com/platform/workflow/overview/)
* [Kubernetes tutorials](http://docs.shippable.com/getting-started/kubernetes-tutorials/)

**Comment by manishas** [comment]
@maxx-bachurin while we work on setting up a call with CS, I want to make sure we resolve your env issue. Can you post a link to your build?

The YAML below should work, but please look at the steps and confirm you have followed all of them.

```
build:
  ci:
    - ./cmd/env
  post_ci:
    - ./cmd/deploy_to_k8s

resources:
  - name: kubeconfig
    type: integration
    integration: <integration name from subscription integrations>

jobs:
  - name: <your ci repo name>_runCI
    type: runCI
    steps:
      - IN: kubeconfig

```

- Enable your repository for CI. [Instructions are here](http://docs.shippable.com/ci/enable-project/)
- Since your YAML also has jobs and resources, [add the rsync repo to activate the assembly line config](http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/)
- Your environment variable will be named: $KUBECONFIG_INTEGRATION_KUBECONFIGCONTENT at this point, since the format is <name of integration resource>_INTEGRATION_<field name>

If this doesn't work for you, do you mind letting us know when you created the Kubernetes integration? I want to make sure this isn't an env issue with an integration that was created a long time ago...
