### ISSUE TITLE
shipctl: command not found

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4022]
With this .yml
```
...
language: c
reset_minion: true
python:
  - 2.7
compiler:
  - gcc
build:
  pre_ci_boot:
    image_name: drydock/u14cpp
    image_tag: prod
    pull: true
    options: "-e HOME=/root"
...
  on_success:
    - shipctl post_resource_state "dep-trigger-helper" "versionName" "$BRANCH.$BUILD_NUMBER"
```
we receive
```
shipctl post_resource_state "dep-trigger-helper" "versionName" "$BRANCH.$BUILD_NUMBER" 0s  
/root/6a9613ec-bd58-4694-bc62-624436c6dbf2.sh: line 73: shipctl: command not found
```

Should it be available?
