### ISSUE TITLE
Build randomly fail with ruby 2.4.2 (same with 2.4.3)

### ISSUE THREAD

**Issue by mberrueta** [Shippable/support#4033]
Hello all!

I'm trying to update my ruby version. Locally and in the server it works well, but with  shippable I'm having some issues, and I'm not able to solve it

Thanks in advance for the help

### Description of your issue:

failed build `/runs/5194/1/`

shippable.yml
```
language: ruby

rvm:
  - 2.4.2

env:
  global:
    - COVERAGE=false
    - COVERAGE_REPORTS=shippable/codecoverage
    - CI_REPORTS=shippable/testresults
    - PGHOST=localhost
    - APP_NAME=xxx
    - secure: xxxxx
    - PROJECT=xxxx
    - SLACK_WEB_HOOK=/services/ccc/ccc/ccc
    - MONGO_USERNAME=ccc
    - MONGO_PASSWORD=ccc

integrations:
  key:
    - integrationName: heroku
      type: ssh-key

services:
  - postgres
  - mongodb

addons:
  postgresql: '9.3'
cache: true

before_install:
  - apt-get update && apt-get -y install libgmp-dev libpq-dev
  - gem update --system

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - bundle install --gemfile="Gemfile"
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle-audit update
  - bundle exec rake ci

after_script:
  - bundle exec rake db:drop

after_success:
  - which heroku || wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - mkdir -p ~/.ssh && cp /tmp/ssh/heroku ~/.ssh/id_rsa.pub && ssh-add ~/.ssh/id_rsa.pub

  - >
    if [ "$BRANCH" == "develop" -a "$PULL_REQUEST" == "false" ] ; then
      git remote add heroku git@heroku.com:$APP_NAME-staging.git && git push heroku develop:master -f;
    fi;

  - >
    if [ "$BRANCH" == "master"  -a "$PULL_REQUEST" == "false" ] ; then
      git remote add heroku git@heroku.com:$APP_NAME-production.git && git push heroku master -f;
    fi;

  -  

 
```

And randomly ( different errors in different places)

[BUG] Segmentation fault at 0x0000000000000008
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

![image](https://user-images.githubusercontent.com/1004448/34448563-4de7f40a-eccd-11e7-8202-e2e9b80e61b6.png)
