### ISSUE TITLE
reuse scripts within multiple runSh jobs

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4038]
I have a long setup script:
```
        - script: echo --- NODE UPGRADE ---
        - script: export NVM_DIR=/root/.nvm
        - script: $NVM_DIR/nvm.sh
        - script: source $NVM_DIR/nvm.sh
        - script: echo --- nvm version ---
        - script: nvm --version
        - script: echo --- nvm install ---
        - script: nvm install 6.11
        - script: node --version
        - script: echo --- NPM UPGRADE ---
        - script: if [ $(npm --version) != "5.6.0" ]; then npm install -g npm@5.6.0; fi;
        - script: npm config set spin false
        - script: export PATH=$PATH:node_modules/.bin
        - script: echo --- NPM INSTALL ---
        - script: cd /build/IN/my-repo-name/gitRepo
        - script: npm install
```

I have multiple RunSh jobs that need node installed, each with a one line deploy script.

How can I include this script before the one liner without copy-paste?

e.g.
```
  - name: deploy_to_DEV
    type: runSh
    steps:    
      - IN: sc-pp-frontend-master-pass-version
      - IN: aws-main-shippable-auth
      - IN: sc-pp-frontend-repo-master
        switch: off
      - TASK:
        - include: install_script # defined elsewhere as above list of steps
        - script: deploy dev
```

**Comment by seniorquico** [comment]
We ended up extracting all of our `script: commands` from our YAML files into proper `.sh` scripts. We placed the shell scripts in a Git repo, added the Git repo as a Shippable `gitRepo` resource, and mapped it into our `runSh` jobs. In fact, we put the `.sh` scripts in the same Git repo as all of our YAML files. (Quick side note related to #4039, we also organize our pipeline jobs & resources into multiple YAML files.)

We added our Git repo as a `syncRepo` resource following these instructions:

http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/

Then, we added the same Git repo as a `gitRepo` resource following these instructions:

http://docs.shippable.com/platform/workflow/resource/gitrepo/

We use the following as a template for all of our `runSh` jobs:

```yaml
jobs:

  - name: <our job name>
    type: runSh
    steps:
      - IN: <our list of IN resources/jobs>
      - IN: Our-DevOps_gitRepo
        switch: off
      - TASK:
        - script: export SHIPPABLE_BUILD_DIR="$( shipctl get_resource_state OURDEVOPS_GITREPO )"
        - script: cd "${SHIPPABLE_BUILD_DIR}"
        - script: "${SHIPPABLE_BUILD_DIR}/shippable/ourJob.sh"
    on_success:
      - NOTIFY: <our success notification>
    on_failure:
      - NOTIFY: <our failure notification>
```

Some notes/benefits we've found with this approach:

1) We set `switch: off` on the `IN: Our-DevOps_gitRepo` to ensure changes to our YAMLs or to the shell scripts don't trigger jobs. Instead, the jobs are left to trigger based on our "actual" pipeline inputs, such as commits or tests or whatever. If a script change does warrant a trigger, we just do it manually (which has been relatively rare).
2) We purposefully define and use the `SHIPPABLE_BUILD_DIR` environment variable to bootstrap the script. This allows us to also share and reuse scripts between our `runSh` and `runCI` jobs.
3) We can run the shell scripts locally during development & test scenarios, since the commands are no longer buried in a proprietary YAML schema. (We had to first create and combine this with a bootstrapping script that sets up a local shell to emulate a Shippable environment that gets everything to run as-is. Not sure if I can share ours, but I could look into it. It would be great if Shippable provided this. I think it even came up on a prior GitHub issue/discussion.)
4) We occasionally ran into subtle syntax errors trying to embed certain shell commands in the YAML. That doesn't happen anymore now that we're running everything as a shell script.
5) You have to make sure to set the executable bits on the shell script in the Git repo, or else you'll get permission errors when running on a build node.
6) We use the following shebang and options in all of our shell scripts:

```sh
#!/usr/bin/env bash
set -eufo pipefail
```

**Comment by manishas** [comment]
@seniorquico thanks for the detailed explanation!

@BryanCrotaz do you still need help with this? As a side note, we will launch custom images for runSh in the next few weeks, so I think you'll be able to bake the node install into your image and just run your one line of deploy script.

**Comment by ambarish2012** [comment]
@BryanCrotaz we have launched custom images for runSh jobs. Please find more information **[here](http://docs.shippable.com/platform/tutorial/workflow/using-runSh/#using-a-custom-docker-image).

**Comment by BryanCrotaz** [comment]
Great!
Can we use the standard Shippable images as well?

**Comment by ambarish2012** [comment]
Yes, definitely.

**Comment by BryanCrotaz** [comment]
Docs don’t say that

**Comment by ambarish2012** [comment]
Thanks for the suggestion. We will update the docs and provide an example to use a Shippable image.

**Comment by ambarish2012** [comment]
@BryanCrotaz when using a Shippable image in your runSh job, I would suggest that you specify a tag that is the same version as the AMI in your subscription. The image then shouldn't have to be pulled, since all of the build images are on the AMI already. If you use a different tag or a different custom image, we will have to pull that image. If your runSh job is running on a custom node, the pulled image will get cached.

**Comment by seniorquico** [comment]
@ambarish2012 It would be slick if the current version was exposed as a global environment variable:

```yml
jobs:
  - name: container_custom_image
    type: runSh
    steps:
      - TASK:
          name: custom_container_opts
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: ${SHIPPABLE_AMI_VERSION}
              options: --dns=4.4.4.4 --dns=8.8.8.8
          script:
            - echo "Checking runtime values"
            - sudo docker info
```
