### ISSUE TITLE
Build triggered based on branch commit

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4056]
I want from shippable the following:
Commit to RepoA/BranchXXX triggers a build of RepoB/BranchXXX
Commit to RepoA/BranchYYY triggers a build of RepoB/BranchYYY

My approach was the following

# RepoB/BranchXXX
shippable.jobs.yml
```
jobs:                                    
  - name: RepoB_runCI
    type: runCI
    steps:
      - IN: RepoAGitRepoBranchXXX
    on_failure:
      - NOTIFY: emailMeCI
```
shippable.resources.yml
```
resources:
  - name: RepoAGitRepoBranchXXX
    type: gitRepo
    integration: "Bitbucket integration"
    pointer:
      sourceName:  
      branch: BranchXXX
```

# RepoB/BranchYYY
shippable.jobs.yml
```
jobs:                                    
  - name: RepoB_runCI
    type: runCI
    steps:
      - IN: RepoAGitRepoBranchYYY
    on_failure:
      - NOTIFY: emailMeCI
```
shippable.resources.yml
```
resources:
  - name: RepoAGitRepoBranchYYY
    type: gitRepo
    integration: "Bitbucket integration"
    pointer:
      sourceName:  
      branch: BranchYYY
```
It seems that the two different definitions of `RepoB_runCI` jobs from the two branches clash. 

1. Should this work as expected?
1. Can I solve this using my approach?
1. Can I solve this in a different way (if possible without using shipctl)?
