### ISSUE TITLE
Empty body sent if have multiple webhook subscriptions that point to same account webhook

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#4078]
### Description of your issue:
We are using a messaging service (Ryver) that the Shippable Slack notifications aren't quite working for - Shippable does not put a `Content-Type: application/json` when it sent out to the configured Slack webhook URL (which Slack itself seems to be OK with) plus Ryver isn't quite formatting the links properly.

So, I decided to use a single custom webhook notification (one account webhook integration and one subscription integration pointing to that account integration) but I couldn't find a way to know if it was a 'start', 'success', or 'failure' notification. Doesn't look like there are any environment variables for that. If there is, I could use that to solve me problem so let me know :).

In the absence of that, I thought I could have three notifications in shippable.yml that would set a payload based on the event happening, e.g.
```
integrations:
  notifications:
    - integrationName: "ryver-notification-start"
      type: webhook
      payload:
        - state=STARTED
      on_start: always
      on_success: never
      on_failure: never
      on_cancel: never
    - integrationName: "ryver-notification-failure"
      type: webhook
      payload:
        - state=FAILED
      on_failure: always
      on_start: never
      on_success: never
      on_cancel: never
    - integrationName: "ryver-notification-success"
      type: webhook
      payload:
        - state=SUCCEEDED
      on_failure: never
      on_start: never
      on_success: always
      on_cancel: never
```

With this option, I needed to configure three subscription integrations, one for each type, but to reduce even more configuration at the account integration level, I pointed each of these subscriptions to a single account configuration. However, when I did this during a build, I would get a body of:
```
{
  "state": "STARTED"
}
```
but on the success/failure, I would get an empty body.
```
{}
```
If I made multiple (yet duplicate account integrations), it *would* work.

Is it possible to have multiple subscription integrations point to a single account integration? This seems like a bug but perhaps it isn't supported.

**Comment by trriplejay** [comment]
Thanks for mentioning the missing content-type. Even though slack is accepting payloads without it, we should be supplying that as a best-practice.  I'll open a bug for that.

I'll also open an internal ticket for the empty body.  This appears to be a bug, but we'll have to take a deeper look.

**Comment by trriplejay** [comment]
regarding environment variables, we don't have one that represents the status of the build, but you could create and set that yourself.  It would look something like this:

```yml
# Language setting
language: node_js

# Version number
node_js:
  - 6.11.0

env:
  global:
    - STATE="starting"

build:
    - echo "hello world"

  on_success:
    - STATE="successful"

  on_failure:
    - STATE="failed"

integrations:
  notifications:
    - integrationName: "test_payload"
      type: webhook
      payload:
        - state=$STATE
      on_success: always
      on_failure: always
      on_start: always
```

I've tested this and it seems to get the results you want.
