### ISSUE TITLE
dockerOptions on GKE - memory/cpu limit vs. request

### ISSUE THREAD

**Issue by bartimar** [Shippable/support#4086]
### How to set cpu/memory limit and request in dockerOptions for GKE?
according to docs I can do
```
resources:
  - name: <string>                              #required
    type: dockerOptions                         #required
    version:
      memory: <integer>                         #optional, in MiB
      cpuShares: <number>                       #optional
```
Setting memory and cpuShares to 
```
  - name: nginx_opts_prod
    type: dockerOptions
    version:
      memory: 128
      cpuShares: 100
```
which is deployed to GKE and the running deployment looks like this:
```
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
```
thus it sets limits and requests to the same value, which is rather useless. Am I missing something in the docs or is this not yet supported?

**Comment by trriplejay** [comment]
If you set "cpuShares" it will only set the "limit", and then gke automatically defaults the request to be the same amount.

If you'd like to set both, I'd recommend using a different style in the dockerOptions, which allows a more direct pass-through of your options. It should look like this:

```
version:
  resources:
      requests:
        memory: "123Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
```

other options not directly supported in the dockerOptions table can also be included this way as described here:
http://docs.shippable.com/platform/workflow/resource/dockeroptions/#google-container-engine  (see the section on Google Cloud Integration)

let me know if you have any questions!
