### ISSUE TITLE
Error exporting environment variable with spaces

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4089]
Given the following env matrix snippet in project `54f05f3c5ab6cc13528f2757`:

```yaml
env:
  # ...
  matrix:
    - PHP_VERSION: 5.6
      FOO: value
      BAR: AFoo/Bar B/Foo/Bar
    # ...
```

The `setup_env` steps fails with the following error (build 309):

> echo 'An error occurred while trying to export an environment variable: PHP_VERSION Please check your YML env section'

Removing the `B/Foo/Bar` part from `BAR` avoids the issue but it's essential.

The following doesn't work either (build 310):

```yaml
env:
  # ...
  matrix:
    - PHP_VERSION: 5.6
      FOO: value
      BAR: "AFoo/Bar B/Foo/Bar"
    # ...
```

(Same error)

Using `>`:

```yaml
env:
  # ...
  matrix:
    - PHP_VERSION: 5.6
      FOO: value
      BAR: >
        AFoo/Bar
        B/Foo/Bar
    # ...
```

This also fails with a different (obscure) error (build 312):

> ScriptType:on_start_job_envs|msg:/tmp/mexec/tmp-script.sh: line 282: syntax error near unexpected token `;'

The same error occurs with `|` (build 313).

**Comment by mbrodala** [comment]
As a workaround I now use the classic environment variable format now (build 314):

```yaml
env:
  # ...
  matrix:
    - PHP_VERSION=5.6 FOO=value BAR="AFoo/Bar B/Foo/Bar"
    # ...
```
