### ISSUE TITLE
Question about the possibility of exporting a file generated in nodeJS to shippable

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4113]
### Description of your issue:
My situation is that I have a function in nodeJS to generate a text file by using  the `fs` module (https://nodejs.org/api/fs.html) and I want to use that text file in another job. I have found that Shippable has a way to share information through jobs by using `shipctl`.
 http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/

However, it seems that a file needs to be generated as a part of command lines in the script
![image](https://user-images.githubusercontent.com/14726381/36080210-aa7811ce-0fe0-11e8-8b4c-16210527a8ce.png)

Below is my first job details to generate a file called ids.txt. 
![image](https://user-images.githubusercontent.com/14726381/36080325-86640d22-0fe2-11e8-8355-310d500bdba5.png)

Could you please advise if I should be able to use `shipctl` to support my situation?

If you need more information, please let me know.

**Comment by trriplejay** [comment]
Hello,

Yes, you should be able to use shipctl for this. We do have a file size limit of 1MB, so you'll have to make sure your generated file is less than that.

your command would look something like `shipctl copy_file_to_state /app/data/ids.txt`

then, in a susbsequent job, you would list job_1 as an IN, and then could use something like `IDS_FILE="$(shipctl get_resource_state job_1)/ids.txt"`

**Comment by JoeRattanamaneesilp** [comment]
@trriplejay 

After running this command `shipctl copy_file_to_state /app/data/ids.txt`, is there a way to print the data in ids.txt on the screen? e.g. 
```
- script: shipctl copy_file_to_state /app/data/ids.txt
- script: cat  /app/data/ids.txt
```
Could you please advise?

**Comment by trriplejay** [comment]
since you mentioned that the original file resides in `/app/data/ids.txt`, you should be able to cat it as you've stated above: `- script: cat /app/data/ids.txt`.  If you wanted to cat the copied file from the destination, you would find it in `$JOB_STATE/ids.txt` so you could `- script: cat $JOB_STATE/ids.txt` instead.

**Comment by JoeRattanamaneesilp** [comment]
Hi @trriplejay 

I have tried `- script: cat $JOB_STATE/ids.txt`. However, after running, it is showing as below.

```
cat: 
/build/state/ids.txt: No such file or directory
runSh failed with error: 1
```

In my function, the file will be generated under /app/data/ 

Should the command contain some paths before `/ids.txt`? 
e.g. `- script: cat $JOB_STATE/???/app/data/ids.txt`

**Comment by trriplejay** [comment]
did you attempt the cat after the shipctl command? the file will only be in `$JOB_STATE/ids.txt` *after* you issue the `shipctl copy_file_to_state` command.  Could you provide a link to your build here so I can see what might be going wrong?

`copy_file_to_state` is really just issuing a `cp` command where you tell us the source, and the destination is `$JOB_STATE`.

**Comment by JoeRattanamaneesilp** [comment]
Hi @trriplejay,

It is working now after using `cat $JOB_STATE/ids.txt`

```
steps:
      - IN: migrate-service-repo-branch
        switch: off
      - TASK:
        - script: cd ./IN/migrate-service-repo-branch/gitRepo/src/app/controllers
        - script: >
            curl -H "Content-Type: application/json" -X POST -d '[{"fromEnv":"dev", "fromSite":"nznow", "number":"2", "toSite":"now"}]' http://..../migrate/migrate/
        - script: sleep 1m
        - script: shipctl copy_file_to_state /app/data/ids.txt
        - script: cat $JOB_STATE/ids.txt
```

However, the data comes from the original ids.txt. It doesn't come from an updated ids.txt file that is generated via API in this command  `curl -H "Content-Type: application/json" -X POST -d '[{"fromEnv":"dev", "fromSite":"nznow", "number":"2", "toSite":"now"}]' http://..../migrate/migrate/`.

I may need to investigate more in my javascript function. Below is the codes for updating the ids.txt file in my function.
```
        fs.writeFile(path, str, (error) => {
            if (error) {
                console.error('write error:  ' + error.message);
            } else {
                console.log('Successful Write to ' + path);
                pathId = './app/data/ids.txt';
                fs.appendFile(pathId, id + ',', (err) => {
                    if (err) throw err;
                    console.log('The "data to append" was appended to file!');
                });
            }
        });
```
Can you please advise if you have any idea how to `cat` or get data from the updated ids.txt?

Note: This is the build log.
https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only-troubleshooting/builds/5a839cb61d4b560600c3f18e/console

Thanks & regards,
Joe
