### ISSUE TITLE
Questions about pushing data to AWS S3

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4116]
### Description of your issue:
**Question 1.** 
I have successfully set up my shippable.yml to store artifacts in AWS S3 as the instruction on this page.
http://docs.shippable.com/ci/push-to-s3/

However, that method is pushing the whole repository to S3. 

Could you please advise if there is a way to push only a specific file to S3?

Below is the configuration I have added in my shippable.yml
```
env:
  global:
    - IMAGE= ....
    - BRANCH_NAME=  ....
    - AWS_S3_BUCKET='<my bucket name>'
    - AWS_S3_REGION='<my region>'
    - secure: <my key>

build: 
    ...
    on_success:
    - aws s3 sync $SHIPPABLE_BUILD_DIR $AWS_S3_BUCKET --region $AWS_S3_REGION
```

**Question 2.**
If I want to store data to S3 after running a specific job (in shippable.jobs.yml), what format of the command should I add in shippable.jobs.yml? I have tried to add under `on_success` as below
```
on_success:
      - aws s3 sync $SHIPPABLE_BUILD_DIR $AWS_S3_BUCKET --region $AWS_S3_REGION
``` 
However, it doesn't work.

Note: Below is the full job details

```
- name: spike-export-only
    type: runSh
    always:
      - NOTIFY: migrate-slack-notifications
    steps:
      - IN: migrate-service-repo-branch
        switch: off
      - TASK:
        - script: cd ./IN/migrate-service-repo-branch/gitRepo/src/app/controllers
        - script: >
            curl -H "Content-Type: application/json" -X POST -d '[{"fromEnv":"dev", "fromSite":"nznow", "number":"2", "toSite":"now"}]' http://....../migrate/migrate/
    on_success:
      - aws s3 sync $SHIPPABLE_BUILD_DIR $AWS_S3_BUCKET --region $AWS_S3_REGION
```

**Comment by rageshkrishna** [comment]
Yes, you have the complete aws cli at your disposal. I think `aws s3 cp myfile.txt $MYS3BUCKET` is what you are looking for.

You can take a look at https://docs.aws.amazon.com/cli/latest/userguide/using-s3-commands.html for more examples.

Your on_success is missing the `script` tag. Please look at http://docs.shippable.com/platform/workflow/job/runsh/ for the details about this.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @rageshkrishna 

I will try those solutions.

**Comment by JoeRattanamaneesilp** [comment]
Hi @rageshkrishna 

:white_check_mark: Regarding the first question, your solution has solved my problem. Below is the command I have updated.
```
  on_success:
    - aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt $AWS_S3_BUCKET --region $AWS_S3_REGION
```

:white_check_mark: Regarding the second question, I have added `script` tag and it can execute the command.
```
on_success:
      - script: echo "SUCCESS"
```

:question: However, there is another problem that I'm trying to solve.

When I use the same command in shippable.jobs.yml as I use in shippable.yml, the log shows an error as below.
_Command in shippable.jobs.yml_ 
```
on_success:
- script: aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt $AWS_S3_BUCKET --region $AWS_S3_REGION
```

_Command in shippable.yml_
```
  on_success:
    - aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt $AWS_S3_BUCKET --region $AWS_S3_REGION
```
_The error in the log_
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument
```

The latest troubleshooting is that I have tried to use different paths and also use a real bucket name instead of the variable.
```
on_success:
      - script: echo "SUCCESS"
      - script: aws s3 cp ../data/ids.txt 's3://migrate-service-s3/'
      - script: aws s3 cp ./IN/migrate-service-repo-branch/gitRepo/src/app/data/ids.txt 's3://migrate-service-s3/'
      - script: aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt 's3://migrate-service-s3/' --region 'ap-southeast-2'
      - script: aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt $AWS_S3_BUCKET
      - script: aws s3 cp $SHIPPABLE_BUILD_DIR/src/app/data/ids.txt $AWS_S3_BUCKET --region $AWS_S3_REGION
```

Below are the errors of those five commands in order.
```
on_success 
SUCCESS
The user-provided path ../data/ids.txt does not exist.
The user-provided path ./IN/migrate-service-repo-branch/gitRepo/src/app/data/ids.txt does not exist.
The user-provided path /src/app/data/ids.txt does not exist.
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument
```

Please see the full log in [this link](https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a83bc2a8dfc650600c3c7e0/console)

So the questions I have now are:
- How can I declare `$AWS_S3_BUCKET` and `$AWS_S3_REGION` in shippable.jobs.yml?
- What should be a correct path of ids.txt?

If you need any more information, please let me know.

Thanks and regards,
Joe

**Comment by a-murphy** [comment]
Usually, when using the AWS CLI in a runSh job, a [cliConfig](http://docs.shippable.com/platform/workflow/resource/cliconfig/) input is used to configure the CLI, including the region.

To add a `cliConfig`, add something like this to your `shippable.resources.yml` with your AWS integration:
```YML
resources:
  - name: myCLIConfig
    type: cliConfig
    integration:  myAWSIntegration
    versionTemplate:
      region: us-east-1
```
This will set up the AWS credentials and region, so you won't need the `--region` option in your AWS commands after adding `- IN: myCliConfig` to the `steps` section of your runSh job.


Environment variables can be added to your runSh job with key-value pair [integration resource](http://docs.shippable.com/platform/workflow/resource/integration/) inputs or [params resource](http://docs.shippable.com/platform/workflow/resource/params/) inputs.

For a params resource with `AWS_S3_BUCKET`:
```YML
resources:
  - name: myParamsResource
    type: params
    versionTemplate:
      params:
        AWS_S3_BUCKET: "myS3Bucket"
```
This can then be added to the runSh job as an `IN` resource to make `$AWS_S3_BUCKET` available.


Assuming that the `ids.txt` file is in `/src/app/data` in your gitRepo (as in the logs), `$MIGRATESERVICEREPOBRANCH_STATE/src/app/data/ids.txt` should be the file you're looking for.

**Comment by JoeRattanamaneesilp** [comment]
Hi @a-murphy,

Thanks for the solution. However, there is an error as `Missing 'region' value in pointer section of migrate-service-cli-config's yml`

I have added them in `shippable.resources.yml` and `shippable.jobs.yml`.

_shippable.resources.yml_
```
  - name: migrate-service-cli-config
    type: cliConfig
    integration: digital-nonprod-AWS
    versionTemplate:
      region: ap-southeast-2

  - name: migrate-service-s3-param
    type: params
    versionTemplate:
      params:
        AWS_S3_BUCKET: "s3://migrate-service-s3/"
```
_shippable.jobs.yml_
```
- name: spike-export-only
    type: runSh
    always:
      - NOTIFY: migrate-slack-notifications
    steps:
      - IN: migrate-service-cli-config
      - IN: migrate-service-s3-param
      - IN: migrate-service-repo-branch
```

Below is the error after running the job.
![image](https://user-images.githubusercontent.com/14726381/36237870-d7cc3bc2-1252-11e8-8a93-dce745c8d553.png)
The full log is in [this link](https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a84dd7e728c4c0700603095/console)


I have also tried to use `pointer` instead of `versioTemplate`. However, it is showing the same error.
```
  - name: migrate-service-cli-config
    type: cliConfig
    integration: digital-nonprod-AWS
    pointer:
      region: ap-southeast-2
```
The log for this configuration is [here](https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a84f4271d4b560600c4a84b/console)

Regards,
Joe

**Comment by a-murphy** [comment]
I suspect that it may be because the nodes in your subscription haven't been reinitialized for a while and the version of the build runner you have isn't working with `versionTemplate`.  You could try reinitializing them, which will update you to the newest build runner.

If you don't want to reinitialize the nodes, you could try changing something else in the cliConfig to make sure that a new version is created with `pointer` (switching between `versionTemplate` and `pointer` isn't recognized as a change because they are interchangeable in newer versions).  Changing the `region` and changing it back or adding something else to `pointer` will be recognized as an update.

**Comment by JoeRattanamaneesilp** [comment]
The error is now fixed after creating a new minion which is using the newest build runner.

I will continue to work on this next week. If there is any progress regarding this report, I will update.

**Comment by JoeRattanamaneesilp** [comment]
@a-murphy 

I have one more question about how to add `secure` variable in shippable.resources.yml.

Below is the `secure` variable which is under `global` in shippable.yml
```
env:
  global:
    - IMAGE= ....
    - BRANCH_NAME=  ....
    - AWS_S3_BUCKET='<my bucket name>'
    - AWS_S3_REGION='<my region>'
    - secure: <my key>
```

I have added `AWS_S3_BUCKET` and `AWS_S3_REGION` in shippable.resources.yml
```
- name: migrate-service-cli-config
    type: cliConfig
    integration: digital-nonprod-AWS
    versionTemplate:
      region: ap-southeast-2

  - name: migrate-service-s3-param
    type: params
    versionTemplate:
      params:
        AWS_S3_BUCKET: "s3://migrate-service-s3/"
```
If I want to add `secure` key too, is it possible to do that?

e.g.
```
  - name: migrate-service-s3-param
    type: params
    versionTemplate:
      params:
        AWS_S3_BUCKET: "s3://migrate-service-s3/"
        secure: <my key>
```
