### ISSUE TITLE
post_ci not called

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4119]
### Description of your issue:
post_ci section not getting called.

https://app.shippable.com/github/Falkonry/systems/runs/2410/1/console

```
language: node_js

node_js:
  - 7.10.1

build:
  ci:
    - node --version
    - npm --version
    - ./setup.sh
  post_ci:
    - ./after_build.sh
    - ./publish.sh

integrations:
  notifications:
    - integrationName: slack-notify
      type: slack
      recipients:
        - "#builds"
      on_success: always
      on_failure: always
      on_start: always
      on_pull_request: always
```

Started happening after this build https://app.shippable.com/github/Falkonry/systems/runs/2405/1/console and I confirmed that there is no change in shippable.yml
