### ISSUE TITLE
Some jobs are not auto-triggered 

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4140]
Recently we have noticed that some jobs in the same level are not auto-triggered in our shippable pipeline.

According to the screenshot below, you can see there are four jobs which are supposed to be auto-triggered. However, only one job is auto-triggered while the other three jobs are not.
![image](https://user-images.githubusercontent.com/14726381/36463594-03b9b1a8-171f-11e8-84b7-b5c34fe37106.png)

Below is a part of shippable.job.yml
![image](https://user-images.githubusercontent.com/14726381/36463738-e0dda15c-171f-11e8-8862-883180301670.png)

We haven't modified anything related to those jobs for a while.  Could you please check if this can be a bug?

Please let me know if you need more information

**Comment by a-murphy** [comment]
This is a duplicate of #4127.  Resources updated in a matrix build (other than in the first job in the matrix) aren't triggering jobs using those resources as inputs.  We will fix this.  There are a few options for workarounds.  The easiest option is to add the runCI job as an additional input to the manifest job, but it means that all manifest jobs will be triggered each time the runCI job runs.

**Comment by ambarish2012** [comment]
@JoeRattanamaneesilp here is a sample that implements the workaround - https://github.com/ambarish2012/ci-run-parallel-tests. We can get into a quick call to discuss how you can implement this workaround in your pipeline.

**Comment by JoeRattanamaneesilp** [comment]
Hi @a-murphy,

Regarding your suggestion to add the runCI job as an input, could you please check if my updated setting is correct? The lines I updated have `<<<<<<<` at the end.

```
  # 1. Sync pipeline to CI
  - name: multi-site_runCI
    type: runCI
    steps:
      - OUT: cosmo-site-img-master
      - OUT: cosmo-site-img-branch
      - OUT: elle-site-img-master
      - OUT: elle-site-img-branch
      - OUT: hb-site-img-master
      - OUT: hb-site-img-branch
      - OUT: gt-site-img-master
      - OUT: gt-site-img-branch

 # 2COSMO. Manifest for MASTER image
  - name: cosmo-site-man-master
    type: manifest
    steps:
      - IN: multi-site_runCI     <<<<<<<<<<<<<<<<<<<<<<<
      - IN: cosmo-site-img-master
      - IN: cosmo-site-opts-sit
      - TASK: managed

  # 2ELLE. Manifest for MASTER image
  - name: elle-site-man-master
    type: manifest
    steps:
      - IN: multi-site_runCI    <<<<<<<<<<<<<<<<<<<<<<<
      - IN: elle-site-img-master
      - IN: elle-site-opts-sit
      - TASK: managed
```

Thanks,
Joe
