### ISSUE TITLE
A problem after changing a docker image in an existing job

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4150]
### Description of your issue:
Today I have changed the docker image name in an existing deploy job. 
Please see `#THIS ONE` line in before and after codes.

Before:
```
  - name: migrate-service-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: migrate-slack-notifications
      - NOTIFY: migrate-service-deployment-notifications
    steps:
      - IN: migrate-service-package-master
        switch: off
      - IN: migrate-service-prod-ecs
      - IN: migrate-service-prod-params
      - IN: migrate-service-prod-alb
        applyTo:
        - manifest: migrate-service-manifest-master
          image: migrate-service-branch-docker-registry   #THIS ONE
          port: 3000
      - TASK: managed
        deployMethod: upgrade
```

After
```
  - name: migrate-service-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: migrate-slack-notifications
      - NOTIFY: migrate-service-deployment-notifications
    steps:
      - IN: migrate-service-package-master
        switch: off
      - IN: migrate-service-prod-ecs
      - IN: migrate-service-prod-params
      - IN: migrate-service-prod-alb
        applyTo:
        - manifest: migrate-service-manifest-master
          image: migrate-service-master-docker-registry   #THIS ONE
          port: 3000
      - TASK: managed
        deployMethod: upgrade
```

After running the job, the production site, which used to work before, is not up. 
[This is the job that I ran. Click [here](https://app.shippable.com/github/bauerxcelmedia/jobs/migrate-service-prod-deploy-master/builds/5a94bea2d80d0d07005573b9/trace)]

When I check the AWS Target Groups, it shows that `there are no targets registered to this target group`.
![image](https://user-images.githubusercontent.com/14726381/36707777-f9f329fc-1bc3-11e8-85cd-665b1e87ad83.png) 
This target group worked when I used the previous docker image.

Should it be because of caching?
