### ISSUE TITLE
Expose current AMI version as an environment variable

### ISSUE THREAD

**Issue by ambarish2012** [Shippable/support#4151]
Using the current AMI version while pulling a shippable language image in a runSh or runCI job speeds up the execution of the job tremendously since the docker image is already available on the node. The current AMI version should be exposed as an environment variable.

```yaml
jobs:
  - name: container_custom_image
    type: runSh
    steps:
      - TASK:
          name: custom_container_opts
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: ${SHIPPABLE_AMI_VERSION}
              options: --dns=4.4.4.4 --dns=8.8.8.8
          script:
            - echo "Checking runtime values"
            - sudo docker info
```
