### ISSUE TITLE
using virtual CAN network interface

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4155]
### Description of your issue:
I'm trying to run `sudo modprobe can` and a few other commands in order to enable virtual CAN interfaces for some integration testing.  `modprobe can` loads the CAN kernel module which is normally available on ubuntu 14.04.  I can get the command working in a debug build but when running in pre-ci I get this error:

````
sudo modprobe can
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-141-generic/modules.dep.bin'
````

https://app.shippable.com/github/MIQ-sirrus7/witcan/runs/103/1/console

**Comment by a-murphy** [comment]
When it worked in a debug build, were you running the command directly on the host?  The `pre_ci` step runs in another container, not on the host.  If you need to run commands on the host, you should consider using a [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) job instead of a CI job.  It will let you define `TASK` sections that will run directly on the host as well as sections that run in containers.

**Comment by larsonmpdx** [comment]
thank you, that makes sense now

I ran the same commands in debug.  I ran them on whatever you get when you ssh with the basic debug ssh string that pops up.  it didn't run to completion but the `modprobe can` bit worked at least

it looks like I need to create a sync repo and a 2nd shippable.yml to do this runsh thing.  Is there a simpler way?

**Comment by ambarish2012** [comment]
Yes - you would need to create a sync repo. You don't need a second shippable.yml, you can define the runSh job in your shippable.yml file.

**Comment by ambarish2012** [comment]
Once you define the runSh job, creating a syncRepo is very straightforward using the UI - http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/#adding-a-syncrepo.

**Comment by larsonmpdx** [comment]
I think I understand what I need to do.  I've poked at the docs and tried to make a simple version but it feels enormously more complicated than a bare runCi job.  Can you point me to an example?

The thing I'm stuck on now is something like: if I have a gitRepo trigger for a PR which starts the runSh job, the downstream runCi job seems to be running with the latest master commit instead of the PR commit.

**Comment by larsonmpdx** [comment]
I found an example here - https://github.com/Shippable/support/issues/3778

I tried the "replicate" option but it isn't transferring the git commit like I want.  should I use `shipctl put_resource_state` to do this?

**Comment by larsonmpdx** [comment]
should I save and load the branch and commit I want to build, like in this comment?  Will my runCi job still have the right commit so it posts results and little green checkmarks to the right places in github?

https://github.com/Shippable/support/issues/3417#issuecomment-284121131

**Comment by a-murphy** [comment]
You should be able to use `replicate` to copy the `gitRepo` to the `ciRepo`.  There's an example copying a `gitRepo` to another `gitRepo` [here](http://docs.shippable.com/platform/tutorial/workflow/writing-keyvalues-to-output-resource/#replicating-an-in-resource-to-an-out).  If you list the `ciRepo` in front of your `runCI` job (the name is usually `projectName_ciRepo`, but make sure it matches the name in the UI) as the `OUT` resource in the `runSh` job, the `runSh` job will copy the `gitRepo` commit information to the `ciRepo` and trigger the `runCI` job.

**Comment by larsonmpdx** [comment]
thanks.  I think I almost have it set up right but the ciRepo isn't triggering builds based on my runSh job.  Can you look at my sanitized shippable.yml and SPOG view below?

![image](https://user-images.githubusercontent.com/12436438/36871300-ae61e00c-1d56-11e8-9ecb-6a7cfc779520.png)

````
language: c

compiler:
  - gcc

build:
  ci:
    - ./run_tests.sh

jobs:
  - name: projectName_runSh
    type: runSh
    steps:
      - IN: projectName_gitRepo
      - TASK:
          name: setup_projectName_host
          runtime:
            container: false # run on host
          script:
            - sudo modprobe can
            - sudo modprobe can_raw
            - sudo modprobe vcan
            - (...)
      - OUT: projectName_ciRepo
        replicate: projectName_gitRepo
  - name: projectName_runCI
    type: runCI
    steps:
      - IN: projectName_ciRepo

resources:
  - name: projectName_gitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: organization/projectName
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: false
      buildOnRelease: false
      buildOnTagPush: false
````
