### ISSUE TITLE
Is it possible to trigger a job when all required IN jobs are done?

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4158]
### Description of your issue:
Ideally, we want a release job to be triggered once three test jobs are passed. 
However, the current configuration seems to trigger the release job once every single test is done.

So the release job is triggered three times by every single test job.
![image](https://user-images.githubusercontent.com/14726381/36829157-e2fe24fe-1d71-11e8-8076-e411f3a455bd.png)
Click [here ](https://app.shippable.com/github/bauerxcelmedia/jobs/cosmo-release-master/dashboard)for the shippable URL

![image](https://user-images.githubusercontent.com/14726381/36829133-bb9c3a86-1d71-11e8-975f-c4fc3e556824.png)

The full release job configuration is 
```
  - name: cosmo-release-master
    type: release
    always:
    - NOTIFY: multi-slack-notifications
    steps:
      - IN: multi-site-automation-test
      - IN: cosmo-site-smoke-test
      - IN: compatibility-multi-site-automation-test
      - IN: cosmo-site-version
      - IN: cosmo-site-man-master
        switch: off
      - TASK: managed
    on_success:
      - NOTIFY: cosmo-deployment-notifications
```
![image](https://user-images.githubusercontent.com/14726381/36829214-3ba315e2-1d72-11e8-92b5-61d4420ade1b.png)

Could you please advise if there is any configuration that can support my goal?

**Comment by ankul-shippable** [comment]
@JoeRattanamaneesilp Yes, we do support this feature. You'll need to add `dependencyMode: strict` in your release job definition.
`cosmo-release-master` job definition needs to be updated to:
```
  - name: cosmo-release-master
    type: release
    dependencyMode: strict
    always:
    - NOTIFY: multi-slack-notifications
    steps:
      - IN: multi-site-automation-test
      - IN: cosmo-site-smoke-test
      - IN: compatibility-multi-site-automation-test
      - IN: cosmo-site-version
      - IN: cosmo-site-man-master
        switch: off
      - TASK: managed
    on_success:
      - NOTIFY: cosmo-deployment-notifications
```

For more information on different job triggering modes, please checkout our docs [here](http://docs.shippable.com/platform/workflow/overview/#trigger-modes). Thanks
