### ISSUE TITLE
Email notifications on builds

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4164]
Apologies if this is in the docs but I've had a good look around and can't see it.

I know we get notifications send to the person who committed a change and also tp the project owner but what I'm really looking to do is only send notifications to the project owner if it is specific branches failing / changing.

So as an example committer1 commits a change to the 'master' branch and the build fails I want the project owner and the committer to receive the emails related to the build failure / recovery.

The same scenario occurs but on a 'feature' branch, I only want the committer to receive the email.

Finally, and this would be icing on the cake if possible. A pull request is raised and the build fails, only the person who raised the PR should be notified.

Is any of this possible? If not can this be added as a feature request?

Many thanks, Andy.

**Comment by manishas** [comment]
You can have multiple email integration blocks in your yml. For example:

```
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - --last_committer
        - --owners
      branches:
        only:
          - master
      on_pull_request: never
    
    - integrationName: email
      type: email
      recipients:
        - --last_committer
      branches:
        only:
          - feature*
      on_pull_request: never
    
    - integrationName: email
      type: email
      recipients:
        - --last_committer
      on_pull_request: always

```

Docs are at http://docs.shippable.com/ci/email-notifications/
