### ISSUE TITLE
using virtual CAN network interface with custom image

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4184]
### Description of your issue:
See previous resolved issue:
https://github.com/Shippable/support/issues/4155

In the previous issue I had trouble configuring a host to have the virtual can kernel module before starting a container, I got help setting up a runSh job to do this.  Everything worked.  Then I changed my runCI job to use a custom container and I can't get it going again.  The image runs correctly but the test container doesn't have access to the virtual CANs and the tests needing that fail (the others pass).  I added "--privileged=true --net=bridge" so the boot_container step looks the same as before.  Here's a simplified form of my shippable.yml:

````
language: c

compiler:
  - gcc

build:
  pre_ci:
    - $(aws ecr get-login --no-include-email --region $PRIMARY_ACCOUNT_AWS_REGION)
    # this image is built in another runSh job
    - docker pull $PRIMARY_ACCOUNT_NUMBER.dkr.ecr.$PRIMARY_ACCOUNT_AWS_REGION.amazonaws.com/repo_amd64_base:latest
    - docker tag $PRIMARY_ACCOUNT_NUMBER.dkr.ecr.$PRIMARY_ACCOUNT_AWS_REGION.amazonaws.com/repo_amd64_base:latest repo_amd64_base
    # this image stays on the build machine from pre_ci to pre_ci_boot
    - docker build -t repo_testing -f Dockerfile.repo_testing .
  pre_ci_boot:
    image_name: repo_testing
    image_tag: latest
    pull: false # image should exist from pre_ci job, and should already be local
    options: "--privileged=true --net=bridge"
  ci:
    - ./test.sh

integrations:
  generic:
    - integrationName: aws-keys-primary
    - integrationName: aws-accounts

jobs:
  - name: repo_runSh
    type: runSh
    steps:
      - IN: repo_gitRepo
      - TASK:
          name: setup_repo_host
          runtime:
            container: false # run on host
          script:
            - sudo modprobe can
            - sudo modprobe can_raw
            - sudo modprobe vcan
            - sudo ip link add dev vcan0 type vcan || true
            - sudo ip link set up vcan0 || true
            - sudo ip link add dev vcan1 type vcan || true
            - sudo ip link set up vcan1 || true
      - OUT: repo_ciRepo
        replicate: repo_gitRepo
  - name: repo_runCI
    type: runCI
    steps:
      - IN: repo_ciRepo

resources:
  - name: repo_gitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: org/repo
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: false
      buildOnRelease: false
      buildOnTagPush: false
````

working build (with the default container):
https://app.shippable.com/github/MIQ-sirrus7/witcan/runs/32/1/console
corresponding runSh job:
https://app.shippable.com/github/MIQ-sirrus7/jobs/witcan_runSh/builds/5aa0e705fece96150067ae56/console

failing build (my container):
https://app.shippable.com/github/MIQ-sirrus7/witcan/runs/55/1/console
corresponding runSh job:
https://app.shippable.com/github/MIQ-sirrus7/jobs/witcan_runSh/builds/5aa1e536fdc5ae1500316344/console
