### ISSUE TITLE
Only trigger downstream jobs based on branch

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4188]
Hey Guys, this is probably really straightforward and I've just missed something in the docs. I have some jobs defined with dependencies, as per the SPOG image below. The job definitions are also below.

What I want to happen sf that the downstream job (ms-rpm_runCI) will only be triggered from ms-schemagen_runCI when that job is on the master branch or a release/* branch. I added a branches only section for those two branches but the ms-rpm_runCI was still triggered when the CI ran for a different branch name.

Can you advise how to achieve my desired outcome please?

Thanks, Andy.

![image](https://user-images.githubusercontent.com/15898957/37249686-f4d1e9ce-2526-11e8-9f1f-a50a4b676c57.png)

```yaml
language: java

jdk:
  - openjdk8

jobs:
  - name: ms-schemagen_runCI
    type: runCI
    branches:
      only:
        - master
        - releases/*
    steps:
      - TASK:
        - script: echo "+++++ ms-schemagen_runCI"

  - name: ms-force-logoff_runCI
    type: runCI
    steps:
      - TASK:
        - script: echo "+++++ ms-schemagen_runCI"

  - name: ms-rpm_runCI
    type: runCI
    steps:
      - IN: ms-schemagen_runCI
      - IN: ms-force-logoff_runCI
```
