### ISSUE TITLE
Unable to force deployment

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4193]
Hello,

I am unable to force deployment for images that did not change. I tried littering `force: yes` with no luck :disappointed: 

The [deployment job](https://app.shippable.com/github/damejidlo/jobs/deploy_sidecar_stage/builds/5aa7ff9bec373f17004a8409/console) wrote:
```
Force deployment is: false
Reset deployment is: false
Summary of 2 manifests:
-- scalable:	0
-- deployable:	0
-- removable:	0
```
However, the configuration should force deployment, as far as I understand [the docs](http://docs.shippable.com/platform/workflow/job/deploy/) that hints to add `force: true` to release INput in the deploy job.
```yaml
  - name: sidecar-release_stage
    type: release
    dependencyMode: strict
    flags:
      - cargo
    bump: minor
    steps:
     - IN: cargo-sqlproxy-manifest_stage
       force: true
     - IN: cargo-redis-cache-manifest_stage
       switch: off
       force: true
     - IN: cargo-version_stage
       switch: off

  - name: deploy_sidecar_stage
    dependencyMode: strict
    maxWaitTime: 120
    type: deploy
    force: true
    flags:
      - cargo
    steps:
      - IN: sidecar-release_stage
        force: true
      - IN: cargo-gke-cluster_stage
        switch: off
      - IN: cargo-app_replicas_stage
        switch: off
```

I really need to deploy the images even though they have not been changed. Following parts of my pipeline depend on them. Can you spot a mistake in my config?
