### ISSUE TITLE
using aws keys integration with runCI

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4195]
### Description of your issue:
I am using aws keys to do an s3 upload in runCI.  Here is a working shippable.yml, I used the resources/jobs sections to add aws keys as the special env vars then grabbed them by name in my runCI section.  Is there any way to simplify this?  I'd really like to knock it down to just a CI job so I don't need the sync repo.
````
language: go

go:
  - 1.9

build:
  ci:
    - go get -u github.com/jstemmer/go-junit-report
    - go test -v 2>&1 | go-junit-report > shippable/testresults/report.xml
    # run coverage separately
    - go get github.com/t-yuki/gocover-cobertura # this does not include branch coverage (march 2018)
    - go test -coverprofile=cover.out
    - gocover-cobertura < cover.out > shippable/codecoverage/coverage.xml
  post_ci:
    - export AWS_ACCESS_KEY_ID=$AWSPRIMARYKEYS_INTEGRATION_ACCESSKEY && export AWS_SECRET_ACCESS_KEY=$AWSPRIMARYKEYS_INTEGRATION_SECRETKEY
    - if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ]; then ./upload_build_outputs_to_s3.sh; fi
integrations:
  generic:
    - integrationName: aws-accounts # unrelated

# below is CD/ pipelines/ resources config.  must be added by adding a sync repo
jobs:
  - name: repo_runCI
    type: runCI
    steps:
      - IN: AWSPRIMARY-keys

resources:
  - name: AWSPRIMARY-keys # this shows up as AWSPRIMARYKEYS_INTEGRATION_ACCESSKEY and AWSPRIMARYKEYS_INTEGRATION_SECRETKEY
    type: integration
    integration: AWSPRIMARY
````
