### ISSUE TITLE
access image details from manifest and release jobs

### ISSUE THREAD

**Issue by chtorr** [Shippable/support#4202]
Hello! I'm wondering if there is a way that I can access the `image versionName` that is part of the version of a `manifest` or `release` job that I pass to a `runSh` job.
  

My goal is to setup a gated release where I promote the specific version that was deployed to the previous environment. My deploy for each environment involves 1 `runSh` job for an un-managed ECS oneshot and then 1 managed ECS `deploy` job. I need to ensure that the docker image tag that the `runSh` job uses is the same that the managed `deploy` job uses.

 An abbreviated example of what I'm thinking:
```yaml
resources: 
  - name: app-image
    type: image
    integration: "..."        
    versionTemplate: 
      sourcename: "some-org/app"
      versionName: "123456"
  
  - name: ecs-cluster-dev
    type: cluster
    integration: "..."    
    versionTemplate: 
      sourceName: "dev-cluster"
      region: "us-east-2"
  
  - name: app-version-dev    
    type: version
    versionTemplate: 
      versionName: "0.0.1"

jobs:
  - name: app_runCI
    type: runCI
    steps: 
      - OUT: app-image

  - name: app-manifest-dev
    type: manifest
    steps: 
      - IN: app-image
    
  - name: app-migration-dev
    type: runSh
    steps: 
      - IN: app-manifest-dev
      - TASK: 
          script: 
            - "<access app-image versionName from app-manifest-dev here>"
    
  - name: app-deploy-dev
    type: deploy
    steps: 
      - IN: app-migration-dev
      - IN: app-manifest-dev
        switch: off
      - IN: ecs-cluster-dev
  
  - name: app-release-dev
    type: release
    bump: rc 
    steps: 
      - IN: deploy-dev
      - IN: app-version-dev
    
  - name: app-migration-staging
    type: runSh
    steps: 
      - IN: app-release-dev
        switch: off
      - TASK:
          script: 
            - "<access app-image versionName tied to release-dev version here>"
    
  - name: app-deploy-staging
    type: depoy
    steps: 
      - IN: app-migration-staging
      - IN: app-release-dev
        switch: off
# ...
```

I've noticed that I can see the value I'm looking for in `$(shipctl get_resource_state <manifest>)/manifests.json`, but parsing that file doesn't seem like the right way to do it.

Any guidance would be greatly appreciated!

Thanks!
