### ISSUE TITLE
Specify node pool in yaml file

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4215]
For a CI only job, how do we specify which node pool to use?

Thanks, Andy.

**Comment by ankul-shippable** [comment]
@andye2004 You can specify it in runtime section like this.
```
language: node_js

runtime:
  nodePool: ubuntu14_nodes

build:
  ci:
    - echo "testing node pool"
```

Let us know if it works for you. Thanks

**Comment by manishas** [comment]
@ambarish2012 we should update config docs to show this.

**Comment by andye2004** [comment]
@ankul-shippable, @manishas Top support yet again guys! I'd barely finished typing the question when the answer came through!

Thanks, Andy.

**Comment by andye2004** [comment]
@ambarish2012 @ankul-shippable, I've created a new node pool called big_yins and added a C4.xlarge  on demand node to it. I've added the config below to the shippable.yml file but it still using the default node pool. Any ideas?

```yaml
language: java

runtime:
  nodepool: big_yins

jdk:
  - openjdk8
```
