### ISSUE TITLE
Inconsistent behaviour with webhook notifications

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#4218]
### Description of your issue:
I'm doing something like what was suggested in #4078 where I set an environment variable and then a webhook notification uses that variable plus other build info to send off to Ryver. The weird thing I am finding is that in some cases it sends the right payload and in other cases sends no payload `[]`. It doesn't work when my specific user account does a commit to the `develop` branch. It works fine for me on commits to another branch set up for pull request. It also works for other users when they commit to any branch, including `develop`.

Link to a build where I did the commit to `develop` (didn't work): https://app.shippable.com/bitbucket/luminarts/luminlife/runs/916/1/console
Link to build where someone else did commit to `develop` (worked): https://app.shippable.com/bitbucket/luminarts/luminlife/runs/909/1/console
Link to build on pull request branch by me (worked): https://app.shippable.com/bitbucket/luminarts/luminlife/runs/903/1/console

Here is the section from `shippable.yml` for notifications:
```
    - integrationName: "luminarts-ryver-build-notify"
      type: webhook
      payload:
        - state=$STATE
        - repo_name=$REPO_FULL_NAME
        - branch=$BRANCH
        - build_number=$BUILD_NUMBER
        - build_url=$BUILD_URL
        - commit_message=$COMMIT_MESSAGE
        - committer=$COMMITTER
        - is_success=$is_success
        - displayName=Shippable
        - avatar=https://app.shippable.com/images/slack-aye-aye-yoga.png
      on_start: always
      on_pull_request: always
      on_success: always
      on_failure: always
```

Any ideas?

Thanks,
Kiley
