### ISSUE TITLE
Unable to debug failing deployment

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4231]
I have a failing deployment to my AKS cluster. Everything succeeds until it just hangs on repeating the following message until timeout.

> Waiting for rollout to finish: 0 of 1 updated replicas are available...

You can see a full sample of the build at

> https://app.shippable.com/github/AIAScience/jobs/mlsuite-kube-deploy/builds/5abb692f3459bf0700c298ec/console

Are there any good way to retrieve the manifest file generate in the pipeline? Exposing that would be a good way for me to verify that I have configured everything correctly. It would also be nice if I could see the actual ```kubectl``` commands executed in the log.

**Comment by trriplejay** [comment]
@oyving we're hoping to improve visibility of the internally created objects soon.  In the meantime there are some other ways to figure out what is going wrong.

Do you have access to the kube UI or some interface on azure where you can view the pods? You might get a more precise error message that way.  One common reason we often see: unable to pull the image (if the image is private, the  nodes need to be configured with the credentials).

The way to view the actual deployment object we specify in kubectl is a bit convoluted, but I'll give an example here of how it can be done:

here's an example yml:

```yml
jobs:
  - name: myDepoy
    type: deploy
    steps:
      - IN: myCluster
      - IN: myManifest

  - name: viewObject
    type: runSh
    steps:
      - IN: myDeploy
      - TASK:
          script:
            - DEPLOYSTATE=$(shipctl get_resource_state myDeploy)
            - cat $DEPLOYSTATE/myManifest/kube-deployment-spec.json
        
```
explanation:
- create a job of type runSh that will take the deployment job as an IN. 
- when a job is supplied as an IN, its latest state information will be available in the runSh job
- deploy jobs save the deployed object in the state directory, at the path `state/<manifestName>/kube-deployment-spec.json`.
- you can use shipctl to fetch the state directory of a particular IN job, then add the manifestname/json piece to the end of the path to `cat` the file to the console, making it visible in the runSh console output, though keep in mind this will print any envs that you've added to your podSpec.

Hopefully with this info you can figure out what the problem is. Please let me know if you have any questions.
