### ISSUE TITLE
Using runSh before runCI?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4236]
I have a C++ project and I would like to use static code analasis before compiling the project.

I could do it from within the runCI job but I wanted to test shippable. My idea was to add a runSh job before like this:

```yml
jobs:
  - name: staticGeoRep
    type: runSh
    steps:
      - IN: georep_ciRepo
      - TASK:
          name: format
          script:
            - compile and test

  - name: georep_runCI
    type: runCI
    steps:
      - IN: staticGeoRep       
```

It does not seem to work or at least I do not know were to look for the results.

Thanks for your help

**Comment by a-murphy** [comment]
Since you want the runSh job to run before the runCI job, you'll need to use a different resource to trigger the runSh job.  You can add a gitRepo resource ([documentation here]()) for the same repository to the runSh job as an `IN` to trigger the runSh job.  Then use [replicate](http://docs.shippable.com/platform/tutorial/workflow/writing-keyvalues-to-output-resource/#replicating-an-in-resource-to-an-out) to copy the gitRepo resource to the ciRepo resource (as an `OUT` in the runSh job), which will trigger the runCI job when the runSh job is complete.

To avoid additional webhook triggers, you will likely want to also turn off processing for each type of webhook on the project settings page in the first panel, but leave the "process webhooks" option enabled so that the updates to the ciRepo resource will still trigger.  You also won't need the `staticGeoRep` input on the runCI job if the ciRepo is triggering it, but can add `switch: off` if you still need access to the state of that job in runCI.

The runSh and runCI jobs will appear as separate jobs, with separate logs and statuses, on your subscription dashboard.  If you want to update the status of pull requests on the source provider for runSh as well as runCI, you can add the [showBuildStatus](http://docs.shippable.com/platform/tutorial/workflow/sending-status-to-scm/#status-notifications-for-pull-requests) option to your runSh job.

**Comment by BotellaA** [comment]
Thank you for your help. I understand a bit better the workflow.
However, I still did not manage to get my runSh job running...

```yml
resources:
  - name: georep_start
    type: gitRepo
    integration: bitbucket
    versionTemplate:
      sourceName: ArnaudBotella/georep

jobs:
  - name: georep_static
    type: runSh
    steps:
      - IN: georep_start
        showBuildStatus: true
      - OUT: georep_ciRepo
        replicate: georep_start
      - TASK:
          name: format
          script:
            - do stuff

  - name: georep_runCI
    type: runCI
    steps:
      - IN: georep_ciRepo
```
