### ISSUE TITLE
Unable to overwrite integration

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4249]
Hi,

I need to deploy to different clusters in different GCP projects. I have tried to change integrations with `shipctl put_resource_state {resource} integration {value}` commands. Deployment [job fails](https://app.shippable.com/github/damejidlo/jobs/deploy_sidecar/builds/5ac4deee07829a07001f1410/console) when accessing the cluster in the wrong project. How do I change it? Is there any other way around the issue?

**Comment by trriplejay** [comment]
integration credentials can't be changed in this way. the recommended solution would be to add a second "cluster" type resource that specifies the correct details, and use that as an IN to the deploy job.

**Comment by RadekDvorak** [comment]
Thank you for your response, @trriplejay. Multiplicating cluster resource could be possible, albeit inelegant. Does the same apply to loadBalancers and cliConfigs?

I am worried - can I select the appropriate cluster at runtime? I use a runSh job to template most resources based on an API call with globalEnv - see #4246. Considering my options: cluster resource is a hardcoded deployment INput, resources' integration attributes are immutable and I do not see a way to modify OUTput replicate attribute. I fear I am running out of options :disappointed: Can you give me an advice, please?

**Comment by RadekDvorak** [comment]
Thank you for your elaborate answer. Things seem to be more complicated than I expected. 

I have been working on a pilot implementation - a pipeline for a simpler application that uses only three de-facto static environments: development, staging and production. Each environment is placed into a separate GCP project. What my work converged to was create a deployment script which triggers the first runSh job with some variables (including target git revision for github). The job then uses these variables to reconfigure pipeline resources. It was intended to configure the target GCP project (included in a different shippable integration) as well.

The stateful nature of deployment you describe looks like a major problem I would encounter soon. A development deployment would tear down any previous production deployment, am I right?

At the moment my environments are tied to GCP projects and thus not created at runtime. I could employ some templating and generate multiple `{environment}.shippable.yml` files with unique resource names. This would satisfy the stateful requirement for deploy job. Clusters, loadBalancers and cliConfigs would use correct gcloud integration and project. However a fully dynamic deployments to kubernetes namespaces is in my backlog. I guess these would have to consider the custom deployment job one day.

You are right, a key and its integration per GCP project are required. I created a new service account, key and integration and got to the state the first message in this issue is about. Your suggestion to trigger different deploy jobs sounds interesting. It could keep few jobs common for all environments.

**Comment by avinci** [comment]
@RadekDvorak a few questions for you, so that i can understand the scenarios

- first one, are you trying to use branches to deploy to different targets? Dev, staging & prod
- second what type of app is this. Is it a Docker app to Kube or a VM deployment

I am happy to jump on a call to understand your scenario a bit more. Let me know if that works.

**Comment by RadekDvorak** [comment]
Hi @avinci,

our branching model is based on [git flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html). I found no (bidirectional) mapping between branches and deployment environments for all use cases. That is why I use the API and leave the target environment on human judgement.

This application is a mix of a kubernetes cluster (Docker), GCE (VM) machines and a managed SQL server. Only kubernetes cluster is expected to be deployed with shippable, others are stateful.

**Comment by avinci** [comment]
I think I have a solution for you. Let me write a sample and send it out. Let me know if that works. I going to use direct kube configs to make it work.

**Comment by avinci** [comment]
Ok here is the setup

- create 2 projects of GCP with each of it having a separate GKE cluster
- create one service account and give access to both projects. You can select the IAM of one project, add the service account of the other project and make it a group/editor. (you can be more restrictive if you want to
- Create a Google cloud integration on Shippable with the JSON of the service account
- Now I have 1 repo that does CI based on 2 branches (master and dev, also you can add regex here) and then pushes an image to Docker hub with branchName in the tag https://github.com/avinci/node_app
- I created another repo for kube specs and added GCP CLI and the 2 clusters as resources with a test deploy job with code as below

```
jobs:
  - name: test_kctl
    type: runSh
    steps:
      - IN: node_app_img_dh
      - IN: gcp_cli
        switch: off
      - IN: dev_cluster
        switch: off
      - IN: prod_cluster
        switch: off
      - IN: config_repo
        switch: off
      - TASK:
          name: test
          runtime:
            options:
              env:
                - APP_LABEL: "test-app"
                - PROJECT: "shipbeta" #setting default to dev
                - CLUSTER_RES: "dev_cluster" #setting default to dev
          script:
            - pushd $(shipctl get_resource_state "config_repo")/specs
            # get the tag
            - export APP_IMG=$(shipctl get_resource_version_key node_app_img_dh sourceName)
            - export APP_TAG=$(shipctl get_resource_version_key node_app_img_dh versionName)
            - shipctl replace appDeploy.yml appSvc.yml
            # change the target depending on the version of the image tag
            - if [[ $APP_TAG = *"master"* ]]; then export PROJECT="devops-recipes"; export CLUSTER_RES="prod_cluster"; fi
            - export CLUST=$(shipctl get_resource_version_key $CLUSTER_RES sourceName)
            - export CLUST_REG=$(shipctl get_resource_version_key $CLUSTER_RES region)
            - gcloud config set project $PROJECT
            - gcloud container clusters get-credentials $CLUST --zone $CLUST_REG
            # deploy the app
            - kubectl delete  -f ./appDeploy.yml 2>/dev/null || echo ""
            - kubectl delete -f ./appSvc.yml  2>/dev/null || echo ""
            - kubectl create -o json -f ./appDeploy.yml >> kube_output.json
            - kubectl create -o json -f ./appSvc.yml >> kube_output.json
            - cat kube_output.json
            - popd
```

The code above is doing this

- all the resources as inputs image, gcp cli, config repo and 2 clusters 
- I set the default target to dev. You can also make this dynamic if you want to
- I then get the image info, which tells me whether i should switch case to dev or prod based on tag name
- then depending on the context i get gcloud to set my project as well as the cluster info
- I connect to the cluster in context
- deploy using kubectl. You could also do helm here if you want to...

Let me know if this is what you are trying to do. Of course the code can be more elegant in certain places, but I wanted to get this out as fast as i can...:-)

Happy Shipping..
