### ISSUE TITLE
Respect travis.yml

### ISSUE THREAD

**Issue by jayzeng** [Shippable/support#425]
Looks like when .travis.yml and shippable.yml are defined at the same time, .travis.yml is completely ignored, which in my case, I have something like this:

``` yml
language: node_js

node_js:
  - "0.10"

script:
  - ./node_modules/karma/bin/karma start test/karma.conf.js --no-auto-watch --single-run --browsers PhantomJS

before_script:
  - npm install -g bower codeclimate-test-reporter
  - npm install
  - bower install
```

shipp.yml

```
notifications:
     email:
         recipients:
             - user@email.com
         on_success: change
         on_failure: always
```

I was expecting shippable.yml will merge .travis.yml, which isn't the case. It automatically defaults to ruby setup and it was confusing.

You can see the build at:
https://www.shippable.com/projects/53f65bd7ada2292503ca524b
