### ISSUE TITLE
bump release step add v in front of VERSION_NAME

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4258]
Hello, I was trying to understand at what point our version is getting v in front of it. 
And looks like it's a bump function.

here is version resource:
```
  - name: release-version
    type: version
    seed:
      versionName: "1.0.0"
```

this is a job which does minor bump:

```
  - name: k10-release-minor-bump
    type: release
    steps:
      - IN: release-version
      - TASK: managed
        bump: minor
```
Here are that job logs:
```
 /home/shippable/micro/nod/genExec/managed/release/run.sh 0s  
Release name: k10-release-minor-bump
incrementing the input version
New release version: v1.1.0
```

As you can see New Release version is v1.1.0, even that original version seed without v
