### ISSUE TITLE
Composer fails to clone repository when cached

### ISSUE THREAD

**Issue by joshystuart** [Shippable/support#426]
My https://github.com/crimsonronin/gateway-module has the following [`composer.json`](https://github.com/crimsonronin/gateway-module/blob/master/composer.json)

``` json
...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/zoopcommerce/mongodb-odm"
        }
    ],
    "require": {
        "php": ">=5.4",
        "zendframework/zendframework"               : "2.3.1",
        "doctrine/annotations"                      : "dev-master#a11349d39d85bef75a71bd69bd604ac4fb993f03 as dev-master",
        "doctrine/doctrine-mongo-odm-module"        : "1.0.x-dev",
        "doctrine/doctrine-module"                  : "1.0.x-dev as 1.0",
        "doctrine/mongodb-odm"                      : "dev-hotfix719 as 1.0.0-BETA9",
        "zoopcommerce/gomi-module"                  : "~2.1"
    },
...
```

And [`shippable.yaml`](https://github.com/crimsonronin/gateway-module/blob/master/shippable.yml)

``` yaml
language: php

php: 
  - 5.4
  - 5.5

env:
    secure: <my secure token>

services:
  - mongodb

before_script: 
  - mkdir -p ~/.composer
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "xdebug.max_nesting_level = 1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "{\"config\":{\"github-oauth\":{\"github.com\":\"$GITHUB_TOKEN\"}}}" > ~/.composer/config.json
  - composer self-update
  - composer update

script:
  - phpunit --log-junit shippable/testresults/junit.xml tests/
  - vendor/bin/phpcs --standard=PSR2 src/ tests/Zoop/
  - vendor/bin/phpmd src/ text ruleset.xml

notifications:
   email: false
```

But, composer on Shippable is failing to clone/get the `https://github.com/zoopcommerce/mongodb-odm` repository even though it's public:

![shipfail](https://cloud.githubusercontent.com/assets/3791360/4019390/b956f7d2-2a6a-11e4-84ad-400391186e61.png)

I tried to:
- `reset_minion`
- Adding a github token
- composer update
- removing composer cache directory (eg `rm -rf ~/.composer/cache/*`)

Note: on first run it works ok, but then fails on subsequent runs. This suggests something is going wrong with the `cache`. Also, it works on TravisCI: https://travis-ci.org/zoopcommerce/gateway-module.

![shipworking](https://cloud.githubusercontent.com/assets/3791360/4019404/61dfc0a0-2a6b-11e4-8dde-1b47e96b6b2f.png)

It's really preventing us from migrating to shippable. Any help would be greatly appreciated.
