### ISSUE TITLE
Possible to use runSh to update/set parameters for image dynamically?

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#4266]
### Description of your issue:
Looking over the docs, it's not clear to me if this is at all possible; I am wanting to execute a runSh job which will utilize a script on our BYON implementation/container to populate values in a parameter object  in the pipeline. The examples in your documentation seem to be limited to reading and writing data within runSh jobs, not setting within a runSh and reading elsewhere in the pipeline (same jobs file in my case).

Thank you !

**Comment by trriplejay** [comment]
This is definitely possible.  You'd want to list the `params` resource as an OUT to your runSh job,

then, in your script, you can use `shipctl put_resource_state <params name> <key> <value>` to add key/value pairs to that resource.  Then, if that `params` resource is later used as an IN, it will contain the values set from the runSh job, and they'll automatically be added to the environment.

let me know if you have further quetsions.

**Comment by grouxsome** [comment]
Thanks @trriplejay! It's not currently functioning, doesn't look like the runSh is running. I am guessing I need to list my runSh as an `IN` somewhere (manifest or deploy)? I tried this and received an error about the runSh job not being versioned.

**Comment by trriplejay** [comment]
it depends. if you're writing to a 'params' resource, then that params resource can be the IN, and you don't need the runSh to be an IN.  

It's true that if you include runSh as an IN, but the runSh has not executed yet, the job that lists it as an IN will not run, since it requires the runSh to have run at least once.

**Comment by grouxsome** [comment]
Interesting @trriplejay it's def not being run (code below incase I've done something wrong). If I am referencing the params in a deploy job, would the runSh show up in the logs for the deploy?


```
####### Dynamic Docker Params ########
- name: widgets-meta-params
  type: params
  version:
    params:
      TEST_STATIC: static param value
```

```
jobs:
###### Test RunSh to read data ########
- name: widgets-image-meta
  type: runSh
  steps:
    - OUT: widgets-meta-params
    - TASK:
      - script:
        - shipctl put_resource_state widgets-meta-params TEST_DYNAMIC "dynamic value"

###### Dev (Sandbox) Deploy and Manifest Jobs ########
- name: widgets-dev
  type: manifest
  flags:
  - "service: widgets"
  - "version: dev"
  steps:
  - IN: widgets-image-dev
  - IN: widgets-options

- name: widgets-dev-deploy
  type: deploy
  flags:
  - "service: widgets"
  - "env: dev"
  steps:
  - IN: zd-uw2-prime
  - IN: widgets-meta-params
  - IN: dev-parameters
  - IN: widgets-dev
    force: true
  - IN: widgets-dev-elb
    applyTo:
    - manifest: widgets-dev
      image: widgets-image-dev
      port: 80
  - IN: widgets-dev-replicas
  - TASK: managed
    deployMethod: upgrade
```

**Comment by trriplejay** [comment]
I don't see it in your yml, but it looks to me like the runSh job is still an input to the deploy job, you might want to check the rSync job and make sure it properly removed that connection.  

also, i think your runSh syntax might be a bit off. I think it should be:
```yml
- name: widgets-image-meta
  type: runSh
  steps:
    - OUT: widgets-meta-params
    - TASK:
        script:
          - shipctl put_resource_state widgets-meta-params TEST_DYNAMIC "dynamic value"
```
(no `-` in front of the word 'script', but still spaced in from TASK)
