### ISSUE TITLE
Detached head in RunSh job using gitRepo

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#4269]
I'm using a gitRepo resource in one of my runSh jobs with the idea to execute a merge as the final step of that runSh job. However, this fails with a nullpointer (using jgit)

I notice in the runSh job logs in the setup step, git_sync gives `You are in 'detached HEAD' state.` Assuming this is the reason it fails I like to know if this (detached head) is normal behaviour or should I include an option or something to the resource.

Currenty I configured the resource like:
`
- name: scripts-from-srcRepo
      type: gitRepo
      integration: GitHub
      versionTemplate:
        sourceName: "repo-name"
        branch: "branch-to-checkout"
`

**Comment by a-murphy** [comment]
That is expected when checking out a commit because a commit can appear in more than one branch.  If you would prefer to check out the branch, you can do so in your `TASK` section.  For example:
```YML
  - TASK:
    script:
      - pushd $SCRIPTSFROMSRCREPO_STATE
      - git checkout $SCRIPTSFROMSRCREPO_BRANCH
      - popd
```

The environment variables are documented [here](http://docs.shippable.com/platform/workflow/resource/gitrepo/#default-environment-variables).
