### ISSUE TITLE
Problems with docker volumes

### ISSUE THREAD

**Issue by JJ** [Shippable/support#4270]
### Description of your issue:

I'm trying to use a Docker container for testing a repo, but I'm having lots of trouble doing it. [Here's the latest report](https://app.shippable.com/github/perl6/doc/runs/463/1/console) and here's my shippable.yml:
```
os:
    - linux

build:
  pre_ci:
    - mkdir -p /tmp/t
    - docker pull jjmerelo/perl6-doccer

  pre_ci_boot:
    options: "-v /tmp/t:$SHIPPABLE_BUILD_DIR/t"

  ci:
    - docker run -t -v /tmp/t:/test jjmerelo/perl6-doccer
```

What I'm trying to do is to, first, map a build container directory to an external directory, and then do the opposite: map that directory to a Docker directory, `test`, which is the one that's used inside the directory. I have checked out #2353 and pretty much followed it, but I don't know what happens. In this last case, it looks like it's simply not running the ci phase

**Comment by a-murphy** [comment]
The `ci` section isn't running because `git_sync` has already failed.  Unfortunately, `git clone` can't clone your repository when there is already something there.  Could you mount the directory somewhere other than `$SHIPPABLE_BUILD_DIR` and then copy your files from that location in the `ci` step?  Or mount `$SHIPPABLE_BUILD_DIR` in `pre_ci_boot` instead of `$SHIPPABLE_BUILD_DIR/t` so the `t` folder doesn't exist before `git clone`?  The voume mounts don't need to be exactly the same for multiple containers as long as they both contain the part you plan to share between them.

**Comment by JJ** [comment]
I have tried this one, same thing
```
os:
    - linux

build:
  pre_ci:
    - docker pull jjmerelo/perl6-doccer

  pre_ci_boot:
    options: "-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"

  ci:
    - docker run -t -v $SHIPPABLE_BUILD_DIR/t:/test jjmerelo/perl6-doccer
```
