### ISSUE TITLE
Shippable pipelines giving permission denied from github

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#4273]
Today I attempted to change our shippable pipelines repo. Now it won't sync. I tried to undo my change, but I still get the same problem. We last changed our pipelines about a year ago.

- Link to the build failure: https://app.shippable.com/github/gitglacier/jobs/peak-pipelines_master_rSync/builds/5ad79d01b5dd7d0700c39895/console

Our pipelines repo is a private github repo, so maybe that's why it can't clone it? I'm not sure what key it's using. I attempted to add the SSH key listed in our integration as a deploy key, but it told me it's already used in another repo. This broke without us changing anything pipelines related, please help.

**Comment by a-murphy** [comment]
There should be a deploy key for the syncRepo on GitHub.  Do you see any other deploy keys listed under "deploy keys" in the repository settings on GitHub?  It is possible that the key could have been deleted by GitHub if the account used to add it to GitHub lost access to the repository.

**Comment by a-murphy** [comment]
We can e-mail the public key so that you can add it back to GitHub.  Unfortunately we do not currently have an easier way to recreate the deploy key for an existing syncRepo.  Would the technical contact on your subscription settings page in Shippable be an appropriate address?

**Comment by gitglacier** [comment]
Yes, emailing us the public key so we can add it to the deploy for peak-pipelines would be perfect. The technical contact would be great. Thanks!

**Comment by a-murphy** [comment]
I've sent the public deploy key.  Let us know if you run into any problems with it.

**Comment by gitglacier** [comment]
I hit 
Can you please help us resolve a dv-rel issue? (No such issue existed a year ago when we last changed the repo.)
```
rSync encountered 1 errors while processing gitglacier/peak-pipelines: 
  - Missing dependency for job: dv-rel
```

https://app.shippable.com/github/gitglacier/jobs/peak-pipelines_master_rSync/builds/5ad7b9dc3e7d2b0700109e7f/console

Our shippable.jobs.yml should be quite similar to the sample pipelines: (Also, this was working fine before being recompiled by the git trigger, strangely?)

```
...

 - name: dv-rel
    type: release
    steps:
      - IN: dv-ver
        switch: off
      - IN: dv-test-ecs
        switch: off
      - IN: dv-trigger
        switch: off
      - TASK: managed
        bump: minor

  - name: dv-prod-ecs
    type: deploy
    steps:
      - IN: dv-rel
        switch: off
      - IN: env-prod-ecs
      - IN: env-prod-replicas
      - TASK: managed
        deployMethod: upgrade
```
