### ISSUE TITLE
Incorrect NodeJS version

### ISSUE THREAD

**Issue by PrabhanshuAttri** [Shippable/support#4275]
### Description of your issue:
I have specified Node 8.10.0 in shippable.yml. But CI is still using 4.8.5. I am doing something wrong. 
![selection_003](https://user-images.githubusercontent.com/4739486/38964969-94127678-4397-11e8-8452-14564d398c92.png)

Here is my shippable.yml
```
language: node_js
node_js:
    - 8.10.0 
env:
    - secure:  XYZ
build:
    pre_ci:
        - node --version
        - npm install
        - npm install -g firebase-tools
        - npm run-script build
    on_success:
        - firebase deploy --token $FIREBASE_TOKEN.

```
