### ISSUE TITLE
cliConfig and runSh with AWS IAM integration

### ISSUE THREAD

**Issue by chtorr** [Shippable/support#4277]
Hello!  I am trying to configure a `runSh` job to use AWS cli with credentials from an `AWS IAM` integration via a `cliConfig` resource, but I am unable to locate AWS credentials in the environment.  I am hoping that this can work without using an AWS keys integration by only assuming the role in the AWS IAM integration.

I followed the instructions on http://docs.shippable.com/platform/integration/aws-iam/ to create an integration.  Here's a simplified example of what I'm trying.

```
resources:
  - name: cli-config-iam-role
    type: cliConfig
    integration: my-iam-role
    versionTemplate:
      region: us-east-1

jobs:
  - name: run-task
    type: runSh
    steps:
      - IN: cli-config-iam-role
      - TASK:
          script:
            - aws sts get-caller-identity
```

The example script outputs: 
`Unable to locate credentials. You can configure credentials by running "aws configure".`

Is there something I'm missing?

Thanks!
