### ISSUE TITLE
Upload to Artifactory does not work: Jfrog CLI not found

### ISSUE THREAD

**Issue by Mgutjahr** [Shippable/support#4302]
### Description of your issue:
I tried to tar my node project and upload it to artifactory in order to reuse the files for following deploy jobs. When executing the command `jfrog rt u ..` shippable however reported the build to have failed. Looking at the logs shippable reported that the jfrog cli is not available on the container. 

My shippable.yml file (excerpt): 
```yml
language: node_js
node_js:
  - 8.10.0
build:
  ci:
    - npm install
    - tar -C $SHIPPABLE_BUILD_DIR -czvf /tmp/mytar.tar.gz .
    - jfrog rt u /tmp/mytar.tar.gz myfolder/mytar.tar.gz
integrations:
  hub:
    - integrationName: artifactory_test
      type: artifactory
```

Link to failed build: https://bit.ly/2jeVfTo
