### ISSUE TITLE
AKS Kubernetes volumes

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4303]
I am trying to configure a pod in AKS with a volume following the [regular tutorial](https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume) for doing that. However, I am having difficulty mapping what the tutorial describes to `shippable.yml` syntax.

Is this possible? Any hints on how? The regular `volumes` part of `dockerOptions` isn't doing the right thing.

**Comment by a-murphy** [comment]
The `volumes` in Shippable dockerOptions resource section is intended to easily add volume mounts with container and host paths.  In your case, you'll want to define `volumeMounts` for the container and `volumes` for the deployment.  The dockerOptions resource would look like this:
```YML
  - name: myDockerOptions
    type: dockerOptions
    versionTemplate:
      volumeMounts:
        - name: azure
          mountPath: /mnt/azure
      pod:
        volumes:
          - name: azure
            azureDisk:
              kind: Managed
              diskName: myAKSDisk
              diskURI: /subscriptions/<subscriptionID>/resourceGroups/MC_myAKSCluster_myAKSCluster_eastus/providers/Microsoft.Compute/disks/myAKSDisk
```
