### ISSUE TITLE
Unable to build with oraclejdk7 on ANY image

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4304]
We need to be able to build a version of our software using oraclejdk7 and despite down grading the node image to 5.5.1 and multiple earlier version we keep getting:

 shipctl jdk set oraclejdk7 0s  
The version of the jdk you are trying to use is not supported. The supported versions include openjdk7, openjdk8, openjdk9, oraclejdk8, oraclejdk9

This is very urgent!

**Comment by trriplejay** [comment]
investigating

**Comment by trriplejay** [comment]
@andye2004 could you link me to a particular build where this failure occurs?

**Comment by andye2004** [comment]
@trriplejay Just caught me before bed, https://app.shippable.com/github/yambay-tech/mobility-server/runs/594/1/console.

That's a 5.4.1 image.

**Comment by trriplejay** [comment]
this is a bug.  That version of oraclejdk is present on the image, however shipctl is failing to find it.

Here's a workaround:

use `language: none` in your yml

add a pre_ci_boot section like this:

```yml
build:
  pre_ci_boot:
    image_name: drydock/u16javall
    image_tag: v5.4.1 # this should match the runtime version that you select for your node pool. 5.5.1 at the latest
  ci:
    - export JAVA_HOME="/usr/lib/jvm/java-7-oracle"
    - export PATH="$PATH:/usr/lib/jvm/java-7-oracle/bin"
    - sudo update-alternatives --set java /usr/lib/jvm/java-7-oracle/jre/bin/java
    - sudo update-alternatives --set javac /usr/lib/jvm/java-7-oracle/bin/javac 
    - java -version
```

This will manually set the correct path for utilizing oraclejdk7. Let me know if you have any further quetsions.
