### ISSUE TITLE
passing state between jobs

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4329]
### Description of your issue:
I have some long-running tests that I want to run on a nightly trigger.  My repo has a script called like "run_test.sh test_type" where test type can be gcov, asan, tsan, etc.  I'd like to trigger each test separately so that one can fail and the others can succeed.

I have a nightly trigger feeding into some runSh jobs which then set a "state" OUT and my runCi job has a state IN, like this:

````
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval: "0 02 * * *"
  - name: test_state
    type: state
...

jobs:
  - name: runCI
    type: runCI
    steps:
      - IN: test_state
  - name: tsan
    type: runSh
    steps:
      - IN: gitRepo
        switch: off
      - IN: nightly-trigger
      - OUT: test_state
      - OUT: ciRepo
        replicate: gitRepo
      - TASK:
          name: tsan
          script:
            - shipctl post_resource_state test_state "TEST_OPTION" "tsan"
...

in runSh job, setting the env var:
            - shipctl post_resource_state test_state "TEST_OPTION" "none"

in runCI job, getting the env var:
    - TEST_OPTION="$(shipctl get_resource_version_key test_state "TEST_OPTION")"
````

This works but when four jobs are triggered at once sometimes one job will set the state and another job's state will be overwritten before it runs, so tsan will run twice, for example.  Also my SPOG shows things not hooked up like I want.  How can I improve this?  I saw the "params" resource, would that work better than "state"?

SPOG
![image](https://user-images.githubusercontent.com/12436438/39829124-3d36acb2-5372-11e8-8cfe-5de7aac96db7.png)

**Comment by trriplejay** [comment]
I think there are a few ways you could do this.  Does the nightly trigger always trigger every state every time? If so, you might want to consider turning your runCI into a matrix-style build.

For example:
```yml
env:
  - TYPE=gcov
  - TYPE=ubsan
  - TYPE=tsan
  - TYPE=asan
build:
  ci:
    - echo "type is $TYPE"
    - ./run_test.sh $TYPE
```

This will split your single runCI into 4 separate jobs that get triggered at the same time.  Your runCI will ultimately succeed if all 4 matrix jobs succeed.

Using this method, you could directly connect the nightly trigger to the runCI job (note: doing this will always trigger the default branch for the CI repo). More info on matrix builds can be found here: http://docs.shippable.com/ci/matrix-builds/

However, if not all get triggered at the same time, or if, for example, the different "types" represent different branches in your CI repo, then you'll still need the initial runSh jobs, but I think you can still get rid of the "state" resource.

The runSh job itself can pass state information without having to use a state resource.  Instead of writing something like `shipctl put_resource_state myStateResource myKey myValue` you'd say `shipctl put_resource_state $JOB_NAME myKey myValue` where JOB_NAME is one of our default ENVs that represents the name of the runSh job in this case.  Then, in runCI, you'd have all of the runSh jobs as INs, and you can access the state of each runSh job itself, instead of the state resource.  There is an existing ENV that will tell you which job triggered the runCI, `$JOB_TRIGGERED_BY_NAME`.  This would give you the name of your runSh job, and you could do a `shipctl get_resource_version_key $JOB_TRIGGERED_BY_NAME myKey`, and this would return the value that you saved in runSh, which you can then pass into your script.  Or better yet, the name of the runSh job itself could be the argument to the script, and save you a few llines.  Does that make sense?

The pipeline can tend to look strange when `state` type resources are used, because they have the unique ability to be both an IN and an OUT of the same job. I think if you use one of the other methods I describe, your pipeline will look better and be less complex.

Let me know if you have any additional questions!
