### ISSUE TITLE
Quiet by default (like Travis CI)

### ISSUE THREAD

**Issue by yihui** [Shippable/support#433]
I found a difference in the default setting between Shippable and Travis CI: Travis CI's default notification policy seems to be

``` yaml
notifications:
  email:
    on_success: change
    on_failure: always
```

whereas Shippable is noisy like `on_success: always`. There is no point sending notifications when there is no surprise.
