### ISSUE TITLE
Hub login failed - Unexpected status code [301]

### ISSUE THREAD

**Issue by aug70** [Shippable/support#4330]
### Description of your issue:
Builds fails when logging in to docker hub

```
hub_login 0s
  echo 'Hub login failed' 0s  
Hub login failed
  echo 'Docker login failed for username yalim and email yalim.aytul@gmail.com' 0s  
Docker login failed for username yalim and email yalim.aytul@gmail.com
  echo 'Error response from daemon: Unexpected status code [301] :' 0s  
Error response from daemon: Unexpected status code [301] :
```

Seems docker hub login can not handle 301 response code.

- Link to the build failure
https://app.shippable.com/bitbucket/aug70co/aug70.com/runs/93/1/console
- Scripts called from the yml (optional)
```
language: php
php: 
  - 5.4
build:
  ci:
    - docker build --tag yalim/aug70_wordpress:latest src
  post_ci:
    - if [ "$BRANCH" == "master" ]; then docker push yalim/aug70_wordpress:latest; fi

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - aug70co@gmail.com
      on_success: change
      on_failure: always
    - integrationName: yalimaytul.com-slack
      type: slack
      recipients:
        - "#shippable"
      on_success: always
      on_failure: always
  hub:
    - integrationName: yalim/aug70_wordpress
      type: dockerRegistryLogin
      branches:
        only:
          - master
```
