### ISSUE TITLE
Key-Value integration not working?

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4333]
### Description of your issue:

Hi! I'm trying to use a Key-Value pair integration in my runCI job, but it doesn't appear to be working:

https://app.shippable.com/bitbucket/machinetelemetry/fledge/runs/28/1/console

I've added the integration to `shippable.yaml` at the very bottom according to [the docs](http://docs.shippable.com/platform/tutorial/integration/howto-use-key-value-in-runci/):
```yml
integrations:
  generic:
    - integrationName: my-integration-name # actually something else, but correct 
```
What am I doing wrong? Thanks!
