### ISSUE TITLE
How to increase the counter in a trigger resource?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4334]
I am looking at a way to increase the counter inside a trigger resource. I assume I have to use the shipctl tool but not sure how..

Thanks for your help.

**Comment by trriplejay** [comment]
if the trigger is an OUT of one of your jobs, you can use a command like this:

```sh
shipctl put_resource_state <trigger resource name> count <desired count>
```

**Comment by BotellaA** [comment]
Ok but how to increment the current count value? What would be your recommandation on the strategy to compute the "desired count" value?

**Comment by trriplejay** [comment]
ah, ok. that would look something like this:

```yml
- count=$(shipctl get_resource_version_key <trigger name> count)
- ((count+=1))
- shipctl put_resource_state <trigger name> count $count
```
This way if your initial commit gave a count of 1, this would take that, increment it, save it.

**Comment by BotellaA** [comment]
Thank you that is what I am looking for!

**Comment by BotellaA** [comment]
Maybe you could add this example to the documentation of trigger.

**Comment by BotellaA** [comment]
@trriplejay It does not seem to work if I put this code inside an on_success block at the root of the runCI job. Do you have an idea why?

```yml
compiler:
  - gcc
  - clang

build:
  ci:
    - mkdir -p build
    - cd build
    - cmake ..
    - cd Debug
    - cmake --build . -- -j

on_success:    
  script:
    - |
      if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ]; then 
        counter=$(shipctl get_resource_version_key georep_release_trigger counter)
        ((counter+=1))
        shipctl post_resource_state georep_release_trigger counter $counter 
      fi
```

**Comment by trriplejay** [comment]
looks like there are a couple yml issues here:
1. `on_success` should be indented to the same level as `ci`
2. remove the `script` part, and just have your block, like this:

```yml
build:
  ci:
    - echo "hello world"
  on_success:
    - |
      if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ]; then 
        counter=$(shipctl get_resource_version_key georep_release_trigger counter)
        ((counter+=1))
        shipctl post_resource_state georep_release_trigger counter $counter 
      fi
```

give that a try and let me know if it's still having problems.
