### ISSUE TITLE
pull_job_image takes > 13 minutes

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4337]
Is it expected that `pull_job_image` takes so much time?

Snippet from our main _.yml_
```
language: python
reset_minion: true
python:
  - 2.7
build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: v5.10.4
    pull: true
    options: "-e HOME=/root"
```
but also with
```
...
build:
  pre_ci_boot:
    image_name: drydock/u14cppall
    image_tag: v6.4.4
    pull: true
...
```
