### ISSUE TITLE
Shippable webhook error: Failed to generated outPayload

### ISSUE THREAD

**Issue by bram-rongen** [Shippable/support#4342]
### Description of your issue:
I'm triggering webhooks from my build, they work for `start` and `success` but not for `failure` or `cancel`.

The error that is shown is: `Failed to generated outPayload: Could not parse body`

The relevant part of our shippable.yml:
```
env:
  - BUILD_STARTED: false
  
build:
  ci:
    - export BUILD_STARTED=true

integrations:
 notifications:
   - integrationName: primate_webhook
     type: webhook
     payload:
        - branch=$BRANCH
        - url=$BUILD_URL
        - build_number=$BUILD_NUMBER
        - commit=$COMMIT
        - compare=$COMPARE_URL
        - repo=$REPO_FULL_NAME
        - repo_url=$REPOSITORY_URL
        - project_id=$PROJECT_ID
        - started=$BUILD_STARTED
        - success=$is_success
     on_start: always
     on_success: always 
     on_failure: always
     on_cancel: always
```

link to the failing build: https://app.shippable.com/bitbucket/goalgorilla/eci_demo/runs/111/1/console

I'm unable to debug this, could you let me know what's wrong?
