### ISSUE TITLE
Not respecting replicas

### ISSUE THREAD

**Issue by Boolos** [Shippable/support#4347]
### Replicas in a mutli-stage build:
It appears that I cannot override the replicas in subsequent deploy jobs for a multistage build.  For example:
```
jobs:
  - name: svc_manifest
    type: manifest
    steps:
      - IN: svc_image    # omitted from this example
      - IN: svc_testing_replicas

  - name: svc_testing_deploy
    type: deploy
    steps:
      - IN: testing_clusterr   # omitted from this example
      - IN: svc_testing_manifest
      - IN: svc_testing_replicas
        applyTo:
          - svc_image

  - name: svc_staging_deploy
    type: deploy
    steps:
      - IN: staging_cluster   # omitted from this example
      - IN: svc_testing_deploy
      - IN: svc_staging_replicas
        applyTo:
          - svc_image

resources:
  - name: svc_testing_replicas
    type: replicas
    versionTemplate:
      count: 2

  - name: svc_staging_replicas
    type: replicas
    versionTemplate:
      count: 4
```
Will result in 2 replica pods in the `testing_cluster` and 2 replica pods in the `staging_cluster` instead of 4 replica pods in the `staging_cluster`.
