### ISSUE TITLE
Added ciRepo as an IN resource to a runSh job - but nothing is checked out

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4355]
I need the content of the git repo to run some scripts and some other resources inside of it. So I added the ciRepo as an IN resource to the runSh job. There is some resource metadata present but the contents of the directory that `shipctl get_resource_state` points to is empty.

This worked with a regular gitRepo resources in an unrelated job, so I really don't understand what is going on here.

**Comment by a-murphy** [comment]
When a ciRepo is used as an input, the repository is not cloned.  A gitRepo input, however, will be cloned.  Usually, gitRepo inputs are used where the cloned repository will be required.  If you need the same repository (and commits) in a runSh job as a runCI job, this is usually solved by adding a gitRepo `OUT` to the runCI job with [`replicate: ciRepoResourceName`](http://docs.shippable.com/platform/workflow/job/runci/#yml-definition) to update the gitRepo resource with the current ciRepo commit information.

**Comment by oyving** [comment]
Let me see if I understood that. You want me to do something like:

```
resources:
  - name: some-other-git-repo
    type: gitRepo

jobs:
  - name: the_runCI
    type: runCI
    steps:
      - OUT: some-other-git-repo
        replicate: the_ciRepo

  - name: what-i-want-to-run
    type: runSh
    steps:
      - IN: some-other-git-repo
```

What do I need to specify in the `gitRepo` resource? Branch and all other information should be replicated from the `ciRepo`, right?

**Comment by a-murphy** [comment]
The `gitRepo` will need at least an `integration` (GitHub, Bitbucket, or GitLab depending on the location of the repository) and, in either `versionTemplate` or `pointer`, a `sourceName` (the full name of the repository, for example, `orgName/the`) as documented [here](http://docs.shippable.com/platform/workflow/resource/gitrepo/).  The `branch` does not need to be set, but I would recommend setting `buildOnCommit: false` so that the resource won't be updated directly by webhooks.

**Comment by oyving** [comment]
A bit unintuitive, but this worked. Thanks. It should be more explicit in the documentation that ciRepo and gitRepo are two completely different things.

**Comment by langovoi** [comment]
> I would recommend setting `buildOnCommit: false` so that the resource won't be updated directly by webhooks.

@a-murphy I have next resources and jobs, but `buildOnCommit: false` didn't prevent build on push. So I have two builds: after runCI finished and push to repo.

```yml
  - name: frontend_gitRepo
    type: gitRepo
    integration: GitHub
    versionTemplate:
      sourceName: krddevdays/frontend
      buildOnCommit: false

  - name: backend_gitRepo
    type: gitRepo
    integration: GitHub
    versionTemplate:
      sourceName: krddevdays/backend
      buildOnCommit: false
```

```yml
  - name: backend_runCI
    type: runCI
    steps:
      - OUT: backend_gitRepo
        replicate: backend_ciRepo
        replicateOnPullRequest: true

  - name: frontend_runCI
    type: runCI
    steps:
      - OUT: frontend_gitRepo
        replicate: frontend_ciRepo
        replicateOnPullRequest: true
```
