### ISSUE TITLE
Fail to build with BitBucket Repo

### ISSUE THREAD

**Issue by menny** [Shippable/support#44]
I'm trying use Shippable with a private git repo hosted at BitBucket, but whenever I click the Build button at Shippable UI, I get an immediate "Fail" error, with no explanation, and I see no builds in the _Build history_ tab.
I have a _shippable.yml_ file at the root of my project:

```
language: java

jdk:
   - oraclejdk7

script: 
   - ./gradlew clean build

notifications:
  email:
      recipients:
         - meXXX@gmail.com
```

This is a Java/Android Gradle project. I'm using a Gradle Wrapper (the executable is in the root of the project), rather than regular Gradle.
