### ISSUE TITLE
How to expose service-provided Redis to build docker?

### ISSUE THREAD

**Issue by ronjouch** [Shippable/support#4400]
I have a working Shippable build, looking something like:

```yaml
language: node_js

build:
  pre_ci_boot:
    image_name: blah/my-shippable-docker-image
    image_tag: latest
    options: "-e HOME=/root"
  ci:
    - npm run test:ci
```

I'm adding tests depending on Redis, so I added the required section to use the [Redis service you provide](http://docs.shippable.com/ci/redis/):

```yaml
services:
  - redis
```

Now, my tests reasonably fail with errors `[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379`. The port is not exposed to my Docker image. But then I fail to do so. I tried to:

1. Add a `-p 6379:6379` to my `build.pre_ci_boot.options`
2. Add a [resource with `portMappings`](http://docs.shippable.com/platform/workflow/resource/dockeroptions/):
```yaml
resources:
  - name: exposeRedisPort
    type: dockerOptions
    versionTemplate:
      portMappings:
        - "6379:6379"
```

... both without success. What am I doing wrong? Thanks.
