### ISSUE TITLE
post init containers

### ISSUE THREAD

**Issue by ahaiong** [Shippable/support#4408]
This is a general question on howto/if this is possible.

On a deployment I'd like to also run a command through my newly built image/container. Similar to Kubernetes init container. Is this possible? What jobs/resource/flags would I need to perform this.
It needs to run through the container since it requires the files/code that's just been built.

Regards

**Comment by trriplejay** [comment]
are you asking if we support kubernetes init containers specifically, or if we can provide a similar functionality on a different provider?

Today you can specify the initContainers section of the podSpec in a dockerOptions resource at the `pod` level.  That would look something like this:
```yml
resources:
  - name: myOptions
    type: dockerOptions
    versionTemplate:
      pod:
        initContainers: 
          - name: myApp
            image: myrepo/myapp
            command: ['sh', '-c', 'echo test init containers']
```

Then you'd IN this on a deploy job, and use `applyTo` to target the manifest you want it to be part of (applyTo not needed if there is only one manifest).
