### ISSUE TITLE
How to get the build status for webhooks

### ISSUE THREAD

**Issue by bram-rongen** [Shippable/support#4423]
Hi guys!

I want to have the build status available in my webhooks, is there an environment variable I can use?  Right now I'm using the $is_success variable but seems to just be the exit code of the test command. This way I'm unable to identify unstable builds.

I'm triggering webhooks from my configuration like this:
```
integrations:
 notifications:
   - integrationName: primate_webhook
     type: webhook
     payload:
        - branch=$BRANCH
        - url=$BUILD_URL
        - build_number=$BUILD_NUMBER
        - commit=$COMMIT
        - compare=$COMPARE_URL
        - repo=$REPO_FULL_NAME
        - repo_url=$REPOSITORY_URL
        - project_id=$PROJECT_ID
        - started=$BUILD_STARTED
        - success=$is_success
     on_start: always
     on_success: always 
     on_failure: always
     on_cancel: always
```
