### ISSUE TITLE
Time triggered build generated in dry run not working

### ISSUE THREAD

**Issue by dturczanski** [Shippable/support#4432]
I generated time trigger and jobs in dry run but after pushing yml to repo pipeline is not updated in SPOG view:

```
language: java

jdk:
  - oraclejdk8

build:
  ci:
    - lib/dependencies/install-missing-dependencies.sh
    - mvn -B -q install
    - if [ "$NIGHTLYTRIGGER_NAME" == "nightly-trigger" ]; then ./bin/heavy_ci.sh; fi


jobs:
  - name: myRepo_runCI
    type: runCI
    steps:
      - IN: nightly-trigger

resources:
  - name: nightly-trigger
    type: time
    versionTemplate:
      interval: 15 7 * * *
```
