### ISSUE TITLE
SPOG not updating

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#4434]
### Description of your issue:

I have in shippable.yml
```
jobs:
  - name: yandexkassa_lib_runCI
    type: runCI
    steps:
      - IN: houry-trigger
      - IN: yandexkassa_lib_ciRepo

resources:
  - name: houry-trigger
    type: time
    versionTemplate:
      interval: "0 * * * *"
```
I have tried to sync repo and waited for a long time. It is not changed and not triggered at all
