### ISSUE TITLE
IN resource version for serial runSh builds

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4444]
This is a question rather than a problem.

Use case:
Job runCI in `base_Repo` pushes to an external repository `ext_Repo`. After the push we want to execute several runSh jobs one by one for **the same commit** to `ext_Repo`. Is this behaviour supported?
(Should not be important but we also need `base_Repo` data so I included it in the example below.)

Expected:

1. `base_Repo_runCI` pushes to `ext_Repo` version 1.0
2. `test1_runSh` is triggered with version 1.0
3. someone commits to `ext_Repo` making version 2.0
4. after `test1_runSh` finishes, `test2_runSh` is triggered with **version 1.0**

.shippable.yml:
```
...
  - name: test1_runSh
    type: runSh
    steps:
      - IN: base_Repo
        switch: off
      - IN: ext_Repo
...
  - name: test2_runSh
    type: runSh
    steps:
      - IN: base_Repo
        switch: off
      - IN: ext_Repo
        switch: off
      - IN: test1_runSh
```
