### ISSUE TITLE
Assistance to Create Test Stack

### ISSUE THREAD

**Issue by cristianszz** [Shippable/support#4454]
Hi,

We are increasing the coverage of tests and we need to create a test stack contemplating two test types.
Currently doing deploy in a test environment and after that, we call the execution of our integration test and after the correct execution we call the execution of e2e. I would like help implementing this flow correctly because of the way it is configured the e2e tests are not called and deploy is not running on staging.

Desired flow:
```Test deployment (test env) ----> Integration Test --(if ok)--> e2e tests --(if ok)--> staging deployment (staging env)```

Actual flow:
<img width="1390" alt="le-tests" src="https://user-images.githubusercontent.com/37660844/42655537-75e91a54-85ea-11e8-9bb3-3337d906e481.png">

Thanks.

**Comment by trriplejay** [comment]
One thing i notice is that your integration-test-runCI has an image OUT which connects it to the e2e_runCI, but your integration_test_runCI doesn't seem to write to that image.  You might want to consider removing that resource and using integration_test_runCI directly as an IN to e2e, this way it will trigger every time.

Regarding the staging deployments, do you already have jobs set up for that and they are not yet connected? or are you still figuring out which jobs to create?

**Comment by cristianszz** [comment]
Hi @trriplejay, 
Ok, I'm going to do this, but I need the e2e tests to run only if the integration tests run successfully. 

On the call to deploy in staging I'm first setting it up this way:
```
jobs:
# job for e2e
  - name: le-e2e_runCI
    type: runCI
    dependencyMode: immediate
    flags:
      - LE
    steps:
      - IN: le-integration-test-img
      - OUT: le-access-control-deploy-staging-ecs
      - OUT: le-airbase-deploy-staging-ecs
      - OUT: le-aircraft-deploy-staging-ecs
      - OUT: le-forecast-deploy-staging-ecs
      - OUT: le-gateway-deploy-staging-ecs
      - OUT: le-web-deploy-staging-ecs
      - OUT: le-itinerary-deploy-staging-ecs
      - OUT: le-report-deploy-staging-ecs
      - OUT: le-search-deploy-staging-ecs
      - OUT: le-upload-deploy-staging-ecs
      - OUT: le-users-deploy-staging-ecs
      - OUT: le-maintcontrol-deploy-staging-ecs
```
Is it correct or is there any other way to deploy?
