### ISSUE TITLE
Run jobs before runCI job

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4456]
Similar to #4236 I'm trying to have some jobs executed before the `runCI` job. I was hoping to run some preparation commands whose result should be used by all following jobs. So basically:

    gitRepo -> prepare -> runCI (matrix build) -> deploy

You can see my attempt in project `58ab0bf60bfe57100058d7a6` whereas the `shippable.yml` roughly looks like this:

```yaml
language: php

php:
  - "7.0"

env:
  matrix:
    - TASK: task1
    - TASK: task2
    - TASK: task3

build:
  ci:
    - $TASK

resources:
  - name: project_gitRepo
    type: gitRepo
    integration: bitbucket
    versionTemplate:
      sourceName: owner/project

jobs:
  - name: project_build_prepare
    type: runSh
    steps:
      - IN: project_gitRepo
      - TASK:
        script:
          - prepare1
          - prepare2
          - prepare3
      - OUT: project_ciRepo
        replicate: project_gitRepo

  - name: project_runCI
    type: runCI
    steps:
      - IN: project_ciRepo

  - name: project_deploy
    type: runSh
    steps:
      - IN: project_runCI
      - TASK:
        script:
          - deploy1
```

However, when I now push a change to my Git repository the only thing executed is `project_runCI`. In the SPOG I see this:

    project_ciRepo -> project_runCI (project_ciRepo  twice as IN) -> project_deploy
    project_gitRepo -> project_build_prepare

However, I obviously would like this instead:

    project_gitRepo -> project_build_prepare -> project_ciRepo  -> project_runCI -> project_deploy

Any idea what's wrong?

**Comment by mbrodala** [comment]
The `project_build_prepare` job currently is in an inconsistent state because it failed in its _Setup_ step:

    Generating job steps
    reqProc|job|generateSteps|_generateScript, Failed to generate script for task : 0 with err: TypeError: cmd.replace is not a function

**Comment by mbrodala** [comment]
Alright, after running `project_branch_rSync` I was able to see that I had syntax errors in my `TASK` steps. Here's the fixed `shippable.yml`:

```yaml
language: php

php:
  - "7.0"

env:
  matrix:
    - TASK: task1
    - TASK: task2
    - TASK: task3

build:
  ci:
    - $TASK

resources:
  - name: project_gitRepo
    type: gitRepo
    integration: bitbucket
    versionTemplate:
      sourceName: owner/project

jobs:
  - name: project_build_prepare
    type: runSh
    steps:
      - IN: project_gitRepo
      - TASK:
          script:
            - prepare1
            - prepare2
            - prepare3
      - OUT: project_ciRepo
        replicate: project_gitRepo

  - name: project_runCI
    type: runCI
    steps:
      - IN: project_ciRepo

  - name: project_deploy
    type: runSh
    steps:
      - IN: project_runCI
      - TASK:
          script:
            - deploy1
```

Now the pipeline actually looks like expected:

    project_gitRepo -> project_build_prepare -> project_ciRepo  -> project_runCI -> project_deploy

However, pushes to the Git repository still only trigger `project_runCI ` ...
