### ISSUE TITLE
Use shared deploy job with parameters

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4458]
We currently have many repositories with PHP packages which trigger a Composer repository ([Satis](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#satis)) update after a successful build.

I'm thinking about moving the deploy step to a `runSh` job and have it set up so that arbitrary package repositories can trigger that job. For the Satis credentials I will use a [`params`](http://docs.shippable.com/platform/workflow/resource/params/) resource and for connecting arbitrary `runCI` jobs with that `runSh` job I could most likely use a globally shared [`state`](http://docs.shippable.com/platform/workflow/resource/state/) resource where I at least need to store the `$REPOSITORY_URL` of the `runCI` job to use this in the `runSh` deploy job.

Is this gonna work the way I imagine this? Since the deploy job will be used by many repositories and setting up these repositories should be as easy as possible I cannot simply add all `runCI` jobs as `IN` for the `runSh` deploy job. That's why I think `state` will help here.

**Comment by a-murphy** [comment]
As long as the `state` resource contains all the information your `runSh` job needs, there shouldn't be any problem with using a `state` resource updated by many other jobs as input.  You may want to add [`dependencyMode: immediate`](http://docs.shippable.com/platform/workflow/job/overview/#job-trigger-modes) to the `runSh` job with so many independent inputs, but that will just make sure that it's still triggered if another one of the jobs is currently running or has failed.

**Comment by manishas** [comment]
@mbridala I want to confirm we understand your scenario. Here is what you're hoping to implement:

![image](https://user-images.githubusercontent.com/2983749/42787291-b2d60ca2-890e-11e8-8e24-dfecc3a4716b.png)

You want the runSh job to be updated each time the intermediate resource is updated by some runCI job.

If that is correct, you should not use the `state` resource as the intermediate. `state` is mainly meant for situations where you want some central resource that is written to by multiple upstream or downstream jobs **without causing circular dependencies**. So updating a `state` resource does not trigger the next job in your Assembly Line.

If the runCI jobs are writing key-value pairs to the intermediate resource, you should use a `params` resource to store those key-value pairs. This will work as expected and the `params` resource will trigger the runSh job.

**Comment by mbrodala** [comment]
@a-murphy Thanks for the hint.

@manishas Good suggestion to use `params` instead. That `params` resource could then be a `IN` for the `runSh` deploy job.

Can you provide two `shippable.yml` to illustrate how this would work? I'm not sure about this since the `params` resource would be shared globally and only allows for static values AFAIK. Or do you mean that the `runCI` of the projects use `shipctl` to put a key-value-pair into the `params` resource?

**Comment by a-murphy** [comment]
CI YML:
```YML
build:
  ci:
    - shipctl put_resource_state myParams myKey myValue
```

Assembly Line YML (may be in more than one file if that is preferred):
```YML
resources:
  - name: myParams
    type: params
    versionTemplate:
      params:
        key: "value"

jobs:
  - name: myCIProject_runCI
    type: runCI
    steps:
      - OUT: myParams

  - name: myRunSh
    type: runSh
    steps:
      - IN: myParams
      - TASK:
          name: myTask
          script:
            - commandOne
            - commandTwo
```

Resources, including `params`, can be updated in jobs using `shipctl`.  The updated keys can either be ones that were defined in the YML or completely new ones.  If the resource is updated again in the YML (with changes to that specific resource, not just the file), then the changes made in the jobs will be lost and the new version will match the YML again.
