### ISSUE TITLE
Problems adding output resource to runCI job

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4459]
### Problem
failed rsync: https://app.shippable.com/bitbucket/mazoea-team/jobs/te-binaries_ubuntu14_rSync/builds/5b4c73428506c307008f325c/console
```
rSync encountered 1 errors while processing mazoea-team/te-binaries: 
  - Cannot add runCI job, please enable the project before adding job: te-binaries_runCI
```

But in `Enable Project...` I see `te-binaries` with green `Enabled CI` and in `Add Assembly Line` I see te-binaries_{master,ubuntu14}.

### What do I want

I push a tag to repo1, repo1 runCI updates resource1, which is used as IN in for job1 that gets executed.

### What is done

resource1 (teBinariesTagged):
```
...
  - name: teBinariesTagged
    type: params
    versionTemplate:
      params:
        tag: "none"
...
```

repo1 runCI  .shippable.yml (te-binaries branch ubuntu14) contains:
```
...
  on_success:
    - if [[ "x$IS_GIT_TAG" == "xtrue" ]]; then shipctl put_resource_state teBinariesTagged tag "$COMMIT" ; fi

jobs:                                    
  - name: te-binaries_runCI
    type: runCI
    steps:
      - OUT: teBinariesTagged
...
```

and job1
```
...
  - name: i2t_valgrind_perf_runSh
    type: runSh
    steps:
      - IN: teBinariesTagged
...
```
