### ISSUE TITLE
need help to create a pipeline with AWS ECS with autoscaling and ALB option

### ISSUE THREAD

**Issue by vinaganti** [Shippable/support#4462]
### Description of your issue: i am looking for help to set up a ECS autoscaling with ALB
Please provide any use cases and sample shippable configuration for my use case, also please let me know that should i provision a autoscaling with ECS cluster prior to shippable configuration or will  shippable take care of creating autoscaling? 

NOTE: If you are experiencing a build failure, please include:
 
- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
There are two forms of autoscaling with ECS.  The cluster can autoscale its nodes, and a service can autoscale its tasks.  I'd recommend that you set up your cluster with node autoscaling ahead of time.  Then you can add this cluster to shippable as a resource in a deploy job.  You can then use the [replicas resource](http://docs.shippable.com/platform/workflow/resource/replicas/) to set up ECS task autoscaling for your service.

I don't think we have a good sample project right now that shows task auto-scaling, but I'll look into putting one together.

**Comment by vinaganti** [comment]
Hi John,
Thanks you for quick response!
i still have few questions about ECS auto scaling, please check the below replica shippable configuration for ECS service scaling and correct me if it is wrong.

resources:
  - name: deploy-ecs-replicas
    type: replicas
    flags:
      - deploy-ecs-frontend
    versionTemplate:
      count:               2           
      minReplicas:         2
      maxReplicas:         5
      autoScalingRole:     <string>
      autoScalingPolicies:
        ResourceId: "service/BNC-UAT-TEST-CLUSTER/service_name"
        ScalableDimension: "ecs:service:DesiredCount"
        ServiceNamespace: "ecs"
      metricAlarms:
        PolicyName: 
        AlarmAction:     

1) how can i relate the count, minReplicas and maxReplicas in shippable file with node/cluster ec2 instance scaling(min, max and desired count), are they same or different ? my assumption is shippable replicas are per node?
2) should i use the same ec2 scaling policies and cloud watch metrics for the service scaling or should shippable create those or should i create before the pipeline configures for  autoScalingPolicies and metricAlarms?

3) in ResourceId: "service/cluster_name/service_name"  i think shippable is creating the ECS service, in that case how should i know the service_name to pass the value here?

**Comment by trriplejay** [comment]
1. The min/max does not translate to node/cluster instance scaling, it only applies to service scaling.  If you need node/cluster scaling, you'll have to set that up manually when you create your cluster.
2. For service autoscaling, I'd recommend putting all of the details into your replicas resource and letting Shippable create the policy and metricAlarm on your behalf.
3. ResourceId, ScalableDimension, and ServiceNamespace should not be included in your yml.  They will be automatically filled in by Shippable when the deploy job executes.

Here's a basic replicas example that defines a policy and metric alarm:
```yml
  - name: myReplicas
    type: replicas
    versionTemplate:
      count: 1
      minReplicas: 1
      maxReplicas: 5
      autoScalingRole: <your role ARN>
      autoScalingPolicies:
        - PolicyName: myPolicy
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 150
      metricAlarms:
        - AlarmName: "myAlarm"
          ComparisonOperator: "GreaterThanThreshold"
          EvaluationPeriods: 2
          MetricName: "high-cpu"
          Namespace: "test"
          Statistic: Average 
          Period: 60
          Threshold: 75.0
          AlarmActions:
            - myPolicy
```
