### ISSUE TITLE
Docker Multi-Stage Builds

### ISSUE THREAD

**Issue by danielahedges** [Shippable/support#4464]
### Cannot get docker multi-stage build to work

The first part of my dockerfile is this:
```
# Dockerfile

FROM node:10.2-alpine AS build
```

And in my shippable.yml file, I'm running a script that includes the build docker image command:

```
docker version
docker image build -t ${DOCKER_IMAGE} .
```

I'm getting an error message:

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
Sending build context to Docker daemon 1.425 MB

Step 1/25 : FROM node:10.2-alpine AS build
Error parsing reference: "node:10.2-alpine AS build" is not a valid repository/tag: invalid reference format
```

Notice that the docker version numbers for both client and server are 1.13.0.

According to this document http://blog.shippable.com/multi-stage-docker-builds all I need to do is update my node to machine image v5.8.2, and I should be able to use docker version 17.06.0-ce, which supports multi-stage builds. Well, I've done that, and in my build's `pull_job_image` step I'm getting `shippable_retry sudo docker pull drydock/u16nodall:v6.6.4`. But still, I'm getting a super-old version of Docker, 1.13.0, not 17.06.0-ce.

So, how can I get a different version of docker on my build image?

Here's my shippable.yml FWIW:

```
language: node_js
node_js:
  - 10.2.1

# services:
#   - mongodb

env:
- secure: ...

branches:
  only:
    - dev-branch

build:
  ci:
    - ./scripts/buildImage.sh
  post_ci:
    - ./scripts/deploy.sh
```

Here's a link to a recent build failure: https://app.shippable.com/github/Elligo/elligo-central/runs/28/1/console
