### ISSUE TITLE
Cache make build failed since subscription upgrade

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#4471]
We recently upgrade our subscription from 5 on_demand L nodes under ubuntu 14.04 to 5 on_demand XL nodes under ubuntu 16.04.

We did not change anything in our shippable.yml and in our scripts, so the config of the cache did not changed.

Since the upgrade we need to reset the cache for every build to make it pass. Otherwise the build failed at the "git sync" step with the error: "fatal: not a git repository (or any of the parent directories): .git"

https://app.shippable.com/github/hiptest/hiptest/runs/5867/summary/console

**Comment by trriplejay** [comment]
This seems to be a duplicate of #4297

A workaround for now would be to update your pre_ci_boot section to specifically use the `drydock/u16ruball:v6.1.4` image while we continue to investigate this problem.

```yml
build:
  pre_ci_boot:
    image_name: drydock/u16ruball
    image_tag: v6.1.4
    pull: true
  ci:
    - echo "your ci commands here"
```

I'll close this, but you can track the other issue for a resolution. Let me know if you have any questions.
