### ISSUE TITLE
shipctl / [: too many arguments

### ISSUE THREAD

**Issue by michael-paddle** [Shippable/support#4472]
### Description of your issue:
When I run shipctl I get a strange error message: 

```
shipctl get_integration_resource_field aws_dev accessKey
/usr/local/bin/utility.sh: line 125: [: too many arguments
```

I don't understand why this is because I have an almost identical shippable.yml with an almost identical integration which is working.  

My build then fails later because I do not have the appropriate integration data.  

- Link to the build failure

https://app.shippable.com/github/PaddleHQ/aws-cloudflare-deploy/runs/10/1/console

an example of the error happens on the 4th line of  build_ci

**Comment by michael-paddle** [comment]
Having looked inside the build machine I notice that the integrations aren't working.  (from running shipctl with bash -vx) 

```
++ '[' -z masterName ']'
++ '[' -f /integration.json ']'
++ echo 'The given resource is not of type integration. /integration.json: No such file or directory'
+ '[' The given resource is not of type integration. /integration.json: No such file or directory == keyValuePair ']'
/usr/local/bin/utility.sh: line 125: [: too many arguments
```

Looking at the job, I can see that the YAML definition has not updated and doesn't .  Could that be related to the problem?

**Comment by scriptnull** [comment]
The job is expecting an [integration resource](http://docs.shippable.com/platform/workflow/resource/integration/) named `aws_dev` to be given as `IN` on the runCI job, so that the job could access the accessKey from it.

Example: The shippable.yml should resemble something like the below

```yml
resources:
  - name: "aws_keys"
    type: integration
    integration: aws_keys_integration

jobs:
  - name: aws-cloudflare-deploy_runCI
    type: runCI
    steps:
      - IN: aws-cloudflare-deploy_ciRepo
      - IN: aws_keys
```

Could you confirm if your YML contains `IN: aws_dev` ( like shown above ), else you could try adding it and see if you are able to access the required variables? 

I am also opening an internal bug to avoid the strange error message.

**Comment by michael-paddle** [comment]
@scriptnull 

Yes;  my jobs section contains aws_dev - like so

```
jobs:
  - name: aws-cloudflare-deploy_runCI
    type: runCI
    steps:
      - IN: aws_dev
        switch: false
      - IN: thegitfordeploy
```

and my resources also matches that, starting like so:

```
resources:
  - name: aws_dev
    type: integration
    integration: aws_dev
```
