### ISSUE TITLE
gitRepo resource getting new versions when it shouldn't

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4477]
We have a few `gitRepo` resources defined as follows:

```
  - name: mlsuite-imaged-github
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: AIAScience/MLSuite
      branch: master
      buildOnCommit: false
```

These resources are `OUT` for some `runSh` jobs and act as `IN` for jobs further downstream. The intended effect is that our `runCI` job will build `master` branch, and on success publish a version and git state for the other jobs to use.

However, we are seeing these `gitRepo` resources being triggered even when we are not making commits to the `master` branch. Is there a bug or did we misunderstand something?
