### ISSUE TITLE
Composer missing for PHP 7.2.7, 7.2.6

### ISSUE THREAD

**Issue by TomasSjosten** [Shippable/support#4498]
### Issue
I receive the following error whenever I try to deploy new code and I cant seem to figure out why. Have tried other versions, but then the build fail on other parts that requires PHP 7.2+

```
composer install
rbenv: composer: command not found

The `composer' command exists in these PHP versions:
  5.6
  7.0
  7.1
  7.2
```

### Link to the build failure:
https://app.shippable.com/github/TomasSjosten/muddest/runs/1384/1/console

### shippable.yml
```
language: php

php:
    - 7.2.6
   
env:
  global:
    - TARGET=prod 
  
branches:
  only:
    - stage

build:
  ci:
    - pwd

before_install:
  - source /usr/local/rvm/scripts/rvm
  - rvm install ruby-2.3.0
  - rvm use 2.3.0
  - rvm use $SHIPPABLE_RUBY || rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && /usr/local/rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY
  - gem install capistrano
  - gem install bundler
  - gem env
  - npm install

install:
  - bundle install --gemfile="Gemfile"
  - ruby -v

before_script:
  - composer install
  - pwd
  - ls
  - bundle show --paths

  - node_modules/.bin/webpack --mode production --config webpack.config.js

after_script:
   - if [ "$BRANCH" == "stage" ]; then export TARGET="stage" ; fi
   - if [ "$BRANCH" == "demo" ]; then export TARGET="demo" ; fi
```
