### ISSUE TITLE
Nightly build on a different JDK

### ISSUE THREAD

**Issue by jodastephen** [Shippable/support#4507]
My goal is to create a single `shippable.yml` that does the following:

* on each commit, build on Java 8
* once each night, build on Java 10

After considerable effort, I have managed to get nightly builds working (feedback, it is a super-complex process when you don't already use assembly lines). I've also managed to get an environment variable if statement working that recognises it is a nightly build as opposed to a normal commit. However, I'm stumped on how to use two different JDK versions based on an environment variable. How can it be done? ie. how can I use an if statement to switch to a different JDK?

**Comment by trriplejay** [comment]
I'd recommend that you use `shipctl` to switch jdk version with a command like `shipctl jdk set oraclejdk10`.  You can see an example of this command being used in the `setup_jdk` section of the logs.

also, you might find it useful that there is an environment variable called `JOB_TRIGGERED_BY_NAME`.  When your job is triggered by your time resource, this variable will be that time resource's name. (otherwise it would typically be the name of the repo)

Here's what i imagine your shipctl command would need to look like:
```yml
  - if [ "$JOB_TRIGGERED_BY_NAME" == "time_resource_name" ] then; shipctl jdk set oraclejdk10; fi
```

let me know if you have any questions.

**Comment by jodastephen** [comment]
I added it to `pre_ci` but unfortunately this does not work:

`oraclejdk10 is not supported on this image`

`Linux 46aecd6dab58 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
drydock/u16reqproc:v6.7.4`

**Comment by jodastephen** [comment]
To get this to work I had to use `pre_ci_boot` to choose an image, Without that oraclejdk10 is not supported. Why?

This is the yml extract I used:

```
language: java

jdk:
  - oraclejdk8

build:
  pre_ci_boot:
    image_name: drydock/u16javall
    image_tag: latest
    pull: true
  ci:
    - java -version
    - mvn --version
    - shipctl jdk set oraclejdk10
    - java -version
    - mvn --version
    - shipctl jdk set oraclejdk8
    - java -version
    - mvn --version
 ```

Interestingly, the `shipctl jdk set` does change the `java` version, but not the one seen by `mvn`.
