### ISSUE TITLE
Adding timescaledb support

### ISSUE THREAD

**Issue by mustela** [Shippable/support#4515]
Im trying to run some tests on a timescaledb but I cant seem to find a way to enable the extension. 

``` 
env:
  global:
    - SHIPPABLE_POSTGRES_VERSION="10"
    - SHIPPABLE_POSTGRES_BINARY="/usr/lib/postgresql/$SHIPPABLE_POSTGRES_VERSION/bin/postgres"
    - SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf\" -c \"shared_preload_libraries = 'timescaledb'\""

language: ruby
rvm:
  - 2.4.4

# services:
#   - postgres

bundler_args: --jobs=8

before_install:
  # Add our PPA
  - sudo add-apt-repository ppa:timescale/timescaledb-ppa
  - sudo apt-get update --fix-missing

  # To install for PG 10.2+
  - sudo apt install timescaledb-postgresql-10
  - sudo apt-get -y install imagemagick ca-certificates curl libcurl3 libcurl3-gnutls openssl libssl-dev libssl-doc libssl1.0.0

  - cat /etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf
  # Restart PostgreSQL instance
  - sudo service postgresql restart

build:
  ci:
    - bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS
    - bundle exec rails db:create
    - bundle exec rails db:schema:load
    - bundle exec rake ci

after_script:
  - bundle exec rake db:drop
```
## Error 
```
Caused by:
PG::UnableToSend: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Tasks: TOP => db:schema:load
-- enable_extension("hstore")
   -> 0.0210s
-- enable_extension("pgcrypto")
   -> 0.0044s
-- enable_extension("plpgsql")
   -> 0.0013s
-- enable_extension("timescaledb")

``` 

Project Id: 5b5f3d39b161f70700b6af65
