### ISSUE TITLE
Use key value integration in CI job 

### ISSUE THREAD

**Issue by sanster23** [Shippable/support#4518]
Hi,

I am new to shippable and i have started writing a CI job 
I am not sure how to use Key-value integration in CI jobs : The official link to this is borken http://docs.shippable.com/platform/tutorial/integration/howto-use-key-value-in-runci/

This is the config that I have been using mostly hit and trial 
```
# Language setting http://docs.shippable.com/ci/languages/node/
# language: python


# branches:
#   only:
    # - master

# build:
#   ci:
#     - ls -la
#     - echo $COMMIT $BRANCH $REPOSITORY_NAME
#     - echo $SHIPPABLE_COMMIT_RANGE
#     - changes_to_folder=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`
#     - echo $changes_to_folder
#     - export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds "accessKey")
#     - export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds "secretKey")
#     - BASTION_HOST_USER=$(shipctl get_integration_resource_field bastion_host_user "user")
#     - LDAP_MANAGER_PASS=$(shipctl get_integration_resource_field ldap_creds_tf "manager_pass")
#     - LDAP_MASTER_HOST_USER=$(shipctl get_integration_resource_field ldap_master_host "user")
#     - echo $AWS_SECRET_ACCESS_KEY $AWS_ACCESS_KEY_ID $BASTION_HOST_USER $LDAP_MANAGER_PASS $LDAP_MASTER_HOST_USER
#     - changes="$(git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $NF}')"
#     - echo $changes
#     - git log

jobs:
  - name: temp_job
    type: runSh
    steps:
      - IN: aws_ec2_ldap_repo
        switch: off
      - IN: aws_creds
        switch: off
      - IN: aws_ec2_ldap_tf_ssh
        switch: off
      - IN: ldap_creds_tf
        switch: off
      - IN: bastion_host_user
        switch: off
      - IN: ldap_master_host
        switch: off
      - TASK:
          name: temp_job_script
          script:
            - pushd $(shipctl get_resource_state "aws_ec2_ldap_repo")
            - echo $COMMIT $BRANCH $REPOSITORY_NAME
            - echo $SHIPPABLE_COMMIT_RANGE
            - changes_to_folder=`git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`
            - echo $changes_to_folder
            - export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_creds "accessKey")
            - export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_creds "secretKey")
            - BASTION_HOST_USER=$(shipctl get_integration_resource_field bastion_host_user "user")
            - LDAP_MANAGER_PASS=$(shipctl get_integration_resource_field ldap_creds_tf "manager_pass")
            - LDAP_MASTER_HOST_USER=$(shipctl get_integration_resource_field ldap_master_host "user")
            - echo $AWS_SECRET_ACCESS_KEY $AWS_ACCESS_KEY_ID $BASTION_HOST_USER $LDAP_MANAGER_PASS $LDAP_MASTER_HOST_USER
            - changes="$(git diff --name-only $SHIPPABLE_COMMIT_RANGE | sort -u | awk 'BEGIN {FS="/"} {print $NF}')"
            - echo $changes
            - git log
            - terraform init
            - terraform destroy -auto-approve -var-file=terraform.tfvars
    on_success:
      script:
        - echo "Successfully destroyed the environment..."
    always:
      script:
        - echo "Going back ........"
        - popd
    flags:
      - aws_ec2
      - aws
      - terraform

  - name: ldap-devops_runCI
    type: runCI
    steps:
      - IN: aws_ec2_ldap_repo
        switch: off
      - IN: aws_ec2_ldap_tf_state
        switch: off
      - IN: aws_creds
        switch: off
      - IN: aws_ec2_ldap_tf_ssh
        switch: off
      - IN: open_vpn_creds_tf
        switch: off
      - IN: ldap_creds_tf
        switch: off
      - IN: temp_job
```

In the above shippable.yml the 
    - commented part runs on commit triggers but the variables dont get populated 
    - the runSh job doesnt get SHIPPABLE_COMMIT_RANGE variable values
    - the last runCI job will run with Ruby environment (which i did not tell it to) and fails saying that 
 
```bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

[!] There was an error parsing `Gemfile`: No such file or directory - /root/src/gitlab.com/velotio/ldap-devops/Gemfile. Bundler cannot continue.
```

What i need is a Ci job that triggers at commits or PR or PR merge so that a terraform script runs.

Please advise on this.

**Comment by a-murphy** [comment]
Is there a reason that you commented out the CI YML and added a runSh job?  The missing Gemfile error in the runCI job when the CI is commented out is because the default CI language is Ruby.  You need to set a language in your `shippable.yml` to specify another language.

`SHIPPABLE_COMMIT_RANGE` is not set in runSh jobs.  The default runSh environment variables are listed [here](http://docs.shippable.com/platform/workflow/job/runsh/#default-environment-variables).

It looks like both the runSh and runCI jobs above are meant to do the same thing, so I would recommend removing the runSh job from the YML, uncommenting the CI YML, and adding the following to the CI YML instead of the `IN` statements for the integration resources:

```YML
integrations:
  generic:
  - integrationName: <name of subscription integration used in aws_creds>
  - integrationName: <name of subscription integration used in aws_ec2_ldap_tf_ssh>
  - integrationName: <name of subscription integration used in open_vpn_creds_tf>
  - integrationName: <name of subscription integration used in ldap_creds_tf>
```

Integrations in CI are specified in the `integrations` section of the [CI YML](http://docs.shippable.com/ci/yml-structure/).  Integration resources are used in other job types.

**Comment by sanster23** [comment]
@a-murphy thanks for this `generic` part (i dont think it was mentioned in the docs explicitly), i had figured this out though and removed the runSh job and used only RunCI and build_ci jobs.

But I have another issue that all I want to do is run a Bash script on CI trigger for user config through terraform.
And as you mentioned that Ci uses an environment of the [ supported languages](http://docs.shippable.com/ci/supported-languages/)
I do not need an env for my bash script
So is there any way that only my `runSh` job gets triggered on the commits (when new files added to git of a certain file extension)

current shippable.yml
```
# # Language setting http://docs.shippable.com/ci/languages/node/
language: python


branches:
  only:
    - master

build:
  ci:
    - ./ldif_added_check.sh

jobs:
  - name: ldap-devops_runCI
    type: runCI
    steps:
      - IN: aws_ec2_ldap_repo
        switch: off
      - IN: aws_creds
        switch: off
      - IN: aws_ec2_ldap_tf_ssh
        switch: off
      - IN: ldap_creds_tf
        switch: off
      - IN: bastion_host_user
        switch: off
      - IN: ldap_master_host
        switch: off
      - IN: bastion_host_ip
        switch: off
      - IN: ldap_master_private_ip
        switch: off
```
