### ISSUE TITLE
Can't push to Docker Hub - denied

### ISSUE THREAD

**Issue by lag-linaro** [Shippable/support#4522]
Push to Docker Hub is failing.

Functionality to 'test Docker Registry credentials' is not provided on Shippable, it could either be the linking between Build and Integration or the set-up of the Integration itself. 

- Link to the build failure

https://app.shippable.com/github/lag-linaro/distribution-library-image/runs/30/1/console

- Error message seen

> denied: requested access to the resource is denied

- Copy of YAML file

````
runtime:
  nodePool:
    shippable_shared_aarch64

build:
  ci:
    - docker build -t docker.io/library/laglinaro/distribution-library-image:1 2.6
  on_success:
    - docker push docker.io/library/laglinaro/distribution-library-image:1

integrations:
  hub:
    - integrationName: docker-hub
      type: dockerRegistryLogin
````
