### ISSUE TITLE
Builds stuck on "Setup - Setting up dependency" 

### ISSUE THREAD

**Issue by johnzhao9** [Shippable/support#4526]
### Description of your issue:

This afternoon (2~3 PM CT?), builds started to get stuck on the "Setup" stage. Last line in the log is "Setting up dependency:"

Would appreciate any hints 

- Link to the build failure
Here is one of the build that got stuck for 1+ hour. I cancelled it:
https://app.shippable.com/github/PassageTech/shippable-ci/runs/1246/1/console

I then kicked off another one and it got stuck again:
https://app.shippable.com/github/PassageTech/shippable-ci/runs/1247/1/console

And again (this one is still running)
https://app.shippable.com/github/PassageTech/shippable-ci/runs/1248/1/console

Here is another in process one that's stuck for over an hour
https://app.shippable.com/github/PassageTech/Helper-Suite/runs/5170/1/console

- Scripts called from the yml (optional)
Please let me know if you need these

**Comment by trriplejay** [comment]
we're investigating.

**Comment by a-murphy** [comment]
We've identified that the error is related to some `gitRepo` resource inputs.

A workaround, until we get the problem fixed, is to add a `gitConfig` to the `pointer` of the `gitRepo` resource you are using as an input to the failing CI job.  The `gitConfig` option should be like this:
```
  - name: yourGitRepo
    type: gitRepo
    integration: bitbucket
    pointer:
      sourceName: yourOrg/yourRepo
      gitConfig:
        - user.name 'Shippable Build'
```

If you would prefer to set a different value for `user.name`, that will also work.  The current default for `user.name` in a CI job is `'Shippable Build'`.

And we'll let you know when this is fixed.
