### ISSUE TITLE
Missing dependency for: IN

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4529]
key-value-pair integration works on one repo and not on another.

'''
reqProc|runCI|_setUpDependencies, Missing dependency for: IN npm_private_auth
'''

**Comment by manishas** [comment]
Are the scopes on the integration set up to include both repos?

**Comment by BryanCrotaz** [comment]
Project Permissions: All projects

**Comment by BryanCrotaz** [comment]
and they're in the same assembly line

**Comment by a-murphy** [comment]
There doesn't appear to be a resource named `npm_private_auth` in your subscription.  There is a subscription integration by that name.  Since you are trying to use it in a runCI job, you may want to add that integration to the `integrations` section of your `shippable.yml` instead of as an `IN` resource.  Although I haven't identified which other project is using the same integration, I'm guessing it's in the `integrations` section and not an `IN` resource.

To add it to your CI yml, it should be in the `integrations` section as follows:
```YML
integrations:
  generic:
    - integrationName: npm_private_auth
```

Or you can set up an [integration resource](http://docs.shippable.com/platform/workflow/resource/integration/) to use as the `IN` resource.

**Comment by BryanCrotaz** [comment]
It's used successfully in ember-cli-template-editor_runCI

**Comment by BryanCrotaz** [comment]
Not Working:
```
  - name: sc-pp-frontend_runCI
    type: runCI
    steps:
      - IN: sc-pp-price-calculator_runCI
      - IN: pixelpipe-ember-data-core_runCI
      - IN: awsmqtt_runCI
      - IN: npm_private_auth
```

Working:
```
  - name: ember-cli-template-editor_runCI
    type: runCI
    steps:
      - IN: aws-shippable-auth
      - IN: npm_private_auth
```

**Comment by a-murphy** [comment]
The last successful runs in `ember-cli-template-editor_runCI` did not have `npm_private_auth` as an `IN` resource or in `integrations`; they weren't using it at all as far as I can tell.  And the most recent runs are failing with the same error as `sc-pp-frontend_runCI`.

You can either add an integration resource (with the same name as your subscription integration or a different name, but matching the `IN` steps on the runCI jobs) to your syncRepo or list the subscription integration in the `integrations` section instead of as an `IN` resource for both.

**Comment by BryanCrotaz** [comment]
you seem to have changed how this works recently?

**Comment by BryanCrotaz** [comment]
http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/
says how to set them up but not how to reference them in the yaml

**Comment by trriplejay** [comment]
CI has always supported an 'integrations' section, and key-value pair integrations were supported there when they were introduced.  We've also supported attaching integrations to resources for use in IN steps for quite awhile.

Usually the instructions on how to include the integration in yml are on the integration's page, since it can differ depending on the type of integration. So [this page](http://docs.shippable.com/platform/integration/key-value/) has info about how to use it.  However, I do see that there is currently a dead link on that page that we'll have to fix.

The instructions above for adding an 'integrations' section to your CI yml will work.  If you'd prefer to use the IN resource method, then you could just create the resource that it's looking for in your `resources` section in your syncRepo, and then your existing job configurations will work:
```yml
resources:
  - name: npm_private_auth
    type: integration
    integration: npm_private_auth
```
