### ISSUE TITLE
Not Able to get the AWS keys into CI

### ISSUE THREAD

**Issue by rahul2393** [Shippable/support#4531]
### Not able to access the AWS access_keys and secret_keys from integration (type amazonKeys):

- Scripts called from the yml (optional)
https://github.com/rahul2393/sample_pipelines_terraform/blob/master/shippable.yml

I have tried following the docs but not able to get values.

**Comment by trriplejay** [comment]
I think there are a few extra steps you'll need to take to get this working:

- add a runCI job definition to a "jobs" section of your yml. This definition should specify your `dr_aws` resource as an IN. it will look like this:
```yml
resources:
  - name: dr_aws
    type: integration
    integration: amazonKeys
jobs:
  - name: sample_pipelines_terraform_runCI #this has to be the name, not customizable
    type: runCI
    steps:
      - IN: dr_aws
```

- next, you have to add this project/branch as a `syncRepo`. Instructions for that are here: http://docs.shippable.com/platform/tutorial/workflow/add-assembly-line/

Once your resources are created, then your CI job should have access to the values that you're looking for.  Let me know if you have questions!

**Comment by rahul2393** [comment]
@trriplejay Here is my yaml
```
language: go

go:
  - 1.9

resources:
  - name: dr_aws
    type: integration
    integration: amazonKeys

build:
  ci:
    - echo $DR_AWS_INTEGRATION_ACCESSKEY
    - shipctl get_integration_resource_field dr_aws "accessKey"
    - echo $(shipctl get_integration_resource_field dr_aws "accessKey")
    - echo $(shipctl get_integration_resource_field dr_aws "secretKey")
    - export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field dr_aws "accessKey")
    - export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field dr_aws "secretKey")
    - export AWS_DEFAULT_REGION="ap-south-1"
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
#    - FILE_NAME=terraform_0.7.4_linux_amd64.zip
#    - sudo apt-get update && apt-get install wget jq unzip
#    - wget https://releases.hashicorp.com/terraform/0.7.4/$FILE_NAME
#    - unzip $FILE_NAME -d $(pwd)
#    - export PATH=$PATH:/build
#
#    - terraform init
#    - terraform plan
#    - terraform apply -auto-approve
```
Nothing gets echoed, So to access the variables do I need to create Jobs first?
