### ISSUE TITLE
Add AWS ECS Container Health Check support

### ISSUE THREAD

**Issue by cpoll** [Shippable/support#4534]
Amazon supports ECS container-level health checks as of March. See: https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-supports-container-health-checks-and-task-health-mana/

We would like to use this feature, but we use Shippable to create our AWS ECS Task Definitions (Shippable manifests), and there doesn't seem to be a way to do this.

To see the feature in AWS, go to ECS -> Task Definitions, click Create a new Task Definition, click Add container, and note the HEALTHCHECK heading. Other options in this interface are typically captured by Shippable's 'dockerOptions'

**Comment by trriplejay** [comment]
while not explicitly documented, we utilize a kind of "pass through" system on the [dockerOptions](http://docs.shippable.com/platform/workflow/resource/dockeroptions/#provider-specific-options_1) resource, where anything you put in the `versionTemplate` section directly will get passed as part of the container definitions. (we also have sections for adding to the taskDefinition directly, as well as the service definition).  So, a yml like below should work. Just add this as an IN to you deploy or manifest job:

```yml
- name: myOptions
  type: dockerOptions
  versionTemplate:
    healthCheck:
      command:
        - 'CMD-SHELL'
        - 'curl -f http://localhost/ || exit 1'
      interval: 60
      timeout: 20
      startPeriod: 15
      retries: 5
```

let me know if you have questions or run into any other issues.

**Comment by cpoll** [comment]
Thanks, I'll try it soon and close this issue.

Incidentally, does this apply to any other resources? We're also looking for a way to create DAEMON services in ECS (https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-ecs-adds-daemon-scheduling/). This is a bit muddier, because the `replicas` and `deploy` resources don't entirely match up with ECS Services... (Let me know if I should just open a new issue for this)

**Comment by trriplejay** [comment]
actually you can set a `schedulingStrategy` also by using the dockerOptions resource.  Since that modifies the service definition (not the container definition) you'd specify it like this:
```yml
- name: myOptions
  type: dockerOptions
  versionTemplate:
    service:
      schedulingStrategy: "DAEMON"
        
```
