### ISSUE TITLE
gitRepo does not trigger anymore

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4537]
My gitRepo georep_start [(link)](https://app.shippable.com/subs/bitbucket/ArnaudBotella/resources/georep_start/versions) does not get triggered anymore but the ciRepo still works [(link)](https://app.shippable.com/subs/bitbucket/ArnaudBotella/resources/georep_ciRepo/versions). I do not understand why. I did not change anything in the yml files.

Thanks for your help

**Comment by ankul-shippable** [comment]
@BotellaA I see that a version for ciRepo was created for pull request. For gitRepo resource(i.e. `georep_start`) no new version was created because it ignores pull request webhooks by default. To create versions for gitRepo resources on pull requests, add the `buildOnPullRequest` flag:
```
resources:
  - name: georep_start
    type: gitRepo
    integration:  <integration_name>
    versionTemplate:
      sourceName: <source_name>
      buildOnPullRequest: true
```

Please let us know if you need any help with configuring your pipelines.
