### ISSUE TITLE
Build against multiple nodePools?

### ISSUE THREAD

**Issue by jmreicha** [Shippable/support#4549]
Is it possible to specify multiple `nodePool`s in the shippable.yml configuration file to build against different architectures?  If that's not possible is there a good way to do builds against different pools?

**Comment by ric03uec** [comment]
@jmreicha you can use multiple node pools in a couple of ways right now. 

## using branches in runCI jobs
- this will require you to add different branches in the project which each branch having
the required `nodePool` value that you want. e.g.

- branch 1 shippable.yml
```
...
runtime:
    nodePool: aarch64_ubuntu16_pool
...

```
- branch 2 shippable.yml
```
...
runtime:
    nodePool: x86_64_ubuntu16_pool
...

```
- **Pros**
  - this is the fastest way to get your existing yml to work on multiple node pools
  - you'll be able to use report parsers
  - matrix buidls will work as-is 
- **Cons**
  - having to manage multiple branches for different node pool types


## using multiple runSH jobs

multiple [runSH](http://docs.shippable.com/platform/workflow/job/runsh/) jobs can be used to run builds on different platforms by defining different `runtime` options for each job.

The workflow will look something like this

![untitled diagram](https://user-images.githubusercontent.com/1110988/45324923-62fc5200-b504-11e8-9264-bf080842e5d7.jpg)

- **Pros**
  - single commit on one branch can trigger builds on as many platforms as you need
- **Cons**
  - report parsers are currently unavailable on `runSH` jobs
  - matrix generation is unavailable on `runSH` jobs

We've added a feature request in our pipeline to treat `nodePool` as one of the inputs
to generate the job matrix. This will ensure that a single yml can be used to trigger
builds on multiple nodepools. 

In the meanwhile, one of the two options should work for you. I'd be happy to get on a
call if you need more help in configuring these.

**Comment by jmreicha** [comment]
@ric03uec Thanks, that makes sense.  Is there any way to reuse scripts/build logic across different jobs?

**Comment by Riturajcse** [comment]
Hi @jmreicha, we do support reusing of `scripts` across different jobs using `templates` you can check more about this in our docs [here](http://docs.shippable.com/platform/workflow/job/runsh/#yml-templates).

**Comment by jmreicha** [comment]
@Riturajcse Awesome thank you!

**Comment by jmreicha** [comment]
Sorry, one last piece of the puzzle to figure out.  Currently my job type is listed as `runCI` and I'm not sure how to change that type to `runSh` in my job settings?

![image](https://user-images.githubusercontent.com/1039098/45377418-6ac50080-b5af-11e8-952e-957d2e73a52e.png)

**Comment by ric03uec** [comment]
the project yml seems be mostly set up correctly. you need a few more things to get this working
1. **enable rSync**: since you're now defining your assembly line configuration (as opposed to just CI configuration) in the shippable.yml file, you'll need to enable a [rSync](http://docs.shippable.com/platform/workflow/job/rsync/) job for it. here's how to do it
    - navigate to the the `+` icon on top right toolbar of subscriptions screen which says `Enable CI project or Add Assembly Line`
    - search for `freeipa-container`
    - click the `+` icon in the column `Add Assembly Line`
    - disable the CI by turning off the `Enable CI` button on the same screen

1. **configure yml**: Once the first step is done, you'll see the assembly line configuration on the subscription SPOG with the two jobs that you've already defined. Since both the jobs need the project repo as an `IN`put, add a [gitRepo](http://docs.shippable.com/platform/workflow/resource/gitrepo/) resource 

```
resources:
    - name: freeipa-container-gitRepo // or anything else
      type:   gitRepo 
      integration: //your git integration name
      versionTemplate:
          sourceName: jmreicha/freeipa-container
          branch: master

jobs:
    - name: job1
      type: runSH
      steps:
          - IN: freeipa-container-gitRepo
       ## --- rest of job config --- ##


    - name: job2
      type: runSH
      steps:
          - IN: freeipa-container-gitRepo
       ## --- rest of job config --- ##
```
