### ISSUE TITLE
Deployment Key and PR Builds Security?

### ISSUE THREAD

**Issue by dandesousa** [Shippable/support#4559]
### Description of your issue:

I'm attempting to setup a configuration where non-PR builds into master automatically triggered an update to the docs by pushing to the gh-pages branch.

However, it seems like in order to do this, I would need to add the deployment key to my project. I've verified that the same key is used during PR builds, which means that in a public repo anyone can modify the yml (bypassing any configuration for skipping pull requests) and shippable will run that and push the changes unverified into production.

Is there any way to do what I'm trying to accomplish. Restated, I would like:

- A push to a master branch automatically pushes some code back to the gh-pages repo
- A pull request into the master branch fails if it attempts to merge into the repo (ideally enforced through a secondary key)

**Comment by dandesousa** [comment]
The simplest possible way I can think of to represent the sort of thing I'm trying to do:


```
language: python

branches:
    only:
        - master

python:
    - 3.6

build:
    ci:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - make html
    on_success:
        - git remote set-url origin git@github.com:$REPO_FULL_NAME.git
        - git config --get remote.origin.url
        - if [ "$IS_PULL_REQUEST" == false ]; then make gh-pages; fi
```
