### ISSUE TITLE
Job got started by object with switch: off

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4569]
Hello, I have a job, which INs looks like this:
```
steps:
  - IN: k10-deploy
  - IN: k10-params
  - IN: k10_repo
    switch: 'off'
  - IN: dashboardbff-img
    switch: 'off'
```
But job is got triggered by k10_repo

![image](https://user-images.githubusercontent.com/1631779/45896029-bd5ca480-bd87-11e8-9db4-96b18576d1ce.png)
