### ISSUE TITLE
Timeline for support for Java 11

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4573]
As you might be aware, Java 11 [has been released](https://www.infoq.com/news/2018/09/java11-released). We are currently on Java 10, and given Oracle's new support model for Java, Java 10 immediately became obsolete as soon as Java 11 came out.

Do you have plans of adding Java 11 to the list of supported Java versions? By when we can expect this to happen? I ask because we will have to plan our Java 11 upgrade accordingly.

**Comment by rageshkrishna** [comment]
Yes, Java 11 will be available in the v6.10.4 release which is currently scheduled for the last week of October.

**Comment by manish-in-java** [comment]
Thanks @rageshkrishna.

**Comment by nealeu** [comment]
@manish-in-java If you want to get going now, you can use the drydock/u16javall:master with openjdk11.

```
jdk
  - openjdk11

build:
  pre_ci_boot:
    image_name: drydock/u16javall
    image_tag: master
    pull: true
```
