### ISSUE TITLE
Deploy to Elastic Beanstalk with dotnet eb

### ISSUE THREAD

**Issue by completer** [Shippable/support#4596]
Hi there, I'm experimenting with dotnet core builds.

We can deploy locally without Shippable like this:

    dotnet eb deploy-environment -app datahub -env jncc-datahub-test --region eu-west-1

So first we would need to install the AWS tool:

    dotnet tool install -g Amazon.ElasticBeanstalk.Tools

which appears to install fine. Demonstration shippable.yml: 
https://github.com/jncc/datahub/blob/master/shippable.yml

I'm not sure what to do next though. Our existing Node apps deploy like this:

```
integrations:
  deploy:
    - integrationName: "aws-jncc-prod-subscription-integration"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: myapp
      env_name: myapp-$BRANCH 
      region: "eu-west-1"
```

Not really sure I understand 'integrations'. Any help gladly received.
