### ISSUE TITLE
My build is very slow, please advice me how to speed it up

### ISSUE THREAD

**Issue by javadev** [Shippable/support#4600]
### Description of your issue:
Dear support,

Please advice me how to improve performance for my bild.

Sincerely, Valentyn

- Link to the build failure
https://app.shippable.com/github/javadev/underscore-java/runs/1395/1/console

- Scripts called from the yml (optional)

language: java

jdk:
  - oraclejdk8

script:
  - mvn clean test jacoco:report

notifications:
   email: false

**Comment by trriplejay** [comment]
Here are a few general recommendations based on what I see in your project.

1. First, I'd recommend updating your yml to use Shippable's newer format.  It should look like this:
```yml
language: java
jdk:
  - oraclejdk8
build:
  ci:
    - mvn install -DskipTests=true
    - mvn clean test jacoco:report

integrations:                               
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_cancel: never
      on_pull_request: never
```
2. I can see that your builds are running on a very old build image.  This image is starting up both postgres and mysql, and then later stopping them.  If you're not using either of these services, then some time is wasted at that step.  If you update your subscription's default node pool to use a more recent version, these steps will no longer be added.  I'd recommend trying `v5.10.4` since it has java 8 as the default, and won't be as big of a change as switching all the way to the latest version would be.  Instructions for changing this setting are here: http://docs.shippable.com/platform/tutorial/runtime/manage-node-pools/#updating-node-pools  You can see there is a "runtime version" dropdown when editing a node pool. Change this to `v5.10.4`
3. enabling caching.  One of the pieces of your build that is taking extra time is the `mvn install` step.  This is downloading your dependencies every time your build runs.  If you enable caching, this download should speed up significantly.  Information on caching can be found here: http://docs.shippable.com/ci/caching/

If you have additional questions about any of this, don't hesitate to ask! We'd be happy to help you get these changes made to improve your performance.
