### ISSUE TITLE
The ability to set queued jobs as low priority

### ISSUE THREAD

**Issue by UndeadTwo** [Shippable/support#4633]
It would be nice to be able to queue several jobs resulting from generally trivial things like master merges as low priority, which would result in them yielding their spot in the queue to higher priority jobs and running when no higher priority jobs exist in the queue.

**Comment by ankul-shippable** [comment]
@UndeadTwo we do support assigning priorities to jobs. You need to set `priority` in your runCI/runSh job definition.

#### For runCI jobs:
```
jobs:
  - name: <name of the runCI job>
    type: runCI
    priority: <[0-10000]>
    steps:
      - IN: <resource>
      - IN: <job>
```

#### For runSh jobs:
```
jobs:
  - name: <job name>
    type: runSh
    priority: <[0-10000]>
    steps:
      - IN: <resource>
      - IN: <job>
      - TASK:
          name: <task name>
          script:
            - <any shell command>
```

`priority` may be set to any value from 0 to 10000 inclusive, with 0 being the highest priority and 10000 being the lowest priority. Queued jobs with higher priority will run before the queued jobs with lower priority. Default priority for all the jobs is 9999. This will not stop any processing jobs and will prioritize only queued jobs in your pipeline

Please take a look at our docs for [runCI](http://docs.shippable.com/platform/workflow/job/runci/#yml-definition) and [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) jobs for more information.
