### ISSUE TITLE
Could runCI starts after runSh?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4641]
I would like to have my runSh script always run before my runCI. Currently, the runCI starts, then the runSh starts and then another runCI starts. So, the runCI is launch twice but I would like to run it once after the runSh.

```
jobs:
  - name: genepi_static
    type: runSh
    steps:
      - IN: genepi_start
        showBuildStatus: true
      - TASK:
          ...
      - OUT: genepi_ciRepo
        replicate: genepi_start

  - name: genepi_runCI
    type: runCI
    dependencyMode: strict
```

I tried different dependencyMode but nothing changes.

Thanks for your help.
