### ISSUE TITLE
Supporting language in matrix

### ISSUE THREAD

**Issue by junaruga** [Shippable/support#4643]
### Description of your issue:

Thank you for providing Shippable service to us.
This is a request for feature.
I would like to use `language` syntax in `matrix` like this.

```
language: none
matrix:
  include:
    - nodePool: shippable_shared_aarch64
      env: ARCH="aarch64"
    - nodePool: shippable_shared_aarch32
      env: ARCH="aarch32"
    - nodePool: shippable_shared_aarch64
      language: python
      python: 3.6
      env: ARCH="aarch64"
      build:
        pre_ci:
          - python --version
```

It seems `language` in `matrix` is not recognized right now. "Lang Version" is empty in the page when setting it in `matrix`.

![shippable-matrix-language](https://user-images.githubusercontent.com/121989/48306236-4649be00-e537-11e8-8610-72c4e4dc00d1.png)

Also it seems that `build/pre_ci` in `matrix` is not recognized. I want the feature too.

#### References

- Link to the build
  [1] https://app.shippable.com/github/junaruga/ci-multi-arch-test/runs/46/summary/console
- Scripts called from the yml (optional)
  https://github.com/junaruga/ci-multi-arch-test/blob/feature/shippable-ruby-case/shippable.yml

#### Used cases in Travis CI

I would share actual use case that `language` in `matrix` is used for Travis CI.

- https://github.com/ruby/ruby/blob/trunk/.travis.yml#L237
- https://github.com/ruby/openssl/blob/master/.travis.yml#L29
- https://github.com/trinityrnaseq/trinityrnaseq/blob/master/.travis.yml
