### ISSUE TITLE
Passing Key-Value pair into ECS docker deployment

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#4654]
I am looking for a way to pass the key-value pairs that I have assigned within the subscription integration into a docker image as environment variables which is deployed to ECS using a managed deploy job.

I have a manifest and a managed deploy job. I have tried adding the Key-Value pair integration as an IN resource to the manifest and the deploy process but neither of these worked. The only solution I was able to find was to use a params resource and set that as an IN to the deploy job.

I like the fact that the Key-Value pair is easily maintained through the UI and would rather use that than having to change params in the shippable.yml. Is there a way to achieve what I am trying to do or is the params resource the only solution ?

Cheers

**Comment by a-murphy** [comment]
Although using the `params` resource is recommended in this case, it would be possible to set environment variables from a key-value pair integration through a `dockerOptions` resource.  A `dockerOptions` resource with `environment` (an array of objects with `name` and `value`) in the `versionTemplate` will override other environment settings and those variables' values can be stored in the key-value pair integration through [templating the resource](http://docs.shippable.com/platform/tutorial/workflow/crud-resource/#templating-resources).

For a key-value integration named `myIntegration` with key `myKey` and value `myValue`:
```YML
resources:
  - name: myIntegration
    type: integration
    integration: myIntegration
  
  - name: myDockerOptions
    type: dockerOptions
    versionTemplate:
      environment:
        - name: myKey
          value: ${myKey}

jobs:
  - name: myDeployJob
    type: deploy
    steps:
      - IN: myCluster
      - IN: myManifest
      - IN: myIntegration
      - IN: myDockerOptions
```
