### ISSUE TITLE
how to not run post_ci step on PR

### ISSUE THREAD

**Issue by grandvizier** [Shippable/support#4658]
The build script starts off with:
```
branches:
  only:
    - master
``` 
and the build has the following steps:
```
build:
  cache: 
  cache_dir_list:
  ci:
  post_ci:
  on_success:
```
I think it's good that the `build.ci` runs when a pull request is created/updated, however I don't want the `post_ci` or `on_success` steps to run. They should only execute in the master branch commits. _(which is what I expected from the `branches.only` option
