### ISSUE TITLE
Problem accessing exposed ports from a docker container in runSh job

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4687]
Build id: builds/5c1bea58596ae107008bdd4a/console

### What I want:
- build and run a docker image that listens on a specified port
- test the port in runSh test script

### What I get

application in the docker logs
```
...
MainProcess:MainThread:2018-12-20 19:17:35,292 WARN  [server] Rest server started at [0.0.0.0:8280].
MainProcess:MainThread:2018-12-20 19:17:35,292 WARN  [server] Rest server waiting for connections...
...
```

main logs
```
...
Docker inspect
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS                    NAMES
094160d05895        te/shippable                 "python main.py --..."   30 seconds ago       Up 30 seconds       0.0.0.0:9342->8280/tcp   1545333454
365f23362bea        drydock/u14all:v6.9.4        "/var/lib/shippabl..."   About a minute ago   Up About a minute                            reqExec.5c1bea58023fb10700e65964.0
ba5c0171d5a7        drydock/u14reqproc:v6.12.4   "/bin/sh -c $IMAGE..."   About an hour ago    Up 23 minutes                                reqProc-5c1bd64726342b070055ecb8
Docker ports
8280/tcp -> 0.0.0.0:9342
...
 Failed to connect to 127.0.0.1 port 9342: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 9342: Connection refused
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
Connection refused
* Failed to connect to 127.0.0.1 port 8280: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 8280: Connection refused
```

#### .shippable.yml
```
...
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: v6.10.4
    pull: true
    options: "-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"
...
  - name: te_basic_integration_runSh
    type: runSh
    steps:
      - IN: te_Repo
      - TASK:
        - script: cd $TE_REPO_PATH/gitRepo/ci && ./integration_test_basic.sh
```
#### test script
```
...
docker build -t te/shippable .
...
docker run --name "$TEST_IMG" -td --rm -p $TE_PORT:8280 -v `pwd`/src:/te te/shippable 
sleep 30
...
curl -v http://127.0.0.1:$TE_PORT/v1/online || true
curl -v http://127.0.0.1:8280/v1/online || true
...
```

### What I tried

- `--host=net` in .shippable.yml 
- `- container: false` in runSh
- `--host=net` in the docker run script
- quite a few other things I do not remember now.

**Comment by trriplejay** [comment]
i see you mentioned `--host=net`, but the correct option should be `--network=host` or `-net=host`, was that a typo, or can you try that option? i think both the pre_ci_boot as well as your docker run inside your script will need to specify it.

**Comment by vidiecan** [comment]
@trriplejay a typo. However, retrying with your suggestion

**Comment by vidiecan** [comment]
@trriplejay did **not** help (docker ports output is now empty which makes sense)

**Comment by rageshkrishna** [comment]
I think the problem is here:

```yaml
  - TASK:
      - runtime:
          - container: false
```

The [syntax for runtime](http://docs.shippable.com/platform/workflow/job/runsh/) is wrong. As a result, the `container: false` setting is being ignored. Can you change it to the following and see if it helps:

```yaml
  - TASK:
      runtime:
        container: false
```

**Comment by trriplejay** [comment]
also wanted to mention that I made a mistake earlier. pre_ci_boot is configuring the runCI script, not the runSh job. The equivalent setting on runSh is:
```yml
- TASK:
    runtime:
      options:
        options: --network=host
```
(yes, that's two levels of "options")

so you might want to take that out of your pre_ci_boot, and add it to the runtime section of your runSh task.  

Correctly utilizing "container: false" should work too, as an alternative to this setting in the options.

**Comment by vidiecan** [comment]
@trriplejay works! thanks.

### What works

.shippable.yml
```
...
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: v6.10.4
    pull: true
    options: "-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"
...
#### JOBS CONFIG (GLOBAL ACROSS SUBSCRIPTION)

jobs:
  - name: te_basic_integration_runSh
    type: runSh
    steps:
      - IN: te_Repo
      - TASK:
          runtime:
            options:
              options: --network=host
          script:
            - cd $TE_REPO_PATH/gitRepo/ci && ./integration_test_basic.sh
```

integration_test_basic.sh
```
...
docker build -t te/shippable .
# have to use original port with `--network=host`
export TE_PORT=8280
docker run --name "$TEST_IMG" --network=host -td --rm -p $TE_PORT:8280 -v `pwd`/src:/te te/shippable 
...
curl -v http://127.0.0.1:$TE_PORT/v1/online
```
