### ISSUE TITLE
PR is being deployed even with "$IS_PULL_REQUEST" == false

### ISSUE THREAD

**Issue by joshuaohana** [Shippable/support#4690]
For certain branches, I do not want PRs to cause a deployment to AWS. As such, I have the below

```
build:
  ci:
    - if [ "$BRANCH" == "develop" ] ; then env=dev npm run build; fi
    - if [ "$BRANCH" == "qa" ] && [ "$IS_PULL_REQUEST" == false ] ; then env=qa npm run build; fi
    - if [ "$BRANCH" == "master" ] && [ "$IS_PULL_REQUEST" == false ] ; then env=prod npm run build; fi
```

My expectation is that this would cause builds and deployments for PRs only into develop, and would ignore PRs into qa or master. That's not happening, and instead PRs trigger builds and deployments on all 3 environments.

The integration yml is
```
integrations:
  deploy:
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-dev
      region: us-east-1    
      branches:
        only:
          - develop
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-qa
      region: us-east-1    
      branches:
        only:
          - qa
    - integrationName: "myapp.api-deploy"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name:  myapp.api
      env_name: myapp-api-prod
      region: us-east-1
      steps:
        - IN: myapp.api-deploy
          switch: off
      branches:
        only:
          - master
```

How can I make it to not trigger/build on PRs?
