### ISSUE TITLE
Higher build timeout limit

### ISSUE THREAD

**Issue by sscarduzio** [Shippable/support#4699]
### Description of your issue:
Our builds are naturally long processes, as we keep supporting multiple versions of the software. I wonder if there is a way to raise the build timeout above the hour. Or what is an equivalent work around to trigger maybe two builds i.e. one at midnight and the other at 1AM.

Current settings:

$ cat shippable.jobs.yml
```yml
jobs:
  - name: xxxxxx_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
```

$ cat shippable.resources.yml
```yml
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval: "0 */12 * * *" # every 12h
```

$ cat shippable.yml

```yml
language: node_js

node_js:
  - "6.12.2"

build:
  ci:
    - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"
    - nvm install 8.11.4
    - nvm alias default 8.11.4
    - bash -xe ci/ci-deploy.sh

branches:
  only:
    - master
```

**Comment by a-murphy** [comment]
Paid subscriptions (those with more than one parallel build or paying for one larger build node or API access) have a two hour maximum timeout instead of a one hour timeout.  Information on further configuring timeouts is available [here](http://docs.shippable.com/ci/custom-timeouts/).  Each item in a matrix will be allowed the configured time starting from when the status is set to "processing."

If you would prefer to trigger your project more than once, you can set up a second `time` resource input and the `JOB_TRIGGERED_BY_NAME` environment variable present in jobs triggered though an Assembly Line will be set to the name of the resource that triggered that particular run.  You can then use `JOB_TRIGGERED_BY_NAME` in your scripts to take different actions in each run.

**Comment by rageshkrishna** [comment]
@sscarduzio I hope your question about the timeout has been answered.

I was just looking at your YML and wondering why you're setting `node_js: 6.12.2` and then proceeding to manually install 8.11.4 during your build. Perhaps you can save a little time by moving a newer machine image that has node 8.x? I believe [machine image v6.8.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v684/#nodejs) has node version 8.11.4.

**Comment by sscarduzio** [comment]
@rageshkrishna thanks for the suggestion. The thing is that we anyway will download a few node versions during the build process in order to build our plugin against different versions of the main project we extend.

**Comment by rageshkrishna** [comment]
That makes sense. Can I close this issue now that your question about the build timeouts has been answered?

**Comment by sscarduzio** [comment]
So basically if I do like this it should work?

```yml
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval:  "0 1 * * *"

  - name: nightly-trigger
     type: time
     seed:
     interval: "0 2 * * *"
```

Or should I duplicate also the job and call it nightly-trigger2?

**Comment by rageshkrishna** [comment]
Resource names need to be unique, so yes you would need `nightly-trigger` and `nightly-trigger2`. You don't really need to trigger them at different times. They can both trigger at the same time and your jobs will get queued for execution. They will start running as soon as a node frees up. Your job can then look at `JOB_TRIGGERED_BY_NAME` to run a subset of tests.

But I think this can become confusing. Because these are basically the same job running twice, you will not be able to rely on the "latest status" that shows on your dashboard. If night-trigger resulted in a failed build, and nightly-trigger2 was successful, your dashboard is going to tell you everything is green. This is probably not what you are looking for.

I think a better solution would be to create a matrix build with different environment variables. For example, with the following YML, you would get two builds in your matrix (one with `TEST=test_group_1` and the other with `TEST=test_group_2`. Your script can then decide what to do. As @a-murphy said above, each job in the matrix gets the full timeout period from the point it goes in to the "processing" state.

```
language: node_js

node_js:
  - "6.12.2"

env:
  - TEST: test_group_1
  - TEST: test_group_2

build:
  ci:
    - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"
    - nvm install 8.11.4
    - nvm alias default 8.11.4
    - bash -xe ci/ci-deploy.sh

branches:
  only:
    - master
```

**Comment by sscarduzio** [comment]
Really glad I asked you, I really like the build matrix approach!

I will go ahead and just add the `env` array in my shippable.yml with two lines as suggested, and in the future also take care of splitting the work meaningfully between the two sub-builds.

I understand that using a matrix approach with two sub-builds will decrement the number of available monthly builds of two, right?

**Comment by rageshkrishna** [comment]
Yes, if it is a private repository it will count towards your monthly quota on a free plan.

Maybe you should upgrade to a paid plan. It will solve your timeouts with no effort and you get unlimited builds. :)

**Comment by sscarduzio** [comment]
Hey I have another question.
So I initially omitted it (sorry, stupid decision I don't remember why), but at the current shippable.yml  **already had** the env array, used for passing various secrets to the build script.

(complete version of shippable.yml)
```yml
language: node_js

node_js:
  - "6.12.2"

env:
  - secure: cPbw4MGzGE...YCoSOek1JVCuBnua+9B87VBPDQ==

build:
  ci:
    - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"
    - nvm install 8.11.4
    - nvm alias default 8.11.4
    - bash -xe ci/ci-deploy.sh

branches:
  only:
    - master
```

So the question is: in the case I want to pass an extra  "stage" variable i.e. "STAGE="unit_tests" to the *same* task (in addition to "secrets" env var), Is there a way to pass multiple env vars for each task?

**Comment by ankul-shippable** [comment]
Yes, you can pass them like this:

```
env:
  global:
    - secure: cPbw4MGzGE...YCoSOek1JVCuBnua+9B87VBPDQ==
  matrix:
    - foo: bar 
    - foo: fizz
```
