### ISSUE TITLE
java.security.InvalidAlgorithmParameterException

### ISSUE THREAD

**Issue by remik-dworczak** [Shippable/support#4704]
Hi All,

I've been trying to build an android  skeleton project and I'm geeting the following exception:
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

https://app.shippable.com/github/remik-dworczak/two-phones/runs/22/1/console

shippable file:

language: java
jdk:
    - oraclejdk8
build:
  ci:
  - source /etc/drydock/.env
install:
    - sudo apt-get install -u lib32stdc++6 lib32z1
    - ./gradlew clean assemble
before_script:
    # - mkdir -p shippable/testresults
script:
    - ./gradlew check
after_script:
   # - cp -r build/test-results/* shippable/testresults/
notifications:
    email:
        recipients:

**Comment by trriplejay** [comment]
Hello, I think you can take a couple steps to get around this:
- change your node pool runtime to 6.8.4.  From your subscription dashboard, click settings -> node pools -> "edit" next to your default node pool -> select 6.8.4 from the "runtime version" dropdown box
- add this line to the top of your CI yml: `sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure`

We're working on updating our java image to make this unnecessary, but for now this is the best workaround. 

I also noticed that your yml seems to be a combination of our old and new formatting.  Here's a cleaned up version you can use:
```yml
language: java
jdk:
  - oraclejdk8
build:
  ci:
    - sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
    - sudo apt-get install -u lib32stdc++6 lib32z1
    - ./gradlew clean assemble
```
"install", "script", and "after_script" are older tags that you can get rid of. I also think the `- source /etc/drydock/.env` line should be unnecessary, and currently is not being executed in your build anyway, due to the mix of yml formats.

Let me know if you have any questions.
