### ISSUE TITLE
Manual change to OUT resource does not trigger an update

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4711]
Project: `te` (548f3ff2d46935d5fbc03c6e ) has in .shippable in master branch this:
```
resources:
  - name: te_dp_fakturabank_success_flag
    type: params
    versionTemplate:
      params:
        tag: "none"

jobs:
  - name: te_runCI
    type: runCI
    steps:
      - OUT: te_dp_fakturabank_success_flag
  ...
```
on a different branch it has in .shippable:
```
  on_success:
    - if [[ "x$TRIGGEROUT" == "xtrue" ]]; then echo "updating te_dp_fakturabank_success_flag" && shipctl put_resource_state te_dp_fakturabank_success_flag tag "$COMMIT"; fi
...
jobs:
  - name: EXPECTED_TO_RUN
    type: runSh
    steps:
      - IN: te_dp_fakturabank_success_flag
      - IN: XXX
...
```

The flag is not updated even when the echo was executed. Therefore, the EXPECTED_TO_RUN is not run at all.
