### ISSUE TITLE
runSh job runs all by itself without being triggered

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4712]
e.g.
https://app.shippable.com/bitbucket/silvercurve/jobs/sc-pp-auth_deploy_to_DEV/builds/5c45e83ec094790700ac1c4f/console

Ran at the same time as a different repo was updated (sc-pp-frontend) which is not in the assembly line config as an IN to the runSh job.

This job has run multiple times today without being triggered by its IN jobs. How should I track this down?

Feature request - in the job console output, show the stack of what caused this build to run

**Comment by a-murphy** [comment]
The linked job was triggered by the gitRepo input, as shown in the job history (click the job name in the breadcrumb at the top to go to this page from the linked page).  It appears that the gitRepo was most likely updated by a webhook, but is also configured as an output of another job that did not run at that time.  If you would like to turn off webhooks on that gitRepo so that it is only updated by the job, you can add `buildOnCommit: false` to the resource in your YML file as described in the [gitRepo documentation](http://docs.shippable.com/platform/workflow/resource/gitrepo/).

**Comment by BryanCrotaz** [comment]
The yaml for the deploy job is:
```
- name: sc-pp-auth_deploy_to_DEV
    type: runSh
    steps:
      - IN: sc-pp-auth-master-pass-version
      - IN: sc-pp-auth-repo-master
        switch: off // my understanding is that the repo commits shouldn't trigger this job
      - IN: aws-shippable-auth
      - IN: npm_private_auth
      - TASK:
        - script stuff
```
