### ISSUE TITLE
Build matrix 4x2

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4713]
How would it be possible to run a matrix with multiple custom env variables?
E.g. I want to builddifferent CMake versions for two with different ubuntu versions. This would be to build docker images.

I want to build e.g.
- CMake 1.0.0 for
  - ubuntu 14
  - ubuntu 16
- CMake 2.0.0 for
  - ubuntu 14
  - ubuntu 16

So this would be 4 builds. Currently I have this setup, but only runs two instances (1.2.3, 2.0.0)

```yml
language: none

env:
  matrix:
    - VERSION: "1.2.3"
      UBUNTU_VERSION: 2
    - VERSION: "2.0.0"
      UBUNTU_VERSION: 3

build:
  ci:
    - echo "Building CMake ${VERSION} for Ubuntu ${UBUNTU_VERSION}"
```

**Comment by a-murphy** [comment]
It sounds like you are trying to run four jobs, one with each combination of `VERSION` and `UBUNTU_VERSION`.  Please let me know if this is not correct.

In the YML section you have included, you've specified that it should only run `VERSION` `1.2.3` with `UBUNTU_VERSION` `2` and `VERSION` `2.0.0` with `UBUNTU_VERSION` `3`.  You can expand this to include the other versions:
```YML
language: none

env:
  matrix:
    - VERSION: "1.2.3"
      UBUNTU_VERSION: 2
    - VERSION: "1.2.3"
      UBUNTU_VERSION: 3
    - VERSION: "2.0.0"
      UBUNTU_VERSION: 2
    - VERSION: "2.0.0"
      UBUNTU_VERSION: 3

build:
  ci:
    - echo "Building CMake ${VERSION} for Ubuntu ${UBUNTU_VERSION}"
```

**Comment by vidavidorra** [comment]
I was afraid it would come to that. I don't particularly like the repetition that this requires. E.g. I have to specify the same version twice in this case, once for `UBUNTU_VERSION=2` and once for `UBUNTU_VERSION=3`. If there is no other way to specify the matrix, which there probably isn't based on your answer, I'd just have to go with this.
@a-murphy Thanks for your response and example. Is there is no easy other way to specify the matrix without the repetition of the `VERSION`? If not, I'll close this ticket.

**Comment by a-murphy** [comment]
There is a shorter option, since you are only specifying variables in your matrix you can put them on the same line.  You'll still have to list the same combinations though.  The shorter option would be:
```YML
language: none

env:
  - VERSION="1.2.3" UBUNTU_VERSION=2
  - VERSION="1.2.3" UBUNTU_VERSION=3
  - VERSION="2.0.0" UBUNTU_VERSION=2
  - VERSION="2.0.0" UBUNTU_VERSION=3

build:
  ci:
    - echo "Building CMake ${VERSION} for Ubuntu ${UBUNTU_VERSION}"
```
