### ISSUE TITLE
trigger gcloud commands after CI job

### ISSUE THREAD

**Issue by vedant-khandelwal** [Shippable/support#4716]
Hi,

How can I trigger a runSh job that uses cliConfig for gcloud after a runCi job. I tried adding resources and jobs section to shippable.yml but there was no trigger for the job.

**Comment by ankul-shippable** [comment]
@vedant-khandelwal Did you add the runCI job as input to runSh job? That should trigger your runSh job once runCI is completed.

```
jobs:
  - name: <runSh job name>
    type: runSh
    steps:
      - IN: <runCI job name>
```

Let us know if it works for you. Thanks
