### ISSUE TITLE
Array as environment variable

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4718]
Is it possible to use a bash array as environment variable?

I've tested the following code, and some other variations on it, but without any success (i.e. the echo statement doesn't show a variable for EXAMPLE).

```yml
env:
  global:
    - EXAMPLE=( '1404' '1604' '1804' )

build:
  ci:
    - echo "Example: '${EXAMPLE}'"
    - for e in "${EXAMPLE[@]}"; do echo "e: '${e}'"; done
```

**Comment by trriplejay** [comment]
Unfortunately i think the best solution at the moment will be to directly add each index to your script section:

```yml
build:
  ci:
    - EXAMPLE[0]=1404
    - EXAMPLE[1]=1604
    - EXAMPLE[2]=1804
    - echo "Example '${EXAMPLE}'"
    - for e in "${EXAMPLE[@]}"; do echo "e-> '${e}'"; done
```



This is valid bash syntax for setting up an array, and your `for` loop should correctly parse each item.  You can't put these lines in the "global:env:" section since Shippable will add an `export` to the front, and bash doesn't like that for this syntax.

I've opened a bug internally to see if we can add array support for the way you attempted to use it.
