### ISSUE TITLE
Capybara not working Capybara::ElementNotFound - But works on development.

### ISSUE THREAD

**Issue by joeyk16** [Shippable/support#4720]
Hello `rspec` passes locally but on Shippable it does not. I get this error on all specs that require capybara and `js: true`. Such as `RSpec.describe 'User Products View', type: :feature, js: true do`

I get this error on shippable.

```
Capybara::ElementNotFound:
       Unable to find css "#product-uuid113"
```
Here is `shippable.yml`

```
language: ruby
rvm:
  - 2.3.1

services:
  - postgres

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
  - sudo apt-get -y install imagemagick
  - gem update bundler --no-ri --no-rdoc
  - cd .
  - ruby -v

before_script:
  - cp config/database.shippable.yml config/database.yml
  - cp config/application.yml.example config/application.yml
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - bundle exec massa

notifications:
    email:
      recipients:
        - admin@xxxxx.com

```
rails_helper.rb contains

```
Capybara.javascript_driver = :poltergeist

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, phantomjs: Phantomjs.path, js_errors: false)
end
```

Any help would be great. Thank you.
