### ISSUE TITLE
Unable to use sshKey integration in assembly lines

### ISSUE THREAD

**Issue by fieldawarepiotr** [Shippable/support#4725]
### Description of your issue:
Build: https://app.shippable.com/github/fieldaware/jobs/shippable-assembly-lines_master_rSync/builds/5c51c36d0c6b2b0600b5ffae/console

I am trying to add a integration resource as:
```
  - name: ssh-github-infrastructure-modules
    type: integration
    integration: ssh_github_infrastructure_modules
```

I already use it in runCI as (works fine)
```
integrations:
  key:
    - integrationName: ssh_github_infrastructure_modules
      type: sshKey
```

When pushing to sync repo I get:
```
No resource exists for name: ssh-github-infrastructure-modules
rSync encountered 2 errors while processing {repo}/shippable-assembly-lines: 
  - Invalid integration: ssh_github_infrastructure_modules for resource: ssh-github-infrastructure-modules
  - Missing dependency for job: application-deployment
```
