### ISSUE TITLE
Shippable started using shippable.yml from the original branch, not from PR

### ISSUE THREAD

**Issue by Kukunin** [Shippable/support#4726]
### Description of your issue:
It seems like the behavior was changed yesterday. Earlier, I could edit shippable.yml in a pull request, and Shippable used a new updated one in the PR builds.

But yesterday it started using the old one, from the branch, a PR is going to be merged with.

This breaks PRs where, for example, a new dependency is installed or an updated version of ruby is used.

After merging a PR, shippable immediately uses a new shippable.yml, because it's in the upstream branch already, so that's not a cache issue. Also, I tried to reset the cache, with no change at all.

An example build is here:
https://app.shippable.com/github/SpotlightMediaLabs/spotlight-cms/runs/276/1/console
`master` branch uses an old ruby, while `development` branch is migrated to a new ruby

**Comment by rageshkrishna** [comment]
@Kukunin We haven't made any changes in the last couple of days that would have caused this. I suspect there may be something going wrong when we try to merge the YMLs. Would you be able to send me the YML files from both branches? This would help speed up the investigation.

You can send it to ragesh@shippable.com if you'd rather not post it here.

**Comment by Kukunin** [comment]
There is something strange. I just created a new PR to `development` branch with slightly updated shippable.yml, and new build ran the new one. But yesterday I had a PR to the same branch, where I modified shippable.yml a couple of times, and latest builds stopped reflect that changes.

My shippable.yml is pretty standard, can share it here:

```yml
language: ruby

rvm:
  - 2.5.3

branches:
  only:
    - master
    - development

services:
  - redis
  - postgres
  - selenium

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - mkdir -p shippable/testresults
    - shippable_retry bundle install --jobs 4
    - cp config/database.shippable.yml config/database.yml
    - rails db:setup RAILS_ENV=test

    - bundle exec rubocop -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb --format RuboCop::Formatter::JUnitFormatter --out shippable/testresults/rubocop.xml
    - yarn install
    - rails webpacker:compile RAILS_ENV=test
    - rails test:warmup RAILS_ENV=test
    - xvfb-run rspec -f RspecJunitFormatter -o shippable/testresults/results.xml

  post_ci:
    - if [ $IS_PULL_REQUEST == false ] && [ "$BRANCH" == "master" ]; then ./bin/build production; fi
    - if [ $IS_PULL_REQUEST == false ] && [ "$BRANCH" == "development" ]; then ./bin/build staging; fi

integrations:
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_cancel: never
      on_pull_request: never
  hub:
    - integrationName: spotlightlabs
      type: dockerRegistryLogin
```

I have a PR from `development` branch to `master`, where old shippable.yml was used.
I just checked and it still uses the old one. 
Closed/reopened the same PR - didn't help.
Closed a PR/created a new PR with the same commit - didn't help. 

It uses still uses old shippable.yml from the `master` branch:

```yml
language: ruby

rvm:
  - 2.3.0

branches:
  only:
    - master
    - development

services:
  - redis
  - postgres

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - mkdir -p shippable/testresults
    - shippable_retry bundle install --jobs 4
    - cp config/database.shippable.yml config/database.yml
    - rake db:setup RAILS_ENV=test

    - bundle exec rubocop -r $(bundle show rubocop-junit-formatter)/lib/rubocop/formatter/junit_formatter.rb --format RuboCop::Formatter::JUnitFormatter --out shippable/testresults/rubocop.xml
    - rspec --tag ~js -f RspecJunitFormatter -o shippable/testresults/results.xml

  post_ci:
    - if [ $IS_PULL_REQUEST == false ] && [ "$BRANCH" == "master" ]; then ./bin/build production; fi
    - if [ $IS_PULL_REQUEST == false ] && [ "$BRANCH" == "development" ]; then ./bin/build staging; fi

integrations:
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_cancel: never
      on_pull_request: never
  hub:
    - integrationName: spotlightlabs
      type: dockerRegistryLogin
```

It fails because shippable downloads Ruby 2.3.0 instead of 2.5.3 in the PR.
