### ISSUE TITLE
email notification --owners

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4734]
The notification setting for `--owners` doesn't seem to work when used alone.

Between build 147 and 148 I should have gotten an email but havent got any. My build history: https://app.shippable.com/github/vidavidorra/ci-fiddle/dashboard/history. `--last_committer` does work.

```yml
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        --owners
        # --last_committer
      on_success: change
      on_failure: change
      on_cancel: never
      on_start: never
      on_pull_request: never
```
