### ISSUE TITLE
Deploy Fargate service failed -  how to define network-configuration

### ISSUE THREAD

**Issue by cgspohn** [Shippable/support#4738]
We are trying to deploy a service using Fargate in AWS, but got the following error in our build:
https://app.shippable.com/github/shiftgig/jobs/lightbulb_api-deploy/builds/5c5dd1ef3bfdcf07007dfb2e/console

I cannot find where I could define the needed network parameters for the `--network-configuration` equivalent (as described here https://docs.aws.amazon.com/cli/latest/reference/ecs/create-service.html).  Could you please point us in the right direction? I looked through the dockerOptions resource in Shippable but could not see where to enter the subnet, security group and assign public ip values.

**Comment by cgspohn** [comment]
Also, we want to enable service discovery (see `--service-registries` in the create-service aws api.  How would we enable and define those options in Shippable?   I was thinking, for now, could we create the service ahead time with all these settings?  If so, I'd just need to know what service name value will shippable used based on our deploy job.

**Comment by cgspohn** [comment]
And the other problem: how to define the task compatibility to be EC2 and Fargate?  Currently it is set to just EC2

**Comment by a-murphy** [comment]
Fargate is not currently supported in managed deploy jobs.  We recommend using a [runSh job](http://docs.shippable.com/platform/workflow/job/runsh/) for Fargate deployments instead of a managed deploy job.  In a runSh job, you can use the AWS CLI for your deployments instead of the API if you prefer.

If you need to add `networkConfiguration` or `serviceRegistries` to a deployment that is not Fargate, the `networkConfiguration` and `serviceRegistries` options would be under `service` in a dockerOptions resource because it is part of the service object created on AWS.  The structure of both objects should match the one in the [AWS service documentation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html).  Converted to YML, this would be:
```YML
  resources:
  - name: <string>
    type: dockerOptions
    versionTemplate:
      service:
        networkConfiguration:
          awsvpcConfiguration:
            assignPublicIp: <string>
            securityGroups:
              - <string>
            subnets:
              - <string>
        serviceRegistries:
          - containerName: <string>
            containerPort: <string>
            port: <number>
            registryArn: <string>
```

**Comment by cgspohn** [comment]
Thanks a-murphy for your prompt response.  I used your suggestion and added all the missing pieces in the dockerOptions under `service` and `taskDefinition` and looks like this is almost close to deploying.  I think the only remaining hurdle is not defining a role when the service is created, since currently get this:
```
Deploying with the role name:  AWSServiceRoleForECS
creating service
Error creating service: InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.
```

FYI, I was able to add these options under dockerOptions and worked:
```
      taskDefinition:
        family: "lightbulb_api"
        taskRoleArn: "..."
        executionRoleArn: "..."
        cpu: "256"
        memory: "512"
        requiresCompatibilities:
          - FARGATE
```
