### ISSUE TITLE
Trigger runSh only on master builds

### ISSUE THREAD

**Issue by vedant-khandelwal** [Shippable/support#4748]
### Description of your issue:

runSh job has runCI mentioned in `IN`, which gets triggered on every commit. But I want to run the runSh job only for master builds. Didn't find anything helpful in the docs. Any ideas?

**Comment by manishas** [comment]
In the runCI job, you can trigger the runSh job only if the $BRANCH environment variable is equal to master branch. Let me know if this works for you.

**Comment by vedant-khandelwal** [comment]
Can you share the supported syntax for the `IN:` section in runSh for the same?

**Comment by trriplejay** [comment]
The best way to accomplish this would be to additionally insert an intermediate resource between the runCI and the runSh.  This will allow you to selectively trigger the runSh via the resource based on whatever criteria you want in your runCI script.

To set this up, you'd want a yml that looks something like this:
```yml
resources:
  - name: ciResults
    type: params
    versionTemplate:
      params:
        buildNumber: 0 # this is just an initial placeholder
  
jobs:
  - name: projectName_runCI
    steps:
      - OUT: ciResults

  - name: myRunSh
    type: runSh
    steps:
      - IN: ciResults
      - TASK:
          script:
            - echo "hello world"
```

and in your runCI job, you can have a line of your script like this:
```yml
build:
  ci:
    - if [ "$BRANCH" == "master" ]; then shipctl put_resource_state ciResults buildNumber $BUILD_NUMBER; fi
```
The subsequent job is only triggered when the resource is updated, and this line will only update the resource when the branch is "master".

Let us know if you have any additional questions.
