### ISSUE TITLE
Completly disable webhook from gitRepo

### ISSUE THREAD

**Issue by Bit-Doctor** [Shippable/support#4752]
Hello shippable,

## Some context
I've got a `gitRepo` repo resource where I disabled all webhook update. 
```
name: repo-update2
type: gitRepo
integration: github
versionTemplate:
  sourceName: thestorefront/test-terraform-CI
  buildOnCommit: false
  buildOnPullRequest: false
  buildOnPullRequestClose: false
  buildOnRelease: false
  buildOnTagPush: false
```

I use this resource as a `OUT` from a `runCi` job with `replicate: true` and as a IN from a `runSh`. 

My use case is: I want to trigger the downstream `runSh` once the `runCi` job is succeed but I need some info from the build such as the branch, the commit message, the commit etc (not the code).

So it's my understanding that I had two option:
- Setup the pipeline as I did
- Use `on_success` in the build job to pass information that I need. 

I prefer not to use the second option as I don't want add complexity to our dev. 
They only care how to build their repo and I take it from that point.

So far so good when the CI step finish my `gitRepo` get updated with the right information and I can act on it (I use IS_PULL_REQUEST, etc.. to manage the rest of the pipeline).

## Now the issue

The problem is that I noticed that the downstream `runSh` is run twice on some occasion, once from webhook ([link](https://app.shippable.com/github/thestorefront/jobs/update_switch/builds/5c6c27c6b2f57f0600f8a033/trace)) the other from the CI job ([link](https://app.shippable.com/github/thestorefront/jobs/update_switch/builds/5c6c28472c0a8108000ddacb/trace)),  you can see ([here](https://app.shippable.com/subs/github/thestorefront/resources/repo-update2/versions)) that everything is in double and that the `gitRepo` still get updated from webhook. 
In this particuliar case I pushed a new branch to the repo and it trigger an update.

I'm not sure what I missed from the doc or if what I want to achieve is even possible.
I there is nothing to do I guess I will fallback on the second solution.

**Comment by trriplejay** [comment]
This looks like some kind of bug on our end. Somehow the values were set back to defaults instead of the "false" options you provided. I've correct your resource, so it should be back to working now. We're still investigating how this might have happened.

**Comment by Bit-Doctor** [comment]
@trriplejay This is still happening on all my `gitRepo`s. 
I never get `isPullRequestClose: true` despite this being the only webhook enabled, but I guess it must be the same problem since the default for `buildOnPullRequestClose` is `false`

ex: https://app.shippable.com/subs/github/thestorefront/resources/tsf-web/versions

**Comment by a-murphy** [comment]
That you for letting us know that some of your other resources had the same problem.  I've been able to identify three `gitRepo` resources in your subscription that lost the `buildOnCommit` and `buildOnPullRequest` options on February 20th and have updated those so that they should now work as expected.  We're still investigating why your resources lost those settings in the first place.

**Comment by nihtastic** [comment]
is there any global fix for this coming out? i have the same problem with a repo with the configuration below that is used as the replicated `OUT` of a `runSH` job. whenever i push **anything** to the repo a new resource version is created and downstream jobs are triggered.

```
  - name: xxx_repo_deploy
    type: gitRepo
    integration: xxx
    versionTemplate:
      sourceName: xxx/xxx
      buildOnCommit: false
      buildOnPullRequest: false
      buildOnPullRequestClose: false
      buildOnRelease: false
      buildOnTagPush: false
```
