### ISSUE TITLE
[question] How to skip entrypoint from pre_ci_boot

### ISSUE THREAD

**Issue by uilianries** [Shippable/support#4756]
### Description of your issue:
Hi!

I would like to run a custom docker image where there is no entrypoint script prepared. The image only runs `cmd [bash]` and all other steps should be executed on `ci` section.

reference: http://docs.shippable.com/ci/build-image/

My shippable.yml looks like:

```yaml

build:
  pre_ci_boot:
    image_name: conanio/gcc5
    image_tag: latest
    pull: true
  ci:
    - .ci/run.sh
    - .ci/run.sh
```

I read the section that explains about `options`, so I tried to put a environment variable, but it only appends on the line:

```yaml

build:
  pre_ci_boot:
    image_name: conanio/gcc5
    image_tag: latest
    pull: true
    options: -e HOME=/home/conan
  ci:
    - .ci/run.sh
    - .ci/run.sh
```

Also, you can check my logs [here](https://app.shippable.com/github/uilianries/conan-folly/runs/12/1/console).

Regards!
