### ISSUE TITLE
Error connecting to postgresql in runSh job

### ISSUE THREAD

**Issue by vitaliy-mityevskyy** [Shippable/support#4786]
In runCI job I use postgre service and its working perfect, but when I trying to use it in runSh job I getting error that there is no postgres service and no psql command. How can I launch postgres in runSh job?

My yml:

```
services:
  - postgres
jobs:
  - name: tests
    type: runSh
    steps:
      - IN: image_for_tests
        switch: off
      - TASK:
          name: runing_tests
          runtime:
            container: false
            options:
              env: .....
          script:
            - psql -c 'create database test_db;' -U postgres
```
