### ISSUE TITLE
Final job after all matrix builds

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4804]
Is there any way of running a final job if all jobs of a build matix have succeeded? E.g in the following example I want to create bottles for some brew formulae and after those are all done I want to create a docker image including all those bottles. 

I couldn't find any direct information on this in the docs so thought I ask here.
I did see #1592 but that isn't resolved as far as I understood.

```yml
language: none
env:
  matrix:
    - FORMULA: x1
    - FORMULA: x1
build:
  ci:
    - 'echo "building formula ${FORMULA}"'
```

**Comment by trriplejay** [comment]
you can accomplish this by adding an [assembly line](http://docs.shippable.com/platform/workflow/config/#assembly-lines-configuration)

and creating a [runSh job](http://docs.shippable.com/platform/workflow/job/runsh/), which has an IN of your CI job.  By default, the runSh job will not trigger until all matrix items have completed in the CI job.

let me know if you have any questions along the way!

**Comment by vidavidorra** [comment]
@trriplejay Got it working, thanks!

Basically using the following config.

```yml
language: none
env:
  matrix:
    - FORMULA: cmake@3.1.0.rb
    - FORMULA: cmake@3.1.1.rb
    - FORMULA: cmake@3.1.2.rb
    - FORMULA: cmake@3.1.s.rb
build:
  ci:
    - 'echo "building formula ./Formula/${FORMULA}"'
jobs:
  - name: ci-fiddle_runCI
    type: runCI
    steps:
      - IN: ci-fiddle_ciRepo
  - name: deployChanges
    type: runSh
    dependencyMode: strict
    steps:
      - IN: ci-fiddle_runCI
      - TASK:
        - script: 
          - echo "deploying now"
```
