### ISSUE TITLE
shipctl: command not found

### ISSUE THREAD

**Issue by JaZo** [Shippable/support#4817]
When using shipctl I get the following error:

> /root/c6b87b62-e0a6-4888-ba8c-96f363f00a72.sh: line 87: shipctl: command not found

Command:
```yml
build:
  post_ci:
    - shipctl post_resource_state projectRepository versionName $COMMIT
```

Image:
swisleiden/swisdev:latest

Node pool version:
7.2.4

Project Id:
5790c5773be4f4faa56d69b3

Build:
4153
