### ISSUE TITLE
Shippable needs a valid YML file to build your project.

### ISSUE THREAD

**Issue by Asgoret** [Shippable/support#4818]
Hi to everyone. Can somebody help with my CI yml? Shippable says that it's not valid, but i can't find any error or syntax error (i tried linter too)
YAML:
```
# Language setting http://docs.shippable.com/ci/languages/node/
# language: python

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  hub:
    - integrationName: docker_hub
      type: dockerRegistryLogin

# python:
#   - 3.7.2

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - docker build -t asgoret/myimagename:$GIT_TAG_NAME .
  post_ci:
    - docker push asgoret/myimagename:$GIT_TAG_NAME


  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never
```

**Comment by a-murphy** [comment]
The YML parser we use is most likely confused by the colons between your Docker image names and tags.  Could you put quotes around those lines as follows?

```YML
build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - "docker build -t asgoret/myimagename:$GIT_TAG_NAME ."
  post_ci:
    - "docker push asgoret/myimagename:$GIT_TAG_NAME"
```
