### ISSUE TITLE
Postgres not starting, though it is listed under "services"

### ISSUE THREAD

**Issue by stevepaulo** [Shippable/support#4829]
I am experiencing a build failure with Postgres.

Error:
```
psql -c 'create user root with superuser;' -U postgres
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Failed build: https://app.shippable.com/github/stevepaulo/thome/runs/392/1/console
shippable.yml: 

```
language: ruby

rvm:
  - 2.6.2

env:
  global:
    - REDIS_URL=redis://localhost:6379
    - SECRET_KEY_BASE=f1cd9654a79646246e3407426693349eca70d1d3d00cd7996ab5608831a5563c5f293ff19b6a707c1c3982fe1d4ea145635d14841a0d3a56fe5111dcefd27077

services:
  - postgres
  - selenium
  - redis

build:
  pre_ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - cp config/database.shippable.yml config/database.yml
    - psql -c 'create user root with superuser;' -U postgres
    - psql -c 'create database thome_test;' -U postgres
  ci:
    - bundle package --all
    - bundle install --gemfile="Gemfile"
  cache: true
  cache_dir_list:
    - /usr/local/rvm/gems/$(rvm strings 2.6.2)/gems
    - /usr/local/rvm/gems/$(rvm strings 2.6.2)/specifications
    - $SHIPPABLE_BUILD_DIR
  post_ci:
    - rubocop
    - mkdir -p shippable/testresults
    - bin/rails db:migrate RAILS_ENV=test
    - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml

integrations:
  notifications:
    - integrationName: thome_deploy
      type: webhook
      on_failure: never
      on_success: always
      branches:
        only:
          - master
    - integrationName: slack_notify
      type: slack
      recipients:
        - "#notifications"
      on_success: always
      on_failure: always
      on_cancel: never
      on_start: never
      on_pull_request: never
```

Now, the old version of the YML syntax works, but it does not cache the Rubygems install. They install every time and it takes minutes more than it should for each run.

Here's an example of a passing build with the old YML syntax: https://app.shippable.com/github/stevepaulo/thome/runs/393/1/console

And here's the content of the shippable.yml in use there:

```
language: ruby
rvm:
  - 2.6.2
env:
  global:
    - REDIS_URL=redis://localhost:6379
    - SECRET_KEY_BASE=f1cd9654a79646246e3407426693349eca70d1d3d00cd7996ab5608831a5563c5f293ff19b6a707c1c3982fe1d4ea145635d14841a0d3a56fe5111dcefd27077
services:
  - postgres
  - selenium
  - redis
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libpq-dev
  - cp config/database.shippable.yml config/database.yml
  - psql -c 'create user root with superuser;' -U postgres
  - psql -c 'create database thome_test;' -U postgres
install:
  - bundle package --all --no-install
  - bundle install --gemfile="Gemfile"
cache: true
cache_dir_list:
  - /usr/local/rvm/gems/$(rvm strings 2.5.3)/gems
  - /usr/local/rvm/gems/$(rvm strings 2.5.3)/specifications
  - $SHIPPABLE_BUILD_DIR
before_script:
  - rubocop
  - mkdir -p shippable/testresults
  - bin/rails db:migrate RAILS_ENV=test
script:
  - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml

integrations:
  notifications:
    - integrationName: thome_deploy
      type: webhook
      on_failure: never
      on_success: always
      branches:
        only:
          - master
    - integrationName: slack_notify
      type: slack
      recipients:
        - "#notifications"
      on_success: always
      on_failure: always
      on_cancel: never
      on_start: never
      on_pull_request: never
```

**Comment by stevepaulo** [comment]
So, I got the psql step to complete by changing the shippable.yml to this:

```
language: ruby

rvm:
  - 2.6.2

env:
  global:
    - REDIS_URL=redis://localhost:6379
    - SECRET_KEY_BASE=f1cd9654a79646246e3407426693349eca70d1d3d00cd7996ab5608831a5563c5f293ff19b6a707c1c3982fe1d4ea145635d14841a0d3a56fe5111dcefd27077

services:
  - postgres
  - selenium
  - redis

build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
    - cp config/database.shippable.yml config/database.yml
    - psql -c 'create user root with superuser;' -U postgres
    - psql -c 'create database thome_test;' -U postgres
    - bundle package --all
    - bundle install --gemfile="Gemfile"
    - rubocop
    - mkdir -p shippable/testresults
    - bin/rails db:migrate RAILS_ENV=test
    - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml
  cache: true
  cache_dir_list:
    - /usr/local/rvm/gems/$(rvm strings 2.6.2)/gems
    - /usr/local/rvm/gems/$(rvm strings 2.6.2)/specifications
    - $SHIPPABLE_BUILD_DIR

integrations:
  notifications:
    - integrationName: thome_deploy
      type: webhook
      on_failure: never
      on_success: always
      branches:
        only:
          - master
    - integrationName: slack_notify
      type: slack
      recipients:
        - "#notifications"
      on_success: always
      on_failure: always
      on_cancel: never
      on_start: never
      on_pull_request: never
```

However, a new error has arrived. Even though Shippable reports that redis has started, it errors out during the `ci` step like this:

```
  rspec -f RspecJunitFormatter -o shippable/testresults/results.xml

Top 2 slowest examples (0.00002 seconds, 0.4% of total time):
  Team self.load_previous_season loads a previous season
    0.00001 seconds ./spec/models/team_spec.rb:41
  Team self.load_offseason_moves loads offseason moves from MLB.com
    0 seconds ./spec/models/team_spec.rb:51
Coverage report generated for RSpec to /root/src/github.com/stevepaulo/thome/coverage. 50 / 1522 LOC (3.29%) covered.


kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
java: no process found
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

Link to build: https://app.shippable.com/github/stevepaulo/thome/runs/394/1/console
