### ISSUE TITLE
Use Docker Compose in build

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4833]
I've followed the instructions from [Using Docker Compose in CI](http://docs.shippable.com/ci/docker-compose/) and [Using a custom Docker image](http://docs.shippable.com/ci/custom-docker-image/) to set up a build with Docker Compose.

However, [the build](https://app.shippable.com/bitbucket/pagemachineag/shippable-docker-compose/runs/1/1/console) fails with some obscure message:

```
sudo docker logs c.exec.shippable-docker-compose.1.1
standard_init_linux.go:187: exec user process caused "no such file or directory"
```

Any idea what's wrong here?

There is a [public repository](https://bitbucket.org/pagemachineag/shippable-docker-compose/src/master/) for this issue.

The currently used `docker-compose.yml`:

```yaml
version: '3'

services:
  test:
    image: php:7.3.5-cli-stretch
    command: ['php', '--version']
    volumes:
      - /app:/app
    working_dir: /app
```

The currently used `shippable.yml`:

```yaml
language: none

build:
  pre_ci_boot:
    image_name: docker/compose
    image_tag: "1.24.0"
    pull: true
    options: "-e HOME=/root -v /app:/app"

  ci:
    - cp -R . /app
    - docker-compose run --rm test
```
