### ISSUE TITLE
Mount/unmount in pre_ci

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4853]
I'm currently investigating the use of a ramdisk to speed up parts of my build. For this I have something like this in `pre_ci` of my `shippable.yml`:

```yaml
build:
  pre_ci:
    - mkdir -p /app
    - sudo umount /app || true
    - sudo mount -t tmpfs none /app

  pre_ci_boot:
    # ...
    options: "-e HOME=/root -v /app:/app"

  ci:
    - cp -R . /app
    - ...
```

However, this fails quickly:

```
  sudo umount /app
umount: /app: must be superuser to unmount
  sudo mount -t tmpfs none /app
mount: permission denied
```

Any idea why? (See e.g. build 759 of project `54f05f3c5ab6cc13528f2756`)
