### ISSUE TITLE
runSh job trigger sequence

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4903]
I would like to run the `runSh` job after the runCI job finishes. Right now both are getting triggered in parallel. This is my shippable.yaml looks like

```
...
resources:
  - name: kubeconfig
    type: cliConfig
    integration: kube-deployment
  - name: repo_gitRepo
    type: gitRepo
    integration: github_integration
    versionTemplate:
      sourceName: org/repo
      branches:
        only:
          - master
      buildOnCommit: true

jobs:
   - name: promote_repo
     type: runSh
     versionTemplate:
       branches:
         only:
           - master
       buildOnCommit: true
     steps:
       - IN: kubeconfig
       - IN: repo_gitRepo
       - IN: repo_runCI
       - TASK:
           script:
             - echo "Hello World"
```
