### ISSUE TITLE
Renaming subscription integration is ineffective (Invalid integration [existing integration] specified for integration type: generic)

### ISSUE THREAD

**Issue by magwas** [Shippable/support#4905]
### Description of your issue:
https://app.shippable.com/github/kode-konveyor/astinxml/runs/23/1/console

"Invalid integration pypi_astinxml specified for integration type: generic"
 
I do have a key-value integration named "pypi_astinxml" 

My shippable.yml looks like this:

```
build_image: kodekonveyor/toolchain:master
language: python
python:
  - 2.7
integrations:
  generic:
    - integrationName: pypi_astinxml
    - integrationName: kkpipeline

build:
  cache: true
  cache_dir_list:
    - ~/.m2
  ci:
    - /usr/local/toolchain/tools/Script
  on_success:
    - /usr/local/toolchain/tools/publish
  on_failure:
    - /usr/local/toolchain/tools/publish

```
