### ISSUE TITLE
Timezone for "time" resource

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4920]
The [time](http://docs.shippable.com/platform/workflow/resource/time/) resource allows me to trigger jobs at a given point in time. However it seems like the timezone is undefined/unclear.

I've set up a resource to trigger a CI build at 01:00 AM:

```yaml
resources:
  - name: nightly-trigger
    type: time
    versionTemplate:
      interval: "0 1 * * *"

jobs:
  - name: <project>_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
````

However, the build was triggered at 03:00 AM instead:

![image](https://user-images.githubusercontent.com/5037116/63746508-48ea8980-c8a5-11e9-85f3-52520aa13409.png)

(Build 853 of project `54f05f3c5ab6cc13528f2756`)

Of course I could simply change the `interval` accordingly but still this looks inconsistent and could be fixed.
