### ISSUE TITLE
environment variables from integration

### ISSUE THREAD

**Issue by magwas** [Shippable/support#4928]
### Description of your issue:
I try to use a key-value pair integration in my job. The keys I define is 'sonarkey' and 'issuetoken'.
I want these keys to show up as environment variables.
I have added the integration to my shippable.yml, but these keys do not show up as environment variables. What do I miss?
Here is my shippable.yml:

```
build_image: kodekonveyor/toolchain:master
integrations:
  generic:
    - integrationName: kkpipeline


build:
  cache: true
  cache_dir_list:
    - ~/.m2
  ci:
    - set |sed 's/[0-9]/X/g'
    - /usr/local/toolchain/tools/Script
  on_success:
    - /usr/local/toolchain/tools/publish
  on_failure:
    - /usr/local/toolchain/tools/publish

```
A console log is here: https://app.shippable.com/github/edemo/PDEngine/runs/972/1/console
