### ISSUE TITLE
Unable to pull or push private images from GCR using integration name

### ISSUE THREAD

**Issue by rameshpitchaiah** [Shippable/support#4949]
I am unable to pull the private image from GCR using the service account mentioned in the integration page

Error snipperts:
The push refers to repository [us.gcr.io/XXXXXXXXX7/jenkins/XXX-jenkins-k8s-helm]
5ce7c7f1ddb1: Preparing
03901b4a2ea8: Preparing
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication.

shippable.yaml:

language: none
build:
 pre_ci:
  - docker build -f Dockerfile . -t  us.gcr.io/XXXX/jenkins/yyy-jenkins-k8s-helm:latest
  post_ci:
    - docker push us.gcr.io/XXXX/jenkins/yyy-jenkins-k8s-helm:latest
  integrations:
    hub:
      - integrationName: gcr-pull
        type: gcloudKey
    
But i can able to pull the docker image using the service account used in the integration page.

**Comment by a-murphy** [comment]
Could you include either a link to the failing job or the project ID from the bottom of that page?  It sounds like either the integration or the YML may be misconfigured, and we can't tell which is more likely from the information in this issue.  The most common reason overall that integrations aren't available in a job is that the indentation in the YML file is incorrect so that the integrations section isn't found.

**Comment by rameshpitchaiah** [comment]
Thanks for the quick response.
This is the Project Id: 5d72a3b9c34fc40007ec1a9d

**Comment by a-murphy** [comment]
It doesn't look like we found the integration specified in your YML.  Could you make sure the indentation is as follows and the file does not contain both tabs and spaces?  (Either tabs or spaces may be used, but not both in the same YML file.)

```YML
language: none
build:
  pre_ci:
    - docker build -f Dockerfile . -t us.gcr.io/XXXX/jenkins/yyy-jenkins-k8s-helm:latest
  post_ci:
    - docker push us.gcr.io/XXXX/jenkins/yyy-jenkins-k8s-helm:latest
integrations:
  hub:
    - integrationName: gcr-pull
      type: gcloudKey
```
