### ISSUE TITLE
The path /usr/bin/python3.7.0 (from --python=/usr/bin/python3.7.0) does not exist

### ISSUE THREAD

**Issue by FiendHunter** [Shippable/support#4978]
### Description of the issue:
So I have a project in Python 3.7.0 in an Ubuntu 16.04 x86_64 machine. My shippable.yml file is:

```yaml
language: python
python:
    - 3.7.0
build:
    pre_ci_boot:
        image_tag: v6.7.4
    ci:
        - sudo apt-get install rabbitmq-server
        - make process_mng
        - make install_tester
        - pip install -r requirements.txt
        - make start
        - make test
```

You can see the makefile [here](https://github.com/nazaretrogue/Microservicio-multimedia/blob/master/Makefile).

I tried changing the node pool to v6.7.4 but it's still not working. The error message is this:

```bash
virtualenv -p /usr/bin/python3.7.0 /root/venv/3.7.0
The path /usr/bin/python3.7.0 (from --python=/usr/bin/python3.7.0) does not exist

retrying 1 of 3 times...
```
The failed build is [here](https://app.shippable.com/github/nazaretrogue/Microservicio-multimedia/dashboard).

Can anybody help me please????

**Comment by a-murphy** [comment]
Although that image has Python 3.7.0, it's in python3.7, not python3.7.0.  Could you try setting
```YML
language: python
python:
    - "3.7"
```
in your shippable.yml file?
