### ISSUE TITLE
modifying image resource does not trigger IN manifest build

### ISSUE THREAD

**Issue by cpoll** [Shippable/support#5021]
### Description of your issue:
I would like to be able to trigger a downsteam manifest build when I modify the `versionName` of the  image resource referenced by my manifest as an IN resource. My use case is to be able to store image versions in git and trigger a new deployment after merging a pull request that changes those versions.

I have a manifest job, `my-service-manifest` with an `- IN: my-service-img` step. If I build it manually, it creates an AWS resource with the appropriate configuration. However, if I modify the `versionName` for `my-service-img`, the downstream manifest does not run. I've been able to get this automatic trigger to happen when I use `shipctl post_resource_state` (different image/manifest).

Is this behaviour by design, or have I misconfigured my jobs/resources?

My Shippable configuration looks like this:
```
resources:
  - name: my-service-img
    type: image
    integration: ecr-integration
    versionTemplate:
      sourceName: "myDockerRepo/myImage"
      versionName: develop.123

jobs:
  - name: my-service-manifest
    type: manifest
    steps:
      - IN: my-service-img
        switch: on
      - IN: my-service-options
        applyTo:
         - my-service-img
```

Link to actual manifest: https://app.shippable.com/github/formhero/jobs/td-dev-pdf-internal-manifest/dashboard
