### ISSUE TITLE
Replicas not created in manifest jobs

### ISSUE THREAD

**Issue by maggiedeuitch** [Shippable/support#5026]
I have a replicas resource:
```
- name: my-replicas-resource
  type: replicas
  versionTemplate:
    count: 1
    minReplicas: 1
    maxReplicas: 3
    autoScalingRole: arn:aws:iam::11111111111:role/ecsAutoscaleRole
    autoScalingPolicies:
      - PolicyName: AutoScalingPolicyForServices
        PolicyType: "TargetTrackingScaling"
        TargetTrackingScalingPolicyConfiguration:
          PredefinedMetricSpecification:
            PredefinedMetricType: "ECSServiceAverageCPUUtilization"
          ScaleInCooldown: 60
          ScaleOutCooldown: 60
          TargetValue: 75
```
When I use it in a manifest job, the replicas settings do not get applied to my service.
```
jobs:
  - name: my-manifest	
    type: manifest	 
    steps:	
    - IN: my-replicas-resource	
    - IN: my-img	
    - IN: my-options	
      applyTo:	    
      - my-img
```
However, if I use it in my deploy job and apply it to my manifest, it works fine. 
In your documentation, it says that this resource is used as an `IN` for deploy jobs and manifest jobs. Is it a bug that it's not working for my manifest job? 
```
jobs:
...
  - name: my-deploy
    type: deploy
    method: blueGreen
    dependencyMode: chrono
    steps:
...
    - IN: my-manifest
    - IN: my-replicas-resource
      applyTo:
      - manifest: my-manifest
...
```
