### ISSUE TITLE
Cache and shippable.yml

### ISSUE THREAD

**Issue by mei-li** [Shippable/support#5027]
### Description of your issue:
We have made some changes in shippable.yml. We have branches that include these changes and ones that do not. I can see from the build that some Pull requests and commits take into account the shippable.yml changes. Though in some branches/ Pull requests, while the changes are in shippable.yml after some commit, the build tries to use the old yml that refers to an unexistent file. 
We had this issue in the past many times as well. Rerun does not help. If I remember correctly in the past we used a workaround of making a new branch.

- https://app.shippable.com/bitbucket/uberresearch/radar/runs/34257/1/console
- Script `shippable_check_integration_tests` was used in the old yml, but it doesnt exist any more.

I suspect that these 2 branches were pushed and build initially before the changes in yml took place, then the changes were pulled in the branch, but the shippable.yml is somehow cached. Is that what happens? Is it expected behavior?

shippable.yml structure
```
    language: python

python:
    - 3.7.3
env:
    - secure: .....

build:
    pre_ci_boot:
        image_name: ...
        image_tag: ...
        pull: true
    cache: true
    cache_dir_list:
        - $SHIPPABLE_BUILD_DIR/node_modules
    ci:
        # set locale
        - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
       # more commands
```
