### ISSUE TITLE
Deploy to DigitalOcean Kubernetes cluster: Failed to apply namespaceSpec

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#5051]
I currently try to set up a deployment to a DigitalOcean Kubernetes cluster using the Shippable docs:

http://docs.shippable.com/deploy/continuous-delivery-single-container-docker-application/
http://docs.shippable.com/deploy/deploy-multiple-containers/

This is the `shippable.yml` of the `rSync` repo right now:

```yaml
resources:
  - name: foo_deploy_cluster
    type: cluster
    integration: foo_cluster
    versionTemplate:
      sourceName: foo-cluster

jobs:
  - name: foo_deploy_manifest
    type: manifest
    steps:
     - IN: foo_frontend_image
     - IN: foo_backend_image

  - name: foo_deploy
    type: deploy
    steps:
      - IN: foo_deploy_manifest
      - IN: foo_deploy_cluster
```

If I trigger a CI build which is [set up to output](http://docs.shippable.com/ci/tutorial/build-push-image-to-docker-hub/) e.g. the `foo_frontend_image`, the `manifest` job is triggered just fine. However, the `deploy` job fails:

```
 /home/shippable/micro/nod/genExec/managed/deploy/run.sh
Starting Deployment for: foo_deploy
Preparing manifests
Applying manifest overrides for foo_deploy_manifest
Summary of cluster:
-- added: 1
-- changed: 0
-- deleted: 0
Force deployment is: false
Reset deployment is: false
Summary of 1 manifests:
-- scalable:  0
-- deployable:  1
-- removable: 0
Deployment Settings:
-- method:  blueGreen
-- workflow:  serial
-- maxWaitTime: 600
getting previous deploy output
Executing deploy type: blueGreen
getting previous namespace spec.
getting previous deployment spec.
Generating namespace specification
W0327 14:00:21.416630    9595 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
error: error validating "/tmp/shippable/c9bb4319-5410-465d-9540-cae1d49fcc83/deploymentSpec-ab396f88-4731-4f2f-9110-7962d004a64c.json": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
Failed to apply namespaceSpec: kubectl failed and exited with error code 1
Successfully created folder /build/state/foo_deploy_manifest/
Successfully saved file kube-namespace-spec.json
Failed to deploy manifest for type: blueGreen
Successfully created folder /build/state
Successfully saved file outputVersion.json
Deployment failed for foo_deploy_manifest
Deployment failed with error : true
```

Any idea what's wrong?
