### ISSUE TITLE
Unable to connect to test database when running tests with docker compose

### ISSUE THREAD

**Issue by pagles** [Shippable/support#5061]
### Unable to connect to a test database when running tests with docker-compose
We have a very typical setup for running our tests in one of our projects which consists of a postgresql image and a custom image that holds our code (based on the python 3.7 docker image). We are running the tests using docker compose where the container with our code `depends_on` the database container. The code container waits for the database container to spin up and then uses it to run the tests. It's a very typical setup that has been working flawlessly for more than a year in this specific project and we use the same setup for a handful more projects. Since March 27 and only for the project in question the above setup has started failing with an error like `psql: could not translate host name "[database name here]" to address: Name or service not known`. After many attempts to make it work I have stripped our setup down to a plain container without any code trying to connect to a db and it still fails. I am posting here the failure of this final totally simplistic setup.

#### Link to one of the build failures
- https://app.shippable.com/github/fieldaware/domo/runs/26/1/console

#### Scripts called from the yml:
- https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh (this is the typical wait for it script to check if a service is up).

#### Reproduction setup
I stripped my repository to the bare minimum and did a run in shippable which failed. The bare minimum setup that fails is the following (notice that it includes no code, it is just spinning up the database and a container and plainly tries to connect to the database from the container). The error is the one I describe:
`psql: could not translate host name "domo-db" to address: Name or service not known`

Dockerfile:
```
FROM python:3.7-stretch

MAINTAINER "Fieldaware Engineering Team" <techteam@fieldaware.com>

RUN apt-get update
RUN apt-get install -y apt-utils postgresql-client

RUN mkdir /scripts
COPY scripts/wait_for_it.sh /scripts/wait_for_it.sh

ENTRYPOINT ["/bin/bash'"]
```

docker-compose.yml
```
version: '3'
services:
  domo-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=domodb
    ports:
      - "5432:5432"
    healthcheck:
      test: psql --username postgres --command "select 1"
  domo-db-test:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      domo-db-test
    depends_on:
      - domo-db
```

shippable.yml
```
language: python

python:
  - 3.6

build:
  cache: true
  pre_ci_boot:
    options: "-v /domo:/domo"

  ci:
    - cp -Rf . /domo
    - pip install -U pip
    - pip install -U docker-compose
    - docker-compose build
    - docker-compose run --rm --entrypoint "bash /scripts/wait_for_it.sh domo-db:5432 -- psql --host domo-db --username postgres --command 'select 1'" domo-db-test
```
