### ISSUE TITLE
AWS Firelens configuration

### ISSUE THREAD

**Issue by maggiedeuitch** [Shippable/support#5084]
Hi there,

I'm trying to configure AWS [Firelens](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html) and my build fails. Firelens is relatively new, so I'm wondering if Shippable supports it?
It doesn't seem to like the `dependsOn` and `firelensConfiguration` parameters

- Link to the build failure
https://app.shippable.com/github/formhero/jobs/formhero-dev-deploy/builds/5eb1c6ffd2a8330007e9a350/console 
- Example yml:

```
jobs:
  - name: example-manifest
     type: manifest
     steps:
       - IN: app-img
       - IN: app-options
         applyTo:
         - app-img
       - IN: log-router-img
       - IN: log-router-img-options
         applyTo:
         - log-router-img
...
  - name: example-deploy
     type: deploy
     method: upgrade
     steps:
      - IN: example-manifest
         switch: 'off'
      - IN: example-manifest-options
      applyTo:
      - manifest: example-manifest
...
resources:
  - name: example-manifest-options
     type: dockerOptions
     versionTemplate:
       taskDefinition:
         taskRoleArn: "arn:aws:iam::1234:role/ecs-task-firehose"
         executionRoleArn: "arn:aws:iam::1234:role/ecsTaskExecutionRole"
       networkMode: "bridge"

  - name: app-options
     type: dockerOptions
     versionTemplate:
       memoryReservation: 350
       cpu: 100
       logConfig:
         type: "awsfirelens"
         options:
          delivery_stream: example-stream-name
          region: ca-central-1
          Name: firehose
      dependsOn:
        containerName: log-router-img
        condition: START

 - name: log-router-img-options
   type: dockerOptions
   versionTemplate:
     memoryReservation: 50
     cpu: 50
     logConfig:
       type: "awslogs"
       options:
          awslogs-group: /ecs/example-manifest
          awslogs-region: ca-central-1
          awslogs-stream-prefix: ecs
     firelensConfiguration:
        type: "fluentbit"
        options: null

 - name: app-img
    type: image
    integration: ecr-integration
    pointer:
      sourceName: 123456789.dkr.ecr.ca-central-1.amazonaws.com/app-image
    seed:
      versionName: latest

 - name: log-router-img
    type: image
    integration: ecr-integration
    pointer:
      sourceName: 906394416424.dkr.ecr.ca-central-1.amazonaws.com/aws-for-fluent-bit
    seed:
      versionName: latest

```
