### ISSUE TITLE
PhantomJS not available in V2

### ISSUE THREAD

**Issue by foldingbeauty** [Shippable/support#510]
When my test suite is running (rspec / cucumber + poltergeist) I got a error that PhantomJS is not available. Do I need to install PhantomJS myself with apt-get? It worked on V1 not on V2.

**Comment by Antronin** [comment]
I would like to reopen this bug as I experience the exact same error message:
```
Could not find an executable ["phantomjs"] on your path. (Cliver::Dependency::NotFound)
      ./features/step_definitions/have_menu.rb:7:in `/^I am on (.*)$/'
```
My shippable yaml is:
```
# build image from Docker Hub (see https://registry.hub.docker.com/repos/shippableimages/)
build_image: shippableimages/ubuntu1404_ruby

# language setting
language: ruby

# version numbers
rvm:
  - 2.0.0

#activate rvm
before_install:
  - shippable_retry apt-get update && apt-get install -y tesseract-ocr libtesseract-dev libtesseract3 libleptonica-dev liblept4 libpq-dev imagemagick libmagickwand-dev libmysqlclient-dev mysql-server
  - ln -s /usr/share/tesseract-ocr/tessdata
  - source ~/.rvm/scripts/rvm
  - shippable_retry rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY
  - service mysql start
  - mysqladmin create ******_test
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *****_test.* TO shippable@localhost"
  - git remote -v | grep ^openshift || git remote add openshift $OPENSHIFT_REPO

#install the dependencies
install:
  - bundle install --gemfile="Gemfile"
  - ruby -v

before_script: 
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults

script:
  - bundle exec rake

notifications:
  email:
    recipients:
    - ******@gmail.com

env:
  global:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
  - TEST_DB_HOST=127.0.0.1 TEST_DB_PORT=3306 TEST_DB_USERNAME=shippable TEST_DB_PASSWORD=*****
  - TESSDATA_PREFIX=/usr/share/tesseract-ocr/
  - OPENSHIFT_REPO=ssh://*****.rhcloud.com/~/git/webfrontend.git/

after_success:
  - git push -f openshift $BRANCH:master
```
