### ISSUE TITLE
Support for Node 12 language version?

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#5111]
### Description of your issue:
Node 12 has been LTS for about 8 months now. Can you add to supported language versions please?

**Comment by byrondover** [comment]
Hey @kileyhykawy, Shippable will no longer be accessible after May 2, 2021. You can learn more about the Shippable sunset here:

https://blog.shippable.com/the-next-step-in-the-evolution-of-shippable-jfrog-pipelines

In the meantime, you can switch to Node 12 on any Linux-based job node by adding the following to your `shippable.yml` file:

```yml
language: node_js

node_js:
  - 12.21.0

build:
  ci:
    # Upgrade Node.js
    - nvm use 12
```

I hope that helps.

Cheers! 🍻
