### ISSUE TITLE
How to set placement constraints for ECS in Shippable

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5131]
ECS offers 2 places where placement constraints are available on is the task definition level and service definition

**Task Definition level**

![image](https://user-images.githubusercontent.com/2689801/89136179-023eee00-d550-11ea-8d1b-df8d80857c8b.png)

**Service Definition level**

![image](https://user-images.githubusercontent.com/2689801/89136348-de2fdc80-d550-11ea-9d50-d1e45bea257e.png)

In the documention [Docker Option](http://docs.shippable.com/platform/workflow/resource/dockeroptions/) I only saw schedulinStrategy under service but nothing under nothing under taskDefinition.

        placementStrategy:
         - field: <string>
           type: <string>
         - field: <string>
           type: <string>
        schedulingStrategy: <string>

Should I put my placement constraints under schedulingStragtegy? Is there something for taskdefintion

**Comment by a-murphy** [comment]
The taskDefinition section will accept a `placementStrategy`, with the same fields and types as the service, but not `schedulingStrategy`.  I think you might be looking for `placementConstraints` in taskDefinition, which is an array of objects with `type` (`memberOf` or `distinctInstance`) and `expression`.

**Comment by tkumark** [comment]
@a-murphy  if were to set placementConstraints at the service level would it be like this?
```
service:
        placementStrategy:
         - field: attribute:appname == myapp
           type: memberof
```

**Comment by a-murphy** [comment]
```YML
service:
  placementConstraints:
    - field: "attribute:appname == myapp"
      type: memberOf
```
should be valid assuming you have an `appname` attribute on the instances.  It is still `placementConstraints` whether it is in the task definition or service with those settings.  The [placementStrategy](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html) can only be `binpack`, `random`, or `spread`.

**Comment by tkumark** [comment]
@a-murphy thanks you right the `appname` attribute is set in the instances. I am adding at userdata
 `echo ECS_INSTANCE_ATTRIBUTES={\"appname\":\"myapp\"} >> /etc/ecs/ecs.config;echo`

**Comment by tkumark** [comment]
Set placement constrainst for custome attribute.

```
  - name: myresourceName
    type: dockerOptions
    version:
      service:
        placementConstraints:
          - expression: "attribute:appname == myapp"
            type: memberOf
```
