### ISSUE TITLE
Is capacityProviderStrategy provided support by shippable

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5138]
When I tried to add the below definition and I go error while deploying. Is Capacity Provider Strategy supported by shippable?

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html

> error creating service: UnexpectedParameter: Unexpected key 'capacityProviderStrategy' found in params
> { UnexpectedParameter: Unexpected key 'capacityProviderStrategy' found in params
>     at ParamValidator.fail (/home/shippable/micro/nod/node_modules/aws-sdk/lib/param_validator.js:50:37)

```
  - name: myservice-opts
    type: dockerOptions
    versionTemplate:
      service:
        capacityProviderStrategy:
          - capacityProvider: "splat-prod"
            weight: 0
            base: 0
```
