### ISSUE TITLE
how to pass value from one job to another job

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5185]
I have 2 job. Job A creates loadbalancer and job B deploys ecs task. Job A and Job B are linked so job B will only run after job A. 

I am creating a loadbalancer and targetgroup in Job A. In Job B I am deploying an ecs task I would like to pass the targetgroup name created in the previous

```
  - name: myapp-frontend-dev-elb
    type: loadBalancer
    pointer:
      sourceName: <variable with value defined in Job A>
      method: application
```
