### ISSUE TITLE
How to setup GPU  in ECS docker option

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5188]
How do i set the GPU as part of the dockerOptions? I only see cpu option I do not see GPU option. Does shippable support GPU option?
http://docs.shippable.com/platform/workflow/resource/dockeroptions/

I tried this but it does not working

```
  - name: 1-gpu-docker-opts
    type: dockerOptions
    version:
      gpu: 1
```

![image](https://user-images.githubusercontent.com/2689801/103534229-80fbd680-4eb4-11eb-934a-df2c5cb0de5b.png)

**Comment by tkumark** [comment]
This works
```
  - name: 1-gpu-docker-opts
    type: dockerOptions
    version:
      resourceRequirements:
       - type: GPU
         value: '1'
```
