### ISSUE TITLE
Sippable don't share local maven repository between projects

### ISSUE THREAD

**Issue by Nayalison** [Shippable/support#577]
Hi,

I do an mvn install in my YML file but every time it download all dependencies. This did not happen in version v1. Local maven repository is shared between projects?

My YML file:

``` YML
build_environment: ubuntu1204

node_js:
  - 0.10.24

language: java

jdk:
 - oraclejdk7

rvm:
 - 2.0.0

addons:
  firefox: "23.0"

before_install:
  - source ~/.nvm/nvm.sh && nvm use 0.10
  - source ~/.rvm/scripts/rvm && rvm use 2.0.0

install:
  - bundle install
  - sudo apt-get -y install graphviz
  - psql -U postgres < config/circleci.sql
  - mkdir -p $HOME/.fonts; cp fonts/msttcorefonts $HOME/.fonts -a
  - npm install
  - "cp src/main/resources/database.properties.shippable src/main/resources/database.properties"
  - mvn install -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true

before_script:
  - "DISPLAY=:1999 /etc/init.d/xvfb start"

script:
  - ./bin/run_tests.sh

after_success:
  - ./bin/deploy.sh

after_script:
  - "/etc/init.d/xvfb stop"
```
