### ISSUE TITLE
All Selenium Tests Fail

### ISSUE THREAD

**Issue by rawphp** [Shippable/support#609]
Haven't been able to get any of my selenium tests to pass. Tried looking at any example I could find, but nothing made a difference yet. Each test fails in the same way as shown below in the log. I tried adding `wait()` periods, but they were either ignored or it didn't help.

Thanks in advance for any help.

Tom

The tests are run using Ant build.xml file.

Here are some excerpts from the log:
## Log Output

```
5.4 (set by /home/shippable/.phpenv/version)
Using firefox version Mozilla Firefox 29.0
127.0.0.1 stepindeals
`/tmp/hosts.original' -> `/etc/hosts'
mysql started successfully
postgres started successfully
selenium started successfully
```

```
Starting virtual X frame buffer: Xvfb.
Buildfile: /home/shippable/workspace/src/bitbucket.com/mrdevfree/step-in-deals/build.xml
```

```
codecept-accept:
     [exec] The command attribute is deprecated.
     [exec] Please use the executable attribute and nested arg elements.
     [exec] Codeception PHP Testing Framework v2.0.5
     [exec] Powered by PHPUnit 4.2.5 by Sebastian Bergmann.
     [exec] Creating MySql()
     [exec] Creating Migrator()
     [exec] Running prepareDatabase()
     [exec] Creating Test.lock file
     [exec] Creating Application()
     [exec] 
     [exec] 
     [exec] ************* RAW_TESTING *************
     [exec] 
     [exec] Updating Migrator Database
     [exec] 
     [exec] 
     [exec] ************* BOOTSTRAP ********************
     [exec] 
     [exec] 
     [exec] Acceptance Tests (7) ----------------------------------------------------------------------------------------------------------------------------------------------------
     [exec] Trying to register and delete account (Deals\Tests\Acceptance\RegisterAndDeleteAccount::registerAndDeleteAccount)                                                   Fail
     [exec] Trying to login and logout (Deals\Tests\Acceptance\SignInAndSignOut::loginAndLogout)                                                                                Fail
     [exec] Trying to login not registered (Deals\Tests\Acceptance\SignInAndSignOut::loginNotRegistered)                                                                        Fail
     [exec] Trying to login as normal user (Deals\Tests\Acceptance\SignInAndSignOut::loginAsNormalUser)                                                                         Fail
     [exec] Trying to login as business user (Deals\Tests\Acceptance\SignInAndSignOut::loginAsBusinessUser)                                                                     Fail
     [exec] Trying to login as admin user (Deals\Tests\Acceptance\SignInAndSignOut::loginAsAdminUser)                                                                           Fail
     [exec] Trying to upgrade account to business (Deals\Tests\Acceptance\UpgradeToBusinessAccount::upgradeAccountToBusiness)                                                   Fail
     [exec] -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     [exec] 
     [exec] 
     [exec] Time: 19.29 seconds, Memory: 13.25Mb
     [exec] 
     [exec] There were 7 failures:
     [exec] 
     [exec] ---------
     [exec] 1) Failed to register for an account in Deals\Tests\Acceptance\RegisterAndDeleteAccount::registerAndDeleteAccount (/home/shippable/workspace/src/bitbucket.com/mrdevfree/step-in-deals/tests/acceptance/RegisterAndDeleteAccountCest.php)
     [exec] Couldn't see "Account","li":
     [exec] Failed asserting that any element by 'li' on page /
     [exec] Elements: 
     [exec] + <li> The site could be temporarily unavailable or too busy. Try again in a few moments.
     [exec] + <li> If you are unable to load any pages, check your computer's network connection.
     [exec] + <li> If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
     [exec] contains text 'Account'
     [exec] 
     [exec] Scenario Steps:
     [exec] 3. I see "Account","li"
     [exec] 2. I am on page "/"
     [exec] 1. As a a new user
```
## Shippable.yml

```
# language
language: php

# versions
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - DB=mysql

archive: TRUE

addons:
    firefox: "29.0"
    hosts:
        - stepindeals

services:
    - selenium

before_script:

    # install composer dependencies
    - composer self-update
    - composer install --dev --prefer-source

    # copy codeSniffer config file
    - cp vendor/rawphp/raw-code-standards/CodeSniffer.conf vendor/squizlabs/php_codesniffer/CodeSniffer.conf
    # create RawPHP standard directory
    - mkdir vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/RawPHP
    # copy standard sniffs to new directory
    - cp -r vendor/rawphp/raw-code-standards/RawPHP/* vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/RawPHP

    # prepare database
    - mysql -e "CREATE DATABASE IF NOT EXISTS step_in_deals_db;"
    - mysql -e "CREATE DATABASE IF NOT EXISTS step_in_deals_db_test;"

script:
    - "export DISPLAY=:99.0"
    - "/etc/init.d/xvfb start"
    - ant

after_script:
    - "/etc/init.d/xvfb stop"
```
