### ISSUE TITLE
Builds have stopped running

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#647]
Pushing updates to origin no longer triggers a build. When rerunning a build I get a spinner and "Waiting for build information..." and nothing happens.

Project: https://app.shippable.com/projects/540f393f586ac5d7e36513c9

My shippable.yml

```
language: ruby
rvm:
  - 2.1.2
branches:
  only:
    - dev
    - stage
    - master
notifications:
   email: false
env:
  - SLACK_ORG=wearefine PROJECT=tracking-sandbox-site
  - CI_REPORTS=shippable/testresults
  - secure: WHKr6NA+6gu7Ghn7O/BL26/HWB6t9Enm2aEF1FZkvm3nefqvppppll3lQAtnMy21VVsQHURKSVr0NVrBOEh8FXeXO6COmM4dYi7S+x718gi9nzmiAH/zjPUBEXFoNAfkZ8y81d2UF7l4cTRMq/H4BqB2XUExlDy1R/OHouXvot32Zy3Sf+8Yv9sbBDjy2yWXBf6TqBOkgMZ73dq8BT4AZ6d1ooELcxu7kdhKpuMRZQnmtq6b7WzrVA/15P6BzoxfzTi95ZVnBIqKyLwHj6ro4oP1JZuVaUhSbJEmr95K3MJd11kbxWXY32HEjPf+YuNLIWdYSv59b65Pp7Ctpn1WYg==
before_script:
  - mkdir -p shippable/testresults
  - mysql -e 'create database tracking_sandbox_test;'
script:
  - rspec -f JUnit -o shippable/testresults/results.xml
  - ssh-agent bash -c 'ssh-add /home/shippable/.ssh/id_rsa; ssh -i /home/shippable/.ssh/id_rsa -vT git@bitbucket.org; cap prod deploy'
after_failure:
  - python slack_notifier.py --project $PROJECT --org $SLACK_ORG --token $SLACK_TOKEN
after_success:
  - python slack_notifier.py --project $PROJECT --org $SLACK_ORG --token $SLACK_TOKEN -s
```

thanks!
