### ISSUE TITLE
No test results found if the build is failed

### ISSUE THREAD

**Issue by rockerhieu** [Shippable/support#657]
Here is part of my `shippable.yml`

``` yaml
script:
  - ./gradlew lintDebug testDebug jacocoTestReport

after_script:
  - cp app/build/test-results/*.xml shippable/testresults
  - cp app/build/jacoco/*.exec shippable/codecoverage
  - cp app/build/test-report shippable
  - cp app/build/outputs/apk shippable
  - cp app/build/outputs/lint-results-debug_files shippable/lint
  - cp app/build/outputs/lint-results-debug.html shippable/lint
  - cp app/build/outputs/lint-results-debug.xml shippable/lint
```

`after_script` isn't executed if the build is failed at `script` section. My build is failed because of the test at `script`: https://app.shippable.com/builds/54379cff1e5036010256ddf0, but I don't see any test results.
