### ISSUE TITLE
Test results of phpunit are always "0", even if tests pass or fail

### ISSUE THREAD

**Issue by urbanc** [Shippable/support#658]
Bitbucket username: skyx

Script return:

``` bash
phpunit -c app/ --log-junit shippable/testresults/junit.xml                          
PHPUnit 4.1.6 by Sebastian Bergmann.                          
Configuration read from /home/shippable/workspace/src/bitbucket.com/USERNAME-SECRET/PROJECTNAME-SECRET/app/phpunit.xml.dist                          
.................
Time: 16.67 seconds, Memory: 72.25Mb         
OK (17 tests, 32 assertions)

Build script completed
Build completed
```

Interface problem where it should show 17 tests passing
![screen shot 2014-10-10 at 13 12 04](https://cloud.githubusercontent.com/assets/1261854/4591540/71933166-506e-11e4-8a92-06a6e7dff00d.png)

My shippable.yml file

``` yml
language: php

php:
  - 5.6

before_script:
  - composer install -n
  - echo "Creating database...";
#  - php app/console doctrine:database:drop --force --env=test
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:update --force --env=test

  - echo "Loading data fixtures...";
  - php app/console doctrine:fixtures:load --env=test --purge-with-truncate --append

  - echo "";
  - echo "Running tests...";
  - echo "";

  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script: phpunit -c app/ --log-junit shippable/testresults/junit.xml

notifications:
  email:
    on_success: never
    on_failure: always
```
