### ISSUE TITLE
Missing secure variable in build

### ISSUE THREAD

**Issue by joshystuart** [Shippable/support#667]
Hi,

I created a new secure environment variable however it is missing when I run a build.

Shippable.yml

``` yml
env:
  - FOO="bar"
  - secure: [... my secure var ...]
before_script: 
  - echo "This is the token - ${GITHUB_TOKEN} - which appears empty"
  - echo "This is an environmental var - ${FOO}"
```

This results in out put from the console:

``` bash
This is the token -  - which appears empty
This is an environmental var - bar
```

This is only happening on a new repo which I set up in the last week or so, whereas secure variables work on old projects.

Can you please provide a solution/fix asasp as it's blocking our builds.

Thanks
