### ISSUE TITLE
Could not create CompressorInputStream.

### ISSUE THREAD

**Issue by sirvon** [Shippable/support#758]
.......
Download http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Android SDK not found. Downloading...

FAILURE: Build failed with an exception.
- Where:

Build file '/home/shippable/workspace/src/bitbucket.com/loqooapps/creator-android/app/build.gradle' line: 20
- What went wrong:

A problem occurred evaluating project ':app'.

> org.apache.commons.compress.compressors.CompressorException: Could not create CompressorInputStream.

---

here's my .yml:

``` yaml
language: java
jdk:
- oraclejdk7
install:
- sudo apt-get install -u lib32stdc++6 lib32z1
- ./gradlew clean assemble
notifications:
email:
recipients:
- 
```
