### ISSUE TITLE
Nothing in coverage and tests

### ISSUE THREAD

**Issue by luigi7up** [Shippable/support#788]
Hey guys, we have problems setting up properly our builds. We want our tests to come out in TESTS tab and code coverage in COVERAGE tab. We have something setup wrong because we see that the first "tag" DEPLOY was successful and the build succeeded

Matrix Values runtime=2.1.3 env=DEPLOY="shippable",PROJECT="ci",VERBOSE="1",JOBS="8",RUBY_GC_MALLOC_LIMIT="990000000"

And the second tag CI_REPORTS we see it fails, but it doesn't explain why
Matrix Values runtime=2.1.3 env=CI_REPORTS="shippable/testresults",COVERAGE_REPORTS="shippable/codecoverage"

Before adding ``` - rspec -f JUnit -o shippable/testresults/results.xml``` to the .yml we were seeing the tests inside the *rake* section in the build output, but now we want that data in the tabs you have especially for that purpose.

Could you please look into our script and tell us what we are doing wrong?

https://app.shippable.com/builds/546b26397aac73c60083334d
```
language: ruby
rvm:
  - 2.1.3
env:
  - DEPLOY=shippable PROJECT=ci VERBOSE=1 JOBS=8 RUBY_GC_MALLOC_LIMIT=990000000
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
services:
  - selenium
addons:
  postgresql: '9.3'
  firefox: "23.0"
bundler_args: -j 3 --without development debug production profile console

before_install:
  - rvm rvmrc trust .

before_script:
  - mkdir -p shippable/testresults
  - cp config/database.yml.shippable config/database.yml
  # - psql -c 'create database "ria_test";' -U postgres
  - rake db:create RAILS_ENV=test
  - rake db:schema:load RAILS_ENV=test
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"

script:
  - rspec -f JUnit -o shippable/testresults/results.xml
after_script:
  - "/etc/init.d/xvfb stop"
```
