### ISSUE TITLE
Skip counts is included with error counts at Build History

### ISSUE THREAD

**Issue by zephiransas** [Shippable/support#793]
![2014-11-20 10 36 58](https://cloud.githubusercontent.com/assets/909101/5118147/32c53e54-70a1-11e4-9126-49d5620fee1d.png)

Actually in build 8.5, Error count is 1 and Skip count is 1.
So, It looks Skip counts is included with error counts...  

Part of my shippable.yml is bellow.

``` yml
(snip)
parallelized_test: true

env:
  matrix:
    - "PARA_NUM_GROUPS=5 PARA_GROUPS=1"
    - "PARA_NUM_GROUPS=5 PARA_GROUPS=2"
    - "PARA_NUM_GROUPS=5 PARA_GROUPS=3"
    - "PARA_NUM_GROUPS=5 PARA_GROUPS=4"
    - "PARA_NUM_GROUPS=5 PARA_GROUPS=5"
  global:
    - CI_REPORTS=shippable/testresults
(snip)
```
