### ISSUE TITLE
build.sh: line 76: export: ` ...  ': not a valid identifier

### ISSUE THREAD

**Issue by scmadmin** [Shippable/support#806]
Seeing this error while trying a sample deployment.  
/home/shippable/build/build.sh: line 76: export: `=my/decrypted/secretawskey': not a valid identifier

It happens in the second step, named "run", during "docker run"

The string "`=my/decrypted/secretawskey" is my decrypted secret key, but with an "=" in front of it.   I looked around for errant quotes or such in my config that might have messed up any downstream scripts, but I think my stuff is ok.  Though it did not start happening until I added config for deployment.  I think somehow an extra "=" sign is getting in there, maybe on this line:

```
  - echo 'AWSSecretKey='$AWSSecretKey >> ~/.elasticbeanstalk/aws_credential_file
```

I did try changing the quotes around in valid bash ways ( echo 'AWSSecretKey='"$AWSSecretKey"), no dice.

here is one of the failed builds
https://app.shippable.com/builds/54736c741609a515006251b1

here is my shippable.yaml

```
# language setting
language: java
  # jdk tag
jdk:
 - oraclejdk8


env:
  global:
    - EB_TOOLS_DIR=/tmp/eb_tools EB_VERSION=AWS-ElasticBeanstalk-CLI-2.6.3 EB_TOOLS=$EB_TOOLS_DIR/$EB_VERSION
    - RDS_HOSTNAME=127.0.0.1 RDS_USERNAME=shippable RDS_PASSWORD="" RDS_DB_NAME=test RDS_PORT=3306
    - AWS_ACCESS_KEY_ID=removed
    - secure: removed

before_install:
  - if [ ! -e $EB_TOOLS ]; then wget -q -O /tmp/eb.zip https://s3.amazonaws.com/elasticbeanstalk/cli/$EB_VERSION.zip && mkdir -p $EB_TOOLS_DIR && unzip /tmp/eb.zip -d $EB_TOOLS_DIR; fi

before_script:
  - mkdir -p ~/.elasticbeanstalk
  - echo 'AWSAccessKeyId=REMOVED' >> ~/.elasticbeanstalk/aws_credential_file
  - echo 'AWSSecretKey='$AWSSecretKey >> ~/.elasticbeanstalk/aws_credential_file

script:
  - mkdir -p .elasticbeanstalk
  - cp config .elasticbeanstalk/
  - mvn clean
  - mvn test -DRDS_PORT=3306 -DRDS_DB_NAME=test -DRDS_HOSTNAME=localhost -DRDS_PASSWORD= -DRDS_USERNAME=shippable

after_success:
  - mvn compile war:exploded
  - cp -r target/App/* ./
  - git add -f META-INF WEB-INF
  - git commit -m "Deploy"
  - $EB_TOOLS/AWSDevTools/Linux/AWSDevTools-RepositorySetup.sh
  - export PATH=$PATH:$EB_TOOLS/eb/linux/python2.7/ && virtualenv ve && source ve/bin/activate && pip install boto==2.14.0 && eb push
```
