### ISSUE TITLE
CommandError: Problem installing fixture

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#814]
I'm getting this error:

CommandError: Problem installing fixture '/home/shippable/workspace/src/bitbucket': com/oeie/kpics-django/apps/stories/fixtures/focus_areas is not a known serialization format.

Bitbucket username: epicserve
repository: kpics-django
shippable.yml:

``` yaml
build_environment: ubuntu12.04

language: python

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.base

python:
   - "2.7"

install: "pip install -r config/requirements/base.txt 'coverage>=3.7.1,<3.8' 'django-nose>=1.2,<1.3' 'selenium==2.42.1'"

before_script: mkdir -p shippable/codecoverage shippable/testresults

script:
  - ./manage.py test --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage run --source='.' manage.py test
  - coverage xml -i -o shippable/codecoverage/coverage.xml
```

I've also attached a screenshot.

![shippable truly fastest ci in the cloud 2014-11-25 12-44-57](https://cloud.githubusercontent.com/assets/191620/5189148/06e56c10-74a1-11e4-895d-5bdea1e6da0e.jpg)
