### ISSUE TITLE
Error parsing coverage reports.

### ISSUE THREAD

**Issue by silentdth** [Shippable/support#821]
My build is failing due to "Error parsing coverage reports.".

```
save_reports ✓ 0 seconds
 parse_coverage_reports
Error parsing coverage reports.
```

The same build definition succeeded 1 week ago, but does not include the section 'save_reports' in the build - is this a new section?

The build is still pushed to Heroku though even though it failed.

Here is the shippable.yml:

```
language: ruby
ruby: 1.9.3
before_install:
 - bundle install
before_script:
 - psql -c 'CREATE DATABASE test;' -U postgres
 - rake db:migrate
 - rake seed
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - APP_NAME=test

notifications:
 email:
  - test@gmail.com

# include
branches:
  only:
    - master

after_success :
  - git push -f git@heroku.com:$APP_NAME.git master   
```

I think this is due to my `csv` coverage reports are now blank. They have the headers only. 

Posting this in case anybody else has the same problem, I will figure out why the data is blank and post back here.
