### ISSUE TITLE
No bundler available?

### ISSUE THREAD

**Issue by Antronin** [Shippable/support#827]
I've got the following error message when running a build. I dont understand why bundler cannot be run.

```
 bundle install --gemfile="Gemfile"
/home/shippable/build/build.sh: line 88: bundle: command not found
Build completed
Skipping artifact upload
Build completed
```

Below is my shippable.yml config:

``` yaml
build_image: shippableimages/ubuntu1404_ruby

# language setting
language: ruby

# version numbers
rvm:
  - 2.1.2

#activate rvm
before_install:
  - source ~/.rvm/scripts/rvm
  - rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY

#install the dependencies
install:
  - bundle install --gemfile="Gemfile"
  - ruby -v

script:
  - bundle exec rake
  - rspec -f JUnit -o shippable/testresults/results.xml

before_install:
  - apt-get update && apt-get install -y tesseract-ocr libtesseract-dev libtesseract3 libleptonica-dev liblept4 libpq-dev imagemagick libmagickwand-dev libmysqlclient-dev

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

notifications:
  email:
    recipients:
    - antronin@gmail.com

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1 AWS_STACK=... AWS_APP_ID=... AWS_ACCESS_KEY_ID=...
  - secure: ...
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

after_success:
  - virtualenv ve && source ve/bin/activate && pip install awscli
  - aws opsworks create-deployment --stack-id $AWS_STACK --app-id $AWS_APP_ID --command '{"Name":"deploy"}'
```
