### ISSUE TITLE
Shippable builds not being triggered any more.

### ISSUE THREAD

**Issue by ghost** [Shippable/support#840]
Hi, my bitbucket username is asubiotto and here is my shippable.yml:

```
# Setup.
language: python
python:
  - "2.7"

services:
  - elasticsearch

env:
  global:
    - APP_NAME=my-app-name

# Test.
install:
  - pip install -r dev_requirements.txt --use-mirrors

script:
  - ./manage.py test apps

after_success:
  - if [ "$BRANCH" = "master" ]; then git push -f git@heroku.com:$APP_NAME.git master; fi

notifications:
  email:
    recipients:
      - example@example.com
    on_success: always
    on_failure: always
```

My problem is that shippable suddenly stopped automatically building our project although there have been no changes to the shippable.yml file or anything I can see that would relate to shippable's ability to build the project. Additionally, "No PRs" is shown in the Pull Requests tab when there are a few open. Could this be a connection problem between the shippable project and the bitbucket repository?
