### ISSUE TITLE
[FEATURE] Don't delete custom environment variables into docker run of custom image

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#843]
I have a custom image with Dockerfile:

```
ENV MYENVIRONMENT_VAR true
```

Now, I set my custom image in my shippable.yml file and add print to all environment variables:

``` yaml
build_image: myorg/myimage
install: 
- python -c "import os;print os.environ['MYENVIRONMENT_VAR']"
- echo ${MYENVIRONMENT_VAR}
```

I expect have this ENV available into my execution of my docker run.

I saw that this ENVIRONMENT_VAR is empty.

Why I can't use my custom environment variable into shippable build?
