### ISSUE TITLE
Question: Use of Makefile with Golang project

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#850]
I am new to shippable and fairly new to Golang as well.

After mucking about for a couple of hours it appears that any project delcared with language Go causes the `go get` and `go build` command to run.  Specifically I see this:

`shippable_retry go get -d -v ./... && go build -v ./...` 

I do not have any build command yet:

``` yaml
branches:
  only:
  - master
  - develop
language: go
go:
- 1.3
before_install:
- sudo apt-get --assume-yes install bzr
```

So the question is, how do I prevent shippable from using `go build` in lieu of the Makefile and target we want to use?

THanks!
