### ISSUE TITLE
Question:  Coverage report not appearing in the UI

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#851]
Per the example found here:

https://github.com/shippableSamples/sample_ubuntu1204_go/blob/master/shippable.yml

I created a coverage report:

```yaml
before_install:
- sudo apt-get --assume-yes install bzr
- go get github.com/t-yuki/gocover-cobertura
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- go get code.google.com/p/go.tools/cmd/cover
before_script:
- mkdir -p shippable/testresults
- mkdir -p shippable/codecoverage
script:
- go test -coverprofile=coverage.txt -covermode count ./
- $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml
- cat shippable/codecoverage/coverage.xml
- cat ./coverage.txt
- echo "DONE"
```

The report was created as can be seen here:

![screen shot 2014-12-06 at 12 21 50 pm](https://cloud.githubusercontent.com/assets/522972/5328432/ac18813c-7d42-11e4-9579-b0f14bf22068.png)

The XML is there as can be seen here:

![screen shot 2014-12-06 at 12 22 15 pm](https://cloud.githubusercontent.com/assets/522972/5328434/b82a72a0-7d42-11e4-8f89-ddd297f59b4f.png)

However no coverage report exists:

![screen shot 2014-12-06 at 12 24 21 pm](https://cloud.githubusercontent.com/assets/522972/5328436/d5f53982-7d42-11e4-8c61-2d5d108dc271.png)

What am I missing?
