### ISSUE TITLE
apt-get install -y lib32stdc++6 lib32z1 fails for Android build

### ISSUE THREAD

**Issue by jraska** [Shippable/support#890]
Hi, I am trying to build Gradle Android project on Shippable.
I followed the steps here https://github.com/Shippable/support/issues/41 but the command `apt-get install -y lib32stdc++6 lib32z1` is failing with this output:
`
sudo apt-get install -y lib32stdc++6 lib32z1
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libnet-daemon-perl libdbi-perl libterm-readkey-perl libhtml-template-perl
  mysql-client-core-5.5 libdbd-mysql-perl libplrpc-perl mysql-client-5.5
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  lib32gcc1 libc6-i386
The following NEW packages will be installed:
  lib32gcc1 lib32stdc++6 lib32z1 libc6-i386
0 upgraded, 4 newly installed, 0 to remove and 51 not upgraded.
Need to get 4,430 kB of archives.
After this operation, 11.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ precise/main lib32z1 amd64 1:1.2.3.4.dfsg-3ubuntu4 [51.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ precise/main lib32gcc1 amd64 1:4.6.3-1ubuntu5 [54.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ precise/main lib32stdc++6 amd64 4.6.3-1ubuntu5 [333 kB]
Err http://archive.ubuntu.com/ubuntu/ precise-security/main libc6-i386 amd64 2.15-0ubuntu10.7
  404  Not Found [IP: 91.189.92.201 80]
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6-i386_2.15-0ubuntu10.7_amd64.deb  404  Not Found [IP: 91.189.92.201 80]
Fetched 438 kB in 1s (436 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

I found same script here https://github.com/rageshkrishna/test_apt_get/blob/master/shippable.yml

Do you have any idea where is the problem?

My shippable.yml:

```
language: java
jdk:
    - oraclejdk7
install:
    - sudo apt-get install -y lib32stdc++6 lib32z1
    - ./gradlew clean assemble
before_script:
    - mkdir -p shippable/testresults
script:
    - ./gradlew check
after_script:
    - cp -r app/build/test-results/* shippable/testresults/

# whitelist
branches:
    only:
        - master

notifications:
   email: false
```
