### ISSUE TITLE
Builds not triggering from multiple bitbucket branches

### ISSUE THREAD

**Issue by roydq** [Shippable/support#897]
I have two main branches - master and production. They are both listed in my shippable.yml:

``` yaml
branches:
  only:
    - master
    - production
```

However, only master is building. I noticed this in my list of shippable notifications:

```
A build was skipped due to missing branch in webhook for "escortdes/cms"
```

Guess there's something wrong with the bitbucket webhook?
