### ISSUE TITLE
Shippable doesn't work with build matrix

### ISSUE THREAD

**Issue by certik** [Shippable/support#94]
Here is Travis build: https://travis-ci.org/certik/csympy/builds/24274106
Here is Shippable build: https://www.shippable.com/projects/5363ad21c4ccfcb5015126bb

You can see that Shippable is missing the Python 3 builds, there were configured by:

```
matrix:
  include:
    - python: 2.6
      env:
        - BUILD_TYPE="Release" TEST_IN_TREE="yes" WITH_PYTHON="yes" WITH_CSYMPY_RCP="yes" WITH_ECM="yes"
    - python: 3.2
      env:
        - BUILD_TYPE="Release" TEST_IN_TREE="yes" WITH_PYTHON="yes" WITH_CSYMPY_RCP="yes" WITH_ECM="yes"
    - python: 3.3
      env:
        - BUILD_TYPE="Release" TEST_IN_TREE="yes" WITH_PYTHON="yes" WITH_CSYMPY_RCP="yes" WITH_ECM="yes"
```
