### ISSUE TITLE
Multiple builds are run instead of just HEAD vs base

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#940]
I 've got a shippable.yml which states:

```yaml
branches:
  only:
    - testing
    - develop
```

When a push to `testing` and PR is issued from `testing` to `develop` there are two builds run, one for `testing` and one for `develop`.

I would need just one build, one that has merged the PR HEAD against the PR base branch.
