### ISSUE TITLE
Global environment variables are being ignored in node_js project in after_failure: and after_success:

### ISSUE THREAD

**Issue by egorpe** [Shippable/support#952]
I am trying to make HipChat notifications to work. Here is my `shippable.yml`.

```yaml
language: node_js
evn:
  global:
    - PROJECT=project-name
    - HIPCHAT_ROOM=12345
    - secure: DFjvfFwMb5Fbvcobcyb6+YwYVWyOY3ke1+59i/X6He2puVyHyJrIz73AwRbcvYA6AUWwTQC0DAY8Ibi78ot/inDBPSkaaVM1WZt37XJ2meShYCXxzm1gyoSKCoUtUp2NUpxKDVtTAHnYnUB36XRdLBgkCnr+y9opujRjBp8WaSoot541MAqyy+Bie3UYDGHhsvxwvA3F2to4Thbqqokk0c+FHFUAqwrTFyjzHcIGJTC0wCcxPOQakJRCmO8bAjA+3r4m57dNmsctZTH8k0VP6ykL79psjHTzaV6HJSHG6lXk6I58YLARP/KQxhkmgPhoix74ShQ1iHBv8HYYUxIuzg==
notifications:
  email:
    - egorp@eneset.com
script:
  - npm install
  - node_modules/.bin/lineman build
  - node_modules/.bin/lineman grunt deploy
after_failure:
  - python hipchat_notifier.py --project $PROJECT --room $HIPCHAT_ROOM --token $HIPCHAT_TOKEN
after_success:
  - echo $PROJECT
  - echo $HIPCHAT_ROOM
  - echo $HIPCHAT_TOKEN
  - python hipchat_notifier.py --project project-name --room 12345 --token <plain text token goes here> -s
```

Secure section is an encrypted `HIPCHAT_TOKEN`.

When the script is called as in `after_failure:` section, no notifications are being sent.

I added an `echo` statements and simple call to `python hipchat_notifier.py` with plain text parameters.

All output from `echo` commands return empty strings and notification is sent successfully with plain text parameters. So my guess is, `evn/global` section is ignored.
