### ISSUE TITLE
scala builds always succeed - even when tests fail

### ISSUE THREAD

**Issue by bardurdam** [Shippable/support#960]
The generated build script ignores sbt's exit code:

```
script() {
  
  start_cmd_group "script"
  exec_cmd "sbt ++$SHIPPABLE_SCALA_VERSION test"
  end_cmd_group
  
  is_success=true
}
```

But if I override the script from .yml like this:
```
 language: scala
 scala:
   - 2.11.4
 jdk:
   - oraclejdk8

 script:
  - sbt ++$SHIPPABLE_SCALA_VERSION test
```

Then the scripts takes the return code into account:
```
script() {
  
  start_cmd_group "script"
  
  exec_cmd $'sbt ++$SHIPPABLE_SCALA_VERSION test'
  ret=$?
  
  [ "$ret" != 0 ] && return;
  
  end_cmd_group
  
  is_success=true
}
```
