### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by bhargav3** [Shippable/support#995]
I'm using the below config to receive email notifications in my shippable.yml file.
But after a build I'm not receiving any emails.

```
notifications:
  email:
    recipients:
      - builds@domain.com
      - builds2@domain.com
    on_success: change
    on_failure: always
```
